.appveyor.yml, .travis.yml
- from https://github.com/aheninger/icu-trunk-exp
=> ICU-20032: re-enable Travis and Appveyor  config

icu4c/source/i18n/numfmt.cpp
Improve the handling of out-of-memory (OOM) errors in the NumberFormat class.
=> ICU-20044 Improve OOM handling in NumberFormat class

.github/pull_request_template.md
=> ICU-20003: add a PR template

icu4c/source/tools/pkgdata/pkgdata.cpp
=> ICU-13138 fix ICU data binary naming for builds with Static layout

icu4c/source/common/static_unicode_sets.cpp, icu4c/source/i18n/number_decimfmtprops.cpp
Should fix possible crashes on ARM platforms.
=> ICU-20001 Adding alignas to static-allocated memory.

icu4c/source/common/bytestriebuilder.cpp, icu4c/source/common/uniset.cpp, icu4c/source/common/usprep.cpp, icu4c/source/io/ufmt_cmn.cpp, icu4c/source/test/intltest/numrgts.cpp, icu4c/source/test/iotest/iotest.cpp
=> ICU-20079 integer overflow & divide by zero sanitizer fixes.

icu4c/source/Makefile.in
=> ICU-20061 fix 'rm: cannot remove 'current'' warning during build

icu4j/build.xml
=> ICU-13413 Java 7 for Javadoc build (#68).

icu4c/source/i18n/gregocal.cpp, icu4c/source/i18n/gregoimp.h
=> ICU-20079 int overflow in Gregorian Calendar.

icu4c/source/test/testdata/rbbitst.txt, icu4j/main/tests/core/src/com/ibm/icu/dev/test/rbbi/rbbitst.txt
=> ICU-13664 RBBI, add regression test for reported problem. #80

.travis.yml
=> ICU-11637 Thread sanitizer added to Travis build.

icu4c/source/common/ucptrie_impl.h, icu4c/source/common/umutablecptrie.cpp, icu4c/source/common/unicode/ucptrie.h, icu4c/source/common/unicode/umutablecptrie.h, icu4c/source/test/cintltst/ucptrietest.c, icu4j/main/classes/core/src/com/ibm/icu/util/CodePointMap.java, icu4j/main/classes/core/src/com/ibm/icu/util/CodePointTrie.java, icu4j/main/classes/core/src/com/ibm/icu/util/MutableCodePointTrie.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/CodePointTrieTest.java
=> ICU-13530 fix bugs, add tests, clarify docs

icu4j/main/classes/core/src/com/ibm/icu/text/DecimalFormat.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/NumberFormatTest.java
Document the exception in the following methods
setMultiplier, setMathContext, setMathContextICU
=> ICU-13808 Document ArithmeticException thrown by DecimalFormat

icu4c/source/runConfigureICU
No tests or documentation needs changing.  Tested locally on Windows in Debug mode.
=> ICU-20027: Support parallel builds with MSYS/MSVC and Cygwin/MSVC

icu4c/source/common/putilimp.h, icu4c/source/common/ucnv.cpp
=> ICU-13834 add pinCapacity() for safer output buffer capacity checking.

icu4j/main/classes/core/src/com/ibm/icu/text/Edits.java
=> ICU-20116 remove @deprecated from Edits.Iterator.toString()

icu4c/source/common/bytesinkutil.cpp, icu4c/source/common/bytesinkutil.h
This is an implementation of the public ICU ByteSink interface that
writes to the ICU internal class CharString.
=> ICU-13417 Add the internal helper class CharStringByteSink.

icu4j/main/classes/core/src/com/ibm/icu/text/BreakIterator.java, icu4j/main/classes/core/src/com/ibm/icu/text/RuleBasedBreakIterator.java
=> ICU-13801 Clarify Javadoc for BreakIterator.setText()

.travis.yml
=> ICU-20119 Small refactor to ICU4J travis file.

icu4c/source/common/locid.cpp, icu4c/source/common/unicode/locid.h, icu4c/source/test/depstest/dependencies.txt, icu4c/source/test/intltest/loctest.cpp, icu4c/source/test/intltest/loctest.h
They are C++ wrappers of uloc_addLikelySubtags() and uloc_minimizeSubtags()
respectively, that take care of dynamic memory management.
=> ICU-13417 Add the Locale::(addLikely|minimize)Subtags() functions.

icu4c/source/i18n/indiancal.cpp, icu4c/source/i18n/indiancal.h, icu4c/source/test/intltest/tsmthred.cpp, icu4c/source/test/intltest/tsmthred.h
=> ICU-20104 Fix lazy init in Indian Calendar. Now matches other calendars.

icu4c/source/i18n/decimfmt.cpp, icu4c/source/test/intltest/numfmtst.cpp, icu4j/main/classes/core/src/com/ibm/icu/text/DecimalFormat.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/NumberFormatTest.java
=> ICU-20063 Make setSignificantDigitsUsed more friendly.

.cpyskip.txt, .travis.yml, tools/scripts/cpysearch/Cpy.pm, tools/scripts/cpysearch/cpyscan.pl
- name the travis build steps
- copy cpyskip.txt to /.cpyskip.txt
- add one named "lint" which runs cpyscan.pl
- remove network access from Cpy.pm (requires installation)
=> ICU-20066 add a copyright scan stage

icu4j/main/classes/core/src/com/ibm/icu/text/MeasureFormat.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/MeasureUnitTest.java
=> ICU-13824 Fixing MeasureFormat#getWidth() to not return @internal value.

icu4j/main/classes/core/src/com/ibm/icu/text/NumberFormat.java
=> ICU-13266 Clarifying documentation for NumberFormat#equals().

icu4c/source/i18n/numparse_impl.cpp, icu4c/source/test/intltest/numfmtst.cpp, icu4c/source/test/intltest/numfmtst.h, icu4j/main/classes/core/src/com/ibm/icu/impl/number/parse/NumberParserImpl.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/NumberFormatTest.java
=> ICU-20073 Do not parse stray percent sign in strict mode.

icu4c/source/i18n/unicode/msgfmt.h, icu4j/main/classes/core/src/com/ibm/icu/text/MessageFormat.java
This is only a documentation fix, so not code / tests updated.
=> ICU-20142: Document the skeleton for MessageFormat number arguments

icu4c/source/i18n/unicode/numberformatter.h, icu4c/source/i18n/unicode/unumberformatter.h
=> ICU-20154 Renaming UGroupingStrategy to UNumberGroupingStrategy.

icu4c/source/i18n/numrange_impl.cpp, icu4c/source/test/intltest/numbertest_range.cpp, icu4j/main/classes/core/src/com/ibm/icu/number/NumberRangeFormatterImpl.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberRangeFormatterTest.java
One small improvement I noticed.
=> ICU-11276 Apply the approximately pattern inside of the unit string.

icu4c/source/common/unicode/ubidi.h, icu4j/main/classes/core/src/com/ibm/icu/text/Bidi.java, icu4j/main/classes/core/src/com/ibm/icu/text/BidiClassifier.java
=> ICU-20125 numeric values of level constants will not change; fix/update some docs

icu4c/source/common/characterproperties.cpp
otherwise includes entry points that should not be included.
=> ICU-20119 Remove C linkage declaration; urename.h BRS-update script

icu4c/source/Doxyfile.in, icu4c/source/common/unicode/icuplug.h, icu4c/source/common/unicode/utext.h, icu4c/source/i18n/reldtfmt.h, icu4c/source/i18n/unicode/decimfmt.h, icu4c/source/i18n/unicode/smpdtfmt.h, icu4c/source/i18n/unicode/udat.h, icu4c/source/i18n/unicode/unum.h, icu4c/source/i18n/unicode/upluralrules.h, icu4c/source/layoutex/layout/playout.h, icu4c/source/layoutex/layout/plruns.h, icu4c/source/test/intltest/colldata.h
This reverts commit 25f1589466c8b74ce36d762d4e9f3a72b3007eaf in #8
=> ICU-13685: Revert #8 c: add @preview (retry)

icu4c/source/common/uloc_tag.cpp
=> ICU-20168 Fix memory leak in error path, add a free statement.

icu4j/tools/build/icu4j53.api3.gz, icu4j/tools/build/icu4j63.api3.gz
Added ICU4J 63 API signature file, removed one for ICU4J 53
=> ICU-20119 BRS63RC Add ICU4J API signature file

icu4c/APIChangeReport.html, icu4c/source/common/ulocimp.h, icu4c/source/common/unicode/bytestream.h, icu4c/source/common/unicode/casemap.h, icu4c/source/common/unicode/edits.h, icu4c/source/common/unicode/filteredbrk.h, icu4c/source/common/unicode/locid.h, icu4c/source/common/unicode/normalizer2.h, icu4c/source/common/unicode/stringoptions.h, icu4c/source/common/unicode/uchar.h, icu4c/source/common/unicode/ucpmap.h, icu4c/source/common/unicode/uenum.h, icu4c/source/common/unicode/utf16.h, icu4c/source/i18n/reldtfmt.h, icu4c/source/i18n/unicode/currunit.h, icu4c/source/i18n/unicode/dcfmtsym.h, icu4c/source/i18n/unicode/numfmt.h, icu4c/source/i18n/unicode/rbnf.h, tools/release/java/src/com/ibm/icu/dev/tools/docs/StableAPI.java
=> ICU-20119 ICU 63 API promotion & change report

icu4j/readme.html
=> ICU-20119 BRS63RC Updated ICU4J README for 63RC

icu4c/readme.html, icu4j/build.properties, icu4j/readme.html
=> ICU-20120 BRS63GA: Update version numbers/readme for ICU 63 GA.

icu4j/readme.html
Just updating API change report link from svn to local.
=> ICU-20120 BRS63GA Updating ICU4J 63 readme.html

icu4j/maven/icu4j-charset/pom.xml, icu4j/maven/icu4j-localespi/pom.xml, icu4j/maven/icu4j/pom.xml, icu4j/readme.html
=> ICU-20120 cherry pick ICU4J pom fix and readme update for 63GA

.travis.yml
=> ICU-20120 Travis TSAN testing, limit time. Cherry Pick to maint-63

tools/commit-checker/.gitignore, tools/commit-checker/Pipfile, tools/commit-checker/README.md, tools/commit-checker/check.py
=> ICU-20166 Adding commit-checker tool.

icu4c/source/i18n/unicode/numberrangeformatter.h
=> ICU-20214 Fix namespace error on Cygwin

icu4c/source/common/unicode/unistr.h
=> ICU-20212 unistr.h, use markdown for API docs

icu4c/source/test/testdata/numberformattestspecification.txt, icu4j/main/tests/core/src/com/ibm/icu/dev/data/numberformattestspecification.txt
=> ICU-11511 Adding tests for CLDR-10103 scientific notation spec changes.

icu4c/source/i18n/japancal.cpp
=> ICU-20240 Fix Windows build failure in japancal.cpp

icu4c/source/common/uloc_tag.cpp
The shared templated helper class MemoryPool is a drop-in replacement
for the local helper class CharStringPool, with a simpler implementation
and an interface that allows parameters to be passed to the constructor.
=> ICU-20202 Replace CharStringPool with MemoryPool.

icu4c/source/common/normalizer2impl.h, icu4c/source/extra/uconv/uwmsg.c, icu4c/source/i18n/listformatter.cpp, icu4c/source/test/cintltst/cbiditst.c, icu4c/source/test/cintltst/cloctst.c, icu4c/source/test/cintltst/cnumtst.c, icu4c/source/test/intltest/punyref.cpp, icu4c/source/test/intltest/transapi.cpp, icu4c/source/test/intltest/transrt.cpp, icu4c/source/tools/toolutil/ucmstate.cpp
=> ICU-20159 Fixing gcc warnings in project and test code.

icu4c/source/common/putilimp.h, icu4c/source/common/umutex.cpp, icu4c/source/common/umutex.h
=> ICU-10183 ICU Mutexes, add a C++11 std::mutex based implementation.

icu4c/source/i18n/fmtable.cpp, icu4c/source/i18n/number_decimalquantity.cpp, icu4c/source/test/intltest/numfmtst.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/number/DecimalQuantity_AbstractBCD.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/DecimalQuantity_DualStorageBCD.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/NumberFormatTest.java
=> ICU-20246 Fixing another integer overflow in number parsing.

.travis.yml
=> ICU-20172 Add dependency checker to Travis CI

icu4c/source/i18n/number_decimalquantity.cpp, icu4c/source/i18n/number_decimalquantity.h, icu4c/source/i18n/number_integerwidth.cpp, icu4c/source/i18n/number_rounding.cpp, icu4c/source/test/intltest/numbertest_decimalquantity.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/number/DecimalQuantity.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/DecimalQuantity_AbstractBCD.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/DecimalQuantity_DualStorageBCD.java, icu4j/main/classes/core/src/com/ibm/icu/number/NumberFormatterImpl.java, icu4j/main/classes/core/src/com/ibm/icu/number/Precision.java, icu4j/main/tests/core/src/com/ibm/icu/dev/impl/number/DecimalQuantity_64BitBCD.java, icu4j/main/tests/core/src/com/ibm/icu/dev/impl/number/DecimalQuantity_ByteArrayBCD.java, icu4j/main/tests/core/src/com/ibm/icu/dev/impl/number/DecimalQuantity_SimpleStorage.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/DecimalQuantityTest.java
=> ICU-13701 Internal cleanup in DecimalQuantity

icu4c/source/i18n/number_decimalquantity.cpp, icu4c/source/i18n/number_decimalquantity.h, icu4c/source/i18n/number_mapper.cpp, icu4c/source/i18n/number_patternstring.cpp, icu4c/source/i18n/number_rounding.cpp, icu4c/source/i18n/number_roundingutils.h, icu4c/source/i18n/number_skeletons.cpp, icu4c/source/i18n/number_utils.cpp, icu4c/source/i18n/unicode/numberformatter.h, icu4c/source/test/intltest/numbertest_api.cpp, icu4c/source/test/intltest/numbertest_decimalquantity.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/number/DecimalQuantity_AbstractBCD.java, icu4j/main/classes/core/src/com/ibm/icu/number/Precision.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
=> ICU-13701 Optimizing increment rounding: check for nickel sooner.

icu4c/source/common/static_unicode_sets.h, icu4c/source/test/intltest/numbertest_api.cpp
=> ICU-13267 Minor documentation and test changes.

.ci-builds/.azure-pipelines.yml, .cpyskip.txt
=> ICU-20215 Convert the VSTS/Azure CI builds definitions to a YML file in the repo.

icu4c/source/common/umutex.cpp, icu4c/source/common/umutex.h
=> ICU-20185 Remove U_USER_ATOMICS_H, U_USER_MUTEX_H, U_USER_MUTEX_CPP

icu4c/source/common/characterproperties.cpp, icu4c/source/common/ucptrie.cpp, icu4c/source/common/umutablecptrie.cpp, icu4c/source/common/unicode/uniset.h, icu4c/source/common/uniset.cpp, icu4c/source/common/uniset_closure.cpp, icu4c/source/common/uniset_props.cpp, icu4c/source/common/uprops.h, icu4c/source/common/uset.cpp, icu4c/source/common/usetiter.cpp, icu4c/source/test/intltest/convtest.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/CharacterPropertiesImpl.java, icu4j/main/classes/core/src/com/ibm/icu/text/UnicodeSet.java, icu4j/main/classes/core/src/com/ibm/icu/text/UnicodeSetIterator.java, icu4j/main/classes/core/src/com/ibm/icu/util/CodePointTrie.java, icu4j/main/classes/core/src/com/ibm/icu/util/MutableCodePointTrie.java
Cherry-pick from master to maint/maint-63.
https://unicode-org.atlassian.net/browse/ICU-20250
=> ICU-20250 make UnicodeSet(intprop=value) faster

icu4c/source/i18n/number_longnames.cpp, icu4c/source/i18n/number_stringbuilder.cpp, icu4c/source/i18n/number_stringbuilder.h, icu4c/source/i18n/unicode/numfmt.h, icu4c/source/i18n/unicode/unum.h, icu4c/source/test/cintltst/unumberformattertst.c, icu4c/source/test/depstest/dependencies.txt, icu4c/source/test/intltest/numbertest.h, icu4c/source/test/intltest/numbertest_api.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/number/LongNameHandler.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/NumberStringBuilder.java, icu4j/main/classes/core/src/com/ibm/icu/text/NumberFormat.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
=> ICU-13267 Implementing MeasureUnit field.

icu4c/source/common/characterproperties.cpp, icu4c/source/common/ucln_cmn.cpp, icu4c/source/common/ucnv_bld.cpp, icu4c/source/common/ucnvmbcs.cpp, icu4c/source/common/umutex.cpp, icu4c/source/common/umutex.h, icu4c/source/common/unifiedcache.cpp, icu4c/source/common/ustr_cnv.cpp, icu4c/source/i18n/astro.cpp, icu4c/source/i18n/chnsecal.cpp, icu4c/source/i18n/gender.cpp, icu4c/source/i18n/islamcal.cpp, icu4c/source/i18n/numfmt.cpp, icu4c/source/i18n/reldatefmt.cpp, icu4c/source/i18n/translit.cpp, icu4c/source/i18n/zonemeta.cpp, icu4c/source/io/locbund.cpp, icu4c/source/test/intltest/simplethread.cpp, icu4c/source/test/intltest/simplethread.h
=> ICU-20179 Remove platform-specific Mutex & Atomic implementations.

.ci-builds/.azure-pipelines.yml
=> ICU-10923 Disable the VS2015 build until the Azure VM image has a working Python 3

icu4c/source/test/intltest/numfmtst.cpp, icu4c/source/test/intltest/numfmtst.h, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/NumberFormatTest.java
=> ICU-20186 Adding test for semicolon spacing in DecimalFormat.

icu4j/main/tests/core/src/com/ibm/icu/dev/test/rbbi/RBBIMonkeyTest.java
=> ICU-20288 add line_cj.txt to RBBI Monkey test.

icu4c/source/data/BUILDRULES.py, icu4c/source/data/buildtool/__init__.py, icu4c/source/data/buildtool/__main__.py, icu4c/source/data/buildtool/renderers/makefile.py, icu4c/source/data/buildtool/utils.py, icu4c/source/test/testdata/BUILDRULES.py
This PR contains refactoring changes to the Python build tools that are required for the sibling PR for the actual data filtering (#301).
Each commit is a single bite-size change.  I suggest looking at each commit individually.  I did work to make sure each commit is readable on its own.
=> ICU-10923 Refactoring BUILDRULES.py in preparation for data filtering.

icu4c/source/configure, icu4c/source/configure.ac, icu4c/source/data/BUILDRULES.py, icu4c/source/data/buildtool/__init__.py, icu4c/source/data/buildtool/__main__.py, icu4c/source/data/buildtool/filtration.py, icu4c/source/data/buildtool/utils.py, icu4c/source/test/cintltst/cdattst.c, icu4c/source/test/intltest/dtfmttst.cpp, icu4c/source/test/intltest/numfmtst.cpp
=> ICU-10923 Data Slicing Phase 2

.travis.yml, icu4c/source/configure, icu4c/source/configure.ac, icu4c/source/data/BUILDRULES.py, icu4c/source/data/buildtool/__main__.py, icu4c/source/data/buildtool/filtration.py, icu4c/source/data/buildtool/renderers/makefile.py, icu4c/source/data/buildtool/utils.py
=> ICU-20299 Adds Python 2.7 support to data build script.

icu4c/source/common/patternprops.cpp, icu4c/source/common/patternprops.h, icu4c/source/i18n/msgfmt.cpp, icu4c/source/i18n/unicode/msgfmt.h, icu4c/source/test/intltest/tmsgfmt.cpp, icu4c/source/test/intltest/tmsgfmt.h, icu4j/main/classes/core/src/com/ibm/icu/text/MessageFormat.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/TestMessageFormat.java
=> ICU-9622 Adding support for date/time skeletons

icu4c/source/common/wintz.h
Follow on from PR #315. Thanks to Jungshik for catching this.
=> ICU-20302 Fix wintz header file. (Windows 7 time zone detection)

.appveyor.yml
=> ICU-20317 Cache the Cygwin Setup.exe on AppVeyor CI builds to prevent flaky failures

icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/XLocaleMatcherTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/data/localeMatcherTest.txt
=> ICU-20329 XLocaleMatcher new test data format, parameterized test, more test cases

.ci-builds/.azure-pipelines.yml
=> ICU-20324 Add MSYS2 (Windows) build bot to the Azure CI builds (GCC x86_64).

icu4c/source/i18n/erarules.h, icu4c/source/i18n/number_decimfmtprops.h, icu4c/source/i18n/number_patternmodifier.h
=> ICU-20325 Fix MSYS2 GCC warnings about unknown pragma (Windows).

icu4j/main/classes/core/src/com/ibm/icu/impl/number/DecimalQuantity_AbstractBCD.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/DecimalQuantityTest.java
=> ICU-13701 Use exact string-to-double conversion in Java.

icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/DecimalQuantityTest.java
=> ICU-13701 Removing obsolete logKnownIssue since bug is fixed.

icu4c/source/allinone/Build.Windows.PlatformToolset.props
=> ICU-13653 Quiet warnings about output target when building with MSVC

icu4c/source/common/cmemory.h, icu4c/source/i18n/currunit.cpp, icu4c/source/i18n/number_formatimpl.cpp, icu4c/source/i18n/unicode/currunit.h, icu4c/source/test/depstest/dependencies.txt, icu4c/source/test/intltest/numfmtst.cpp
=> ICU-20183 Adding CurrencyUnit StringPiece constructor.

.travis.yml, icu4c/as_is/bomlist.py, icu4c/source/test/depstest/dependencies.py, icu4c/source/test/depstest/depstest.py, icu4c/source/tools/icu-file-utf8-check.py
Test: Execute every python script with python 2 and 3
=> ICU-20334 Add python3 support for tools

icu4c/source/common/umutex.h
=> ICU-20323 Suppress MSYS2 GCC warning about std::atomic visibility (Windows)

icu4c/source/i18n/number_patternstring.cpp, icu4c/source/test/intltest/numfmtst.cpp, icu4c/source/test/intltest/numfmtst.h, icu4j/main/classes/core/src/com/ibm/icu/impl/number/PatternStringUtils.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/NumberFormatTest.java
=> ICU-20358 Clean up grouping resolution in DecimalFormat#toPattern().

icu4c/source/common/utrie2_builder.cpp
This is a redo of PR #358, since I initially committed to the wrong branch.
Note: This new PR has the changes suggested by Andy in the comment on the other PR.
=> ICU-20369 ICU4C: Report OOM errors in the utrie2_clone function.

.travis.yml, icu4c/source/common/unicode/uvernum.h
=> ICU-20089 Add ICU4C Docs build to Travis CI

icu4c/source/common/uloc.cpp, icu4c/source/test/cintltst/cloctst.c
=> ICU-20370 Fix error checking in uloc_getLCID function.

icu4c/source/i18n/number_capi.cpp, icu4c/source/i18n/number_fluent.cpp, icu4c/source/i18n/number_skeletons.cpp, icu4c/source/i18n/number_skeletons.h, icu4c/source/i18n/numparse_types.h, icu4c/source/i18n/unicode/numberformatter.h, icu4c/source/i18n/unicode/unumberformatter.h, icu4c/source/test/cintltst/unumberformattertst.c, icu4c/source/test/intltest/numbertest_skeletons.cpp, icu4c/source/test/intltest/numbertest_stringsegment.cpp, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberSkeletonTest.java
=> ICU-13657 Adding NumberFormatter skeleton factory method with UParseError.

icu4c/source/test/intltest/numbertest_api.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/number/LongNameHandler.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
This just add more unit tests.
=> ICU-20355 Add unit test for simply USD currency case.

icu4c/source/configure, icu4c/source/configure.ac, icu4c/source/data/BUILDRULES.py, icu4c/source/data/buildtool/__main__.py, icu4c/source/data/buildtool/renderers/common_exec.py, icu4c/source/data/buildtool/renderers/unix_exec.py, icu4c/source/data/buildtool/renderers/windows_exec.py, icu4c/source/data/makedata.mak, icu4c/source/test/testdata/testdata.mak
- Renames --format flag to --mode.
- Renames windirect to windows-exec.
=> ICU-10923 Adding unix-exec mode to buildtool and updating help page.

icu4c/source/allinone/Build.Windows.Library.ProjectConfiguration.props, icu4c/source/allinone/Build.Windows.Library.WarningSettings.ProjectConfiguration.props, icu4c/source/allinone/Build.Windows.PlatformToolset.props
=> ICU-20200 Treat select compiler warnings as errors in the ICU4C library code (with MSVC)

icu4c/source/allinone/Build.Windows.Library.WarningSettings.ProjectConfiguration.props, icu4c/source/allinone/Build.Windows.PlatformToolset.props
Thanks @daniel-ju for noticing this.
=> ICU-20200 Fix mistaken move of MSB8012 warning suppression from Shared props file to Library only props file.

icu4c/source/test/fuzzer/locale_fuzzer.cc, icu4c/source/test/fuzzer/locale_util.cc, icu4c/source/test/fuzzer/locale_util.h, icu4c/source/test/fuzzer/uloc_canonicalize_fuzzer.cc, icu4c/source/test/fuzzer/uloc_canonicalize_fuzzer_seed_corpus.zip, icu4c/source/test/fuzzer/uloc_for_language_tag_fuzzer.cc, icu4c/source/test/fuzzer/uloc_for_language_tag_fuzzer_seed_corpus.zip, icu4c/source/test/fuzzer/uloc_get_name_fuzzer.cc, icu4c/source/test/fuzzer/uloc_get_name_fuzzer_seed_corpus.zip, icu4c/source/test/fuzzer/uloc_is_right_to_left_fuzzer.cc, icu4c/source/test/fuzzer/uloc_is_right_to_left_fuzzer_seed_corpus.zip, icu4c/source/test/fuzzer/uloc_open_keywords_fuzzer.cc, icu4c/source/test/fuzzer/uloc_open_keywords_seed_fuzzer_corpus.zip
=> ICU-20217 Adds additional ICU4C fuzzer targets

icu4c/source/i18n/unicode/msgfmt.h, icu4j/main/classes/core/src/com/ibm/icu/text/MessageFormat.java
=> ICU-9622 Update documentation for MessageFormat and skeletons

icu4c/source/data/cldr-icu-readme.txt
=> ICU-20395 Fix cldr-icu-readme.txt to not mention whitelist

.travis.yml
=> ICU-20376 Add out-of-source build testing to Travis.

icu4c/packaging/distrelease.ps1
=> ICU-20002 Modify Windows 'distrelease.ps1' for 32-bit (x86) builds

icu4c/source/test/testdata/BUILDRULES.py
=> ICU-10923 Fixing warning in testdata build file.

icu4c/source/common/uloc_tag.cpp, icu4c/source/test/cintltst/cloctst.c, icu4c/source/test/intltest/loctest.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/locale/LanguageTag.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/ULocaleTest.java
=> ICU-20320 Fix the missing digit singleton extension

icu4j/main/classes/core/src/com/ibm/icu/util/BytesTrie.java, icu4j/main/classes/core/src/com/ibm/icu/util/CharsTrie.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/BytesTrieTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/CharsTrieTest.java
https://unicode-org.atlassian.net/browse/ICU-20373
=> ICU-20373 simpler state saving for Java string tries via long not object

icu4c/source/i18n/formattedval_iterimpl.cpp, icu4c/source/i18n/listformatter.cpp, icu4c/source/i18n/ulistformatter.cpp, icu4c/source/i18n/unicode/listformatter.h, icu4c/source/i18n/unicode/ulistformatter.h, icu4c/source/test/cintltst/ulistfmttest.c, icu4c/source/test/intltest/formattedvaluetest.cpp, icu4c/source/test/intltest/listformattertest.cpp, icu4c/source/test/intltest/listformattertest.h
=> ICU-20121 Implementing FormattedList.

icu4c/source/i18n/numparse_impl.cpp, icu4c/source/i18n/numparse_impl.h, icu4c/source/i18n/numparse_parsednumber.cpp, icu4c/source/i18n/numparse_types.h, icu4c/source/test/intltest/numbertest.h, icu4c/source/test/intltest/numbertest_parse.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/number/parse/NumberParserImpl.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/parse/ParsingUtils.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberParserTest.java
=> ICU-20360 Testing and fixing stack overflow in numparse.

icu4c/source/i18n/formattedval_impl.h
=> ICU-20138 Copy fErrorCode in FormattedValue subclass macro.

icu4c/source/i18n/formattedvalue.cpp, icu4c/source/i18n/unicode/formattedvalue.h, icu4c/source/i18n/unicode/uformattedvalue.h
=> ICU-20378 Changing APIs for UFieldCategory to int32_t.

icu4c/source/test/perf/DateFmtPerf/DateFmtPerf.vcxproj, icu4c/source/test/perf/charperf/charperf.vcxproj, icu4c/source/test/perf/collationperf/collperf.cpp, icu4c/source/test/perf/collperf/collperf.vcxproj, icu4c/source/test/perf/collperf2/collperf2.vcxproj, icu4c/source/test/perf/convperf/convperf.cpp, icu4c/source/test/perf/convperf/convperf.vcxproj, icu4c/source/test/perf/normperf/normperf.h, icu4c/source/test/perf/normperf/normperf.vcxproj, icu4c/source/test/perf/strsrchperf/strsrchperf.vcxproj, icu4c/source/test/perf/ubrkperf/ubrkperf.vcxproj, icu4c/source/test/perf/ucnvavailperf/ucnvavailperf.vcxproj, icu4c/source/test/perf/unisetperf/unisetperf.vcxproj, icu4c/source/test/perf/usetperf/usetperf.vcxproj, icu4c/source/test/perf/ustrperf/stringperf.vcxproj, icu4c/source/test/perf/utfperf/utfperf.vcxproj, icu4c/source/test/perf/utrie2perf/utrie2perf.vcxproj
=> ICU-13789 ICU-20387 ICU4C PerfTest does not build, Upgrade various *.vcxproj files

icu4c/source/common/simpleformatter.cpp, icu4c/source/common/unicode/simpleformatter.h, icu4c/source/i18n/dtitvfmt.cpp, icu4c/source/i18n/formattedval_impl.h, icu4c/source/i18n/formattedval_iterimpl.cpp, icu4c/source/i18n/fphdlimp.cpp, icu4c/source/i18n/fphdlimp.h, icu4c/source/i18n/udateintervalformat.cpp, icu4c/source/i18n/unicode/dtitvfmt.h, icu4c/source/i18n/unicode/dtitvinf.h, icu4c/source/i18n/unicode/smpdtfmt.h, icu4c/source/i18n/unicode/udateintervalformat.h, icu4c/source/i18n/unicode/uformattedvalue.h, icu4c/source/test/cintltst/cdateintervalformattest.c, icu4c/source/test/intltest/dtifmtts.cpp, icu4c/source/test/intltest/dtifmtts.h, icu4c/source/test/intltest/simpleformattertest.cpp
This PR includes the C and C++ implementations.  See the test files for an example call site.
=> ICU-20342 Implementing FormattedDateInterval in ICU4C.

icu4c/source/tools/genrb/parse.cpp
Correcting corner case in early return.
=> ICU-11991 Fixed memory leak in parse.cpp

icu4c/source/i18n/calendar.cpp
=> ICU-20416 OOM not handled in calendar.cpp in some places

icu4c/source/data/buildtool/__init__.py
=> ICU-10923 Remove unused variable AVAILABLE_FEATURES.

icu4c/source/i18n/formattedval_impl.h, icu4c/source/i18n/formattedvalue.cpp, icu4c/source/i18n/unicode/formattedvalue.h, icu4c/source/i18n/unicode/uformattedvalue.h, icu4c/source/test/cintltst/uformattedvaluetst.c, icu4c/source/test/intltest/formattedvaluetest.cpp, icu4j/main/classes/core/src/com/ibm/icu/text/ConstrainedFieldPosition.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/FormattedValueTest.java
=> ICU-20138 Adding matchesField as draft and removing getConstraintType.

icu4c/source/i18n/unicode/listformatter.h, icu4c/source/i18n/unicode/ulistformatter.h
=> ICU-20121 Fixing docs tags in FormattedList.

icu4c/source/i18n/listformatter.cpp, icu4c/source/i18n/unicode/listformatter.h, icu4c/source/i18n/unicode/uformattedvalue.h, icu4c/source/i18n/unicode/ulistformatter.h, icu4c/source/test/cintltst/ulistfmttest.c, icu4c/source/test/intltest/listformattertest.cpp
=> ICU-20121 Adding span field for FormattedList.

icu4j/main/classes/core/src/com/ibm/icu/impl/number/NumberStringBuilder.java, icu4j/main/classes/core/src/com/ibm/icu/text/ConstrainedFieldPosition.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/FormattedValueTest.java
=> ICU-20138 Adding a tech-preview API, constrainFieldAndValue, and updating matchhesField.

icu4c/source/common/uloc.cpp, icu4c/source/test/cintltst/cloctst.c, icu4c/source/test/intltest/loctest.cpp, icu4c/source/test/intltest/loctest.h, icu4j/main/classes/core/src/com/ibm/icu/util/ULocale.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/ULocaleTest.java
=> ICU-20407 hy-arevela/hy-arevmda canonicalize into hy / hyw

icu4c/source/i18n/decimfmt.cpp, icu4c/source/i18n/number_fluent.cpp, icu4c/source/i18n/unicode/decimfmt.h, icu4c/source/test/intltest/dcfmapts.cpp
=> ICU-20380 Adding error code to DecimalFormat::toNumberFormatter().

icu4c/source/i18n/formattedval_impl.h, icu4c/source/i18n/number_asformat.cpp, icu4c/source/i18n/number_capi.cpp, icu4c/source/i18n/number_fluent.cpp, icu4c/source/i18n/number_output.cpp, icu4c/source/i18n/number_utypes.h, icu4c/source/i18n/numrange_fluent.cpp, icu4c/source/i18n/numrange_impl.cpp, icu4c/source/i18n/numrange_impl.h, icu4c/source/i18n/plurfmt.cpp, icu4c/source/i18n/quantityformatter.cpp, icu4c/source/i18n/smpdtfmt.cpp, icu4c/source/i18n/unicode/dtitvfmt.h, icu4c/source/i18n/unicode/listformatter.h, icu4c/source/i18n/unicode/numberformatter.h, icu4c/source/i18n/unicode/numberrangeformatter.h, icu4c/source/i18n/unicode/reldatefmt.h, icu4c/source/i18n/unicode/unumberformatter.h, icu4c/source/test/cintltst/unumberformattertst.c, icu4c/source/test/depstest/dependencies.txt, icu4j/main/classes/core/src/com/ibm/icu/impl/Utility.java, icu4j/main/classes/core/src/com/ibm/icu/number/FormattedNumber.java, icu4j/main/classes/core/src/com/ibm/icu/text/RelativeDateTimeFormatter.java
This is part 1 of 2.  I will send part 2 after part 1 is checked in.
=> ICU-20409 Additional FormattedValue implementation refactoring.

icu4c/source/common/static_unicode_sets.cpp, icu4c/source/common/static_unicode_sets.h, icu4c/source/i18n/numparse_symbols.cpp, icu4c/source/test/intltest/numbertest_parse.cpp, icu4c/source/test/intltest/static_unisets_test.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/StaticUnicodeSets.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/parse/InfinityMatcher.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/ExhaustiveNumberTest.java
Can you think of a good way to add unit tests for this without duplicating all of the data loading code into the test suite?
=> ICU-20108 Adding new parseLenients from CLDR 34 to ICU.

icu4c/source/i18n/unicode/numberformatter.h, icu4c/source/i18n/unicode/numberrangeformatter.h, icu4j/main/classes/core/src/com/ibm/icu/number/FormattedNumber.java, icu4j/main/classes/core/src/com/ibm/icu/number/FormattedNumberRange.java, icu4j/main/classes/core/src/com/ibm/icu/number/LocalizedNumberFormatter.java, icu4j/main/classes/core/src/com/ibm/icu/number/LocalizedNumberRangeFormatter.java, icu4j/main/classes/core/src/com/ibm/icu/number/NumberFormatter.java, icu4j/main/classes/core/src/com/ibm/icu/number/NumberRangeFormatter.java, icu4j/main/classes/core/src/com/ibm/icu/number/UnlocalizedNumberFormatter.java, icu4j/main/classes/core/src/com/ibm/icu/number/UnlocalizedNumberRangeFormatter.java
=> ICU-20313 Adding more docs about thread-safety of Number[Range]Formatter.

icu4c/source/configure, icu4c/source/configure.ac
=> ICU-10923 Configure should fail when Python fails.

.gitignore, icu4c/source/i18n/unicode/listformatter.h, icu4c/source/test/intltest/listformattertest.cpp, icu4c/source/test/intltest/listformattertest.h, icu4j/main/classes/core/src/com/ibm/icu/text/ListFormatter.java, icu4j/main/classes/core/src/com/ibm/icu/text/MeasureFormat.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/ListFormatterTest.java
=> ICU-10675 ListFormatter bad / outdated documentation

icu4j/main/classes/core/src/com/ibm/icu/impl/FormattedValueFieldPositionIteratorImpl.java, icu4j/main/classes/core/src/com/ibm/icu/impl/SimpleFormatterImpl.java, icu4j/main/classes/core/src/com/ibm/icu/impl/Utility.java, icu4j/main/classes/core/src/com/ibm/icu/text/DateIntervalFormat.java, icu4j/main/classes/core/src/com/ibm/icu/text/SimpleDateFormat.java, icu4j/main/classes/core/src/com/ibm/icu/text/UFormat.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/DateIntervalFormatTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/FormattedValueTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/serializable/FormatHandler.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/serializable/SerializableTestUtility.java
=> ICU-20342 FormattedDateInterval, Java.

icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberRangeFormatterTest.java
Consider looking at #440 first.
=> ICU-20144 Adding test for range pattern consistency.

icu4c/source/i18n/number_formatimpl.cpp, icu4c/source/i18n/number_formatimpl.h, icu4c/source/i18n/number_microprops.h, icu4c/source/i18n/numrange_impl.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/number/MicroProps.java, icu4j/main/classes/core/src/com/ibm/icu/number/NumberFormatterImpl.java, icu4j/main/classes/core/src/com/ibm/icu/number/NumberRangeFormatterImpl.java
There is no locale with data where I can test this behavior; see #438.
=> ICU-20144 Implementing numsys-dependent range pattern loading.

icu4c/source/common/unicode/ucurr.h, icu4j/main/classes/core/src/com/ibm/icu/util/Currency.java
=> ICU-20284 Updating docs on mutability of currency fraction digits.

icu4c/source/i18n/numparse_affixes.cpp, icu4c/source/i18n/numparse_affixes.h
=> ICU-20254 Handling OOM in AffixTokenMatcherWarehouse.

icu4c/source/i18n/uregex.cpp
=> ICU-20415 uregex_start64() and end64() truncation.

icu4c/source/configure, icu4c/source/configure.ac, icu4c/source/data/BUILDRULES.py, icu4c/source/data/buildtool/__init__.py, icu4c/source/data/buildtool/__main__.py, icu4c/source/data/buildtool/filtration_schema.json, icu4c/source/data/buildtool/request_types.py, icu4c/source/data/buildtool/utils.py, icu4c/source/data/makedata.mak, icu4c/source/test/testdata/testdata.mak
=> ICU-10923 Adding file replacement mechanism to buildtool.

icu4c/source/test/intltest/restsnew.cpp, icu4c/source/test/testdata/filters/filtertest.txt, icu4c/source/test/testdata/filtertest.txt, icu4c/source/tools/genrb/filterrb.cpp, icu4c/source/tools/genrb/filterrb.h, icu4c/source/tools/genrb/genrb.cpp
=> ICU-10923 Adding wildcard resource matching.

.ci-builds/.azure-exhaustive-tests.yml
This adds a separate YML file for the Exhaustive Tests configuration so that the Azure Pipelines build can be run separately from the regular PR builds.
Once this is added, we can decided if we want to run this on every single PR, or just on the master branch on scheduled builds.
=> ICU-20243 Add YML file for Exhaustive Tests in the CI builds.

.travis.yml, icu4c/source/test/intltest/tsmthred.cpp
=> ICU-20197 ICU4C Multithreaded tests cleanup

icu4c/source/common/putil.cpp
Change-Id: I61042ca66f86457768e8fc0315137051013d2820
Signed-off-by: Semun Lee <semun.lee@samsung.com>
=> ICU-20345 Skip ahead some files in searchForTZFile

icu4c/source/i18n/number_formatimpl.cpp, icu4c/source/test/intltest/numbertest.h, icu4c/source/test/intltest/numbertest_api.cpp, icu4c/source/test/intltest/numbertest_decimalquantity.cpp, icu4j/main/classes/core/src/com/ibm/icu/number/NumberFormatterImpl.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/ExhaustiveNumberTest.java
=> ICU-20417 Parity between NoUnit and MeasureUnit Percent.

icu4j/main/classes/charset/manifest.stub
=> ICU-20326 Added Export-Package OSGi header in charset.jar

icu4c/source/i18n/formattedval_iterimpl.cpp, icu4c/source/test/cintltst/cnumtst.c, icu4c/source/test/intltest/localebuildertest.cpp
=> ICU-20351 A few more MSVC warning cleanups. (Mostly adding static_cast)

icu4c/source/samples/datefmt/main.cpp, icu4c/source/samples/numfmt/util.cpp, icu4c/source/samples/props/props.cpp, icu4c/source/samples/udata/writer.c, icu4c/source/samples/ustring/ustring.cpp
=> ICU-20438 BRS64RC Fix compiler warnings in ICU4C samples

icu4j/APIChangeReport.html, icu4j/build.properties, icu4j/main/classes/core/src/com/ibm/icu/text/ConstrainedFieldPosition.java, icu4j/main/classes/core/src/com/ibm/icu/text/CurrencyDisplayNames.java, icu4j/main/classes/core/src/com/ibm/icu/text/DateTimePatternGenerator.java, icu4j/main/classes/core/src/com/ibm/icu/util/Currency.java
Also includes API tag fixes. build.properties was updated for producing API change report.
=> ICU-20438 API status promotion for ICU4J 64

icu4c/LICENSE, icu4j/main/shared/licenses/LICENSE
=> ICU-20438 Update LICENSE file

icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/ListFormatterTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/RelativeDateTimeFormatterTest.java
=> ICU-20438 Fixed eclipse compiler warnings

icu4c/readme.html, icu4j/readme.html
=> ICU-20438 ICU 64RC BRS - Update readme files.

icu4c/source/i18n/unicode/dtitvfmt.h, icu4c/source/i18n/unicode/listformatter.h, icu4c/source/i18n/unicode/numberformatter.h, icu4c/source/i18n/unicode/numberrangeformatter.h, icu4c/source/i18n/unicode/reldatefmt.h
(Produced warnings in V8 build system.)
=> ICU-20452 Removing extra semicolons from public header files.

icu4c/source/common/unicode/localebuilder.h, icu4c/source/common/unicode/localpointer.h, icu4c/source/i18n/unicode/currunit.h, icu4c/source/i18n/unicode/decimfmt.h, icu4c/source/i18n/unicode/dtptngen.h, icu4c/source/i18n/unicode/formattedvalue.h, icu4c/source/i18n/unicode/measunit.h, icu4c/source/i18n/unicode/nounit.h, icu4c/source/i18n/unicode/numberformatter.h, icu4c/source/i18n/unicode/numsys.h, icu4c/source/i18n/unicode/plurrule.h, icu4c/source/i18n/unicode/reldatefmt.h, icu4c/source/i18n/unicode/uformattedvalue.h, icu4c/source/i18n/unicode/unum.h, icu4c/source/i18n/unicode/upluralrules.h, icu4c/source/i18n/unicode/ureldatefmt.h
=> ICU-20438 64rc BRS, update U_HIDE_ conditionals

icu4c/source/test/intltest/measfmttest.cpp
=> ICU-20438 Removing old logKnownIssue fixed by ICU-13591

icu4c/source/test/hdrtst/testinternalheaders.sh
=> ICU-20438 Adds fuzzer directory to testinternalheaders.sh

icu4c/APIChangeReport.html, icu4c/source/common/unicode/localebuilder.h, icu4c/source/common/unicode/ucurr.h, icu4c/source/common/unicode/utf8.h, icu4c/source/common/unicode/utypes.h, icu4c/source/i18n/number_fluent.cpp, icu4c/source/i18n/number_grouping.cpp, icu4c/source/i18n/number_skeletons.cpp, icu4c/source/i18n/number_skeletons.h, icu4c/source/i18n/unicode/dtptngen.h, icu4c/source/i18n/unicode/formattedvalue.h, icu4c/source/i18n/unicode/measunit.h, icu4c/source/i18n/unicode/numberformatter.h, icu4c/source/i18n/unicode/numfmt.h, icu4c/source/i18n/unicode/udatpg.h, icu4c/source/i18n/unicode/unumberformatter.h, tools/release/java/build.xml, tools/release/java/readme.txt
=> ICU-20438 ICU 64 C API promotion.

tools/commit-checker/README.md, tools/commit-checker/check.py
=> ICU-20438 Improving commit report instructions and efficiency.

icu4c/source/configure, icu4c/source/configure.ac, icu4c/source/data/BUILDRULES.py, icu4c/source/data/Makefile.in, icu4c/source/data/buildtool/__main__.py, icu4c/source/data/icu4j-readme.txt, icu4c/source/data/makedata.mak
=> ICU-20460 Adding mechanism to build unicore data into dat file.

icu4c/source/common/characterproperties.cpp, icu4c/source/i18n/listformatter.cpp, icu4c/source/test/intltest/listformattertest.h
=> ICU-20438 Fixes issues found during BRS configuration test task.

tools/commit-checker/README.md, tools/commit-checker/check.py
Additional changes after #498.
=> ICU-20438 Further updating readme and instructions for commit-checker.

icu4c/source/common/unicode/docmain.h
=> ICU-20438 Updating index page of C docs with new APIs and fixing links.

icu4j/main/classes/core/src/com/ibm/icu/impl/locale/LanguageTag.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/ULocaleTest.java
=> ICU-20148 fix dup variant and dup ext singleton

icu4c/source/i18n/regexcmp.cpp, icu4c/source/test/intltest/regextst.cpp, icu4c/source/test/intltest/regextst.h
=> ICU-20359 Fix stack overflow in Regex Pattern Compile.

icu4c/source/data/BUILDRULES.py, icu4c/source/data/buildtool/filtration.py, icu4c/source/data/buildtool/request_types.py
- Includes other minor cleanup of buildtool.
=> ICU-20472 Moving index res file request to tree category.

icu4c/source/configure, icu4c/source/configure.ac, icu4c/source/data/makedata.mak, icu4c/source/icudefs.mk.in, icu4c/source/test/testdata/testdata.mak
- similar to ICU-20062, add a `-B` option to the two python invocations
- also to a test case
=> ICU-20479 don’t leave junk in source directory on configure or check

docs/userguide/format_parse/numbers/skeletons.md, icu4c/source/i18n/number_skeletons.cpp, icu4c/source/test/intltest/numbertest.h, icu4c/source/test/intltest/numbertest_api.cpp, icu4c/source/test/intltest/numbertest_skeletons.cpp, icu4j/main/classes/core/src/com/ibm/icu/number/NumberSkeletonImpl.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberSkeletonTest.java
Also fixes a minor bug in the syntax and adds tests.
=> ICU-20469 Adding user guide for number skeletons.

icu4c/source/common/unicode/unistr.h
=> ICU-13709 fix shadow param inside #ifdef

icu4j/main/classes/core/src/com/ibm/icu/text/PluralRules.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/PluralRulesTest.java
=> ICU-20264 FixedDecimal.toString locale independent

icu4c/source/i18n/unicode/numberformatter.h, icu4c/source/i18n/unicode/numberrangeformatter.h
=> ICU-20463 Use copybrief for children that are older than parents.

icu4c/source/data/Makefile.in, icu4c/source/data/cldr-icu-readme.txt
=> ICU-20439 Updating cldr-icu-readme.txt to reflect changes in eac8f4b.

icu4c/source/data/unidata/changes.txt, icu4c/source/data/unidata/norm2/uts46.txt, icu4c/source/test/testdata/IdnaTestV2.txt, icu4j/main/tests/core/src/com/ibm/icu/dev/data/unicode/IdnaTestV2.txt
https://unicode-org.atlassian.net/browse/ICU-20203
=> ICU-20203 Unicode 12 final data (only trivial changes)

icu4c/source/common/uidna.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/IDNA2003.java
=> ICU-10291 Optimize IDNA toASCII loop

icu4j/main/tests/core/src/com/ibm/icu/dev/test/lang/UCharacterCaseTest.java
=> ICU-11094 Add test to ensure fixing of ICU-11094

.ci-builds/.azure-exhaustive-tests.yml
=> ICU-20496 Run the Exhaustive Tests on "maint" branches as well.

icu4c/source/i18n/number_compact.cpp, icu4c/source/i18n/number_longnames.cpp, icu4c/source/i18n/number_patternmodifier.cpp, icu4c/source/i18n/number_patternmodifier.h, icu4c/source/i18n/number_utils.h, icu4c/source/test/intltest/numbertest.h, icu4c/source/test/intltest/numbertest_api.cpp, icu4c/source/test/intltest/numbertest_patternmodifier.cpp, icu4c/source/test/intltest/numfmtst.cpp, icu4c/source/test/intltest/numfmtst.h, icu4j/main/classes/core/src/com/ibm/icu/impl/number/LongNameHandler.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/MutablePatternModifier.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/RoundingUtils.java, icu4j/main/classes/core/src/com/ibm/icu/number/CompactNotation.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/NumberFormatTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
=> ICU-20499 Fixing code path for plural form in MutablePatternModifier.

icu4j/main/classes/core/src/com/ibm/icu/text/DateIntervalFormat.java
=> ICU-20492 Fixing final declarations in DateIntervalFormat.java

docs/userguide/icu_data/buildtool.md
=> ICU-20469 Adding data build tool debugging tips

icu4c/readme.html, icu4c/source/data/icu4j-readme.txt, icu4j/build.properties, icu4j/main/shared/data/icudata.jar, icu4j/main/shared/data/icutzdata.jar, icu4j/main/shared/data/testdata.jar, icu4j/readme.html
=> ICU-20439 BRS64GA Update version number and regenerate JAR files

docs/userguide/icu_data/buildtool.md
=> ICU-20469 Fixing typo: locale_tree -> locales_tree

icu4c/source/data/buildtool/__main__.py, icu4c/source/data/buildtool/filtration_schema.json
I added an option to the config file.  Do you prefer also removing the command-line flag?
=> ICU-20473 Adding collation ucadata option to filter file.

icu4c/source/tools/genrb/filterrb.cpp, icu4c/source/tools/genrb/filterrb.h
=> ICU-20507 Adding virtual destructor to PathFilter

docs/userguide/icu_data/buildtool.md
=> ICU-20469 Updating how to control ucadata type in userguide.

icu4c/source/i18n/fmtable.cpp, icu4c/source/i18n/number_decimalquantity.cpp, icu4c/source/test/intltest/numbertest_api.cpp, icu4c/source/test/intltest/numfmtst.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/number/DecimalQuantity_AbstractBCD.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/DecimalQuantity_DualStorageBCD.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/NumberFormatTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
=> ICU-20494 Fixes to very large magnitude exponents in number parsing.

icu4c/source/i18n/numsys.cpp, icu4c/source/i18n/unicode/numberformatter.h, icu4c/source/i18n/unicode/numsys.h, icu4c/source/i18n/unicode/reldatefmt.h, icu4c/source/test/hdrtst/cxxfiles.txt
=> ICU-20439 Fix internal and draft headers.

icu4c/APIChangeReport.html
=> ICU-20439 API Change Report for ICU 64 regenerated.

icu4j/build.xml
https://unicode-org.atlassian.net/browse/ICU-20509
=> ICU-20509 Add dependencies on langdata, regiondata to packagingCheck.

icu4c/source/configure, icu4c/source/configure.ac
=> ICU-20528 Fill in testdata/rules.mk when there is no Python.

icu4j/build.xml
=> ICU-20539 Use https:// for JDK doc link in javadoc task

icu4c/readme.html, icu4j/readme.html
=> ICU-20515 ICU 64.2 BRS Update readme files

icu4j/tools/build/icu4j64.api3.gz
=> ICU-20439 Update ICU4J API signature file for 64.1 GA

icu4c/source/common/localsvc.h, icu4c/source/common/rbbi.cpp, icu4c/source/common/ubidiwrt.cpp, icu4c/source/common/unicode/uvernum.h, icu4c/source/i18n/decNumberLocal.h, icu4c/source/i18n/timezone.cpp, icu4c/source/test/intltest/idnaconf.cpp, icu4c/source/test/intltest/uobjtest.cpp, icu4c/source/tools/toolutil/ucbuf.cpp
=> ICU-20543 Fix -Wundef in library and test code.

tools/commit-checker/README.md, tools/commit-checker/check.py
Maybe should put this on a different ticket number because I opened this PR against master and the ticket is for ICU 64.2.
=> ICU-20553 Updating commit checker instructions and making --rev-range required.

icu4c/source/common/bytesinkutil.h, icu4c/source/i18n/tzfmt.cpp, icu4c/source/i18n/tzgnames.cpp, icu4c/source/i18n/tznames_impl.cpp
=> ICU-20445 Pass ByteSink to ulocimp_addLikelySubtags().

.travis.yml, icu4c/source/test/intltest/formatted_string_builder_test.cpp
https://unicode-org.atlassian.net/browse/ICU-20572
=> ICU-20572 build & test with U_NO_DEFAULT_INCLUDE_UTF_HEADERS

icu4c/source/data/buildtool/__main__.py, icu4c/source/data/buildtool/renderers/common_exec.py, icu4c/source/data/buildtool/renderers/unix_exec.py, icu4c/source/data/buildtool/renderers/windows_exec.py
=> ICU-20593 Buildtool: adding some options and improving exec mode.

icu4c/source/data/buildtool/__main__.py, icu4c/source/data/buildtool/filtration.py, icu4c/source/data/buildtool/filtration_schema.json
=> ICU-20593 Buildtool: Implementing new "additive" mode.

icu4c/source/data/BUILDRULES.py, icu4c/source/data/buildtool/request_types.py
=> ICU-20529 Generate res_index on partial resource trees.

icu4c/source/i18n/unicode/msgfmt.h, icu4j/main/classes/core/src/com/ibm/icu/text/MessageFormat.java
=> ICU-20591 Increased the date rowspan to include the argSkeletonText line

icu4c/packaging/distrelease.ps1
=> ICU-20567 Use 7Zip to package Windows binaries on CI build bots

icu4c/source/common/locdspnm.cpp, icu4c/source/test/intltest/locnmtst.cpp, icu4c/source/test/intltest/locnmtst.h
=> ICU-12760 support UDISPCTX_TYPE_SUBSTITUTE_HANDLING

icu4c/source/common/localebuilder.cpp, icu4c/source/common/unicode/localebuilder.h, icu4c/source/test/intltest/localebuildertest.cpp
=> ICU-20602 add LocaleBuilder::copyErrorTo

icu4c/source/common/ubidiimp.h
=> ICU-20641 Fixes undefined-shift

icu4c/source/test/intltest/dtptngts.cpp, icu4j/main/classes/core/src/com/ibm/icu/text/DateTimePatternGenerator.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/DateTimeGeneratorTest.java
We discovered this issue when integrating #660.
=> ICU-20629 DTPG: Fixing uncaught exception in Java.

docs/userguide/icu_data/buildtool.md, icu4c/source/python/icutools/databuilder/__main__.py
=> ICU-20593 ICU Data Build Tool documentation updates.

icu4c/source/data/makedata.mak
=> ICU-20658 Fix broken Data Filtering on Windows builds.

.travis.yml, docs/userguide/icu_data/buildtool.md, docs/userguide/icu_data/tracing.md, icu4c/source/common/Makefile.in, icu4c/source/common/common.vcxproj, icu4c/source/common/common.vcxproj.filters, icu4c/source/common/common_uwp.vcxproj, icu4c/source/common/resource.h, icu4c/source/common/restrace.cpp, icu4c/source/common/restrace.h, icu4c/source/common/udata.cpp, icu4c/source/common/unicode/utrace.h, icu4c/source/common/uresbund.cpp, icu4c/source/common/uresdata.cpp, icu4c/source/common/uresdata.h, icu4c/source/common/utrace.cpp, icu4c/source/test/depstest/dependencies.txt, icu4c/source/test/intltest/intltest.cpp, icu4c/source/test/intltest/intltest.h, icu4c/source/test/intltest/restsnew.cpp, icu4c/source/test/intltest/restsnew.h, icu4c/source/tools/toolutil/pkgitems.cpp
=> ICU-20593 Trace instrumentation for resource loading.

icu4c/source/test/intltest/numfmtst.cpp, icu4c/source/test/intltest/numfmtst.h, icu4j/main/classes/core/src/com/ibm/icu/text/NumberFormatServiceShim.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/NumberFormatTest.java
=> ICU-20631 Fix desired currency not set for some NumberFormat currency styles

.gitignore
=> ICU-20527 Fix some incorrect entires in the top-level .gitignore file

icu4c/source/i18n/measfmt.cpp, icu4c/source/i18n/unicode/measfmt.h, icu4c/source/test/intltest/measfmttest.cpp, icu4j/main/classes/core/src/com/ibm/icu/text/MeasureFormat.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/MeasureUnitTest.java
=> ICU-20622 Fixing several MeasureFormat problems

docs/userguide/icu_data/buildtool.md, icu4c/source/common/udata.cpp
=> ICU-20593 Data docs tweaks and fixing UDATA_DEBUG build.

docs/userguide/icu_data/buildtool.md, icu4c/source/data/BUILDRULES.py, icu4c/source/python/icutools/databuilder/__main__.py, icu4c/source/python/icutools/databuilder/filtration_schema.json
=> ICU-20660 Add usePoolBundle option to filters.json.

icu4c/source/common/uloc_tag.cpp, icu4c/source/test/cintltst/cloctst.c, icu4c/source/test/cintltst/cloctst.h
=> ICU-20149 allow duplicate unicode attribute

icu4c/source/data/brkitr/rules/word.txt, icu4c/source/data/brkitr/rules/word_POSIX.txt, icu4j/main/shared/data/icudata.jar
=> ICU-20404 Simplify word break rules.

icu4c/source/i18n/measfmt.cpp
=> ICU-20622 Removing dead code in measfmt.cpp.

docs/processes/rules_update.md, icu4c/source/data/brkitr/rules/README.md, icu4c/source/test/testdata/break_rules/README.md
=> ICU-13637 Documentation for doing break iterator updates.

icu4c/source/i18n/formatted_string_builder.cpp, icu4c/source/i18n/formatted_string_builder.h, icu4c/source/i18n/measfmt.cpp, icu4c/source/test/intltest/formatted_string_builder_test.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/FormattedStringBuilder.java, icu4j/main/classes/core/src/com/ibm/icu/text/MeasureFormat.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/FormattedStringBuilderTest.java
=> ICU-20666 Adding insert/appendChar16 to FormattedStringBuilder.

.travis.yml, icu4c/source/common/cmemory.h, icu4c/source/common/uarrsort.cpp, icu4c/source/common/ucnv.cpp, icu4c/source/common/ucnv2022.cpp, icu4c/source/common/ucnvhz.cpp, icu4c/source/common/utext.cpp, icu4c/source/test/cintltst/ccapitst.c, icu4c/source/test/depstest/dependencies.txt, icu4c/source/test/intltest/uobjtest.cpp, icu4c/source/tools/toolutil/toolutil.cpp
=> ICU-20048 remove uses of UAlignedMemory

icu4c/source/common/uarrsort.cpp
=> ICU-20650 Memory Alignment in quickSort() function.

icu4c/source/common/ucptrie.cpp, icu4c/source/i18n/listformatter.cpp, icu4c/source/test/cintltst/ccaltst.c, icu4c/source/test/cintltst/cloctst.c, icu4c/source/test/cintltst/cnumtst.c, icu4c/source/test/intltest/caltest.cpp, icu4c/source/test/intltest/datadrivennumberformattestsuite.cpp, icu4c/source/test/intltest/rbbitst.cpp, icu4c/source/test/intltest/transrt.cpp
=> ICU-20672 Compiler Warning Cleanup.

.ci-builds/data-filter.json, icu4c/source/python/icutools/databuilder/request_types.py
=> ICU-20593 Data slicing: Fix mixed file and resource filter.

icu4c/source/python/icutools/databuilder/filtration_schema.json
=> ICU-20593 Data slicing: allow more characters in res filter rules.

icu4c/source/common/umutex.cpp
=> ICU-20689 Fix race condition in UMutex code, leading to random crashes.

icu4c/source/tools/genccode/genccode.c, icu4c/source/tools/pkgdata/pkgdata.cpp, icu4c/source/tools/toolutil/pkg_genc.cpp, icu4c/source/tools/toolutil/pkg_genc.h
=> ICU-20716 Fixing some buffer overruns in genccode

.gitignore
=> ICU-20675 ignore .vscode configuration files.

icu4c/source/common/ucnv.cpp
=> ICU-20048 Remove use of std::align() for compat with g++ 4.9.

icu4c/source/i18n/unicode/utrans.h
=> ICU-20757 Fix typos in utrans.h public header file.

icu4c/source/test/intltest/Makefile.in, icu4c/source/test/intltest/intltest.cpp, icu4c/source/test/intltest/intltest.h, icu4c/source/test/intltest/intltest.vcxproj, icu4c/source/test/intltest/intltest.vcxproj.filters, icu4c/source/test/intltest/numbertest.h, icu4c/source/test/intltest/numbertest_permutation.cpp, icu4c/source/test/testdata/numberpermutationtest.txt, icu4j/main/classes/core/src/com/ibm/icu/number/Precision.java, icu4j/main/tests/core/src/com/ibm/icu/dev/data/numberpermutationtest.txt, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberPermutationTest.java
Adds a test suite in C++ and Java to test many permutations of options in NumberFormatter.
=> ICU-13743 Adding number permutation test.

icu4c/source/i18n/compactdecimalformat.cpp, icu4c/source/i18n/decimfmt.cpp, icu4c/source/i18n/number_mapper.h
=> ICU-20394 Changing DecimalFormatFields to not allocate as many objects

docs/userguide/icu_data/buildtool.md, icu4c/source/python/icutools/databuilder/filtration.py, icu4c/source/python/icutools/databuilder/filtration_schema.json, icu4c/source/test/intltest/restsnew.cpp, icu4c/source/test/testdata/filters/filtertest.txt, icu4c/source/test/testdata/filtertest.txt, icu4c/source/tools/genrb/filterrb.cpp
=> ICU-20764 Allow top-level include and exclude in data filter rules.

icu4c/source/common/unicode/utypes.h
=> ICU-20685 Improving docs for UErrorCode.

.ci-builds/data-filter.json, docs/userguide/icu_data/buildtool.md, icu4c/source/python/icutools/databuilder/__main__.py, icu4c/source/python/icutools/databuilder/filtration_schema.json, icu4c/source/python/icutools/databuilder/request_types.py, icu4c/source/python/icutools/databuilder/utils.py
Also fixes some bugs with file replacement.
=> ICU-20524 Adding variables for relative file replacement directory.

icu4c/source/i18n/unicode/dtptngen.h, icu4j/main/classes/core/src/com/ibm/icu/text/DateTimePatternGenerator.java
=> ICU-20771 Fix incorrect documentation tag for DateTimePatternGenerator

icu4c/source/common/unicode/uobject.h
=> ICU-20422 Redefining U_NO_THROW to U_NOEXCEPT

icu4c/source/i18n/number_decnum.h, icu4c/source/i18n/number_output.cpp, icu4c/source/i18n/number_utils.cpp, icu4c/source/i18n/unicode/numberformatter.h, icu4c/source/i18n/unicode/unumberformatter.h, icu4c/source/test/intltest/numbertest.h, icu4c/source/test/intltest/numbertest_api.cpp
=> ICU-20562 Adding toDecimalNumber method to C++ FormattedNumber.

icu4c/source/common/edits.cpp, icu4c/source/common/unicode/edits.h
https://unicode-org.atlassian.net/browse/ICU-20646
=> ICU-20646 make Edits::copyErrorTo() const

icu4c/source/i18n/smpdtfmt.cpp, icu4c/source/test/intltest/dtfmttst.cpp, icu4c/source/test/intltest/dtfmttst.h
=> ICU-20799 delete calendarToAdopt upon error

icu4c/source/test/intltest/erarulestest.cpp, icu4j/main/tests/core/src/com/ibm/icu/dev/test/calendar/EraRulesTest.java
=> ICU-20589 Fix EraRulesTest#testAPIs failure on 1 May 2019

icu4c/source/common/uloc.cpp
=> ICU-20802 OOM not handled in uloc_openKeywordList

icu4c/source/common/unicode/uchar.h
https://unicode-org.atlassian.net/browse/ICU-20518
=> ICU-20518 update u_isbase() reference to Unicode Standard Base character

README.md
=> ICU-20269 Update the CI badges in the top-level README file.

icu4j/main/classes/core/src/com/ibm/icu/number/NumberFormatterImpl.java, icu4j/main/classes/core/src/com/ibm/icu/number/NumberRangeFormatterImpl.java, icu4j/main/classes/core/src/com/ibm/icu/text/RelativeDateTimeFormatter.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/DateIntervalFormatTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/FormattedStringBuilderTest.java
=> ICU-20795 BRS65 Clean up import statements

icu4j/main/classes/core/src/com/ibm/icu/util/ByteArrayWrapper.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/UtilityTest.java
https://unicode-org.atlassian.net/browse/ICU-11976
=> ICU-11976 test & fix ByteArrayWrapper.hashCode()

icu4j/APIChangeReport.html, icu4j/main/classes/core/src/com/ibm/icu/lang/CharacterProperties.java, icu4j/main/classes/core/src/com/ibm/icu/number/CompactNotation.java, icu4j/main/classes/core/src/com/ibm/icu/number/CurrencyPrecision.java, icu4j/main/classes/core/src/com/ibm/icu/number/FormattedNumber.java, icu4j/main/classes/core/src/com/ibm/icu/number/FormattedNumberRange.java, icu4j/main/classes/core/src/com/ibm/icu/number/FractionPrecision.java, icu4j/main/classes/core/src/com/ibm/icu/number/IntegerWidth.java, icu4j/main/classes/core/src/com/ibm/icu/number/LocalizedNumberFormatter.java, icu4j/main/classes/core/src/com/ibm/icu/number/LocalizedNumberRangeFormatter.java, icu4j/main/classes/core/src/com/ibm/icu/number/Notation.java, icu4j/main/classes/core/src/com/ibm/icu/number/NumberFormatter.java, icu4j/main/classes/core/src/com/ibm/icu/number/NumberFormatterSettings.java, icu4j/main/classes/core/src/com/ibm/icu/number/NumberRangeFormatter.java, icu4j/main/classes/core/src/com/ibm/icu/number/NumberRangeFormatterSettings.java, icu4j/main/classes/core/src/com/ibm/icu/number/Precision.java, icu4j/main/classes/core/src/com/ibm/icu/number/Scale.java, icu4j/main/classes/core/src/com/ibm/icu/number/ScientificNotation.java, icu4j/main/classes/core/src/com/ibm/icu/number/SimpleNotation.java, icu4j/main/classes/core/src/com/ibm/icu/number/SkeletonSyntaxException.java, icu4j/main/classes/core/src/com/ibm/icu/number/UnlocalizedNumberFormatter.java, icu4j/main/classes/core/src/com/ibm/icu/number/UnlocalizedNumberRangeFormatter.java, icu4j/main/classes/core/src/com/ibm/icu/text/DecimalFormat.java, icu4j/main/classes/core/src/com/ibm/icu/text/SpoofChecker.java, icu4j/main/classes/core/src/com/ibm/icu/util/CodePointMap.java, icu4j/main/classes/core/src/com/ibm/icu/util/CodePointTrie.java, icu4j/main/classes/core/src/com/ibm/icu/util/LocaleMatcher.java, icu4j/main/classes/core/src/com/ibm/icu/util/MeasureUnit.java, icu4j/main/classes/core/src/com/ibm/icu/util/MutableCodePointTrie.java
- Updating API status version for ICU4J 65 release
- Fixed a few minor API doc issues in DecimalFormat and LocaleMatcher
=> ICU-20795 BRS65 ICU4J API status promotion

icu4j/tools/build/icu4j55.api3.gz, icu4j/tools/build/icu4j65.api3.gz
Deleted ICU4J 55 API signature file
=> ICU-20795 BRS65 ICU4J 65 API signature file

.gitignore
=> ICU-20793 ignore binary file from git  

icu4c/APIChangeReport.html, icu4c/APIChangeReport.md, icu4c/source/common/unicode/locid.h, icu4c/source/common/unicode/uchar.h, icu4c/source/common/unicode/ucpmap.h, icu4c/source/common/unicode/ucptrie.h, icu4c/source/common/unicode/umutablecptrie.h, icu4c/source/common/unicode/utrace.h, icu4c/source/i18n/unicode/decimfmt.h, icu4c/source/i18n/unicode/formattedvalue.h, icu4c/source/i18n/unicode/listformatter.h, icu4c/source/i18n/unicode/numberformatter.h, icu4c/source/i18n/unicode/numberrangeformatter.h, icu4c/source/i18n/unicode/reldatefmt.h, icu4c/source/i18n/unicode/ulistformatter.h, icu4c/source/i18n/unicode/unumberformatter.h, icu4c/source/i18n/unicode/uspoof.h
[ICU-20795]
- includes a fix to UTRACE_UDATA_BUNDLE which missed @draft
- includes new APIChangeReport.md
- the 'simplification' section is no longer new
- Note: uses tools from [ICU-20162] #807
- fix locid.h from comments
[ICU-20795]: https://unicode-org.atlassian.net/browse/ICU-20795
[ICU-20162]: https://unicode-org.atlassian.net/browse/ICU-20162
=> ICU-20795 ICU4C 65 API promotion

icu4c/source/common/ucnvsel.cpp
=> ICU-20804 OOM not handled in selectForMask

icu4c/source/common/unicode/bytestrie.h, icu4c/source/common/unicode/localebuilder.h, icu4c/source/common/unicode/ucharstrie.h, icu4c/source/common/unicode/uniset.h, icu4c/source/i18n/unicode/calendar.h, icu4c/source/i18n/unicode/dcfmtsym.h, icu4c/source/i18n/unicode/dtptngen.h, icu4c/source/i18n/unicode/formattedvalue.h, icu4c/source/i18n/unicode/numberformatter.h, icu4c/source/i18n/unicode/numberrangeformatter.h, icu4c/source/i18n/unicode/plurfmt.h, icu4c/source/i18n/unicode/ulistformatter.h
=> ICU-20796 BRS 65 update C API guard macros (manual version)

docs/userguide/icu_data/buildtool.md, icu4c/source/python/icutools/databuilder/filtration.py
=> ICU-20811 Add fields required for locale inheritance to additive mode.

.ci-builds/.azure-pipelines.yml, icu4c/packaging/distrelease.ps1
=> ICU-20825 Add ARM64 to distrelease.ps1 script, and run in the CI builds

icu4c/source/test/intltest/numfmtst.cpp, icu4c/source/test/intltest/numfmtst.h, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/NumberFormatTest.java
=> ICU-13735 Adding tests for DecimalFormat grouping getters

icu4c/source/data/cldr-icu-readme.txt, icu4c/source/data/misc/metadata.txt, icu4c/source/data/misc/supplementalData.txt, icu4j/main/shared/data/icudata.jar, icu4j/main/shared/data/icutzdata.jar, icu4j/main/shared/data/testdata.jar
Integrate CLDR release-36-beta; for ICU this mainly involves some changes to subdivision containment and deprecation (and a change to the integration process which is hopefully temporary, to be fixed on CLDR side)
=> ICU-20796 brs65 integrate cldr release-36-beta

.ci-builds/.azure-pipelines.yml, icu4c/source/test/intltest/strtest.cpp, icu4c/source/test/intltest/strtest.h
=> ICU-20453 Add more warning types to CI build.

icu4c/source/common/umutex.cpp, icu4c/source/common/umutex.h
https://unicode-org.atlassian.net/browse/ICU-20845
=> ICU-20845 UMutex not trivially but constexpr constructible

tools/commit-checker/README.md
=> ICU-20835 Update instructions for commit checker.

tools/commit-checker/check.py
=> ICU-20835 Updating check.py to work with CLDR

README.md
Add as per instructions at
https://google.github.io/oss-fuzz/getting-started/new-project-guide/#status-badge
=> ICU-20855 Add OSS-Fuzz fuzzing badge

icu4c/source/i18n/dtitvinf.cpp, icu4c/source/test/intltest/dtifmtts.cpp, icu4c/source/test/intltest/dtifmtts.h, icu4c/source/test/intltest/restsnew.cpp, icu4c/source/test/intltest/restsnew.h, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/DateIntervalFormatTest.java
This PR has only the test, but now fix
=> ICU-20706 Fix DateInterval::createInstance w/ test

icu4c/source/test/intltest/rbbitst.cpp
=> ICU-20728 Improve debug output for old C++ RBBI monkey test

icu4c/source/tools/pkgdata/pkgdata.cpp
=> ICU-20850 Use LocalMemory for cmd to prevent use-after-free issue

docs/userguide/icu_data/buildtool.md
=> ICU-20841 Update buildtool docs according to user feedback.

icu4c/source/i18n/unicode/numberformatter.h
=> ICU-20872 remove extra ; after function {}

icu4c/source/common/uloc.cpp
=> ICU-20884 initialized buffer uloc_getKeywordValue

tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/PathMatcher.java, tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/mapper/LocaleMapper.java, tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/mapper/RbnfMapper.java
Just pulling out some tidy ups from the upcoming PR for dependency graphs.
=> ICU-20693 Quick tidy of some stale/broken comments

tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/DependencyGraph.java, tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/LdmlConverter.java
Dependency graph support for writing JSON files with parent and alias mappings in (for the build process).
=> ICU-20693 Supporting dependency graph generation (first draft)

tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/LdmlConverter.java
The current code doesn't quite handle forced parent IDs correctly, and allows something like:
"zh_Hant"  -- forced parent --> "zh"
to write the %%Parent value of "zh". However when the parent is the "truncated" locale ID, it should not be written. This PR fixes that (tested locally with a full conversion which definitely removed the issue).
I also fixed a trivial issue to prevent the supplementalData file in "curr/" from having a cldrVersion field.
Latest diffs from this PR can be found at:
https://docs.google.com/spreadsheets/d/10UqiRFEXVgFygSchF7ZhWcz5pC0_gqAE5sgPGIB36iM/edit
see the new diffs at the bottom of each directory tab.
=> ICU-20693 Fixing how forced parent IDs work

icu4c/source/i18n/dtptngen.cpp, icu4c/source/test/intltest/dtfmttst.cpp, icu4j/main/classes/core/src/com/ibm/icu/text/DateTimePatternGenerator.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/DateFormatTest.java
=> ICU-20739 Force seconds if the skeleton has fractional seconds

icu4c/source/i18n/udateintervalformat.cpp, icu4c/source/i18n/unicode/udateintervalformat.h, icu4c/source/test/cintltst/cdateintervalformattest.c
=> ICU-20705 Add udtitvfmt_formatCalendarToResult

icu4c/source/test/intltest/dtfmttst.cpp, icu4c/source/test/intltest/dtfmttst.h, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/DateFormatTest.java
https://unicode-org.atlassian.net/browse/ICU-20741
Cc @sffc
=> ICU-20741 Adding tests for C/C++ API into DateFormatTests

icu4c/source/data/brkitr/rules/line_cj.txt, icu4c/source/data/brkitr/rules/line_loose.txt, icu4c/source/data/brkitr/rules/line_loose_cj.txt, icu4c/source/data/brkitr/rules/line_normal.txt, icu4c/source/data/brkitr/rules/line_normal_cj.txt, icu4c/source/test/testdata/break_rules/line.txt, icu4c/source/test/testdata/break_rules/line_cj.txt, icu4c/source/test/testdata/break_rules/line_loose.txt, icu4c/source/test/testdata/break_rules/line_loose_cj.txt, icu4c/source/test/testdata/break_rules/line_normal.txt, icu4c/source/test/testdata/break_rules/line_normal_cj.txt, icu4j/main/shared/data/icudata.jar, icu4j/main/tests/core/src/com/ibm/icu/dev/test/rbbi/break_rules/line_cj.txt, icu4j/main/tests/core/src/com/ibm/icu/dev/test/rbbi/break_rules/line_loose.txt, icu4j/main/tests/core/src/com/ibm/icu/dev/test/rbbi/break_rules/line_loose_cj.txt, icu4j/main/tests/core/src/com/ibm/icu/dev/test/rbbi/break_rules/line_normal.txt, icu4j/main/tests/core/src/com/ibm/icu/dev/test/rbbi/break_rules/line_normal_cj.txt
=> ICU-20893 Line break tailorings updated to Unicode 13.

icu4c/readme.html, icu4j/readme.html
=> ICU-20857 Update Readme for ICU 66 Preview.

icu4j/main/tests/core/src/com/ibm/icu/dev/test/calendar/EraRulesTest.java
=> ICU-20857 BRS 66 Clean up import statement

icu4c/APIChangeReport.html, icu4c/APIChangeReport.md
[ICU-20857] update API Change Report for ICU 66preview
[ICU-20857]: https://unicode-org.atlassian.net/browse/ICU-20857
=> ICU-20857 update API Change Report for ICU 66preview

docs/userguide/layoutengine/index.md, docs/userguide/layoutengine/paragraph.md, docs/userguide/usefrom/cobol.md
=> Userguide migration: layout and cobol topics

docs/userguide/locale/localizing.md
Note: There's only one page cleaned-up in this PR.
I wanted to make sure that I was going about this right before doing other pages. :)
=> Userguide migration: fixup localizing

icu4j/main/classes/core/src/com/ibm/icu/text/PluralRules.java
=> ICU-20906 Annotate APIs in PluralRules with why they are @internal

icu4c/source/i18n/dtptngen.cpp, icu4c/source/i18n/udatpg.cpp, icu4c/source/i18n/unicode/dtptngen.h, icu4c/source/i18n/unicode/udat.h, icu4c/source/i18n/unicode/udatpg.h, icu4c/source/test/cintltst/udatpg_test.c, icu4c/source/test/intltest/dtptngts.cpp, icu4j/main/classes/core/src/com/ibm/icu/text/DateFormat.java, icu4j/main/classes/core/src/com/ibm/icu/text/DateTimePatternGenerator.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/DateTimeGeneratorTest.java
=> ICU-20436 Add getDefaultHourCycle to DateTimePatternGenerator

icu4c/source/i18n/udateintervalformat.cpp, icu4c/source/i18n/unicode/udateintervalformat.h, icu4c/source/test/cintltst/cdateintervalformattest.c
=> ICU-20883 Move UFormattedDateInterval to end of argument list.

icu4c/source/i18n/listformatter.cpp, icu4c/source/i18n/ulistformatter.cpp, icu4c/source/i18n/unicode/listformatter.h, icu4c/source/i18n/unicode/ulistformatter.h, icu4c/source/test/cintltst/ulistfmttest.c, icu4c/source/test/intltest/listformattertest.cpp, icu4c/source/test/intltest/listformattertest.h
=> ICU-12863 Add list style APIs to C and C++

docs/userguide/conversion/compression.md, docs/userguide/dev/contributions.md, docs/userguide/dev/index.md, docs/userguide/dev/sync/custom.md, docs/userguide/dev/sync/index.md
=> Userguide migration: dev, conversion

tools/cldr/cldr-to-icu/README.txt
Added a sentence pointing people at the JAR file setup (this should have, obviously, always been there).
=> ICU-20693 Remember to mention the JAR setup

icu4c/source/common/localematcher.cpp, icu4c/source/common/locdistance.cpp, icu4c/source/common/locdistance.h, icu4c/source/common/loclikelysubtags.cpp, icu4c/source/common/lsr.cpp, icu4c/source/common/lsr.h, icu4c/source/test/testdata/localeMatcherTest.txt, icu4j/main/classes/core/src/com/ibm/icu/impl/locale/LSR.java, icu4j/main/classes/core/src/com/ibm/icu/impl/locale/LocaleDistance.java, icu4j/main/classes/core/src/com/ibm/icu/impl/locale/XLikelySubtags.java, icu4j/main/classes/core/src/com/ibm/icu/util/LocaleMatcher.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/data/localeMatcherTest.txt, icu4j/tools/misc/src/com/ibm/icu/dev/tool/locale/LikelySubtagsBuilder.java, icu4j/tools/misc/src/com/ibm/icu/dev/tool/locale/LocaleDistanceBuilder.java
https://unicode-org.atlassian.net/browse/ICU-20916
=> ICU-20916 LocaleMatcher distinguish between equivalent locales

icu4c/source/common/lsr.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/locale/LocaleDistance.java, icu4j/main/classes/core/src/com/ibm/icu/impl/locale/XLikelySubtags.java, icu4j/main/classes/core/src/com/ibm/icu/util/LocaleMatcher.java
https://unicode-org.atlassian.net/browse/ICU-20916
=> ICU-20916 UBSan & ErrorProne fixes

icu4c/source/common/uloc.cpp, icu4c/source/test/intltest/loctest.cpp, icu4c/source/test/intltest/loctest.h, icu4j/main/classes/core/src/com/ibm/icu/util/ULocale.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/ULocaleTest.java
=> ICU-20900 Fix createCanonical

icu4c/source/tools/pkgdata/pkgdata.cpp
On systems without `icu-config` installed, `pkgdata` will fail because it uses the legacy script to generate the path to pkgdata.inc.
Example command: `pkgdata -p bin_mkltfs -m static -v foo.txt'
`pkg-config` is always available, so I've created a patch to use it instead of `icu-config`.
=> ICU-20924 Use pkg-config to generate the path to pkgdata.inc

docs/userguide/format_parse/numbers/skeletons.md, icu4c/source/common/stringpiece.cpp, icu4c/source/common/unicode/stringpiece.h, icu4c/source/i18n/measunit.cpp, icu4c/source/i18n/number_skeletons.cpp, icu4c/source/i18n/number_skeletons.h, icu4c/source/i18n/unicode/measunit.h, icu4c/source/test/intltest/numbertest.h, icu4c/source/test/intltest/numbertest_api.cpp, icu4c/source/test/intltest/numbertest_skeletons.cpp, icu4c/source/test/intltest/strtest.cpp, icu4c/source/test/intltest/strtest.h, icu4j/main/classes/core/src/com/ibm/icu/impl/StringSegment.java, icu4j/main/classes/core/src/com/ibm/icu/number/NumberSkeletonImpl.java, icu4j/main/classes/core/src/com/ibm/icu/util/MeasureUnit.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberSkeletonTest.java
=> ICU-20418 Add concise number skeleton support.

.ci-builds/.azure-pipelines.yml, .ci-builds/data-filter.json, icu4c/source/i18n/translit.cpp, icu4c/source/test/intltest/transtst.cpp, icu4c/source/test/intltest/transtst.h
Ignore errors while reading root.res by using local status.
=> ICU-20673 Allow built-in translit ID w/o data.

icu4c/source/common/uassert.h, icu4c/source/i18n/formatted_string_builder.cpp, icu4c/source/i18n/formatted_string_builder.h, icu4c/source/i18n/formattedval_impl.h, icu4c/source/i18n/formattedval_sbimpl.cpp, icu4c/source/i18n/measfmt.cpp, icu4c/source/i18n/number_affixutils.cpp, icu4c/source/i18n/number_compact.cpp, icu4c/source/i18n/number_formatimpl.cpp, icu4c/source/i18n/number_longnames.cpp, icu4c/source/i18n/number_modifiers.cpp, icu4c/source/i18n/number_modifiers.h, icu4c/source/i18n/number_padding.cpp, icu4c/source/i18n/number_patternmodifier.cpp, icu4c/source/i18n/number_patternmodifier.h, icu4c/source/i18n/number_scientific.cpp, icu4c/source/i18n/number_scientific.h, icu4c/source/i18n/number_types.h, icu4c/source/i18n/number_utypes.h, icu4c/source/i18n/numrange_impl.cpp, icu4c/source/i18n/numrange_impl.h, icu4c/source/i18n/quantityformatter.cpp, icu4c/source/i18n/reldatefmt.cpp, icu4c/source/test/intltest/formatted_string_builder_test.cpp, icu4c/source/test/intltest/numbertest_affixutils.cpp, icu4c/source/test/intltest/numbertest_modifiers.cpp, icu4c/source/test/intltest/numbertest_patternmodifier.cpp
=> ICU-20665 Removing number-dependence from ICU4C FormattedStringBuilder fields.

icu4c/source/test/intltest/tztest.cpp, icu4j/build.xml, icu4j/main/tests/core/src/com/ibm/icu/dev/test/timezone/TimeZoneTest.java
Routine merge of maint/maint-66 to master in order to pick up CI fixes in #965.
=> ICU-20919 Merge maint/maint-66 to master

icu4c/source/samples/ufortune/ufortune.c
=> ICU-20767 Potential negative index access in one of the sample codes

icu4j/main/classes/core/src/com/ibm/icu/impl/FormattedStringBuilder.java, icu4j/main/classes/core/src/com/ibm/icu/impl/FormattedValueStringBuilderImpl.java, icu4j/main/classes/core/src/com/ibm/icu/impl/SimpleFormatterImpl.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/ConstantMultiFieldModifier.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/CurrencySpacingEnabledModifier.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/SimpleModifier.java, icu4j/main/classes/core/src/com/ibm/icu/text/DateIntervalFormat.java, icu4j/main/classes/core/src/com/ibm/icu/text/ListFormatter.java, icu4j/main/classes/core/src/com/ibm/icu/text/MeasureFormat.java, icu4j/main/classes/core/src/com/ibm/icu/text/RelativeDateTimeFormatter.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/FormattedStringBuilderTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/ListFormatterTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/serializable/FormatHandler.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/serializable/SerializableTestUtility.java
This includes both of the current Java ListFormatter proposals.  The PR also includes some refactoring on SimpleFormatterImpl (ICU-20406).
=> ICU-20099 Implementing all current Java ListFormatter proposals.

docs/ide4c/vscode/README.md, docs/ide4c/vscode/launch.json, docs/ide4c/vscode/tasks.json
=> ICU-20744 Add VS Code configuration files for c++

docs/userguide/datetime/universaltimescale.md, docs/userguide/glossary.md, docs/userguide/locale/examples.md, docs/userguide/locale/index.md, docs/userguide/locale/resources.md
=>  Userguide migration: glossary, locale/*, universaltimescale

icu4c/source/i18n/dtptngen.cpp, icu4c/source/test/intltest/dtfmttst.cpp, icu4j/main/classes/core/src/com/ibm/icu/text/DateTimePatternGenerator.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/DateFormatTest.java
=> ICU-20738 Best-match pattern for 'sS' uses <appendItem> data

icu4c/source/common/locid.cpp, icu4c/source/common/uloc_tag.cpp, icu4c/source/common/unicode/locid.h, icu4c/source/test/intltest/loctest.cpp, icu4c/source/test/intltest/loctest.h, icu4j/main/classes/core/src/com/ibm/icu/impl/PluralRulesLoader.java, icu4j/main/classes/core/src/com/ibm/icu/util/ULocale.java, icu4j/main/tests/collate/src/com/ibm/icu/dev/test/format/GlobalizationPreferencesTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/ULocaleTest.java
Implement UTS35 Locale ID Canonicalization
=> ICU-20834 Implement UTS35 Locale ID Canonicalization

icu4c/LICENSE, icu4j/main/shared/licenses/LICENSE
=> ICU-20975 BRS66rc update Unicode license copyright

tools/cldr/cldr-to-icu/lib/README.txt
=> ICU-20693 Update README.txt in lib directory to lessen risk of failure when setting up libs.

docs/userguide/boundaryanalysis/break-rules.md, docs/userguide/boundaryanalysis/index.md
UserGuide PR
Note: As always, there are editorial changes I've avoided making for now, for this first step.
=> ICU-20088 userguide: boundaryanalysis

docs/userguide/datetime/timezone/examples.md, docs/userguide/datetime/timezone/index.md, docs/userguide/design.md, docs/userguide/dev/codingguidelines.md
- Coding Guidelines
- ICU Architectural Design
- ICU TimeZone Classes
- Date and Time Zone Examples
=> ICU-20088 Userguide fixes by Yoshito

.ci-builds/.azure-exhaustive-tests.yml, .ci-builds/.azure-pipelines.yml
=> ICU-21003 Fix Git LFS in CI config, add timeout to ICU4J exhaustive test

icu4c/source/i18n/number_mapper.cpp, icu4c/source/i18n/number_mapper.h, icu4c/source/i18n/number_patternstring.cpp, icu4c/source/i18n/numparse_impl.cpp, icu4c/source/test/intltest/numfmtst.cpp, icu4c/source/test/intltest/numfmtst.h, icu4j/main/classes/core/src/com/ibm/icu/impl/number/PatternStringUtils.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/PropertiesAffixPatternProvider.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/parse/NumberParserImpl.java, icu4j/main/classes/core/src/com/ibm/icu/number/NumberPropertyMapper.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/NumberFormatTest.java
=> ICU-20961 Return correct currency plural pattern from DecimalFormat

docs/userguide/collation/api.md, docs/userguide/collation/architecture.md, docs/userguide/collation/concepts.md, docs/userguide/collation/customization/ignorepunct.md, docs/userguide/collation/customization/index.md, docs/userguide/collation/examples.md, docs/userguide/collation/faq.md, docs/userguide/collation/index.md, docs/userguide/collation/string-search.md
=> ICU-20088 User Guide collation page fixes

icu4c/source/i18n/dtitvfmt.cpp, icu4c/source/i18n/dtitvinf.cpp, icu4c/source/i18n/unicode/dtitvfmt.h, icu4c/source/i18n/unicode/dtitvinf.h, icu4c/source/test/intltest/dtifmtts.cpp, icu4c/source/test/intltest/dtifmtts.h, icu4j/main/classes/core/src/com/ibm/icu/text/DateIntervalFormat.java, icu4j/main/classes/core/src/com/ibm/icu/text/DateIntervalInfo.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/DateIntervalFormatTest.java
=> ICU-20967 add millisecond to DateIntervalFormat

icu4c/source/i18n/number_decimalquantity.cpp, icu4c/source/test/intltest/numbertest_api.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/number/DecimalQuantity_AbstractBCD.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
=> ICU-20974 Correctly handle extreme values of double.

icu4c/source/i18n/ucal.cpp, icu4c/source/test/cintltst/ccaltst.c
The issue shows under valgrind or as an Address Sanitizer failure.
=> ICU-21004 Fix buffer over-read in ucal_open

docs/userguide/strings/utext.md, docs/userguide/transforms/casemappings.md
=> ICU-20088 User Guide fix-ups for UText and Case Mapping pages

icu4c/source/test/intltest/numbertest_decimalquantity.cpp, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/ExhaustiveNumberTest.java
=> ICU-20974 Fix exhaustive test failures

README.md
=> ICU-20626 Update Readme badges to add CI-Valgrind pipeline

icu4j/main/tests/core/src/com/ibm/icu/dev/test/rbbi/RBBITestMonkey.java
Port the C++ changes in https://github.com/unicode-org/icu/pull/730/files
to Java.
=> ICU-21006 Improve output from RBBI Monkey Test in ICU4J

icu4c/source/common/unicode/uloc.h
https://unicode-org.atlassian.net/browse/ICU-20700
Addendum after PR #1022 -- I took another look at the C API docs and thought a small update would be useful. Sorry for the churn.
=> ICU-20700 uloc_acceptLanguage API doc update

icu4c/source/i18n/dtitvfmt.cpp, icu4c/source/i18n/dtitvinf.cpp
=> ICU-21014 Fix OOM not checked in dtitvfmt.cpp and dtitvinf.cpp

icu4j/build.xml
=> ICU-21008 Make ant checkTest run tests in exhaustive mode

docs/userguide/strings/regexp.md
=> ICU-20088 ICU User Guide md migration of regexp

icu4c/source/Makefile.in, icu4c/source/configure, icu4c/source/configure.ac
=> ICU-20978 Reduce unnecessary building for tools when cross-building

icu4j/main/classes/core/src/com/ibm/icu/number/CurrencyPrecision.java, icu4j/main/classes/core/src/com/ibm/icu/number/FractionPrecision.java, icu4j/main/classes/core/src/com/ibm/icu/number/IntegerWidth.java, icu4j/main/classes/core/src/com/ibm/icu/number/LocalizedNumberRangeFormatter.java, icu4j/main/classes/core/src/com/ibm/icu/number/Precision.java, icu4j/main/classes/core/src/com/ibm/icu/number/ScientificNotation.java, icu4j/main/classes/core/src/com/ibm/icu/text/FormattedValue.java
=> ICU-21020 Document unchecked exception in various number formatter classes

icu4c/source/i18n/vtzone.cpp
=> ICU-21013 Fix OOM not checked in vtzone.cpp

docs/userguide/conversion/compression.md, docs/userguide/datetime/universaltimescale.md, docs/userguide/dev/contributions.md, docs/userguide/dev/index.md, docs/userguide/dev/sync/custom.md, docs/userguide/dev/sync/index.md, docs/userguide/glossary.md, docs/userguide/locale/examples.md, docs/userguide/locale/index.md, docs/userguide/locale/localizing.md, docs/userguide/locale/resources.md
Missed this when doing the User Guide markdown edits.
=> ICU-20088 Add Unicode copyright to some User Guide pages.

icu4c/source/i18n/listformatter.cpp, icu4c/source/i18n/unicode/listformatter.h, icu4c/source/test/depstest/dependencies.txt, icu4c/source/test/intltest/listformattertest.cpp, icu4c/source/test/intltest/listformattertest.h, icu4j/main/classes/core/src/com/ibm/icu/text/ListFormatter.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/ListFormatterTest.java
=> ICU-21016 Special handling of Spanish and Hebrew list format until CLDR get the data

icu4c/source/i18n/dcfmtsym.cpp, icu4c/source/i18n/decimfmt.cpp, icu4c/source/i18n/number_formatimpl.cpp, icu4c/source/i18n/number_mapper.cpp, icu4c/source/i18n/number_mapper.h, icu4c/source/i18n/number_patternmodifier.cpp, icu4c/source/i18n/number_patternmodifier.h, icu4c/source/i18n/number_skeletons.cpp, icu4c/source/i18n/unicode/dcfmtsym.h, icu4c/source/i18n/unicode/numberformatter.h, icu4c/source/test/intltest/numbertest_patternmodifier.cpp, icu4c/source/test/intltest/numfmtst.cpp, icu4c/source/test/intltest/numfmtst.h, icu4j/main/classes/core/src/com/ibm/icu/number/NumberFormatterImpl.java, icu4j/main/classes/core/src/com/ibm/icu/text/DecimalFormat.java, icu4j/main/classes/core/src/com/ibm/icu/text/DecimalFormatSymbols.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/NumberFormatTest.java
=> ICU-20956 Fix monetary symbol getters in DecimalFormat

icu4c/source/i18n/decimfmt.cpp, icu4c/source/i18n/fphdlimp.h, icu4c/source/i18n/measfmt.cpp, icu4c/source/i18n/number_capi.cpp, icu4c/source/i18n/number_output.cpp, icu4c/source/i18n/number_utypes.h, icu4c/source/i18n/numrange_fluent.cpp, icu4c/source/i18n/unicode/decimfmt.h, icu4c/source/i18n/unicode/numberformatter.h, icu4c/source/i18n/unicode/numberrangeformatter.h, icu4c/source/i18n/unicode/unumberformatter.h, icu4c/source/test/intltest/numbertest_api.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/number/LocalizedNumberFormatterAsFormat.java, icu4j/main/classes/core/src/com/ibm/icu/number/FormattedNumber.java, icu4j/main/classes/core/src/com/ibm/icu/number/FormattedNumberRange.java, icu4j/main/classes/core/src/com/ibm/icu/number/LocalizedNumberFormatter.java, icu4j/main/classes/core/src/com/ibm/icu/number/Precision.java, icu4j/main/classes/core/src/com/ibm/icu/number/ScientificNotation.java, icu4j/main/classes/core/src/com/ibm/icu/text/DecimalFormat.java, icu4j/main/classes/core/src/com/ibm/icu/text/MeasureFormat.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
=> ICU-20806 Removing obsolete number formatting methods.

icu4c/source/test/testdata/collationtest.txt, icu4j/main/tests/collate/src/com/ibm/icu/dev/data/collationtest.txt
Might as well make progress on something :-)
=> ICU-13790 Add data tests to verify certain chars present in pinyin, stroke

icu4c/source/i18n/measunit_extra.cpp, icu4c/source/i18n/measunit_impl.h, icu4c/source/i18n/unicode/measunit.h, icu4c/source/test/intltest/measfmttest.cpp
=> ICU-20920 Changing "Sequence" to "Mixed" in ICU4C MeasureUnit

icu4c/source/data/curr/su.txt, icu4j/main/shared/data/icudata.jar, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/IntlTestNumberFormat.java
=> ICU-21005 Fix exhaustive test failure in IntlTestNumberFormat.

docs/userguide/format_parse/numbers/skeletons.md, icu4c/source/i18n/number_skeletons.cpp, icu4c/source/i18n/number_skeletons.h, icu4c/source/test/intltest/numbertest.h, icu4c/source/test/intltest/numbertest_api.cpp, icu4c/source/test/intltest/numbertest_skeletons.cpp, icu4j/main/classes/core/src/com/ibm/icu/number/NumberSkeletonImpl.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberSkeletonTest.java
=> ICU-20418 Number skeletons: implement star wildcard; user guide fixes

docs/userguide/icudata.md, docs/userguide/icufaq/icu4j-faq.md, docs/userguide/icufaq/index.md, docs/userguide/index.md, docs/userguide/io/ustdio.md, docs/userguide/io/ustream.md
=> ICU-20088 fix pages as part of userguide migration to markdown format.

icu4j/main/classes/core/src/com/ibm/icu/impl/CurrencyData.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/MutablePatternModifier.java, icu4j/main/classes/core/src/com/ibm/icu/number/NumberFormatter.java, icu4j/main/classes/core/src/com/ibm/icu/number/NumberSkeletonImpl.java, icu4j/main/classes/core/src/com/ibm/icu/text/CurrencyDisplayNames.java, icu4j/main/classes/core/src/com/ibm/icu/util/Currency.java, icu4j/main/classes/currdata/src/com/ibm/icu/impl/ICUCurrencyDisplayInfoProvider.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/CurrencyTest.java
=> ICU-20854 Add support for more currency variants.

icu4c/source/common/unicode/platform.h
=> ICU-20964 Fix small typo mistake

icu4j/main/classes/core/src/com/ibm/icu/impl/number/MutablePatternModifier.java
=> ICU-20979 BRS67RC Clean up import statements

icu4j/main/classes/core/src/com/ibm/icu/util/LocaleMatcher.java
=> ICU-20979 BRS67RC Fixed a java doc issue

icu4j/APIChangeReport.html, icu4j/main/classes/core/src/com/ibm/icu/number/FormattedNumber.java, icu4j/main/classes/core/src/com/ibm/icu/number/FormattedNumberRange.java, icu4j/main/classes/core/src/com/ibm/icu/text/ConstrainedFieldPosition.java, icu4j/main/classes/core/src/com/ibm/icu/text/DateFormatSymbols.java, icu4j/main/classes/core/src/com/ibm/icu/text/DateIntervalFormat.java, icu4j/main/classes/core/src/com/ibm/icu/text/DecimalFormat.java, icu4j/main/classes/core/src/com/ibm/icu/text/FormattedValue.java, icu4j/main/classes/core/src/com/ibm/icu/text/ListFormatter.java, icu4j/main/classes/core/src/com/ibm/icu/text/NumberFormat.java, icu4j/main/classes/core/src/com/ibm/icu/text/PluralRules.java, icu4j/main/classes/core/src/com/ibm/icu/text/RelativeDateTimeFormatter.java, icu4j/main/classes/core/src/com/ibm/icu/text/UFormat.java, icu4j/main/classes/core/src/com/ibm/icu/util/BytesTrie.java, icu4j/main/classes/core/src/com/ibm/icu/util/CharsTrie.java, icu4j/main/classes/core/src/com/ibm/icu/util/MeasureUnit.java
Update ICU draft API up to 64 to stable. Regenerated API change report.
=> ICU-20979 BRS67RC ICU4J API status promotion

icu4j/main/classes/core/src/com/ibm/icu/number/Precision.java
=> ICU-20806 Removing 'implements Cloneable' from Precision.java

icu4j/main/classes/core/src/com/ibm/icu/text/ListFormatter.java
=> ICU-20099 Fix API tags in ListFormatter.SpanField

icu4c/source/common/locid.cpp, icu4c/source/i18n/ucol_sit.cpp, icu4c/source/test/intltest/rbbitst.cpp, icu4c/source/test/intltest/strtest.cpp
Fixing a few warnings from running the samples.
=> ICU-20979 BRSRC: Fixing minor MSVC warnings

tools/commit-checker/README.md
Apparently the Jira API servers want you to sign in with an email address now, not just a username.
=> ICU-20979 Fixing instructions in commit report tool

icu4j/tools/build/icu4j57.api3.gz, icu4j/tools/build/icu4j67.api3.gz
And removed ICU4J 57 API signature data file.
=> ICU-20979 BRS67RC Adding ICU4J 67 API signature data file

icu4j/readme.html
For now, just updating version to 67, but not mentioning it's RC, so we don't need another update.
I also updated all dead ICU user guide links.
=> ICU-20979 BRS67RC Updating ICU4J readme

icu4c/source/test/intltest/dtfmtrtts.cpp
Just updated the logKnownIssue added for https://unicode-org.atlassian.net/browse/ICU-21022 to refer to the new bug forfixing the issue in a future release: https://unicode-org.atlassian.net/browse/ICU-21049
=> ICU-21022 Update logKnownIssue to refer to ticket for fixing in future release

icu4c/source/common/unicode/localebuilder.h, icu4c/source/common/unicode/localematcher.h, icu4c/source/common/unicode/localpointer.h, icu4c/source/common/ustr_imp.h, icu4c/source/i18n/unicode/currunit.h, icu4c/source/i18n/unicode/decimfmt.h, icu4c/source/i18n/unicode/dtitvfmt.h, icu4c/source/i18n/unicode/formattedvalue.h, icu4c/source/i18n/unicode/listformatter.h, icu4c/source/i18n/unicode/measunit.h, icu4c/source/i18n/unicode/numberformatter.h, icu4c/source/i18n/unicode/numberrangeformatter.h, icu4c/source/i18n/unicode/numfmt.h, icu4c/source/i18n/unicode/plurrule.h, icu4c/source/i18n/unicode/reldatefmt.h, icu4c/source/i18n/unicode/udateintervalformat.h, icu4c/source/i18n/unicode/uformattedvalue.h, icu4c/source/i18n/unicode/ulistformatter.h, icu4c/source/i18n/unicode/unum.h, icu4c/source/i18n/unicode/unumberformatter.h, icu4c/source/i18n/unicode/upluralrules.h, icu4c/source/i18n/unicode/ureldatefmt.h
ICU 67 C API promotion per spreadsheet in https://docs.google.com/spreadsheets/d/1EryaBvIZkiGRJLZe37PHlCv_Lz2MPg0WEaNnV7pUTiw
Also fixes use of U_INTERNAL and U_DRAFT in a couple of files per comments in https://github.com/unicode-org/icu/pull/1072
=> ICU-20979 BRS 67rc, ICU4C API promotion

icu4c/source/i18n/double-conversion-ieee.h, icu4c/source/i18n/double-conversion-string-to-double.cpp, icu4c/source/i18n/double-conversion-strtod.cpp, icu4c/source/i18n/double-conversion-utils.h, vendor/double-conversion/upstream/Changelog, vendor/double-conversion/upstream/double-conversion/ieee.h, vendor/double-conversion/upstream/double-conversion/string-to-double.cc, vendor/double-conversion/upstream/double-conversion/strtod.cc, vendor/double-conversion/upstream/double-conversion/utils.h, vendor/double-conversion/upstream/test/cctest/test-conversions.cc, vendor/double-conversion/upstream/test/cctest/test-diy-fp.cc, vendor/double-conversion/upstream/test/cctest/test-fast-dtoa.cc, vendor/double-conversion/upstream/test/cctest/test-ieee.cc, vendor/double-conversion/upstream/test/cctest/test-strtod.cc
It was a clean integration this time.  Hopefully the build bots are happy.
=> ICU-20979 Updating double-conversion from upstream master

icu4c/source/i18n/measunit_extra.cpp, icu4c/source/test/depstest/dependencies.txt
Also see: ICU-20920 ICU-21059 ICU-20429 ICU-21058
=> ICU-20979 Update TODOs in formatting code to point to open issues.

icu4c/APIChangeReport.html, icu4c/APIChangeReport.md
[ICU-20979]
API Change Report… 66 vs 67
[ICU-20979]: https://unicode-org.atlassian.net/browse/ICU-20979
=> ICU-20979 API Change Report for 67 RC

icu4c/source/i18n/measunit_extra.cpp, icu4c/source/i18n/measunit_impl.h, icu4c/source/test/intltest/measfmttest.cpp
=> ICU-21060 Fix heap-use-after-free bug.

icu4j/build.properties, icu4j/main/shared/data/icudata.jar, icu4j/main/shared/data/icutzdata.jar, icu4j/main/shared/data/testdata.jar
=> ICU-21061 BRS67GA Update version numbers for 67GA

icu4c/source/i18n/number_formatimpl.cpp, icu4c/source/test/intltest/dtifmtts.cpp, icu4c/source/test/intltest/numfmtst.cpp, icu4c/source/test/intltest/transtst.cpp
=> ICU-21040 Fix segfaults in no data tests

.ci-builds/data-filter.json, docs/userguide/icu_data/buildtool.md, icu4c/source/data/BUILDRULES.py, icu4c/source/python/icutools/databuilder/filtration.py
=> ICU-21073 Fix ICU Data Build Tool in "locale" mode.

icu4c/source/common/localematcher.cpp, icu4c/source/test/intltest/localematchertest.cpp
[ICU-20936] fix a bug found by memory sanitizer
[ICU-20936]: https://unicode-org.atlassian.net/browse/ICU-20936
=> ICU-20936 copy the new direction field

icu4c/source/common/utrie_swap.cpp, icu4c/source/test/cintltst/ucptrietest.c
Also include unit tests for 8bits.
=> ICU-21069 Fix ucptrie_swap pointer logic

tools/cldr/cldr-to-icu/README.txt, tools/cldr/cldr-to-icu/install-cldr-jars.sh
=> ICU-21078 Adding script and updating docs for CLDR jars

icu4c/source/i18n/measunit_extra.cpp
=> ICU-21082 Fix error: no member named 'abs' in"std"

icu4c/source/i18n/listformatter.cpp, icu4c/source/i18n/unicode/dtptngen.h, icu4c/source/i18n/unicode/listformatter.h, icu4c/source/i18n/unicode/udatpg.h
=> ICU-21053 Fix compile problems with UCONFIG_NO_FORMATTING = 1

tools/cldr/cldr-to-icu/install-cldr-jars.sh
=> ICU-21078 Adding missing copyright notice (sorry!)

icu4c/source/i18n/double-conversion-utils.h, vendor/double-conversion/upstream/double-conversion/utils.h, vendor/double-conversion/upstream/msvc/double-conversion.vcxproj, vendor/double-conversion/upstream/msvc/double-conversion.vcxproj.filters, vendor/double-conversion/upstream/msvc/run_tests/run_tests.vcxproj
=> ICU-21061 ICU-21085 Merge latest changes from double-conversion

icu4c/source/common/uassert.h
@jefgen How/where would you recommend adding a C++14 build bot?
=> ICU-21081 Make U_ASSERT C++14 compatible

icu4j/main/classes/core/src/com/ibm/icu/text/ListFormatter.java
=> ICU-21090 Fix private class

icu4c/source/common/localematcher.cpp, icu4c/source/common/unicode/localematcher.h, icu4c/source/test/intltest/localematchertest.cpp, icu4j/main/classes/core/src/com/ibm/icu/util/LocaleMatcher.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/LocaleMatcherTest.java
https://unicode-org.atlassian.net/browse/ICU-21029
=> ICU-21029 LocaleMatcher: add option to turn off default locale

icu4c/source/i18n/number_fluent.cpp, icu4c/source/i18n/number_mapper.h, icu4c/source/i18n/unicode/numberformatter.h, icu4c/source/test/intltest/numfmtst.cpp, icu4c/source/test/intltest/numfmtst.h
=> ICU-21134 Copy additional data when toNumberFormatter is used

icu4c/source/common/rbbi.cpp, icu4c/source/common/rbbidata.cpp, icu4c/source/common/rbbidata.h, icu4c/source/common/rbbitblb.cpp, icu4c/source/common/rbbitblb.h, icu4c/source/test/intltest/rbbitst.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/RBBIDataWrapper.java, icu4j/main/classes/core/src/com/ibm/icu/text/RBBITableBuilder.java, icu4j/main/classes/core/src/com/ibm/icu/text/RuleBasedBreakIterator.java, icu4j/main/shared/data/icudata.jar, icu4j/main/tests/core/src/com/ibm/icu/dev/test/rbbi/RBBITest.java
=> ICU-13565 RBBI, make all state table row data be unsigned.

tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/LdmlConverter.java, tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/ant/CleanOutputDirectoryTask.java, tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/ant/ConvertIcuDataTask.java
=> ICU-21140 Fix cldr-to-icu tooling to work on Windows

.gitignore, tools/cldr/.gitignore, tools/cldr/cldr-to-icu/README.txt
=> ICU-21078 Improve instructions and gitignore file for cldr-to-icu

icu4c/source/common/locdispnames.cpp, icu4c/source/common/unicode/urename.h
=> ICU-21161 Mark uloc_getDisplayScriptInContext static

.ci-builds/.azure-exhaustive-tests.yml
=> ICU-21177 Skip running the Exhaustive tests on changes to docs and other files

icu4c/source/common/putil.cpp, icu4c/source/common/putilimp.h, icu4c/source/common/ucnv_bld.cpp, icu4c/source/common/ucnv_bld.h, icu4c/source/tools/gensprep/store.c
=> ICU-21170 Fix function prototypes

icu4c/source/common/cmemory.h
(Also makes a tiny tweak to appendAll() documentation.)
=> ICU-21174 Add a const version of MaybeStackVector::getAlias().

docs/userguide/transforms/general/index.md, docs/userguide/transforms/general/rules.md
=> ICU-20088 Fixing pages under transforms/general

icu4c/source/test/intltest/dtfmttst.cpp
=> ICU-21122 Fix flaky TestAdoptCalendarLeak

icu4c/source/test/fuzzer/Makefile.in, icu4c/source/test/fuzzer/fuzzer_driver.cpp
=> ICU-20734 Improve fuzzer_driver

icu4c/source/i18n/calendar.cpp, icu4c/source/i18n/cecal.cpp, icu4c/source/i18n/chnsecal.cpp, icu4c/source/i18n/gregocal.cpp, icu4c/source/i18n/hebrwcal.cpp, icu4c/source/i18n/indiancal.cpp, icu4c/source/i18n/islamcal.cpp, icu4c/source/i18n/persncal.cpp, icu4c/source/i18n/smpdtfmt.cpp, icu4c/source/i18n/timezone.cpp, icu4c/source/i18n/unicode/timezone.h, icu4c/source/test/intltest/caltest.cpp, icu4c/source/test/intltest/caltest.h, icu4c/source/test/intltest/dtfmttst.cpp, icu4c/source/test/intltest/dtfmttst.h, icu4j/main/classes/core/src/com/ibm/icu/util/CECalendar.java, icu4j/main/classes/core/src/com/ibm/icu/util/Calendar.java, icu4j/main/classes/core/src/com/ibm/icu/util/ChineseCalendar.java, icu4j/main/classes/core/src/com/ibm/icu/util/EthiopicCalendar.java, icu4j/main/classes/core/src/com/ibm/icu/util/GregorianCalendar.java, icu4j/main/classes/core/src/com/ibm/icu/util/HebrewCalendar.java, icu4j/main/classes/core/src/com/ibm/icu/util/IndianCalendar.java, icu4j/main/classes/core/src/com/ibm/icu/util/IslamicCalendar.java, icu4j/main/classes/core/src/com/ibm/icu/util/PersianCalendar.java, icu4j/main/classes/core/src/com/ibm/icu/util/TimeZone.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/calendar/CalendarRegressionTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/DateFormatTest.java
=> ICU-20465 Calendar/DateFormat listen to tz extension

icu4c/source/i18n/measunit.cpp, icu4c/source/i18n/unicode/measunit.h, icu4c/source/test/intltest/numfmtst.cpp
=> ICU-21076 Delete unneeded MeasureUnit data & code

icu4c/source/data/BUILDRULES.py
=> ICU-21175 Add cnvalias as a dependency of misc_res

docs/userguide/conversion/data.md, docs/userguide/datetime/calendar/examples.md, docs/userguide/datetime/calendar/index.md
=> ICU-20088 Userguide fixes to formatting

docs/index.md
Entry point to find the new home of the User Guide.
https://unicode-org.atlassian.net/browse/ICU-20088
=> ICU-20088 index page for ICU GitHub Pages

docs/userguide/format_parse/messages/index.md
https://unicode-org.atlassian.net/browse/ICU-20088
See https://stackoverflow.com/questions/3426182/how-to-escape-liquid-template-tags
=> ICU-20088 turn off liquid processing in MessageFormat page

icu4c/source/i18n/measunit_extra.cpp
=> ICU-21174 Add a memory allocation check in MeasureUnit.

icu4c/source/common/cmemory.h
=> ICU-21174 Delete not-to-be-used methods. Add a constructor warning. Fix a debug msg.

icu4c/source/common/cmemory.h
I intend to squash this and attribute the whole PR to @younies, with his approval - as I really just copied his code to move it one step up the class hierarchy.
=> ICU-21174 Add "AndCheckError" versions of "emplaceBack()" and "create()"

.ci-builds/data-filter.json, docs/userguide/icu_data/buildtool.md, icu4c/source/python/icutools/databuilder/filtration.py, icu4c/source/python/icutools/databuilder/filtration_schema.json
=> ICU-21176 Add aliases for terms "whitelist" and "blacklist" in data filter

icu4c/source/test/hdrtst/testtagsguards.sh
=> ICU-21191 Improve configurability of testtagsguards.sh

icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/NumberFormatSpecificationTest.java
=> ICU-21057 Remove obsolete logKnownIssue for ICU-11025

icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/CompactDecimalFormatTest.java
=> ICU-21056 Remove obsolete logKnownIssues in CompactDecimalFormatTest

icu4c/source/i18n/i18n.vcxproj, icu4c/source/i18n/i18n.vcxproj.filters, icu4c/source/i18n/i18n_uwp.vcxproj, icu4c/source/i18n/numrange_capi.cpp, icu4c/source/i18n/sources.txt, icu4c/source/i18n/unicode/numberrangeformatter.h, icu4c/source/i18n/unicode/unumberformatter.h, icu4c/source/i18n/unicode/unumberrangeformatter.h, icu4c/source/test/cintltst/Makefile.in, icu4c/source/test/cintltst/cformtst.c, icu4c/source/test/cintltst/cintltst.vcxproj, icu4c/source/test/cintltst/cintltst.vcxproj.filters, icu4c/source/test/cintltst/unumberrangeformattertst.c, icu4c/source/test/depstest/dependencies.txt
=> ICU-21182 Adding UNumberRangeFormatter.

icu4c/source/extra/scrptrun/Makefile.in
=> ICU-21217 Windows: Fix link command for extra/scrptrun

tools/cldr/cldr-to-icu/src/test/java/org/unicode/icu/tool/cldrtoicu/SupplementalDataTest.java
=> ICU-21228 fix test broken by https://github.com/unicode-org/cldr/pull/615

icu4c/source/tools/icupkg/icupkg.cpp
=> ICU-20774 Add option to icupkg to allow missing deps between resource files.

icu4c/source/test/cintltst/cloctst.c
Fix memory leaks in the test code in PR #1235
=> ICU-21159 Fix memory leaks in cintltst TestUsingDefaultWarning.

tools/cldr/cldr-to-icu/src/test/java/org/unicode/icu/tool/cldrtoicu/ant/CleanOutputDirectoryTaskTest.java
=> ICU-21237 Copyright fix

icu4c/source/test/cintltst/cloctst.c
Change from using u_austrcpy to aescstrdup
=> ICU-21157 Fix test code

tools/cldr/cldr-to-icu/build-icu-data.xml, tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/IcuConverterConfig.java, tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/LdmlConverter.java, tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/LdmlConverterConfig.java, tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/ant/ConvertIcuDataTask.java
Note that in this version the CLDR version is (by default) from CLDRFile, but could be overwritten.
=> ICU-21028 Adding ICU version file generation to tools

icu4c/source/i18n/number_decimalquantity.cpp, icu4c/source/test/intltest/numfmtst.cpp, icu4c/source/test/intltest/numfmtst.h, icu4j/main/classes/core/src/com/ibm/icu/impl/number/DecimalQuantity_DualStorageBCD.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/NumberFormatTest.java
=> ICU-21232 Improve performance of DecimalFormat#parse on long numbers

docs/userguide/boundaryanalysis/index.md, docs/userguide/dev/codingguidelines.md, icu4c/source/Doxyfile.in, icu4c/source/common/unicode/ucnv.h, icu4c/source/common/unifiedcache.cpp, icu4c/source/common/unifiedcache.h, icu4c/source/data/cldr-icu-readme.txt, icu4c/source/i18n/dtitvfmt.cpp, icu4c/source/i18n/nfrs.cpp, icu4c/source/i18n/nfrule.cpp, icu4c/source/i18n/nfrule.h, icu4c/source/i18n/nfsubs.cpp, icu4c/source/i18n/rbt_pars.cpp, icu4c/source/i18n/region.cpp, icu4c/source/i18n/unicode/rbnf.h, icu4c/source/test/testdata/rbbitst.txt, icu4j/main/classes/core/src/com/ibm/icu/text/DateIntervalFormat.java, icu4j/main/classes/core/src/com/ibm/icu/text/NFRule.java, icu4j/main/classes/core/src/com/ibm/icu/text/NFRuleSet.java, icu4j/main/classes/core/src/com/ibm/icu/text/NFSubstitution.java, icu4j/main/classes/core/src/com/ibm/icu/text/RuleBasedNumberFormat.java, icu4j/main/classes/core/src/com/ibm/icu/util/Region.java, icu4j/main/classes/translit/src/com/ibm/icu/text/TransliteratorParser.java, icu4j/tools/misc/src/com/ibm/icu/dev/tool/translit/dumpICUrules.bat
https://unicode-org.atlassian.net/browse/ICU-21242
=> ICU-21242 rephrase documentation using term master 

icu4c/source/test/intltest/measfmttest.cpp
=> ICU-20927 Adding French narrow duration unit test.

icu4c/source/i18n/measunit_extra.cpp, icu4c/source/test/intltest/measfmttest.cpp
Fix kilogram parsing: ignore 'kilogram' as a stem, we have 'gram'.
Failures in the added unit test before the fix: withSIPrefix resulted
in 'microkilogram', and kilogram's prefix was considered to be
"ONE" (i.e. 10^0).
=> ICU-21246 Handle kilogram SI prefix correctly

icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/MeasureUnitTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/PluralRulesTest.java
https://unicode-org.atlassian.net/browse/ICU-21036
=> ICU-21036 use StringBuilder(String str) not StringBuilder(int capacity)

icu4c/source/common/uloc.cpp
The one single caller of _getVariantEx() is _getVariant() and this in
turn only has 3 callers, one of which is commented out (so it can be
deleted), one of which doesn't actually do anything (so it too can be
deleted) and one which can be replaced by inlining the use of
CheckedArrayByteSink.
This also allows _getVariantEx() to be renamed to _getVariant() as it's
the only such function left now.
=> ICU-21035 Replace backward compatibility _getVariant*() functions.

icu4c/source/test/perf/localecanperf/runTest.sh, icu4c/source/test/perf/utrie2perf/utrie2perf.sh
=> ICU-21051 Add copyright Remove License from sh

icu4c/source/.clang-format
=> ICU-20963 Add .clang-format file to icu4c/source

docs/userguide/io/ustdio.md, docs/userguide/services.md
=> ICU-20088 fix broken links (format_parse)

icu4c/source/test/testdata/numberpermutationtest.txt, icu4j/main/tests/core/src/com/ibm/icu/dev/data/numberpermutationtest.txt
This should fix the broken master branch.
=> ICU-21249 Update numberpermutationtest.txt

icu4c/source/common/locdispnames.cpp, icu4c/source/common/locmap.cpp, icu4c/source/common/uloc.cpp, icu4c/source/common/uloc_tag.cpp
https://unicode-org.atlassian.net/browse/ICU-21035
=> ICU-21035 Update locale implementation to use ulocimp_getKeywordValue().

icu4c/source/common/simpleformatter.cpp, icu4c/source/i18n/formattedval_impl.h, icu4c/source/i18n/formattedval_sbimpl.cpp, icu4c/source/i18n/listformatter.cpp, icu4c/source/i18n/measfmt.cpp, icu4c/source/test/depstest/dependencies.txt, icu4c/source/test/intltest/formattedvaluetest.cpp
=> ICU-20826 Updating C++ ListFormatter impl to be more like Java

icu4c/source/i18n/number_compact.cpp, icu4c/source/test/intltest/numbertest_api.cpp, icu4c/source/test/intltest/numbertest_decimalquantity.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/number/CompactData.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/CompactDecimalFormatTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/PluralRulesTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/DecimalQuantityTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
First step: I found the place in library code that needs to change, and I refactored the tests accordingly.
=> ICU-21258 Refactor code and tests for compact data known issue

.appveyor.yml, .ci-builds/.azure-exhaustive-tests.yml, .ci-builds/.azure-pipelines.yml, .ci-builds/.azure-valgrind.yml
=> ICU-21265 Increase git fetch depth on CI builds to allow rebuilding older commits

icu4c/source/data/makedata.mak
=> ICU-21272 Changes to makedata.mak to fix Windows Debug cross-build for ARM & ARM64

docs/userguide/format_parse/datetime/index.md
=> ICU-21225 Conflicting documentation for stand alone quarter

icu4j/main/classes/core/src/com/ibm/icu/impl/units/MeasureUnitImpl.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/SingleUnitImpl.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitsData.java, icu4j/main/classes/core/src/com/ibm/icu/util/MeasureUnit.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/MeasureUnitTest.java
=> ICU-21010 MeasureUnit extension in Java

icu4c/source/i18n/number_capi.cpp, icu4c/source/i18n/number_decimalquantity.cpp, icu4c/source/i18n/number_decimalquantity.h, icu4c/source/i18n/number_decnum.h, icu4c/source/i18n/numrange_capi.cpp, icu4c/source/i18n/numrange_fluent.cpp, icu4c/source/i18n/unicode/numberformatter.h, icu4c/source/i18n/unicode/numberrangeformatter.h, icu4c/source/i18n/unicode/unumberformatter.h, icu4c/source/i18n/unicode/unumberrangeformatter.h, icu4c/source/test/cintltst/unumberformattertst.c, icu4c/source/test/cintltst/unumberrangeformattertst.c, icu4c/source/test/intltest/numbertest.h, icu4c/source/test/intltest/numbertest_range.cpp
=> ICU-20775 Complete set of toDecimalNumber functions in ICU4C

icu4j/main/classes/core/src/com/ibm/icu/impl/units/ComplexUnitsConverter.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/ConversionRates.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/MeasureUnitImpl.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/SingleUnitImpl.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitConverter.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitPreferences.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitsData.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitsRouter.java, icu4j/main/classes/core/src/com/ibm/icu/util/MeasureUnit.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/impl/UnitsTest.java
=> ICU-20568 Implementation of UnitConverter, ComplexUnitConverter and UnitsRouter

icu4c/source/i18n/quantityformatter.h, icu4c/source/test/intltest/measfmttest.cpp, icu4c/source/test/intltest/numfmtst.cpp, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/MeasureUnitTest.java
=> ICU-21249 Fix stale logKnownIssues and TODOs

icu4c/source/i18n/measunit_extra.cpp, icu4c/source/i18n/number_longnames.cpp, icu4c/source/i18n/number_usageprefs.cpp, icu4c/source/i18n/unicode/measunit.h, icu4c/source/test/intltest/measfmttest.cpp
=> ICU-21021 Changing MeasureUnit::splitToSingleUnits to return std::pair

icu4c/source/i18n/number_longnames.h
=> ICU-20568 Cleanup: drop declaration for no longer existing factory.

icu4c/LICENSE
=> ICU-21163 Update URL to lao-dictionary project in LICENSE

icu4j/build.xml
=> ICU-21287 Enable asserts for 'ant checkTest'

icu4c/source/i18n/number_skeletons.cpp, icu4c/source/i18n/number_usageprefs.cpp, icu4c/source/i18n/unicode/numberformatter.h
In particular: actually handle Usage memory allocation errors (Closes: https://github.com/icu-units/icu/issues/89).
Also: correct Scale's error condition.
=> ICU-20568 Improve MacroProps error handling

icu4c/source/common/ucnv_u8.cpp, icu4c/source/test/intltest/convtest.cpp, icu4c/source/test/intltest/convtest.h
=> ICU-21280 Correct source bytes counting

.travis.yml, icu4c/source/test/testdata/break_rules/README.md, tools/scripts/icu-file-utf8-check.py
=> ICU-21248 Adds source file check (UTF-8 and absence of BOM) to

icu4c/source/common/unicode/utypes.h, icu4c/source/i18n/unicode/dtitvfmt.h, icu4c/source/test/hdrtst/testtagsguards.sh
https://unicode-org.atlassian.net/browse/ICU-21249
=> ICU-21249 add hide-draft guards for some @draft ICU 68 API

icu4c/source/test/hdrtst/testtagsguards.sh
Fixing bug introduced by #1196
=> ICU-21191 Fixing testtagsguards.sh

icu4c/source/i18n/number_rounding.cpp, icu4c/source/i18n/number_roundingutils.h, icu4c/source/i18n/number_skeletons.cpp, icu4c/source/i18n/number_usageprefs.cpp, icu4c/source/i18n/number_usageprefs.h, icu4c/source/i18n/unicode/numberformatter.h, icu4c/source/i18n/units_complexconverter.cpp, icu4c/source/i18n/units_complexconverter.h, icu4c/source/i18n/units_converter.cpp, icu4c/source/i18n/units_converter.h, icu4c/source/i18n/units_router.cpp, icu4c/source/i18n/units_router.h, icu4c/source/test/depstest/dependencies.txt, icu4c/source/test/intltest/numbertest_api.cpp, icu4c/source/test/intltest/units_test.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/number/UnitConversionHandler.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/UsagePrefsHandler.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/ComplexUnitsConverter.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/MeasureUnitImpl.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitConverter.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitPreferences.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitsRouter.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/impl/UnitsTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
Closes: icu-units#73
Closes: icu-units#103
=> ICU-20568 Fix "1 foot 12 inches" behaviour

docs/userguide/editing.md, docs/userguide/icu4c-readme.md
Initial work on updating Readme.  PR represents progress in converting the ICU4C Readme to Markdown for the new ICU User Guide.  Also includes update of user guide editing instructions.
=> ICU-21034 Progress in converting ICU4C Readme to markdown

icu4c/source/common/uniquecharstr.h
Clarify how to use this internal helper class.
https://unicode-org.atlassian.net/browse/ICU-21236
=> ICU-21236 better document UniqueCharStrings

icu4c/source/common/localematcher.cpp
https://unicode-org.atlassian.net/browse/ICU-20846
=> ICU-20846 remove header guard from .cpp file

tools/scripts/icu-file-utf8-check.py
quite well into what the script is doing already.
Note that one file, 'testrunner.cmd', contains \r, which seems to
be acceptable since it is a Windows file.
=> ICU-21248 Adds line ending check to Travis CI check. The eol check fits

icu4j/main/classes/core/src/com/ibm/icu/impl/units/MeasureUnitImpl.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/SingleUnitImpl.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitConverter.java, icu4j/main/classes/core/src/com/ibm/icu/util/MeasureUnit.java
=> ICU-21010 add the @draft to the public methods

.github/pull_request_template.md
https://unicode-org.atlassian.net/browse/ICU-21257
=> ICU-21257 remove #License suffix from pull request template

icu4c/source/common/unicode/localematcher.h
https://unicode-org.atlassian.net/browse/ICU-21124
=> ICU-21124 fix minor LocaleMatcher API doc issues

icu4c/source/common/unicode/bytestrie.h, icu4c/source/common/unicode/localebuilder.h, icu4c/source/common/unicode/localematcher.h, icu4c/source/common/unicode/locid.h, icu4c/source/common/unicode/stringpiece.h, icu4c/source/common/unicode/ucharstrie.h, icu4c/source/common/unicode/uloc.h, icu4c/source/common/unicode/utrace.h, icu4c/source/i18n/number_asformat.h, icu4c/source/i18n/unicode/numberformatter.h, icu4c/source/i18n/unicode/reldatefmt.h, icu4c/source/i18n/unicode/ucal.h
Updated the `@draft ICU 65` documentation tags to `@stable ICU 65`.  See https://docs.google.com/spreadsheets/d/1JNV3j4qu_ezpKqXRWTFfyA-Jscss9tqowd-tLTl8dWM/edit#gid=0 for details.
=> ICU-21249 ICU4C API promotions

icu4j/main/classes/core/src/com/ibm/icu/number/Precision.java, icu4j/main/classes/core/src/com/ibm/icu/text/RelativeDateTimeFormatter.java, icu4j/main/classes/core/src/com/ibm/icu/util/LocaleMatcher.java, icu4j/main/classes/core/src/com/ibm/icu/util/LocalePriorityList.java, icu4j/main/classes/core/src/com/ibm/icu/util/TimeZone.java, icu4j/main/classes/core/src/com/ibm/icu/util/ULocale.java
See https://docs.google.com/spreadsheets/d/1OIezmSf2mN-hiRnIrpwugCHTzCFIm_-GyeA3ng4QFP8
=> ICU-21249 ICU4J 68 API status updates

icu4j/main/classes/core/src/com/ibm/icu/impl/number/LongNameMultiplexer.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/MicroProps.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/MixedUnitLongNameHandler.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/UnitConversionHandler.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/UsagePrefsHandler.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/ComplexUnitsConverter.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/ConversionRates.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/MeasureUnitImpl.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitConverter.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitPreferences.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitsData.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitsRouter.java, icu4j/main/classes/core/src/com/ibm/icu/text/DateIntervalFormat.java, icu4j/main/classes/core/src/com/ibm/icu/util/MeasureUnit.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/MeasureUnitTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/impl/UnitsTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/ULocaleTest.java
=> ICU-21249 ICU 68 BRS - Clean up import statements

icu4c/source/i18n/rematch.cpp
=> ICU-21293 Fix typo in rematch.cpp comment

icu4j/main/classes/core/src/com/ibm/icu/text/PluralRules.java, icu4j/main/classes/core/src/com/ibm/icu/util/MeasureUnit.java
=> ICU-21249 Fix API status tag issues

icu4j/main/classes/core/src/com/ibm/icu/number/NumberFormatterSettings.java
=> ICU-21249 Fixing javadoc errors

icu4j/main/classes/core/src/com/ibm/icu/impl/units/ConversionRates.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/MeasureUnitImpl.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/SingleUnitImpl.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitConverter.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitsData.java, icu4j/main/classes/core/src/com/ibm/icu/util/HebrewCalendar.java, icu4j/main/classes/core/src/com/ibm/icu/util/MeasureUnit.java, icu4j/main/classes/core/src/com/ibm/icu/util/ULocale.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/calendar/JapaneseTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/DateIntervalFormatTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/impl/UnitsTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberSkeletonTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/rbbi/RBBITestMonkey.java
=> ICU-21249 Fixing java/javadoc compiler warnings.

icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitConverter.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitsData.java, icu4j/main/classes/core/src/com/ibm/icu/util/ULocale.java
=> ICU-21249 Fixed some coding problems found by Spotbugs

icu4c/source/i18n/measunit.cpp, icu4c/source/i18n/number_longnames.cpp, icu4c/source/i18n/number_skeletons.cpp, icu4c/source/i18n/number_skeletons.h, icu4c/source/i18n/unicode/measunit.h, icu4c/source/test/intltest/measfmttest.cpp, icu4c/source/test/intltest/numbertest.h, icu4c/source/test/intltest/numbertest_api.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/number/LongNameHandler.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/MeasureUnitImpl.java, icu4j/main/classes/core/src/com/ibm/icu/number/NumberSkeletonImpl.java, icu4j/main/classes/core/src/com/ibm/icu/util/MeasureUnit.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/MeasureUnitTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
Closes icu-units#35, closes icu-units#59.
=> ICU-21266 Support toSkeleton() for all functional Unit Formatters

icu4j/main/classes/core/src/com/ibm/icu/util/MeasureUnit.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
=> ICU-21249 Fixed warnings in last minute changes for 68RC

icu4c/APIChangeReport.html, icu4c/APIChangeReport.md, icu4j/APIChangeReport.html
=> ICU-21249 API Change Reports for C++ and Java

icu4c/source/common/unicode/docmain.h
https://unicode-org.atlassian.net/browse/ICU-21249
=> ICU-21249 add unumberrangeformatter.h to API docs main page

icu4c/readme.html, icu4j/readme.html
These are the remaining changes for updating the Readme files for the BRS for 68 RC.
It seems like many of the changes for the ICU4C Readme were previously done by @erik0686 and @daniel-ju during the work in https://github.com/unicode-org/icu/commit/ba3b6acd5c2599466c3b3fb460212c438f556768 (thanks!)
=> ICU-21249 BRS68RC Remaining updates for Readmes for ICU4C and ICU4J

icu4j/main/classes/core/src/com/ibm/icu/util/VersionInfo.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/VersionInfoTest.java
https://unicode-org.atlassian.net/browse/ICU-20901
=> ICU-20901 VersionInfo.compareTo() compare signed version int as unsigned

tools/release/java/readme.txt
=> ICU-21249 Update release readme for C++ API change report files

icu4c/source/test/cintltst/cldrtest.c
Original plan was to add a test to demonstrate that the reported problem no longer occurs. But in fact it does still occur, so this will need to be expanded to actually fix the problem.
=> ICU-13259 Check whether ulocdata_getDelimiter works in various locales including fr_CA

icu4c/source/i18n/units_converter.h
=> ICU-21337 Remove U_I18N_API from enum.

icu4j/main/classes/core/src/com/ibm/icu/impl/units/MeasureUnitImpl.java
=> ICU-21308 Fix units parser thread safety issue

icu4c/source/i18n/number_skeletons.cpp, icu4c/source/test/intltest/numbertest.h, icu4c/source/test/intltest/numbertest_api.cpp, icu4c/source/test/intltest/numbertest_skeletons.cpp, icu4j/main/classes/core/src/com/ibm/icu/number/NumberSkeletonImpl.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberSkeletonTest.java
=> ICU-21339 toSkeleton: treat percent and permille correctly

icu4j/main/classes/core/src/com/ibm/icu/impl/number/CompactData.java
This ports https://github.com/unicode-org/icu/pull/1296 to the internal CLDR API that Mark was using.
=> ICU-21333 Port fix from ICU-21258 to internal CLDR API

icu4c/source/common/locid.cpp, icu4c/source/test/intltest/loctest.cpp, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/ULocaleTest.java
Also add same unit test in Java which have no problem.
=> ICU-21344 Fix wrong passing of script in Locale.

icu4c/source/common/unicode/docmain.h, icu4c/source/i18n/listformatter.cpp, icu4c/source/i18n/unicode/listformatter.h, icu4c/source/i18n/unicode/ulistformatter.h
Also fixes ICU-20957 and ICU-21286.
=> ICU-21334 Promote ICU4C ListFormatter openForType to stable.

icu4j/main/classes/core/src/com/ibm/icu/impl/units/MeasureUnitImpl.java
=> ICU-21308 Fix icu4j build for Java 7 in MeasureUnitImpl

icu4c/source/test/depstest/dependencies.txt
This is to fix the dep breakage I introduced in #1422
=> ICU-21344 merge localebuilder into resourcebundle

icu4c/source/test/intltest/units_test.cpp, icu4j/main/tests/core/src/com/ibm/icu/dev/test/impl/UnitsTest.java
=> ICU-21349 Some improvements to UnitsTest

icu4c/source/test/intltest/units_test.cpp, icu4j/main/tests/core/src/com/ibm/icu/dev/test/impl/UnitsTest.java
This PR addresses remaining TODO(icu-units#100) comments - almost just a refactoring. They're no longer memory-leak related, so this is tracked under ticket ICU-21349.
This PR specifically doesn't do more: since fixing/refactoring some of the existing unit tests highlighted that precision/rounding thresholds could do with more attention, I've added a TODO(icu-units#108).
Two assignees and reviewers suggested: someone may unassign themselves. :-)
Two separate commits initially, in order to demonstrate a change I'm making (that's more than just refactoring), as well as temporarily demonstrate how double precision works in practice, relative to decimal literals. See 5c4b6e0 for these intermediate changes.
=> ICU-21349 Refactor testComplexUnitsConverter

icu4c/source/common/locid.cpp
=> ICU-21373 Remove wrong cast to avoid CFI

icu4c/source/common/locid.cpp, icu4c/source/common/uloc.cpp, icu4c/source/test/cintltst/cloctst.c, icu4c/source/test/intltest/loctest.cpp
=> ICU-21385 Fix assertion when setKeywordValue w/ long value.

icu4c/source/common/rbbitblb.cpp
=> ICU-21395 Fix UBSan breakage on 8bit of rbbi

icu4c/source/test/intltest/numbertest_api.cpp, icu4j/main/classes/core/src/com/ibm/icu/number/NumberFormatterSettings.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
=> ICU-21394 Don't use null to test for unset ICU4J NumberFormatter options

icu4c/source/test/perf/collationperf/collperf.cpp, icu4c/source/test/perf/howExpensiveIs/howExpensiveIs.cpp, icu4c/source/test/perf/howExpensiveIs/sieve.cpp, icu4c/source/test/perf/normperf/normperf.h, icu4c/source/test/perf/normperf/simplenormperf.cpp, icu4c/source/test/perf/usetperf/bitset.cpp
=> ICU-21391 Make test/perf compile

icu4c/source/i18n/formatted_string_builder.cpp, icu4c/source/test/intltest/listformattertest.cpp, icu4c/source/test/intltest/listformattertest.h
=> ICU-21410 fix int32_t overflow in listFormat

icu4c/source/i18n/measunit.cpp
Still marked "draft": in case we find more performance improvements. But maybe worth submitting this now already, even if we have another PR later?
=> ICU-21387 measunit: check for nullptr before calling delete

icu4c/source/i18n/unicode/measunit.h, icu4j/main/classes/core/src/com/ibm/icu/util/MeasureUnit.java
Closes: https://github.com/icu-units/icu/issues/77
=> ICU-21349 Small improvements to MeasureUnit comments

icu4c/source/i18n/measunit.cpp, icu4c/source/i18n/measunit_extra.cpp, icu4c/source/i18n/measunit_impl.h, icu4c/source/i18n/number_formatimpl.cpp, icu4c/source/i18n/number_longnames.cpp, icu4c/source/i18n/number_usageprefs.cpp, icu4c/source/i18n/units_converter.cpp, icu4c/source/test/intltest/measfmttest.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/units/MeasureUnitImpl.java
=> ICU-21349 Make appendSingleUnit behaviour in C++ comply with Java

icu4c/source/common/locid.cpp, icu4c/source/test/intltest/loctest.cpp, icu4c/source/test/intltest/loctest.h
=> ICU-21419 Fix memory leak in AliasReplacer

icu4c/source/test/intltest/measfmttest.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/units/ComplexUnitsConverter.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/ConversionRates.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/SingleUnitImpl.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitConverter.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/MeasureUnitTest.java
Closes: https://github.com/icu-units/icu/issues/87
Closes: https://github.com/icu-units/icu/issues/116
=> ICU-21349 ensure parser behave the same and add import test cases to Java Code

icu4j/readme.html
@erik0686 has already covered the ICU4C Readme version update (thanks!) in https://github.com/unicode-org/icu/pull/1495/files#r534507835, so this PR is just for the remaining ICU4J Readme version update.
=> ICU-21405 Update ICU4J Readme for BRS 68.2

icu4c/source/common/locid.cpp, icu4c/source/test/intltest/loctest.cpp
=> ICU-21430 propagate error code

icu4c/source/common/ustr_wcs.cpp, icu4c/source/i18n/basictz.cpp, icu4c/source/i18n/rbt_pars.cpp, icu4c/source/i18n/rbt_pars.h, icu4c/source/i18n/reldatefmt.cpp, icu4c/source/i18n/unicode/rbnf.h, icu4c/source/test/cintltst/cformtst.h, icu4c/source/tools/ctestfw/uperf.cpp, icu4c/source/tools/toolutil/xmlparser.cpp, icu4j/main/classes/core/src/com/ibm/icu/text/NumberFormat.java, icu4j/main/classes/translit/src/com/ibm/icu/text/TransliteratorParser.java, icu4j/tools/misc/src/com/ibm/icu/dev/tool/ime/translit/TransliteratorInputMethodDescriptor.java, tools/unicodetools/com/ibm/rbm/gui/BundleItemCreationDialog.java
=> ICU-21416 Fix typos in comments

.ci-builds/.azure-pipelines.yml, .ci-builds/.azure-valgrind.yml, .github/workflows/icu_ci.yml, icu4c/source/configure, icu4c/source/configure.ac, icu4c/source/test/letest/PortableFontInstance.cpp, icu4c/source/test/letest/SimpleFontInstance.cpp, icu4c/source/test/letest/cmaps.cpp
ICU-13837
- also update configure.ac that was missed in #1265 cad3903cc25c0db7f392adbc024829aea6591a50 ICU-21051
- also, some FALSE/TRUE were missed in source/test/letest
-----
Notes:
- see https://github.com/harfbuzz/icu-le-hb/issues/13 about building icu-le-hb
-  I did not fix some FALSE/TRUE that may be in source/samples/layout as I do not have a way to test it currently.
=> ICU-13837 c build: make --disable-layoutex the default

icu4c/source/common/unicode/urename.h
=> ICU-21405 Cherry-pick maintenance commits from master to maint/maint-68

icu4c/source/common/charstr.cpp, icu4c/source/common/charstr.h, icu4c/source/common/util.h, icu4c/source/i18n/measunit_extra.cpp, icu4c/source/i18n/measunit_impl.h, icu4c/source/i18n/unicode/measunit.h, icu4c/source/test/intltest/strtest.cpp, icu4c/source/test/intltest/strtest.h, icu4j/main/classes/core/src/com/ibm/icu/impl/units/MeasureUnitImpl.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/SingleUnitImpl.java
Closes: https://github.com/icu-units/icu/issues/79
=> ICU-21349 Adjust C++ `MeasureUnitImpl::serialize` to be as same as the Java one

icu4j/main/tests/core/src/com/ibm/icu/dev/test/impl/UnitsTest.java
Closes: https://github.com/icu-units/icu/issues/92
=> ICU-21349 move testConverter from C++ to Java

icu4c/source/i18n/measunit_extra.cpp, icu4c/source/i18n/measunit_impl.h, icu4c/source/i18n/number_formatimpl.cpp, icu4c/source/i18n/number_longnames.cpp, icu4c/source/i18n/number_longnames.h, icu4c/source/i18n/number_microprops.h, icu4c/source/i18n/number_usageprefs.cpp, icu4c/source/i18n/number_usageprefs.h, icu4c/source/i18n/units_complexconverter.cpp, icu4c/source/i18n/units_complexconverter.h, icu4c/source/test/intltest/numbertest_api.cpp, icu4c/source/test/intltest/units_test.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/number/MicroProps.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/MixedUnitLongNameHandler.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/UnitConversionHandler.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/UsagePrefsHandler.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/ComplexUnitsConverter.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/MeasureUnitImpl.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitsRouter.java, icu4j/main/classes/core/src/com/ibm/icu/number/NumberFormatterImpl.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/impl/UnitsTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
Closes: https://github.com/icu-units/icu/issues/97 
Closes: https://github.com/icu-units/icu/issues/119
=> ICU-21349 Enhance Supporting Mixed Unit (such as "inch-and-foot")

icu4c/source/i18n/measunit_extra.cpp, icu4c/source/i18n/measunit_impl.h, icu4c/source/i18n/unicode/measunit.h, icu4c/source/i18n/units_converter.cpp, icu4c/source/i18n/units_converter.h, icu4c/source/test/intltest/measfmttest.cpp, icu4c/source/test/intltest/numbertest_api.cpp, icu4c/source/test/intltest/units_test.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/units/ConversionRates.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/MeasureUnitImpl.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/SingleUnitImpl.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitConverter.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitsData.java, icu4j/main/classes/core/src/com/ibm/icu/util/MeasureUnit.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/MeasureUnitTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/impl/UnitsTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
Resolves: https://github.com/icu-units/icu/issues/114
=> ICU-21357 Support IEC Binary Prefixes in MeasureUnit

icu4c/source/i18n/unicode/measunit.h, icu4j/main/classes/core/src/com/ibm/icu/util/MeasureUnit.java
**This touches the headers / public API docs, so I believe it needs a quick review via icu-design?**
Closes: https://github.com/icu-units/icu/issues/106
=> ICU-21349 Improve forIdentifier docs to exclude long_unit_identifier.

icu4c/source/tools/genrb/reslist.cpp, icu4c/source/tools/genrb/reslist.h
=> ICU-21466 Remove size limit of intvector

docs/userguide/transforms/bidi.md
https://unicode-org.atlassian.net/browse/ICU-13435
=> ICU-13435 more RTL languages

icu4c/source/data/misc/units.txt, icu4c/source/i18n/units_data.cpp, icu4c/source/i18n/units_router.cpp, icu4c/source/test/intltest/numbertest_api.cpp, icu4c/source/test/intltest/units_data_test.cpp, icu4c/source/test/testdata/cldr/units/unitPreferencesTest.txt, icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitPreferences.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitsData.java, icu4j/main/shared/data/icudata.jar, icu4j/main/shared/data/icutzdata.jar, icu4j/main/shared/data/testdata.jar, icu4j/main/tests/core/src/com/ibm/icu/dev/test/impl/UnitsTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
Fixes: https://github.com/icu-units/icu/issues/124
=> ICU-21451 Implement inverse unit handling for new consumption unit preferences in CLDR

icu4c/source/i18n/units_complexconverter.cpp, icu4c/source/i18n/units_complexconverter.h, icu4c/source/i18n/units_converter.cpp, icu4c/source/i18n/units_converter.h, icu4c/source/test/intltest/units_test.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/units/ComplexUnitsConverter.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/ConversionRates.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitsConverter.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/impl/UnitsTest.java
=> ICU-21349 Change UnitConverter name to UnitsConverter

icu4c/source/test/letest/cletest.c, icu4c/source/test/letest/cletest.sln, icu4c/source/test/letest/gendata.cpp, icu4c/source/test/letest/gendata.sln, icu4c/source/test/letest/letest.cpp, icu4c/source/test/letest/letest.sln, icu4c/source/test/letest/xmlreader.cpp
=> ICU-21440 letest updated to true/false from TRUE/FALSE

icu4c/source/test/intltest/units_test.cpp, icu4c/source/test/testdata/cldr/units/unitPreferencesTest.txt, icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitsConverter.java, icu4j/main/tests/core/src/com/ibm/icu/dev/data/cldr/units/unitPreferencesTest.txt, icu4j/main/tests/core/src/com/ibm/icu/dev/test/impl/UnitsTest.java
unitPreferencesTest.txt was added to this PR by "ant copy-cldr-testdata" provided with a CLDR_DIR having release-39-alpha0 checked out.
Contributes to: icu-units#82
=> ICU-21349 Fix ICU4J reciprocal unit conversions

docs/userguide/dev/codingguidelines.md
https://unicode-org.atlassian.net/browse/ICU-21050
=> ICU-21050 add detail for when need to ifndef C++ boilerplate

icu4c/source/common/ubrk.cpp, icu4c/source/common/unicode/ubrk.h, icu4c/source/test/cintltst/cbiapts.c
=> ICU-21455 Add new API ubrk_clone() and deprecate ubrk_safeClone()

icu4c/source/i18n/measfmt.cpp, icu4c/source/i18n/unicode/listformatter.h, icu4c/source/test/intltest/listformattertest.cpp, icu4c/source/test/intltest/listformattertest.h, icu4j/main/classes/core/src/com/ibm/icu/text/ListFormatter.java, icu4j/main/classes/core/src/com/ibm/icu/text/MeasureFormat.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/ListFormatterTest.java
=> ICU-20888 Hide or remove old list formatter methods

icu4c/source/i18n/measunit_impl.h, icu4c/source/test/intltest/measfmttest.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/units/SingleUnitImpl.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/MeasureUnitTest.java
=> ICU-21284 Deal with remaining unit normalization TODOs

icu4j/main/classes/core/src/com/ibm/icu/util/MeasureUnit.java
=> ICU-21067 Maybe fix synchronization lint in MeasureUnit.java

icu4c/source/i18n/formattedval_impl.h, icu4c/source/i18n/formattedval_sbimpl.cpp, icu4c/source/i18n/listformatter.cpp, icu4c/source/i18n/numrange_impl.cpp, icu4c/source/i18n/unicode/uformattedvalue.h, icu4c/source/test/cintltst/unumberrangeformattertst.c, icu4c/source/test/intltest/numbertest_range.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/FormattedStringBuilder.java, icu4j/main/classes/core/src/com/ibm/icu/impl/FormattedValueStringBuilderImpl.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/range/PrefixInfixSuffixLengthHelper.java, icu4j/main/classes/core/src/com/ibm/icu/number/FormattedNumberRange.java, icu4j/main/classes/core/src/com/ibm/icu/number/NumberRangeFormatter.java, icu4j/main/classes/core/src/com/ibm/icu/number/NumberRangeFormatterImpl.java, icu4j/main/classes/core/src/com/ibm/icu/text/ListFormatter.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberRangeFormatterTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/serializable/FormatHandler.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/serializable/SerializableTestUtility.java
=> ICU-20421 Add span fields to NumberRangeFormatter

icu4c/source/i18n/unicode/numberrangeformatter.h
See also https://github.com/ovalhub/pyicu/issues/135
=> ICU-21210 Fix Visual Studio static builds

icu4c/source/i18n/units_complexconverter.cpp, icu4c/source/i18n/units_complexconverter.h, icu4c/source/test/intltest/units_test.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/units/ComplexUnitsConverter.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/impl/UnitsTest.java
=> ICU-21349 Add extra ComplexUnitsConverter constructor that takes only CLDR units Identifier

icu4c/source/test/intltest/measfmttest.cpp
=> ICU-21432 Fix TestInternalMeasureUnitImpl() segfaulting with bad data

icu4c/source/i18n/units_converter.cpp, icu4c/source/i18n/units_converter.h, icu4c/source/test/intltest/units_test.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitsConverter.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/impl/UnitsTest.java
closes: https://github.com/icu-units/icu/issues/135
=> ICU-21349 Add extra UnitsConverter constructor that takes only CLDR unit identifiers

icu4c/source/common/resource.h, icu4c/source/common/restrace.cpp, icu4c/source/i18n/measunit_extra.cpp, icu4c/source/i18n/measunit_impl.h, icu4c/source/i18n/number_formatimpl.cpp, icu4c/source/i18n/number_longnames.cpp, icu4c/source/i18n/number_longnames.h, icu4c/source/i18n/unicode/measunit.h, icu4c/source/test/intltest/numbertest.h, icu4c/source/test/intltest/numbertest_api.cpp
Closes: icu-units#115, closes: icu-units#27
=> ICU-20941 NumberFormatter: format arbitrary compound units, with inflections

icu4j/main/classes/core/src/com/ibm/icu/impl/number/LongNameHandler.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/LongNameMultiplexer.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/MacroProps.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/MicroProps.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/MixedUnitLongNameHandler.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/UsagePrefsHandler.java, icu4j/main/classes/core/src/com/ibm/icu/number/FormattedNumber.java, icu4j/main/classes/core/src/com/ibm/icu/number/LocalizedNumberFormatter.java, icu4j/main/classes/core/src/com/ibm/icu/number/NumberFormatterImpl.java, icu4j/main/classes/core/src/com/ibm/icu/number/NumberFormatterSettings.java, icu4j/main/classes/core/src/com/ibm/icu/number/NumberSkeletonImpl.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
=> ICU-21123 Support unit inflections in ICU4J

docs/userguide/design.md
This change is narrowly focused on the initialization and cleanup / termination
of ICU. The whole user-guide section (file) needs to be reviewed for out-of-date
information, but not as part of this change.
=> ICU-21346 Update user guide section on initialization.

.github/pull_request_template.md
=> ICU-21480 Update GitHub pull request template to note JIRA issue is needed on commit message(s)

.github/workflows/icu_ci.yml
each pull request. This test has a high catch rate.
=> ICU-21323 Adds BRS task 'test ICU4C without data' to GHA, triggered by

icu4j/main/classes/core/src/com/ibm/icu/text/BurmeseBreakEngine.java, icu4j/main/classes/core/src/com/ibm/icu/text/KhmerBreakEngine.java, icu4j/main/classes/core/src/com/ibm/icu/text/LaoBreakEngine.java, icu4j/main/classes/core/src/com/ibm/icu/text/ThaiBreakEngine.java
=> ICU-21179 Remove unused code in Java break engines

docs/userguide/format_parse/numbers/skeletons.md, icu4c/source/i18n/number_rounding.cpp, icu4c/source/i18n/number_skeletons.cpp, icu4c/source/i18n/unicode/numberformatter.h, icu4c/source/i18n/unicode/unumberformatter.h, icu4c/source/test/intltest/numbertest_api.cpp, icu4c/source/test/intltest/numbertest_skeletons.cpp, icu4j/main/classes/core/src/com/ibm/icu/number/FractionPrecision.java, icu4j/main/classes/core/src/com/ibm/icu/number/NumberFormatter.java, icu4j/main/classes/core/src/com/ibm/icu/number/NumberSkeletonImpl.java, icu4j/main/classes/core/src/com/ibm/icu/number/Precision.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberSkeletonTest.java
=> ICU-20019 Implement withSignificantDigits option

icu4j/main/classes/core/src/com/ibm/icu/impl/OlsonTimeZone.java, icu4j/main/classes/core/src/com/ibm/icu/text/SimpleDateFormat.java, icu4j/main/classes/core/src/com/ibm/icu/util/BasicTimeZone.java, icu4j/main/classes/core/src/com/ibm/icu/util/Calendar.java, icu4j/main/classes/core/src/com/ibm/icu/util/RuleBasedTimeZone.java, icu4j/main/classes/core/src/com/ibm/icu/util/SimpleTimeZone.java, icu4j/main/classes/core/src/com/ibm/icu/util/VTimeZone.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/timezone/TimeZoneOffsetLocalTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/timezone/TimeZoneRuleTest.java
Some updates based on PR #1571 submitted by @FrankYFTang
=> ICU-21490 Exposing getOffsetFromLocal for ICU4J

icu4c/source/i18n/basictz.cpp, icu4c/source/i18n/olsontz.cpp, icu4c/source/i18n/olsontz.h, icu4c/source/i18n/rbtz.cpp, icu4c/source/i18n/simpletz.cpp, icu4c/source/i18n/ucal.cpp, icu4c/source/i18n/unicode/basictz.h, icu4c/source/i18n/unicode/rbtz.h, icu4c/source/i18n/unicode/simpletz.h, icu4c/source/i18n/unicode/ucal.h, icu4c/source/i18n/unicode/vtzone.h, icu4c/source/i18n/vtzone.cpp, icu4c/source/test/cintltst/ccaltst.c, icu4c/source/test/intltest/tzoffloc.cpp
Updated based on @FrankYFTang's PR #1556.
=> ICU-21372 getOffsetFromLocal for C and C++

.github/workflows/icu_ci.yml
=> ICU-21323 Automates BRS testing tasks of U_CHARSET_IS_UTF8 and

icu4c/readme.html, icu4j/readme.html
=> ICU-21480 BRS69RC update readmes for RC

icu4c/source/common/unicode/bytestream.h, icu4c/source/common/unicode/localematcher.h, icu4c/source/common/unicode/locid.h, icu4c/source/common/unicode/stringpiece.h, icu4c/source/common/unicode/utrace.h, icu4c/source/i18n/unicode/dtptngen.h, icu4c/source/i18n/unicode/measunit.h, icu4c/source/i18n/unicode/udat.h, icu4c/source/i18n/unicode/udateintervalformat.h, icu4c/source/i18n/unicode/udatpg.h
=> ICU-21480 Promoted all @draft ICU 67 APIs to @stable ICU 67.

icu4c/source/i18n/dtitvfmt.cpp, icu4c/source/test/intltest/dtifmtts.cpp, icu4c/source/test/intltest/dtifmtts.h, icu4j/main/classes/core/src/com/ibm/icu/text/DateIntervalFormat.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/DateIntervalFormatTest.java
=> ICU-21222 Fix Era in Interval format

.github/workflows/icu_ci.yml
=> ICU-21323 Automates BRS test task of build and run testmap.

icu4c/source/common/putil.cpp
=> ICU-21498 Improve comment in uprv_tzname

docs/userguide/icu4c-readme.md
Syntax error, it should be:
git clone https://github.com/unicode-org/icu.git
=> ICU-21416 Update icu4c-readme.md

icu4c/source/common/bytestriebuilder.cpp, icu4c/source/common/unicode/bytestrie.h, icu4c/source/common/unicode/bytestriebuilder.h, icu4c/source/test/intltest/bytestrietest.cpp, icu4j/main/classes/core/src/com/ibm/icu/util/BytesTrie.java, icu4j/main/classes/core/src/com/ibm/icu/util/BytesTrieBuilder.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/BytesTrieTest.java
https://unicode-org.atlassian.net/browse/ICU-21368
=> ICU-21368 unit-test & fix BytesTrie jump delta encoding

icu4c/source/common/uresimp.h, icu4c/source/i18n/number_longnames.cpp, icu4c/source/test/intltest/numbertest_api.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/number/LongNameHandler.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/MixedUnitLongNameHandler.java, icu4j/main/classes/core/src/com/ibm/icu/number/FormattedNumber.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
=> ICU-21123 Calculate built-in units' gender when CLDR lacks the data

icu4j/main/classes/core/src/com/ibm/icu/text/DateIntervalFormat.java, icu4j/main/classes/core/src/com/ibm/icu/text/ListFormatter.java, icu4j/main/classes/core/src/com/ibm/icu/text/RelativeDateTimeFormatter.java
=> ICU-21480 Change ICU 64 draft readResolve APIs to @internal

icu4c/source/i18n/number_compact.cpp, icu4c/source/i18n/number_compact.h, icu4c/source/i18n/standardplural.cpp, icu4c/source/i18n/standardplural.h, icu4c/source/test/intltest/numbertest.h, icu4c/source/test/intltest/numbertest_api.cpp, icu4c/source/test/intltest/numbertest_decimalquantity.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/StandardPlural.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/CompactData.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/DecimalQuantity.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/DecimalQuantity_AbstractBCD.java, icu4j/main/classes/core/src/com/ibm/icu/number/CompactNotation.java, icu4j/main/classes/core/src/com/ibm/icu/text/PluralRules.java, icu4j/main/tests/core/src/com/ibm/icu/dev/impl/number/DecimalQuantity_SimpleStorage.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/DecimalQuantityTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
=> ICU-21330 Use =0 and =1 plural forms in compact notation

icu4j/APIChangeReport.html
=> ICU-21480 Update ICU4J APIChangeReport.html to 69

icu4c/source/common/unicode/docmain.h
=> ICU-21480 BRS-50: updated docmain.h

icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/PluralRulesTest.java
=> ICU-21480 update logKnownIssue number

icu4c/source/common/locid.cpp, icu4j/main/classes/core/src/com/ibm/icu/util/ULocale.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/ULocaleTest.java
=> ICU-21480 Scrub TODOs for completed issues 21292 and 21236

icu4c/readme.html, icu4j/readme.html
Much of the BRS Readme update work is the version change in the text, and Erik already covered most of that for v69 in his [version update PR](https://github.com/unicode-org/icu/pull/1567) (thanks!), both for ICU4C and ICU4J. The only remaining piece is the "last updated" date.
=> ICU-21480 Change ICU4C/J Readme update date after version change

.ci-builds/.azure-pipelines.yml, .github/workflows/icu_ci.yml
Also update the Azure CI so that it makes the "List failures" step show up as a red X in the UI if there are any failures.
=> ICU-21542 Have GHA output ICU4J test failures if there are any.

icu4c/source/i18n/double-conversion-double-to-string.cpp, icu4c/source/i18n/double-conversion-double-to-string.h, icu4c/source/i18n/double-conversion-string-to-double.cpp, icu4c/source/i18n/double-conversion-strtod.cpp, icu4c/source/i18n/double-conversion-strtod.h, icu4c/source/i18n/double-conversion-utils.h, vendor/double-conversion/upstream/.gitignore, vendor/double-conversion/upstream/double-conversion/double-to-string.cc, vendor/double-conversion/upstream/double-conversion/double-to-string.h, vendor/double-conversion/upstream/double-conversion/string-to-double.cc, vendor/double-conversion/upstream/double-conversion/strtod.cc, vendor/double-conversion/upstream/double-conversion/strtod.h, vendor/double-conversion/upstream/double-conversion/utils.h, vendor/double-conversion/upstream/test/cctest/test-conversions.cc, vendor/double-conversion/upstream/test/cctest/test-strtod.cc
=> ICU-21480 Update double-conversion

icu4c/source/tools/genrb/parse.cpp
=> ICU-21552 Only show the "Encountered empty table warning" in verbose mode

.bazeliskrc, .gitignore, WORKSPACE, icu4c/source/common/BUILD, icu4c/source/data/unidata/changes.txt, icu4c/source/data/unidata/clean.sh, icu4c/source/data/unidata/generate.sh, icu4c/source/data/unidata/norm2/BUILD, icu4c/source/tools/gennorm2/BUILD, icu4c/source/tools/toolutil/BUILD, icu4c/source/tools/toolutil/toolutil.cpp, tools/unicode/c/genprops/BUILD, tools/unicode/c/genprops/bidipropsbuilder.cpp, tools/unicode/c/genprops/casepropsbuilder.cpp, tools/unicode/c/genprops/corepropsbuilder.cpp, tools/unicode/c/genprops/genprops.cpp, tools/unicode/c/genprops/namespropsbuilder.cpp, tools/unicode/c/genprops/pnamesbuilder.cpp
=> ICU-21117 Use Bazel to automate generation of Unicode data files

tools/cldr/cldr-to-icu/pom.xml
This PR is for integrating CLDR release-39-beta2 (the spec beta) into ICU main. There are no actual data changes (but I needed to verify that); the only change is updating the version of the ICU4J libraries specified in tools/cldr/cldr-to-icu/pom.xml and used for the cldr-icu integration.
=> ICU-21546 integrate CLDR release-39-beta2 to ICU maint-69, just affects cldr-icu pom

icu4c/source/common/charstr.cpp, icu4c/source/i18n/number_longnames.cpp
=> ICU-21562 Add include to fix std:abs build problem

icu4c/source/common/filteredbrk.cpp, icu4c/source/common/locid.cpp, icu4c/source/common/uelement.h, icu4c/source/common/uniset.cpp, icu4c/source/common/uvector.cpp, icu4c/source/i18n/uspoof_conf.cpp, icu4c/source/test/intltest/uvectest.cpp
=> ICU-21526 Change return of UElementComparator to int32_t

icu4c/source/tools/genren/README
Regenerated urename.h. There were no updates to it, but I did add a process note to the README for genren.
=> ICU-21546 brs 69, add note about genren process

tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/ant/ConvertIcuDataTask.java
- avoid static init problem from CLDR-14636
=> ICU-21568 Pre-initialize CLDRConfig and SupplementalDataInfo

icu4c/source/i18n/formattedval_sbimpl.cpp, icu4c/source/test/intltest/formattedvaluetest.cpp
=> ICU-21540 Fix FormattedList test and behavior regression

icu4c/source/i18n/plurrule_impl.h
=> ICU-21523 Declare default impl for copy operator for GCC warning

icu4c/source/i18n/smpdtfmt.cpp
Also remove the use of the unsafe double-checked lock idiom in the same
function, SimpleDateFormat::tzFormat(). Synchronization now always uses a
mutex, which is slower, but in the context of format or parse operations,
shouldn't be significant.
Added synchronization to one more unsafe direct reference to a const
SimpleDateFormat::fTimeZoneFormat. In the assignment operator.
=> ICU-21591 Release lock in SimpleDateFormat::tzFormat in case of failure

icu4c/source/common/locid.cpp, icu4c/source/test/intltest/loctest.cpp, icu4c/source/test/intltest/loctest.h
=> ICU-21597 Fix Null-deref W in canonicalizeLocale

icu4j/main/classes/core/src/com/ibm/icu/util/ULocale.java
https://unicode-org.atlassian.net/browse/ICU-21567
No behavior change is expected
=> ICU-21567 Avoid using regex in ULocale.getName()

icu4c/source/test/intltest/locnmtst.cpp
=> ICU-21585 Remove not used var.
