unicode-org/icu

icu4c/source/Makefile.in, icu4c/source/configure, icu4c/source/configure.ac
Make installation of `icu-config` optional.
Users who do not want to install `icu-config` must pass either `--disable-icu-config` or `--enable-icu-config=no` to `configure`.
From version 64.1, `icu-config` will not be installed by default.
Signed-off-by: Hugh McMaster <hugh.mcmaster@outlook.com>
=> ICU-10464 Make installation of icu-config optional

icu4j/main/classes/core/src/com/ibm/icu/impl/locale/XLikelySubtags.java, icu4j/main/classes/core/src/com/ibm/icu/impl/locale/XLocaleDistance.java, icu4j/main/classes/core/src/com/ibm/icu/impl/locale/XLocaleMatcher.java
Incorporates the easiest elements from the new language matcher code that is held locally in Google.
ICU4J builds and all unit tests pass.
=> ICU-13829 Languagematcher: Fixes straightforward code issues.

icu4c/source/common/locid.cpp
The Locale class assignment operator should set the locale to "bogus" if an out-of-memory (OOM) error occurs when attempting to copy data over from the other locale.
=> ICU-20034 Locale assignment operator should set the locale to bogus if OOM occurs.

icu4c/source/common/uniset.cpp
Some of the UnicodeSet constructors methods don't take an error code parameter, meaning that if an OOM error/failure happens during the constructor's execution, it will not reported back to the caller, and the caller has no way to know that the object is in a half-constructed state.
Similar with the assignment operator (operator=), if OOM occurs then there is no way to know that the object that was supposed to be assigned to is now in bad state.
We should mark the object as being in a "bogus" state when this happens.
=> ICU-20035 UnicodeSet constructors and assignment operator should setToBogus when OOM occurs.

icu4c/source/i18n/plurrule.cpp, icu4c/source/i18n/plurrule_impl.h, icu4c/source/i18n/unicode/plurrule.h
Improve the handling of out-of-memory (OOM) errors in the PluralRules class. Use an internal error code to better report errors during clone and copy construction, use LocalPointer in some places to prevent memory leaks when OOM occurs, and also use nullptr instead of NULL.
=> ICU-20042 Improve OOM handling in PluralRules class.

icu4c/source/i18n/unicode/datefmt.h
I missed this when reviewing the changes in PR #29.
=> ICU-13810 Fix typo in datefmt.h

icu4c/source/config/mh-mingw, icu4c/source/config/mh-mingw64
For builds using Cygwin and MSVC with Debug configuration,
'.dll' and '.lib' binaries has 'd' suffix.
Doing the same for builds using mingw and mingw64,
based on the code from MSVC toolchain.
This is a repeat of PR https://github.com/unicode-org/icu/pull/9.
=> ICU-13138 mingw: add 'd' suffix to the names of binary files with Debug configuration

icu4c/source/i18n/rbnf.cpp
There are a few locations in the RuleBasedNumberFormat class that don't check for out-of-memory (OOM) failures.
=> ICU-20046 Fix some OOM issues in the RBNF class.

icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/ULocaleTest.java
Both the number of installed locales and the name of the last locale
change with updates to and customizations of CLDR/ICU data so test
expectations on these values will cause bogus test failures.
=> ICU-20018 Remove hardcoded expectations on available locales.

icu4c/source/Doxyfile.in, icu4c/source/common/unicode/icuplug.h, icu4c/source/common/unicode/utext.h, icu4c/source/i18n/reldtfmt.h, icu4c/source/i18n/unicode/decimfmt.h, icu4c/source/i18n/unicode/smpdtfmt.h, icu4c/source/i18n/unicode/udat.h, icu4c/source/i18n/unicode/unum.h, icu4c/source/i18n/unicode/upluralrules.h, icu4c/source/layoutex/layout/playout.h, icu4c/source/layoutex/layout/plruns.h, icu4c/source/test/intltest/colldata.h
ICU-13685
re-open from #7 
Tech Preview should not be 'do not use', but `@internal` in Doxygen comes with an ominous warning.
Add `@preview` as a doxygen command such that:
> `@preview ICU 4.4` 
gives:
=> ICU-13685  c: add @preview (retry)

icu4c/as_is/bomlist.py, icu4c/source/test/depstest/dependencies.py, icu4c/source/test/depstest/depstest.py, icu4c/source/tools/icu-svnprops-check.py, tools/release/c/bomfix.py, tools/scripts/bldicures.py, tools/unicode/c/genprops/misc/ucdcopy.py, tools/unicode/c/genuca/genteststub.py, tools/unicode/py/parsescriptmetadata.py, tools/unicode/py/preparseucd.py
This will prevent littering the source tree with spurious .pyc files.
The potential faster execution when re-running a script that has an
up-to-date .pyc file is negligible.
=> ICU-20062 Set the Python -B flag to inhibit the writing of .pyc files.

icu4c/source/common/unicode/urename.h, icu4c/source/tools/genren/genren.pl
This is a follow-up to ICU-13814.
In the SVN commit the logic was mixed up for the IntelliSense define. We actually want to turn *off* the renaming defines inside IntelliSense so that  VS doesn't get confused when you press F12.
=> ICU-13814 Fix define for excluding renaming from VS IntelliSense

icu4c/source/common/udata.cpp
When looking at the file paths that are used to open data files in the debugger, it was noticed that ICU very often ends up with double separators in the file paths.
For example, some of the paths end up looking similar to the following:
- "`globalization\icu\\zoneinfo64.res`"
- "`globalization\icu\\metaZones.res`"
- "`.\\timezoneTypes.res`"
Initially, the thinking was that this was because the `UDataPathIterator` class doesn't check if both the current path and the suffix have separators when appending the suffix.
( https://github.com/unicode-org/icu/blob/master/icu4c/source/common/udata.cpp#L605 ).
The initially proposed change (see the attachment on the Issue [ICU-13636](https://unicode-org.atlassian.net/browse/ICU-13686)) added a method to the `CharString` class to check if the string …
=> ICU-13686 ICU4C: Prevent double file separators on data file paths.

icu4c/source/common/rbbirb.cpp, icu4c/source/common/rbbitblb.cpp, icu4c/source/common/rbbitblb.h, icu4c/source/data/brkitr/rules/line.txt, icu4c/source/data/brkitr/rules/line_fi.txt, icu4c/source/data/brkitr/rules/line_loose.txt, icu4c/source/data/brkitr/rules/line_loose_cj.txt, icu4c/source/data/brkitr/rules/line_loose_fi.txt, icu4c/source/data/brkitr/rules/line_normal.txt, icu4c/source/data/brkitr/rules/line_normal_cj.txt, icu4c/source/data/brkitr/rules/line_normal_fi.txt, icu4c/source/test/intltest/rbbitst.cpp, icu4c/source/test/testdata/break_rules/line.txt, icu4c/source/test/testdata/break_rules/line_loose.txt, icu4c/source/test/testdata/break_rules/line_loose_cj.txt, icu4c/source/test/testdata/break_rules/line_normal.txt, icu4c/source/test/testdata/break_rules/line_normal_cj.txt, icu4j/main/classes/core/src/com/ibm/icu/text/RBBIRuleBuilder.java, icu4j/main/classes/core/src/com/ibm/icu/text/RBBITableBuilder.java, icu4j/main/shared/data/icudata.jar, icu4j/main/shared/data/icutzdata.jar, icu4j/main/tests/core/src/com/ibm/icu/dev/test/rbbi/RBBITestMonkey.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/rbbi/break_rules/line.txt, icu4j/main/tests/core/src/com/ibm/icu/dev/test/rbbi/break_rules/line_loose.txt, icu4j/main/tests/core/src/com/ibm/icu/dev/test/rbbi/break_rules/line_loose_cj.txt, icu4j/main/tests/core/src/com/ibm/icu/dev/test/rbbi/break_rules/line_normal.txt, icu4j/main/tests/core/src/com/ibm/icu/dev/test/rbbi/break_rules/line_normal_cj.txt
Includes all line break tailorings.
Corresponding updates to monkey test rules.
State table builder, fix missed table optimization, uncovered by the new LB8 rule.
Fixed bug in RBBI monkey test of Regional Indicators (LB30a) that was uncovered while exhaustive testing the primary (LB 8) changes included here.
=> ICU-7270 Line Break rule LB8 updated for UAX-14 conformance.

icu4c/source/common/putilimp.h, icu4c/source/configure, icu4c/source/configure.ac
=> ICU-12505 U_HAVE_STD_ATOMICS, reduce & simplify configure options.

.gitignore
This reverts commit b3629170a80489a94a8f93d0008beb72584c6540.
Made obsolete by commit bfc0093b7f776f0137ddd7bc9ef98f118842dd6e.
=> ICU-20054 Revert "ICU-20054 Adding depstest *.pyc to gitignore"

icu4c/source/common/umutablecptrie.cpp
Use LocalPointer instead of raw new in umutablecptrie.cpp so that an ErrorCode will be set in the case of out-of-memory (OOM) failure.
=> ICU-13530 Use LocalPointer instead of raw new in umutablecptrie.cpp

icu4j/main/classes/core/src/com/ibm/icu/number/Scale.java
Different implementations of BigDecimal.stripTrailingZeros(), in
different versions of the JDK (and different versions of Android), have
differences in their handling of zero. To avoid this, ICU4J can return
BigDecimal.ZERO for any value that is equal to zero, instead of calling
BigDecimal.stripTrailingZeros() in this problematic case.
=> ICU-20000 Workaround for BigDecimal.stripTrailingZeros() differences.

icu4c/source/i18n/numparse_currency.cpp, icu4c/source/test/intltest/numfmtst.cpp, icu4c/source/test/testdata/numberformattestspecification.txt, icu4j/main/classes/core/src/com/ibm/icu/impl/number/parse/CombinedCurrencyMatcher.java, icu4j/main/tests/core/src/com/ibm/icu/dev/data/numberformattestspecification.txt, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/NumberFormatTest.java
ICU4J 60 and 61 parsed ISO codes as case-insensitive in .parse().  This was changed to case-sensitive as a side-effect of ICU-13736.  However, ICU-13696 says that it is desirable for the codes to be parsed case-insensitive.  This change will make ICU 63, both C and J, have the ICU4J 60 and 61 behavior.
The current ticket, ICU-13696, says that this should be able to be toggled by an `@internal` flag.  I have not included such a flag in this PR, because it is very easy for users to change the behavior back via a patch, and a flag would add complexity, particularly because this feature would want to bubble all the way up to the DecimalFormat API.
Also see http://b/112469513
=> ICU-13696 Parse local currency ISO codes as case-insensitive.

icu4c/source/test/Makefile.in
=> ICU-20051 fix '@goods=: command not found' warning during build

.travis.yml
Enable address sanitizer in Travis build. Make it the default for Clang on Linux builds.
=> ICU-20083 Enable Address sanitizer in ICU4C builds.

icu4c/source/common/common_uwp.vcxproj, icu4c/source/common/putil.cpp, icu4c/source/common/wintz.cpp, icu4c/source/common/wintz.h
Use GetDynamicTimeZoneInformation instead of accessing the Windows registries so that it does not rely on COM in wintz. So that UWP apps could also use this code.
=> ICU-13842 Use GetDynamicTimeZoneInformation instead of Windows registry access in wintz.cpp

icu4c/source/common/rbbi.cpp
=> ICU-20043 Compile warning fix with improved portability.

icu4c/source/common/unicode/ucptrie.h, icu4c/source/common/unicode/umutablecptrie.h
=> ICU-13530 fix doxygen warnings: hide internals, hide struct/enum typedefs, avoid fwd+real struct decl

icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/DateFormatRegressionTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/timezone/TimeZoneTest.java
When running in Android, java.util.TimeZone.getDefault() will only
return a TimeZone object for a time zone that actually exists, so when
passing a bogus test TimeZone object to setDefault() and afterwards
calling getDefault() it won't return that same time zone.
Changing our tests to instead use a real existing (but otherwise unused)
time zone instead makes the tests work in Android as well.
Neither of these tests was testing the ability to set an arbitrarily
made up time zone as the default, so no test coverage is lost.
=> ICU-13483 Use a real time zone to make tests work in Android.

icu4j/main/tests/translit/src/com/ibm/icu/dev/test/translit/TransliteratorDisorderedMarksTest.java, icu4j/main/tests/translit/src/com/ibm/icu/dev/test/translit/TransliteratorTest.java
By extracting this test case into a separate class and separating the
complex and time consuming building of the UnicodeSet disorderedMarks
data structure into an @BeforeClass shared setup method it becomes
possible to test the 18 different transliteration rules as a
parametrized test case.
This will lower the running time per test case and also aid in debugging
as it will make it immediately obvious which transliteration rules cause
test failures (and which don't).
=> ICU-20006 Parameterize the TestSourceTargetSet2 test case.

icu4c/source/common/udata.cpp, icu4c/source/common/umapfile.cpp, icu4c/source/common/umapfile.h, icu4c/source/common/uresbund.cpp
ICU does not report Out-Of-Memory (OOM) if it fails to memory map the data file(s) when calling the platform API(s) to do so.
When you are using ICU with memory-mapped data file(s), and ICU fails to map the data file due to being out-of-memory, it does not bubble this failure up to the API that was called.
For example:
```c++
char localeID[] = u8"en_US";
ucol_getKeywordValuesForLocale("collation", localeID, false, &status);
```
If the memory-mapped data file can't be loaded at all due to being Out-of-memory in the above code snippet, then you will get back the error `U_MISSING_RESOURCE_ERROR`, rather than `U_MEMORY_ALLOCATION_ERROR`, which might be a bit surprising to the caller of the API.
This can lead to the application thinking that there are no resources for "en_US" or "en" (or even …
=> ICU-13712 ICU4C does not report OOM if it fails to memory map the data file(s)

icu4c/source/common/putil.cpp
This pull request is to remove COM dependency in ICU, so that ICU does not need to care about if the caller is a UWP or not. The work is still on going. Make a PR earlier to get some feedback first.
=> ICU-20103 Using GetLocaleInfoEx to get user default locale instead of using language for UWP app.

icu4c/source/common/uloc_tag.cpp, icu4c/source/test/cintltst/cloctst.c, icu4j/main/classes/core/src/com/ibm/icu/impl/locale/LanguageTag.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/ULocaleTest.java
Two bugs were discovered in BCP 47 structural validity check: 1. extlang check 2. private use singleton check. 
BCP 47 has the following for language. extlang subtag can only be
preceded by 2*3ALPHA. Add a check for the length of language subtag
before extlang subtag.
```
language      = 2*3ALPHA            ; shortest ISO 639 code
["-" extlang]       ; sometimes followed by
; extended language subtags
/ 4ALPHA              ; or reserved for future use
/ 5*8ALPHA            ; or registered language subtag
extlang       = 3ALPHA              ; selected ISO 639 codes
*2("-" 3ALPHA)      ; permanently reserved}}
```
With this change, 'hant-cmn-CN' would drop '-cmn-CN' keeping only
'hant'.
In addition, ICU4C has a bug with a privateuse singleton. 'zh-x_t-ab' is invalid, but it's treated the …
=> ICU-20098 Fix BCP47 validity check for extlang and privateuse singleton

icu4c/source/common/putil.cpp, icu4c/source/common/umapfile.cpp
Enable the Windows UWP version of ICU4C to use TZ update/override files (.res files) for out-of-band timezone data updates.
=> ICU-13687 ICU4C Enable Windows UWP version to use TZ update/override files.

icu4c/source/common/unicode/platform.h
Currently `U_FALLTHROUGH` is not defined for GCC, meaning that any `switch case` statements with fall-throughs will generate warnings when building ICU4C.
In GCC 7, they added support for: "`_attribute_((fallthrough))`" which we can now use for `U_FALLTHROUGH`, which eliminates many warnings.
=> ICU-13812 Define U_FALLTHROUGH for GCC 7+ for ICU4C.

icu4c/source/common/locid.cpp, icu4c/source/common/unicode/locid.h, icu4c/source/test/intltest/loctest.cpp, icu4c/source/test/intltest/loctest.h
They are C++ wrappers of uloc_forLanguageTag() and uloc_toLanguageTag()
respectively, that take care of dynamic memory management.
=> ICU-13417 Add the Locale::(for|to)LanguageTag() functions.

icu4c/source/common/locid.cpp, icu4c/source/common/unicode/locid.h, icu4c/source/test/intltest/loctest.cpp, icu4c/source/test/intltest/loctest.h
This is a wrapper of Locale::createKeywords() that under the hood calls
uloc_toUnicodeLocaleKey() for each key before returning it, so that the
caller won't have to do this.
=> ICU-13417 Add the Locale::createUnicodeKeywords() function.

icu4c/source/common/locid.cpp
Follow-up from pull request #117:
Specify buffer size in only one place, explicitly check status before
proceeding and set status = U_MEMORY_ALLOCATION_ERROR if new fails.
=> ICU-13417 Improved error handling in Locale::create(Unicode)?Keywords().

icu4c/source/common/unicode/locid.h, icu4c/source/test/intltest/loctest.cpp, icu4c/source/test/intltest/loctest.h
They are C++ template wrappers around Locale::createKeywords() and
Locale::createUnicodeKeywords() respectively, that write to any
container for which an STL style output iterator can be provided.
The simplest imaginable usage would just look like this:
std::string keys[16];
l.getKeywords<std::string>(keys, status);
The unit test has a more elaborate invocation, writing to an std::set<>.
=> ICU-13417 Add the Locale::get(Unicode)?Keywords() functions.

icu4c/source/common/locid.cpp
Organizing the implementation like this instead will (hopefully) make it
more clear what's being done and make it possible to use analogous
control flow in the copy and move implementations of operator=().
=> ICU-13645 Clean up implementation of Locale::operator=(const Locale&).

icu4c/source/i18n/erarules.cpp, icu4c/source/i18n/erarules.h, icu4c/source/i18n/japancal.cpp, icu4c/source/i18n/unicode/calendar.h
- Enable UWP version of ICU to use Environment variable `ICU_ENABLE_TENTATIVE_ERA` for testing placeholder era names.
- Use `LocalArray<int32_t>` for the Era Start Dates to simply memory management, so that `goto` can be removed.
- Also fix some minor typos in header file.
=> ICU-12973 Enable UWP version of ICU to use Environment variable ICU_ENABLE_TENTATIVE_ERA for testing placeholder names

icu4j/main/classes/translit/src/com/ibm/icu/text/Transliterator.java, icu4j/main/tests/translit/src/com/ibm/icu/dev/test/translit/TransliteratorTest.java
Create a proper hash code with Objects.hash instead of returning 42
=> ICU-20133 Undeprecate Transliterator.Position#hashCode

icu4c/source/common/unicode/platform.h
Clang comes with `__has_declspec_attribute` to detect whether the name of an attribute is implemented as a MS style `__declspec`.
This adds __has_declspect_attribute to the list of clang compatibility macros and then uses that check to determine if `__declspec(dllimport)` and `__declspec(dllexport)` can be used.
=> ICU-20135 Use __has_declspec_attribute for shared builds

icu4c/source/common/putilimp.h
Currently if no value is found on a platform for either `U_TZSET` or `U_TZNAME` the build will fail. This because the value will fall through to the default else.
The configure currently exposes both `U_HAVE_TZSET` and `U_HAVE_TZSET` so this should be checked to provide a predefined value. This adds the same behavior that is present in the `U_TIMEZONE` block.
=> ICU-20136 Check U_HAVE_TZ* values

icu4c/source/i18n/number_fluent.cpp, icu4c/source/i18n/numrange_fluent.cpp, icu4c/source/i18n/unicode/numberformatter.h, icu4c/source/i18n/unicode/numberrangeformatter.h, icu4c/source/test/intltest/numbertest.h, icu4c/source/test/intltest/numbertest_api.cpp, icu4c/source/test/intltest/numbertest_range.cpp
=> ICU-20050 Fixing memory leaks in move and copy assignment in Number*Formatter

icu4c/source/common/locid.cpp, icu4c/source/common/uloc_tag.cpp, icu4c/source/common/ulocimp.h, icu4c/source/common/unicode/uloc.h
If not passed a length, ultag_parse() will call uprv_strlen(), requiring
the input buffer to be NUL terminated. This is unnecessary.
=> ICU-13417 Pass length from Locale::forLanguageTag() to ultag_parse().

icu4c/source/i18n/numparse_scientific.cpp, icu4c/source/test/intltest/numfmtst.cpp, icu4c/source/test/intltest/numfmtst.h, icu4j/main/classes/core/src/com/ibm/icu/impl/number/parse/ScientificMatcher.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/NumberFormatTest.java
Also restricts parsing to read only one exponent per string.
=> ICU-20037 Fixing ScientificMatcher integer overflow.

icu4c/source/common/wintz.cpp
- Use stack allocated UResouceBundle to reduce number of calls to malloc (in a method that can't report back an error if Out-Of-Memory happens).
- Use LocalUResourcePointer for automatic clean-up of UResouceBundle.
- Use uprv_strdup instead of calloc + strcpy.
- Changes comments, formatting, etc.
=> ICU-13827 Clean up ICU4C "wintz.cpp" time zone detection code.

icu4c/source/common/locid.cpp, icu4c/source/i18n/gregocal.cpp, icu4c/source/i18n/gregoimp.h, icu4c/source/i18n/number_types.h, icu4c/source/io/ufmt_cmn.cpp, icu4c/source/io/uprintf.cpp, icu4c/source/io/ustream.cpp, icu4c/source/tools/gencfu/gencfu.cpp, icu4c/source/tools/gencnval/gencnval.c, icu4c/source/tools/gensprep/gensprep.c, icu4c/source/tools/pkgdata/pkgdata.cpp, icu4c/source/tools/toolutil/filestrm.cpp, icu4c/source/tools/toolutil/filetools.cpp, icu4c/source/tools/toolutil/package.cpp, icu4c/source/tools/toolutil/udbgutil.cpp
=> ICU-20147 Fix MSVC warning C4251 for SimpleModifier::fParameters, and other warnings too

icu4j/build.xml, icu4j/main/classes/collate/src/com/ibm/icu/text/CollationElementIterator.java, icu4j/main/classes/collate/src/com/ibm/icu/text/Collator.java, icu4j/main/classes/core/src/com/ibm/icu/lang/CharacterProperties.java, icu4j/main/classes/core/src/com/ibm/icu/number/NumberRangeFormatter.java, icu4j/main/classes/core/src/com/ibm/icu/number/Precision.java, icu4j/main/classes/core/src/com/ibm/icu/number/ScientificNotation.java, icu4j/main/classes/core/src/com/ibm/icu/text/CurrencyPluralInfo.java, icu4j/main/classes/core/src/com/ibm/icu/text/DateIntervalInfo.java, icu4j/main/classes/core/src/com/ibm/icu/text/Edits.java, icu4j/main/classes/core/src/com/ibm/icu/text/MeasureFormat.java, icu4j/main/classes/core/src/com/ibm/icu/text/PluralRules.java, icu4j/main/classes/core/src/com/ibm/icu/text/RuleBasedNumberFormat.java, icu4j/main/classes/core/src/com/ibm/icu/text/SpoofChecker.java, icu4j/main/classes/core/src/com/ibm/icu/text/StringPrepParseException.java, icu4j/main/classes/core/src/com/ibm/icu/text/TimeUnitFormat.java, icu4j/main/classes/core/src/com/ibm/icu/util/ByteArrayWrapper.java, icu4j/main/classes/core/src/com/ibm/icu/util/CaseInsensitiveString.java, icu4j/main/classes/core/src/com/ibm/icu/util/CodePointMap.java, icu4j/main/classes/core/src/com/ibm/icu/util/MeasureUnit.java, icu4j/main/classes/core/src/com/ibm/icu/util/SimpleTimeZone.java, icu4j/main/classes/core/src/com/ibm/icu/util/TimeZone.java, icu4j/main/classes/core/src/com/ibm/icu/util/ULocale.java, icu4j/main/classes/core/src/com/ibm/icu/util/VersionInfo.java, icu4j/main/classes/translit/src/com/ibm/icu/text/Transliterator.java, icu4j/tools/build/src/com/ibm/icu/dev/tool/docs/APIStatusConsistencyChecker.java, icu4j/tools/build/src/com/ibm/icu/dev/tool/docs/DeprecatedAPIChecker.java
- Updated API status of java.lang.Object method overrides (equals/hashCode/toString/clone) to match status of declaring class. There are some API comments that is insufficient, or incorrect, or not appropriate after the change. Most of these issues were fixed.
- APIStatusConsistencyChecker and ant tasks invoking the check, designed for checking this requirement. For now, Normalizer#clone() does not satisfy the requirement, but unchanged on purpose. The tool can accept exception. This change is for ICU-20151 Check API status of equals()/hashCode() match the containing class's status
- DeprecatedAPIChecker had a problem for handling non-static inner class's constructor. CodePointMap$StringIterator is the very first instance of such class in ICU4J. The problem was fixed by removing the …
=> ICU-20150 API status of equals()/hashCode() should match the ICU class's status

icu4c/source/common/uloc.cpp, icu4c/source/common/uloc_tag.cpp, icu4c/source/test/cintltst/cloctst.c, icu4c/source/test/cintltst/cloctst.h, icu4c/source/test/intltest/loctest.cpp, icu4c/source/test/intltest/loctest.h
This gets rid of those fixed buffers that caused ICU-13417 to be filed
in the first place, those that prevent handling language tags with very
large amounts of keywords.
A number of fixed buffers will still remain in uloc_tag.cpp (and
elsewhere in the locale handling code) for the time being, but this
change is a necessary first step in cleaning up this code and will
alleviate the most pressing problem encountered by ICU4C users.
=> ICU-13417 Replace fixed buffers in uloc_tag.cpp with CharString.

icu4j/main/classes/core/src/com/ibm/icu/util/JapaneseCalendar.java
Updated era constants (HEISEI/SHOWA...) initialization to static initializer block. By doing so, we would make java compiler not to inline these values in consumer codes. This should allow us to support better binary compatibility across versions. There are no API changes.
=> ICU-20153 Make ICU4J JapaneseCalendar constants non-inlineable.

icu4c/source/i18n/currunit.cpp, icu4c/source/test/intltest/itutil.cpp, icu4c/source/test/intltest/measfmttest.cpp, icu4c/source/test/intltest/numfmtst.cpp, icu4c/source/tools/ctestfw/tstdtmod.cpp, icu4c/source/tools/ctestfw/unicode/testlog.h
Replying to Markus's long-overdue feedback on ICU-13850.
=> ICU-13850 Make CurrencyUnit safe with 1-length and 2-length strings.

icu4j/main/classes/core/src/com/ibm/icu/text/CurrencyDisplayNames.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/CurrencyTest.java
=> ICU-13830 Fixing CurrencyDisplayNames.getInstance(Locale) boolean attribute behavior.

.cpyskip.txt, .travis.yml
- correct typo from 518f10b7a90a7bca1dd554601a681ba9f341f583
=> ICU-20066 fixup .travis.yml

icu4c/source/common/sharedobject.h, icu4c/source/common/umutex.h, icu4c/source/test/cintltst/callcoll.c, icu4c/source/test/iotest/filetst.c, icu4c/source/test/iotest/trnstst.c, icu4c/source/tools/genrb/reslist.cpp, icu4c/source/tools/toolutil/unewdata.cpp
The change in ICU-12505 caused `#define U_HAVE_STD_ATOMICS 1`  to be set all the time, for all platforms.
Previously, it was only set if `U_HAVE_ATOMIC` was set either by a autoconf test or manually, meaning that Windows-based platforms used the Interlocked* APIs instead.
While looking through the errors on MSVC and trying to clean them up I noticed the following new error in ICU 63.1
```
> icu4c\source\common\sharedobject.h(176): warning C4251: 'icu_62::SharedObject::hardRefCount': struct 'std::atomic<int>' needs to have dll-interface to be used by clients of class 'icu_62::SharedObject' (compiling source file unifiedcache.cpp)
```
We need to export an explicit template instantiation for `std::atomic<int32_t>` since it is used as a data member of the exported class SharedObject.
Note: …
=> ICU-20157 Fix MSVC C4251: Need to export explicit template instantiation, plus some more warning fixes.

icu4c/source/configure, icu4c/source/configure.ac, icu4c/source/data/makedata.mak
=> ICU-20160 Add check for Python 3 in autoconf and nmake.

icu4c/source/i18n/decimfmt.cpp, icu4c/source/i18n/numrange_fluent.cpp, icu4c/source/i18n/unicode/numberrangeformatter.h
I need to use some form of an atomic for proper thread safety. Here is one way to do it, my preferred option, which involves including in a public header file. If this is problematic, I can work around by newing an internal object for the atomic, which comes at the cost of extra mallocs.
=> ICU-11276 Using atomics for thread safety in NumberRangeFormatter.

icu4c/source/test/intltest/numbertest_api.cpp, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
=> ICU-11319 Add tests for compact decimal in zh-Hant and zh-Hant-HK.

icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/ICUResourceBundleTest.java
This reverts commit 1dccd7472e9f2db4830293b9d33500ea4b4ce082.
=> ICU-20085 Revert workaround for pseudolocale region codes for display names.

icu4c/source/common/cmemory.h, icu4c/source/common/locid.cpp, icu4c/source/i18n/erarules.cpp, icu4c/source/i18n/erarules.h, icu4c/source/test/depstest/dependencies.txt
Updated intra-library dependencies, adjusted for new and moved files.
http://site.icu-project.org/processes/release/tasks/healthy-code#TOC-Check-library-dependencies
EraRules was using global new & delete via LocalArray<primitive type> which is a no-no. Changed to use LocalMemory, and fixed a bug in LocalMemory::moveFrom().
locid.cpp: The dependencies checker looks for virtual destructors that are missing (implicit) or defined inside the class declaration, because if that is done in a header file the destructor cannot serve as the "key function". Inside a .cpp file this would not be a problem, but the tool cannot distinguish. So moved the destructor definition outside the class declaration.
=> ICU-20119 update C++ dependencies, fix bugs

icu4c/source/common/putil.cpp, icu4c/source/common/wintz.cpp, icu4c/source/common/wintz.h
This was fixed in earlier commits (see, for example, ICU-12786), but
the problem was reintroduced in commits f8ba68e and fcb82cb.
=> ICU-20191 Don't use Win32 API on Cygwin

icu4c/source/common/unicode/urename.h, icu4c/source/tools/genren/genren.pl
_MSC_VER is not defined in other compiler.
Change the logic and so urename.h is ignored on VS IntelliSense
=> ICU-20193 urename.h shouldn't be ignored by other compilers except VS IntelliSense

icu4c/source/common/putil.cpp, icu4c/source/common/wintz.cpp, icu4c/source/common/wintz.h
This was fixed in earlier commits (see, for example, ICU-12786), but
the problem was reintroduced in commits f8ba68e and fcb82cb.
(cherry picked from commit 7d99ba4e578f3f10f6319b26873edb41ce557046)
=> ICU-20191 Don't use Win32 APIs on Cygwin (#185)

icu4c/source/common/unicode/urename.h, icu4c/source/tools/genren/genren.pl
The macro _MSC_VER is not defined in other compilers.
Change the logic and so urename.h is ignored on VS IntelliSense
(cherry picked from commit ff72d74d1eeedb6f4ae9326a87f90eaad7b8595d)
=> ICU-20193 urename.h shouldn't be ignored by other compilers except VS IntelliSense (#189)

icu4c/source/common/uloc_tag.cpp, icu4c/source/i18n/unicode/datefmt.h, icu4c/source/i18n/unicode/decimfmt.h, icu4c/source/i18n/unicode/numberrangeformatter.h
This fixes MSVC/clang compiler warning C4251 by exporting an explicit template instantiation, which is required when building DLLs on Windows. This PR also fixes a few other warnings as well.
=> ICU-20196 Fix MSVC/clang compiler warning C4251, and other warnings.

icu4c/source/common/uloc_tag.cpp, icu4c/source/i18n/unicode/datefmt.h, icu4c/source/i18n/unicode/decimfmt.h, icu4c/source/i18n/unicode/numberrangeformatter.h
Fix MSVC/clang compiler warning C4251, export explicit template, required for building DLLs on Windows. Also fix a few other warnings as well.
(cherry picked from commit ba001f46163ded5886972aeb927e35756f00d761)
=> ICU-20196 Fix MSVC/clang compiler warning C4251, plus other warning fixes.

icu4j/main/classes/charset/manifest.stub, icu4j/main/classes/localespi/manifest.stub, icu4j/manifest.stub
Added Automatic-Module-Name field to META-INF/MANIFEST.MF.
The line makes this library available for all modular jars 
containing module-info having been compiled with Java 9 or higher.
Please change the module name "com.ibm.icu" if it is not appropriate.
This is a very important decision, because the libraries using this library
will declare the name in their module-info.java as below:
```
requires  com.ibm.icu;
```
Checklist
=> ICU-20192 Add Automatic-Module-Name to META-INF/MANIFEST.MF

.github/pull_request_template.md
This change will create a link from GitHub to Jira on every PR.  Right now a browser extension is required for this functionality.
The issue is closed.  I can open a new issue or re-open the old one to accept a new commit.
=> ICU-20198 Add issue browse link to PR template.

icu4j/main/classes/charset/manifest.stub, icu4j/main/classes/localespi/manifest.stub, icu4j/manifest.stub
* Add Automatic-Module-Name to META-INF/MANIFEST.MF
* Added com.ibm.icu.number in Export-Package list
* Add Automatic-Module-Name to charset and localespi
(cherry picked from commit 2e580c050409ad61c08d6d83f433110e48a67680)
=> ICU-20192 Add Automatic-Module-Name to META-INF/MANIFEST.MF (#193)

icu4c/source/common/unicode/urename.h, icu4c/source/i18n/uspoof.cpp
In ICU-12549, the code in `uspoof.cpp` was refactored which added this new function. This function is not exported or used anywhere other than inside the uspoof.cpp file. We can mark it as `static` as it operates on the input `This` argument.
After marking this as static, regenerating the `urename.h` file causes the `checkImpl` function to no longer be included.
=> ICU-20208 uspoof.cpp function checkImpl should be static, regenerate urename.h

icu4c/source/test/intltest/dcfmapts.cpp
Using temporary variables for the two values to be compared here makes
GCC compile the code just like we expect it to. (What it really is that
it otherwise does on some architechtures remains a mystery.)
This will make the tests pass as expected also on IA-32 with GCC.
It'll also make it possible to revert the old workaround for SPARC
introduced by commit 5b0592af79c7601d08cafcbbc7b71077faeb7e4f.
Tested:
Linux gcc45 3.16.0-5-686-pae #1 SMP Debian 3.16.51-3+deb8u1 (2018-01-08) i686 GNU/Linux
Debian clang version 3.5.0-10 (tags/RELEASE_350/final) (based on LLVM 3.5.0)
g++ (Debian 4.9.2-10+deb8u1) 4.9.2
Linux gcc202 4.16.0-1-sparc64-smp #1 SMP Debian 4.16.5-1 (2018-04-29) sparc64 GNU/Linux
clang version 4.0.1-10+sparc64 (tags/RELEASE_401/final)
g++ (Debian 8.2.0-7) 8.2.0
=> ICU-20080 Avoid strange compiler behaviour in ASSERT_EQUAL() macro.

icu4c/source/common/unicode/urename.h, icu4c/source/i18n/uspoof.cpp
(cherry picked from commit 9ec2c332c1c9156323944ea2b15c2b91952efae4)
=> ICU-20208 uspoof.cpp function checkImpl should be static, regenerate urename.h (maint-63)

icu4c/source/i18n/unicode/numberrangeformatter.h
(cherry picked from commit 31b89b54840361fdfc367ef02019b10424cdb75c)
=> ICU-20214 Fix namespace error on Cygwin (maint-63)

icu4c/source/common/locid.cpp, icu4c/source/common/uloc_tag.cpp, icu4c/source/common/ulocimp.h, icu4c/source/test/cintltst/cloctst.c, icu4c/source/test/cintltst/cloctst.h
This eliminates the need for a scratch buffer in Locale::toLanguageTag()
and also the need for counting bytes required in uloc_toLanguageTag(),
something that ByteSink will now handle correctly and thereby
eliminating the bug where too few bytes required was returned.
=> ICU-20132 Pass ByteSink from Locale::toLanguageTag() to uloc_toLanguageTag()

icu4c/source/common/umutex.h, icu4c/source/i18n/unicode/numberrangeformatter.h, icu4c/source/test/intltest/numbertest.h
The change to `icu4c/source/test/intltest/numbertest.h` was necessary to get Cygwin-x64 with GCC to compile correctly.
(Also FYI for @jungshik , since I can't add him as a reviewer explicitly.)
=> ICU-20209 Fix compile failure on Clang for Windows with std::atomic not in enclosing namespace 'std'.

icu4c/source/i18n/number_decimalquantity.cpp, icu4c/source/i18n/number_decimalquantity.h, icu4c/source/test/intltest/numbertest.h, icu4c/source/test/intltest/numbertest_decimalquantity.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/number/DecimalQuantity.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/DecimalQuantity_AbstractBCD.java, icu4j/main/tests/core/src/com/ibm/icu/dev/impl/number/DecimalQuantity_SimpleStorage.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/DecimalQuantityTest.java
Avoids expensive arithmetic when performing nickel rounding for currencies such as CAD, CHF, and DKK.
Note: This is not the only PR for ICU-13701.  I am sending this PR separately because the change is more complex than I expect the other changes to be.
=> ICU-13701 Adding custom logic for nickel rounding, C and J.

icu4c/source/test/intltest/numbertest_api.cpp, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
=> ICU-20231 Adding tests for accounting with variable currency widths.

icu4c/source/i18n/dtfmtsym.cpp
CalendarDataSink doesn't use any of the additional functionality
provided by UVector, it just needs a simple way to keep track of
allocated objects to delete them after it's done using them.
=> ICU-20202 Replace UVector with MemoryPool in CalendarDataSink.

icu4c/source/common/uloc_keytype.cpp
By moving the required call to uhash_close() into the destructor of
LocExtKeyData and using CharString instead of raw chunks of bytes
allocated with uprv_malloc(), it becomes easier to guarantee that
memory handling is correct, without leaks or overflows.
With the need for custom deleter functions removed, the code doesn't use
any of the additional functionality provided by UVector, it just needs a
simple way to keep track of allocated objects to delete them after it's
done using them, which MemoryPool does in a simpler and typesafe way.
=> ICU-20202 Replace UVector with MemoryPool in uloc_keytype.

icu4c/source/common/locavailable.cpp, icu4c/source/common/locdispnames.cpp, icu4c/source/common/loclikely.cpp, icu4c/source/common/locresdata.cpp, icu4c/source/common/locutil.cpp, icu4c/source/common/uloc_keytype.cpp, icu4c/source/common/uloc_tag.cpp
Doing this consistently first will make it easier to then clean up
resource management and error handling later.
=> ICU-20169 Use smart pointers in all locale code instead of u*_close().

icu4c/source/common/umutex.h, icu4c/source/i18n/unicode/numberrangeformatter.h, icu4c/source/test/intltest/numbertest.h
Note: I had to manually resolve the merge conflicts from cherry-picking this from master to maint/maint-63
cherry picked from commit 5a34bfb1516a6719b5f470063c6be2f47446f0b2
=> ICU-20209 Fix build failures on Windows with std::atomic not in enclosing namespace std

icu4c/source/i18n/fmtable.cpp, icu4c/source/i18n/number_decimalquantity.cpp, icu4c/source/test/intltest/numfmtst.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/number/DecimalQuantity_AbstractBCD.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/DecimalQuantity_DualStorageBCD.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/NumberFormatTest.java
(cherry picked from commit 53d8c8f3d181d87a6aa925b449b51c4a2c922a51)
=> ICU-20246 Fixing another integer overflow in number parsing.

icu4c/source/i18n/numparse_affixes.cpp, icu4c/source/i18n/numparse_affixes.h
The shared templated helper class MemoryPool can be used to replace the
local helper class CodePointMatcherWarehouse, reducing the amount of
specialized code needed.
=> ICU-20202 Replace CodePointMatcherWarehouse with MemoryPool.

icu4c/source/test/intltest/numbertest.h, icu4c/source/test/intltest/numbertest_api.cpp, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
Makes future field position logic easier to test.
=> ICU-13267 Refactoring field position testing logic into helper function.

icu4c/source/common/characterproperties.cpp, icu4c/source/common/ucptrie.cpp, icu4c/source/common/umutablecptrie.cpp, icu4c/source/common/unicode/uniset.h, icu4c/source/common/uniset.cpp, icu4c/source/common/uniset_closure.cpp, icu4c/source/common/uniset_props.cpp, icu4c/source/common/uprops.h, icu4c/source/common/uset.cpp, icu4c/source/common/usetiter.cpp, icu4c/source/test/intltest/convtest.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/CharacterPropertiesImpl.java, icu4j/main/classes/core/src/com/ibm/icu/text/UnicodeSet.java, icu4j/main/classes/core/src/com/ibm/icu/text/UnicodeSetIterator.java, icu4j/main/classes/core/src/com/ibm/icu/util/CodePointTrie.java, icu4j/main/classes/core/src/com/ibm/icu/util/MutableCodePointTrie.java
=> ICU-20250 faster to make a property set

icu4c/source/test/intltest/dcfmapts.cpp, icu4c/source/test/intltest/intltest.h, icu4c/source/test/intltest/itutil.cpp, icu4c/source/test/intltest/loctest.cpp, icu4c/source/test/intltest/numfmtst.cpp, icu4c/source/test/intltest/rbbiapts.cpp, icu4c/source/test/intltest/rbbitst.cpp, icu4c/source/test/intltest/ustrtest.cpp
=> ICU-20084 IntlTest, add WHERE macro; remove redundant TEST macros.

icu4c/source/common/cmemory.h
For historical reasons (commit 3b12074b4092241a7e73ec8c7ea6be75548b1b82),
all C++ code (even #include statements) in cmemory.h is contained in an
#ifdef block at the end of the file. A recent bugfix inadvertently added
an additional #ifdef __cplusplus block at the beginning of the file to
add a new #include statement so that C++ #include statements now are
found in two places (commit 1bad36b91afa1fb33a0d45902a163a923d6e860a).
=> ICU-20202 Merge #ifdef __cplusplus blocks.

icu4c/source/data/brkitr/brkfiles.mk, icu4c/source/data/brkitr/ja.txt, icu4c/source/data/brkitr/rules/line_cj.txt, icu4c/source/data/brkitr/rules/line_normal_cj.txt, icu4c/source/data/brkitr/zh.txt, icu4c/source/data/brkitr/zh_Hant.txt, icu4c/source/data/xml/brkitr/ja.xml, icu4c/source/data/xml/brkitr/zh.xml, icu4c/source/data/xml/brkitr/zh_Hant.xml, icu4c/source/test/intltest/rbbimonkeytest.cpp, icu4c/source/test/testdata/break_rules/line_cj.txt, icu4c/source/test/testdata/break_rules/line_normal_cj.txt
Special tailoring for CJ so that `“ 201C` and `” 201D` become `OP` and `CL` instead of `QU`.
**line_cj.txt** was copied from **line.txt**. The diffs between **line_cj.txt** and **line.txt** are identical to the changes for **line_loose_cj.txt** and **line_normal_cj.txt**.
=> ICU-13441 For zh/ja, tailor linebreak classes for quotations such as “ 201C and ” 201D

icu4c/source/i18n/number_affixutils.cpp, icu4c/source/i18n/number_affixutils.h, icu4c/source/i18n/number_compact.cpp, icu4c/source/i18n/number_formatimpl.cpp, icu4c/source/i18n/number_patternmodifier.cpp, icu4c/source/i18n/number_patternmodifier.h, icu4c/source/i18n/unicode/numfmt.h, icu4c/source/i18n/unicode/unum.h, icu4c/source/test/intltest/numbertest_affixutils.cpp, icu4c/source/test/intltest/numbertest_api.cpp, icu4c/source/test/intltest/numbertest_patternmodifier.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/number/AffixUtils.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/MutablePatternModifier.java, icu4j/main/classes/core/src/com/ibm/icu/number/CompactNotation.java, icu4j/main/classes/core/src/com/ibm/icu/number/NumberFormatterImpl.java, icu4j/main/classes/core/src/com/ibm/icu/text/NumberFormat.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/AffixUtilsTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/MutablePatternModifierTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
Adds some plumbing to allow MutablePatternModifier to set fields, and otherwise builds upon the infrastructure from the previous commit to add the MEASURE_UNIT field.
=> ICU-20230 Implementing COMPACT field.

.ci-builds/.azure-pipelines.yml
This is a somewhat hacky workaround until the VS2015 images are updated to include Python 3 by default.
(Using the webinstaller with various options to try and limit the amount downloaded on each build.)
=> ICU-20281 Reenable the VS2015 build bot. Use manual install of Py3.

icu4c/source/common/capi_helper.h, icu4c/source/common/common.vcxproj, icu4c/source/common/common.vcxproj.filters, icu4c/source/common/common_uwp.vcxproj, icu4c/source/i18n/number_capi.cpp, icu4c/source/i18n/number_utypes.h, icu4c/source/i18n/uspoof_impl.cpp, icu4c/source/i18n/uspoof_impl.h
The same "magic number" code was already duplicated 4 times.  I moved it to a common templated base class.  I intend to continue using it to implement FormattedValue and related classes.
=> ICU-20293 Make common base class to implement "validate" methods.

icu4j/build.xml
Simple change to include the missing pom templates.
=> ICU-20287 ICU4J source tarball does not contain maven pom templates

icu4c/source/configure, icu4c/source/configure.ac
* use `=` instead of `==` in configure shell script
* Note: the diff will show changes to "runstatedir". This is
a feature which ICU does not use, and it is not in any released
autoconf version. Perhaps some distributions patched autoconf
locally.
https://lists.gnu.org/archive/html/autoconf/2018-07/msg00006.html
=> ICU-20247 use = instead of == in autoconf

icu4c/source/test/intltest/numfmtst.cpp, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/NumberFormatTest.java
=> ICU-20186 Adding test for leading and trailing spaces in DecimalFormat.

icu4c/source/common/locid.cpp, icu4c/source/test/intltest/loctest.cpp, icu4c/source/test/intltest/loctest.h
This is splitted from #286 and only contains the locale parsing fix.
=> ICU-11053 Fix locale parsing which has _ timezone

icu4c/source/data/BUILDRULES.py
Fixes warnings and a flaky test.
This is likely the cause of the test failure on #305.
=> ICU-10923 Fixing broken dependency names in BUILDRULES.py.

icu4j/main/classes/core/src/com/ibm/icu/text/TimeZoneFormat.java
=> ICU-20295 Fix wrong java doc of "{#link" in TimeZoneFormat

icu4c/source/test/hdrtst/cxxfiles.txt
=> ICU-20307 Add reldatefmt.h and compactdecimalformat.h into cxxfiles.txt

icu4c/source/common/normlzr.cpp
Remove unneeded check for MSVC internal _ARM64_ macro in normlzr.cpp
=> ICU-20279 Remove MSVC specific macro _ARM64_

icu4c/source/test/intltest/restsnew.cpp, icu4c/source/test/intltest/restsnew.h, icu4c/source/test/testdata/BUILDRULES.py, icu4c/source/test/testdata/filters/filtertest.txt, icu4c/source/test/testdata/filtertest.txt, icu4c/source/tools/genrb/Makefile.in, icu4c/source/tools/genrb/filterrb.cpp, icu4c/source/tools/genrb/filterrb.h, icu4c/source/tools/genrb/genrb.cpp, icu4c/source/tools/genrb/genrb.vcxproj, icu4c/source/tools/genrb/genrb.vcxproj.filters, icu4c/source/tools/genrb/reslist.cpp, icu4c/source/tools/genrb/reslist.h
This PR contains initial changes to add `--filterDir` to genrb.
Unused values are scrubbed, but based on inspection of the .res files, unused keys are not yet being scrubbed.  I want to sync with you briefly on the right way to scrub the keys.  I currently plan to do it all in the `compactKeys()` function, which takes the initial list of keys (hard to change) and converts it to an optimized list (easier to change).
=> ICU-10923 Adding --filterDir option to genrb.

icu4c/source/common/wintz.cpp, icu4c/source/test/cintltst/putiltst.c
From debugging the issue on Windows 7:
It seems that the `DYNAMIC_TIME_ZONE_INFORMATION` struct returned by the Windows API `GetDynamicTimeZoneInformation` may have garbage data after the null terminator.
For example, when the Time Zone is set to "Pacific Standard Time" this is contents of the 256 byte (128 wchar_t) `TimeZoneKeyName` buffer after calling the API:
```
0x000000000015EB2C  50 00 61 00 63 00 69 00 66 00 69 00 63 00 20 00 53 00 74  P.a.c.i.f.i.c. .S.t
0x000000000015EB3F  00 61 00 6e 00 64 00 61 00 72 00 64 00 20 00 54 00 69 00  .a.n.d.a.r.d. .T.i.
0x000000000015EB52  6d 00 65 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  m.e................
0x000000000015EB65  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ...................
0x000000000015EB78  c0 7e 0f 00 00 00 …
```
=> ICU-20302 Timezone detection fails on Windows 7.

icu4c/source/tools/makeconv/makeconv.cpp
The MSYS2 builds were accidentally broken with ICU-10923. 
The call to `makeconv` is slightly different now, and the program will internally combine the input source path argument with the converter path/name.
Before:
```
PATH=../lib:../stubdata:../tools/ctestfw:$PATH  ../bin/makeconv -c -d ./out/build/icudt62l ./mappings/cns-11643-1992.ucm
```
After:
```
PATH=../lib:../stubdata:../tools/ctestfw:$PATH  ../bin/makeconv -s . -d ./out/build/icudt63l -c mappings/cns-11643-1992.ucm
```
The problem is that the leading "." on the path (`./mappings/`) ends up confusing the MSYS heuristics that are used for translating Unix/POSIX paths to Windows style paths.
This change restores the MSYS2 builds, so that they actually work now.
=> ICU-20315 Fix MSYS2 build break: Don't prepend the source dir if it is just a current directory (.) path.

icu4c/source/common/cmemory.h, icu4c/source/i18n/numparse_affixes.h
This was accidentally regressed in [ICU-20202](https://unicode-org.atlassian.net/browse/ICU-20202), but since we don't have any build bots (CI builds) that treat this warning as an error, we didn't notice it at the time. (Aside: I have a separate issue/ticket to treat this warning as an error in the CI builds, so that we can catch this in the future...)
Note: I had to move the `STACK_CAPACITY ` value out of the anonymous enum, so that it could be used in the header `numparse_affixes.h`. However, there might be another/better way to do this. Please feel free to suggest other ideas.
=> ICU-20353 Fix MSVC Warning/Error C4251 with CodePointMatcherWarehouse and MemoryPool

icu4c/source/data/locales/fr_CH.txt, icu4c/source/i18n/decimfmt.cpp, icu4c/source/i18n/number_mapper.cpp, icu4c/source/i18n/number_mapper.h, icu4c/source/i18n/number_patternstring.cpp, icu4c/source/test/intltest/numfmtst.cpp, icu4c/source/test/intltest/numfmtst.h, icu4j/main/classes/core/src/com/ibm/icu/impl/number/PatternStringUtils.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/PropertiesAffixPatternProvider.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/NumberFormatTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/PatternStringTest.java
If this looks good, I will make the same change in ICU4J.
=> ICU-20348 Fixing DecimalFormat set affix currency behavior.

icu4c/source/config/mh-cygwin, icu4c/source/config/mh-cygwin-msvc, icu4c/source/config/mh-cygwin64
=> ICU-20364 Cygwin builds need to set WINVER to 0x0601 for Windows 7, similar to MinGW builds.

icu4c/source/common/locmap.cpp, icu4c/source/common/locmap.h, icu4c/source/common/uloc.cpp, icu4c/source/common/unicode/uconfig.h
This change will enable users of ICU (like Chrome) to control the use of the LCID Platform APIs by setting `UCONFIG_USE_WINDOWS_LCID_MAPPING_API ` to 0.
(FYI for @jungshik, this would mean that the `vscomp.patch` file could be deleted in Chromium, and you could set the define instead.)
=> ICU-20206 ICU4C: Make USE_WINDOWS_LCID_MAPPING_API compile-time configurable

icu4c/source/i18n/unicode/numberformatter.h, icu4c/source/i18n/unicode/unumberformatter.h, icu4j/main/classes/core/src/com/ibm/icu/number/FormattedNumber.java
Most users can use the new method, but these methods may still be useful when needing to interact with the FieldPosition-based APIs.
=> ICU-20283 Updating docs of old FormattedNumber field position methods.

icu4c/source/common/unicode/localpointer.h, icu4c/source/test/intltest/itutil.cpp
- Requires the right side to be an rvalue reference.
=> ICU-20357 Adding LocalPointer conversion methods to/from std::unique_ptr

icu4j/main/classes/core/src/com/ibm/icu/text/DecimalFormatSymbols.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/IntlTestDecimalFormatSymbols.java
=> ICU-20350 Fix DecimalFormatSymbols.setPatternForCurrencySpacing affecting the value across instances

icu4c/source/i18n/number_multiplier.cpp
Split off from PR #374.
The move assignment operator leaks the `fArbitrary` member (96 bytes). We need to free the existing data before taking ownership of the moved from data.
=> ICU-20393 ICU4C: Scale move assignment operator leaks fArbitrary member.

icu4c/source/i18n/decimfmt.cpp, icu4c/source/i18n/number_decimfmtprops.cpp, icu4c/source/i18n/number_decimfmtprops.h, icu4c/source/i18n/number_mapper.h, icu4c/source/i18n/unicode/decimfmt.h, icu4c/source/test/intltest/dcfmapts.cpp, icu4c/source/test/intltest/dcfmapts.h
There are 2 issues/tickets addressed in this PR:
- Protect against de-referencing null members in the setters and getters where needed.
- Fallback to the default `DecimalFormatProperties` instance if in a failure state.
- Use move assignment for `fields->formatter` (LocalizedNumberFormatter) instead of creating new heap object every time.
- Add test cases for DecimalFormat object in invalid state.
- Protect against self-assignment in assignment operator.
- Fix segmentation fault when attempting to compare valid and invalid DecimalFormat objects. (ICU-20381)
- Fix leaks in `adoptCurrencyPluralInfo` and `adoptDecimalFormatSymbols` if the object is in an invalid state.
- Changes based on review feedback from Shane.
- Fix minor typos in the public header file.
=> ICU-13847 ICU-20381 Improve handling of errors (Out-of-Memory) in DecimalFormat

icu4c/source/test/intltest/numfmtst.cpp
Split off from PR #374.
We need to use `free()` with `malloc()` instead of `uprv_free()`, as the heaps can be different.
=> ICU-20388 ICU4C: intltest fails with a Debug Break on MSVC. (uprv_free vs free)

icu4c/source/i18n/fmtable.cpp, icu4c/source/test/cintltst/cnumtst.c, icu4c/source/test/intltest/numfmtst.cpp
In ICU 62, Formattable::internalGetCharString switched to generating a string using scientific notation for Formattables whose integer representation would require 6 digits or more. As part of this, the expected result for an existing test was changed (commit cd92fa2c88788780b2572d508f129cddb89c2e36, Wed Apr 11 05:52:58 2018) as follows:
```
-        ASSERT_EQUALS("1234567890123", f.getDecimalNumber(status));
+        ASSERT_EQUALS("1.234567890123E+12", f.getDecimalNumber(status).data());
```
Revert the internalGetCharString  behavior change for Formattables whose internal type is kLong or kInt64, and revert the test change above. Add plain C tests for this and other parse cases.
Note that ICU4J does not have parseDecimal.
=> ICU-20374 Formattable::internalGetCharString to create int string for types kLong, kInt64

icu4c/source/common/common_uwp.vcxproj, icu4c/source/common/umapfile.cpp
In order to make development of UWP apps easier, we can switch from calling the UWP-only Win32 API `CreateFileMappingFromApp`, and instead use the standard Win32 `CreateFileMapping` for both the UWP version and the non-UWP version. This reduces one of the "forks" in the code for the UWP version.
- `CreateFileMappingW` is marked for both desktop and UWP apps, so we can call that in both code paths.
- We can use the W version of the `CreateFileMapping` API instead of A version since we pass a NULL for the name anyways.
- We can call the same API `CreateFile[A|W]` from both the UWP and Win32 versions of the code, reducing one of the UWP forks.
- Add a work-around for older versions of the Windows 10 SDK UWP headers.
- Remove the code that was creating a custom security descriptor (but …
=> ICU-20204 ICU4C: Use the CreateFileMapping API for both the UWP version and Win32 versions.

icu4c/source/i18n/reldatefmt.cpp, icu4c/source/test/cintltst/crelativedateformattest.c, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/RelativeDateTimeFormatterTest.java
I added a test for RelativeDateTimeFormatter using locale "ak" (per the JIRA ticket), which is interesting because it falls back to root which only supports the "other" case. This test initially failed in C but passed in J. I also added a test using en_IN, which has an incomplete logical group in the data for relative Wednesdays (could not add this test in J, it does not support relative Wednesdays).
I then rolled in a slightly modified version of the patch from the ICU-20253 ticket, to make ICU4C data fallback match ICU4J, and this fixed the test failures in C.
=> ICU-20253 ICU4C RelativeDateTimeFormatter to fall back to OTHER case, as in ICU4J

icu4c/source/i18n/Makefile.in, icu4c/source/i18n/formattedval_impl.h, icu4c/source/i18n/formattedval_iterimpl.cpp, icu4c/source/i18n/formattedvalue.cpp, icu4c/source/i18n/fphdlimp.cpp, icu4c/source/i18n/fphdlimp.h, icu4c/source/i18n/fpositer.cpp, icu4c/source/i18n/i18n.vcxproj, icu4c/source/i18n/i18n.vcxproj.filters, icu4c/source/i18n/i18n_uwp.vcxproj, icu4c/source/i18n/number_capi.cpp, icu4c/source/i18n/number_utypes.h, icu4c/source/i18n/unicode/formattedvalue.h, icu4c/source/i18n/unicode/uformattedvalue.h, icu4c/source/test/cintltst/cformtst.h, icu4c/source/test/cintltst/uformattedvaluetst.c, icu4c/source/test/cintltst/unumberformattertst.c, icu4c/source/test/depstest/dependencies.txt, icu4c/source/test/intltest/formattedvaluetest.cpp, icu4c/source/test/intltest/itformat.h, icu4c/source/test/intltest/numbertest_api.cpp, icu4j/main/classes/core/src/com/ibm/icu/text/ConstrainedFieldPosition.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/FormattedValueTest.java
- Adds test infra for multi-category formatted values.
- Adds helper method ConstrainedFieldPosition#matchesField, currently internal.
=> ICU-20138 Implementing ufmtval_nextPosition and additional internal infrastructure.

icu4c/source/i18n/decimfmt.cpp, icu4c/source/test/cintltst/cnumtst.c, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/NumberFormatTest.java
In ICU4C, parsing a 0-length string (in NumberFormat or unum_parse*) should set U_PARSE_ERROR as in ICU 61. In ICU4J, so far I just added a test to check current behavior; parsing a 0-length string (in NumberFormat) just returns null, but does not throw an IllegalArgumentException. Should it? I will adjust the test according to whatever we decide the correct behavior is.
=> ICU-20347 In ICU4C, parse empty string should set PARSE_ERROR as before; check ICU4J behavior

icu4c/source/common/unicode/brkiter.h, icu4j/main/classes/core/src/com/ibm/icu/text/BreakIterator.java
https://unicode-org.atlassian.net/browse/ICU-20213
=> ICU-20213 deprecate BreakIterator::createTitleInstance()

icu4c/source/test/intltest/itutil.cpp, icu4c/source/test/intltest/ustrtest.cpp
https://unicode-org.atlassian.net/browse/ICU-13081
=> ICU-13081 test self-move without clang warning

icu4c/source/common/unicode/utext.h
Removed incorrect #ifndef U_HIDE_INTERNAL_API around UTEXT_MAGIC (been there since 2011!), which is needed for public UTEXT_INITIALIZER.
=> ICU-20306 Remove incorrect #ifndef U_HIDE_INTERNAL_API around UTEXT_MAGIC

icu4c/source/common/uloc_tag.cpp, icu4c/source/test/cintltst/cloctst.c, icu4j/main/classes/core/src/com/ibm/icu/impl/locale/UnicodeLocaleExtension.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/LocaleBuilderTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/ULocaleTest.java
Returns false when passingin alphanum digit.
Sync with UTS35
https://www.unicode.org/reports/tr35/#Unicode_locale_identifier
=> ICU-20321 Fix ultag_isUnicodeLocaleKey

.ci-builds/.azure-pipelines.yml
In order to catch issues like [ICU-20388](https://unicode-org.atlassian.net/browse/ICU-20388), this replaces the 32-bit Release build with a 32-bit "Debug" build instead (for the Azure Pipelines CI builds).
=> ICU-20389 Add MSVC Debug build to the Azure CI builds.

icu4c/source/tools/toolutil/pkg_genc.cpp
The tools `pkgdata` and `genccode` on Windows currently support producing ARM 32-bit objects, but not ARM 64-bit objects.
However, when building the data .obj files for ARM64, the image file type doesn't actually need to be set.
We can use the unknown type, `IMAGE_FILE_MACHINE_UNKNOWN`, since they are data only obj files.
(This is what is currently used for AMD64 (x64) architecture.)
We can use this approach to simply the code somewhat, which will also enable support for ARM64 as well.
(Thanks to Jon Kunkee for reporting this bug.)
Note: Unfortunately, the variable name decoration/mangling is different on x86, which means we can't use the UNKNOWN type for all architectures though, and must keep the special case for x86.
=> ICU-20382 ICU4C: pkgdata and genccode support ARM32 but not ARM64 on Windows

icu4c/source/tools/gencnval/gencnval.c
If gencnval encounters an empty input file the function resolveAlias
triggers an out of boundary write due to uniqueAliasArr pointing to
a 0 byte reserved memory address.
This patch protects the code in question with a check for
knownAliasesCount being not 0.
Signed-off-by: Tobias Stoeckmann <tobias@stoeckmann.org>
=> ICU-20363 gencnval: Out of boundary write on empty input file.

icu4c/source/tools/escapesrc/escapesrc.cpp
If a file with an input line larger than INT32_MAX (i.e. 2 GB) contains
an UTF8 character after that limit, escapesrc crashes on 64 bit systems
or does not remove incomplete files on 32 bit systems.
The issue is that an unchecked cast from size_t to int32_t can turn
negative, which results in negative offsets during array access.
This will eventually lead to an out of boundary read, which most likely
crashes the tool.
This patch sets a fixed limit on 1 GB to make sure that no side effects
occur if the line is exactly INT32_MAX or a few bytes less. It should
still be way more than anyone would really need.
Signed-off-by: Tobias Stoeckmann <tobias@stoeckmann.org>
=> ICU-20362 escapesrc: segfault/leftover files with very long input lines

icu4c/source/i18n/timezone.cpp, icu4c/source/i18n/unicode/timezone.h
The `TimeZone::getDisplayName` method's "`daylight`" parameter conflicts with an existing macro in the CRT "`time.h`" header used by MinGW, causing build errors for Firefox.
The suggestion from Markus was to rename the parameter/argument to `inDaylight`.
=> ICU-20100 Change TimeZone::getDisplayName daylight parameter to avoid macro collision.

icu4c/source/i18n/unicode/decimfmt.h, icu4c/source/i18n/unicode/unum.h, icu4c/source/test/cintltst/cnumtst.c, icu4c/source/test/intltest/numfmtst.cpp, icu4c/source/test/intltest/numfmtst.h, icu4j/main/classes/core/src/com/ibm/icu/text/DecimalFormat.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/NumberFormatTest.java
This PR brings parity to the DecimalFormat APIs in C, C++, and Java.  Although new users are encouraged to use NumberFormatter, keeping these dozen or so APIs around as preview introduces technical debt.  The alternative to promoting them to @draft would be to remove them.
=> ICU-11725 Promoting tech-previews in DecimalFormat to @draft.

icu4c/source/common/uloc.cpp
Hi,
When building with LTO support and -Wall -Wextra -Werror, you might end up in your final program having build errors in ICO code:
```
uloc.cpp: In function ‘_ZL13_canonicalizePKcPcijP10UErrorCode.part.9’:
uloc.cpp:1741: error: ‘strncpy’ specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
uloc.cpp:1738: note: length computed here
lto1: all warnings being treated as errors
```
gcc simply complains that it is not so efficient to use strncpy using the exact lenght of the string computed by memcpy, since it will check for end of string uselessly. Instead using memcpy has the same behavior and is more efficient since it doesn't check the end of string.
I have not signed the CLA. Is this necessary for such a trivial pull request ?
Cheers,
Romain
=> ICU-20244 Fix gcc stringop-overflow warning/error in uloc.cpp.

icu4c/source/i18n/fmtable.cpp, icu4c/source/i18n/number_mapper.cpp, icu4c/source/i18n/number_patternstring.cpp, icu4c/source/i18n/number_patternstring.h, icu4c/source/test/cintltst/cnumtst.c, icu4j/main/classes/core/src/com/ibm/icu/impl/number/PatternStringUtils.java, icu4j/main/classes/core/src/com/ibm/icu/number/NumberPropertyMapper.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/NumberFormatTest.java
All this really does (in both C and J) is:
- Add a static method PatternStringUtils::ignoreRoundingIncrement that determines whether the roundingIncrement is so small that it would not affect any fractional places to the significance specified by maxFrac.
- Use that in NumberPropertyMapper::oldToNew and PatternStringUtils::propertiesToPatternString as an additional test of whether increment rounding should be used.
- (ignoreRoundingIncrement is in PatternStringUtils rather than NumberPropertyMapper because the latter is package private in J)
- (this PR also fixes the code in i18n/fmtable.cpp that caused a warning, introduced by another PR)
- This change does not affect the result of any existing test, but I added several new tests for it.
What this change does NOT do is change how C and J …
=> ICU-20365 if roundingIncrement significance smaller than maxFrac, do not use it

icu4c/source/i18n/msgfmt.cpp, icu4c/source/test/intltest/msfmrgts.cpp, icu4c/source/test/intltest/msfmrgts.h
We were allocating formats using wrong metric - instead of actual number of placeholders, we counted argument type counts.
Norbert and I decided to name TestICUxxxxx instead plain Testxxxx to distinguish between old Trac and new Jira numbers (to avoid confusion on where to look for issue). I am open to other ideas.
Andy said it's ok to fix trailing spaces in a CL so I left them in.
Side fixes - NULL -> nullptr
=> ICU-12584 Fix memory allocation for getFormats.

icu4c/source/i18n/unicode/numsys.h, icu4c/source/i18n/unicode/unumsys.h, icu4c/source/test/intltest/numfmtst.cpp, icu4j/main/classes/core/src/com/ibm/icu/text/NumberingSystem.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/NumberFormatTest.java
NumberingSystem is not the most well-tested class in ICU.  There are parts of its behavior that are not documented or tested.  I noticed this while working on the rest of ICU-20144.  Thought I would check it in.
Sending to @jefgen because I already have PRs pending on most of the other people I might send this to.
=> ICU-20144 Adding better documentation and behavior testing on NumberingSystem.

icu4c/source/common/uloc_tag.cpp, icu4c/source/test/cintltst/cloctst.c, icu4c/source/test/cintltst/cstrcase.c, icu4c/source/test/intltest/loctest.cpp, icu4c/source/test/intltest/loctest.h, icu4j/main/classes/core/src/com/ibm/icu/impl/locale/LanguageTag.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/ULocaleTest.java
=> ICU-20410 Fix grandfathered tag w/ extensions

icu4c/source/i18n/dtptngen.cpp, icu4c/source/test/intltest/dtptngts.cpp, icu4c/source/test/intltest/dtptngts.h, icu4j/main/classes/core/src/com/ibm/icu/text/DateTimePatternGenerator.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/DateTimeGeneratorTest.java
Since CLDR 29, the recommendation to handle the 'j' and 'J' pattern characters in skeletons has been to map them using using the "preferred" time cycle from the timeData for the locale's region. However, ICU code has still been following the earlier recommendation to use the time cycle of the standard short time format for the locale. This updates ICU to the newer recommendation.
An added test also exposed some related problems with CLDR data; filed as https://unicode.org/cldr/trac/ticket/11853; test failures due to these are skipped with logKnownIssue.
=> ICU-20383 DateTimePatternGen should map 'j' using timeData, not short time cycle

icu4c/source/test/intltest/numfmtst.cpp, icu4c/source/test/intltest/numfmtst.h, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/NumberFormatTest.java
=> ICU-13731 Adding test for default currency symbol.

.appveyor.yml
[Cygwin 3.0.0](https://cygwin.com/ml/cygwin-announce/2019-02/msg00010.html) was released on Saturday, Feb. 16, 2019 -- and now the AppVeyor CI builds for ICU4C are failing. (Previously, the AppVeyor builds used Cygwin 2.11.2.)
From the build output, it looks like `pkgdata` is failing with the following error:
`Assembly type "-a gcc-mingw64" is unknown.`
This change forces AppVeyor to use the Cygwin 2.11 release (for now) until we can further investigate the build failure on Cygwin 3.0.0
Additionally, this change removes the redundant VS2017 build from AppVeyor, since we have Azure Pipelines for VS, and also limits the git clone depth to 1 -- both in an effort to speed up the already quite slow AppVeyor CI builds.
=> ICU-20434 AppVeyor CI builds failing on Cygwin 3.0.0. Use Cygwin 2.11 for now

icu4c/source/common/unicode/urename.h, icu4c/source/common/unicode/ures.h, icu4c/source/common/uresbund.cpp, icu4c/source/common/uresimp.h, icu4c/source/i18n/timezone.cpp, icu4c/source/test/cintltst/crestst.c, icu4c/source/test/cintltst/creststn.c
This change adds an internal API `ures_openDirectFillIn` which is the same as `ures_openDirect` but allows the caller to provide a previously allocated UResourceBundle, instead of having the API always heap-allocate a new one.
We can then use this new method in the `initTZDataVersion` function to avoid (some) of the potential OOM failure problems by using a stack allocated `UResourceBundle`.
Also fixes a few issues with some of the API comments on `ures_openFillIn`.
(Aside: Once PR #449 is merged, we could use the `StackUResourceBundle` helper in the `initTZDataVersion` function.)
=> ICU-20414 Add ures_openDirectFillIn function, use it in initTZDataVersion

icu4c/source/common/uresbund.cpp, icu4c/source/test/intltest/dtptngts.cpp
https://unicode-org.atlassian.net/browse/ICU-20431
When this was discussed in the 2019–01–30 ICU TC meeting, the decision was reached that the resource loading code should be updated so that any _XX locale should fall back to the default locale, just like any und_XX locale, instead of falling back directly to the root locale.
=> ICU-20431 Both und_XX and _XX should fall back to the default locale

icu4c/source/common/uresimp.h, icu4c/source/common/wintz.cpp, icu4c/source/i18n/coll.cpp, icu4c/source/i18n/olsontz.cpp, icu4c/source/i18n/timezone.cpp, icu4c/source/i18n/zonemeta.cpp
[ICU-20249](https://unicode-org.atlassian.net/browse/ICU-20249) added a nice internal RAII helper class for stack allocated `UResourceBundle` objects to the common library.
However, the class is not marked for export, meaning that the class currently cannot be used in the i18n library without getting LINK errors on MSVC.
This change exports the class (with `U_COMMON_API`), and then replaces all current usages of `ures_initStackObject()` in the i18n library with the `StackUResourceBundle` helper class.
(Aside: Another possible alternative would have been to move the constructor/destructor implementation from `uresbund.cpp` file into to the header file `uresimp.h`, making the class "header-only" similar to the `LocalPointer` class.)
=> ICU-20419 Export internal StackUResourceBundle helper, so can be used in i18n library.

icu4j/main/classes/core/src/com/ibm/icu/text/DateFormatSymbols.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/IntlTestDateFormatSymbols.java
Straightforwad addition of getNarrowEras/setNarrowEras to ICU4J DateFormatSymbols (already present in ICU4J DateFormatSymbols), parallel to the ICU4J DateFormatSymbols getters/setters for other era name widths. Note that the narrow eras were already supported in ICU4J DateFormatSymbols data loading and formatting, but I did add a test for them to the the test for object equality.
=> ICU-13320 ICU4J DateFormatSymbols, add getNarrowEras/setNarrowEras

icu4c/source/i18n/timezone.cpp, icu4c/source/test/intltest/tztest.cpp, icu4c/source/test/intltest/tztest.h
We can use static allocated memory and placement new to avoid OOM failures for the GMT and Unknown time zones.
Note: This approach is already used in `static_unicode_sets.cpp` and `number_decimfmtprops.cpp`, so this isn't introducing any new features/dependencies with the use of `alignas` or placement new.
=> ICU-20413 OOM not handled in initStaticTimeZones() in timezone.cpp

.ci-builds/.azure-exhaustive-tests.yml
It seems that Azure Pipelines recently added support for defining the "triggers" in the YML file, rather than in the Azure DevOps site itself.
This change adds the triggers to the Exhaustive Test file -- only building the master branch, and "batch" up any pending changes, so that we only have at most 1 build running at a time.
=> ICU-20243 Setup triggers for Exhaustive Tests to only build on master

icu4c/source/i18n/datefmt.cpp, icu4c/source/i18n/smpdtfmt.cpp, icu4c/source/test/intltest/dtfmrgts.cpp, icu4c/source/test/intltest/dtfmrgts.h, icu4j/main/classes/core/src/com/ibm/icu/text/DateFormat.java, icu4j/main/classes/core/src/com/ibm/icu/text/SimpleDateFormat.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/DateFormatRegressionTest.java
Now createInstanceForSkeleton/getInstanceForSkeleton get the type for any passed-in Calendar, and add calendar keyword with that type (or replace an existing one) in the Locale it passes to [Simple]DateFormat.
Also, in DateFormat.subFormat, do not try to capitalize the first field if it is empty.
=> ICU-12902 make getInstanceForSkeleton use correct calendar; don't capitalize empty field

icu4c/source/i18n/currfmt.cpp, icu4c/source/i18n/currfmt.h, icu4c/source/i18n/measfmt.cpp, icu4c/source/i18n/number_longnames.cpp, icu4c/source/i18n/number_longnames.h, icu4c/source/i18n/quantityformatter.h, icu4c/source/i18n/tmutfmt.cpp, icu4c/source/i18n/unicode/decimfmt.h, icu4c/source/i18n/unicode/measfmt.h, icu4c/source/test/intltest/numbertest_api.cpp, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
This is an internal change in MeasureFormat.  It removes data loading from MeasureFormat and leverages the NumberFormatter plumbing for the formatting of units.
I ran MeasureFormatTest through Callgrind on master and on my branch.  The overall number of operations is lower on my branch, down from 210 MIr to 125 MIr.  Looking in more detail, you find that the *construction* cost of MeasureFormat in a new locale is significantly lower on the branch, whereas the cost of calling *.format()* is sometimes lower and sometimes higher depending on the situation.  Overall I think this is a win for performance, but of course I am a bit biased when I say that.  I filed [ICU-20433](https://unicode-org.atlassian.net/browse/ICU-20433) to work on optimization within NumberFormatter itself rather than …
=> ICU-13591 Refactor ICU4C MeasureFormat to call NumberFormatter directly

icu4c/source/common/ubidiln.cpp, icu4c/source/common/ustr_titlecase_brkiter.cpp, icu4c/source/i18n/measfmt.cpp
More warnings cropped up since the previous batch of fixes last fall.  Let's fix the GCC warnings now and avoid a release with GCC warnings.
=> ICU-20159 Fixing more GCC warnings.

icu4c/source/common/locid.cpp, icu4c/source/common/loclikely.cpp, icu4c/source/common/ulocimp.h, icu4c/source/common/uscript.cpp, icu4c/source/i18n/calendar.cpp, icu4c/source/i18n/dtptngen.cpp
https://unicode-org.atlassian.net/browse/ICU-20158
This eliminates the need for scratch buffers in any code path that ends
with these functions and also eliminates the need for counting bytes,
something that ByteSink will now handle correctly when needed.
Existing calls to uloc_addLikelySubtags() and uloc_minimizeSubtags()
throughout ICU4C implementation code are also updated to instead use
either the Locale or ulocimp_* functions with the new API.
None of this should have any externally visible effect, it's all about
cleaning up implementation internals.
=> ICU-20158 Pass ByteSink all the way to _uloc_(addLikely|minimize)Subtags().

icu4c/source/common/putil.cpp, icu4c/source/i18n/timezone.cpp, icu4c/source/i18n/unicode/timezone.h, icu4c/source/i18n/unicode/ucal.h
Per discussion in the ICU-TC call on 2018-06-06, ICU4C is supposed to be using the special zone "Etc/Unknown" when the host detection fails, and shouldn't be using "Etc/UTC".
This change modifies ICU4C to use the Unknown zone when host detection fails and updates the API docs for the C and C++ APIs to clarify what is returned in failure cases.
=> ICU-13820 ICU4C should use "Etc/Unknown" zone when host TZ detection fails

icu4c/source/data/icu-config.xml
Update icu-config.xml to include the “real” full locale names for the ff_Latn regional locales (but CLDR also has stub locales for the short names like ff_CM that alias to the full forms, so we do not need to move ff_CM and similar from icu-config.xml  to icu-locale-deprecates.xml. Also add new locales from CLDR in two categories:
- New regional locales for languages already included in ICU, e.g. en_AE
- New language ceb (Cebuano) and its regional locale ceb_PH
None of this will have any effect until I do the CLDR-to-ICU integration over the next few days.
=> ICU-20252 Update icu-config with more CLDR locales

icu4c/source/common/locdispnames.cpp, icu4c/source/common/locid.cpp, icu4c/source/common/loclikely.cpp, icu4c/source/i18n/ucol_res.cpp, icu4c/source/test/intltest/loctest.cpp, icu4c/source/test/intltest/loctest.h, icu4c/source/test/intltest/restest.cpp, icu4c/source/test/intltest/svccoll.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/LocaleDisplayNamesImpl.java, icu4j/main/classes/core/src/com/ibm/icu/util/ULocale.java, icu4j/main/tests/collate/src/com/ibm/icu/dev/test/collator/CollationServiceTest.java, icu4j/main/tests/collate/src/com/ibm/icu/dev/test/format/GlobalizationPreferencesTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/LocaleMatcherTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/TestLocaleValidity.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/ULocaleTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/data/localeMatcherTest.txt
https://unicode-org.atlassian.net/browse/ICU-20273
Please start out with reviewing the changes to the unit tests, to make sure that we're all in agreement that these accurately reflect the desired and agreed upon behaviour (before we go into the details of how to achieve this behaviour).
=> ICU-20273 Resolve inconsistent behavior of "root", "und", "" in locales

icu4c/source/i18n/plurrule.cpp, icu4c/source/test/intltest/plurults.cpp, icu4c/source/test/intltest/plurults.h, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/PluralRulesTest.java
https://unicode-org.atlassian.net/browse/ICU-20280
=> ICU-20280 PluralRules::forLocale() ignore locale extensions

icu4c/source/common/hash.h, icu4c/source/common/unicode/dtintrv.h, icu4c/source/common/unicode/locdspnm.h, icu4c/source/common/unicode/locid.h, icu4c/source/common/unicode/parsepos.h, icu4c/source/common/unicode/rbbi.h, icu4c/source/common/unicode/uniset.h, icu4c/source/common/unicode/unistr.h, icu4c/source/common/uvector.h, icu4c/source/common/uvectr32.h, icu4c/source/common/uvectr64.h
Methods implementead as 'inline' but not declared 'inline' cause clang++
to throw compilation warnings on Windows. This adds 'inline' to the
relevant method declarations.
=> ICU-20356 Fix compilation warnings 'dllimport' attribute ignored

icu4c/source/config/dist.mk
- use git instead of svn for versioning
- update generated file names to match official downloads
Example filenames:
- icu4c-63_1-c5749aaf94-src.tgz (includes git hash or tag)
- icu4c-63_1-src.tgz (hard link to above)
- icu4c-src.tgz (symlink)
- icu4c-63_1-c5749aaf94-src.zip (includes git hash or tag)
- icu4c-63_1-src.zip (hard link to above)
- icu4c-src.zip (symlink)
- icu4c-63_1-c5749aaf94-data.zip (includes git hash or tag)
- icu4c-63_1-data.zip (hard link to above)
- icu4c-data.zip (symlink)
- icu4c-63_1-c5749aaf94-docs.zip (includes git hash or tag)
- icu4c-63_1-docs.zip (hard link to above)
- icu4c-docs.zip (symlink)
=> ICU-20229 update make dist to use git, not svn

icu4c/source/i18n/smpdtfmt.cpp, icu4c/source/i18n/unicode/smpdtfmt.h, icu4c/source/test/cintltst/cdattst.c, icu4c/source/test/intltest/dtifmtts.cpp, icu4c/source/test/intltest/incaltst.cpp, icu4c/source/test/intltest/incaltst.h, icu4j/main/classes/core/src/com/ibm/icu/text/SimpleDateFormat.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/calendar/JapaneseTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/DateIntervalFormatTest.java
This adds a simple-minded hack to force Gannen year numbering (y=jpanyear)  for language "ja" with calendar=japanese, for non-numeric formats (do not include 年), if there are no number formatter overides alreaady specified.
This does not update if applyPattern subsequently changes the pattern type from numeric to non-numeric or vice-versa; that is a possible future enhancement.
Note: In the process of doing the work for this and https://github.com/unicode-org/icu/pull/465, noticed a general problem with RBNF number formatters parsing numeric date fields separated by period, filed a separate issue: https://unicode-org.atlassian.net/browse/ICU-20449
=> ICU-20441 force Gannen use if ja@calendar=japanese, non-numeric fmts, no override

icu4c/source/i18n/smpdtfmt.cpp, icu4c/source/test/intltest/dtifmtts.cpp
There was an uninitialized variable fHasHanYearChar in the previous PR-474 for ICU-20441, which caused affected the result obtained for one test (and the committed test had the wrong value). This  fixes the initialization and the test result.
=> ICU-20441 fix uninitialized fHasHanYearChar

icu4c/source/common/cmemory.h, icu4c/source/common/unicode/uobject.h, icu4c/source/common/uobject.cpp, icu4c/source/common/uresimp.h, icu4c/source/i18n/fphdlimp.h
Hi,
When building in C++ >= 11 with clang and the -Wdeprecated flag, ICU headers emit a warning for U_NO_THROW usage. It is today defined as "throw()" which is deprecated in C++11, and shall be replaced by "noexecpt" instead.
Note: my company is currently figuring out the paperwork for the CLA.
Cheers,
Romain
=> ICU-20265 Use noexcept instead of throw() in C++ >= 11.

icu4c/source/common/locdispnames.cpp, icu4c/source/common/locid.cpp, icu4c/source/common/loclikely.cpp, icu4c/source/common/uloc.cpp, icu4c/source/i18n/collationruleparser.cpp, icu4c/source/i18n/rulebasedcollator.cpp, icu4c/source/test/cintltst/cloctst.c, icu4c/source/test/intltest/loctest.cpp, icu4c/source/test/intltest/loctest.h
https://unicode-org.atlassian.net/browse/ICU-20447
For sooner or for later, these are the changes required to move the ""/"und"/"root" logic from C++ to C. I thought it best to write it all right now, while I still had it all fresh in mind.
=> ICU-20447 fix uloc_getName(x) same as Locale(x).getName() etc. for ""/"und"/"root"

.ci-builds/.azure-exhaustive-tests.yml
No actual change to the product code.
This PR simply fixes the YML config file to actually run the exhaustive tests for `cintltst` in the CI builds.
(Thanks to Andy for running the tests manually and noticing the failure!).
Note: The exhaustive test for ICU4C has a failure in cintltst test `/tsutil/cldrtest/VerifyTranslation`.
This is tracked by [ICU-20210](https://unicode-org.atlassian.net/browse/ICU-20210), which needs changes from CLDR.
=> ICU-20243 Fix exhaustive test CI builds to run cintltst.

icu4c/source/common/uresbund.cpp
Also change to using `UPRV_LENGTHOF()` instead of the macro `URES_MAX_BUFFER_SIZE`.
=> ICU-20454 Fix comparison of keyPath with stackPack in uresbund.cpp

icu4c/source/configure, icu4c/source/configure.ac, icu4c/source/data/Makefile.in
( about the runstatedir being removed from configure, see http://gnu-autoconf.7623.n7.nabble.com/Does-a-2-70-release-exist-td20904.html - Autoconf 2.70 doesn't exist yet, but it's 'out there' masquerading as 2.69.)
=> ICU-20470 fix configure to be able to run from a prebuilt data tarball

icu4c/source/configure, icu4c/source/configure.ac, icu4c/source/data/Makefile.in
Merge in 07df49c9a92c2fcc73b6b2daac5624d477e1b14f to maint branch
- If icu/source/data/locales/root.txt missing, skip
python rules.mk generation.
- Also, create build directories properly as needed
- Also includes noise changes to configure
(configure was probably generated using unreleased
autoconf 2.70 or 2.69 + patches)
- eac8f4b31ab7395abb3a216aa17bafe7af6314ed did not
regen configure properly, so BUILDTOOL_OPTS is now
ICU_DATA_BUILDTOOL_OPTS
=> ICU-20470 skip data/rules.mk regen for source tarball

icu4c/source/allinone/Build.Windows.Library.ProjectConfiguration.props
This change/fix allows for setting preprocessor defines on the command line when building with MSBUILD.
=> ICU-20474 VS library build Props file ignores command line defines with MSBUILD

icu4c/source/common/ucurr.cpp, icu4c/source/test/intltest/numbertest_api.cpp, icu4c/source/test/intltest/numfmtst.cpp, icu4c/source/test/intltest/numfmtst.h, icu4j/main/classes/core/src/com/ibm/icu/text/CurrencyDisplayNames.java, icu4j/main/classes/currdata/src/com/ibm/icu/impl/ICUCurrencyDisplayInfoProvider.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/CurrencyTest.java
=> ICU-20484 Narrow currency symbol should fall back to short symbol.

icu4c/source/i18n/number_mapper.cpp, icu4c/source/i18n/number_patternstring.cpp, icu4c/source/test/cintltst/cnumtst.c, icu4j/main/classes/core/src/com/ibm/icu/impl/number/PatternStringUtils.java, icu4j/main/classes/core/src/com/ibm/icu/number/NumberPropertyMapper.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/NumberFormatTest.java
Soould treat any formatWidth <= 0  (not just -1) as disabling padding e.g. when generating the pattern string, etc.
=> ICU-20471 setFormatWidth(0) should cause padding to be ignored in pattern etc.

icu4c/source/common/putil.cpp
There's technically no reason why the Windows UWP version should require or limit the icudtl.dat file
to be in the same directory as the icuuc.dll file.
(From looking at the history, this change was originally introduced by commit e9946ec, which itself was a merge of several other UWP related changes).
It is possible that the original comment was intended to say something along the lines of "UWP requires the icudtl.dat file be in the same package as the DLL files", but I'm not sure if it is worth adding that comment buried in some random .cpp file.
=> ICU-20491 u_getDataDirectory shouldn't set path to current dir by default on Windows

icu4c/source/common/putil.cpp
Replace the obsolete platform-specific conditional TARGET_IPHONE_SIMULATOR with the updated version TARGET_OS_SIMULATOR. The block controlled by this is still needed for some environments in which Darwin ICU is built (it is itself open-source).
=> ICU-13440 replace obsolete TARGET_IPHONE_SIMULATOR conditional

icu4j/main/classes/charset/src/com/ibm/icu/charset/CharsetUTF7.java, icu4j/main/tests/charset/src/com/ibm/icu/dev/test/charset/TestCharset.java
=> ICU-12956 fix buffer overrun of UTF-7 and IMAP-mailbox-name

icu4j/main/classes/core/src/com/ibm/icu/impl/locale/LSR.java, icu4j/main/classes/core/src/com/ibm/icu/impl/locale/LikelySubtagsBuilder.java, icu4j/main/classes/core/src/com/ibm/icu/impl/locale/LocaleDistance.java, icu4j/main/classes/core/src/com/ibm/icu/impl/locale/LocaleDistanceBuilder.java, icu4j/main/classes/core/src/com/ibm/icu/impl/locale/XLikelySubtags.java, icu4j/main/classes/core/src/com/ibm/icu/impl/locale/XLocaleMatcher.java, icu4j/main/classes/core/src/com/ibm/icu/util/LocaleMatcher.java, icu4j/main/classes/core/src/com/ibm/icu/util/LocalePriorityList.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/LocaleMatcherTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/XLocaleDistanceTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/XLocaleMatcherTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/data/localeMatcherTest.txt
Milestone: Get XLocaleMatcher ready for replacing the LocaleMatcher code. More simplifications beyond ICU-20330, smaller data, some more optimizations. New API ready to be moved over.
https://unicode-org.atlassian.net/browse/ICU-20467
=> ICU-20467 get XLocaleMatcher ready for drop-in

icu4c/source/i18n/double-conversion.cpp, icu4c/source/i18n/double-conversion.h, vendor/double-conversion/upstream/CMakeLists.txt, vendor/double-conversion/upstream/Changelog, vendor/double-conversion/upstream/double-conversion/bignum-dtoa.cc, vendor/double-conversion/upstream/double-conversion/bignum-dtoa.h, vendor/double-conversion/upstream/double-conversion/bignum.cc, vendor/double-conversion/upstream/double-conversion/bignum.h, vendor/double-conversion/upstream/double-conversion/cached-powers.cc, vendor/double-conversion/upstream/double-conversion/cached-powers.h, vendor/double-conversion/upstream/double-conversion/diy-fp.cc, vendor/double-conversion/upstream/double-conversion/diy-fp.h, vendor/double-conversion/upstream/double-conversion/double-conversion.cc, vendor/double-conversion/upstream/double-conversion/double-conversion.h, vendor/double-conversion/upstream/double-conversion/fast-dtoa.cc, vendor/double-conversion/upstream/double-conversion/fast-dtoa.h, vendor/double-conversion/upstream/double-conversion/fixed-dtoa.cc, vendor/double-conversion/upstream/double-conversion/fixed-dtoa.h, vendor/double-conversion/upstream/double-conversion/ieee.h, vendor/double-conversion/upstream/double-conversion/strtod.cc, vendor/double-conversion/upstream/double-conversion/strtod.h, vendor/double-conversion/upstream/test/cctest/test-conversions.cc
Removes the u16 separator ICU patch.
=> ICU-20439 Updating double-conversion.

icu4c/source/data/misc/currencyNumericCodes.txt, icu4j/main/shared/data/icudata.jar, icu4j/main/shared/data/icutzdata.jar, tools/currency/build.xml, tools/currency/src/com/ibm/icu/dev/tool/currency/NumericCodeData.java
=> ICU-20439 Updated currency numeric code for YUD to 890.

icu4c/source/common/cmemory.h, icu4c/source/common/dictbe.cpp, icu4c/source/common/dictionarydata.h, icu4c/source/common/rbbi.cpp, icu4c/source/common/rbbi_cache.h, icu4c/source/common/rbbiscan.h, icu4c/source/common/umutex.h, icu4c/source/common/unifiedcache.h, icu4c/source/i18n/csdetect.cpp, icu4c/source/i18n/number_decimalquantity.h, icu4c/source/i18n/number_patternstring.h, icu4c/source/i18n/numparse_types.h, icu4c/source/i18n/scriptset.h, icu4c/source/i18n/tzgnames.h, icu4c/source/i18n/tznames.cpp, icu4c/source/i18n/unicode/alphaindex.h, icu4c/source/i18n/unicode/dtitvfmt.h, icu4c/source/i18n/unicode/formattedvalue.h, icu4c/source/i18n/unicode/listformatter.h, icu4c/source/i18n/unicode/numberformatter.h, icu4c/source/i18n/unicode/numberrangeformatter.h, icu4c/source/i18n/unicode/reldatefmt.h
More precisely, I added `-Wextra-semi` to my CXXFLAGS and got rid of all the errors according to Clang4.0.1-10.
This fixes the warnings in library code, but I didn't touch test code.
Actually it's probably only important in the public header files, but it was easier to just fix it in the whole library.
=> ICU-20508 Fixing -Wextra-semi in library code.

.ci-builds/.azure-pipelines.yml
The VM images used by the Azure Pipelines for VS2015 (not VS2017) are missing Python 3.
In order to work around this, I added a step to the CI build that downloads and installs Python 3 on the build bot (see ICU-20281).
However, it was pointed out on https://github.com/Microsoft/azure-pipelines-image-generation/issues/374 that the Python installer's `PrependPath` option doesn't appear to work on the build machine.
A workaround was found by @mloskot: We can modify the `PATH` to prepend the Python directory ourselves. (Thanks for the tip!)
Also, we should take this opportunity to update the version of the Python installer too (to 3.7.2).
=> ICU-20503 Add Python 3 to the CI build PATH, and bump Python version.

icu4c/source/i18n/number_output.cpp, icu4c/source/i18n/numrange_fluent.cpp
Work-around for MSVC not handling empty arguments to a function-like macro.
=> ICU-20516 Work-around MSVC Warning C4003

icu4c/source/i18n/unicode/usearch.h, icu4c/source/i18n/usearch.cpp
=> ICU-20523 Fix typos in API docs for usearch_getMatchedLength

icu4j/main/classes/core/src/com/ibm/icu/impl/EraRules.java
ICU4C change: https://github.com/unicode-org/icu/pull/574
=> ICU-20475 Japanese calendar era calculation should use local time, not UTC (ICU4J)

icu4c/source/i18n/erarules.cpp, icu4c/source/i18n/erarules.h
The Japanese calendar current era calculation uses `ucal_getNow` to determine if new era should start or not.
However, `ucal_getNow` returns the time in UTC, not local time.
This means that the era start time in JST will actually be 9:00 AM instead of 00:00.
This change modifies `erarules.cpp` to use ICU's default time zone offset, so that the era will start relative to local time, not UTC.
Note: This is only for ICU4C, but if this looks okay then similar change should be made for ICU4J too.
ICU4J change: https://github.com/unicode-org/icu/pull/577
=> ICU-20475 Japanese calendar era calculation should use local time, not UTC (ICU4C)

icu4c/source/config/mh-darwin, icu4c/source/config/mh-solaris, icu4c/source/config/mh-solaris-gcc, icu4c/source/config/pkgdataMakefile.in, icu4c/source/data/pkgdataMakefile.in, icu4c/source/extra/uconv/pkgdataMakefile.in, icu4c/source/test/testdata/pkgdataMakefile.in, icu4c/source/tools/pkgdata/pkgdata.cpp
- added `PKGDATA_TRAILING_SPACE` to all of the pkgdataMakefile.in file.
- NOTE: Users who create their own `pkgdata.inc` /` icupkg.inc` files may need to recreate this `PKGDATA_TRAILING_SPACE` behavior.
- used the above variable, normally undefined, in `mh-*` files that need a trailing space
- Also, fixed use of `system()` in `pkgdata.cpp` per [ICU-20538](https://unicode-org.atlassian.net/browse/ICU-20538). This was causing `pkgdata` to return a zero (success) status even on clang failure, masking this issue.
=> ICU-20526 fix pkgdata where LD_SONAME has a trailing space

icu4c/source/config/mh-darwin, icu4c/source/config/mh-solaris, icu4c/source/config/mh-solaris-gcc, icu4c/source/config/pkgdataMakefile.in, icu4c/source/data/pkgdataMakefile.in, icu4c/source/extra/uconv/pkgdataMakefile.in, icu4c/source/test/testdata/pkgdataMakefile.in, icu4c/source/tools/pkgdata/pkgdata.cpp
cherry pick from #579 
- added PKGDATA_TRAILING_SPACE to all of the pkgdataMakefile.in file.
- NOTE: Users who create their own pkgdata.inc / icupkg.inc files may need
to recreate this PKGDATA_TRAILING_SPACE behavior.
- used the above variable, normally undefined, in mh-* files that need a trailing space
- Also, fixed use of system() in pkgdata.cpp per ICU-20538
This was causing pkgdata to return a zero status even on clang
failure, masking this issue.
(cherry picked from commit 83a0542b5b52a30b7af736f5ef6b0405f6582867)
=> ICU-20526 fix pkgdata where LD_SONAME has a trailing space (maint-64)

icu4j/main/tests/core/src/com/ibm/icu/dev/test/calendar/CalendarRegression.java
a5fe7b2 had a bad merge:
- extra right curlybracket
- anachronistic `@Test` annotation was backported
=> ICU-12504 Maint 4.8 fixup of bad merge

icu4c/source/i18n/dtitvfmt.cpp, icu4c/source/i18n/dtitvinf.cpp, icu4c/source/i18n/smpdtfmt.cpp, icu4c/source/i18n/unicode/udat.h, icu4c/source/test/intltest/dtifmtts.cpp, icu4c/source/test/intltest/incaltst.cpp, icu4j/main/classes/core/src/com/ibm/icu/text/DateFormat.java, icu4j/main/classes/core/src/com/ibm/icu/text/DateIntervalFormat.java, icu4j/main/classes/core/src/com/ibm/icu/text/DateIntervalInfo.java, icu4j/main/classes/core/src/com/ibm/icu/text/SimpleDateFormat.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/calendar/JapaneseTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/DateIntervalFormatTest.java
This PR does the following:
- Fixes DateIntervalInfo and DateIntervalFormat to load and use the actual intervalFormats with skeletons containing 'G' from the data
- Fixes SimpleDateFormat applyPattern to update use of Gannen year numbering based on the new pattern being applied (previously SimpleDateFormat just set the use of Gannen year numbering from the format it was initialized with)
- Fixes ICU4C TestJapanese3860 to adapt to new Japan eras
- Addes tests for Gannen updating with applyPattern
- Removes the code that skipped some DateIntervalFormatTest cases if the ICU_ENABLE_TENTATIVE_ERA  environment variable was not set
- Updates expected results from DateIntervalFormatTest now that we are loading the correct patterns
=> ICU-20537 jaEra: DateIntvFmt to load fmts with G, applyPattern to update Gannen use

icu4c/source/i18n/smpdtfmt.cpp
PR-604 introduced a leak in SimpleDateFormat::applyPattern (detected by travis tests), this fixes it
=> ICU-20537 jaEra: fix leak in SimpleDateFormat::applyPattern

icu4j/main/classes/core/src/com/ibm/icu/util/JapaneseCalendar.java
=> ICU-20534 Add Japanese era constant for REIWA in ICU4J JapaneseCalendar

icu4c/source/i18n/japancal.cpp, icu4c/source/test/cintltst/ccaltst.c
This changes Japanese calendar calculations to include through the last valid era, not just the current one (based on system time). For example, ucal_add UCAL_ERA +1 should not pin the era until in the last valid era.
This PR is just for the ICU4C changes, the ICU4J changes will be in another PR
Note, without the library code fixes, the added test produced the following:
```
TestJpnCalAddSetNextEra   {
!!    ERROR: set 1 then add ERA 1, expected start year 2019 but get 1989
!!    ERROR: set 2 then add ERA 1, expected start year 2019 but get 1989
}
```
=> ICU-20550 jaEra: use all valid eras for calendar calculations

icu4c/source/i18n/regexcmp.cpp, icu4c/source/test/testdata/regextst.txt
=> ICU-20544 Regex, Fix assertion failure in positive look-behind

icu4c/source/test/testdata/format.txt, icu4j/main/shared/data/testdata.jar
TestConsistentPivot will start failing after April 30, because it contains test data depending on date of execution. The current expected value is valid when current era is still Heisei, but it is not longer valid starting on May 1, 2019 because current era will be changed to Reiwa.
For now, we want to disable the test case, because this will definitely introduce some confusions.
=> ICU-20554 Disabled current date sensitive Japanese era test cases

icu4c/source/allinone/Build.Windows.Library.WarningSettings.ProjectConfiguration.props
=> ICU-20513 Treat MSVC warnings C4910 and C4003 as errors in library code

icu4j/main/tests/packaging/src/com/ibm/icu/dev/test/TestLocaleNamePackaging.java
These test expectations have been out-of-sync with the output that ICU4J
actually generates for quite some time now. This change brings the
expectations in sync with actual behaviour and makes the test pass.
=> ICU-12431 Update test expectations in TestLocaleNamePackaging.

icu4c/source/config/mh-darwin
- in the rpath case, we do NOT want a trailing space in LD_SONAME
regression was introduced in ICU-20526 with
83a0542b5b52a30b7af736f5ef6b0405f6582867 (master)
b76cb6517efa113739a3ffadda7ff024db0d5689 (in maint-64)
=> ICU-20563 fix macosx rpath breakage in the data build

icu4c/source/config/mh-darwin
maint-64 version of https://github.com/unicode-org/icu/pull/625
- in the rpath case, we do NOT want a trailing space in LD_SONAME
regression was introduced in ICU-20526 with
83a0542b5b52a30b7af736f5ef6b0405f6582867 (master)
b76cb6517efa113739a3ffadda7ff024db0d5689 (in maint-64)
(cherry picked from commit ~7471c531b343f2a05c3ccdf8acbfebc16a3a8f77~ 1c553b9 )
=> ICU-20563 fix macosx rpath breakage in the data build (maint-64)

icu4c/source/i18n/regexcmp.cpp, icu4c/source/test/testdata/regextst.txt
=> ICU-20391 Fix regexp crash with nested look-behinds, from fuzz testing.

icu4c/source/i18n/dtptngen.cpp, icu4c/source/test/intltest/dtptngts.cpp, icu4c/source/test/intltest/dtptngts.h
(Thanks to @gvictor for tracking down the issue.)
This [commit](https://github.com/unicode-org/icu/commit/b12a927c9365bb38831afbf76fdd0999f8f33deb) for [ICU-13778](https://unicode-org.atlassian.net/browse/ICU-13778) improved the error checking in the `DateTimePatternGenerator` class, adding checks for errors/failures where there previously was none at all. This was done in order to catch catastrophic errors like out-of-memory (OOM), and properly report them to the caller, rather than ignoring/hiding these errors.
However, in doing so it exposed a case where the code was depending on ignoring errors in order to fallback to the Gregorian calendar when the default ICU locale is set to root.
This commit restores the previous behavior, by allowing the error of `U_MISSING_RESOURCE_ERROR` to …
=> ICU-20558 Fix compat issue with DateTimePatternGenerator fallback to default root locale

.travis.yml, icu4c/source/common/unicode/ucptrie.h, icu4c/source/common/unicode/udata.h, icu4c/source/common/unicode/uversion.h, icu4c/source/i18n/unicode/reldatefmt.h, icu4c/source/i18n/unicode/uspoof.h
Remove explicit extern "C++" scope.
Fix issues detected by make -C test/hdrtst.
Run test/hdrtest during CI to detect future breakage.
Signed-off-by: Alon Bar-Lev <alon.barlev@gmail.com>
=> ICU-20530 Fix header issues based on test/hdrtst

icu4c/source/common/putil.cpp
- Fix issues from 1afef30549d93c17bb966c6803d5d943cf055925 / PR #418
1. `LANG=C.UTF-8` would not map to `en_US_POSIX` but to invalid language `c`
2. `LANG=aa@BB` (and similar) would map to `aa__BB__BB`
=> ICU-20575 fix broken default locale mapping for C.UTF-8

icu4c/source/i18n/dtptngen.cpp, icu4c/source/test/intltest/dtptngts.cpp, icu4c/source/test/intltest/dtptngts.h
Backporting to ICU 64.
This is cherry-picked from commit: 693adf3987c192c9ec649bc88e3e41b52f23204d
See pull-request #632.
This fixes a regression introduced by commit 
b12a927c9365bb38831afbf76fdd0999f8f33deb for issue [ICU-13778](https://unicode-org.atlassian.net/browse/ICU-13778).
The above commit improved the error checking in the
DateTimePatternGenerator class, adding checks for errors/failures
where there previously was none at all. This was done in order to
catch catastrophic errors like out-of-memory (OOM), and properly
report them to the caller, rather than ignoring/hiding these errors.
However, in doing so it exposed a case where the code was depending
on ignoring errors in order to fall-back to the Gregorian calendar
when the default ICU locale is set to root.
This restores the …
=> ICU-20558 Fix regression in DateTimePatternGenerator (Backport for 64)

icu4c/source/i18n/dtptngen.cpp, icu4c/source/test/intltest/dtptngts.cpp, icu4c/source/test/intltest/dtptngts.h
Backporting to ICU 63.
This is manually cherry-picked from commit: 693adf3987c192c9ec649bc88e3e41b52f23204d
See pull-request #632.
This fixes a regression introduced by commit
b12a927c9365bb38831afbf76fdd0999f8f33deb for issue [ICU-13778](https://unicode-org.atlassian.net/browse/ICU-13778).
The above commit improved the error checking in the
DateTimePatternGenerator class, adding checks for errors/failures
where there previously was none at all. This was done in order to
catch catastrophic errors like out-of-memory (OOM), and properly
report them to the caller, rather than ignoring/hiding these errors.
However, in doing so it exposed a case where the code was depending
on ignoring errors in order to fall-back to the Gregorian calendar
when the default ICU locale is set to root.
This …
=> ICU-20558 Fix regression in DateTimePatternGenerator (Backport for 63)

icu4c/source/common/putil.cpp
Regression was in 1afef30549d93c17bb966c6803d5d943cf055925
PR #418 [ICU-20187]
- We dropped the mapping from "C" in `uloc_canonicalize`,
but then putil.cpp did not handle cases where a codepage was
set (such as "C.UTF-8").
- Add an additional check in `uprv_getDefaultLocaleID()` for
locales that end up as "C" or "POSIX" after removing codepage
suffix.
- Also fix regression where aa@bb would become aa__BB__BB
(incorrectly doubled __BB)
(cherry picked from commit 075cefb2e21f57f4cac1bc2868e93dd1b8c077cc and #634 )
[ICU-20187]: https://unicode-org.atlassian.net/browse/ICU-20187
=> ICU-20575 locale mapping for C.UTF-8 - 64-maint backport

icu4c/source/tools/genrb/reslist.cpp
=> ICU-20593 Genrb: Remove keys if bundle is empty after filtering.

icu4c/source/data/BUILDRULES.py
The option was added in b603285, but the option was not being used.
=> ICU-20593 Consuming ignore_xml_deprecates option in BUILDRULES.py.

.ci-builds/.azure-pipelines.yml
This runs the `distrelease.ps1` script to package up the Windows binaries on the Azure CI build machines (for x64 Release) into a zip file, and then publishes the file as a build "artifact" for the pipline.
This will allow us to use the generated binaries from the CI build machines for the BRS tasks.
=> ICU-20549 Publish Windows build artifacts from CI builds (x64 Release)

icu4c/source/i18n/timezone.cpp, icu4c/source/i18n/unicode/timezone.h, icu4c/source/test/intltest/tzfmttst.cpp, icu4c/source/test/intltest/tzfmttst.h
=> ICU-20595 Make icu::TimeZone::AdoptDefault thread safe

icu4c/source/test/intltest/intltest.vcxproj.filters
ICU-20613 fix missing ` </ClInclude>`
=> ICU-20613 fix missing  </ClInclude>

icu4c/source/i18n/dtptngen.cpp
Commit that introduced this (~2 yrs ago): https://github.com/unicode-org/icu/commit/e2e48c9dce85e1a460c32df5e6b8bd84c6fcf0fb
=> ICU-20625 Fixing uninitialized memory in DTPG detected by Valgrind.

icu4c/source/common/localebuilder.cpp, icu4c/source/common/unicode/localebuilder.h
=> ICU-20602 copyErrorTo() functions should be const

icu4c/source/common/unicode/platform.h
[ICU-20608]
Adds basic platform defines for Emscripten, a C++ toolchain for the Web that can target asm.js and WebAssembly. Note that this does not make icu4c fully build with Emscripten yet.
[ICU-20608]: https://unicode-org.atlassian.net/browse/ICU-20608
=> ICU-20608 Add platform defines for Emscripten.

icu4c/source/python/icutools/databuilder/request_types.py
Small fix, whoops; manifests itself with `--filter_file` is used.  We should probably make a BRS task that checks that code path, or add something to the automated build.
=> ICU-20627 Fixing typo introduced by #670.

icu4c/source/data/makedata.mak
Back-porting to ICU 64. 
(cherry picked from commit d72aa9142925691c3197f60949f42ca67650ae1f)
=> ICU-20658 Fix broken Data Filtering on Windows builds. (backport for 64)

icu4c/source/i18n/ucal.cpp
The `ucal_open` API will leak the TimeZone object `zone` if the calendar type is `UCAL_GREGORIAN`  and the `uloc_setKeywordValue` fails (for any reason). 
If we use a LocalPointer for the TimeZone object, then we can prevent the leak.
=> ICU-20647 Fix TimeZone leak in ucal_open if uloc_setKeywordValue fails.

.ci-builds/.azure-pipelines.yml, .ci-builds/data-filter.json
This adds two extra CI builds to exercise the Data Filtering on Linux with Clang and on Windows with MSVC.
Notes:
I'm only using the simple example file from the [ICU Data Build Tool](https://github.com/unicode-org/icu/blob/master/docs/userguide/icu_data/buildtool.md) document for now, and adding it to the `.ci-builds` sub-folder.
We could move it somewhere else if you wanted, or use more advanced data filtering -- this is mainly just to have CI build coverage for now.
Also, these builds don't run any tests, as the reduced data bundle would cause test failures.
=> ICU-20664 Add CI builds that exercise the Data Filtering.

icu4c/source/test/intltest/loctest.cpp, icu4c/source/test/intltest/loctest.h, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/ULocaleTest.java
=> ICU-20661 Adding test that (U)Locale constructor accepts BCP47.

icu4c/source/extra/Makefile.in, icu4c/source/extra/scrptrun/scrptrun.cpp, icu4c/source/extra/scrptrun/scrptrun.h, icu4c/source/extra/scrptrun/srtest.cpp
ICU-20566: ICU now uses namespaces. When trying to use the scrptrun.h header, the
header cannot compile stand-alone as it is inheriting from UObject which
is namespaced now. Add namespace macros to properly inherit.
This PR might be incomplete.  There is an srtset.cpp file that also needs to be updated but I'm not sure what the right way to do it is.  I was also asked to add these files to the default build but I'm not certain how to as I think they are already part of the build.  Can someone please help me verify this?
=> ICU-20566 Add missing ICU namespace macros for extra files

icu4c/source/test/fuzzer/collator_compare_fuzzer.cpp
=> ICU-20652 Corrects calculation of byte sequence length to prevent buffer

docs/userguide/icu_data/tracing.md, icu4c/source/common/restrace.cpp, icu4c/source/common/restrace.h, icu4c/source/common/unicode/utrace.h, icu4c/source/common/uresbund.cpp, icu4c/source/common/utrace.cpp, icu4c/source/test/intltest/restsnew.cpp
=> ICU-20593 Various updates to resource tracing.

icu4c/source/config/mh-mingw, icu4c/source/config/mh-mingw64
The Azure DevOps VM images that are used in the CI builds recently updated the version of MSYS that is installed, which is causing the MSYS builds to fail. It seems that this new version has issues with using the `shell cmd` method in the makefiles to obtain the current path.
However, we can avoid this entirely by using the `cygpath` utility, which also avoids the overhead of launching a new `cmd` instance just to get the path.
Unfortunately, it seems that older versions of MSYS don't have this utility program included by default, though versions of MSYS 2 and up do have it included by default.
We can continue using the old approach for the older versions and use the `cygpath` approach for new versions.
This PR supplants/replaces PR #709.
=> ICU-20718 Fix failing MSYS2 build due to current path confusion.

icu4c/source/i18n/unicode/unum.h
=> ICU-20721 Fix typo in API docs about unumf_openForSkeletonAndLocale.

icu4c/source/configure, icu4c/source/configure.ac
[ICU-20493]
- add -Wglobal-constructors to clang (only for libs)
- Note: ignore 'runstatedir' flap in configure
[ICU-20493]: https://unicode-org.atlassian.net/browse/ICU-20493
=> ICU-20493 Warn on global/static c’tors

icu4c/source/common/common_uwp.vcxproj
onecore.lib is on all devices, while onecoreuap.lib is only on devices that support UWP. Moving down to OneCore.lib means being able to target more devices.
See https://docs.microsoft.com/en-us/windows/win32/apiindex/windows-umbrella-libraries for additional info.
=> ICU-20747 Change dependency for common_uwp from onecoreuap.lib to onecore.lib

.travis.yml
=> ICU-20766 Fix failing TravisCI build for ICU4J due to missing ANT.

icu4c/source/common/utrie.h, icu4c/source/i18n/tzfmt.cpp, icu4c/source/samples/cal/cal.c, icu4c/source/test/cintltst/callcoll.c, icu4c/source/test/cintltst/capitst.c, icu4c/source/test/cintltst/cbiapts.c, icu4c/source/test/cintltst/ccaltst.c, icu4c/source/test/cintltst/cnumtst.c, icu4c/source/test/cintltst/crestst.c, icu4c/source/test/cintltst/cstrtest.c, icu4c/source/test/cintltst/nccbtst.c, icu4c/source/test/cintltst/ncnvtst.c, icu4c/source/test/cintltst/reapits.c, icu4c/source/test/cintltst/spooftest.c, icu4c/source/test/cintltst/ucnvseltst.c, icu4c/source/test/intltest/utxttest.cpp
https://unicode-org.atlassian.net/browse/ICU-20601
These inconsistent uses of statement terminating semicolons were found while working on the macro definitions that trigger -Wextra-semi-stmt in client code. We might just as well clean them up.
=> ICU-20601 Remove and add semicolons for consistency

icu4c/source/common/unicode/bytestrie.h, icu4c/source/common/unicode/ucharstrie.h, icu4c/source/test/intltest/bytestrietest.cpp, icu4c/source/test/intltest/ucharstrietest.cpp, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/BytesTrieTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/CharsTrieTest.java
https://unicode-org.atlassian.net/browse/ICU-20735
Note: C++ test functions copied from the functions for the older state-saving API, then modified to match the new, parallel Java test functions.
=> ICU-20735 simpler state saving for C++ string tries

icu4c/source/i18n/decimfmt.cpp, icu4c/source/i18n/plurfmt.cpp, icu4c/source/i18n/quantityformatter.cpp, icu4c/source/i18n/smpdtfmt.cpp, icu4c/source/i18n/unicode/decimfmt.h
=> ICU-20423 Removing deprecated method toNumberFormatter()

icu4c/source/i18n/unicode/numfmt.h
Note: there is a test for this already in numfmtst.cpp
=> ICU-13596 Clarifying error code type in numfmt.h parse()

icu4c/source/i18n/ucal.cpp, icu4c/source/i18n/unicode/ucal.h, icu4c/source/test/cintltst/ccaltst.c
In ICU4C there is a C++ API for getting the host OS timezone (not ICU's default time zone) which doesn't cache the result: `TimeZone::detectHostTimeZone`.
This is useful for applications that want to determine the host OS timezone, and to detect if it has changed.
However, there is no corresponding C API for this functionality.
This adds a new public C API `ucal_getHostTimeZone` which exposes this functionality to C API users.
=> ICU-20759 Add ucal_getDefaultTimeZone C API for host OS timezone detection

icu4c/source/common/unicode/stringpiece.h, icu4c/source/configure, icu4c/source/configure.ac, icu4c/source/test/intltest/strtest.cpp, icu4c/source/test/intltest/strtest.h
https://unicode-org.atlassian.net/browse/ICU-20758
Using the C++ SFINAE (substitution failure is not an error) technique,
it's possible to provide an icu::StringPiece constructor that accepts
any string view type that might be available in the current compilation
unit, without adding any additional dependencies or configuration flags
to ICU.
=> ICU-20758 Add a StringPiece constructor for any string view type

icu4c/source/common/unicode/ucptrie.h, icu4c/source/common/unicode/umachine.h, icu4c/source/common/unicode/utext.h, icu4c/source/common/unicode/utf16.h, icu4c/source/common/unicode/utf8.h, icu4c/source/common/unicode/utf_old.h
https://unicode-org.atlassian.net/browse/ICU-20601
This is the normal way of making compound macros behave like statements
and allowing macro invocations that look like function calls to work
just like if they were function calls.
Before ICU 65, function like multi statement ICU macros were just
defined as series of statements wrapped in { } blocks and the caller
could choose to either treat them as if they were actual functions and
end the invocation with a trailing ; creating an empty statement after
the block or else omit this trailing ; using the knowledge that the
macro would expand to { }.
To continue supporting code that depends on that old behaviour, on being
able to omit the trailing ; when invoking one of these macros, the new
surrounding do { } while is done through …
=> ICU-20601 Wrap public ICU API compound macros in do { } while.

icu4c/source/common/loclikely.cpp, icu4c/source/common/ubidiimp.h, icu4c/source/common/ubiditransform.cpp, icu4c/source/common/ucase.cpp, icu4c/source/common/ucnv_lmb.cpp, icu4c/source/common/ucnvbocu.cpp, icu4c/source/common/ucnvhz.cpp, icu4c/source/common/ucnvisci.cpp, icu4c/source/common/uhash.cpp, icu4c/source/common/uloc.cpp, icu4c/source/common/unames.cpp, icu4c/source/common/uniset_props.cpp, icu4c/source/common/ustring.cpp, icu4c/source/common/utracimp.h, icu4c/source/common/utrie.h, icu4c/source/common/utrie2.h, icu4c/source/i18n/bocsu.h, icu4c/source/i18n/decNumberLocal.h, icu4c/source/i18n/dtitvinf.cpp, icu4c/source/i18n/number_skeletons.cpp, icu4c/source/i18n/rbnf.cpp, icu4c/source/tools/genrb/rle.c, icu4c/source/tools/genrb/ustr.h
This does the same for the ICU implementation code as was done for the public ICU API in PR #759.
This is not necessary to do in order to enable users of ICU to use -Wextra-semi-stmt when building their own code (that has now already been resolved), but it will make it possible to use this warning when building ICU itself which is useful both to weed out mistakes in the ICU code itself and to prevent future changes that cause this warning to creep in into the public ICU API. It'll also make macro definitions consistent in ICU between API and implementation code.
=> ICU-20601 Wrap ICU implementation compound macros in do { } while.

icu4j/main/classes/core/src/com/ibm/icu/impl/StaticUnicodeSets.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/DecimalFormatProperties.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/parse/IgnorablesMatcher.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/parse/NumberParserImpl.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/parse/ParsingUtils.java, icu4j/main/classes/core/src/com/ibm/icu/text/DecimalFormat.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/NumberFormatJavaCompatilityTest.java
The internal parse mode is introduced for Android libcore.
=> ICU-20623 Introduction of a new parse mode called "compatibility" in DecimalFormat

icu4c/source/i18n/regexcmp.cpp, icu4c/source/i18n/regeximp.h, icu4c/source/i18n/rematch.cpp, icu4c/source/test/intltest/regextst.cpp, icu4c/source/test/testdata/regextst.txt
=> ICU-20618 regex nested look around, fix restore of original input bounds when leaving blocks

icu4c/source/common/umutex.cpp, icu4c/source/common/umutex.h
Adds `U_ASSERT` check before using `m->lock()` to make allocation issues
more apparent at least in debug builds.
There is probably quite a few places like this, but let's try fixing
broken windows.
=> ICU-20776 Checks for nullness in UMutex::lock()

icu4c/source/i18n/usearch.cpp, icu4c/source/test/cintltst/ccaltst.c
Adding comments about the changes in PR #780 for posterity, and also so that searching for `UPRV_UNREACHABLE` is easier in the future for the follow-up ticket [ICU-20792].
(Thanks Peter for making the changes in PR #780).
[ICU-20792]: https://unicode-org.atlassian.net/browse/ICU-20792
=> ICU-20680 Add comments about UPRV_UNREACHABLE to CEIBuffer::get[Previous] and test case

tools/cldr/cldr-to-icu/README.txt, tools/cldr/cldr-to-icu/build-icu-data.xml, tools/cldr/cldr-to-icu/pom.xml, tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/IcuConverterConfig.java, tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/LdmlConverter.java, tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/LdmlConverterConfig.java, tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/ant/ConvertIcuDataTask.java
This PR adds the ability to build via Ant (in order to take care of the complex arguments needed).
See the README.txt for information.
Note that Ant is NOT being used to compile anything and just calls out to Maven to do that and then links to a standalone JAR file (to avoid needing to know anything about class paths etc.).
The alternative to this was XML properties file(s) but they don't support nested structures, so I'd have had to hack it with special "paths" in key names.
=> ICU-20693 Adding Ant support for configuration of ICU data builds.

icu4c/source/python/icutools/databuilder/renderers/common_exec.py
When building ICU4C from a long folder path on Windows, the data build portion of the build process will **fail** as the length of the command line passed to `genrb.exe` exceeds the maximum length supported by CMD, which is 8191 characters.
One possible method of working around this is to modify/hack the Python data build scripts.
However, that has the the unfortunate result of losing some of the parallelism in some cases, as the 
`RepeatedOrSingleExecutionRequest` needs to be changed to a `SingleExecutionRequest` in order to move the decision about whether or not to pass the the locale listing as an argument list or as a file to `genrb.exe` earlier in the data build process.
Instead, it turns out that we can actually use PowerShell instead to execute the command when the length exceeds …
=> ICU-20555 Fix Windows data build failure with long paths

icu4c/source/i18n/decimfmt.cpp, icu4c/source/test/cintltst/cnumtst.c
The test is plain C, matching the compatibility issue as actually reported.
=> ICU-20620 cap UNUM_MAX_FRACTION_DIGITS setting at 999

.ci-builds/.azure-pipelines.yml
This adds another build bot that builds ICU4C on MacOSX 10.14 using Clang with Warnings-as-Errors, in order to have additional coverage.
cc: @jungshik as FYI.
=> ICU-13764 Add a MacOSX CI build with Warnings-as-Errors

icu4c/source/test/intltest/plurults.cpp, icu4c/source/test/intltest/plurults.h, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/PluralRulesTest.java
The original problem appears to have been already fixed in ICU 64.1 with https://github.com/unicode-org/icu/pull/471, so all I am doing here is adding more tests.
=> ICU-20701 Add more PluralRules tests for locales with keywords

icu4c/readme.html
Probably worth adding a note to the README.html file that all of the public C++ headers are now guarded with the macro "`U_SHOW_CPLUSPLUS_API`".
=> ICU-20795 Add comment to ICU4C Readme.html about U_SHOW_CPLUSPLUS_API.

icu4c/source/i18n/number_formatimpl.cpp
=> ICU-20368 OOM not handled in NumberFormatterImpl::macrosToMicroGenerator

icu4c/source/common/uloc.cpp
We need to use `LocalMemory` instead of `LocalPointer` in the function `uloc_openKeywordList`.
Both `UEnumeration` and `UKeywordsContext` are expected to be eventually released with `uprv_free` as they are supposed to be allocated with `uprv_malloc`. Using a `LocalPointer` means they would be allocated with operator `new` instead.
Thanks to @markusicu for catching this!
=> ICU-20802 Need to use LocalMemory in uloc_openKeywordList, not LocalPointer

tools/cldr/cldr-to-icu/pom.xml
I have no idea why, but my Maven setup had used version 65.1 of the ICU4J dependency in the pom file. Perhaps it was configured locally (e.g. my setup or in Google) for some reason but it stopped working abruptly for me tonight (Maven would not build and could not resolve the dependency). I set it back to 64.2 and added some comments, and everything appears to work again. Very odd.
=> ICU-20693 Fix weird bug in Maven pom file and add comments

icu4c/source/i18n/gregocal.cpp, icu4c/source/test/intltest/calregts.cpp, icu4c/source/test/intltest/calregts.h
[ICU-13745] fix undefined behavior in GregorianCalendar::setGregorianChange
- Julian days outside of INT32_MIN..INT32_MAX are normalized
- Add a test case
[ICU-13745]: https://unicode-org.atlassian.net/browse/ICU-13745
=> ICU-13745 fix UBS in gregocal

icu4c/source/test/cintltst/ccaltst.c
The issue was found by Norbert while running the Environment tests for the ICU 65 BRS.
It looks like the test case for the C wrapper I added in ICU 65 (`ucal_getHostTimeZone`) exposed a latent issue in the cintltst test code.
The cintltst fails for "America/Argentina/ComodRivadavia", which has length of 32, the same as the buffer that the test is using.
This results in the string being not terminated with a NUL, leading to the new test case failing.
This PR increases the buffer size used by the test, and also checks for the string not terminated warning.
=> ICU-20807 BRS65: Environment test failure in cintltst-timezone

icu4c/source/common/unicode/docmain.h
For ICU 65rc: https://unicode-org.atlassian.net/browse/ICU-20795
=> ICU-20795 add LocaleMatcher to API docs index

tools/cldr/cldr-to-icu/.classpath, tools/cldr/cldr-to-icu/.project, tools/cldr/cldr-to-icu/.settings/org.eclipse.jdt.core.prefs, tools/cldr/cldr-to-icu/.settings/org.eclipse.jdt.ui.prefs, tools/cldr/cldr-to-icu/.settings/org.eclipse.m2e.core.prefs
This is by no means complete, but represents the basic settings for classpaths and import ordering.
Importantly, when IntelliJ is set up and told to use/import Eclipse settings, it produces 100% identical import statements (consistency is the most important thing).
=> ICU-20693 Basic Eclipse settings

icu4c/source/common/unicode/locid.h
[ICU-20795]
- fixup some functions in locid.h that were incorrectly guarded as draft
- Error was in:
- 5a3ea669aaf3f2c3984e1a10b3998d4b736621bf
- https://github.com/unicode-org/icu/pull/808
[ICU-20795]: https://unicode-org.atlassian.net/browse/ICU-20795
=> ICU-20795 ICU4C 65.1 API promotion - locid.h fix

icu4c/source/test/intltest/reldatefmttest.cpp
Just added an ICU4C test that RelativeDateTimeFormatter now works in Afrikaans
=> ICU-20396 add RelativeDateTimeFormatter test for af

icu4c/source/test/intltest/caltest.cpp
The purpose of the FIELD_NAME_STR() macro is to create a string literal
by using the # preprocessing operator and then skip the first 5 chars of
this string by using the +5 pointer arithmetic. This is all intentional,
but if the parentheses are misplaced the compiler might think that this
is a mistake, a failed string concatenation (-Wstring-plus-int).
=> ICU-20819 Correct placement of parentheses in preprocessor macro.

icu4c/source/i18n/usearch.cpp, icu4c/source/test/cintltst/usrchtst.c
=> ICU-20832 use uint32_t instead of uint16_t to avoid overflows for very long strings

icu4c/source/i18n/smpdtfmt.cpp, icu4c/source/i18n/unicode/smpdtfmt.h
The issue at hand is a fairly rare data race; the only way I found to reliably reproduce it in a unit test was to add a 20 millisecond sleep in [`rbbi_cache.cpp`](https://github.com/unicode-org/icu/blob/c78d9fa13762b7ae1ee9aec623d0b818d02a9956/icu4c/source/common/rbbi_cache.cpp#L434-L435), and to then simultaneously call `format` with different values from many threads on a `SimpleDateFormat` created as follows.
```C++
icu::ErrorCode error;
// NOTE: The choice of pattern and locale here is important: the resulting
// date must start with a lowercase letter in its default capitalization, so
// that we actually go through the capitalization code.
icu::Locale french("fr_FR");
icu::SimpleDateFormat simple_date_format(icu::UnicodeString::fromUTF8("cccc"),
french,
error); …
```
=> ICU-20831 Eliminate a data race in SimpleDateFormat::format.

tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/mapper/Bcp47Mapper.java, tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/mapper/BreakIteratorMapper.java, tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/mapper/CollationMapper.java, tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/mapper/DayPeriodsMapper.java, tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/mapper/PluralRangesMapper.java, tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/mapper/PluralsMapper.java, tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/mapper/SupplementalMapper.java
This is an optional, but very "nice to have" PR which removes all non-test use of the "ARBITRARY" order. As soon as everything is in and we're happy to change ICU files a bit, I will remove all ability to control path ordering from the API and go with DTD order everything (this will change supplemental data order a lot). This isolates ICU from any XML file ordering, which seems like a good thing. This PR is just me getting rid of the really egregious case ("arbitrary ordering") first since it really doesn't have any need to exist any more.
=> ICU-20693 No arbitrary ordering in path/value visitation for new API

icu4j/main/classes/core/src/com/ibm/icu/text/SimpleDateFormat.java
This is the J fix corresponding to the C fix in https://github.com/unicode-org/icu/pull/839
=> ICU-20831 clone capitalizationBrkIter for actual use

icu4c/source/i18n/unicode/plurrule.h
I checked all the public header files and this is the only header with code that uses `U_SHOW_CPLUSPLUS_API` before including `utypes.h`.
I'll file a separate ticket for after ICU 65 to add an automated test to the hdrtest.
=> ICU-20836 ICU4C header plurrule.h needs to include utypes.h before using U_SHOW_CPLUSPLUS_API

icu4c/source/common/unicode/umachine.h
[ICU-20813]
- This comment failed on gcc. Split it into two lines.
[ICU-20813]: https://unicode-org.atlassian.net/browse/ICU-20813
=> ICU-20813 Fix Multi-line comment in umachine.h

icu4c/source/test/hdrtst/Makefile.in
https://unicode-org.atlassian.net/browse/ICU-20839
This adds another test/check to the `hdrtst` checker, which is intended to catch any usage of the macro `U_SHOW_CPLUSPLUS_API` without properly including the header file `utypes.h` first -- which causes/caused issues like ICU-20836.
The header file `utypes.h` is what defines the macro `U_SHOW_CPLUSPLUS_API`. So if a public header file uses the macro *before* it is defined it will evaluate as 0, causing the code to be removed by the preprocessor.
The test works by creating a temporary cpp file that includes each public header file that refers to `U_SHOW_CPLUSPLUS_API`, and then checks that the macro is actually defined *after* including the public header file.
If the macro is used before `utypes.h` is included, then the definition of …
=> ICU-20839 Add header test for utypes.h when using U_SHOW_CPLUSPLUS_API

icu4c/source/test/intltest/numfmtst.cpp, icu4c/source/test/intltest/numfmtst.h, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/NumberFormatTest.java
=> ICU-13734 Adding tests for DecimalFormat strict mode handling of flexible whitespace

icu4c/source/data/makedata.mak
The `tool_cfg` setting that is passed to the Python data build script should use `CFGTOOLS` instead of `CFG`.
The rest of the `Makedata.mak` makefile uses `CFGTOOLS`, so this is inconsistent.
However, this also causes build failures on ARM64 builds when the data file hasn't previously been built (for either x86 or x64). -- (Thanks to Marc Sweetgall for reporting/finding this!).
=> ICU-20859 ICU4C: Python data build uses wrong value for tool_cfg

icu4c/source/python/icutools/databuilder/renderers/common_exec.py
There is an edge case that was missed in the change for ICU-20858.
The length of the path to the current `COMSPEC` should be included in the length of the total command line.
Otherwise it is still possible for the command line length to exceed the 8,191 length limit, leading to build failures.
=> ICU-20858 Fix Windows data build failure with long paths

icu4c/source/common/locid.cpp, icu4c/source/test/intltest/loctest.cpp, icu4c/source/test/intltest/loctest.h
=> ICU-20862 Fix setKeywordValue U_BUFFER_OVERFLOW_ERROR bug.

icu4c/source/common/uloc_tag.cpp, icu4c/source/test/cintltst/cloctst.c, icu4c/source/test/intltest/loctest.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/locale/InternalLocaleBuilder.java, icu4j/main/classes/core/src/com/ibm/icu/util/ULocale.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/ULocaleTest.java
=> ICU-20478 Sort variant in (for|to)LanguageTag of icu::Locale and ULocale

icu4c/source/i18n/repattrn.cpp
https://unicode-org.atlassian.net/browse/ICU-20863
Follow-up on PR #890
=> ICU-20863 Regex Named Capture map, add a missing nullptr check.

tools/cldr/cldr-to-icu/build-icu-data.xml, tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/AlternateLocaleData.java, tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/ant/ConvertIcuDataTask.java
This should now match the desired behaviour used by Google to remap alt-values for paths.
You can now specify a list of locale IDs for an <altPath> element and any source paths are removed from the filtered data.
=> ICU-20693 Fix alt values to support per-locale mappings and remove source paths.

tools/cldr/cldr-to-icu/build-icu-data.xml, tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/IcuConverterConfig.java, tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/LdmlConverter.java, tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/LdmlConverterConfig.java, tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/ant/ConvertIcuDataTask.java
This restructures the build-icu-data.xml Ant build file a bit and adds more support to manage the additional mechanisms needed to support the special case rewriting of locale parents in certain ICU directories.
Once the build system is changed to use the dependency graph information produced by the conversion tool (rather than the files produced by the old system), this PR should provide the last step in the chain to create 100% compatible ICU output.
=> ICU-20693 Reworking Ant structure to better explain and reflect 'tailorings'

icu4c/source/i18n/decimfmt.cpp, icu4c/source/i18n/number_formatimpl.cpp, icu4c/source/i18n/number_mapper.cpp, icu4c/source/test/cintltst/cnumtst.c, icu4c/source/test/intltest/numbertest_api.cpp
- In NumberPropertyMapper::oldToNew, remove restriction against minInt=minFrac=0 (only if maxInt != 0)
- Ensure DecimalFormat::doFastFormatInt32 always produces at least 1 digit
This does not break any existing tests but does fix the problem demonstrated by the newly added test for this.
This PR is just for C. If the approach seems OK, I will create a separate PR for Java.
=> ICU-20844 reduce restriction on minInt=minFrac=0

icu4c/source/common/normalizer2impl.cpp, icu4c/source/common/ubidiwrt.cpp
The Visual Studio/MSVC optimizer has trouble with these functions when building for Windows ARM64 on versions below 16.4.
(Thanks to @marswe for help with this issue!)
=> ICU-20907 Disable optimization for MSVC on ARM64 on versions below 16.4

icu4c/source/i18n/smpdtfmt.cpp, icu4c/source/i18n/unicode/smpdtfmt.h, icu4c/source/test/intltest/dtfmttst.cpp, icu4j/main/classes/core/src/com/ibm/icu/text/ChineseDateFormat.java, icu4j/main/classes/core/src/com/ibm/icu/text/SimpleDateFormat.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/DateFormatTest.java
There is a fallback mechanism on fields `b` and `B` to field `a` when data is not provided for a locale. This fallback is done calling `subFormat` recursively. However, when such function finishes execution, caller still executes its remaining operations, causing duplication of fields `a` and `B`  to the same position. This PR is changing the behavior for this function to return as soon as the fallback calls returns. Since we want to keep results consistent when a data change on CLDR happen, the field included  on iterator is the one requested by the pattern.
@sffc
=> ICU-20741 Changing SimpleDateTimeFormat::subFormat to avoid duplicated field for same position

icu4c/source/common/unicode/umachine.h
When C code includes the ICU headers, the `UChar` type is defined to be
`uint16_t`. But when C++ code includes the headers, `UChar` is `char16_t`
even when `U_SHOW_CPLUSPLUS_API` has been set to 0. Apart from arguably
being an inconsistency in the API, this means that C++98 or C++03 code
can't use the C API even though C99 code can.
So, change unicode/umachine.h to check not just whether `__cplusplus` is
defined but the value of `U_CPLUSPLUS_VERSION` when deciding how to
typedef UChar.
=> ICU-20904 Don't use char16_t with C++98/03

icu4c/source/i18n/decimfmt.cpp, icu4c/source/i18n/number_decimalquantity.cpp
It's not available with some libc implementations. Specifically,
BIONIC and uClibc-ng. uprv_ variants are available.
Signed-off-by: Rosen Penev <rosenp@gmail.com>
=> ICU-20877 i18n: Don't use C++11 math

icu4c/source/common/rbbi.cpp, icu4c/source/common/rbbiscan.cpp, icu4c/source/common/rbbiscan.h, icu4c/source/common/rbbitblb.cpp, icu4c/source/common/rbbitblb.h, icu4c/source/test/intltest/rbbitst.cpp, icu4c/source/test/intltest/rbbitst.h, icu4c/source/test/testdata/rbbitst.txt, icu4j/main/classes/core/src/com/ibm/icu/text/RBBIRuleScanner.java, icu4j/main/classes/core/src/com/ibm/icu/text/RBBITableBuilder.java, icu4j/main/classes/core/src/com/ibm/icu/text/RuleBasedBreakIterator.java, icu4j/main/shared/data/icudata.jar, icu4j/main/tests/core/src/com/ibm/icu/dev/test/rbbi/rbbitst.txt
- Merge the look-ahead results slots used when multiple rules share a common accepting state.
- Sequentially number the look-ahead result slot. Will eventually allow replacing the runtime map with an array.
- Inhibit chaining out of look-ahead rules. This could never actually happen; when a hard break
rule matches, the engine is stopped immediately, but the state table was being constructed
as if it could  happen. Reduces table size for line break rules.
- Remove incorrect handling of fAccepting and fLookAhead fields of a state table row
when removing duplicate states. Look-ahead slot number was being mis-interpreted as a state number.
=> ICU-20303 Break Iterator, improve handling of look-ahead rules.

icu4j/main/classes/core/src/com/ibm/icu/util/Calendar.java
There did not appear to be any occurrences of the term "weekend data" in ICU4C that weren't being suitably explained.
=> ICU-20354 Change 'weekend data' to 'week data'

.gitattributes
Note that changes to `.gitattributes` files won't take effect on GitHub until something else has been modified in a follow-up commit. It's an acknowledged caching issue.
=> ICU-20892 Highlight `.cpyskip.txt` on GitHub.com

icu4c/source/common/locdistance.cpp, icu4c/source/common/locdistance.h, icu4c/source/common/loclikelysubtags.cpp, icu4c/source/common/loclikelysubtags.h, icu4c/source/test/testdata/localeMatcherTest.txt, icu4j/main/classes/core/src/com/ibm/icu/impl/locale/LocaleDistance.java, icu4j/main/classes/core/src/com/ibm/icu/impl/locale/XLikelySubtags.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/data/localeMatcherTest.txt
https://unicode-org.atlassian.net/browse/ICU-20917
Compares two supported locales that match equally well but not perfectly. Favors the one which has more-default subtags.
I had thought about another approach: Doing a more complicated addLikelySubtags lookup, keeping information in the LSR about how close it is to the default, and scoring on that. However, that seemed tricky, would slow down all addLikelySubtags processing -- and we only want to distinguish between two supported locales, so we need not tweak the match distance between desired and supported.
=> ICU-20917 LocaleMatcher: prefer a more-default locale

icu4c/source/test/intltest/tztest.cpp, icu4j/main/tests/core/src/com/ibm/icu/dev/test/timezone/TimeZoneTest.java
Somehow these tests are now fail on trunks.
Per https://mm.icann.org/pipermail/tz-announce/2019-July/000056.html
Brazil has canceled DST and will stay on standard time indefinitely.
=> ICU-20934 Fix TZ test error

icu4j/main/classes/core/src/com/ibm/icu/impl/number/DecimalFormatProperties.java
ParseMode.COMPATIBILITY was eventually renamed to
ParseMode.JAVA_COMPATIBILITY but it's javadoc was not updated.
=> ICU-20928 Fix incorrect javadoc reference in DecimalFormatProperties

icu4c/source/i18n/dtptngen.cpp, icu4c/source/test/intltest/dtifmtts.cpp, icu4c/source/test/intltest/dtifmtts.h, icu4j/main/classes/core/src/com/ibm/icu/text/DateTimePatternGenerator.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/DateIntervalFormatTest.java
DateTimePatternGenerator needs to consider the hour-cycle preferred by
Locale. This means that we need to to override the hour-cycle when a
locale contains "hc" keyword. This patch is adding such functionality.
In addition, "DateTimePatternGenerator::adjustFieldTypes" should adjust
hour field to properly follow tr35
spec(https://www.unicode.org/reports/tr35/tr35-dates.html#dfst-hour).
@sffc
=> ICU-20442 Adding support for hour-cycle on DateTimePatternGenerator

icu4c/source/common/uarrsort.cpp, icu4c/source/common/utext.cpp, icu4c/source/tools/toolutil/toolutil.cpp
The definition of `max_align_t` is not guaranteed to be available unless
the appropriate header is included. Since use of `<stddef.h>` from C++ is
deprecated, that's `<cstddef>`, and `max_align_t` is thus defined under the
std namespace rather than in the global namespace.
=> ICU-20875 Include <cstddef> for max_align_t

icu4c/source/test/intltest/tztest.cpp, icu4j/build.xml, icu4j/main/tests/core/src/com/ibm/icu/dev/test/timezone/TimeZoneTest.java
Note: This PR is into the `maint/maint-66` branch.
This PR contains two commits:
- Fix the failing ICU4J build by bumping Apache Ivy to 2.5.0
- Cherry-picking #959 (Brazil TZ change) into ICU 66.
For the first commit:
It looks like Apache Ivy is trying to use HTTP to download `junit` -- but the Maven repo seems to only supports HTTPS. This change bumps the old version of Apache Ivy from 2.1.0-rc2 (released on Jul 23, 2009) to 2.5.0 (the most recent stable version, released Oct 20, 2019).
I'll create another PR to cherry-pick this single commit into `master` once this is merged.
For the second commit:
This is cherry-picked from 11ad8d69fb4c70e529c592d37df5a30c925b6af4 (PR #959).
=> ICU-20942 ICU-20934 Update Apache Ivy to 2.5.0, cherry-pick Brazil DST change into ICU 66

icu4j/main/classes/core/src/com/ibm/icu/impl/number/DecimalQuantity.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/DecimalQuantity_AbstractBCD.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/DecimalQuantity_DualStorageBCD.java, icu4j/main/classes/core/src/com/ibm/icu/number/CompactNotation.java, icu4j/main/classes/core/src/com/ibm/icu/number/ScientificNotation.java, icu4j/main/classes/core/src/com/ibm/icu/text/PluralRules.java, icu4j/main/tests/core/src/com/ibm/icu/dev/impl/number/DecimalQuantity_64BitBCD.java, icu4j/main/tests/core/src/com/ibm/icu/dev/impl/number/DecimalQuantity_ByteArrayBCD.java, icu4j/main/tests/core/src/com/ibm/icu/dev/impl/number/DecimalQuantity_SimpleStorage.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/PluralRulesTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/DecimalQuantityTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
Note: the test for selection of the correct plural rule is still failing, I'm stuck on figuring out why that is the case when the tests for the returned numerical value of the plural operands pass.
=> ICU-13836 Improve plural support for compact decimal format via suppressed exponent

icu4c/source/common/unistr.cpp, icu4c/source/test/intltest/ustrtest.cpp, icu4c/source/test/intltest/ustrtest.h
=> ICU-20958 Prevent SEGV_MAPERR in append

icu4c/source/i18n/rematch.cpp, icu4c/source/test/testdata/regextst.txt
In regular expressions, when testing for word boundaries with \b, the
boundaries were incorrect when in Unicode mode, meaning that an ICU word break
iterator is being used to find the boundaries, and the text being matched is
UTF-8 encoded.
The bug stemmed from a misunderstanding of how string indexes work with UText
and break iterators, leading to the inclusion of code to convert from UTF-8 to
UTF-16 indexing, when what was wanted was the original UTF-8 index everywhere.
Removing the indexing conversion fixes the problem.
=> ICU-20939 Fix problem w regexp \b boundaries & UTF-8 text

.gitattributes
This change informs GitHub to use the "JSONC" format for JSON files when syntax highlighting, in order to better handle comments in JSON files.
(Note: There should be no "real" impact here other than fixing the syntax highlighting.)
=> ICU-20953 Tell GitHub to use JSONC to fix syntax highlighting for comments

icu4c/source/i18n/number_modifiers.cpp, icu4c/source/test/intltest/numbertest.h, icu4c/source/test/intltest/numbertest_api.cpp, icu4c/source/test/testdata/numberpermutationtest.txt, icu4j/main/classes/core/src/com/ibm/icu/impl/number/CurrencySpacingEnabledModifier.java, icu4j/main/tests/core/src/com/ibm/icu/dev/data/numberpermutationtest.txt, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
=> ICU-20954 Fix currency spacing in suffix.

icu4c/source/common/putil.cpp
Adds `ICU_TIMEZONE_FILES_DIR_PREFIX_ENV_VAR`, similar to
`ICU_DATA_DIR_PREFIX_ENV_VAR`, that specifies an environment variable
to retrieve and prepend to the ICU time zone data file path.
Note: `ICU_DATA_DIR_PREFIX_ENV_VAR` is not currently documented or tested.
=> ICU-20895 ICU_TIMEZONE_FILES_DIR_PREFIX_ENV_VAR

icu4c/source/i18n/regexcmp.cpp, icu4c/source/i18n/rematch.cpp, icu4c/source/i18n/unicode/regex.h, icu4c/source/test/testdata/regextst.txt
Change the implementation of grapheme cluster matching in regex to use an ICU
break iterator instead of a little one-off state machine.
The old implementation had fallen behind the Unicode UAX-29 specification for
graphem clusters, and could not be easily updated.
The implementation follows the same general pattern that is used for finding
word boundaries with an ICU break iterator. In reviewing that code, a few
improvements to the handling of ICU error codes were also made.
Also note that this change adds a new dependency on Break Iteration.  Regex
patterns that previously would work with ICU builds that were configured with
no break iteration will now fail. But only if they include \X for matching
grapheme cluster boundaries.
=> ICU-20876 Regex Grapheme Cluster matching with Break Iterators.

icu4c/source/common/ucnv.cpp, icu4c/source/tools/toolutil/pkg_genc.cpp
Fixing a few warnings found while running the ICU4C samples.
=> ICU-20975 BRS66rc Fix warnings found when building ICU4C samples.

icu4c/source/i18n/dtptngen.cpp, icu4c/source/i18n/unicode/dtptngen.h, icu4c/source/i18n/unicode/udatpg.h, icu4c/source/test/cintltst/udatpg_test.c, icu4c/source/test/intltest/dtptngts.cpp, icu4c/source/test/intltest/dtptngts.h
If you call the C++ API `getDefaultHourCycle` on an empty `DateTimePatternGenerator`
instance, or the C API `udatpg_getDefaultHourCycle`, then it hits `UPRV_UNREACHABLE` which calls `abort()`.
We should likely return an error code instead of aborting.
Add test cases for both the C++ and C APIs.
=> ICU-21000 Fix abort called by DateTimePatternGenerator getDefaultHourCycle

icu4c/source/common/brkiter.cpp, icu4c/source/common/dictbe.cpp, icu4c/source/common/rbbi.cpp, icu4c/source/common/rbbidata.h, icu4c/source/common/unicode/utrace.h, icu4c/source/test/intltest/rbbitst.cpp, icu4c/source/test/intltest/rbbitst.h
Extend utrace enum to trace BreakIterator instance and internal language break engine
=> ICU-20991 Trace BreakIterator/BreakEngine creation

.ci-builds/.azure-valgrind.yml
This adds a separate CI pipeline on Azure for running [valgrind](https://en.wikipedia.org/wiki/Valgrind) continuously on ICU4C in an automated fashion.
The base Ubuntu images don't have valgrind installed by default though, so we need to install valgrind first via `apt`.
For running valgrind, this set the option `--error-exitcode=1` so that *any* errors found by valgrind will fail the CI build.
This also sets the option `--leak-check=full` so that valgrind will report any leaked memory as well.
(Though this does slow down the execution time a bit).
**Note:** ICU4C currently does *not* run cleanly under valgrind, so this new automated CI run will fail under these issues are addressed. I've filed a separate ticket for this here [ICU-21001](https://unicode-org.atlassian.net/browse/ICU-21001). …
=> ICU-20626 Adding valgrind to the CI tests for ICU4C.

.ci-builds/.azure-pipelines.yml
=> ICU-20965 Remove VS2015 from CI builds, no longer supported by Azure DevOps

.ci-builds/.azure-valgrind.yml
It seems that having "pr:none" completely disables running on PRs, even
when explicitly triggered by a comment.
(See here for more info: https://github.com/MicrosoftDocs/vsts-docs/issues/4206#issuecomment-493451760).
=> ICU-20626 Remove "pr:none" from Valgrind CI config to enable comment triggers

icu4j/main/classes/core/src/com/ibm/icu/number/NumberFormatterImpl.java, icu4j/main/classes/core/src/com/ibm/icu/number/NumberPropertyMapper.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/NumberFormatTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
This is the ICU4J fix that corresponds to the ICU4C fix in https://github.com/unicode-org/icu/pull/917
=> ICU-20844 ICU4J, reduce restriction on minInt=minFrac=0

icu4c/source/test/intltest/calregts.cpp, icu4c/source/test/intltest/caltest.cpp, icu4j/main/tests/core/src/com/ibm/icu/dev/test/calendar/CalendarRegressionTest.java
Fix typo in ICU tests, calender → calendar (one instance in actual code, two in comments)
=> ICU-20879 fix typo in tests, calender → calendar

.ci-builds/.azure-pipelines.yml
This is into the `maint/maint-66` branch, so that the CI builds are unblocked for ICU 66.
Cherry-picked from PR #1028.
=> ICU-20965 Remove VS2015 from CI builds, no longer supported by Azure Pipelines [ICU 66]

icu4c/source/common/rbbirb.cpp
To print it,
$ CXXFLAGS="-DRBBI_DEBUG" ./runConfigureICU --enable-debug --disable-release  Linux/gcc --disable-layoutex
$ make clean
$ U_RBBIDEBUG="size" make
=> ICU-21011 Debug print detail size of brk files.

icu4c/source/common/localematcher.cpp
https://unicode-org.atlassian.net/browse/ICU-21009
FYI I introduced this problem just recently in PR #1018.
=> ICU-21009 LocaleMatcher() order[] always set all elements

icu4c/source/common/ucasemap.cpp, icu4c/source/common/unicode/bytestream.h, icu4c/source/common/unicode/stringpiece.h, icu4c/source/test/intltest/collationtest.cpp, icu4c/source/test/intltest/compactdecimalformattest.cpp, icu4c/source/test/intltest/regextst.cpp, icu4c/source/test/intltest/strcase.cpp, icu4c/source/test/intltest/strtest.cpp, icu4c/source/test/intltest/strtest.h, icu4c/source/test/intltest/tstnorm.cpp, icu4c/source/test/intltest/uts46test.cpp
https://unicode-org.atlassian.net/browse/ICU-20984
This is a follow-up to ICU-20972 PR #979 which fixed `char8_t *` build failures just using reinterpret_cast so that we could include it in ICU 66.
Here are some new API overloads to make working with C++20 u8"string literals" easier while keeping ICU compatible with C++11.
This includes one not originally proposed overload for `StringPiece(std::nullptr_t p)` to type-disambiguate uses of `StringPiece(nullptr)` especially when the constructor call is implicit. I decided not to add such overloads for every pointer variation here; see the PR comment thread.
Note that `StringPiece(NULL)` call sites may break, depending on the compiler. In portable code this is unavoidable, as in the adoption of char16_t (see …
=> ICU-20984 StringPiece & ByteSink overloads for char8_t*

icu4c/source/config/dist-data.sh, icu4c/source/config/dist.mk
[ICU-20600]
make dist will now produce:
- icu4c-67.1-data-bin-b.zip
- icu4c-67.1-data-bin-l.zip
I made the builder a separate shell script, so that I can run it on backlevel ICUs.
[ICU-20600]: https://unicode-org.atlassian.net/browse/ICU-20600
=> ICU-20600 build icu-data-bin files

icu4c/source/i18n/collationtailoring.h, icu4c/source/i18n/numparse_affixes.h, icu4c/source/test/intltest/numberformattesttuple.cpp
[ICU-20797]
Two issues here:
- fix 2 build issue in i18n when compiling with clang++ -fsanitize=undefined
the following two symbols were not exported (and they should be):
typeinfo for icu::CollationCacheEntry
typeinfo for icu::numparse::impl::CodePointMatcher
- remove undefined behavior warning in NumberFormatTestTuple.. minor, but very annoying
when repeated many times during every test run. Tends to mask real errors.
> numberformattesttuple.cpp:319:5: runtime error: member access within null pointer of type 'NumberFormatTestTuple'
[ICU-20797]: https://unicode-org.atlassian.net/browse/ICU-20797
=> ICU-20797 fix UBS compilation error and UBS in test code

.travis.yml
[ICU-20605]
- run 'make dist' after the linux clang build
~- upgrade ubuntu xenial (16 LTS) to bionic (18 LTS) [(schedule)](https://wiki.ubuntu.com/Releases)~
HT: https://github.com/unicode-org/icu/pull/1048#discussion_r392544485
[ICU-20605]: https://unicode-org.atlassian.net/browse/ICU-20605
=> ICU-20605 travis: make dist.

icu4c/source/tools/toolutil/pkg_genc.cpp
Intel Control-flow Enforcement Technology (CET):
https://software.intel.com/en-us/articles/intel-sdm
contains shadow stack (SHSTK) and indirect branch tracking (IBT).  When
CET is enabled, ELF object files must be marked with .note.gnu.property
section.  GCC provides <cet.h> which can be included in assembly codes
to generate CET maker when compiling with -fcf-protection.
This fixes:
https://unicode-org.atlassian.net/browse/ICU-21019
=> ICU-21019 x86: Add .note.gnu.property section for Intel CET

icu4j/main/classes/core/src/com/ibm/icu/text/RBBITableBuilder.java
Fix the issue identified by Coverity.
The problem was in code handling the mapping from the table build time
representation of a set of status values for an RBBI rule to the corresponding
status data as saved in a binary RBBI rule file.
The problem was benign, the rbbi data built by the incorrect code would
would still operate correctly, although it might not byte-for-byte match
that built by ICU4C. (The problem was in Java only.)
=> ICU-21024 RBBI Table Builder / Coverity CID 1460598 "Dodgy Code" issue

.travis.yml, icu4c/source/common/ucnv2022.cpp, icu4c/source/common/uposixdefs.h, icu4c/source/i18n/ucol_sit.cpp
[ICU-20976]
ICU-20976 GCC8 fixes phase 1
Some initial fixes for GCC8
- setup a gcc8 buildbot with -Wextra
- rewrite ucol_sit to use icu::CharString
- workaround for gcc7+ on mac
see https://github.com/arbor-sim/arbor/issues/562#issuecomment-409970434
- fix ucnv_2022 strcpy site
[ICU-20976]: https://unicode-org.atlassian.net/browse/ICU-20976
=> ICU-20976 GCC8 fixes

icu4c/source/common/cmemory.h, icu4c/source/i18n/Makefile.in, icu4c/source/i18n/currunit.cpp, icu4c/source/i18n/i18n.vcxproj, icu4c/source/i18n/i18n.vcxproj.filters, icu4c/source/i18n/i18n_uwp.vcxproj, icu4c/source/i18n/measunit.cpp, icu4c/source/i18n/measunit_extra.cpp, icu4c/source/i18n/measunit_impl.h, icu4c/source/i18n/nounit.cpp, icu4c/source/i18n/number_asformat.cpp, icu4c/source/i18n/number_fluent.cpp, icu4c/source/i18n/number_longnames.cpp, icu4c/source/i18n/number_skeletons.cpp, icu4c/source/i18n/ucln_in.h, icu4c/source/i18n/unicode/measunit.h, icu4c/source/i18n/unicode/numberformatter.h, icu4c/source/test/depstest/dependencies.txt, icu4c/source/test/intltest/measfmttest.cpp, icu4c/source/test/intltest/numbertest_api.cpp, icu4c/source/test/intltest/numfmtst.cpp
This PR includes machinery to support the new [CLDR 37 unit identifiers](https://docs.google.com/document/d/1BSJFap5SnDX3E4AbG6pdK5S0HFHYQzl1d7OVD3HxP1c/edit) in ICU4C.  It does this by adding a new factory function `MeasureUnit::forIdentifier()` as well as additional methods to MeasureUnit to access and modify units.
=> ICU-20920 Add support for draft CLDR 37 unit identifiers in ICU4C

tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/LdmlConverter.java
ICU-20693 The cldrVersion value is added as a bit of a hack in the supplementalData.txt file (because that data doesn't come from CLDR XML directly). However it should only go into the "main" misc/supplementalData.txt, not the curr/supplementalData.txt file.
This fix just sets the flag to add it to false for the curr/ version.
This can be seen via the diffs for the new tools:
diff -r -I '^[ /]\*' /icu-65-1/icu4c/source/data/curr/supplementalData.txt /tmp/icu65/curr/supplementalData.txt
...
5207a5244
>     cldrVersion{"36"}
=> ICU-20693 Fix erroneous addition of cldrVersion

icu4c/source/i18n/smpdtfmt.cpp, icu4c/source/test/intltest/dtfmrgts.cpp, icu4c/source/test/intltest/dtfmrgts.h
Notes to reviewer:
This PR fixes the SimpleDateFormat::operator= issue described in ICU-10858 with corresponding regression unit test. This does _not_ address SimpleDateFormat's equality operator nor the number bear formats overrides described in the ticket.
Please kindly advise on the following:
* since this only covers part of ICU-10858, what is the recommended tracking practice? Is it still appropriate to attach this PR to ICU-10858, or a new ticket is required?
* unit test is added to "icu4c/source/test/intltest/dtfmrgts.cpp". Is this the recommended location to validate this behavior?
Thanks,
Campion
=> ICU-10858 Fix missing fTimeZoneFormat assignment in SimpleDateFormat::operator=

icu4c/source/common/cstring.h, icu4c/source/common/ustr_imp.h, icu4c/source/common/ustring.cpp, icu4c/source/i18n/currunit.cpp, icu4c/source/test/intltest/numfmtst.cpp, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/CurrencyTest.java
=> ICU-20912 Make C/J Currency consistent on lowercase/uppercase currency equality

.appveyor.yml
Cygwin 3.x builds of ICU previously were all failing due to issues with Cygwin, but it looks like Cygwin has since made changes to fix things and ICU now builds on 3.x. (We were continuing to use v2.x for the time being as a work-around).
This updates to version 3 and also splits the build up somewhat to speed things up.
(Note: A full parallel build fails with Cygwin though).
=> ICU-20435 Update Cygwin to 3.x to fix CI builds.

icu4c/source/test/intltest/dtfmtrtts.cpp
In exhaustive mode, TestDateFormatRoundTrip has a failure in which the successive parse/format cycles for ar_JO@calendar=islamic-civil in time-format-only mode fail to converge as rapidly as expected. For now just add a logKnownIssue that allows more cycles for convergence in this case.
=> ICU-21022 Use logKnownIssue to avoid TestDateFormatRoundTrip exhaustive fail

.appveyor.yml, icu4c/source/config/mh-cygwin, icu4c/source/config/mh-cygwin64
This is a follow-up to PR #1059.
Parallel builds on Cygwin 3.x were broken, this PR fixes them, and changes the AppVeyor CI config to use a parallel build (which saves for each run on PRs).
=> ICU-20435 Fix parallel builds with Cygwin to 3.x

icu4j/main/classes/core/src/com/ibm/icu/number/LocalizedNumberRangeFormatter.java
https://unicode-org.atlassian.net/browse/ICU-21020
=> ICU-21020 Fix a typo in the LocalizedNumberRangeFormatter's documentation

icu4c/source/tools/gensprep/store.c
=> ICU-21026 fix GCC warnings of signed-int left shift

icu4c/source/common/locid.cpp, icu4c/source/common/uloc.cpp, icu4c/source/common/ulocimp.h
https://unicode-org.atlassian.net/browse/ICU-20803
This eliminates the need for the fixed size scratch buffer inside of
locale_set_default_internal() and also eliminates the need for counting
bytes, something that ByteSink will now handle correctly when needed.
None of this should have any externally visible effect (apart from
removing the arbitrary size limit imposed by the fixed size scratch
buffer), it's all about cleaning up implementation internals.
=> ICU-20803 Pass ByteSink to _canonicalize()

.appveyor.yml, .ci-builds/.azure-exhaustive-tests.yml, .ci-builds/.azure-pipelines.yml, .ci-builds/.azure-valgrind.yml, .ci-builds/data-filter.json, .travis.yml, icu4c/source/common/putil.cpp, icu4c/source/common/putilimp.h, icu4c/source/common/unicode/unistr.h, icu4c/source/common/unistr.cpp, icu4c/source/test/cintltst/putiltst.c, icu4c/source/test/intltest/ustrtest.cpp, icu4c/source/test/intltest/ustrtest.h
[ICU-21032] Backport of [ICU-20958] aka #971 
Includes partial backports so that this can be merged:
- ICU-13634 Adding functions for integer overflow
- ICU-13634 Removing stray #include added in r41136.
- ICU-13707 Make UnicodeString safe when appended or inserted into itself. (#147)
Multiple commits to preserve history, so:
[ICU-21032]: https://unicode-org.atlassian.net/browse/ICU-21032
[ICU-20958]: https://unicode-org.atlassian.net/browse/ICU-20958
=> ICU-21032 Backport of ICU-20958 to 61.x

icu4c/readme.html
Removed stale reference to Unicode 13 and CLDR 36. Thanks Yoshito for catching this in the ICU4J readme update in PR #1086.
=> ICU-20979 Update ICU4C readme

icu4c/source/i18n/unicode/numberformatter.h
This was for the BRS task to
"Check non-stable API macros (U_HIDE_DRAFT_API and others)".
After the updates for API promotion, the only further thing that I found to change was to remove one no-longer-relevant comment related to U_HIDE macros.
=> ICU-20979 delete no-longer-relevant comment related to U_HIDE macros

icu4c/source/i18n/dtptngen.cpp, icu4c/source/i18n/dtptngen_impl.h, icu4c/source/i18n/unicode/basictz.h, icu4c/source/i18n/unicode/numsys.h, icu4c/source/test/cintltst/ccapitst.c, icu4c/source/test/intltest/convtest.cpp, icu4c/source/test/intltest/rbbitst.cpp, icu4c/source/tools/pkgdata/pkgdata.cpp
We accepted this ticket for ICU 67, and I didn't get the fix ready by the official code freeze, and then Markus said no, punt to 68.  But I would really rather see this in ICU 67.  There is one actual potential bug in library code, and there are also some changes in ICU public header files, which means that anyone using GCC and building against ICU may also encounter these errors, which is a standard we should avoid.
=> ICU-21015 Fixing gcc compiler warnings

icu4c/source/i18n/measunit_extra.cpp, icu4c/source/test/intltest/measfmttest.cpp
The core change in this PR is at line 425 in measunit_extra.cpp:
case COMPOUND_PART_TIMES:
if (fAfterPer) {
result.dimensionality = -1;
}
break;
The sawPlus/sawAnd change is a cosmetic addition/improvement.
=> ICU-21060 Fix the foo-per-a-b -> foo-b-per-a bug.

icu4c/source/common/unicode/umutablecptrie.h, icu4c/source/common/unicode/utext.h
Move U_DEFINE_LOCAL_OPEN_POINTER outside U_CDECL_BEGIN / _END
to fix conflicting declaration of C function
=> ICU-21065 Move U_DEFINE_LOCAL_OPEN_POINTER

icu4j/demos/src/com/ibm/icu/dev/demo/rbnf/RbnfDemo.java
ICU-5938 - Fix inaccurate output on RBNF demo sample
- Replace the attribute type of the attribute from double to
BigDecimal in order to format a number by using RBNF rules
without rounding error issues.
- A modification on < and > buttons (multiply/divide by 10)
to also fix rounding error issues.
- @Override annotations automatically added.
=> ICU-5938 Fix inaccurate output on RBNF demo sample

icu4j/demos/src/com/ibm/icu/dev/demo/rbnf/RbnfDemo.java
ICU-5938 Fix inaccurate output on RBNF demo sample
- In order to guarantee more accuracy on formatting, check
if number has fraction. If so, use double. Otherwise, use long.
=> ICU-5938 Fix inaccurate output on RBNF demo sample (accuracy)

icu4c/source/test/intltest/restsnew.cpp, icu4c/source/test/intltest/restsnew.h
I filed ICU-21080 to capture the outstanding work needed to restore the input values into the test case.
=> ICU-21055 Remove test inputs causing logKnownIssues test run to hang

icu4c/source/i18n/number_longnames.cpp, icu4c/source/test/cintltst/unumberformattertst.c, icu4c/source/test/intltest/numbertest.h, icu4c/source/test/intltest/numbertest_skeletons.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/number/LongNameHandler.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberSkeletonTest.java
Do not assume the "one" pattern always contains "{0}"
=> ICU-20949 Fix compound unit in "ar", "ne" locales

tools/cldr/cldr-to-icu/build-icu-data.xml, tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/AlternateLocaleData.java, tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/LdmlConverter.java, tools/cldr/cldr-to-icu/src/test/java/org/unicode/icu/tool/cldrtoicu/AlternateLocaleDataTest.java
The converter will now keep alt-paths when an alt-path mapping exists but for which the target path is missing in a locale. This is consistent with the old behaviour and doesn't tie the <altPath> mapping with any implied semantics of CLDR data (which is not true of the alternate PR https://github.com/unicode-org/icu/pull/1129). The downside is that this PR will not give any warnings about the mapping being ignored.
One minor additional fix relating to directory creation (which prevented easy debugging).
=> ICU-21089 Ignoring incomplete alt path mappings.

icu4c/source/i18n/nfrule.cpp, icu4c/source/i18n/plurfmt.cpp, icu4c/source/test/intltest/itrbnf.cpp, icu4j/main/classes/core/src/com/ibm/icu/text/NFRule.java, icu4j/main/classes/core/src/com/ibm/icu/text/PluralFormat.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/RbnfTest.java
ICU-21071 Fix lenient parse rules
- Check non-lenient rules before call lenint parsing
- Remove logKnownIssue 9503 from test code
- Adjust TestAllLocales test on ICU4C
- Add lenient checks on ICU4J
=> ICU-21071 Fix lenient parse rules

icu4c/source/i18n/udat.cpp, icu4c/source/i18n/unicode/udat.h, icu4c/source/test/cintltst/cdattst.c
Fix udat_toCalendarDateField to handle all defined UDateFormatField values, and to not read past array bounds for unknown inputs
=> ICU-21099 udat_toCalendarDateField, handle all UDateFormatFields and out of range

icu4c/source/test/intltest/rbbitst.cpp
Update failing rbbi tests to have a logKnownIssue that points to an open ticket; remove one logKnownIssue that does not produce a test failure.
=> ICU-21096 adjust logKnownIssues for ICU rbbitst

icu4c/source/data/makedata.mak
The python data build script is getting invoked due to the dependency on `$(COREDATA_TS)`, which isn't needed for the testdata. This causes the build to completely fail for Windows when using the pre-built data file in the tgz (tarball) file.
=> ICU-21102 Fix broken builds on Windows when using a pre-built data file.

.ci-builds/.azure-pipelines.yml, .travis.yml
Note: The Ubuntu 18.04 image doesn't have HarfBuzz, so we need to disable building the layout engine.
(Related PR: #1132).
Also updating/fixing the Ubuntu image name to use the preferred VM Image name.
=> ICU-21104 Add new build bot: Ubuntu 18.04 with C++14

.ci-builds/.azure-pipelines.yml
Enable running the ICU4C tests for Mac OSX on the Azure build bot.
=> ICU-21121 Enable tests for MacOSX build bot.

icu4c/source/test/intltest/intltest.cpp, icu4c/source/test/intltest/intltest.h, icu4c/source/tools/ctestfw/ctest.c, icu4c/source/tools/ctestfw/unicode/ctest.h, icu4c/source/tools/toolutil/udbgutil.cpp, icu4c/source/tools/toolutil/udbgutil.h
ICU-21098
- Still allows "1234" or "cldrbug:1234" format ticket IDs
- However, docs recommend "ICU-1234" or "CLDR-1234" format
in the future.
- Other ticket IDs could be used, but won't be linkified.
New format:
```
--------------------------------------
KNOWN ISSUES
[CLDR-1911] https://unicode-org.atlassian.net/browse/CLDR-1911
/TransliteratorRoundTripTest/TestDevanagariLatin/TestDevanagariLatin
/TransliteratorRoundTripTest/TestGreek/TestGreek
/TransliteratorRoundTripTest/TestGreekUNGEGN/TestGreekUNGEGN
/TransliteratorRoundTripTest/TestHebrew/TestHebrew
/TransliteratorRoundTripTest/TestInterIndic/TestInterIndic
/TransliteratorRoundTripTest/Testel/Testel
[CLDR-6745] https://unicode-org.atlassian.net/browse/CLDR-6745
/UCAConformanceTest/TestRulesNonIgnorable/TestRulesNonIgnorable …
```
=> ICU-21098 fix ticket URLs for logKnownIssue tickets.

icu4c/source/common/unistr.cpp, icu4c/source/test/intltest/ustrtest.cpp, icu4c/source/test/intltest/ustrtest.h
ICU-21032 v65.x backport of ICU-20958
See #971
(cherry picked from commit b7d08bc04a4296982fcef8b6b8a354a9e4e7afca)
=> ICU-21032 v65.x backport ICU-20958 Prevent SEGV_MAPERR in append

icu4c/source/common/unistr.cpp, icu4c/source/test/intltest/ustrtest.cpp, icu4c/source/test/intltest/ustrtest.h
ICU-21032 Backport to 64.x: ICU-20958 Prevent SEGV_MAPERR in append
See #971
(cherry picked from commit b7d08bc04a4296982fcef8b6b8a354a9e4e7afca)
=> ICU-21032 Backport to 64 of ICU-20958

icu4c/source/common/unistr.cpp, icu4c/source/test/intltest/ustrtest.cpp, icu4c/source/test/intltest/ustrtest.h
ICU-21032 backport of ICU-20958 to 66.x
See #971
(cherry picked from commit b7d08bc04a4296982fcef8b6b8a354a9e4e7afca)
=> ICU-21032 Backport to 66.x:  ICU-20958 Prevent SEGV_MAPERR in append

icu4c/source/common/loclikely.cpp, icu4c/source/test/cintltst/cloctst.c, icu4c/source/test/intltest/loctest.cpp, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/ULocaleTest.java
1. Add test cases in C++ from Java.
2. Add test cases in C++ and Java from examples of UTS35 and
https://github.com/tc39/test262/blob/master/test/intl402/Locale/prototype/minimize/removing-likely-subtags-first-adds-likely-subtags.js
3. Fix C++ code:
a) Make _ulocimp_addLikelySubtags propagate matching error so
minimizeSubtags can just return the no matching case unchanged.
b) rename the sink variable to outSink and local sink variables to
avoid confusion and mistake
c) Correct the implementation of minimizeSubtags by using the lang,
region, script of the "max" instead of the localeID in the algorithm.
=> ICU-13786 Fix addLikelySubtags/minimizeSubtags

icu4c/source/data/makedata.mak, icu4c/source/data/makedata.vcxproj, icu4c/source/python/icutools/databuilder/renderers/common_exec.py
If the ICU data build fails during the Python data build script on Windows, then you don't get very helpful error messages/logs. This isn't as much of an issue on non-Windows platforms, as the Python data build script is run as part of the configure script, and not during the build (make).
The change in this PR does two things:
- It logs the command line for any failed command executed during the data build (for any platform).
- It enables `--verbose` when building under DEBUG mode on Windows.
This should help to track down build failure issues that occur during the data build, like the one in PR #1141. 🙂
=> ICU-21119 Log failed commands & enable verbose output from ICU data build on Windows/DEBUG

tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/PseudoLocales.java, tools/cldr/cldr-to-icu/src/test/java/org/unicode/icu/tool/cldrtoicu/AlternateLocaleDataTest.java, tools/cldr/cldr-to-icu/src/test/java/org/unicode/icu/tool/cldrtoicu/PseudoLocalesTest.java, tools/cldr/cldr-to-icu/src/test/java/org/unicode/icu/tool/cldrtoicu/mapper/LocaleMapperTest.java, tools/cldr/cldr-to-icu/src/test/java/org/unicode/icu/tool/cldrtoicu/testing/FakeDataSupplier.java
Hopefully a fix to the issue of pseudo-locales generating both values and aliases to values (which is not expected by ICU resource bundle generation, even though they are distinct CLDR paths).
=> ICU-21135 Fix pseudo locales to filter only non-root paths and avoid aliases.

tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/IcuTextWriter.java, tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/ant/CleanOutputDirectoryTask.java, tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/mapper/TransformsMapper.java
I found one more case where UTF-8 had to be specified and I made it explicit in all the remaining file accesses I could find. While I'm glad UTF-8 is default in Files.newBufferedReader(), the fact that Java has for so many years assumed that "no charset" implies "system default" means the people reading the code are potentially going to be confused if it's omitted, so I just added it consistently everywhere.
=> ICU-21140 Make UTF-8 explicit for all file access.

icu4c/source/common/locid.cpp
The result of pointer end + 1 will not be used if end is nullptr so it doesn't really matter that the result of this operation is undefined, but it's therefore also unnecessary to perform the operation at all.
Changing this removes this unnecessary operation and by doing so gives the undefined behaviour sanitizer one thing less to worry about.
=> ICU-21143 Applying non-zero offset to null pointer is undefined behaviour

icu4c/source/data/makedata.mak
This cherry-picks the fix for ICU-21102 from the `master` branch to the `maint/maint-67` branch.
This is cherry-picked from:
ICU-21102 Fix broken builds on Windows when using a pre-built data file (from the tgz).
PR #1139
(cherry picked from commit 82a5959b863ac647fce3bcc5804ed906fb3b4bc0)
=> ICU-21150 Backport fix for broken Windows build with prebuilt data to 67

icu4c/source/i18n/number_grouping.cpp, icu4c/source/i18n/unicode/decimfmt.h, icu4c/source/i18n/unicode/unum.h, icu4c/source/test/intltest/numfmtst.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/number/Grouper.java, icu4j/main/classes/core/src/com/ibm/icu/text/DecimalFormat.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/NumberFormatTest.java
Enhance DecimalFormat::setMinimumGroupingDigits to accept
UNUM_MINIMUM_GROUPING_DIGITS_AUTO and
UNUM_MINIMUM_GROUPING_DIGITS_MIN2 to support locale default
for minimum grouping digits
=> ICU-21109 minimum grouping digits in DecimalFormat

.cpyskip.txt, docs/ide4c/vscode/README.md, docs/ide4c/vscode/c_cpp_properties.json, docs/ide4c/vscode/launch.json, docs/ide4c/vscode/tasks.json
- Adds c_cpp_properties.json, primarily for the includePath settings.
- make's "-l" parameter is system load average, not CPU percentage.
A load average of 90 makes my laptop unusable, changing to -l20.
- Load average takes a while to respond, specify -j24 to always limit
parallel jobs to a maximum of 24.
- Set intltest's Current Working Directory correctly to enable finding
resources.
- Make running all tests the unit-testing default.
- Document the adjustments that can be made in the README.
- Skip these json files when checking for copyright notices. Pure json
does not permit comments, so c_cpp_properties.json cannot have
comments.
=> ICU-21137 Adjust VSCode IDE settings and README.

icu4c/source/common/unicode/bytestriebuilder.h, icu4c/source/common/unicode/ucharstriebuilder.h, icu4c/source/i18n/measunit_extra.cpp, icu4c/source/i18n/measunit_impl.h, icu4c/source/test/depstest/dependencies.txt
Also swap a UCharsTrie for a BytesTrie, providing us with a set of char* values we can also return through getIdentifier().
=> ICU-21169 Add SimpleUnitImpl::getSimpleUnitID() method

icu4c/source/tools/toolutil/unewdata.cpp
[ICU-20545]
If `udata_create` won't find `U_FILE_SEP_CHAR` at the end of a `dir` variable,
then it appends it. The problem starts if the `dir` variable uses
`U_FILE_ALT_SEP_CHAR` which is not equal to `U_FILE_SEP_CHAR`. Then the
resulting path could look like this
`../data\mappings/cns-11643-1992.ucm`
instead of this
`../data/mappings/cns-11643-1992.ucm`
This patch uses `U_FILE_SEP_CHAR` unless it detects that the `dir` variable
doesn't use it, and uses `U_FILE_ALT_SEP_CHAR` instead.
[ICU-20545]: https://unicode-org.atlassian.net/browse/ICU-20545
=> ICU-20545 Detect file separator char from dir

tools/cldr/cldr-to-icu/build-icu-data.xml, tools/cldr/lib/README.txt, tools/cldr/lib/install-cldr-jars.sh, tools/cldr/lib/pom.xml
Hugo recently had an issue involving stale cache entries and other teething troubles. This PR should fix them. It:
* Fixes an issue whereby purging of cached libraries might not work.
* Makes the ICU tool fail if the Maven build step fails.
* Updates docs to reflect new script location and talk about troubleshooting.
=> ICU-21142 Improving Maven handling of CLDR API Jar file for new tools.

icu4c/source/i18n/plurrule.cpp
Fix a clang compiler warning and a potential undefined behavior arising
from casting an out-of-range double to an int. See the Jira ticket for a
more detailed description of the problem.
This PR is to fix the immediate problem. Longer term, the function
may be replaced entirely - see issue ICU-21147.
=> ICU-20869 Fix compiler warning in FixedDecimal::getFractionalDigits().

tools/cldr/lib/README.txt, tools/cldr/lib/install-cldr-jars.sh
A few tweaks to the install jar script to make it less dependent on Unix/Linux tools.
I think that (perhaps with the exception of 'which') everything is now a command that exists in the Bash man-page.
=> ICU-21142 Hopefully fixing the install script (bash only)

icu4c/source/common/localematcher.cpp, icu4c/source/common/locdistance.h, icu4c/source/common/unicode/localematcher.h, icu4c/source/test/intltest/localematchertest.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/locale/LocaleDistance.java, icu4j/main/classes/core/src/com/ibm/icu/util/LocaleMatcher.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/LocaleMatcherTest.java
https://unicode-org.atlassian.net/browse/ICU-21144
- LocaleMatcher.Builder.setMaxDistance(desired, supported)
- non-static LocaleMatcher.isMatch(desired, supported)
=> ICU-21144 LocaleMatcher setMaxDistance(), isMatch()

icu4c/source/common/charstr.cpp, icu4c/source/common/charstr.h
`CharString`, when asked, appends `U_FILE_SEP_CHAR` at the end of the string
it holds, if it won't find `U_FILE_SEP_CHAR` or `U_FILE_ALT_SEP_CHAR` there.
The problem starts if the `dir` variable uses
`U_FILE_ALT_SEP_CHAR` which is not equal to `U_FILE_SEP_CHAR`. Then the
resulting path could look like this
`../data\`
instead of this
`../data/`
This patch uses `U_FILE_SEP_CHAR` unless it detects that the `dir` variable
doesn't use it, and uses `U_FILE_ALT_SEP_CHAR` instead.
=> ICU-20545 Ensure that path ends with detected file separator

README.md
This PR changes/updates the CI build status badges in the top-level README file to point to the new Azure DevOps Pipelines URL.
=> ICU-21177 Update README.md badges to point to new Azure Pipelines URL

icu4c/source/test/intltest/numfmtst.cpp, icu4c/source/test/intltest/numfmtst.h, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/NumberFormatTest.java
Added tests for strict and lenient parsing of ¤ (U+00A4) patterns described in http://unicode.org/reports/tr35/tr35-numbers.html#Special_Pattern_Characters
=> ICU-13733 Added test for mismatching currency format for strict-mode parsing

icu4c/source/common/putil.cpp
Bionic libc looks "`persist.sys.timezone`" system property in https://android.googlesource.com/platform/bionic/+/master/libc/tzcode/bionic.cpp#43 instead of zonefile. So ICU should read this property to detect current time zone on Android.
This issue is from https://bugzilla.mozilla.org/show_bug.cgi?id=1487594. Gecko/SpiderMonkey's ECMA-402 implementation uses ICU.
=> ICU-11992 uprv_tzname doesn't return valid time zone on Android

icu4c/source/i18n/measunit_extra.cpp, icu4c/source/test/intltest/measfmttest.cpp
This is a cherry-pick of the upstream-impacting commit from https://github.com/icu-units/icu/pull/18
Specification:
https://www.unicode.org/reports/tr35/tr35-general.html#Unit_Identifiers
=> ICU-21192 MeasureUnit Identifier spec compliance: s/p/pow/

icu4c/source/io/uscanf_p.cpp, icu4c/source/test/iotest/iotest.cpp
I have made changes to `u_scanf_integer_handler()` in `uscanf_p.cpp`, to make sure that parsing an integer will not (try to) parse a decimal point. The usecase where I discovered the bug: 
`u_sscanf_u("[1.2.3]", "[%d.%d.%d]", &first, &second, &third);`
I am a longtime icu user, but not a very accomplished git user. I would be happy to get your feedback on procedural or programming mistakes I made. I would **really** like to have this issue fixed.
Full disclosure: The ticket was raised by a colleague and I.
=> ICU-13339 Do not parse decimal point for integers

icu4c/source/common/locdispnames.cpp, icu4c/source/test/cintltst/cloctst.c, icu4c/source/test/cintltst/cloctst.h
When the function is called during preflight,
return the max of the two possible results.
=> ICU-21160 Fix the length return by preflight

icu4c/source/common/ustring.cpp, icu4c/source/test/cintltst/custrtst.c
Downstream bug https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=15505
Fix Fuzzer-detected Use-of-uninitialized-value in isMatchAtCPBoundary
To test to show the bug in the new test case, configure and build with
CFLAGS="-fsanitize=memory" CXXFLAGS="-fsanitize=memory" ./runConfigureICU \
--enable-debug --disable-release  Linux  --disable-layoutex
Test with
cintltst /tsutil/custrtst
=> ICU-20684 Fix Use-of-uninitialized-value in isMatchAtCPBoundary

icu4c/source/common/unicode/udisplaycontext.h, icu4c/source/test/cintltst/cloctst.c
Add document to mention U_ILLEGAL_ARGUMENT_ERROR would be set to error
code when there are no data for UDISPCTX_NO_SUBSTITUTE.
=> ICU-21158 Fix doc of UDISPCTX_NO_SUBSTITUTE

icu4c/source/i18n/measure.cpp, icu4c/source/i18n/number_formatimpl.cpp
Measure: initialize unit to nullptr, and don't dereference it if it is
nullptr.
NumberFormatterImpl::writeAffixes: U_ASSERT not-null, instead of
segfaulting for coding mistakes.
=> ICU-21174 Increase safety of Measure and writeAffixes.

icu4c/source/i18n/measunit_extra.cpp, icu4c/source/i18n/measunit_impl.h, icu4c/source/test/depstest/dependencies.txt
In a discussion with Mark, I think we have consensus that it's fine to pull this from convertUnits for now. It's the cleanest list of simple unit identifiers we have.
Follow-up work should help us trust the convertUnits list to always be complete: I propose I add a test that simply ensures we can parse all of the units that show up in the supplementalData/idValidity/unit/regular" list.
(This was previously reviewed as: https://github.com/icu-units/icu/pull/41)
=> ICU-21059 Load simple unit IDs from convertUnits.

icu4c/source/data/Makefile.in
When building in parallel it's possible that the rc command is invoked
before other rules get around to creating the output directory.
=> ICU-21216 Windows: Ensure directory exists before running rc

icu4c/source/common/ustring.cpp, icu4c/source/test/cintltst/custrtst.c
When the u_unescape is called with repeated escaped surrogate lead,
it calls u_unescapeAt and recursively calls u_unescapeAt and
cause stack overflow. Limit the length to the end of the escape of
surrogate tail to avoid repeat recursion calls.
The problem case is a long list of surrogate lead in escaped form follow by each other, which would cause recursion for every one of them.
For example:
\ud800\ud800\ud800 ...... \ud800 (repeat several thousands)
To prevent that, we only recursively call the u_unescapeAt function with max to length 5 (the u and the 4 hex) from the current position after we found the surrogate lead and a '\'  . In this way, we guarantee the stack depth is only 2 .
=> ICU-20725 Fix stack overflow of u_unescapeAt

icu4c/source/common/punycode.cpp, icu4c/source/test/intltest/uts46test.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/Punycode.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/normalizer/UTS46Test.java
Since I had to add another range check, I changed the code from using a table for Latin-1 code points to have an all-range-checks function more like [decode_digits in the RFC sample code](https://tools.ietf.org/html/rfc3492#page-25), but with a hardcoded binary search.
https://unicode-org.atlassian.net/browse/ICU-21212
=> ICU-21212 full range check for Punycode digits

icu4c/source/common/uts46.cpp, icu4c/source/test/intltest/uts46test.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/UTS46.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/normalizer/UTS46Test.java
Check for "xn--" and "xn--ASCII-" and fail equivalently to IDNA2008 ToUnicode which verifies that its input round-trips via ToASCII back to the same string. These strings turn into "" and "ASCII", different from the input.
UTS \#46 otherwise validates equivalently as well. The code here uses a much simpler test for these edge cases.
https://unicode-org.atlassian.net/browse/ICU-21030
=> ICU-21030 validate ACE label edge cases

icu4c/source/common/unicode/uloc.h, icu4c/source/test/cintltst/cloctst.c, icu4c/source/test/cintltst/cloctst.h
Document the fact
uloc_getDisplay(Language|Script|Country|Variant|Keyword|KeywordValue)
would fallback with the code, case canonicalied in same cases, and
set the status to U_USING_DEFAULT_WARNING.
No change to the implementation behavior. Only complete the missing
comments and tweak line wrap, remove double spaces and add test to
validate this pre-existing behavior that I added the documents now.
=> ICU-21159 Document U_USING_DEFAULT_WARNING in .h

docs/userguide/format_parse/index.md
Fix links on the "Formatting and Parsing" page in the User Guide.
=> ICU-20088 User Guide migration: Fix links on formatting page.

tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/PseudoLocales.java, tools/cldr/cldr-to-icu/src/test/java/org/unicode/icu/tool/cldrtoicu/PseudoLocalesTest.java
=> ICU-21227 Fixing pseudo locale generation to include RTL control chars in exemplars

icu4c/source/data/cldr-icu-readme.txt, tools/cldr/build.xml, tools/cldr/cldr-to-icu/README.txt, tools/cldr/cldr-to-icu/build-icu-data.xml
This PR does a few useful things to improve the ICU build process.
1: Introduces a new higher level Ant build file (still provisional so not documented in detail yet).
This can act as a coordinator for installing CLDR libraries, test data and running the default ICU data generation.
Eventually this should take over all the default operations which use CLDR related code/data when doing a release.
2: Fix the build-icu-data.xml build file to no longer require the CLDR_DIR environment variable to be set.
This is great for simplifying the build steps since it avoids a risk of confusion. You can invoke it now by either setting a CLDR_DATA_DIR environment variable or passing the "cldrDataDir" property.
3: Reworded the cldr-to-icu readme to use the same environment variable names and descriptions …
=> ICU-21066 Improvements in Ant build files

icu4j/main/classes/charset/src/com/ibm/icu/charset/CharsetUTF16.java, icu4j/main/classes/core/src/com/ibm/icu/util/VersionInfo.java
Internal API VersionInfo.javaVersion() maps Java version number to  4 integer fields. Each field must be up to 255. However, recent OpenJDK 8 update exceed this range.
Luckily, we have only one reference in our code base for checking Java version. CharsetUTF16 uses maxBytePerChar = 4 for Java 5 and older, maxBytePerChar = 2 for newer Java version. Because we no longer support Java 5 runtime, we don't need this conditional check.
We don't have any other uses of VersionInfo.javaVersion(). Java's version range is not what we can control, so I decided to delete the internal use only API completely.
=> ICU-21219 Fix for Java version number overflow problem

.ci-builds/.azure-pipelines.yml, icu4c/source/test/cintltst/cloctst.c, icu4c/source/test/cintltst/cloctst.h
This PR adds a test to make sure that the `C` and `C.UTF-8` LANG setting will cause ICU to have `en_US_POSIX` as the default locale. It seems that in some previous versions this was changed and we now want to make sure that it remains the same or a test fails to let us know it changed so we can investigate further.
=> ICU-20808 Add test for the C locale to default to en_US_POSIX

icu4c/source/common/loclikely.cpp, icu4c/source/common/uloc.cpp, icu4c/source/common/ulocimp.h
https://unicode-org.atlassian.net/browse/ICU-21035
By always calling the dynamic memory allocation implementation directly
instead, the fixed memory buffer boundary gets pushed one step further
towards the edges.
=> ICU-21035 Replace backward compatibility ulocimp_getLanguage() overload.

icu4c/source/common/locdispnames.cpp, icu4c/source/test/cintltst/cloctst.c, icu4c/source/test/cintltst/cloctst.h
While the buffer is the exact length of the output string, the
function should not null terminate it but set status to
U_STRING_NOT_TERMINATED_WARNING.
=> ICU-21157 Fix incorrect null termination.

icu4c/source/common/cmemory.h, icu4c/source/common/localematcher.cpp, icu4c/source/i18n/listformatter.cpp, icu4c/source/i18n/number_decimalquantity.cpp, icu4c/source/i18n/number_utils.cpp, icu4c/source/i18n/numparse_affixes.cpp, icu4c/source/i18n/numparse_affixes.h, icu4c/source/i18n/numparse_types.h, icu4c/source/test/intltest/numbertest_parse.cpp
It’s probably a very unlikely failure: how often might memory allocation fail for something like this?
But “more correct” is probably not bad, and the “toString” that’s hereby getting a “status” parameter is probably mostly for debugging?
=> ICU-21230 Add status parameter to MaybeStackArray(int32_t newCapacity) constructor

icu4c/source/common/loclikely.cpp, icu4c/source/common/uloc.cpp, icu4c/source/common/ulocimp.h
By always calling the dynamic memory allocation implementation directly
instead, the fixed memory buffer boundary gets pushed one step further
towards the edges.
=> ICU-21035 Replace backward compatibility ulocimp_getScript() overload.

icu4c/source/common/loclikely.cpp, icu4c/source/common/uloc.cpp, icu4c/source/common/ulocimp.h
By always calling the dynamic memory allocation implementation directly
instead, the fixed memory buffer boundary gets pushed one step further
towards the edges.
=> ICU-21035 Replace backward compatibility ulocimp_getCountry() overload.

icu4c/source/common/uloc_tag.cpp
The complicated buffer allocation code is inherited from times past but
no longer serves any purpose, it's now possible to instead simply call
the CharString copy constructor.
=> ICU-21035 Remove obsolete use of CharString::getAppendBuffer().

vendor/double-conversion/upstream/.gitignore, vendor/double-conversion/upstream/BUILD, vendor/double-conversion/upstream/CMakeLists.txt, vendor/double-conversion/upstream/test/cctest/CMakeLists.txt
The diffs are clean.  The only changes are in build files; the library code is unchanged.
=> ICU-21249 Updating double-conversion for ICU 68

icu4c/source/common/locid.cpp, icu4c/source/common/uloc.cpp, icu4c/source/common/ulocimp.h, icu4c/source/common/unicode/urename.h
By updating the last 3 callers to do dynamic memory allocation instead,
the fixed memory buffer function becomes obsolete.
=> ICU-21035 Replace backward compatibility locale_getKeywords() function.

icu4c/source/common/punycode.cpp, icu4c/source/common/punycode.h, icu4c/source/test/intltest/uts46test.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/Punycode.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/normalizer/UTS46Test.java
https://unicode-org.atlassian.net/browse/ICU-13727
See the bug ticket for a discussion of the length limits.
Using the new input-too-long error/exception.
The unit tests deliberately use much longer input strings. I do not want them to be tighter than necessary.
=> ICU-13727 limit length of input for Punycode encode/decode

icu4c/source/i18n/number_formatimpl.cpp, icu4c/source/test/intltest/numbertest_api.cpp, icu4c/source/test/intltest/numbertest_permutation.cpp, icu4c/source/test/testdata/numberpermutationtest.txt, icu4j/main/classes/core/src/com/ibm/icu/number/NumberFormatterImpl.java, icu4j/main/tests/core/src/com/ibm/icu/dev/data/numberpermutationtest.txt, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
This PR depends on #1230.  I broke tradition and pushed my branches to upstream instead of to my fork so that I can actually make the PRs depend on each other in GitHub's UI ([details](https://github.com/isaacs/github/issues/959#issuecomment-642838613)).
=> ICU-20923 Fix compact notation with percent.

icu4c/source/common/charstrmap.h, icu4c/source/common/common.vcxproj, icu4c/source/common/common.vcxproj.filters, icu4c/source/common/common_uwp.vcxproj, icu4c/source/common/loclikelysubtags.cpp, icu4c/source/common/loclikelysubtags.h, icu4c/source/common/uniquecharstr.h
Move UniqueCharStrings and CharStringMap from
loclikelysubtags.{h,cpp} to separate header files
so we can reuse them to implement
https://github.com/unicode-org/icu/pull/1254
- [] Tests included
- [] Documentation is changed or added
=> ICU-21236 Refactor UniqueCharStrings / CharStringMap

icu4c/source/common/locid.cpp, icu4c/source/common/uloc.cpp, icu4c/source/common/ulocimp.h
This eliminates the need for a scratch buffer in Locale::getKeywordValue()
and also the need for counting bytes required in uloc_getKeywordValue(),
something that ByteSink will now handle correctly.
=> ICU-21035 Pass ByteSink from Locale::getKeywordValue() to uloc_getKeywordValue()

icu4c/source/i18n/plurrule.cpp, icu4c/source/i18n/plurrule_impl.h, icu4c/source/test/intltest/plurults.cpp, icu4c/source/test/intltest/plurults.h
This PR adds the missing functionality in C++ for parsing plural rule strings as a part of supporting the exponent operand in plural rules.  The previous exponent operand work was implemented in #938 (Java) and #972 (C++).
As a side note, after adding the logic for the plural rule parser for the 'e' operation in C++, I noticed that the equivalent code for the 'w' operand seems to be missing -- is that intentional?
=> ICU-21254 Add plural rule parsing for exponent operand in C++

tools/cldr/cldr-to-icu/build-icu-data.xml
This just adds the br collation to the cldr-to-icu integration build. It will not have any effect until the next cldr-to-icu integration. I checked and this is the only item in CLDR coll/rbnf/brkiter data that was missing from the build-icu-data.xml file.
=> ICU-21262 add br collation for cldr-to-icu build

icu4c/source/common/ucurr.cpp
These two calls to uloc_getKeywordValue() write to the buffer "id" which
then immediately after is overwritten by calls to idForLocale() so they
can simply be removed without any loss of functionality.
https://unicode-org.atlassian.net/browse/ICU-21035
=> ICU-21035 Delete meaningless calls to uloc_getKeywordValue().

icu4c/source/common/cmemory.h, icu4c/source/i18n/measunit.cpp, icu4c/source/i18n/measunit_impl.h
Rationale: appendAll() requires T to have a copy constructor. For Units work, we're using MaybeStackVector to store things that cannot be copy-constructed. While Clang succeeds, we have MSVC failures when we export the required symbols.
This was cherry-picked out of the big ICU4C Units-upstreaming PR: https://github.com/unicode-org/icu/pull/1284/commits/2f4561c7a76794b90c800768b407977a2336df5a / https://github.com/unicode-org/icu/pull/1284.
=> ICU-21174 Drop MaybeStackVector::appendAll()

icu4c/source/i18n/dtptngen.cpp
We need to check that `calendarTypeLen > 0`, otherwise it will try to append random memory.
=> ICU-21271 Fix valgrind failure in dtptngen.cpp

.ci-builds/.azure-pipelines.yml, icu4c/source/allinone/Build.Windows.PlatformToolset.props
This also adds a new `AutodetectWin10SDK` parameter, so that we can build with the VS2019 installation (which doesn't have the Win8.1 SDK) but still use the VS2015 compiler/toolset.
(Note: The Win10 SDK is still backwards compatible with Win7).
=> ICU-21108 Fix CI job names after VS2019 update, and add CI build using the VS2015 toolset

icu4c/source/common/uloc_tag.cpp, icu4c/source/test/cintltst/utf8tst.c
A number of functions had the optimizer turned off due to optimizer bugs that were present in VS2015 and VS2017.
Since we can now build with VS 2019 (see PR #1288), we can enable optimization for these functions for MSVC when building with VS2019 or higher.
Note: Unfortunately, it seems that the MSVC compiler (using the latest VS2019) is *still* having issues with the following function:
`void ExtraData::writeExtraData(UChar32 c, Norm &norm)`
https://github.com/unicode-org/icu/blob/master/icu4c/source/tools/gennorm2/extradata.cpp#L189
So we’ll need to keep this one turned off for now.
=> ICU-21264 Re-enable optimizations for various functions for MSVC with VS2019 and above

icu4c/source/io/ufile.cpp, icu4c/source/io/unicode/ustdio.h, icu4c/source/test/iotest/filetst.c, icu4c/source/test/iotest/iotest.cpp, icu4c/source/test/iotest/iotest.h
This avoids possible buffer overflow in u_fopen_u for long filenames due to use of u_austrcpy with fixed-size buffer. Instead, this uses UnicodeString.extract for conversion to platform codepage, with buffer allocation if result would overflow fixed buffer.
It adds a test opening a file with a very long name. I noticed that existing u_file open tests generally *created* files for writing instead of opening existing files for reading. @grhoten, @jefgen, @markusicu: Do we (still) have platform compatibility issues that might cause problems adding a file with a long name (in the first version of this the filename itself is 254 characters, but the path passed to u_fopen_u is >256) with a specified content encoding (UTF-8)?
=> ICU-21106 avoid buffer overflow in u_fopen_u

icu4c/source/test/cintltst/cintltst.c
segmentation faults when unit tests run without ICU data.
=> ICU-21268 Adds NULL string checks to assert statements to prevent

icu4c/source/i18n/hebrwcal.cpp, icu4c/source/i18n/indiancal.cpp, icu4c/source/i18n/islamcal.cpp, icu4c/source/test/intltest/incaltst.cpp, icu4c/source/test/intltest/incaltst.h, icu4c/source/test/testdata/calendar.txt
This PR fixes
ICU-21043 Erroneous date display in indian calendar of all dates prior to 0001-01-01.
ICU-21044 Hebrew Calendar calculation is incorrect when the year < 1
ICU-21045 Erroneous date display in islamic and islamic-rgsa calendars of all dates prior to 0622-07-18.
ICU-21046 Erroneous date display in islamic-umalqura calendar of all dates prior to  -195366-07-23.
The problem in the indiancal.cpp is
* ICU-21043 the gregorian/julain convesion is wrong. Swith to use
i18n/gregoimp.h fix the problem.
The problem in the hebrwcal.cpp is
* ICU-21044 the use of bulit in / is wrong when the year or month could be < 1.
Fix it by switching to use ClockMath::floorDivide in i18n/gregoimp.h .
The problem in the islamcal.cpp:
* ICU-21045: The math of % negative number for year and month is wrong. …
=> ICU-21043 Fix calendar problems

.ci-builds/.azure-pipelines.yml, icu4c/source/data/makedata.mak
This is part 2 of the fix for [ICU-21272](https://unicode-org.atlassian.net/browse/ICU-21272):
- The fix for `makedata.mk` was done in PR #1316.
- This PR changes/modifies the CI builds to add another build for ARM64 Debug to the CI pipeline to prevent any regressions.
Description:
The ARM/ARM64 builds for ICU4C for Windows require building x64 *first*, as they use the x64 tools in order to cross-build ARM/ARM64. In the `makedata.mk` file, there was an accidental hard-coded reference to always use the `x64\Release` version of the tools. However, this should use `x64\Debug` if you're building ARM/ARM64 for `Debug`, and `x64\Release` for `Release`.
Thanks to @shaobero for finding and reporting this issue. :)
=> ICU-21272 Add Windows ARM64 Debug build to CI build configuration

icu4c/source/i18n/dtitvfmt.cpp, icu4c/source/i18n/udateintervalformat.cpp, icu4c/source/i18n/unicode/dtitvfmt.h, icu4c/source/i18n/unicode/udateintervalformat.h, icu4c/source/test/cintltst/cdateintervalformattest.c, icu4c/source/test/intltest/dtifmtts.cpp, icu4c/source/test/intltest/dtifmtts.h, icu4j/main/classes/core/src/com/ibm/icu/text/DateIntervalFormat.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/DateIntervalFormatTest.java
This adds setContext and getContext to [U]DateIntervalFormat, to control capitalization of the formatted result depending on the context in which it will be used. This API addition was approved by TC 2019-Jun-12 (originally for ICU 65). Because DateIntervalFormat already uses a SimpleDateFormat (in fDateFormat) to format the various parts of the pattern and because SimpleDateFormat already supports setContext, all we need to do is make sure that the context set for DateIntervalFormat is used for the call to SimpleDateFormat that formats the first part of the interval pattern and then no context is set for any subsequent calls to SimpleDateFormat for the remainder of the interval pattern.
=> ICU-20651 add setContext/getContext for [U]DateIntervalFormat

icu4c/source/i18n/unicode/ucoleitr.h, icu4c/source/i18n/unicode/usearch.h
This change adds notes to the API documentation in `ucoleiter.h` and `usearch.h` that the input string arguments must not be deleted and/or changed while the ICU objects are still potentially using them.
I tried to use wording for this that is similar to existing wording on other APIs in order to have consistency in the library.
Some existing examples:
https://github.com/unicode-org/icu/blob/master/icu4c/source/common/unicode/brkiter.h#L178
```
* The BreakIterator will retain a reference to the supplied string.
* The caller must not modify or delete the text while the BreakIterator
* retains the reference.
```
https://github.com/unicode-org/icu/blob/master/icu4c/source/common/unicode/ubrk.h#L364
```
* The break iterator retains a pointer to the supplied text.
* The caller must not modify …
```
=> ICU-21196 Clarify API docs for input strings in ucoleiter.h and usearch.h

icu4c/source/i18n/unicode/numberformatter.h
- Original icu-design review took place in February ([ICU 67 API proposal status](https://docs.google.com/document/d/e/2PACX-1vQwfVlRqSzD3VHPNt5UGKad9lZSK1rj9M9h8VHi06cxu1wp3GwAWZvjDG1wLZXVHJQlO1-AJnXJM14e/pub) - ”[approved:2020-02-19] ICU proposal: Support Locale-aware Measurement Unit Formatting” - design at http://bit.ly/icu-measurement-formatting).
- Commit 45f79b6 was already reviewed in March at https://github.com/sffc/icu/pull/23. Please give extra attention to the following commit (459c33b).
This PR is intended to precede #1284 in order to make review easier.
- We could merge the PRs separately, or,
- we could rebase 1284 onto the result of this review in order to stack them and merge them at the same time.
- (If we go this latter route, moving this PR into a new branch on …
=> ICU-20568 Fix NumberFormatterSettings::usage documentation

.travis.yml, icu4c/source/test/hdrtst/testinternalheaders.sh
Updates test script to return an non zero exit code in case of a
compilation error.
=> ICU-21248 Adds internal header check to Travis Continued Integration.

icu4c/source/test/intltest/strcase.cpp
error (toTitle() not found) when this configuration flag is set.
=> ICU-21249 Adds #if !UCONFIG_NO_BREAK_ITERATOR to prevent compilation

icu4c/source/i18n/number_formatimpl.cpp, icu4c/source/i18n/number_usageprefs.cpp, icu4c/source/i18n/number_usageprefs.h, icu4c/source/i18n/unicode/measunit.h
This moves input unit calculation out of UnitConversionHandler making
it simpler and clearer, and localises the "MacroProps interpretation"
work in macrosToMicroGenerator, where it belongs.
=> ICU-20568 Units cleanup: have macrosToMicroGenerator do the input unit calculation

icu4j/main/classes/core/src/com/ibm/icu/util/IndianCalendar.java, icu4j/main/classes/core/src/com/ibm/icu/util/IslamicCalendar.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/calendar/IBMCalendarTest.java
This is the java port of ICU-21043 (for C++)
This PR fixes
ICU-21043 Erroneous date display in indian calendar of all dates prior to 0001-01-01.
ICU-21044 Hebrew Calendar calculation is incorrect when the year < 1
ICU-21045 Erroneous date display in islamic and islamic-rgsa calendars of all dates prior to 0622-07-18.
ICU-21046 Erroneous date display in islamic-umalqura calendar of all dates prior to -195366-07-23.
The problem in the IndianCalendarl is
ICU-21043 the gregorian/julain convesion is wrong. Swith to use the
calculation function in the Calendar class.
The problem in the HebrewCalendar is
ICU-21044 the use of bulit in / is wrong when the year or month could be < 1.
The problem in the IslamicCalendar is
ICU-21045: The math of % negative number for year and month is wrong.
Also add …
=> ICU-21283 Fix Java for calendar bugs

.ci-builds/.azure-exhaustive-tests.yml
It seems that recent additional test cases for Exhaustive Mode are running up against the current time limit for the Exhaustive Tests that run on master, leading to timeouts which causes build failures.
This change increases the timeout for the builds, and filters out a few more unrelated files to avoid churn.
=> ICU-21291 Increase the timeout for the Exhaustive Test CI builds

.github/workflows/maven.yaml, icu4j/.gitignore, icu4j/main/classes/core/src/com/ibm/icu/text/DecimalFormat.java
ICU-21251
- on a release (created from Github), publish to
<https://github.com/unicode-org/icu/packages>
- also fix a doc bug in DecimalFormat
- this is intended for CLDR use to support CLDR-11585 maven
No effect on current build systems, no effect on commit or PRs.
=> ICU-21251 release icu4j.jar/utilities.jar to GH Maven

tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/PseudoLocales.java
datetime pattern item from 12 hrs to 24 hrs format to prevent a unit
test failure.
=> ICU-21259 Adds a filter to pseudolocale generator to switch a particular

tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/LdmlConverter.java
no longer added to the .txt data files with the exception of the
root.txt files. This will drastically limit the number of changed
files during a version upgrade because the version change is the
only change in many of the data files.
ICU-21028 Fixed an indent.
=> ICU-21028 Modifies ICU data generator so that the CLDR version is

icu4j/main/classes/core/src/com/ibm/icu/text/PluralRules.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/PluralRulesTest.java
@sffc Let me know if this is reasonable or at least if it is on the right track.  FYI, the test data came from Mark's commit at https://github.com/unicode-org/cldr/pull/712/files.  Also, in case it's useful, Mark's PR solves the problem alternatively by subclassing FixedDecimal.
=> ICU-21270 Update FixedDecimal in Java to support exponent

icu4c/source/i18n/dtptngen.cpp, icu4c/source/i18n/smpdtfmt.cpp, icu4c/source/i18n/unicode/dtptngen.h, icu4c/source/test/intltest/dtptngts.cpp, icu4c/source/test/intltest/dtptngts.h, icu4j/main/classes/core/src/com/ibm/icu/text/DateTimePatternGenerator.java, icu4j/main/classes/core/src/com/ibm/icu/util/Calendar.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/DateTimeGeneratorTest.java
When there is no specific data for a locale, ensure that standard time formats (primarily the SHORT version) at least match the same formats that would be obtained using DateFormat.getInstanceForSkeleton or DateTimePatternGenerator.getBestPattern using skeletons with 'j' such as "jmm"; this ensures that the time formats at least have the correct hour cycle for the specified or inferred region.
To do this, ICU4C SimpleDateFormat and ICU4J Calendar call DateTimePatternGenerator to generate the appropriate time patterns when there is no locale data. To prevent circular dependencies from DateTimePatternGenerator on SimpleDateFormat/Calendar, the DateTimePatternGenerator instantiated from SimpleDateFormat/Calendar is a slightly stripped-down version that still provides what is needed for the …
=> ICU-20590 Ensure time format consistency for SHORT vs 'j' patterns if no locale data

icu4c/source/samples/all/samplecheck.bat, icu4c/source/samples/coll/coll.cpp, icu4c/source/samples/numfmt/main.cpp, icu4c/source/samples/strsrch/strsrch.cpp, icu4c/source/samples/uciter8/uciter8.c, icu4c/source/samples/uciter8/uit_len8.c, icu4c/source/samples/ucnv/convsamp.cpp, icu4c/source/samples/ucnv/flagcb.c, icu4c/source/samples/udata/reader.c, icu4c/source/samples/ufortune/ufortune.c, icu4c/source/samples/ufortune/ufortune.vcxproj, icu4c/source/samples/ugrep/ugrep.cpp, icu4c/source/samples/ugrep/ugrep.vcxproj, icu4c/source/samples/uresb/uresb.c, icu4c/source/samples/ustring/ustring.cpp
This PR makes changes/fixes for the ICU 68 BRS task for "ICU4C Samples", in order to get the samples to compile with some of the changes made in ICU 68. (The change to use C++/C99 `true`/`false` instead of of the custom ICU macros for them).
Changes in this PR include:
- Change to use `true`/`false` instead of the custom `TRUE`/`FALSE` macros in order to fix compilation errors.
- Adding casts to prevent/silence warnings.
- Some clean-up to the "ufortune" and "ugrep" Visual Studio project `.vcxproj` files.
- Setting the codepage to UTF-8 in `samplecheck.bat` in order to prevent garbled output when running the samples.
=> ICU-21249 BRS68RC: Fixes and changes for the ICU4C Samples.

docs/userguide/format_parse/datetime/index.md
No content changes.  This make the display of date patterns, date field symbols, and skeletons consistent.
- Date field symbols are in a code block (e.g. `y` or `yyyy`)
- Date patterns are quoted in a code block (e.g. `"y"` or `"MMMM d 'at' h:mm a"`)
- Skeletons are the same as date patterns (e.g. "`MMMMdjmm`")
- Strings that might be the result of a date pattern are quoted (e.g. "April 2 at 5:00 PM")
Thus `"y"` denotes the date pattern containing the date field symbol `y`
=> ICU-21282 Fixup date patterns and date field symbols display

icu4c/source/common/locid.cpp, icu4c/source/test/cintltst/unumberrangeformattertst.c, icu4c/source/test/intltest/plurults.cpp, icu4c/source/test/intltest/units_test.cpp
Reproduce procedure
1. build and test normally
2. cd icu4c/source
cp stubdata/libicudata.so.60.1 lib/
cd test/intltest
INTLTEST_OPTS=-w make check
cd ../cintltst
CINTLTST_OPTS=-w make check
Fixed 4 issues:
In locid.cpp return memory error if the singleton is nullptr
In test code, stop testing after checked failure.
=> ICU-21297 Fix crash when ICU runs with stubdata only

icu4c/source/test/cintltst/cldrtest.c, icu4c/source/test/cintltst/creststn.c, icu4c/source/test/intltest/restsnew.cpp, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/ICUResourceBundleTest.java
... which PR #1365 commented out to work around ICU-21028 removing the Version string resource from most locale data bundles. The root bundles in each locale data tree still have a Version string, so this PR restores the test cases with a little more leniency.
https://unicode-org.atlassian.net/browse/ICU-21249 (ICU 68rc BRS)
=> ICU-21249 restore tests of Version resources

icu4j/main/shared/licenses/LICENSE
Lao dictionary repo location was updated in LICENSE file in icu4c, but a copy in icu4j tree was not. Sync the icu4j copy with the icu4c one.
=> ICU-21249 Update copy of LICENSE file in icu4j tree

icu4c/source/common/wintz.cpp
@jungshik: This PR is a continuation of PR #1297.
I created a new PR for this in order to get the change into ICU 68 by the code freeze. :)
Description from the previous PR and the bug:
The Windows 'Date and Time' Control Panel has a setting for "Automatically adjust clock for DST".
When this setting is manually unchecked, the DST setting is considered OFF, and the clock does not adjust for DST.
However, ICU currently doesn't detect this setting and will continue to use the time zone ID which has DST enabled.
In order to handle this situation, this change detects when the DST setting is OFF and uses the non-DST offset to map to an Etc/GMT+-hh zone.
This change also refactors the code in `uprv_detectWindowsTimeZone` somewhat as well.
Note: Much of this change was originally authored by …
=> ICU-13845 Windows timezone detection: When DST is off, map to an Etc/GMT+-hh zone

icu4c/source/layoutex/ParagraphLayout.cpp
Let the `complexTable[]` length be determined by the compiler, and check the array index against the actual array length.
https://unicode-org.atlassian.net/browse/ICU-21269
FYI  I also see where scriptCodeCount is used but not where it's defined.
=> ICU-21269 ParagraphLayout complexTable: init & access based on actual values

icu4j/main/classes/core/src/com/ibm/icu/impl/Utility.java, icu4j/main/classes/core/src/com/ibm/icu/util/ULocale.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/UtilityTest.java
Recent code changes introduced String#join(...) method, which is available in Java 8 or newer release. We still need to support Java 7 as minimum runtime, we need to replace the method call with equivalent code. I added Utility#joinStrings(...) as temporary alternative until we change minimum Java version to 8 or later.
=> ICU-21307 Java 7 compatibility support in ULocale.java

.ci-builds/.azure-pipelines.yml
No code changes in this PR. This is adding another CI build bot that builds on Ubuntu 20.04 with GCC.
=> ICU-21278 Add Ubuntu 20.04 build bot with GCC to CI builds.

.appveyor.yml
(No code changes in this PR).
The Cygwin parallel build often fails (it is flaky) due to race-condition(s) and issues with `ln -f` failing.
This PR changes the AppVeyor build to be single-threaded in order to have more stability for the CI builds.
=> ICU-21249 Change AppVeyor to not use parallel build due to Cygwin stability issues

icu4c/source/i18n/number_longnames.cpp, icu4c/source/i18n/units_complexconverter.cpp, icu4c/source/i18n/units_router.cpp, icu4c/source/test/intltest/numbertest_api.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/number/MixedUnitLongNameHandler.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/ComplexUnitsConverter.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitsRouter.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
Without this PR, negative number formatting for mixed units is several kinds of screwy.
With this PR: "-1 foot, 3 inches". First number gets the negative, the remaining numbers are formatted positively. (TBD: whether this is correct for all locales. It's definitely a huge improvement for common European languages and languages with similar writing systems for numbers.)
Closes: https://github.com/icu-units/icu/issues/63.
=> ICU-20568 Improve negative measure handling for mixed units

icu4c/source/common/locid.cpp
This fixes new warnings in `locid.cpp` that were introduced by the recent changes for ICU-21236.
Warnings:
```
locid.cpp: In member function `bool icu_68::{anonymous}::AliasReplacer::replaceLanguage(bool, bool, bool, icu_68::UVector&, UErrorCode&)`:
locid.cpp:1255:21: warning: `replacedLanguage` may be used uninitialized in this function [-Wmaybe-uninitialized]
locid.cpp:1279:54: warning: `replacedExtensions` may be used uninitialized in this function [-Wmaybe-uninitialized]
locid.cpp:1043:28: warning: `replacedVariant` may be used uninitialized in this function [-Wmaybe-uninitialized]
locid.cpp:1043:20: warning: `replacedRegion` may be used uninitialized in this function [-Wmaybe-uninitialized]
locid.cpp:1043:20: warning: `replacedScript` may be used uninitialized in this function …
```
=> ICU-21249 Fix warnings about uninitialized variables in locid.cpp

icu4c/source/i18n/plurrule.cpp, icu4c/source/i18n/plurrule_impl.h, icu4c/source/i18n/unicode/plurrule.h, icu4c/source/test/intltest/plurults.cpp, icu4c/source/test/intltest/plurults.h
Changing the plural rule sample parsing from returning doubles to returning FixedDecimals seemed successful (existing tests still pass).
Tests pass parsing integer samples.  But the tests for parsing decimal samples fail.  So that's where I'm stuck at the moment.
=> ICU-21270 Support exponent in FixedDecimal and samples in C++

icu4c/source/test/cintltst/unumberrangeformattertst.c
=> ICU-21249 Adds check of result string for NULL to prevent segmentation fault if

icu4c/source/common/ubidiimp.h, icu4c/source/test/intltest/numbertest.h
https://unicode-org.atlassian.net/browse/ICU-20853
Fixes [ICU-20853] = [ICU-20935].
Also fixes [ICU-20241] and replaces its PR #467.
[ICU-20853]: https://unicode-org.atlassian.net/browse/ICU-20853
[ICU-20935]: https://unicode-org.atlassian.net/browse/ICU-20935
[ICU-20241]: https://unicode-org.atlassian.net/browse/ICU-20241
=> ICU-20853 undef Solaris x86 register macros where they conflict

icu4c/source/i18n/unicode/numberformatter.h, icu4c/source/i18n/unicode/plurfmt.h, icu4c/source/i18n/unicode/timezone.h
Added U_HIDE_INTERNAL_API guards around new `@internal` APIs.
This is the first time I've done this, so it's possible that I've done it wrong.  I can say that `make check` in `test/hdrtst` still passes with these changes.  I also didn't do anything about `@internal` stuff in `stringtriebuilder.h` and `ucptrie.h`, because these seemed to be long-standing API additions and seemed to have other things guarding them.  (It's also entirely possible that some of the stuff I found when I prepped for `@internal` and didn't include here was stuff I just missed, although I tried hard to make sure the only things I skipped were for clear reasons listed in the guidelines for this task.)
=> ICU-21249 Add new U_HIDE_INTERNAL_API guards

icu4c/source/common/locid.cpp, icu4c/source/i18n/ulocdata.cpp, icu4c/source/test/cintltst/cloctst.c, icu4c/source/test/cintltst/crestst.c, icu4c/source/test/cintltst/creststn.c
1. Fix Locale Canonicalization code when the default locale is one of
the possible region. Use 'und' instead of nullptr to construct the
locale.
2. use ures_getStringByKeyWithFallback instead of ures_getStringByKey
inside ulocdata_getDelimiter because fa_CA depends on the fallback to
get data from fr locale.
3. Skip resources bundle tests if default locale is one of te, sh or mc
locales since the testdata include data of these locales and the test
expectation does not hold if the default locale is one of them .
4. Only report uloc_getDisplayLanguage issue if the default locale
is one listed in the available list.
=> ICU-21316 Fix bug under different default locales

icu4c/source/data/Makefile.in, icu4c/source/extra/scrptrun/Makefile.in, icu4c/source/tools/toolutil/toolutil.cpp
Dear Maintainers
I have fixed multiple failures preventing normal building with cygwin/MSVC. Could you consider also merging those into next release alpha?
- Fixed genrb (and all other utils) not recognizing alternative file separators on windows, which previously prevented generation of data in out-of-source build. Officially distributed binaries have the same issue. f402ff9; Now checks for last occurrence of both the separator and alternative separator are run before returning the one which is furthest into the string.
- Added few more fixes to the makefile of a new component  (extra/scrptrun), it had a redundant inculde of platform setup duplicating suffices in names of libraries (i.e. requiring compiler to find 'libicuucd**d**.lib' along with some other possible ill side-effects) …
=> ICU-20677 Fixing cygwin/MSVC build

icu4c/source/common/wintz.cpp
This is related to PR #1362. 
Thanks to @FrankYFTang for catching this issue, and sorry for the build break.
The variable `utcOffsetMins` is type `long` (via a typedef for `LONG`), so the calculation of `-utcOffsetMins/60` is also a `long` as well. This leads to an error as the format string uses `d` which is only for `int`.
(Aside: A possible alternate fix would be to use `static_cast<int>(-utcOffsetMins/60)` in order to make it an `int` as the value should never require the full range of `long`.)
=> ICU-21336 Fix format string to use long instead of int in common/wintz.cpp

icu4c/source/i18n/formattedval_impl.h, icu4c/source/i18n/formattedval_sbimpl.cpp, icu4c/source/i18n/listformatter.cpp, icu4c/source/test/intltest/listformattertest.cpp, icu4c/source/test/intltest/listformattertest.h
I managed to fix forward.  The new code is simpler than the old code.
=> ICU-21340 Don't coalesce adjacent list formatter fields in ICU4C

icu4c/source/common/wintz.cpp
The time zone detection logic in ICU uses the Win32 API `GetDynamicTimeZoneInformation` (which is available since Vista) to get the current time zone info, as this API returns a _non-localized_ time zone name which can be then mapped to an ICU time zone.
However, in some RDP/terminal services situations, this struct isn't always fully complete, and the `TimeZoneKeyName` field of the struct might be `NULL`.
This can happen in some RDP/terminal services sessions where the 'Time Zone Redirection' feature is enabled, as some 3rd party RDP clients (and also older versions of the RDP protocol), don't send the newer `TimeZoneKeyName` information, and only send the `StandardName` and `DaylightName`.
Since these 3rd party clients and older RDP clients only send the pre-Vista time zone information …
=> ICU-21352 Windows time zone detection can fail in RDP sessions with 3rd party software and older RDP clients

tools/cldr/cldr-to-icu/pom.xml
The GtiHub automated scanning flagged an issue with an older version of Apache Ant.
This change updates the version of Apache Ant from 1.10.8 to 1.10.9 in order pick up the fix for CVE-2020-1945.
=> ICU-21250 Update Apache Ant to 1.10.9

icu4c/source/common/cmemory.h, icu4c/source/test/intltest/measfmttest.cpp, icu4c/source/test/intltest/units_test.cpp
**Question to reviewer:** indirectly testing this via MeasureUnitImpl: sufficient? Or should I produce a unit test specifically for a MemoryPool instance?
The old array can't simply be deallocated, their pointers still need to be deallcoated too.
Using swap() ensures that the destructor can take care of it when `other` is deallocated.
=> ICU-21356 Fix memory handling in MemoryPool::operator=()

icu4c/source/i18n/number_formatimpl.cpp, icu4c/source/i18n/number_longnames.cpp, icu4c/source/i18n/number_longnames.h, icu4c/source/i18n/number_skeletons.cpp, icu4c/source/test/intltest/numbertest_api.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/number/LongNameHandler.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/LongNameMultiplexer.java, icu4j/main/classes/core/src/com/ibm/icu/number/NumberFormatterImpl.java, icu4j/main/classes/core/src/com/ibm/icu/number/NumberSkeletonImpl.java, icu4j/main/classes/core/src/com/ibm/icu/util/MeasureUnit.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
Small step in the direction of ICU-20941 - contributes to icu-units#27.
With this change:
* LongNameHandler constructors no longer take "unit" and "perUnit" - they take only one parameter.
* Combining of "perUnit" into "unit" thus moved outside of the class, and
* splitting of "unit" into numerator and denominator moved into the class.
* Skeleton handling is simpler, because we no longer care about "perUnit".
Joule per Furlong was already supported when specified separately. It's just when given as a single unit that it didn't automatically get split.
=> ICU-20941 Support formatting joule-per-furlong (builtin-per-builtin).

icu4c/source/test/intltest/numfmtst.cpp, icu4c/source/test/intltest/numfmtst.h
This port was requested to confirm functionality for icu4c for php to use.
=> ICU-10997 Port test case for currency formatting to icu4c

icu4c/source/i18n/formattedval_impl.h, icu4c/source/i18n/formattedval_sbimpl.cpp, icu4c/source/i18n/listformatter.cpp, icu4c/source/test/intltest/formattedvaluetest.cpp, icu4c/source/test/intltest/listformattertest.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/FormattedValueStringBuilderImpl.java, icu4j/main/classes/core/src/com/ibm/icu/text/ConstrainedFieldPosition.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/FormattedValueTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/ListFormatterTest.java
The fix to the reported issue, a list with more than 8 elements, is the addition of an argument to the `.resize()` call in `appendSpanInfo`.  The other fix, at the bottom of `nextPositionImpl`, came up in Valgrind during testing and is triggered when calling `.nextPosition()` repeatedly after it has returned false.
=> ICU-21383 Fix memory problem in FormattedStringBuilder

icu4c/source/test/intltest/units_test.cpp
Java not included in this PR because Java doesn't have the same unit tests yet: icu-units#92 tracks that.
Closes: icu-units#112
This also takes the testConverter "maxDelta" from `1e-4*expected` to `1e-6*expected`. (Tests start failing for me at 1e-7.)
=> ICU-21366 testConverter: allow some double-precision error for 0.0

icu4c/source/common/wintz.cpp
This PR is a fix for the regression caused by the change in PR #1326.
The list of possible time zones returned is a space-delimited list in some cases.
The change in PR #1362 was only stopping at the null-terminator. Instead we need to stop at the first space.
I missed this when reviewing the changes in PR https://github.com/unicode-org/icu/pull/1297.
The issue is due to the removal of the check here on this line which was stopping at the null or space:
https://github.com/unicode-org/icu/pull/1297/files#diff-04dfe6b718cf7d1421df2b6ff3aa89d0b95a7e2d468f5eb323e3698557a3a936L106
=> ICU-21392 Fix Windows Time Zone detection when more than one possible time zone.

icu4c/source/i18n/units_complexconverter.cpp, icu4c/source/i18n/units_converter.cpp, icu4c/source/i18n/units_converter.h, icu4j/main/classes/core/src/com/ibm/icu/impl/units/MeasureUnitImpl.java
Compare two units using their conversion rates to the base instead of using a complete converter
=> ICU-21349 Improve MeasureUnit comparators

icu4c/source/i18n/units_complexconverter.cpp, icu4c/source/test/intltest/units_test.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/units/ComplexUnitsConverter.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/impl/UnitsTest.java
This improves some unit tests and makes C++ and Java code more similar, with an edge-case improvement in C++ complex number conversion accuracy.
I was considering tackling icu-units#108, but I think we should discuss what precision-handling differences we want between C++ and Java.
=> ICU-21349 Remove a potential 0/0 (=NaN). Align C++ & Java better.

icu4c/source/i18n/units_converter.cpp, icu4c/source/i18n/units_converter.h, icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitConverter.java
Addresses feedback given on unicode-org#1279 and sffc#21.
(These names were still confusing me - every time I dealt with the Java code in particular. On #1279 we had agreement that they needed to be fixed, so I'm fixing them.)
=> ICU-21349 Fix confusing names of exponent variables.

icu4c/source/common/uloc_tag.cpp, icu4c/source/test/intltest/loctest.cpp, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/ULocaleTest.java
Java is already doing so. Just add the same test to also assure it.
=> ICU-21401 Fix C++ canonicalize cel-gaulish to xtg

.appveyor.yml
While working on other things, I noticed that the AppVeyor CI setup uses the `Invoke-WebRequest` method to download the Cygwin installer setup program.
Based on experimentation and reading other reports online, it turns out that this is _really_ very slow way to download things. It takes several minutes+ to download files that are only a few megabytes in size. If we use `System.Net.WebClient.DownloadFile` method instead then the download only takes _seconds_.
Changing this should help a bit to speed up the AppVeyor builds.
They have been timing out and failing recently as they are now regularly running up against the 60 minute hard limit on AppVeyor.
=> ICU-21381 AppVeyor CI Builds: Speed up the Cygwin setup download.

icu4c/source/common/uloc_tag.cpp, icu4c/source/test/intltest/localebuildertest.cpp
=> ICU-21408 Prohibit alpha4 as language inside tlang.

icu4c/source/common/locid.cpp, icu4c/source/test/intltest/loctest.cpp, icu4j/main/classes/core/src/com/ibm/icu/util/ULocale.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/ULocaleTest.java
Only replace if the replacement value fit alphanum{3,8} for now.
replacement value length of 2 are pending on resolution of
https://unicode-org.atlassian.net/browse/CLDR-14312
=> ICU-21402 replace sd and rg by subdivisionAlias

docs/_config.yml
The older ICU User Guide (hosted on the Google Sites pages) had Google Analytics (GA) setup.
This PR adds the same GA tracking to the new GitHub pages-based ICU User Guide site as well (using the Jekyll config for it).
=> ICU-21377 Add Google Analytics to the ICU User Guide.

icu4c/source/i18n/unicode/tblcoll.h, icu4c/source/test/intltest/regcoll.cpp, icu4c/source/test/intltest/regcoll.h
The `RuleBasedCollator` class isn't marked as `U_FINAL`.
It appears as though the only reason the class isn't marked as final is due to test code in the `intltest` suite which subclasses the `RuleBasedCollator` class.
This is despite the fact that the `RuleBasedCollator` is documented as "not to be subclassed". (See: https://github.com/unicode-org/icu/blob/master/icu4c/source/i18n/unicode/tblcoll.h#L112).
However, the test code calling the test-only subclass has actually been commented out since 1999... see: https://github.com/unicode-org/icu/commit/256f5b22ad48ebcf6e1ec9350d4c7b31579176b9
It appears as though the only intent of the test case was to ensure that the `RuleBasedCollator` called `createCollationElementIterator` (and it did this by adding a `count` member), but the comment …
=> ICU-21388 Remove test case that does nothing so RuleBasedCollator can be marked as final.

icu4c/source/runConfigureICU
Yoshito is making this change on behalf of @datalogics-robb.
IBM's XL compiler can only support c++11 when the 'clang front end' is used.
This change modifies the configure step to use xlclang and  xlclang++
Change readme.html reference to xlC to refer to xlclang++ instead.
=> ICU-21363 Resurrect support for IBM's XL compiler

icu4c/source/common/locid.cpp, icu4c/source/common/uloc_tag.cpp, icu4c/source/common/ulocimp.h, icu4c/source/test/intltest/loctest.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/locale/LanguageTag.java, icu4j/main/classes/core/src/com/ibm/icu/util/ULocale.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/ULocaleTest.java
1. put tfield in alphabet order based on tkey
2. canonicalize tlang
=> ICU-21406 canonicalize -T- extension

icu4c/source/common/loclikelysubtags.cpp, icu4c/source/common/uloc_tag.cpp, icu4c/source/test/cintltst/cloctst.c, icu4c/source/test/intltest/loctest.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/locale/XLikelySubtags.java, icu4j/main/classes/core/src/com/ibm/icu/util/ULocale.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/ULocaleTest.java
Also fix ICU-21433 forLanguageTag when there are variant and -x-
extension
=> ICU-21414 Fix toLanguageTag x-private

docs/userguide/design.md
https://unicode-org.atlassian.net/browse/ICU-20107
User Guide binary compatibility: Clarify that there is no guarantee that the exports from common/i18n are stable in terms of not moving between the two libaries.
https://github.com/markusicu/icu/blob/clarify-binary-compatibility/docs/userguide/design.md
=> ICU-20107 binary compat: APIs may move between libraries

icu4c/source/common/cmemory.h, icu4c/source/common/uloc_tag.cpp
It was pointed out that uprv_memcpy() and uprv_memmove() internally use memcpy and memmove respectively, and these do not allow dst or src to be null. In this PR, I am adding a check for Debug mode for these two functions to make sure that doesn't happen.
After building ICU on Linux there was a case where adding this check could bring errors on the tests, so I am adding a check to uloc_tag.cpp as well.
After this, I built again on Linux and Windows and found no more issues. And all tests pass successfully :D
=> ICU-21118 check that dst and src are not null in uprv_memcpy

icu4c/source/common/unicode/urename.h
Update urename.h for ICU 68.2. This is targeted at the main branch. It does not remove any renames that were present in ICU 68.1, it just adds a new one.
=> ICU-21405 brs 68.2, update urename.h

docs/userguide/strings/regexp.md
See ICU-20088, which seems to be where most of them were introduced.
This is a copy of PR #1419, with the commit message updated to include the Jira issue.
=> ICU-21416 Fix typos and formatting errors in regexp.md

docs/userguide/strings/unicodeset.md, icu4c/source/common/unicode/uniset.h, icu4c/source/common/uniset.cpp, icu4c/source/common/uniset_props.cpp, icu4c/source/common/unisetspan.cpp, icu4c/source/test/intltest/usettest.cpp, icu4c/source/test/intltest/usettest.h, icu4j/main/classes/core/src/com/ibm/icu/impl/StaticUnicodeSets.java, icu4j/main/classes/core/src/com/ibm/icu/impl/UnicodeSetStringSpan.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/parse/InfinityMatcher.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/parse/MinusSignMatcher.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/parse/ParsingUtils.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/parse/PlusSignMatcher.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/parse/ScientificMatcher.java, icu4j/main/classes/core/src/com/ibm/icu/text/UnicodeSet.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/lang/UnicodeSetTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/StringTokenizerTest.java
... and ignore in matching like span().
https://unicode-org.atlassian.net/browse/ICU-13702 “Allow UnicodeSets to contain empty string”
and also
https://unicode-org.atlassian.net/browse/ICU-13805 “UnicodeSet.contains("") should not throw exception”
=> ICU-13702 allow empty string in UnicodeSet

icu4c/source/common/localematcher.cpp, icu4c/source/common/uhash.cpp, icu4c/source/common/uhash.h, icu4c/source/common/unicode/localematcher.h, icu4c/source/test/cintltst/chashtst.c, icu4c/source/tools/toolutil/xmlparser.cpp
https://unicode-org.atlassian.net/browse/ICU-20698
Make UHashtable usable with integer value zero, so that we need not add/subtract one (or do other tricks) for storing array indexes etc.
I am following the suggestion from the 2019 team ticket discussion: “Steven suggests instead adding a new variant of puti() that allows actually setting a 0 value, and a new variant of geti() that returns both the value and the “found” status.”
This turned out to be a fairly simple addition to the existing machinery.
New internal API:
- uhash_putiAllowZero()
- uhash_iputiAllowZero()
- uhash_getiAndFound()
- uhash_igetiAndFound()
- uhash_containsKey()
- uhash_icontainsKey()
=> ICU-20698 UHashtable allow integer value zero

icu4c/source/common/hash.h, icu4c/source/common/localeprioritylist.cpp, icu4c/source/tools/gennorm2/extradata.cpp
https://unicode-org.atlassian.net/browse/ICU-20698
Same additions for the C++ wrapper as in PR #1521 for the C implementation.
Also change two more callers to use the new functionality.
=> ICU-20698 C++ Hashtable allow integer value zero

icu4c/source/common/uniset.cpp, icu4c/source/common/uniset_props.cpp, icu4c/source/test/intltest/usettest.cpp
https://unicode-org.atlassian.net/browse/ICU-13702
More readable than numeric constants, easier porting between Java & C++.
=> ICU-13702 C++ UnicodeSet cleanup: use UTF-16 literals

icu4c/source/common/norm2allmodes.h, icu4c/source/common/normalizer2impl.cpp, icu4c/source/common/normalizer2impl.h, icu4c/source/common/unicode/normalizer2.h, icu4c/source/test/intltest/normconf.cpp, icu4c/source/test/intltest/tstnorm.cpp, icu4c/source/test/intltest/tstnorm.h
https://unicode-org.atlassian.net/browse/ICU-21279
This replaces the Normalizer2::normalizeUTF8() base class default implementation for NFD/NFKD. The base class converts to UTF-16, normalizes, and converts back; and it does not support Edits.
This PR adds a dedicated Normalizer2Impl::decomposeUTF8() that only converts substrings that do need normalization changes. As usual, the same code is also written to perform the isNormalizedUTF8() and spanQuickCheckYes() operations, but note that there is no public API for the UTF-8 version of spanQuickCheckYes().
There are some changes in the UTF-8 version of decomposeShort() which is now shared with composeUTF8().
There are some changes for wiring this into the Normalizer2 implementation class hierarchy.
The new code is called from the …
=> ICU-21279 decompose (NFD/NFKD) UTF-8 with Edits

icu4j/main/classes/core/src/com/ibm/icu/impl/FormattedValueStringBuilderImpl.java
Android ignores assert statement by default.
The test also failed when running with ant and on OpenJDK runtime
on release-67-1. But no longer fails on master branch.
=> ICU-21116 Fix ListFormatterTest on Android

tools/cldr/.gitignore
I recently ran into trouble trying to mirror/copy files from one ICU clone to another clone due to there being already checked-in files that were ignored by the `.gitignore` file under `tools/cldr`
The problem is that it excludes everything under the lib folder:
```
/lib/**
```
However, there are 3 checked in files in that folder which likely shouldn't be `gitignored`:
```
install-cldr-jars.txt
README.txt
pom.xml
```
The `README.txt` file is already _excluded_ by the `.gitignore` file:
```
!/lib/README.txt
```
We should likely add the other two files to the `.gitignore` file as well.
=> ICU-21427 Don't ignore already checked-in files under "tools/cldr/lib".

icu4c/source/config/mh-mingw, icu4c/source/config/mh-mingw64
After doing some research, it seems that the -Bsymbolic flag only makes sense on ELF platforms. The mingw linker driver for lld also doesn't support this flag either, so it should be removed.
=> ICU-21435 Remove -Bsymbolic flag for mingw targets

.github/workflows/icu_ci.yml
=> ICU-21450 Add builds for MacOS and for g++ with extra warnings to GHA CI.

icu4j/main/classes/core/src/com/ibm/icu/impl/ICULocaleService.java
I'm reordering the assignment that gets into this double check synchronized block to be the last step within the block. We want to avoid a scenario where loc is assigned to fallbackLocale before returning the fallbackLocaleName from this function.
=> ICU-21462 ICULocaleService.java has a race condition

icu4c/source/common/wintz.cpp
This PR fixes a bug in the changes for ICU-13845, for handling when the "Automatic DST" setting is OFF in the Control Panel.
It turns out that the offset value for the calculated time zone when the "Automatic DST" setting is turn off is wrong. The sign for the time zone offset is flipped. (It's positive when it should be negative, and vice-versa).
I think this was perhaps due to confusion about the value for the UTC offset, how POSIX style offsets are handled, and what is reported by the Win32 API `GetDynamicTimeZoneInformation`.
It seems that this issue was actually present in the original PR for ICU-13845 here: https://github.com/unicode-org/icu/pull/1297 , and it was missed in the reviews on the other PR for the ticket here: https://github.com/unicode-org/icu/pull/1362 .
I also missed …
=> ICU-21465 Fix Windows Time Zone offset when Automatic DST setting is Off

icu4c/source/common/wintz.cpp
This PR is cherry-picking the change from PR #1539 into the `maint/maint-68` branch. (Cherry-picked from commit a1a1fafb7d1a0e1c9beee626b6b57e63c27b901b).
This PR fixes a bug in the changes for ICU-13845, for handling when the "Automatic DST" setting is OFF in the Control Panel.
It turns out that the offset value for the calculated time zone when the "Automatic DST" setting is turn off is wrong. The sign for the time zone offset is flipped. (It's positive when it should be negative, and vice-versa).
I think this was perhaps due to confusion about the value for the UTC offset, how POSIX style offsets are handled, and what is reported by the Win32 API `GetDynamicTimeZoneInformation`.
It seems that this issue was actually present in the original PR for ICU-13845 here: …
=> ICU-21465 Cherry-pick: Fix Windows Time Zone mapping when the Automatic DST setting is OFF to ICU 68.

.github/workflows/icu_ci.yml
This change modifies the GHA CI script in order to enable running on branches other than `master`, as we'll want to enable running the GHA CI on other `maint/maint-*` branches going forward (i.e.: for ICU 69).
Related PR which back-ports to ICU 68 is here: #1546
=> ICU-21473 Enable GHA CI on maint/maint* branches and on any pull-requests

.github/workflows/icu_ci.yml, icu4c/source/test/depstest/dependencies.txt
This change backports the new GitHub Actions script to the `maint/maint-68` branch, which replaces the Travis CI builds.
(Thanks to @gnrunge for porting the Travis builds!)
This change ports the changes from the following two ICU tickets:
- https://unicode-org.atlassian.net/browse/ICU-21434
- https://unicode-org.atlassian.net/browse/ICU-21450
This PR includes changes from the following commits:
- 8078ae4937ac507b20dc613fb739d29a1c887d15
- 38125f3c5065791e5e396556cb9b4c67ed97898a
- e5a3f2baa7af6cfd7488b5e0144b1a5f562b085b
- c7ea02fccadc29ffdf3ad24c70dddd1ddffea2f8
Note: There are multiple commits in this PR, as I needed to adjust the branch settings to enable running the GHA CI on the `maint/maint-68` branches, and also disable the LayoutEx build, which was disabled by default in ICU 69. …
=> ICU-21473 Backport GitHub Actions (GHA) script to ICU 68 (replaces Travis CI)

icu4c/source/common/uresbund.cpp, icu4c/source/test/cintltst/cloctst.c, icu4c/source/test/cintltst/cloctst.h
When calling APIs like `uloc_getDisplayLanguage`, if the input locale ID has `/` (the `RES_PATH_SEPARATOR` value) then the resource look-up code ends up in an infinite loop.
For example, the following code will never return:
```c++
UErrorCode status = U_ZERO_ERROR;
const char* localeNameTemp = "/"; // RES_PATH_SEPARATOR
uloc_getDisplayLanguage(localeNameTemp, localeNameTemp, NULL, 0, &status);
```
The `do {...} while` loop in `ures_getByKeyWithFallback` calls `res_findResource`, but it never checks to see if the returned resource is `RES_BOGUS`, meaning that for some paths it will never terminate. (Thanks to am11 for doing the initial investigation into this issue.)
This PR also includes a test case for the issue. Note that there is nothing really "tested" by the test case, as the test is …
=> ICU-21449 Infinite loop can occur with locale IDs that contain RES_PATH_SEPARATOR

icu4c/source/common/uchar.cpp, icu4c/source/common/uprops.h
and some underused character constants
https://unicode-org.atlassian.net/browse/ICU-21461
It turned out that the gc macros were not used. (They probably were used some time ago.)
There were also some adjacent character constants (as enum constants) that are less useful now that we can use Unicode character literals. I removed some that were used in only one or two places.
=> ICU-21461 uprops.h: remove unused gc macros

icu4c/source/data/misc/units.txt, icu4c/source/i18n/units_converter.cpp, icu4c/source/i18n/units_converter.h, icu4c/source/test/testdata/cldr/units/unitPreferencesTest.txt, icu4c/source/test/testdata/cldr/units/unitsTest.txt, icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitConverter.java, icu4j/main/shared/data/icudata.jar, icu4j/main/shared/data/icutzdata.jar, icu4j/main/tests/core/src/com/ibm/icu/dev/data/cldr/units/unitPreferencesTest.txt, icu4j/main/tests/core/src/com/ibm/icu/dev/data/cldr/units/unitsTest.txt
This updates ICU code to match [CLDR-14232 Change blood glucose measures to be compatible](https://github.com/unicode-org/cldr/pull/951) and [CLDR-14232 regenerate unit test data](https://github.com/unicode-org/cldr/pull/987).
* This units.txt was generated from units.xml in cldr, not in cldr-staging, because cldr-staging has not been updated since 16 December.
Closes: icu-units#126
=> ICU-21472 Update ICU to support latest CLDR units updates (ofglucose, new constants)

icu4c/source/common/dictbe.cpp
The wordsMatched conditional gave the misleading impression that only the first "first word" candidate that was followed by a dictionary word would be marked, but because the wordsMatched declaration is inside the while loop, every "first word" candidate that's followed by a dictionary word is marked (resulting in the shortest and not the longest first candidate that's followed by a second dictionary word).
After making the change, the comment felt like it made more sense, so I didn't modify it in this change.  If anyone feels like it should change or if clarification should be made somewhere of what the result of this loop is, I'm open to making additional changes to clarify.
=> ICU-21179 Clean up unused code in the RBBI dictbe

icu4c/source/i18n/unicode/measfmt.h, icu4c/source/i18n/units_complexconverter.cpp, icu4c/source/test/intltest/measfmttest.cpp, icu4c/source/test/intltest/numbertest_api.cpp, icu4j/main/classes/core/src/com/ibm/icu/text/MeasureFormat.java, icu4j/main/classes/core/src/com/ibm/icu/util/MeasureUnit.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/MeasureUnitTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
- N/A Documentation is changed or added
Closes: https://github.com/icu-units/icu/issues/38
=> ICU-21284 More MeasureFormatTest and NumberFormatterApiTest test cases

icu4c/source/i18n/formattedval_sbimpl.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/FormattedValueStringBuilderImpl.java, icu4j/main/classes/core/src/com/ibm/icu/text/ListFormatter.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/FormattedValueTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/ListFormatterTest.java
This PR ports https://github.com/unicode-org/icu/pull/1425 to ICU4J.
=> ICU-21351 Don't coalesce adjacent list formatter fields in ICU4J

icu4c/source/i18n/number_output.cpp, icu4c/source/i18n/unicode/numberrangeformatter.h
=> ICU-21275 Remove obsolete functions from numberrangeformatter.h

icu4c/source/i18n/units_converter.cpp, icu4c/source/i18n/units_converter.h, icu4c/source/test/intltest/units_test.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitsConverter.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/impl/UnitsTest.java
Closes: https://github.com/icu-units/icu/issues/24
=> ICU-21349 Add UnitsConverter.getConversionInfo()

icu4c/source/common/unicode/uniset.h, icu4c/source/common/unicode/uset.h, icu4c/source/common/uniset.cpp, icu4c/source/common/uset.cpp, icu4c/source/test/cintltst/usettest.c, icu4c/source/test/intltest/usettest.cpp, icu4j/main/classes/core/src/com/ibm/icu/text/UnicodeSet.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/lang/UnicodeSetTest.java
and fix a bug in Java UnicodeSet.retain(String) which added the string even if the set did not contain it before,
and some drive-by API doc fixes/clarifications
https://unicode-org.atlassian.net/browse/ICU-13702
See the [API proposal](https://docs.google.com/document/d/1SsQkNxM9RiqeEtts0IhVAl6TuTEVsrGGGXXYVYkaCd4/edit#heading=h.ao6zu9x4p1gf)
=> ICU-13702 add missing API functions

icu4c/source/i18n/number_fluent.cpp, icu4c/source/i18n/number_formatimpl.cpp, icu4c/source/i18n/number_longnames.cpp, icu4c/source/i18n/number_longnames.h, icu4c/source/i18n/number_microprops.h, icu4c/source/i18n/number_output.cpp, icu4c/source/i18n/number_roundingutils.h, icu4c/source/i18n/number_skeletons.cpp, icu4c/source/i18n/number_usageprefs.cpp, icu4c/source/i18n/number_utypes.h, icu4c/source/i18n/unicode/numberformatter.h, icu4c/source/test/intltest/intltest.cpp, icu4c/source/test/intltest/numbertest.h, icu4c/source/test/intltest/numbertest_api.cpp, tools/cldr/cldr-to-icu/src/main/resources/ldml2icu_locale.txt
Closes: icu-units#111
Progress:
- N/A support mixed unit gender - ICU-21494
- icu-units#138: correctly implement Lateral Inheritance (current implementation is a shortcut adequate for CLDR 39 data)
- icu-units#139: implement deriveComponent plural per rules (currently hard-coded, matches all CLDR 39 rules)
- icu-units#140: support gender when not using unit-width-full-name
- icu-units#141: support gender for built-in compound units (treat as not-builtin to get the builtin-per-builtin gender)
=> ICU-21123 Support unit inflections in ICU4C

icu4c/source/i18n/regexcmp.cpp, icu4c/source/test/testdata/regextst.txt
A regex pattern containing nested look-behind blocks could trigger an assertion
failure during pattern compilation. The problem was caused by an off-by-one
error in the code that computes an upper bound on the match length, needed
because look-behind expressions are constrained to not have unbounded match
length.
Nested look-behind blocks come into play because, when computing the maximum
match length of an outer block, any inner look-behind blocks are skipped over -
they do not directly contribute to the length matched by the outer block. The
problem was in the code that skips over these nested look-behind blocks.
=> ICU-21492 Fix regex compile assertion failure.

icu4c/source/common/cmemory.h
Both Clang and GCC will output warnings when they know a variable cannot be `NULL`/`nullptr`.
This causes the two `U_ASSERT` macros added to `uprv_memcpy` and `uprv_memmove` in ICU-21118 to generate a number of noisy warnings.
We can suppress these warnings for Clang and GCC. Though doing so is a bit tricky, as we can't use `#ifdef` or `#pragma` inside of a macro `#define` token-string. The resulting output from the #define isn't processed by the preprocessor again, so if we have anything like `#pragma` in the token-string, it effectively gets ignored.
However, it turns out that we can use the C99 `_Pragma` [feature ](https://gcc.gnu.org/onlinedocs/cpp/Pragmas.html)for this (thanks to @erik0686 for this tip!).
=> ICU-21499 Suppress warning about non-NULL addresses in uprv_memcpy and uprv_memmove

README.md
Since Travis CI is no longer used, the status badge in the top-level README should be replaced with one for GitHub Actions.
=> ICU-21474 Update top-level README status badge to replace Travis CI with GitHub Actions

icu4c/source/test/intltest/units_test.cpp
test runs with ICU stub data only.
=> ICU-21502 Adds status checks to test to prevent segmentation fault when

icu4c/source/data/locales/nn.txt, icu4c/source/data/unit/eu.txt, icu4c/source/data/unit/fr.txt, icu4c/source/data/unit/ro.txt, icu4j/main/shared/data/icudata.jar, icu4j/main/shared/data/icutzdata.jar
This integrates CLDR release-39-alpha3. The difference from CLDR release-39-alpha2 is really just:
- Some BRS passes, which normalized exemplars for "nn" (and then removed some as redundant). (The BRS passes also affected production data such as annotations, but those are not in ICU)
- The result of fixing [CLDR-14533](https://unicode-org.atlassian.net/browse/CLDR-14533),  which corrected some unit patterns
=> ICU-21480 integrate CLDR release-39-alpha3 to ICU trunk

icu4c/source/test/intltest/numbertest_api.cpp
This PR touches only ICU4C, because the equivalent ICU4J PR is nr 1597, which is not finished yet.
=> ICU-21480 Update French unit-times pattern in unit tests

icu4c/source/i18n/number_longnames.cpp
Waiting for https://github.com/unicode-org/icu/pull/1601 to fix French compound unit formatting.
=> ICU-20941 Fix uninitialized values: DerivedComponents' compound0_ and compound1_

docs/userguide/format_parse/numbers/index.md, icu4c/source/i18n/unicode/numberformatter.h, icu4c/source/i18n/unicode/unum.h, icu4c/source/i18n/unicode/unumberformatter.h, icu4c/source/test/cintltst/cnumtst.c, icu4j/main/classes/core/src/com/ibm/icu/number/NumberFormatter.java, icu4j/main/classes/core/src/com/ibm/icu/number/NumberFormatterSettings.java
In this PR, I am addressing two docs-related issues related to NumberFormatter, which were opened by @filmil and @richgillam.  PTAL and let me know if these improvements look good to you.
- https://unicode-org.atlassian.net/browse/ICU-21203
- https://unicode-org.atlassian.net/browse/ICU-21198
- https://unicode-org.atlassian.net/browse/ICU-21479
=> ICU-21203 ICU-21198 ICU-21479 Improve docs discoverability for NumberFormatter

icu4c/source/i18n/units_complexconverter.h, icu4j/main/classes/core/src/com/ibm/icu/impl/number/UnitConversionHandler.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/ComplexUnitsConverter.java, icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitsRouter.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/impl/UnitsTest.java
toString() now uses category, so `@SuppressWarnings("unused")` is no longer needed.
=> ICU-21349 ICU4J units cleanup: eclipse warnings, unsuppress one warning

icu4c/source/i18n/number_longnames.cpp, icu4c/source/i18n/number_longnames.h, icu4c/source/test/intltest/numbertest_api.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/PatternProps.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/LongNameHandler.java, icu4j/main/classes/core/src/com/ibm/icu/impl/number/MixedUnitLongNameHandler.java, icu4j/main/classes/core/src/com/ibm/icu/number/NumberFormatterImpl.java, icu4j/main/classes/core/src/com/ibm/icu/util/MeasureUnit.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
Closes: icu-units#146
Makes some simultaneous tweaks/fixes to ICU4C.
Commit history, pre-squash: https://github.com/hugovdm/icu/tree/pr1597/presquash
* I have commits that have copy/pasted C++ code (that doesn't compile) followed by commits that convert that to Java, such that the finer-grained git commit history _might_ be easier to review than comparing it side-by-side with ICU4C.
=> ICU-20941 Port Arbitrary Units support from ICU4C to ICU4J

.github/pull_request_template.md
The change added in PR #1600 updated the GitHub PR template. However, the example ticket numbers used in the PR template end up getting turned into automatic links on every PR. 
This makes the comments instead, so the PR author can still see them, but now they won't get autolinked to the JIRA ticket.
=> ICU-21480 Update GitHub pull request template to prevent autolinking example ticket number.

icu4c/source/i18n/number_longnames.cpp, icu4c/source/test/intltest/numbertest_api.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/number/LongNameHandler.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
Fixes icu-units#140.
Individual commits were:
1. fe6e96c486 Add (failing) tests for gender for not-full-width
2. 5b11e64881 Opportunistically flesh out getInflectedMeasureData docs.
3. 99356c448f ICU4J: catch MissingResourceException only, instead of all Exceptions
4. b24232f8df (tag: pr1617/presquash) Explicitly fetch gender for all MeasureUnit data loads
Arguably 2 and 3 are a little bit out of scope for this PR - piggybacking? We talked about the Exception vs MissingResourceException thing before: I clearly changed my mind, opting for more idiomatic Java, and aiming for a bit more consistency within the file too (no generic Exception catching).
=> ICU-21123 Support FormattedNumber::getGender() for "short" and "narrow" formatting too

icu4c/source/common/locid.cpp
uprv_strcmp is strcmp which return int by C++ standard
On arm64-v8a or other implementation strcmp may return positive int > 127 and cause the cast to int8_t as negative number.
Return only 0, 1, -1 to solve the issue.
=> ICU-21521 Fix cast of uprv_strcmp

icu4c/source/test/intltest/numbertest_api.cpp, icu4j/main/classes/core/src/com/ibm/icu/number/NumberFormatterSettings.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
closes: https://github.com/icu-units/icu/issues/144
=> ICU-21349 calling .usage("") should unset the existing usage

icu4c/source/common/rbbiscan.cpp, icu4c/source/test/intltest/rbbitst.cpp, icu4c/source/test/intltest/rbbitst.h, icu4j/main/classes/core/src/com/ibm/icu/text/RBBIRuleBuilder.java, icu4j/main/classes/core/src/com/ibm/icu/text/RBBIRuleScanner.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/rbbi/RBBITest.java
Return error in rbbi parser while the rule text contains unpaired surrogate char
=> ICU-21127 Error when rbbi got unpaired surrogate char

icu4j/main/classes/core/src/com/ibm/icu/impl/ICUDebug.java
ICUDebug seemed to check Java version whether it's 1.4 or higher. The code referencing the version is already gone. We also no longer support Java 1.3 runtime since long time ago. Remove the unused code checking Java version.
=> ICU-21507 Removing unused class initializer code

docs/userguide/strings/index.md
Fix some broken markdown formatting in `userguide/strings/index.md`.
=> ICU-21416 Fix markdown formatting in userguide/strings

docs/processes/release/tasks/updating-measure-unit.md, docs/userguide/dev/sync/custom.md, docs/userguide/dev/sync/index.md, docs/userguide/icudata.md, docs/userguide/locale/resources.md, docs/userguide/packaging/index.md, docs/userguide/packaging/plug-ins.md
Sorry I took so long to get to this.
**Currently serving this branch:** https://hugovdm.github.io/icu/
See links at:
* https://hugovdm.github.io/icu/userguide/dev/sync/custom.html
* https://hugovdm.github.io/icu/userguide/dev/sync/index.html
* https://hugovdm.github.io/icu/userguide/icudata.html
* https://hugovdm.github.io/icu/userguide/locale/resources.html
* https://hugovdm.github.io/icu/userguide/packaging/index.html
* https://hugovdm.github.io/icu/userguide/packaging/plug-ins.html
* https://hugovdm.github.io/icu/processes/release/tasks/updating-measure-unit.html
Method for finding relevant links, run in the docs/ directory:
$ rgrep '\.\./\.\./' . | grep -v '([./_a-z]*\.md)'
I was initially thinking to not also change processes/release/tasks/updating-measure-unit.md - but I changed my …
=> ICU-21313 UserGuide: use absolute GitHub links for links outside docs/

icu4c/source/i18n/ucal.cpp
ucal_openTimeZones(UErrorCode*) used to call TimeZone::createEnumeration(), which does not return UErrorCode. TimeZone::createEnumeration() internally calls TZEnumeration::create(USystemTimeZoneType, const char*, const int32_t*, UErrorCode&), but it internally defines and eats UErrorCode. To set error status properly in ucal_openTimeZones(UErrorCode*), we should use TimeZone::createTimeZoneIDEnumeration(USystemTimeZoneType, const char*, const int32_t*, UErrorCode&), which is wrapped by ucal_openTimeZoneIDEnumeration(USystemTimeZoneType, const char*, const int32_t*, UErrorCode*), with UCAL_ZONE_TYPE_ANY, null region/offset.
Same thing applied to ucal_openCountryTimeZones(const char*, UErrorCode*).
=> ICU-20918 ucal_openTimeZones() to call ucal_openTimeZoneIDEnumeration()

icu4j/main/tests/core/src/com/ibm/icu/dev/test/timezone/TimeZoneTest.java
The test code was written long time ago. Java 1.3 TimeZone did not have getDSTSavings() method. The test code compares DST saving of Lord_Howe between ICU and JDK, and calling getDSTSavings() through reflection for 1.3 compatibility. This is no longer necessary and replaced with regular method call.
=> ICU-21207 Remove unnecessary reflection call

icu4j/main/classes/core/src/com/ibm/icu/number/NumberRangeFormatterSettings.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberRangeFormatterTest.java
Port of https://github.com/unicode-org/icu/pull/1466 to NumberRangeFormatter
=> ICU-21397 Allow null to unset options in Java NumberRangeFormatter

icu4c/source/test/intltest/itrbnf.cpp, icu4c/source/test/intltest/itrbnf.h, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/RbnfTest.java
Per suggestion from George Rhoten, add tests to verify that RBNF spellout behaves the same way for "no" and "nb" after the parent change in earlier CLDR data integrations. Apparently aliasing does not work normally for RBNF, but parent inheritance does seem to, in this case at  least.
=> ICU-21480 brs 69rc, add tests to verify that rbnf spellout is the same for no,nb

icu4c/source/i18n/unicode/ucal.h
In UTimeZoneLocalOption enum, when U_HIDE_DRAFT_API is defined, provide a dummy internal value so enum is not empty. I did not see a precedent for this anywhere else.
=> ICU-21532 In UTimeZoneLocalOption enum, add dummy value if U_HIDE_DRAFT_API

icu4c/source/common/uloc.cpp, icu4c/source/test/intltest/loctest.cpp, icu4c/source/test/testdata/structLocale.txt
1. For COUNTRIES/COUNTRIES_3:
a. Added `XK / XXK  Kosovo`; although in ISO 3166 this is user-defined, it is valid in CLDR and has wide currency (and an accepted 3-letter code).
b. The following missing 2-letter codes (and corresponding 3-letter codes) are all exceptionally reserved in ISO 3166, but valid in CLDR; two do not have reserved 3-letter codes, so I used codes beginning with X. We only have locales that use the first 3, so I just added those:
```
DG DGA Diego Garcia
EA XEA Ceuta, Melilla
IC XIC Canary Islands
AC ASC Ascension Island
CP CPT Clipperton Island
TA TAA Tristan da Cunha
```
2. For LANGUAGES/LANGUAGES_3: The following were all in the main list but are now deprecated in CLDR (“mo” is also deprecated in ISO 639), so moved them to the deprecated section of the arrays (note …
=> ICU-21341 for getISO codes, add some CLDR-valid regions, remove some CLDR-invalid langs

.github/workflows/icu_ci.yml, icu4c/source/test/hdrtst/Makefile.in, tools/scripts/uconfig_vars_test.py
subsequently sets each of the UCONFIG_NO_XXX flags to '1' (exceptions apply)
and runs the ICU4C unit tests and the header test. Afterwards all
UCONFIG_NO_XXX flags are set to '1' and unit tests and header test
are executed.
To allow concurrent execution and reduce total run time, the script provides
the option to execute only the unit tests or only the header test.
=> ICU-21323 Automates the uconfig variation BRS tasks. The test

icu4c/source/i18n/unicode/basictz.h, icu4c/source/i18n/unicode/calendar.h, icu4c/source/i18n/unicode/measunit.h, icu4c/source/i18n/unicode/numberformatter.h, icu4c/source/i18n/unicode/numberrangeformatter.h, icu4c/source/i18n/unicode/unum.h, icu4c/source/i18n/unicode/unumberformatter.h, icu4c/source/i18n/unicode/unumberrangeformatter.h, icu4c/source/i18n/unicode/vtzone.h
Adjusted nonstable API guard conditionals.
- Included more items in #ifndef U_HIDE_INTERNAL_API
- Broke some #ifndef U_HIDE_DRAFT_API into multiple sections for (likely) different version tags; removed redundant #ifndef U_HIDE_DRAFT_API
- Gave explicit numeric values to UNumberUnitWidth enum values to prevent problems when new enum values are added or when compiling with U_HIDE_DRAFT_API defined.
- Removed no-longer-applicable #ifndef U_HIDE_DRAFT_API around inline impl of a @stable method
=> ICU-21480 brs 69rc, adjust nonstable API macros

icu4c/source/test/perf/normperf/NormPerf.pl, icu4c/source/test/perf/normperf/NormPerf_r.pl, icu4c/source/test/perf/perldriver/Output.pm, icu4c/source/test/perf/ubrkperf/UBrkPerf_r.pl, icu4c/source/test/perf/ustrperf/StringPerf.pl, icu4c/source/test/perf/ustrperf/StringPerf_r.pl
evaluates to the empty string and the result files are missing the
perf test name as a result. E.g. '_Mar_16_155820.html' instead of
'unisetperf_Mar_16_155820.html'.
Not obvious why the regex was even created since it doesn't seem
necessary because the name of the caller doesn't require additional
parsing. The particular code is from 2002, maybe changes in Perl
account for the issue(?)
=> ICU-21520 Housekeeping: Fixes typos in name of test data file; removes a regex that

tools/commit-checker/check.py
ICU-20233, and pursuant to CLDR-14520
- improve checks for CLDR resolutions
- update batch fetch from 50 to 100
- do not show no-commit tickets under illegal-state
- add navigation
- use numeric IDs for status, resolution, types with constants
(`S_`*, `R_`*, `I_`*)
fix bugs from CLDR-14224
- do not show not-in-query issues as open
- cache single-issue queries
- give information on each problem as to what it is
- put 'review' in a separate section (not counted in Problems)
- more detailed fix info under each issue
- fix section headings, always show component, add nocopyright option
- sort open issues by componnent
- sort the 'review' list
ICU-20444:
- exclude (via git-cherry) any commits already cherry picked to the branch.
- used a workaround to …
=> ICU-20233 tool: improvements to commit checker for CLDR

icu4c/source/common/locid.cpp, icu4c/source/test/intltest/loctest.cpp, icu4j/main/classes/core/src/com/ibm/icu/util/ULocale.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/ULocaleTest.java
Use subdivisionAlias when len is 2 by appending "zzzz" per changes to
UTS35 in https://github.com/unicode-org/cldr/pull/1132
=> ICU-21550 Add zzzz to subdivision if len==2

icu4c/source/common/putil.cpp
clang 11 throws an error when using undefined variables starting with
TARGET_OS_, and TARGET_OS_SIMULATOR is missing in earlier versions
of macOS, so the code would not compile without an additional guard.
See also ICU-13440.
=> ICU-21513 check if TARGET_OS_SIMULATOR has been defined

icu4c/source/i18n/measunit_impl.h
Moving template after declaration of the MeasureUnitImpl
=> ICU-21563 Fix delete-incomplete on windows

icu4c/source/common/locid.cpp, icu4c/source/common/uloc_tag.cpp, icu4c/source/test/intltest/tzfmttst.cpp
Fix a few warnings that were found while running the samples check BRS item for MSVC.
=> ICU-21546 BRS69GA Fix warnings from running the samples with MSVC.

icu4j/main/classes/core/src/com/ibm/icu/impl/StringSegment.java, icu4j/main/classes/core/src/com/ibm/icu/number/NumberSkeletonImpl.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/impl/StringSegmentTest.java
and remove hashCode() because of now-missing equals() and because
StringSegment is mutable and documented as not suitable for HashMaps
=> ICU-21561 rename StringSegment.equals() to contentEquals()

icu4c/source/common/filteredbrk.cpp, icu4c/source/test/testdata/rbbitst.txt, icu4j/main/classes/core/src/com/ibm/icu/impl/SimpleFilteredSentenceBreakIterator.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/rbbi/rbbitst.txt
Result.matches() is an insufficient guard for Result.getValue().
I simplified the match loop so that there is only one place for checking hasValue() and recording a match.
It did not fail in C++ because the assertion is commented out there because it's in a public header file -- but the C++ code was bug-compatible with Java.
Other bug fixes: Neither implementation was thread-safe for copies/clones used in parallel threads.
- In Java, changed clone() to clone the fields (which are all stateful).
- In C++, made the worker function use stack-local copies of the trie iterator objects so that the shared ones remain const, and changed the data refcount to an atomic int.
=> ICU-21459 properly guard BytesTrie.Result.getValue()

tools/cldr/cldr-to-icu/pom.xml
This PR replaces https://github.com/unicode-org/icu/pull/1672.
Dependabot bumped to 29.0-jre, but there is a CVE with version 29, so we'll want to bump to version 30.0 instead.
=> ICU-21576 Bump guava from 27.1-jre to 30.0-jre

icu4c/source/common/locid.cpp, icu4c/source/test/intltest/loctest.cpp, icu4c/source/test/intltest/loctest.h, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/ULocaleTest.java
=> ICU-21539 Fix getUnicodeKeywords to skip non keys

icu4c/source/common/locid.cpp, icu4c/source/test/intltest/loctest.cpp, icu4c/source/test/intltest/loctest.h
Edge cases not fixed in assign and move assign operator
while the locale is long and call setKeywordValue with incorrect
keyword/values.
=> ICU-21587 Fix memory bug w/ baseName

README.md
The Cygwin build was moved from AppVeyor to Azure CI in PR #1694.
This change removes the AppVeyor entry from the top-level Readme file as well.
=> ICU-21535 Remove AppVeyor from top-level Readme

docs/userguide/layoutengine/index.md
The fd.o harfbuzz link currently goes to the github repo, which is a bit less documentation-ish than the github.io page.
Add link to icu-le-hb.
Wait, JIRA?
=> ICU-21577 doc/layoutengine: update harfbuzz link; + icu-le-hb link

icu4c/source/common/lstmbe.cpp
Remove LocalUResourceBundlePointer fDictRes which shadowed the real
UUResourceBundle*.
ICU-21569 fix assert
=> ICU-21569 Remove extra LocalUResourceBundlePointer

.ci-builds/.azure-pipelines.yml
There was a recent update the Azure CI Ubuntu 18.04 build bot image which causes the C++14 Debug build bot to fail in the tests with a segfault.
We initially thought this was related to ICU-changes, but it turns out that it was a change to the build bot image itself.
Using the work-around from this thread to remove GCC 11 fixes the issue.
See: https://github.com/actions/virtual-environments/issues/3376
=> ICU-21615 Work-around Azure CI build bot issue on Ubuntu 18.04

icu4c/source/common/lstmbe.cpp, icu4c/source/test/intltest/lstmbetst.cpp
Remember the Bundle in LSTMData and close in the destructor
because fName is pointing to string data inside rb.
=> ICU-21569 LSTM fix resource issue.

.ci-builds/.azure-pipelines.yml
This increases the timeout to 3 hours and separates the build/test steps in the Cygwin CI build. This attempts to address the potential timeouts and more clearly see what step is timing out.
=> ICU-21600 Increase timeout and separate build/test in Cygwin CI

icu4c/source/test/intltest/localebuildertest.cpp, icu4c/source/test/intltest/plurults.cpp
Fix typos in hard-coded test data, uncovered by a compiler upgrade to
clang version 12.0.0-1ubuntu1
=> ICU-21579 Compiler warning fixes.

icu4j/main/classes/core/src/com/ibm/icu/impl/RuleCharacterIterator.java, icu4j/main/classes/core/src/com/ibm/icu/impl/Utility.java, icu4j/main/classes/core/src/com/ibm/icu/impl/data/TokenIterator.java, icu4j/main/classes/core/src/com/ibm/icu/text/RBBIRuleScanner.java, icu4j/main/classes/core/src/com/ibm/icu/text/UnicodeSet.java, icu4j/main/classes/translit/src/com/ibm/icu/text/TransliteratorParser.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/rbbi/RBBITestExtended.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/UtilityTest.java
I had stumbled over some easily avoidable heap allocations during debugging.
As part of that, I am replacing Utility.unescapeAt(), which takes an `int[]` for offset input/output, with unescapeAndLengthAt(), which returns an int with both the result code point and the number of code units consumed.
=> ICU-21645 reduce heap allocations in unescape() and other parsing

icu4c/source/common/serv.cpp
There were a few more places (beyond what was called out in the bug) that I changed to use `LocalPointer` in order to prevent leaks if an OOM error occurs.
=> ICU-21644 Use LocalPointer in ICUService::getKey to prevent memory leaks.

.ci-builds/.azure-exhaustive-tests.yml, .ci-builds/.azure-pipelines.yml, .ci-builds/.azure-valgrind.yml
This is related to the upstream issue: https://github.com/actions/virtual-environments/issues/3287
> Traditional 5-years support of Ubuntu 16.04 by Canonical ends in April, 2021. To keep our environment updated and secured, we will remove Ubuntu 16.04 on September 20, 2021.
This change migrates the Azure CI build bots to use Ubuntu 18.04.
From discussion in the ICU-TC call, we'll use Ubuntu 18.04 for Azure CI. The GitHub Actions builds will continue to use the `ubuntu-latest`, which is Ubuntu 20.04.
=> ICU-21657 Update Azure CI build bots to use Ubuntu 18.04

icu4c/source/common/unicode/uniset.h, icu4c/source/common/unicode/uset.h, icu4c/source/common/unicode/usetiter.h, icu4c/source/common/uset.cpp, icu4c/source/test/cintltst/usettest.c, icu4c/source/test/intltest/csdetest.cpp, icu4c/source/test/intltest/transrt.cpp, icu4c/source/test/intltest/usettest.cpp, icu4c/source/test/intltest/usettest.h, icu4j/main/classes/core/src/com/ibm/icu/number/NumberFormatter.java, icu4j/main/classes/core/src/com/ibm/icu/text/UnicodeSet.java, icu4j/main/classes/core/src/com/ibm/icu/text/UnicodeSetIterator.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/lang/UnicodeSetTest.java, icu4j/main/tests/framework/src/com/ibm/icu/dev/util/UnicodeMapIterator.java, icu4j/main/tests/translit/src/com/ibm/icu/dev/test/translit/RoundTripTest.java
Also, UnicodeSetIterator is not intended for public subclassing, but there was one subclass in a unit test (in each of Java & C++). I rewrote that to compute a modified set rather than fiddle with the iterator, and removed protected @internal access in Java. In C++ we should discuss whether that's ok: ICU-21663 "UnicodeSetIterator: make protected members private"
This PR also addresses ICU-6553 "uset_charAt() / uset_size() inconsistent" via documentation and adding uset_getRangeCount().
=> ICU-21525 UnicodeSet.hasString(), UnicodeSetIterator.skipToStrings() & C API

icu4c/source/common/locid.cpp
I went looking in the code history for this one... it seems that when the code was refactored for ICU-12745 (see commit https://github.com/unicode-org/icu/commit/a5e61ccf5761159bc032f41d93bb3c59752c92fa) the `size` variable was no longer actually used. However, the usage of the variable wasn't fully cleaned-up, leading to this warning being generated by newer compilers that can detect if a variable is written to, but never read from.
This change removes the unused size variable and cleans up the comments.
[@jungshik FYI, since I think this ticket came from Chromium.]
=> ICU-21664 Fix set but unused warning in locid.cpp

icu4c/source/common/uresbund.cpp, icu4c/source/test/intltest/svccoll.cpp, icu4j/main/tests/collate/src/com/ibm/icu/dev/test/collator/CollationServiceTest.java
icu::Collator::getKeywordValues("collation", status) does not report "emoji" and "eor"
Use res_open intead of ures_openDirect  inside ures_getKeywordValues so it access the fallback resource in "root". This make it align to Java and will also count "emoji" and "eor" which is specified in "root" 
Also add test for both C++ and Java
Java behavior correctly without any fix.
=> ICU-21641 Fix "emoji" and "eor" for Collator::getKeywordValues

icu4c/source/common/uloc_tag.cpp, icu4c/source/test/intltest/loctest.cpp, icu4c/source/test/intltest/loctest.h
Only happen with legacy locale tag
=> ICU-21676 Fix strcpy buffer override in ultag_parse
