unicode-org/icu

- icu4c/source/common/brkeng.cpp
- icu4c/source/common/brkeng.h
- icu4c/source/common/dictbe.cpp
- icu4c/source/common/dictbe.h
- icu4c/source/common/lstmbe.cpp
- icu4c/source/common/lstmbe.h
- icu4c/source/common/rbbi_cache.cpp
- icu4c/source/test/intltest/lstmbetst.cpp
> ICU-21569 Propagate LSTM memory allocation issue

- icu4c/source/tools/genrb/reslist.cpp
> ICU-21588 Fix strncpy warning

- .ci-builds/.azure-valgrind.yml
> ICU-21244 Make Valgrind CI build/test check run on every Pull Request

- icu4c/source/common/lstmbe.cpp
Refactor the array allocation out of compute method and out of the loop
to reduce repeated malloc/free. Move all the array allocation code to
the same place before the loop.
This should dramatically reduce the number of calls to malloc/free.
> ICU-21569 LSTM Optimize memory usage.

- icu4c/source/test/intltest/lstmbetst.cpp
- icu4c/source/test/intltest/lstmbetst.h
> ICU-21569 LSTM Add test to test long string.

- icu4j/main/classes/core/src/com/ibm/icu/impl/breakiter/LSTMBreakEngine.java
> ICU-21569 LSTM: Remove Java 8 dependency

- icu4c/source/config/mh-aix-gcc
- icu4c/source/runConfigureICU
> ICU-21623 Removed linker flag -dexpall for AIX xlclang build.

- .github/workflows/icu_ci.yml
- icu4j/build.xml
> ICU-21626 Add CIs for Java 16

- .github/workflows/icu_ci.yml
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/rbbi/LSTMBreakEngineTest.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/rbbi/RBBILSTMTest.java
> ICU-21569 Fix Java7 breakage in LSTM & add Java7 CI

- icu4c/readme.html
- icu4j/readme.html
> ICU-21632 Fix links in readme.html files to respective User Guide pages

- icu4c/source/common/ubidiln.cpp
- icu4c/source/common/ucnvscsu.cpp
- icu4c/source/data/mappings/convrtrs.txt
- icu4c/source/test/intltest/bidiconf.cpp
- icu4j/main/classes/collate/src/com/ibm/icu/text/Collator.java
- icu4j/main/classes/collate/src/com/ibm/icu/text/RuleBasedCollator.java
- icu4j/main/classes/core/src/com/ibm/icu/lang/UCharacter.java
- icu4j/main/classes/core/src/com/ibm/icu/text/Bidi.java
- icu4j/main/classes/core/src/com/ibm/icu/text/BidiLine.java
- icu4j/main/classes/core/src/com/ibm/icu/text/Normalizer.java
- icu4j/main/classes/core/src/com/ibm/icu/text/Normalizer2.java
- icu4j/main/classes/core/src/com/ibm/icu/text/SCSU.java
- icu4j/main/classes/core/src/com/ibm/icu/text/UnicodeCompressor.java
- icu4j/main/classes/core/src/com/ibm/icu/text/UnicodeDecompressor.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/bidi/BiDiConformanceTest.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/normalizer/ConformanceTest.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/normalizer/UnicodeNormalizerConformanceTest.java
These relied on old redirects.
> ICU-21580 fix unicode.org/unicode/ URLs

- icu4j/main/classes/core/src/com/ibm/icu/impl/Utility.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/UtilityTest.java
> ICU-21645 test & fix unescapeAt(2 supp escapes)

- icu4c/source/i18n/calendar.cpp
- icu4c/source/i18n/smpdtfmt.cpp
Remove the usage of BasicTimeZone::getOffsetFromLocal
> ICU-21491 Remove internal usage of @internal BasicTimeZone::getOffsetFromLocal

- icu4j/main/classes/collate/src/com/ibm/icu/text/RuleBasedCollator.java
> ICU-21580 fix RuleBasedCollator doc typo, extra open brace

- icu4j/main/classes/core/src/com/ibm/icu/text/TimeZoneFormat.java
on line 1885, plus Eclipse auto changes
> ICU-21580 fix TimeZoneFormat doc typo, extra open brace

- icu4c/source/test/intltest/numbertest_api.cpp
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
> ICU-21659 Adding test for exabyte

- icu4c/source/common/unicode/localematcher.h
- icu4c/source/common/unicode/ucurr.h
- icu4c/source/common/unicode/utypes.h
- icu4c/source/i18n/unicode/dtitvfmt.h
- icu4c/source/i18n/unicode/measunit.h
- icu4c/source/i18n/unicode/nounit.h
- icu4c/source/i18n/unicode/numberformatter.h
- icu4c/source/i18n/unicode/numberrangeformatter.h
- icu4c/source/i18n/unicode/plurrule.h
- icu4c/source/i18n/unicode/udateintervalformat.h
- icu4c/source/i18n/unicode/unum.h
- icu4c/source/i18n/unicode/unumberformatter.h
- icu4c/source/i18n/unicode/unumberrangeformatter.h
- icu4c/source/i18n/unicode/upluralrules.h
> ICU-21581 Promoted @draft 68 APIs to stable

- icu4c/source/common/unicode/urename.h
> ICU-21581 BRS 70rc, update urename.h pass 1

- icu4j/perf-tests/README.txt
- icu4j/perf-tests/converterperf.pl
- icu4j/perf-tests/dateformatperf.pl
- icu4j/perf-tests/decimalformatperf.pl
- icu4j/perf-tests/normperf.pl
- icu4j/perf-tests/perftests.pl
- icu4j/perf-tests/ucharacterperf.pl
- icu4j/perf-tests/unicodesetperf.pl
> ICU-21638 re-enable some of the ICU4J performance tests

- icu4c/source/config/mh-solaris
> ICU-21680 Add -std flag when generating dependency information

- icu4c/source/common/unicode/ubidi.h
- [✅] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-21694
- [✅] Required: The PR title must be prefixed with a JIRA Issue number. 
- [✅] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [✅] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [✅] Issue accepted (done by Technical Committee after discussion)
- [✅] Tests included, if applicable (not applicable)
- [✅] API docs and/or User Guide docs changed or added, if applicable
> ICU-21694 ubidi.h sample code would not compile

- icu4j/main/classes/collate/src/com/ibm/icu/util/GlobalizationPreferences.java
- icu4j/main/classes/core/src/com/ibm/icu/number/FormattedNumber.java
- icu4j/main/classes/core/src/com/ibm/icu/number/NumberFormatterSettings.java
- icu4j/main/classes/core/src/com/ibm/icu/text/DateIntervalFormat.java
- icu4j/main/classes/core/src/com/ibm/icu/text/DecimalFormat.java
- icu4j/main/classes/core/src/com/ibm/icu/text/PluralRules.java
- icu4j/main/classes/core/src/com/ibm/icu/util/ICUInputTooLongException.java
- icu4j/main/classes/core/src/com/ibm/icu/util/LocaleMatcher.java
- icu4j/main/classes/core/src/com/ibm/icu/util/MeasureUnit.java
- icu4j/main/classes/core/src/com/ibm/icu/util/NoUnit.java
> ICU-21581 BRS#18 Promote @draft ICU4J API elements from version 68 to @stable

- icu4c/source/common/uresbund.cpp
- icu4c/source/test/cintltst/udatpg_test.c
- icu4c/source/test/intltest/dtptngts.cpp
> ICU-21202 Fixed error in alias resolution in uresbund.cpp.

- icu4c/source/common/unicode/localebuilder.h
> ICU-21729 Fix setLanguageTag doc matching Java

- icu4c/source/test/cintltst/cldrtest.c
Lingering exhaustive test failure, need to separately skip the month names exemplar test (for sd_Deva) in addition to the day names exemplar test (for mai, sd_Deva)
> ICU-21581 lingering exhaustive fail, need to separately skip sd_Deva month name exemplar test

- icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/RegionTest.java
> ICU-21584 Fixed Java7 build error in earlier fix.

- icu4c/source/i18n/number_decimalquantity.cpp
- icu4c/source/test/intltest/numbertest_api.cpp
> ICU-21693 Fix FormattedNumber::toDecimalNumber on 0

- icu4j/main/shared/licenses/LICENSE
> ICU-21581 Update ICU4J LICENSE file

- icu4c/source/common/rbbiscan.h
- icu4c/source/i18n/calendar.cpp
- icu4c/source/i18n/csrmbcs.cpp
- icu4c/source/test/cintltst/cdtdptst.c
- icu4c/source/test/cintltst/cdtrgtst.c
- icu4c/source/test/cintltst/cintltst.c
- icu4c/source/test/intltest/dtfmttst.cpp
- icu4c/source/test/intltest/dtifmtts.cpp
- icu4c/source/test/intltest/dtptngts.cpp
- icu4c/source/test/intltest/numrgts.cpp
- icu4c/source/test/intltest/plurfmts.cpp
- icu4c/source/test/intltest/plurults.cpp
- icu4c/source/test/intltest/regextst.cpp
- icu4c/source/test/intltest/sdtfmtts.cpp
- icu4c/source/test/intltest/selfmts.cpp
- icu4c/source/tools/icuinfo/icuinfo.cpp
- icu4j/main/classes/core/src/com/ibm/icu/lang/UCharacterEnums.java
- icu4j/main/classes/core/src/com/ibm/icu/util/CompactByteArray.java
- icu4j/main/classes/core/src/com/ibm/icu/util/CompactCharArray.java
- icu4j/tools/misc/src/com/ibm/icu/dev/tool/charsetdet/mbcs/BIG5Tool.java
- icu4j/tools/misc/src/com/ibm/icu/dev/tool/charsetdet/mbcs/EUCTool.java
- tools/scripts/reticket
- tools/unicodetools/com/ibm/rbm/docs/RBReporter.html
This PR fixes typos from letters d to i. They were considerably less than the other pull requests I've done like this, since we had a contributor help with this a lot :) This greatly reduced the amount of remaining Typos.
> ICU-21555 Fix typos in repo from letter d to i

- icu4c/source/common/uresbund.cpp
- icu4c/source/common/uresdata.h
- icu4c/source/common/uresimp.h
- icu4c/source/test/cintltst/crestst.c
- icu4c/source/test/cintltst/creststn.c
- icu4c/source/test/cintltst/creststn.h
- icu4c/source/test/intltest/restsnew.cpp
- icu4c/source/test/intltest/restsnew.h
- icu4c/source/tools/genrb/derb.cpp
> ICU-20769 refactor UResourceBundle.fResData & init_resb_result()

- icu4c/source/test/intltest/measfmttest.cpp
- icu4c/source/test/intltest/units_test.cpp
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/MeasureUnitTest.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/impl/UnitsTest.java
closes: https://github.com/icu-units/icu/issues/152
> ICU-21730 Check unit aliases support.

- icu4c/source/i18n/units_complexconverter.cpp
- icu4c/source/test/cintltst/cdattst.c
- icu4c/source/test/cintltst/cintltst.c
- icu4c/source/test/cintltst/cintltst.h
- icu4c/source/test/intltest/intltest.cpp
- icu4c/source/test/intltest/plurults.cpp
- icu4c/source/test/intltest/rbbiapts.cpp
- icu4c/source/test/intltest/strtest.cpp
- icu4c/source/test/intltest/tzregts.cpp
This PR fixes a number of compiler warnings when building with MSVC.
> ICU-21579 Fix compiler warnings with MSVC.

- icu4c/source/i18n/measunit_impl.h
- icu4c/source/test/intltest/measfmttest.cpp
- icu4c/source/test/intltest/numbertest_api.cpp
- icu4j/main/classes/core/src/com/ibm/icu/impl/units/SingleUnitImpl.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/MeasureUnitTest.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
Fixes https://github.com/icu-units/icu/issues/154
> ICU-21551 Fixing unit prefix normalization order to match LDML spec

- .ci-builds/.azure-pipelines.yml
- .github/workflows/icu_ci.yml
- icu4j/build.xml
- icu4j/main/tests/localespi/.classpath
- icu4j/main/tests/localespi/src/com/ibm/icu/dev/test/localespi/DateFormatSymbolsTest.java
- icu4j/main/tests/localespi/src/com/ibm/icu/dev/test/localespi/DateFormatTest.java
- icu4j/main/tests/localespi/src/com/ibm/icu/dev/test/localespi/DecimalFormatSymbolsTest.java
- icu4j/main/tests/localespi/src/com/ibm/icu/dev/test/localespi/NumberFormatTest.java
- icu4j/main/tests/localespi/src/com/ibm/icu/dev/test/localespi/TestUtil.java
- icu4j/main/tests/localespi/src/com/ibm/icu/dev/test/localespi/TimeZoneNameTest.java
> ICU-21038 Run ICU4J localespiCheck as a part of CI build

- tools/commit-checker/check.py
> ICU-21727 Commit Checker: add Reviewer: header

- docs/userguide/icu4c/build.md
> ICU-21741 remove redundant html tag: </pre>

- .gitignore
> ICU-21630 Ignore .DS_Store files

- .ci-builds/.azure-pipelines.yml
> ICU-21734 Add -Wsuggest-override to  Build only WarningsAsErrors buildbot  

- icu4c/source/test/intltest/units_data_test.cpp
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/impl/UnitsTest.java
closes: https://github.com/icu-units/icu/issues/129
> ICU-21730 Port `testGetPreferencesFor` ICU4C tests to ICU4J

- icu4c/source/test/cintltst/cloctst.c
> ICU-20870 Fix breakage on UCONFIG_NO_FORMATTING

- icu4c/source/i18n/number_skeletons.cpp
- icu4c/source/i18n/number_skeletons.h
- icu4c/source/test/intltest/numbertest.h
- icu4c/source/test/intltest/numbertest_api.cpp
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
> ICU-21654 Fix skeleton output for rounding increment

- docs/userguide/icu4c/faq.md
- docs/userguide/icu4c/packaging.md
> ICU-21752 fix wrong link of howtouseicu

- icu4c/source/test/intltest/numbertest.h
- icu4c/source/test/intltest/numbertest_range.cpp
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberRangeFormatterTest.java
> ICU-21675 Add Infinity and NaN tests for NumberRangeFormatter

- icu4c/source/i18n/number_decimalquantity.cpp
- icu4c/source/i18n/number_decimalquantity.h
- icu4c/source/test/intltest/numbertest.h
- icu4c/source/test/intltest/numbertest_api.cpp
- icu4j/main/classes/core/src/com/ibm/icu/impl/number/DecimalQuantity_AbstractBCD.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
> ICU-21668 Fix nickel rounding with away-from-zero rounding mode

- icu4c/source/i18n/measunit_extra.cpp
- icu4c/source/i18n/measunit_impl.h
- icu4c/source/i18n/units_router.cpp
- icu4c/source/test/intltest/numbertest_api.cpp
- icu4c/source/test/intltest/units_data_test.cpp
- icu4j/main/classes/core/src/com/ibm/icu/impl/units/MeasureUnitImpl.java
- icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitsData.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/impl/UnitsTest.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
closes: https://github.com/icu-units/icu/issues/130
> ICU-21656 fix wrong matching categories.

- icu4c/source/test/intltest/numfmtst.cpp
- icu4c/source/test/intltest/numfmtst.h
- icu4j/main/classes/core/src/com/ibm/icu/number/NumberPropertyMapper.java
- icu4j/main/classes/core/src/com/ibm/icu/text/DecimalFormat.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/NumberFormatTest.java
> ICU-20425 Strip trailing zeros from double rounding increment

- icu4c/source/i18n/decimfmt.cpp
- icu4c/source/i18n/number_currencysymbols.cpp
- icu4c/source/i18n/number_decimfmtprops.cpp
- icu4c/source/i18n/number_decimfmtprops.h
- icu4c/source/i18n/number_formatimpl.cpp
- icu4c/source/i18n/number_formatimpl.h
- icu4c/source/i18n/number_mapper.cpp
- icu4c/source/i18n/number_mapper.h
- icu4c/source/i18n/number_microprops.h
- icu4c/source/i18n/number_patternmodifier.cpp
- icu4c/source/i18n/number_patternmodifier.h
- icu4c/source/i18n/number_patternstring.cpp
- icu4c/source/i18n/number_patternstring.h
- icu4c/source/i18n/number_types.h
- icu4c/source/test/intltest/numbertest.h
- icu4c/source/test/intltest/numbertest_patternstring.cpp
- icu4c/source/test/intltest/numfmtst.cpp
- icu4c/source/test/intltest/numfmtst.h
- icu4j/main/classes/core/src/com/ibm/icu/impl/number/AffixPatternProvider.java
- icu4j/main/classes/core/src/com/ibm/icu/impl/number/CurrencyPluralInfoAffixProvider.java
- icu4j/main/classes/core/src/com/ibm/icu/impl/number/DecimalFormatProperties.java
- icu4j/main/classes/core/src/com/ibm/icu/impl/number/MicroProps.java
- icu4j/main/classes/core/src/com/ibm/icu/impl/number/MutablePatternModifier.java
- icu4j/main/classes/core/src/com/ibm/icu/impl/number/PatternStringParser.java
- icu4j/main/classes/core/src/com/ibm/icu/impl/number/PatternStringUtils.java
- icu4j/main/classes/core/src/com/ibm/icu/impl/number/PropertiesAffixPatternProvider.java
- icu4j/main/classes/core/src/com/ibm/icu/number/NumberFormatterImpl.java
- icu4j/main/classes/core/src/com/ibm/icu/text/DecimalFormat.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/NumberFormatTest.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/PatternStringTest.java
> ICU-21556 Support currency as decimal separator in patterns

- icu4c/source/i18n/number_decimalquantity.cpp
- icu4c/source/i18n/number_decnum.h
- icu4c/source/i18n/number_rounding.cpp
- icu4c/source/i18n/number_skeletons.cpp
- icu4c/source/i18n/number_utils.cpp
- icu4c/source/test/intltest/numbertest_range.cpp
- icu4c/source/test/intltest/numbertest_skeletons.cpp
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberSkeletonTest.java
> ICU-21675 Allow NaN and Infinity to appear in DecNum strings

- icu4c/source/i18n/formattedval_impl.h
- icu4c/source/i18n/formattedval_sbimpl.cpp
- icu4c/source/i18n/number_capi.cpp
- icu4c/source/i18n/numrange_capi.cpp
- icu4c/source/test/cintltst/unumberformattertst.c
- icu4c/source/test/intltest/numbertest.h
- icu4c/source/test/intltest/numbertest_range.cpp
> ICU-21683 ICU-21674 Clear state from UFormattedNumber[Range] in C API

- icu4c/source/i18n/units_converter.cpp
- icu4c/source/test/intltest/numbertest.h
- icu4c/source/test/intltest/numbertest_api.cpp
- icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitsConverter.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
closes: https://github.com/icu-units/icu/issues/82
> ICU-21544 Throw argument error when the units are not convertible.

- .github/workflows/icu_merge_ci.yml
maintenance branches only and adds GHA CI automation of BRS task 'Test ICU4J
with only little-endian ICU4C data', cf.:
https://unicode-org.github.io/icu/processes/release/tasks/integration.html#test-icu4j-with-only-little-endian-icu4c-data.
> ICU-21581 Creates a new workflow to be activated upon merge into main or

- icu4c/source/config/dist-data.sh
ex: icu4c-70_1-data-bin-b.zip
(was incorrectly "70.1" before)
> ICU-21764 icu-data-bin: fix filenames to nn_n

- icu4c/source/i18n/double-conversion-fast-dtoa.cpp
- icu4c/source/i18n/double-conversion-string-to-double.cpp
- icu4c/source/i18n/double-conversion-string-to-double.h
- icu4c/source/i18n/double-conversion-utils.h
- vendor/double-conversion/pull-from-upstream.sh
- vendor/double-conversion/upstream/Changelog
- vendor/double-conversion/upstream/double-conversion/bignum-dtoa.cc
- vendor/double-conversion/upstream/double-conversion/double-to-string.h
- vendor/double-conversion/upstream/double-conversion/fast-dtoa.cc
- vendor/double-conversion/upstream/double-conversion/fixed-dtoa.cc
- vendor/double-conversion/upstream/double-conversion/string-to-double.cc
- vendor/double-conversion/upstream/double-conversion/string-to-double.h
- vendor/double-conversion/upstream/double-conversion/strtod.cc
- vendor/double-conversion/upstream/double-conversion/utils.h
- vendor/double-conversion/upstream/test/cctest/test-conversions.cc
> ICU-21581 Update double-conversion

- docs/userguide/icu4c/build.md
Moving the ICU Download page notes on the Windows "ICU4C Platform Support" to the User Guide page on "Building ICU4C".
> ICU-21777 Move Windows "ICU4C Platform Support" notes to "Building ICU4C" User Guide page.

- .github/workflows/icu_ci.yml
Checks that the build process completes without failure and that the
generated data is identical with the data currently in the repository.
> ICU-21649 Adds build and execution of Unicode update tools to GHA CI.

- docs/userguide/icu4c/build.md
Cherry-picking PR #1890 into the "`maint/maint-70`" branch for 70.
*Previous description:*
Moving the ICU Download page notes on the Windows "ICU4C Platform Support" to the User Guide page on "Building ICU4C".
> ICU-21777 Cherry-Pick: Move Windows "ICU4C Platform Support" notes to "Building ICU4C" User Guide.

- icu4c/source/i18n/vtzone.cpp
Revise uses of UVector in vtzone.cpp to better handle memory allocation
failures.  This is one of an ongoing series of commits to address similar
problems with UVector usage throughout ICU.
The changes primarily involve switching uses of UVector::addElementX() to the
new adoptElement() or addElement() functions, as appropriate, and using
> ICU-21763 UVector cleanup in vtzone.cpp

- icu4c/source/tools/toolutil/toolutil.cpp
> ICU-21793 Fix ucptrietest golden diff

- icu4j/main/classes/core/src/com/ibm/icu/text/FormattedValue.java
Thanks to jdison16 at yahoo dot com for reporting the typo!
> ICU-21814 fix typo ConstrainableFieldPosition

- CONTRIBUTING.md
> ICU-21824 add a basic CONTRIBUTING.md

- icu4c/source/common/uvectr32.cpp
- icu4c/source/common/uvectr32.h
> ICU-21819 Make all comparison operators const.

- icu4c/source/i18n/units_complexconverter.cpp
This PR is an alternative to the older #1715 - which we could not merge due to the CLA being unsigned.
> ICU-21613 Fix undefined behaviour in ComplexUnitsConverter::applyRounder

- icu4c/source/tools/icuexportdata/icuexportdata.cpp
> ICU-21762 Export Script_Extensions data in icuexportdata tool

- icu4c/source/common/dictbe.cpp
- icu4c/source/common/dictbe.h
- icu4j/main/classes/core/src/com/ibm/icu/impl/breakiter/BurmeseBreakEngine.java
- icu4j/main/classes/core/src/com/ibm/icu/impl/breakiter/CjkBreakEngine.java
- icu4j/main/classes/core/src/com/ibm/icu/impl/breakiter/KhmerBreakEngine.java
- icu4j/main/classes/core/src/com/ibm/icu/impl/breakiter/LaoBreakEngine.java
- icu4j/main/classes/core/src/com/ibm/icu/impl/breakiter/ThaiBreakEngine.java
> ICU-21847 Move UnicodeSet to stack in constructor

- icu4c/source/configure
- icu4c/source/configure.ac
> ICU-13543 Do not remove -std=c++11 from compiler flags on Solaris

- icu4c/source/common/ubrk.cpp
- icu4c/source/common/ucnv.cpp
- icu4c/source/common/unicode/ubrk.h
- icu4c/source/common/unicode/ucnv.h
- icu4c/source/i18n/ucol.cpp
- icu4c/source/i18n/unicode/ucol.h
- icu4c/source/test/cintltst/capitst.c
- icu4c/source/test/cintltst/capitst.h
- icu4c/source/test/cintltst/ccapitst.c
> ICU-21894 A modern version of ucol_safeClone and ucnv_safeClone API

- icu4c/source/common/ucasemap.cpp
- icu4c/source/common/ustrcase.cpp
- icu4c/source/test/intltest/strcase.cpp
- icu4j/main/classes/core/src/com/ibm/icu/impl/CaseMapImpl.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/lang/UCharacterCaseTest.java
Currently done for ICU4J, will do C++ port(s) if logic & code seem correct.
> ICU-21141 Fix titlecase of accented Dutch ij digraph

- docs/userguide/transforms/general/index.md
> ICU-21849 Fix Broken Link from General Transforms / Regular Expressions to Rules Tutorial

- icu4c/source/i18n/number_rounding.cpp
- icu4c/source/i18n/number_skeletons.cpp
- icu4c/source/i18n/unicode/numberformatter.h
- icu4c/source/test/intltest/numbertest.h
- icu4c/source/test/intltest/numbertest_api.cpp
- icu4j/main/classes/core/src/com/ibm/icu/number/FractionPrecision.java
- icu4j/main/classes/core/src/com/ibm/icu/number/NumberSkeletonImpl.java
- icu4j/main/classes/core/src/com/ibm/icu/number/Precision.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
> ICU-21886 Make rounding priority consistent with ECMA-402

- docs/userguide/icu_data/index.md
> ICU-21814 Fix broken links in icu_data/index.md

- icu4c/LICENSE
- icu4j/main/shared/licenses/LICENSE
> ICU-21900 BRS71 Update license files

- icu4c/source/common/ucasemap.cpp
- icu4c/source/common/ustrcase.cpp
- icu4c/source/test/intltest/strcase.cpp
- icu4j/main/classes/core/src/com/ibm/icu/impl/CaseMapImpl.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/lang/UCharacterCaseTest.java
> ICU-21919 Fix fuzzer bug (buffer overflow) in Dutch accented IJ titlecase

- icu4c/source/common/unicode/ubrk.h
- icu4c/source/common/unicode/uniset.h
- icu4c/source/common/unicode/uset.h
- icu4c/source/i18n/unicode/basictz.h
- icu4c/source/i18n/unicode/measunit.h
- icu4c/source/i18n/unicode/numberformatter.h
- icu4c/source/i18n/unicode/rbtz.h
- icu4c/source/i18n/unicode/simpletz.h
- icu4c/source/i18n/unicode/ucal.h
- icu4c/source/i18n/unicode/unum.h
- icu4c/source/i18n/unicode/unumberformatter.h
- icu4c/source/i18n/unicode/vtzone.h
> ICU-21900 Promote all @draft ICU 69 APIs to @stable ICU 69

- icu4c/source/data/misc/currencyNumericCodes.txt
- icu4j/main/shared/data/icudata.jar
- tools/currency/src/com/ibm/icu/dev/tool/currency/NumericCodeData.java
> ICU-21900 BRS71 Updating currency numeric code data.

- icu4c/source/test/intltest/numbertest_api.cpp
- icu4j/main/classes/core/src/com/ibm/icu/number/Precision.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
> ICU-21881 TrailingZeroDisplay + RoundingMode

- icu4c/source/test/intltest/incaltst.cpp
- icu4c/source/test/intltest/numbertest_decimalquantity.cpp
- icu4c/source/test/intltest/plurults.cpp
- icu4c/source/test/intltest/ustrtest.cpp
Fixing warnings found while running the ICU samples as part of the BRS tasks.
> ICU-21900 Fix issues found while running samples.

- icu4c/source/i18n/number_decimalquantity.cpp
- icu4c/source/i18n/number_decimalquantity.h
- icu4c/source/i18n/number_mapper.cpp
- icu4c/source/i18n/number_patternstring.cpp
- icu4c/source/i18n/number_rounding.cpp
- icu4c/source/i18n/number_roundingutils.h
- icu4c/source/i18n/number_skeletons.cpp
- icu4c/source/i18n/number_skeletons.h
- icu4c/source/i18n/unicode/numberformatter.h
- icu4c/source/test/intltest/numbertest_api.cpp
- icu4c/source/test/intltest/numbertest_decimalquantity.cpp
- icu4c/source/test/intltest/numfmtst.cpp
- icu4j/main/classes/core/src/com/ibm/icu/number/Precision.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
> ICU-21908 Exact Rounding Increment

- icu4c/source/samples/Makefile.in
- icu4c/source/samples/case/ucase.c
- icu4c/source/samples/citer/citer.cpp
- icu4c/source/samples/coll/coll.cpp
- icu4c/source/samples/datecal/cal.cpp
- icu4c/source/samples/dtitvfmtsample/Makefile
- icu4c/source/samples/dtitvfmtsample/dtitvfmtsample.cpp
- icu4c/source/samples/dtptngsample/Makefile
- icu4c/source/samples/dtptngsample/dtptngsample.cpp
- icu4c/source/samples/plurfmtsample/Makefile
- icu4c/source/samples/plurfmtsample/plurfmtsample.cpp
- icu4c/source/samples/readme.txt
- icu4c/source/samples/strsrch/strsrch.cpp
> ICU-21900 Fix ICU4C sample build and execution

- .github/workflows/icu_ci.yml
> ICU-21816 Add ICU4C samples check to workflow for BRS "Test C Samples"

- icu4j/main/classes/core/src/com/ibm/icu/number/FractionPrecision.java
- icu4j/main/classes/core/src/com/ibm/icu/number/NumberFormatter.java
- icu4j/main/classes/core/src/com/ibm/icu/number/NumberRangeFormatter.java
- icu4j/main/classes/core/src/com/ibm/icu/number/Precision.java
- icu4j/main/classes/core/src/com/ibm/icu/util/BasicTimeZone.java
- icu4j/main/classes/core/src/com/ibm/icu/util/MeasureUnit.java
- icu4j/main/classes/core/src/com/ibm/icu/util/RuleBasedTimeZone.java
- icu4j/main/classes/core/src/com/ibm/icu/util/SimpleTimeZone.java
- icu4j/main/classes/core/src/com/ibm/icu/util/VTimeZone.java
- [ x Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
> ICU-21900 ICU4J: Promote all '@draft ICU 69' to '@stable'

- icu4c/source/i18n/number_output.cpp
- icu4c/source/i18n/unicode/numberformatter.h
- icu4c/source/i18n/unicode/unounclass.h
- icu4c/source/test/intltest/numbertest.h
- icu4c/source/test/intltest/numbertest_api.cpp
- icu4j/main/classes/core/src/com/ibm/icu/number/FormattedNumber.java
- icu4j/main/classes/core/src/com/ibm/icu/util/NounClass.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
> ICU-21379 Add getNounClass and enum NounClass

- icu4c/source/i18n/number_decimalquantity.cpp
- icu4c/source/i18n/number_decimalquantity.h
- icu4c/source/test/intltest/numbertest.h
- icu4c/source/test/intltest/numbertest_decimalquantity.cpp
- icu4j/main/classes/core/src/com/ibm/icu/impl/number/DecimalQuantity.java
- icu4j/main/classes/core/src/com/ibm/icu/impl/number/DecimalQuantity_AbstractBCD.java
- icu4j/main/classes/core/src/com/ibm/icu/impl/number/DecimalQuantity_DualStorageBCD.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/impl/number/DecimalQuantity_SimpleStorage.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/DecimalQuantityTest.java
> ICU-21322 Add parse and format methods for DecimalQuantity with exponent

- icu4c/source/io/ustdio.cpp
See https://unicode-org.atlassian.net/browse/ICU-21805
> ICU-21805 Remove useless check

- icu4c/source/i18n/units_complexconverter.h
- icu4j/main/classes/core/src/com/ibm/icu/impl/units/ComplexUnitsConverter.java
> ICU-21936 Make the internal units converters public

- icu4c/source/common/ucasemap.cpp
https://unicode-org.atlassian.net/browse/ICU-21815
ICU 71: code warnings/version updates
> ICU-21815 Remove unused line

- tools/commit-checker/check.py
It was not successfully filtering issues with type Task or User Guide.
Committed against the BRS ticket.
> ICU-21900 Fix issue filtering in commit checker

- icu4c/APIChangeReport.html
- icu4c/APIChangeReport.md
- tools/release/java/src/main/java/com/ibm/icu/dev/tools/docs/StableAPI.java
> ICU-21900 ICU4C 71 change report

- icu4c/source/common/unicode/localematcher.h
> ICU-21844 Fix variable shadowing

- icu4c/source/test/cintltst/cbiditst.c
- icu4c/source/test/cintltst/cloctst.c
- icu4c/source/test/cintltst/cnormtst.c
- icu4c/source/test/cintltst/utexttst.c
Test code for coverage of the C API functions listed in the ticket.
> ICU-21875 improve C API coverage

- icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
> ICU-21900 BRS71 Cleanup import statements in ICU4J

- icu4c/source/i18n/number_longnames.cpp
- icu4c/source/test/intltest/numbertest.h
- icu4c/source/test/intltest/numbertest_api.cpp
- icu4j/main/classes/core/src/com/ibm/icu/impl/number/LongNameHandler.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
> ICU-21840 Fix formatting Aliases

- icu4c/source/i18n/formattedval_sbimpl.cpp
- icu4c/source/test/cintltst/ulistfmttest.c
- icu4c/source/test/intltest/listformattertest.cpp
- icu4c/source/test/intltest/listformattertest.h
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/ListFormatterTest.java
> ICU-21871 Make behavior consistent on list format of empty strings

- docs/userguide/collation/customization/index.md
- docs/userguide/dev/codingguidelines.md
- docs/userguide/icu/design.md
- docs/userguide/icu4c/build.md
- docs/userguide/icu_data/buildtool.md
- docs/userguide/io/ustdio.md
> ICU-21814 Fix small typos in docs/userguide

- .ci-builds/.azure-pipelines.yml
- icu4c/source/tools/icuexportdata/icuexportdata.cpp
> ICU-21762 Export Script_Extensions with --all flag in icuexportdata

- docs/userguide/icu4c/index.md
- icu4c/source/data/makedata.mak
- icu4c/source/data/makedata.vcxproj
- icu4c/source/data/makedata.vcxproj.filters
- icu4c/source/data/makedata_uwp.vcxproj
These references should have been removed in ICU-20489 and ICU-21420.
Take the opportunity to update the doc as well.
> ICU-21967 Remove obsolete references in makedata VS projects

- icu4c/source/common/locid.cpp
Need to check the status in the loop to avoid heap-buffer-overflow
> ICU-21994 Fix heap-buffer-overflow

- icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitsConverter.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/impl/UnitsTest.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
> ICU-21959 Update stale Jira tickets in ICU4J TODOs

- docs/processes/release/tasks/publish/index.md
> ICU-21959 Online demos how to update

- icu4c/source/data/mappings/iso-8859_10-1998.ucm
- icu4c/source/data/mappings/iso-8859_11-2001.ucm
- icu4c/source/data/mappings/iso-8859_14-1998.ucm
Merges the changes in the Unicode MAPPINGS file headers into the ICU file headers. (Links to both sets of files in the ICU ticket.)
Preserves differences due to different file formats.
> ICU-22007 remove outdated terms of use from Unicode conversion files

- icu4c/source/i18n/formatted_string_builder.cpp
- icu4c/source/test/intltest/formatted_string_builder_test.cpp
> ICU-22005 Fix int32 overflow in FormattedStringBuilder

- icu4c/source/allinone/Build.Windows.PlatformToolset.props
> ICU-21945 Add support for Visual Studio 2022

- .github/workflows/icu_merge_ci.yml
> ICU-22037 Adds performance tests for ICU forward and backward

- docs/userguide/layoutengine/paragraph.md
https://sourceforge.net/p/icu/mailman/message/37657918/
> ICU-21959 Fix the URL to the icu-le-hb repository.

- tools/unicode/py/preparseucd.py
Starting with Unicode 15, Unicode data files may contain more than one `@missing` line, specifying a default property value not just for all of Unicode but potentially also other default values for certain code point ranges.
This change adjusts preparseucd.py to handle such additional lines.
For example, DerivedBidiClass.txt may contain lines like
```
```
For documentation see https://www.unicode.org/reports/tr44/tr44-29.html#Missing_Conventions
See also https://github.com/unicode-org/unicodetools/pull/267
> ICU-21980 parse multiple `@missing` lines

- icu4c/source/i18n/numrange_fluent.cpp
- icu4c/source/i18n/numrange_impl.cpp
- icu4c/source/test/intltest/numbertest.h
- icu4c/source/test/intltest/numbertest_range.cpp
- icu4j/main/classes/core/src/com/ibm/icu/number/NumberRangeFormatterImpl.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberRangeFormatterTest.java
> ICU-22017 Fix numbering system resolution in NumberRangeFormatter

- icu4c/source/i18n/calendar.cpp
> ICU-22070 Return if UErrorCode is error in calendar.cpp

- icu4c/source/io/ufile.cpp
> ICU-22002 Fix for C++20 - don't undef __STRICT_ANSI__

- icu4c/source/i18n/ulocdata.cpp
> ICU-22004 Avoid UBSan bug by casting only when success

- .ci-builds/.azure-pipelines.yml
- docs/processes/release/tasks/publish/index.md
> ICU-22061 71 Backport of #2121 to 71

- icu4c/source/i18n/unicode/unum.h
- icu4c/source/i18n/unum.cpp
- icu4c/source/test/cintltst/cnumtst.c
> ICU-22056 Add a new unum_hasAttribute() method.

- icu4c/source/tools/icuexportdata/icuexportdata.cpp
Testing is running the export, importing it into ICU4X and running the normalization and collation conformance tests there.
> ICU-22095 Export ICU4X normalization data with tries only without Unicode sets

- icu4c/source/tools/icuexportdata/icuexportdata.cpp
This is #2140 for the maint-71 branch.
Testing is running the export, importing it into ICU4X and running the normalization and collation conformance tests there.
> ICU-22095 backport Export ICU4X normalization data with tries only without Unicode sets

- .ci-builds/.azure-valgrind.yml
Increasing timeout for valgrind CI pipeline
- Total by 15 mins (60 to 75)
- Intl Tests by 15 mins (45 to 60)
> ICU-22074 Increase the valgrind CI timeout

- icu4c/source/tools/icuexportdata/icuexportdata.cpp
Testing is on the [ICU4X side](https://github.com/unicode-org/icu4x/pull/2371).
> ICU-22115 Merge passthrough and canonical combining class data into the NFD trie for ICU4X

- icu4j/APIChangeReport.html
- icu4j/main/classes/core/src/com/ibm/icu/lang/UCharacter.java
- icu4j/main/classes/core/src/com/ibm/icu/lang/UProperty.java
- icu4j/main/classes/core/src/com/ibm/icu/text/UnicodeSet.java
- icu4j/main/classes/core/src/com/ibm/icu/text/UnicodeSetIterator.java
> ICU-21957 ICU4J API status and change report for ICU 72

- icu4j/main/classes/core/src/com/ibm/icu/number/NumberFormatterSettings.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/UtilityTest.java
> ICU-21957 BRS72 organize import statements

- icu4c/source/data/misc/currencyNumericCodes.txt
- icu4j/main/shared/data/icudata.jar
- icu4j/main/shared/data/icutzdata.jar
- tools/currency/src/com/ibm/icu/dev/tool/currency/NumericCodeData.java
> ICU-21957 BRS72 Updating currency numeric code data.

- icu4c/source/common/unicode/uchar.h
- icu4c/source/common/unicode/uniset.h
- icu4c/source/common/unicode/uset.h
- icu4c/source/common/unicode/usetiter.h
- icu4c/source/i18n/unicode/numberrangeformatter.h
- icu4c/source/i18n/unicode/udat.h
- icu4c/source/i18n/unicode/uformattedvalue.h
API promotions spreadsheet for ICU70: https://docs.google.com/spreadsheets/d/1BlD5EM9BH9I8VNnBPkqGqjg6VIYC99EYVqpmL9he-TI/edit#gid=0
> ICU-21958 ICU 70 API Promotions

- .ci-builds/.azure-pipelines.yml
> ICU-22114 Update pipeline workflows to use macOS-latest

- icu4j/main/classes/core/src/com/ibm/icu/text/DateIntervalFormat.java
It didn't compile. I copied it into test code, fixed it, and copied it back.
> ICU-21959 fix DateIntervalFormat general usage example

- icu4c/source/i18n/unicode/measunit.h
- icu4j/main/classes/core/src/com/ibm/icu/util/MeasureUnit.java
Add notes about future deprecation (and preferred replacement) to MeasureUnit createMetricTon/getMetricTon (ICU4C), METRIC_TON (ICU4J)
> ICU-22125 Add note about future deprecation to MeasureUnit createMetricTon/getMetricTon/METRIC_TON

- icu4c/source/i18n/hebrwcal.h
> ICU-22025 Rename the enum type for Hebrew calendar to Month

- icu4c/source/data/locales/lo.txt
- icu4c/source/data/locales/th.txt
- icu4c/source/data/misc/metadata.txt
- icu4c/source/data/misc/supplementalData.txt
- icu4j/main/shared/data/icudata.jar
- icu4j/main/shared/data/icutzdata.jar
- icu4j/main/shared/data/testdata.jar
- tools/cldr/cldr-to-icu/pom.xml
Integrate CLDR release-42-beta1 to ICU main for 72rc.
- Fixes personName spacing in Lao and Thai
- Fixes some language data (including adding en_Shaw_GB as a default content locale)
> ICU-21957 integrate CLDR release-42-beta1 to ICU main for 72

- icu4c/source/i18n/number_currencysymbols.cpp
- icu4c/source/i18n/number_currencysymbols.h
- icu4c/source/i18n/number_patternmodifier.cpp
- icu4c/source/i18n/number_patternstring.cpp
- icu4c/source/i18n/number_patternstring.h
- icu4c/source/i18n/numparse_affixes.cpp
- icu4c/source/i18n/numparse_affixes.h
- icu4c/source/test/cintltst/cnumtst.c
> ICU-20512 Add extra matchers to handle empty currency symbols

- icu4c/source/i18n/number_usageprefs.cpp
- icu4c/source/i18n/units_data.cpp
- icu4c/source/i18n/units_data.h
- icu4c/source/i18n/units_router.cpp
- icu4c/source/i18n/units_router.h
- icu4c/source/test/intltest/numbertest.h
- icu4c/source/test/intltest/numbertest_api.cpp
- icu4c/source/test/intltest/units_data_test.cpp
- icu4c/source/test/intltest/units_test.cpp
- icu4j/main/classes/core/src/com/ibm/icu/impl/number/UsagePrefsHandler.java
- icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitPreferences.java
- icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitsData.java
- icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitsRouter.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/impl/UnitsTest.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
> ICU-22122 Support Locale Tags (ms, mu and rg)

- icu4j/main/classes/core/src/com/ibm/icu/impl/ICUResourceBundle.java
- icu4j/main/classes/core/src/com/ibm/icu/impl/personname/FieldModifierImpl.java
- icu4j/main/classes/core/src/com/ibm/icu/impl/personname/PersonNameFormatterImpl.java
- icu4j/main/classes/core/src/com/ibm/icu/impl/personname/PersonNamePattern.java
- icu4j/main/classes/core/src/com/ibm/icu/text/PersonNameFormatter.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/PersonNameFormatterTest.java
> ICU-21957 BRS72 Cleanup import statements

- icu4c/source/common/unicode/platform.h
- icu4c/source/i18n/unicode/unum.h
Add header for U_HIDDEN with status tag; fix status tag for unum_hasAttribute
> ICU-21957 Fix status tags for U_HIDDEN, unum_hasAttribute

- icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitPreferences.java
> ICU-21957 Fixed java compiler warnings

- docs/userguide/transforms/general/index.md
Fix UserGuide link to info in Korean transliteration.
> ICU-21879 Fix UserGuide link to info in Korean transliteration

- docs/userguide/format_parse/datetime/index.md
> ICU-20894 Add UserGuide info on date pattern chars B, b

- icu4j/main/classes/core/src/com/ibm/icu/message2/PlainStringFormattedValue.java
> ICU-21957 Change the internal/deprecated javadoc tags

- docs/processes/release/tasks/docs.md
> ICU-21958 Improved process for Releasing ICU API Docs

- icu4c/source/i18n/unicode/displayoptions.h
> ICU-21958 Fix typo in displayoptions.h documentation

- docs/userguide/locale/resources.md
> ICU-22170 Fix typo in resource bundle documentation.

- icu4j/build.properties
> ICU-21958 BRS72GA Update version number

- tools/currency/build.xml
- tools/currency/readme.txt
> ICU-21958 BRS72 Updated ISO currency data URLs

- icu4c/source/tools/genrb/parse.cpp
> ICU-22177 Replace angular brackets in include with double quotes.

- icu4c/source/data/curr/hr.txt
- icu4c/source/data/curr/supplementalData.txt
- icu4j/main/shared/data/icudata.jar
- icu4j/main/shared/data/icutzdata.jar
- [x ] Required: Each commit message must be prefixed with a JIRA Issue number. 
Integrate CLR release-42-beta5 to ICU The only change is related to Croatian currency:
- EUR becomes valid from 2023-01-01, and HRK ceases to be valid on 2023-01-15.
- In `hr`, change the currency symbol for EUR from "EUR" to "€".
> ICU-21958 integrate CLDR release-42-beta5 to ICU main for 72

- docs/processes/rules_update.md
Replicates remaining doc-related change(s) from #746.
> ICU-22194 Fix typo in doc for BreakIterator rules update

- icu4c/source/runConfigureICU
@josephshen found that the help text here has the wrong word, and I dropped the ball on his PR #2217 :-(
> ICU-22194 runConfigureICU computer->compiler

- icu4c/source/tools/toolutil/writesrc.cpp
Second fix, see @barracuda156's comment https://github.com/unicode-org/icu/pull/2239#issuecomment-1304879911
> ICU-22191 writesrc.cpp: enable PRI formatting constants on all compilers

- icu4c/source/common/rbbiscan.cpp
- icu4c/source/common/ucnvisci.cpp
- icu4c/source/common/udata.cpp
- icu4c/source/common/uidna.cpp
- icu4c/source/common/uresbund.cpp
- icu4c/source/common/usprep.cpp
- icu4c/source/common/utext.cpp
- icu4c/source/i18n/calendar.cpp
- icu4c/source/i18n/dcfmtsym.cpp
- icu4c/source/i18n/dtitvinf.cpp
- icu4c/source/i18n/gregocal.cpp
- icu4c/source/i18n/regexcmp.cpp
- icu4c/source/i18n/search.cpp
- icu4c/source/i18n/usearch.cpp
- icu4c/source/i18n/uspoof_conf.cpp
- icu4c/source/io/uscanf_p.cpp
Fix "unsafe mix of type 'UBool' and type 'bool' in operation:
> ICU-22206 Fix unsafe mix of UBool

- icu4j/main/tests/core/src/com/ibm/icu/dev/test/calendar/CalendarRegressionTest.java
> ICU-22201 Add test to verify ICU-22043 on Java

- icu4c/source/test/cintltst/sprpdata.c
> ICU-22214 Fix set pointer to false in sprpdata.c

- icu4c/source/tools/genccode/genccode.c
- icu4c/source/tools/pkgdata/pkgdata.cpp
- icu4c/source/tools/toolutil/pkg_genc.cpp
- icu4c/source/tools/toolutil/pkg_genc.h
👋 
This is the associated PR to fix bug [ICU-22203](https://unicode-org.atlassian.net/browse/ICU-22203).
> ICU-22203 Windows: enable C-code generation with overridden entry point

- .github/workflows/icu_ci.yml
- .gitignore
- icu4j/maven-build/README.md
- icu4j/maven-build/local-maven-repo/com/ibm/icu/icudata/73.1-SNAPSHOT/icudata-73.1-SNAPSHOT.jar
- icu4j/maven-build/local-maven-repo/com/ibm/icu/icudata/73.1-SNAPSHOT/icudata-73.1-SNAPSHOT.pom
- icu4j/maven-build/local-maven-repo/com/ibm/icu/icudata/73.1-SNAPSHOT/maven-metadata-local.xml
- icu4j/maven-build/local-maven-repo/com/ibm/icu/icudata/maven-metadata-local.xml
- icu4j/maven-build/local-maven-repo/com/ibm/icu/icutzdata/73.1-SNAPSHOT/icutzdata-73.1-SNAPSHOT.jar
- icu4j/maven-build/local-maven-repo/com/ibm/icu/icutzdata/73.1-SNAPSHOT/icutzdata-73.1-SNAPSHOT.pom
- icu4j/maven-build/local-maven-repo/com/ibm/icu/icutzdata/73.1-SNAPSHOT/maven-metadata-local.xml
- icu4j/maven-build/local-maven-repo/com/ibm/icu/icutzdata/maven-metadata-local.xml
- icu4j/maven-build/local-maven-repo/com/ibm/icu/testdata/73.1-SNAPSHOT/maven-metadata-local.xml
- icu4j/maven-build/local-maven-repo/com/ibm/icu/testdata/73.1-SNAPSHOT/testdata-73.1-SNAPSHOT.jar
- icu4j/maven-build/local-maven-repo/com/ibm/icu/testdata/73.1-SNAPSHOT/testdata-73.1-SNAPSHOT.pom
- icu4j/maven-build/local-maven-repo/com/ibm/icu/testdata/maven-metadata-local.xml
- icu4j/maven-build/maven-icu4j-charset/README.md
- icu4j/maven-build/maven-icu4j-charset/pom.xml
- icu4j/maven-build/maven-icu4j-datafiles/README.md
- icu4j/maven-build/maven-icu4j-datafiles/pom.xml
- icu4j/maven-build/maven-icu4j-localespi/README.md
- icu4j/maven-build/maven-icu4j-localespi/pom.xml
- icu4j/maven-build/maven-icu4j-test-datafiles/README.md
- icu4j/maven-build/maven-icu4j-test-datafiles/pom.xml
- icu4j/maven-build/maven-icu4j/README.md
- icu4j/maven-build/maven-icu4j/create-fullLocaleNames.sh
- icu4j/maven-build/maven-icu4j/file-listing-helper.sh
- icu4j/maven-build/maven-icu4j/pom.xml
- icu4j/maven-build/pom.xml
> ICU-12811 Build ICU4J using Maven

- .github/workflows/icu_ci.yml
- icu4j/build.xml
- icu4j/main/classes/core/src/com/ibm/icu/ICUConfig.properties
- icu4j/main/classes/core/src/com/ibm/icu/impl/ICUConfig.java
- icu4j/main/classes/core/src/com/ibm/icu/impl/breakiter/CjkBreakEngine.java
- icu4j/main/classes/core/src/com/ibm/icu/impl/breakiter/MlBreakEngine.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/rbbi/RBBITestExtended.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/rbbi/rbbitst.txt
> ICU-22100 Incorporate BudouX into ICU (Java)

- .github/workflows/icu_ci.yml
> ICU-22233 Use separate Bazel cache keys per OS

- icu4c/source/i18n/unicode/numberformatter.h
- icu4c/source/i18n/unicode/numberrangeformatter.h
> ICU-22222 Add explicit instantiation declarations

- icu4c/source/i18n/number_capi.cpp
- icu4c/source/i18n/unicode/usimplenumberformatter.h
- icu4c/source/test/cintltst/unumberformattertst.c
- icu4c/source/test/intltest/numbertest_simple.cpp
_No hurry to review this; I don't expect a review until January_
CC @Manishearth 
[ICU-22093]: https://unicode-org.atlassian.net/browse/ICU-22093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ICU-1234]: https://unicode-org.atlassian.net/browse/ICU-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ICU-1234]: https://unicode-org.atlassian.net/browse/ICU-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ICU-22093 Polish for SimpleNumberFormatter

- icu4c/source/i18n/gregoimp.cpp
Check the third argument and not set if it is a nullptr
> ICU-22058 make pointer argument in floorDivide optional

- icu4c/source/test/perf/collperf/collperf.cpp
> ICU-21833 Replace nullptr with 0 when assigning to UChar.

- icu4c/source/common/dictionarydata.h
- icu4c/source/common/lstmbe.h
- icu4c/source/common/normalizer2impl.h
> ICU-21833 Replace UChar with char16_t in C++ code.

- .ci-builds/.azure-exhaustive-tests.yml
Automate "Test ICU4J with only little-endian ICU4C data" as stated in https://unicode-org.github.io/icu/processes/release/tasks/integration.html#test-icu4j-with-only-little-endian-icu4c-data
> ICU-22257 Add "Test ICU4J with only little-endian ICU4C data"

- docs/processes/release/tasks/integration.md
> ICU-22257 BRS doc: J with little-endian data automatic

- docs/userguide/format_parse/datetime/index.md
> ICU-22194 Update DateTime skeleton docs with link to symbols table

- icu4c/source/tools/icuexportdata/icuexportdata.cpp
> ICU-22270 Add support for property and property value names/aliases in icuexport

- icu4c/source/i18n/unicode/dtptngen.h
- icu4c/source/i18n/unicode/numberformatter.h
- icu4c/source/i18n/unicode/udatpg.h
- icu4c/source/i18n/unicode/unum.h
> ICU-22220 ICU 73 API promotions (promoting ICU 71 and earlier)

- .ci-builds/.azure-exhaustive-tests.yml
Since the same work has been done in PR #1884 before.
> ICU-22257 Revert PR 2302 "Add "Test ICU4J with only little-endian ICU4C data""

- icu4c/source/i18n/ucol_res.cpp
- icu4c/source/test/intltest/regcoll.cpp
- icu4c/source/test/intltest/regcoll.h
> ICU-22277 correct collation error return of uninitialized length value while previous code return error

- icu4j/main/classes/core/src/com/ibm/icu/message2/MessageFormatter.java
> ICU-22194 Fixed javadoc error (self-closing element not allowed)

- docs/processes/release/tasks/integration.md
> ICU-22257 BRS doc: J with little-endian data automatic since ICU 70

- docs/processes/release/tasks/integration.md
> ICU-22262 Document environment test automation

- docs/processes/release/tasks/healthy-code.md
Just realize the task is already automated in 
.github/workflows/icu_ci.yml
as "icu4c-test-samples:" but we should document that.
> ICU-22291 doc automation of "Test samples (C) on Linux"

- icu4c/source/Doxyfile.in
- icu4c/source/common/unicode/caniter.h
- icu4c/source/common/unicode/casemap.h
- icu4c/source/common/unicode/char16ptr.h
- icu4c/source/common/unicode/edits.h
- icu4c/source/common/unicode/rbbi.h
- icu4c/source/common/unicode/simpleformatter.h
- icu4c/source/common/unicode/umachine.h
- icu4c/source/common/unicode/uniset.h
- icu4c/source/common/unicode/usetiter.h
- icu4c/source/i18n/unicode/coleitr.h
- icu4c/source/i18n/unicode/dtfmtsym.h
- icu4c/source/i18n/unicode/dtitvinf.h
- icu4c/source/i18n/unicode/regex.h
- icu4c/source/i18n/unicode/stsearch.h
- icu4c/source/i18n/unicode/tblcoll.h
> ICU-21833 Replace U_FINAL with final everywhere.

- icu4c/source/tools/icuexportdata/icuexportdata.cpp
Followup from https://github.com/unicode-org/icu/pull/2312
> ICU-22270 Add support for General_Category_Mask in icuexport

- icu4c/source/tools/icuexportdata/icuexportdata.cpp
Uplifts #2339 and #2340 (the latter has not been merged yet)
ALLOW_MANY_COMMITS=1
> ICU-22270 Uplift icuexport changes to maint

- icu4j/APIChangeReport.html
> ICU-22220 ICU4J API change report

- icu4c/APIChangeReport.html
- icu4c/APIChangeReport.md
- tools/release/java/src/main/java/com/ibm/icu/dev/tools/docs/StableAPI.java
> ICU-22220 ICU4C APIChangeReport for ICU73

- icu4j/main/classes/core/src/com/ibm/icu/text/DateTimePatternGenerator.java
- icu4j/main/classes/core/src/com/ibm/icu/text/NumberFormat.java
> ICU-22220 Update ICU4J API status for BRS frontloading

- tools/release/java/readme.txt
These instructions are slightly out of date and incomplete. Fixing them will make future updates easier.
> ICU-22220 Add a step to instructions and fix an obsolete path.

- icu4c/source/tools/icuexportdata/icuexportdata.cpp
> ICU-22270 expose uproperty values in icuexportdata (uplift)

- icu4c/LICENSE
- icu4j/main/shared/licenses/LICENSE
> ICU-22220 BRS73 Updating the Unicode data files and software license

- icu4j/main/classes/core/src/com/ibm/icu/text/UnicodeSet.java
> ICU-22299 deprecate redundant UnicodeSet.CASE

- icu4j/main/tests/collate/src/com/ibm/icu/dev/test/collator/CollationAPITest.java
- icu4j/main/tests/collate/src/com/ibm/icu/dev/test/collator/CollationMiscTest.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/calendar/JapaneseTest.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/CompactDecimalFormatTest.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/DateFormatRegressionTest.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/DateFormatTest.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/DateIntervalFormatTest.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/TimeUnitTest.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/serializable/FormatHandler.java
> ICU-22279 Fix invalid new Locale in testing

- icu4c/source/tools/icuexportdata/icuexportdata.cpp
> ICU-22256 Add helper code to dump Bidi_Mirroring_Glyph data to file

- icu4j/build.xml
- icu4j/main/tests/translit/src/com/ibm/icu/dev/util/ElapsedTimer.java
> ICU-12811 Fix cldrUtils (add ElapsedTime and UnicodeMap*)

- docs/userguide/icu_data/buildtool.md
Explains how to undo the omit-by-default change from PR #2365.
> ICU-22285 how to include gb2312 & big5han collation tailorings

- icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/CurrencyTest.java
Add unit tests for Croatia currency change from HRK to EUR... exactly as requested in ticket
> ICU-22186 Add unit tests for Croatia currency change from HRK to EUR

- icu4c/source/common/unicode/uchar.h
- icu4j/main/classes/core/src/com/ibm/icu/lang/UCharacter.java
Clarified C++ docs a bit, and replaced outdated docs in Java.
> ICU-12725 adjust API docs for new impl != JDK

- .ci-builds/.azure-post-merge-tests.yml
- docs/processes/release/tasks/healthy-code.md
> ICU-22301 Add azure CI tests to be run post merge

- icu4c/APIChangeReport.html
- icu4c/APIChangeReport.md
- icu4j/APIChangeReport.html
> ICU-22220 ICU 73 API Changes 4J & 4C

- icu4c/source/common/unicode/urename.h
Just adds one new exported function
> ICU-22220 BRS 73rc update urename.h pass 2

- icu4j/main/classes/core/src/com/ibm/icu/text/PersonName.java
- icu4j/main/classes/core/src/com/ibm/icu/text/SimplePersonName.java
> ICU-22220 BRS73 Fix API doc tagging problems

- icu4c/source/tools/icuexportdata/icuexportdata.cpp
Cherry-picking the change from https://github.com/unicode-org/icu/pull/2392 onto the maint/maint-72 branch
fyi @Manishearth
> ICU-22270 Fix hex number formatting in icuexportdata

- docs/userguide/boundaryanalysis/break-rules.md
- icu4c/source/common/rbbirb.cpp
- icu4c/source/common/rbbirb.h
- icu4c/source/common/rbbiscan.cpp
- icu4c/source/common/rbbitblb.cpp
- icu4j/main/classes/core/src/com/ibm/icu/text/RBBIRuleBuilder.java
- icu4j/main/classes/core/src/com/ibm/icu/text/RBBIRuleScanner.java
- icu4j/main/classes/core/src/com/ibm/icu/text/RBBITableBuilder.java
> ICU-22295 Remove deprecated RBBI LBCMNoChain option

- .github/workflows/icu_ci.yml
> ICU-22330 build and test ICU4J with Java 17

- docs/processes/release/tasks/docs.md
This adds steps to revise the table of API docs in README.md with updated version numbers for either the Dev or Released entries.
> ICU-22220 Add step for updating API Doc table

- docs/processes/release/tasks/publish/index.md
> ICU-22190 Add information about the KEYS file to the Publish document.

- tools/commit-checker/check.py
- support Umbrella ticket type (no commits)
- explain why commit policy was applied
> ICU-22341 commit checker: umbrella, explanations

- icu4c/source/test/intltest/dtifmtts.cpp
- icu4c/source/test/intltest/dtifmtts.h
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/DateIntervalFormatTest.java
> ICU-20926 Add tests for identity behavior in DateIntervalFormat

- .ci-builds/.azure-pipelines.yml
> ICU-22349 Bump the cygwin timeout to 50 minutes

- .ci-builds/.azure-pipelines.yml
> ICU-22373 Export segmentation dictionaries

- icu4c/source/i18n/units_data.cpp
- icu4c/source/test/intltest/numbertest.h
- icu4c/source/test/intltest/numbertest_api.cpp
- icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitPreferences.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
> ICU-22378 Fix temperature format ignoring -u-mu-fahrenhe

- icu4c/source/i18n/chnsecal.h
- icu4j/main/classes/core/src/com/ibm/icu/util/ChineseCalendar.java
Reusing a generic "Documentation bugs" issue.
> ICU-22323 Remove broken link from the Chinese Calendar documentation

- icu4c/source/common/unicode/locid.h
- icu4j/main/classes/core/src/com/ibm/icu/util/ULocale.java
> ICU-22371 Fix ULocale.getISOLanguages() API docs

- icu4c/source/common/unicode/ures.h
- icu4c/source/test/intltest/Makefile.in
- icu4c/source/test/intltest/intltest.vcxproj
- icu4c/source/test/intltest/intltest.vcxproj.filters
- icu4c/source/test/intltest/uchar_type_build_test.cpp
Cherry-pick commit 4fd9d6ce9a951e66e727b296138f22cd05479de1 from branch main to branch maint/maint-73.
> ICU-22356 Use ConstChar16Ptr to safely cast from UChar* to char16_t*

- icu4c/source/tools/icuexportdata/icuexportdata.cpp
> ICU-22372 Fix headers in icuexportdata

- icu4j/main/classes/core/src/com/ibm/icu/impl/ICUResourceBundleReader.java
- icu4j/main/classes/translit/src/com/ibm/icu/text/AnyTransliterator.java
- icu4j/main/classes/translit/src/com/ibm/icu/text/TransliteratorRegistry.java
It reduces the method runtime by approx. 60%.
> ICU-22390 Speed-up ICU4J Transliterator.<clinit>

- icu4c/source/tools/icuexportdata/icuexportdata.cpp
> ICU-22372 Fix headers in icuexportdata (Uplift)

- icu4c/source/tools/icuexportdata/icuexportdata.cpp
Uplifts https://github.com/unicode-org/icu/pull/2470
> ICU-22403 Uplift icuexportdata out-of-bounds fix

- icu4c/source/data/unidata/changes.txt
Adds a top section merged from the 15.0 change log and the CLDR 43 root collation update, with adjustments for 15.1.
As usual, this change log will be updated while we work through the steps. In particular, the separate "TODO" line usually moves to after what we have done so far.
FYI @eggrobin
> ICU-22404 changes.txt for Unicode 15.1

- icu4c/source/tools/gentest/gentest.c
> ICU-22396 Fix tool until ICU4J add Temporal Calendar API

- icu4j/maven-build/README.md
Include instruction of how to run one or multiple tests
> ICU-22409 Update README.md for Maven build

- icu4c/source/data/BUILDRULES.py
- icu4c/source/python/icutools/databuilder/__main__.py
> ICU-22405 Move coll_tree filter into data so it doesn't affect testdata

- docs/processes/release/tasks/publish/index.md
> ICU-22389 Add missing git lfs install to instructions.

- icu4c/source/i18n/ucol_res.cpp
- icu4c/source/test/intltest/collationtest.cpp
> ICU-22414 Fix bogus locale in collation res fallback

- tools/cldr/cldr-to-icu/README.md
- tools/cldr/cldr-to-icu/README.txt
> ICU-22323 Correct alt='ascii' paths, point Readme.txt to .md

- icu4c/source/i18n/reldatefmt.cpp
- icu4c/source/i18n/unicode/reldatefmt.h
- icu4c/source/i18n/unicode/ureldatefmt.h
> ICU-22260 Allow relative datetime formatting without context adjustment with UCONFIG_NO_BREAK_ITERATION

- icu4j/main/classes/core/src/com/ibm/icu/text/MessageFormat.java
> ICU-22426 Do not create nested StringBuilder when appending

- icu4c/source/i18n/fmtable.cpp
> ICU-22401 fix build on MSVC with cpp20

- icu4c/source/i18n/unicode/numberformatter.h
- icu4j/main/classes/core/src/com/ibm/icu/number/NumberFormatter.java
Is this enough? Suggestions on more places where it might be useful?
> ICU-20297 Improve discoverability of currency formatting

- icu4c/source/i18n/calendar.cpp
- icu4c/source/i18n/hebrwcal.cpp
- icu4c/source/test/intltest/caltest.cpp
> ICU-22446 Fix incorrect Hebrew ORDINAL MONTH bug

- icu4j/main/tests/core/src/com/ibm/icu/dev/test/calendar/IBMCalendarTest.java
Similar to changes to C++ in
https://github.com/unicode-org/icu/pull/2298
Fix post merge test breakages for https://github.com/unicode-org/icu/pull/2526
> ICU-22407 Suppress Calendar Consistency

- .gitignore
- icu4c/build_qnx/Makefile
- icu4c/build_qnx/build-hooks
- icu4c/build_qnx/linux-x86_64-o/GNUmakefile
- icu4c/build_qnx/nto-aarch64-le/GNUmakefile
- icu4c/build_qnx/nto-x86_64-o/GNUmakefile
- icu4c/source/configure
- icu4c/source/test/cintltst/Makefile.in
- icu4c/source/test/intltest/Makefile.in
- icu4c/source/test/iotest/Makefile.in
Add support for QNX 7.1 build and test
Build instruction for Ubuntu:
```bash
source <path-to-qnxsdp-env.sh>/qnxsdp-env.sh
rm $QNX_TARGET/aarch64le/usr/lib/libicu*
rm $QNX_TARGET/x86_64/usr/lib/libicu*
git clone https://github.com/chachoi/icu.git && cd icu/icu4c/build_qnx
JLEVEL=4 make install
```
[Test instruction](https://gitlab.com/qnx/libs/icu/-/wikis/Test-ICU)
cintltst, intltest, and iotest all pass on QNX 7.1.
> ICU-22363 Add support for QNX 7.1 build and test

- icu4c/build_qnx/Makefile
- icu4c/build_qnx/build-hooks
- icu4c/build_qnx/linux-x86_64-o/GNUmakefile
- icu4c/build_qnx/nto-aarch64-le/GNUmakefile
- icu4c/build_qnx/nto-x86_64-o/GNUmakefile
> ICU-22363 Add copyright notices to new QNX build files

- icu4j/maven-migration/README_MAVEN.md
- icu4j/maven-migration/demos/pom.xml
- icu4j/maven-migration/main/charset/pom.xml
- icu4j/maven-migration/main/collate/pom.xml
- icu4j/maven-migration/main/common_tests/pom.xml
- icu4j/maven-migration/main/core/pom.xml
- icu4j/maven-migration/main/currdata/pom.xml
- icu4j/maven-migration/main/framework/pom.xml
- icu4j/maven-migration/main/icu4j/pom.xml
- icu4j/maven-migration/main/langdata/pom.xml
- icu4j/maven-migration/main/localespi/pom.xml
- icu4j/maven-migration/main/pom.xml
- icu4j/maven-migration/main/regiondata/pom.xml
- icu4j/maven-migration/main/translit/pom.xml
- icu4j/maven-migration/pom.xml
- icu4j/maven-migration/samples/pom.xml
- icu4j/maven-migration/toMaven.sh
- icu4j/maven-migration/tools/build/pom.xml
- icu4j/maven-migration/tools/misc/pom.xml
- icu4j/maven-migration/unpack_jars.sh
Includes scripts to restructure files from the current structure to a maven one.
> ICU-22324 Mavenize ICU4J

- icu4c/source/common/loclikely.cpp
- icu4c/source/common/loclikelysubtags.cpp
- icu4c/source/test/cintltst/cloctst.c
> ICU-22466 Fix incorrect memory read while the locale is bogus

- icu4j/maven-migration/README_MAVEN.md
- icu4j/maven-migration/main/charset/pom.xml
- icu4j/maven-migration/main/core/pom.xml
- icu4j/maven-migration/main/framework/pom.xml
- icu4j/maven-migration/main/icu4j/pom.xml
- icu4j/maven-migration/pom.xml
- icu4j/maven-migration/toMaven.sh
- icu4j/maven-migration/tools/misc/pom.xml
- Symlinks to LICENSE, so that it is included in the .jar files
- Fixed version in the jar manifests (s/73/74/)
- Added Main-Class, Export-Package, some *-Title and *-Description to manifests
At this point the .jar files (including manifests) produced by ant / maven are byte to byte identical, except for some small differences that are expected and can be explained (will cover them in the email to the team)
> ICU-22324 Small fixes for script moving folders to maven structure

- icu4c/source/i18n/unicode/uspoof.h
- icu4c/source/i18n/uspoof.cpp
- icu4c/source/test/cintltst/spooftest.c
- icu4c/source/test/depstest/dependencies.txt
- icu4c/source/test/intltest/itspoof.cpp
- icu4c/source/test/intltest/itspoof.h
- icu4j/main/classes/core/src/com/ibm/icu/text/SpoofChecker.java
- icu4j/main/tests/core/src/com/ibm/icu/dev/test/text/SpoofCheckerTest.java
> ICU-22332 bidiSkeleton and LTR- and RTL-confusabilities

- icu4c/source/common/ulocale.cpp
- icu4c/source/common/ulocbuilder.cpp
> ICU-22365 call u_terminateChars in ULocale(Builder)?

- icu4j/maven-migration/pom.xml
> ICU-22324 Exclude tools/build from jdk > 8

- .github/workflows/scorecard.yml
Fix the Github Action failure by fixing typo in action's version number tag in #2521.
> ICU-22423 Fix version tag for OSSF Scorecard GH Action

- icu4c/source/i18n/unicode/displayoptions.h
- icu4c/source/i18n/unicode/formattednumber.h
- icu4c/source/i18n/unicode/numberformatter.h
- icu4c/source/i18n/unicode/udisplayoptions.h
- icu4c/source/i18n/unicode/unum.h
> ICU-22325 Promoted all @draft ICU 72 APIs to @stable ICU 72.

- icu4j/main/core/src/test/java/com/ibm/icu/dev/test/format/PersonNameConsistencyTest.java
> ICU-22478 Fix log spew in PersonNameConsistencyTest.

- icu4c/source/common/uloc_tag.cpp
- icu4c/source/test/intltest/loctest.cpp
> ICU-22497 Fix buffer-overflow READ for toLanguateTag

- icu4c/APIChangeReport.html
- icu4c/APIChangeReport.md
- icu4c/source/i18n/unicode/uspoof.h
> ICU-22325 Update ICU4C API Change Reports - frontload

- icu4c/source/common/brkeng.cpp
- icu4c/source/common/unicode/rbbi.h
- icu4c/source/test/intltest/rbbitst.cpp
> ICU-22342 Rename fillBreak to fillBreaks

- icu4c/source/common/uloc_tag.cpp
- icu4c/source/test/intltest/loctest.cpp
> ICU-22504 Fix buffer overflow write error

- icu4c/source/test/fuzzer/Makefile.in
- icu4c/source/test/fuzzer/calendar_fuzzer.cpp
> ICU-22479 Add fuzzer for Calendar API

- icu4c/source/test/fuzzer/Makefile.in
- icu4c/source/test/fuzzer/date_format_fuzzer.cpp
> ICU-22479 Add Fuzzer for DateFormat

- icu4c/source/test/fuzzer/Makefile.in
- icu4c/source/test/fuzzer/list_format_fuzzer.cpp
> ICU-22479 Add Fuzzer for ListFormat

- icu4c/source/test/fuzzer/date_format_fuzzer.cpp
> ICU-22509 Limit the dateStyle and timeStyle in fuzzer to only valid enum

- icu4j/main/core/src/test/java/com/ibm/icu/dev/test/format/PersonNameConsistencyTest.java
> ICU-22502 Fix TestPersonNames failure on Windows

- icu4j/main/core/src/main/java/com/ibm/icu/util/Calendar.java
- icu4j/main/core/src/main/java/com/ibm/icu/util/ChineseCalendar.java
- icu4j/main/core/src/main/java/com/ibm/icu/util/HebrewCalendar.java
- icu4j/main/localespi/pom.xml
- icu4j/pom.xml
- icu4j/releases_tools/api_reports.sh
- icu4j/releases_tools/cheatsheet.txt
- icu4j/stylesheet8.css
> ICU-22324 Mavenization, resolve some of the release tasks

- icu4c/source/i18n/calendar.cpp
Add field check for Calendar API. Either ignore invalid field or return with status code set to .U_ILLEGAL_ARGUMENT_ERROR
> ICU-22510 Fix Calendar API to ignore or reject invalid field.

- icu4j/APIChangeReport.html
- icu4j/main/core/src/main/java/com/ibm/icu/number/FormattedNumber.java
- icu4j/main/core/src/main/java/com/ibm/icu/number/NumberFormatterSettings.java
- icu4j/main/core/src/main/java/com/ibm/icu/text/DisplayOptions.java
> ICU-22325 BRS#19 ICU4J 74 Status and Change Report

- icu4c/source/i18n/reldatefmt.cpp
- icu4c/source/test/fuzzer/Makefile.in
- icu4c/source/test/fuzzer/relative_date_time_formatter_fuzzer.cpp
And also fix a bug by checking the unit
> ICU-22479 Add fuzzer for RelativeTimeFormatFuzzer

- icu4c/source/test/fuzzer/list_format_fuzzer.cpp
Add the testing for invalid type and width.
Also test formatStringsToValue
> ICU-22479 Enahnce the fuzzer for ListFormatter

- icu4c/source/common/uloc_tag.cpp
> ICU-22498 Write directly to sink (instead of into legacy buffers)

- icu4j/pom.xml
- icu4j/releases_tools/api_reports.sh
This should make the version update easier:
- run maven to update `<version>` in all projects (`mvn versions:set` or `mvn release:update-versions`, tbd)
- `icu.major.version` in the root pom
- three variables in `releases_tools/api_reports.sh`
Can also grep / search for `"Version update!"`
> ICU-22324 Mavenization, minimize the places that need a version

- icu4c/source/common/loclikely.cpp
- icu4c/source/common/ucurr.cpp
- icu4c/source/common/uresbund.cpp
- icu4c/source/i18n/calendar.cpp
- icu4c/source/i18n/collationruleparser.cpp
- icu4c/source/i18n/dtitvinf.cpp
- icu4c/source/i18n/dtptngen.cpp
- icu4c/source/i18n/rulebasedcollator.cpp
- icu4c/source/i18n/ucol_sit.cpp
> ICU-21289 Switch to using CharString for calling uloc_getKeywordValue()

- icu4c/source/i18n/reldatefmt.cpp
To avoid later unknown address in icu_74::UnicodeString::copyFrom
> ICU-22516 Return error in RelativeDateTimeFormatter if style is invalid

- icu4c/source/common/loclikely.cpp
- icu4c/source/common/locmap.cpp
- icu4c/source/common/locresdata.cpp
- icu4c/source/common/ucurr.cpp
- icu4c/source/common/uloc_tag.cpp
- icu4c/source/common/uresbund.cpp
- icu4c/source/i18n/calendar.cpp
- icu4c/source/i18n/ucol_sit.cpp
> ICU-21289 Switch to using CharString for calling uloc name functions

- icu4c/source/common/locmap.cpp
- icu4c/source/i18n/windtfmt.cpp
- icu4c/source/i18n/winnmfmt.cpp
> ICU-21289 Switch to using CharString for calling uloc_toLanguageTag()

- icu4c/source/common/ucurr.cpp
- icu4c/source/common/uloc.cpp
- icu4c/source/common/ulocimp.h
- icu4c/source/i18n/dayperiodrules.cpp
- icu4c/source/i18n/gender.cpp
- icu4c/source/i18n/plurrule.cpp
- icu4c/source/i18n/tmutfmt.cpp
> ICU-21289 Switch to using CharString for calling uloc_getParent()

- .github/workflows/maven.yaml
- icu4j/perf-tests/src/main/java/com/ibm/icu/dev/test/perf/PerfTest.java
- icu4j/pom.xml
- icu4j/tools/misc/src/main/java/com/ibm/icu/dev/tool/localeconverter/XLIFF2ICUConverter.java
- icu4j/tools/misc/src/main/java/com/ibm/icu/dev/tool/shared/UOption.java
- icu4j/tools/utilities-for-cldr/pom.xml
> ICU-22324 Mavenization, building the CLDR utilities

- docs/processes/release/tasks/versions.md
- icu4j/releases_tools/api_reports.sh
- icu4j/releases_tools/serial_test_data.sh
- icu4j/releases_tools/shared.sh
This corresponds to the `serialTestData` task in the Ant build
> ICU-22324 Mavenization, script to generate serial test data

- icu4c/source/i18n/unicode/uspoof.h
- icu4j/main/core/src/main/java/com/ibm/icu/text/SpoofChecker.java
> ICU-22332 document advanced usage of bidi confusability

- icu4c/source/common/unicode/docmain.h
New C “services” from https://htmlpreview.github.io/?https://github.com/unicode-org/icu/blob/main/icu4c/APIChangeReport.html#added
> ICU-22325 docmain ICU 74 new C services

- icu4c/source/i18n/double-conversion-double-to-string.cpp
- icu4c/source/i18n/double-conversion-double-to-string.h
- vendor/double-conversion/upstream/.github/workflows/ci.yml
- vendor/double-conversion/upstream/.github/workflows/scons.yml
- vendor/double-conversion/upstream/CMakeLists.txt
- vendor/double-conversion/upstream/Changelog
- vendor/double-conversion/upstream/SConstruct
- vendor/double-conversion/upstream/double-conversion/double-to-string.cc
- vendor/double-conversion/upstream/double-conversion/double-to-string.h
- vendor/double-conversion/upstream/test/cctest/test-conversions.cc
> ICU-22325 Update double-conversion to v3.3.0

- icu4c/source/i18n/calendar.cpp
- icu4c/source/test/intltest/caltest.cpp
- icu4c/source/test/intltest/caltest.h
> ICU-22521 Avoid crash by return U_INTERNAL_PROGRAM_ERROR instead of  "%  0"

- docs/processes/release/tasks/docs.md
> ICU-22325 Update docs.md to change `ant` commands to new mavenized scripts

- icu4c/source/i18n/unicode/measure.h
- icu4c/source/test/intltest/measfmttest.cpp
> ICU-22527 add Measure::operator!=()

- .ci-builds/.azure-pipelines.yml
- .ci-builds/data-filter.json
- icu4c/source/i18n/ulocdata.cpp
- icu4c/source/test/cintltst/cldrtest.c
- icu4j/main/core/src/main/java/com/ibm/icu/util/LocaleData.java
Replaces https://github.com/unicode-org/icu/pull/2473
> ICU-22149 Be more graceful with missing lang bundle data

- icu4c/source/test/intltest/measfmttest.cpp
> ICU-22527 Add -Wambiguous-reversed-operator test code

- icu4j/pom.xml
> ICU-22324 Mavenization: fix the with_full_javadoc profile

- docs/processes/release/tasks/healthy-code.md
- icu4j/demos/pom.xml
- icu4j/pom.xml
- icu4j/samples/pom.xml
Updates docs for some of the BRS tasks
> ICU-22324 Update BRS task docs

- docs/processes/release/tasks/versions.md
- icu4j/releases_tools/api_reports.sh
- icu4j/releases_tools/github_release.sh
- icu4j/releases_tools/shared.sh
Files produced (example):
```
icu4j-74rc-javadoc.jar
icu4j-74rc-sources.jar
icu4j-74rc.jar
icu4j-74rc.md5
icu4j-charset-74rc-sources.jar
icu4j-charset-74rc.jar
icu4j-localespi-74rc-sources.jar
icu4j-localespi-74rc.jar
```
> ICU-22534 Script preparing the GitHub icu4j release files

- icu4c/source/common/unicode/rbbi.h
> ICU-22537 unbreak build for external break engine / UCONFIG_NO_SERVICE

- .ci-builds/.azure-pipelines.yml
- icu4c/source/allinone/Build.Windows.ProjectConfiguration.props
1. Added VS2022 checks and removed some VS2019 and VS2017 checks.
2. changed Windows SDK version in Windows Project Configuration for ARM checks as VS2022 required updated Windows SDK.
Pipeline build - https://dev.azure.com/ms/icu/_build/results?buildId=494912&view=results
> ICU-21991 added VS2022 checks and changed windows SDK version

- icu4c/source/i18n/transreg.cpp
> ICU-22322 Fix include to use double quotes

- icu4c/source/test/depstest/dependencies.txt
- icu4c/source/test/fuzzer/locale_util.h
> ICU-22326 Fix build problems

- icu4j/pom.xml
> ICU-22326 ICU 74 release not candidate

- icu4c/source/i18n/measunit_extra.cpp
- icu4c/source/i18n/unicode/measunit.h
- icu4c/source/test/intltest/measfmttest.cpp
- icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/format/MeasureUnitTest.java
- icu4j/main/core/src/main/java/com/ibm/icu/util/MeasureUnit.java
> ICU-22540 Add new CLDR units ronto, ronna, quecto, and quetta

- icu4c/source/common/loclikelysubtags.cpp
- icu4c/source/test/cintltst/cloctst.c
- icu4c/source/test/intltest/loctest.cpp
- icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/util/ULocaleTest.java
- icu4j/main/core/src/main/java/com/ibm/icu/impl/locale/XLikelySubtags.java
> ICU-22545 Fix addLikelySubtags for pseudo Locales

- docs/processes/release/tasks/publish/index.md
> ICU-22533 Update BRS instructions for tagging release

- icu4c/source/test/fuzzer/Makefile.in
- icu4c/source/test/fuzzer/unicodeset_fuzzer.cpp
> ICU-22549 Add UnicodeSet fuzzer

- icu4c/source/test/fuzzer/Makefile.in
- icu4c/source/test/fuzzer/timezone_create_fuzzer.cpp
> ICU-22549 Add Fuzzer for TimeZone

- icu4c/source/test/fuzzer/collator_rulebased_fuzzer.cpp
> ICU-22588 Limit test data to avoid meaningless timeout

- .ci-builds/.azure-pipelines.yml
- icu4c/source/test/cintltst/ccapitst.c
> ICU-22576 Use standard alignof() with modern C

- icu4j/pom.xml
> ICU-22605 Exclude the data files from the -sources.jar

- icu4c/source/test/fuzzer/Makefile.in
- icu4c/source/test/fuzzer/normalizer2_fuzzer.cpp
ICU-22549 Remove unnecessary include files
> ICU-22549 Add Normalizer2 Fuzzer

- icu4c/source/test/fuzzer/normalizer2_fuzzer.cpp
> ICU-22549 Limit Normalizer2 Fuzzer for 5K of input

- docs/userguide/icu4c/build.md
- icu4c/source/acinclude.m4
- icu4c/source/configure
- icu4c/source/configure.ac
> ICU-21107 Update ICU4C minimum standard version from C99 to C11

- icu4c/source/test/fuzzer/Makefile.in
- icu4c/source/test/fuzzer/plurrule_fuzzer.cpp
> ICU-22549 Add PluralRule Fuzzer

- icu4c/source/samples/layout/FontMap.cpp
- icu4c/source/samples/layout/FontMap.h
- icu4c/source/samples/layout/GnomeFontInstance.cpp
- icu4c/source/samples/layout/GnomeFontInstance.h
- icu4c/source/samples/layout/GnomeFontMap.cpp
- icu4c/source/samples/layout/GnomeFontMap.h
- icu4c/source/samples/layout/RenderingSurface.h
- icu4c/source/samples/layout/ScriptCompositeFontInstance.cpp
- icu4c/source/samples/layout/ScriptCompositeFontInstance.h
- icu4c/source/samples/layout/UnicodeReader.cpp
- icu4c/source/samples/layout/cmaps.cpp
- icu4c/source/samples/layout/gnomeglue.cpp
- icu4c/source/samples/layout/rsurface.cpp
- icu4c/source/samples/translit/answers/main_2.cpp
- icu4c/source/samples/translit/answers/main_3.cpp
- icu4c/source/samples/translit/answers/main_4.cpp
- icu4c/source/samples/translit/answers/unaccent.cpp
- icu4c/source/samples/translit/answers/unaccent.h
- icu4c/source/test/letest/FontObject.cpp
- icu4c/source/test/perf/leperf/FontObject.cpp
- icu4c/source/test/perf/unisetperf/draft/bitset.cpp
- icu4c/source/test/perf/unisetperf/draft/trieset.cpp
- icu4c/source/test/thaitest/thaitest.cpp
- icu4c/source/tools/escapesrc/tblgen.cpp
- icu4c/source/tools/gencolusb/extract_unsafe_backwards.cpp
- icu4c/source/tools/gencolusb/verify_uset.cpp
> ICU-22608 Add necessary using statements for namespace icu

- icu4c/source/common/locdspnm.cpp
> ICU-22520 Remove unnecessary copying of statically allocated strings

- icu4c/source/common/uloc_tag.cpp
> ICU-22520 Replace uprv_malloc() / uprv_free() with icu::LocalPointer

- icu4c/source/common/locid.cpp
> ICU-22520 Replace uprv_malloc() / uprv_free() with icu::CharString

- icu4c/source/common/loclikely.cpp
> ICU-22520 Remove now superfluous intermediate buffers

- .ci-builds/.azure-pipelines.yml
- icu4c/source/tools/gendict/gendict.cpp
> ICU-22481 Add toml support to gendict

- icu4c/source/common/locdspnm.cpp
- icu4c/source/common/locresdata.cpp
- icu4c/source/common/locutil.cpp
> ICU-22520 Replace char arrays with icu::CharString

- icu4c/source/i18n/number_fluent.cpp
- icu4c/source/i18n/numrange_fluent.cpp
- icu4c/source/i18n/unicode/numberformatter.h
- icu4c/source/i18n/unicode/numberrangeformatter.h
- icu4c/source/test/intltest/numbertest.h
- icu4c/source/test/intltest/numbertest_api.cpp
- icu4c/source/test/intltest/numbertest_range.cpp
- icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
- icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/number/NumberRangeFormatterTest.java
- icu4j/main/core/src/main/java/com/ibm/icu/number/LocalizedNumberFormatter.java
- icu4j/main/core/src/main/java/com/ibm/icu/number/LocalizedNumberRangeFormatter.java
Will send an API proposal shortly.
> ICU-21952 Add withoutLocale functions to LocalizedNumber[Range]Formatter

- icu4c/source/test/fuzzer/break_iterator_fuzzer.cpp
- icu4c/source/test/fuzzer/collator_compare_fuzzer.cpp
- icu4c/source/test/fuzzer/date_format_fuzzer.cpp
- icu4c/source/test/fuzzer/date_time_pattern_generator_fuzzer.cpp
This reverts commit 11d1148e5680fe62456659af85b37f690612ba73.
> ICU-22549 Revert "ICU-22549 Improve fuzzer to test more locale"

- icu4c/source/test/fuzzer/plurrule_fuzzer.cpp
> ICU-22549 Fix fuzzer to call Locale with null-terminiate string

- icu4c/source/common/charstr.h
- icu4c/source/common/uresbund.cpp
- icu4c/source/i18n/units_data.cpp
> ICU-22520 Make icu::CharString comparable with itself

- icu4c/source/tools/tzcode/zic.c
ISO C99 and later do not support implicit function declarations.
> ICU-22532 Set a value for _POSIX_C_SOURCE to get symlink() declared

- icu4c/source/common/uloc_tag.cpp
> ICU-22520 Replace char arrays with icu::CharString & icu::MemoryPool

- docs/userguide/icu4c/build.md
> ICU-21107 Clarify the C11 & C++17 requirement in the userguide

- icu4c/source/common/unicode/stringpiece.h
- icu4c/source/i18n/formatted_string_builder.h
> ICU-21107 Simplify type_traits expressions for C++17

- icu4c/source/test/cintltst/ccapitst.c
> ICU-22576 Remove now obsolete pre-C11 backward compatibility code

- icu4c/source/i18n/chnsecal.cpp
- icu4c/source/i18n/chnsecal.h
- icu4c/source/test/intltest/caltest.cpp
- icu4c/source/test/intltest/caltest.h
> ICU-22639 Clone the calendar so we don't mess with the real one

- icu4c/source/i18n/calendar.cpp
This reverts changes from commit 47b9a517be000559499dcfcb2ed62eace740e194.
This reverts changes from commit 214ae60d9425e5cc78580d0dddf3bbbe4c80e991.
> ICU-22639 Revert now obsolete bug workarounds

- icu4c/source/tools/tzcode/tz2icu.cpp
> ICU-21107 Replace use of adapter and binder classes removed in C++17

- icu4c/source/configure
- icu4c/source/configure.ac
- icu4c/source/test/intltest/strtest.cpp
- icu4c/source/test/intltest/strtest.h
> ICU-21107 Remove obsolete conditional use of C++17 std::string_view

- icu4c/source/i18n/timezone.cpp
- icu4c/source/test/intltest/tztest.cpp
- icu4j/main/core/src/main/java/com/ibm/icu/impl/ZoneMeta.java
- icu4j/main/core/src/test/java/com/ibm/icu/dev/test/timezone/TimeZoneTest.java
> ICU-22637 Accept non-ASCII digit in GMT custom time zone to fix mistake introduced in PR 2792

- docs/devsetup/java/maven.md
- docs/processes/cldr-icu.md
- docs/processes/release/tasks/healthy-code.md
- docs/userguide/icu4j/index.md
> ICU-22533 Update Maven CLI instructions for multi-module ICU4J

- icu4c/source/common/normalizer2impl.cpp
- icu4c/source/test/intltest/tstnorm.cpp
> ICU-22635 Avoid integer-overflow for invalid large UChar32

- icu4c/source/common/uloc.cpp
- icu4c/source/common/ulocimp.h
- icu4c/source/common/unicode/urename.h
- icu4c/source/i18n/ucal.cpp
> ICU-22520 Switch to using CharString for calling uloc_setKeywordValue()

- icu4c/source/i18n/calendar.cpp
- icu4c/source/i18n/gregoimp.cpp
- icu4c/source/test/intltest/caltest.cpp
- icu4c/source/test/intltest/caltest.h
> ICU-22633 Fix Integer-overflow in icu_75::Calendar::add

- icu4c/source/test/letest/letest.cpp
> ICU-22627 Delete obsolete test case letest/api/ScriptTest

- icu4c/source/i18n/dtfmtsym.cpp
> ICU-22649 Fix possible leakage by using LocalUResourceBundlePointer

- icu4c/source/common/unicode/localpointer.h
> ICU-22651 Move LocalOpenPointer into an internal nested namespace

- icu4c/source/common/loclikely.cpp
- icu4c/source/common/ucurr.cpp
- icu4c/source/common/ulocimp.h
- icu4c/source/i18n/calendar.cpp
- icu4c/source/i18n/dtptngen.cpp
- icu4c/source/i18n/ucal.cpp
- icu4c/source/i18n/ulocdata.cpp
- icu4c/source/i18n/units_data.cpp
> ICU-22520 Let ulocimp_getRegionForSupplementalData() return CharString

- icu4c/source/i18n/calendar.cpp
- icu4c/source/i18n/cecal.cpp
- icu4c/source/i18n/cecal.h
- icu4c/source/i18n/chnsecal.cpp
- icu4c/source/i18n/chnsecal.h
- icu4c/source/i18n/coptccal.cpp
- icu4c/source/i18n/ethpccal.cpp
- icu4c/source/i18n/gregocal.cpp
- icu4c/source/i18n/gregoimp.cpp
- icu4c/source/i18n/gregoimp.h
- icu4c/source/i18n/hebrwcal.cpp
- icu4c/source/i18n/hebrwcal.h
- icu4c/source/i18n/indiancal.cpp
- icu4c/source/i18n/indiancal.h
- icu4c/source/i18n/islamcal.cpp
- icu4c/source/i18n/islamcal.h
- icu4c/source/i18n/persncal.cpp
- icu4c/source/i18n/persncal.h
- icu4c/source/i18n/timezone.cpp
- icu4c/source/i18n/unicode/calendar.h
- icu4c/source/i18n/unicode/gregocal.h
- icu4c/source/test/fuzzer/calendar_fuzzer.cpp
- icu4c/source/test/intltest/caltest.cpp
- icu4c/source/test/intltest/caltest.h
> ICU-22633 Fix integer overflow inside Calendar code

- icu4c/source/common/unicode/localpointer.h
> ICU-22651 Add a docstring for LocalOpenPointer

- icu4c/source/common/uloc.cpp
These functions that eventually write their output to a `ByteSink` need a small temporary buffer for processing the subtag they're about to write and currently use a local `CharString` object to provide this buffer, which then gets written to the `ByteSink` and discarded.
This intermediate step is unnecessary as a `ByteSink` can provide an append buffer which can be used instead, eliminating the need to allocate a local temporary buffer and to copy the data around.
This approach also makes it natural to split the processing into two steps, first calculating the length of the subtag, then processing it, which makes it possible to return early when no output is requested.
> ICU-22520 Use a ByteSink append buffer instead of a local CharString

- icu4c/source/common/localebuilder.cpp
- icu4c/source/common/loclikely.cpp
- icu4c/source/common/locmap.cpp
- icu4c/source/common/uloc.cpp
- icu4c/source/common/uloc_tag.cpp
- icu4c/source/common/ulocimp.h
This is to facilitate further refactoring of the locale code.
> ICU-22520 Refactor function macros into inline functions

- icu4c/source/common/loclikely.cpp
Now when the `parseTagString()` helper function just is a wrapper over `ulocimp_getSubtags()` it can be replaced by calling that function directly instead and letting it handle variant subtags as well.
> ICU-22520 Remove local custom code for parsing variant subtags

- .ci-builds/.azure-pipelines-icu4c.yml
- .ci-builds/.azure-pipelines-icu4j.yml
> ICU-22314 Add PR triggers for Azure pipelines

- tools/commit-checker/Pipfile
- tools/commit-checker/README.md
> ICU-22532 Improve commit checker instructions

- icu4c/source/test/intltest/citrtest.cpp
> ICU-22676 Undefine move32 since it is interpreted as a system call with MSVC ARM64

- CONTRIBUTING.md
- Text is from: https://github.com/unicode-org/.github/issues/12
> ICU-22677 update CONTRIBUTING.md

- LICENSE
- README.md
- icu4j/maven-migration/pom.xml
- icu4j/pom.xml
- https://github.com/unicode-org/.github/issues/15
- update year in LICENSE and README.md
- add SPDX link in LICENSE
- use SPDX code in pom.xml instead of raw license file
> ICU-22677 update LICENSE and README.md

- icu4c/source/test/testdata/collationtest.txt
This test is also relevant to issues ICU-12765 ICU-13508 ICU-20532
> ICU-22646 Update collation test for Latvian locale

- .github/workflows/icu4c.yml
- .github/workflows/icu4j.yml
- .github/workflows/icu_envtest.yml
- .github/workflows/icu_merge_ci.yml
- .github/workflows/icu_valgrind.yml
Github has increased the number of cores in the machines available for Github Actions from 2 to 4:
https://github.blog/2024-01-17-github-hosted-runners-double-the-power-for-open-source/
> ICU-22532 Increase Github Actions CI parallelism from 2 to 4

- .github/workflows/icu_envtest.yml
This is needed to help us to debug and find out what happen on the test machine.
> ICU-22274 display tz db version on the test machine.

- icu4j/main/core/src/main/java/com/ibm/icu/text/PersonName.java
- icu4j/main/core/src/main/java/com/ibm/icu/text/PersonNameFormatter.java
- icu4j/main/core/src/main/java/com/ibm/icu/text/SimplePersonName.java
- icu4j/main/core/src/main/java/com/ibm/icu/text/UnicodeSet.java
- icu4j/main/core/src/main/java/com/ibm/icu/util/MeasureUnit.java
> ICU-22534 ICU4J 75 frontload: API status update

- icu4j/main/core/src/main/java/com/ibm/icu/impl/units/ConversionRates.java
- icu4j/main/core/src/main/java/com/ibm/icu/impl/units/MeasureUnitImpl.java
- icu4j/main/core/src/main/java/com/ibm/icu/impl/units/UnitsConverter.java
- icu4j/main/core/src/test/java/com/ibm/icu/dev/test/impl/UnitsTest.java
This implements unit conversion for speed-beaufort using the new CLDR `special` attribute for the `convertUnit` element; this attribute specifies table-based conversions between a base unit (e.g. meters/sec in this case) and a scale in which a given scale value represents a range of base unit values (instead of the mapping being represented by a factor and optional offset). Conversions from base to scale map any unit on the range to the specific scale value; conversions from the scale value to base use a value in the middle of the range. The only special scale currently supported is "beaufort". The mechanics of the mapping are similar to the CLDR implementation in https://github.com/unicode-org/cldr/pull/3487, see in particular UnitConverter.java in that file.
This is PR is only for the …
> ICU-22655 Implement "special" conversion for speed-beaufort, part 1 icu4j

- icu4j/APIChangeReport.html
> ICU-22534 ICU4J 75 frontload API change report

- .github/workflows/icu_envtest.yml
> ICU-22274 Add zdump info while env test fail

- icu4c/source/common/unicode/uset.h
- icu4c/source/i18n/unicode/calendar.h
- icu4c/source/i18n/unicode/measunit.h
- icu4c/source/i18n/unicode/numfmt.h
- icu4c/source/i18n/unicode/simplenumberformatter.h
- icu4c/source/i18n/unicode/ucal.h
- icu4c/source/i18n/unicode/usimplenumberformatter.h
API promotions spreadsheet: https://docs.google.com/spreadsheets/d/1fXcIjmG-BxcDktMWqi1QenB2CW592DVnPEdt_roWnuE/edit#gid=0
> ICU-22534 Promote almost all @draft ICU 73 APIs to @stable ICU 73

- icu4c/source/test/intltest/callimts.cpp
- icu4c/source/test/intltest/g7coll.cpp
- icu4c/source/test/intltest/loctest.cpp
- icu4c/source/test/intltest/numbertest_range.cpp
- icu4c/source/test/intltest/transtst.cpp
- icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/number/NumberRangeFormatterTest.java
- icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/util/ICUResourceBundleTest.java
- icu4j/main/core/src/test/java/com/ibm/icu/dev/test/format/DateIntervalFormatTest.java
> ICU-22534 BRS#27 scrub closed issues (frontload)

- icu4c/source/i18n/calendar.cpp
- icu4c/source/test/intltest/caltest.cpp
- icu4c/source/test/intltest/caltest.h
Address issue found in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=67160
> ICU-22633 Fix overflow issue in Hebrew calendar

- icu4c/source/test/intltest/loctest.cpp
> ICU-22534 BRS#27 fix CI-Exhaustive-Main breakage for locale qaa

- .ci-builds/.azure-pipelines-icu4c.yml
> ICU-22597 Add MSVC build bot to build ICU4C without exceptions

- icu4c/APIChangeReport.html
- icu4c/APIChangeReport.md
> ICU-22534 BRS#19 Update ICU4C API Change Report (frontloading)

- README.md
- docs/userguide/dev/ci.md
> ICU-22533 Add docs on Continuous Integration

- icu4c/source/tools/genren/genren.pl
> ICU-22687 Fix genren.pl not to skip C++ functions on Mac

- icu4j/main/core/src/main/java/com/ibm/icu/util/IslamicCalendar.java
Refactor different rules into implementation of private interface Algorithm.
Since IslamicCalendar is public in Java (not in C++), we cannot put them into different subclass of Calendar and have to let them use the same class and object since the caller UNFORTUNALLY can call setCalculationType and setCivil to change the object to different rule. With this refactoring, we group the formula for the same rule into the same Algorithm 
implementaiton and now we only do the if/switch check in the constructor or during the call of setCalculationType and setCivil only. The calculation operation is then just delegate the work to the assigned concrete Algorithm.
Improve the efficency while the month is very large. Apply the same optimization in PR 2853 which estimate starting point of year …
> ICU-22679 Refactor Islamic Calendar and Optmize starting condition of loop

- icu4c/source/i18n/islamcal.cpp
- icu4c/source/i18n/islamcal.h
> ICU-22679 Remove duplicate code inside Islamic calendar

- icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
- icu4j/main/core/src/main/java/com/ibm/icu/impl/units/UnitPreferences.java
> ICU-22686 Fix Unit preferences calculation in Java

- icu4c/source/i18n/units_data.cpp
- icu4c/source/test/intltest/numbertest_api.cpp
> ICU-22686 Fix Unit preferences calculation in Cpp

- icu4c/source/test/intltest/ucdtest.cpp
- icu4c/source/test/intltest/ucdtest.h
- icu4c/source/tools/toolutil/ppucd.cpp
> ICU-22689 Add PPUCD-based data driven test for binary props

- icu4c/source/data/unidata/changes.txt
> ICU-22689 reminder for 16.0 update

- icu4c/source/common/brkiter.cpp
- icu4c/source/common/uresdata.cpp
- icu4c/source/i18n/astro.cpp
- icu4c/source/i18n/datefmt.cpp
- icu4c/source/i18n/displayoptions.cpp
- icu4c/source/i18n/dtptngen.cpp
- icu4c/source/i18n/measunit_extra.cpp
- icu4c/source/i18n/number_currencysymbols.cpp
- icu4c/source/i18n/number_modifiers.cpp
- icu4c/source/i18n/number_patternmodifier.cpp
- icu4c/source/i18n/number_patternstring.cpp
- icu4c/source/i18n/number_simple.cpp
- icu4c/source/i18n/number_skeletons.cpp
- icu4c/source/i18n/rbnf.cpp
- icu4c/source/i18n/repattrn.cpp
- icu4c/source/i18n/unicode/nounit.h
- icu4c/source/i18n/units_converter.cpp
- icu4c/source/i18n/upluralrules.cpp
- icu4c/source/test/intltest/fldset.cpp
- icu4c/source/test/intltest/intltest.cpp
- icu4c/source/test/intltest/loctest.cpp
- icu4c/source/test/intltest/testidna.cpp
The purpose of this ticket was to apply only straightforward fixes, not anything that could need discussion, so this is the _modernize-return-braced-init-list_ commit originally from PR #2880 but now with all non-trivial changes manually reverted.
> ICU-22621 Apply straightforward Clang-Tidy fixes

- icu4c/source/i18n/number_capi.cpp
- icu4c/source/i18n/number_decimalquantity.cpp
- icu4c/source/i18n/number_decimalquantity.h
- icu4c/source/i18n/number_integerwidth.cpp
- icu4c/source/i18n/number_patternstring.cpp
- icu4c/source/i18n/number_rounding.cpp
- icu4c/source/i18n/number_simple.cpp
- icu4c/source/i18n/smpdtfmt.cpp
- icu4c/source/i18n/unicode/simplenumberformatter.h
- icu4c/source/i18n/unicode/usimplenumberformatter.h
- icu4c/source/test/cintltst/unumberformattertst.c
- icu4c/source/test/intltest/numbertest.h
- icu4c/source/test/intltest/numbertest_decimalquantity.cpp
- icu4c/source/test/intltest/numbertest_simple.cpp
> ICU-22692 Update names of SimpleNumber functions

- .github/workflows/icu_envtest.yml
> ICU-22711 Set EnvTest frequency to nightly in March/April/Sept/Oct

- icu4c/source/test/intltest/itrbnf.cpp
- icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/format/RbnfTest.java
> ICU-22611 Fixed failures in EnvTest.

- icu4c/source/test/perf/unisetperf/draft/bitset.cpp
- icu4c/source/test/perf/unisetperf/draft/trieset.cpp
> ICU-22618 Make unisetperf/draft possible to compile

- icu4c/source/test/letest/letest.cpp
> ICU-22628 Replace log_err() with log_knownIssue() for known failure

- icu4c/APIChangeReport.html
- icu4c/APIChangeReport.md
> ICU-22534 ICU4C API change report update

- icu4c/source/common/unicode/docmain.h
> ICU-22534 add mf2 to docmain.h

- icu4j/demos/pom.xml
- icu4j/main/charset/pom.xml
- icu4j/main/collate/pom.xml
- icu4j/main/common_tests/pom.xml
- icu4j/main/core/pom.xml
- icu4j/main/currdata/pom.xml
- icu4j/main/framework/pom.xml
- icu4j/main/icu4j/pom.xml
- icu4j/main/langdata/pom.xml
- icu4j/main/localespi/pom.xml
- icu4j/main/regiondata/pom.xml
- icu4j/main/translit/pom.xml
- icu4j/perf-tests/pom.xml
- icu4j/pom.xml
- icu4j/samples/pom.xml
- icu4j/tools/build/pom.xml
- icu4j/tools/misc/pom.xml
- icu4j/tools/utilities-for-cldr/pom.xml
> ICU-22534 Updating pom version to 75.1-SNAPSHOT

- icu4c/source/common/uloc_tag.cpp
Some allocators are less lenient about this than others.
> ICU-22532 Resolve new / free() mismatch

- .ci-builds/.azure-pipelines-icu4c.yml
- icu4c/source/i18n/messageformat2_allocation.h
- icu4c/source/i18n/messageformat2_data_model.cpp
- icu4c/source/i18n/messageformat2_evaluation.cpp
- icu4c/source/i18n/unicode/messageformat2_data_model.h
> ICU-22261 Refactor error handling for internal MF2 array-allocating functions

- icu4j/demos/pom.xml
- icu4j/main/charset/pom.xml
- icu4j/main/collate/pom.xml
- icu4j/main/common_tests/pom.xml
- icu4j/main/core/pom.xml
- icu4j/main/currdata/pom.xml
- icu4j/main/framework/pom.xml
- icu4j/main/icu4j/pom.xml
- icu4j/main/langdata/pom.xml
- icu4j/main/localespi/pom.xml
- icu4j/main/regiondata/pom.xml
- icu4j/main/translit/pom.xml
- icu4j/perf-tests/pom.xml
- icu4j/pom.xml
- icu4j/releases_tools/shared.sh
- icu4j/samples/pom.xml
- icu4j/tools/build/pom.xml
- icu4j/tools/misc/pom.xml
- icu4j/tools/utilities-for-cldr/pom.xml
> ICU-22535 BRS_75_GA: Update ICU version to 75.1 (no more -SNAPSHOT)

- icu4c/APIChangeReport.html
- icu4c/APIChangeReport.md
- icu4c/source/common/unicode/uconfig.h
- icu4c/source/common/unicode/utypes.h
- icu4c/source/data/misc/zoneinfo64.txt
- icu4c/source/i18n/unicode/messageformat2.h
- icu4c/source/i18n/unicode/messageformat2_arguments.h
- icu4c/source/i18n/unicode/messageformat2_data_model.h
- icu4c/source/i18n/unicode/messageformat2_formattable.h
- icu4c/source/i18n/unicode/messageformat2_function_registry.h
> ICU-22533 Change API version annotation from 75.0 to 75

- tools/cldr/cldr-to-icu/build-icu-data.xml
> ICU-22535 BRS_75_GA: Update cldr-to-icu version to 75.1

- icu4c/source/test/testdata/cldr/personNameTest/_header.txt
- icu4c/source/test/testdata/cldr/personNameTest/catalog.txt
- icu4j/main/core/src/test/resources/com/ibm/icu/dev/data/cldr/personNameTest/_header.txt
- icu4j/main/core/src/test/resources/com/ibm/icu/dev/data/cldr/personNameTest/catalog.txt
- tools/cldr/build.xml
Another small round of CLDR integration targeted at PersonName test data files.
> ICU-22535 Integrate CLDR 45 final release update

- .github/pull_request_template.md
- CONTRIBUTING.md
- docs/devsetup/cpp/index.md
> ICU-22723 Update PR template help text for next version's ticket numbers

- icu4c/source/common/loclikelysubtags.cpp
- icu4c/source/test/cintltst/cloctst.c
- icu4c/source/test/intltest/loctest.cpp
- icu4c/source/test/intltest/loctest.h
- icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/util/ULocaleTest.java
- icu4j/main/core/src/main/java/com/ibm/icu/impl/locale/LikelySubtags.java
> ICU-22742 Fix handling of XA,XB,XC for addLikelySubtags

- icu4c/source/layoutex/layout/ParagraphLayout.h
- icu4c/source/layoutex/layout/RunArrays.h
- icu4c/source/layoutex/plruns.cpp
- icu4c/source/samples/translit/answers/unaccent.h
- icu4c/source/samples/translit/unaccent.h
- icu4c/source/test/letest/PortableFontInstance.h
- icu4c/source/test/letest/SimpleFontInstance.h
- icu4c/source/test/letest/cmaps.h
- icu4c/source/test/perf/DateFmtPerf/DateFmtPerf.h
- icu4c/source/test/perf/charperf/charperf.h
- icu4c/source/test/perf/collperf/collperf.cpp
- icu4c/source/test/perf/collperf2/collperf2.cpp
- icu4c/source/test/perf/dicttrieperf/dicttrieperf.cpp
- icu4c/source/test/perf/howExpensiveIs/howExpensiveIs.cpp
- icu4c/source/test/perf/leperf/PortableFontInstance.h
- icu4c/source/test/perf/leperf/SimpleFontInstance.h
- icu4c/source/test/perf/leperf/cmaps.h
- icu4c/source/test/perf/localecanperf/localecanperf.cpp
- icu4c/source/test/perf/normperf/dtfmtrtperf.h
- icu4c/source/test/perf/normperf/normperf.h
- icu4c/source/test/perf/normperf/simplenormperf.cpp
- icu4c/source/test/perf/strsrchperf/strsrchperf.h
- icu4c/source/test/perf/ubrkperf/ubrkperf.h
- icu4c/source/test/perf/unisetperf/draft/bitset.cpp
- icu4c/source/test/perf/unisetperf/draft/trieset.cpp
- icu4c/source/test/perf/unisetperf/unisetperf.cpp
- icu4c/source/test/perf/usetperf/usetperf.cpp
- icu4c/source/test/perf/ustrperf/stringperf.h
- icu4c/source/test/perf/utfperf/utfperf.cpp
- icu4c/source/test/perf/utrie2perf/utrie2perf.cpp
https://releases.llvm.org/17.0.1/tools/clang/tools/extra/docs/clang-tidy/checks/modernize/use-override.html
> ICU-22721 Clang-Tidy: modernize-use-override

- icu4c/source/test/letest/PortableFontInstance.cpp
- icu4c/source/test/letest/letsutil.cpp
- icu4c/source/test/perf/DateFmtPerf/DateFmtPerf.h
- icu4c/source/test/perf/collationperf/collperf.cpp
- icu4c/source/test/perf/collperf/collperf.cpp
- icu4c/source/test/perf/collperf2/collperf2.cpp
- icu4c/source/test/perf/howExpensiveIs/howExpensiveIs.cpp
- icu4c/source/test/perf/leperf/PortableFontInstance.cpp
- icu4c/source/test/perf/leperf/cmaps.cpp
- icu4c/source/test/perf/leperf/leperf.cpp
- icu4c/source/test/perf/leperf/xmlreader.cpp
- icu4c/source/test/perf/normperf/dtfmtrtperf.h
- icu4c/source/test/perf/ustrperf/stringperf.h
> ICU-22721 Delete unused variables

- icu4c/source/layoutex/layout/ParagraphLayout.h
- icu4c/source/layoutex/layout/RunArrays.h
- icu4c/source/layoutex/plruns.cpp
- icu4c/source/test/letest/cmaps.h
- icu4c/source/test/perf/collationperf/collperf.cpp
- icu4c/source/test/perf/collperf/collperf.cpp
- icu4c/source/test/perf/leperf/cmaps.h
- icu4c/source/test/perf/ubrkperf/ubrkperf.h
- icu4c/source/test/thaitest/thaitest.cpp
> ICU-22721 Address trivial compiler warnings

- icu4c/source/test/fuzzer/Makefile.in
- icu4c/source/test/fuzzer/ubidi_fuzzer.cpp
Port the code from https://unicode-org.atlassian.net/browse/ICU-22079 to add fuzzer for ubidi
> ICU-22079 Add ubidi_fuzzer

- icu4j/main/collate/src/test/java/com/ibm/icu/dev/test/collator/AlphabeticIndexTest.java
- icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/format/PluralRulesTest.java
- icu4j/main/core/src/test/java/com/ibm/icu/dev/test/lang/UnicodeSetTest.java
- icu4j/main/core/src/test/java/com/ibm/icu/dev/test/util/DataDrivenTestHelper.java
- icu4j/main/translit/src/test/java/com/ibm/icu/dev/test/translit/UnicodeMapTest.java
> ICU-21757 Remove ICU dependencies on CollectionUtilities

- icu4c/source/test/fuzzer/ubidi_fuzzer.cpp
Check data length to avoid memcpy out of bound.
> ICU-22079 Fix bidi fuzzer

- icu4c/source/tools/gendict/gendict.cpp
> ICU-22764 Fix gendict memory safety in toml uchars mode

- .github/workflows/maven.yaml
> ICU-21757 Small GitHub workflow cleanup

- icu4c/source/test/cintltst/custrtst.c
> ICU-22721 Rename scoped variable to not shadow variable in outer scope

- .github/workflows/maven.yaml
The suggestion I missed in a previous PR.
> ICU-22722 Better name for workflow

- icu4c/source/i18n/basictz.cpp
- icu4c/source/i18n/calendar.cpp
- icu4c/source/i18n/chnsecal.cpp
- icu4c/source/i18n/erarules.cpp
- icu4c/source/i18n/gregoimp.cpp
- icu4c/source/i18n/gregoimp.h
- icu4c/source/i18n/indiancal.cpp
- icu4c/source/i18n/olsontz.cpp
- icu4c/source/i18n/simpletz.cpp
- icu4c/source/i18n/timezone.cpp
- icu4c/source/i18n/tzrule.cpp
- icu4c/source/i18n/vtzone.cpp
Address issues discovered in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=68895
> ICU-22730 propagate error avoid overflow

- icu4c/source/common/putil.cpp
This is a cherry-pick of commit 564c92d666354a8ed0f99cba0f239eba790bd148.
> ICU-22721 Cherry-pick MinGW CI bugfix to maint-75

- icu4c/source/common/ubiditransform.cpp
> ICU-22777 Fix incorrect pointer comparision

- tools/cldr/README.md
- tools/cldr/cldr-to-icu/README.md
> ICU-22722 Update docs for cldr-to-icu converter

- tools/cldr/cldr-to-icu/README.md
> ICU-22722 Make cldr-to-icu verbiage on alt="ascii" more authoritative

- icu4c/source/configure
- icu4c/source/configure.ac
This hack was originally added for ICU-7972 by commit 63e1b55feaa6effb0aa4478baa0f9ea312194a3b.
> ICU-22310 Revert now obsolete autoconf "pld hack"

- icu4c/source/common/ucurr.cpp
> ICU-21810 Fix memory allocation error check in ucurr.cpp

- icu4c/source/test/fuzzer/uregex_match_fuzzer.cpp
- icu4c/source/test/fuzzer/uregex_open_fuzzer.cpp
- icu4c/source/test/perf/DateFmtPerf/DateFmtPerf.h
Just because it's nice to be able to build with `-Werror`.
> ICU-22721 Address minor warnings

- .ci-builds/.azure-exhaustive-tests.yml
- .ci-builds/.azure-pipelines-icu4c.yml
- .ci-builds/.azure-pipelines-icu4j.yml
- .ci-builds/.azure-post-merge-tests.yml
- .github/workflows/icu4c.yml
- .github/workflows/icu4j.yml
- .github/workflows/icu_common.yml
- .github/workflows/icu_docs.yml
- .github/workflows/icu_merge_ci.yml
- .github/workflows/icu_valgrind.yml
> ICU-22721 Prevent redundant concurrent CI runs on the same PR branch

- .github/workflows/cifuzz.yml
per instruction on https://google.github.io/oss-fuzz/getting-started/continuous-integration/
> ICU-22814 Add CIFuzz to ICU

- icu4c/source/common/locdispnames.cpp
- icu4c/source/common/locid.cpp
- icu4c/source/common/loclikely.cpp
- icu4c/source/common/uloc.cpp
- icu4c/source/common/ulocimp.h
- icu4c/source/common/uresbund.cpp
> ICU-22696 Update ulocimp_getKeywordValue() to use std::string_view

- icu4c/source/i18n/tzgnames.cpp
> ICU-22826 Fix memory leak

- icu4c/source/common/uidna.cpp
> ICU-22824 Fix mem Leak during error in uidna.cpp

- icu4c/source/i18n/timezone.cpp
> ICU-22827 Fix memLeak by using LocalUResourceBundlePointer

- icu4c/source/tools/genrb/wrtxml.cpp
> ICU-22820 Fix memLeak during error in genrb

- icu4j/main/core/src/main/java/com/ibm/icu/text/UnicodeSet.java
- icu4j/main/core/src/test/java/com/ibm/icu/dev/test/lang/UnicodeSetTest.java
> ICU-22845 Better iterations for the ICU4J UnicodeSet

- icu4c/source/common/rbbirb.cpp
> ICU-22849 Fix memLeak in RBBIRuleBuilder by using LocalMemory

- icu4c/source/common/locid.cpp
- icu4c/source/common/uloc.cpp
- icu4c/source/common/ulocimp.h
- icu4c/source/common/unicode/locid.h
> ICU-22696 Update ulocimp_setKeywordValue() to use std::string_view

- icu4c/source/common/ulocale.cpp
> ICU-22696 Avoid unnecessary copies of already NUL terminated strings

- icu4c/source/tools/gennorm2/gennorm2.cpp
> ICU-22864 Move main() out of the ICU namespace

- icu4j/main/core/src/main/java/com/ibm/icu/impl/JavaTimeConverters.java
- icu4j/main/core/src/main/java/com/ibm/icu/message2/DateTimeFormatterFactory.java
- icu4j/main/core/src/main/java/com/ibm/icu/message2/MFDataModelFormatter.java
- icu4j/main/core/src/main/java/com/ibm/icu/text/DateFormat.java
- icu4j/main/core/src/main/java/com/ibm/icu/text/DateIntervalFormat.java
- icu4j/main/core/src/main/java/com/ibm/icu/text/MessageFormat.java
- icu4j/main/core/src/main/java/com/ibm/icu/text/SimpleDateFormat.java
- icu4j/main/core/src/test/java/com/ibm/icu/dev/test/format/JavaTimeConvertersTest.java
- icu4j/main/core/src/test/java/com/ibm/icu/dev/test/format/JavaTimeFormatTest.java
> ICU-22853 Support formatting types in java.time

- icu4c/source/common/uresdata.cpp
- no other callers when this is set
> ICU-22374 guard gCollationBinKey behind if !UCONFIG_NO_COLLATION

- docs/download/76.md
> ICU-22723 start ICU 76 download page

- icu4c/source/common/unicode/docmain.h
> ICU-22722 Add RelativeDateTimeFormatter to main API page via docmain.h

- icu4c/source/common/unicode/unistr.h
- icu4c/source/test/intltest/ustrtest.cpp
> ICU-22843 UnicodeString::operator!=(string view)

- icu4c/source/test/intltest/regiontst.cpp
- icu4j/main/core/src/test/java/com/ibm/icu/dev/test/util/RegionTest.java
> ICU-22854 Add consistency test against Region API

- vendor/double-conversion/upstream/.github/dependabot.yml
- vendor/double-conversion/upstream/.github/workflows/ci.yml
- vendor/double-conversion/upstream/.github/workflows/cifuzz.yml
- vendor/double-conversion/upstream/.github/workflows/scons.yml
- vendor/double-conversion/upstream/.github/workflows/scorecard.yml
- vendor/double-conversion/upstream/CMakeLists.txt
- vendor/double-conversion/upstream/MODULE.bazel
- vendor/double-conversion/upstream/README.md
- vendor/double-conversion/upstream/msvc/double-conversion.vcxproj
> ICU-22723 Update double-conversion

- docs/processes/cldr-icu.md
- docs/userguide/icu4c/build.md
- docs/userguide/icu4c/faq.md
- icu4c/source/runConfigureICU
The old names are kept as aliases, but not listed in the help messsage.
> ICU-22881 Switch to using macOS instead of MacOSX in runConfigureICU

- docs/userguide/locale/index.md
- ~~[ ] Tests included, if applicable~~ (not applicable)
> ICU-22877 revised "Region code" (formerly "Country code") section

- icu4c/source/common/unicode/idna.h
- icu4c/source/common/unicode/uidna.h
- icu4c/source/test/intltest/uts46test.cpp
- icu4j/main/core/src/main/java/com/ibm/icu/text/IDNA.java
- icu4j/main/core/src/test/java/com/ibm/icu/dev/test/normalizer/UTS46Test.java
> ICU-22294 UTS46 transitional=deprecated, change DEFAULT

- icu4j/main/core/src/main/java/com/ibm/icu/impl/UnicodeMap.java
- icu4j/main/core/src/main/java/com/ibm/icu/text/DateTimePatternGenerator.java
- icu4j/main/core/src/main/java/com/ibm/icu/util/VersionInfo.java
- icu4j/main/core/src/test/java/com/ibm/icu/dev/test/UnicodeSetBoilerplateTest.java
- icu4j/main/core/src/test/java/com/ibm/icu/dev/test/message2/IcuFunctionsTest.java
- icu4j/main/core/src/test/java/com/ibm/icu/dev/test/rbbi/RBBITestMonkey.java
> ICU-22723 Organize import statements.

- docs/userguide/strings/regexp.md
> ICU-22875 escape less-than sign in regex.md

- README.md
> ICU-22722 Remove old announcement of default git branch name

- icu4c/source/test/fuzzer/Makefile.in
- icu4c/source/test/fuzzer/message_formatter_fuzzer.cpp
> ICU-22716 Add MessageFormat fuzzer

- icu4c/source/test/fuzzer/number_format_fuzzer.cpp
Easy way to increase the fuzzer test coverage.
> ICU-22716 Test more number format

- .github/workflows/cifuzz.yml
CIFuzz ran on post merged since 7/20
https://github.com/unicode-org/icu/actions/workflows/cifuzz.yml
Turn to run on every PR
> ICU-22814 Run CIFuzz on PR

- icu4c/source/i18n/cecal.cpp
- icu4c/source/i18n/cecal.h
- icu4c/source/i18n/coptccal.cpp
- icu4c/source/i18n/ethpccal.cpp
- icu4c/source/test/intltest/caltest.cpp
- icu4c/source/test/intltest/caltest.h
fix overflow issue found in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=71434
> ICU-22730 Fix int overflow inside CE Calendar

- docs/userguide/strings/index.md
> ICU-22722 Add example code for UnicodeString and the standard library

- icu4c/APIChangeReport.html
- icu4c/APIChangeReport.md
> ICU-22723 Frontload ICU4C change report 75 -> 76 (BRS #19)

- icu4j/main/core/src/main/java/com/ibm/icu/lang/UProperty.java
- icu4j/main/core/src/main/java/com/ibm/icu/number/LocalizedNumberFormatter.java
- icu4j/main/core/src/main/java/com/ibm/icu/number/LocalizedNumberRangeFormatter.java
- icu4j/main/core/src/main/java/com/ibm/icu/text/Normalizer2.java
- icu4j/main/core/src/main/java/com/ibm/icu/text/PersonName.java
- icu4j/main/core/src/main/java/com/ibm/icu/text/PersonNameFormatter.java
- icu4j/main/core/src/main/java/com/ibm/icu/text/SpoofChecker.java
- icu4j/main/core/src/main/java/com/ibm/icu/util/CECalendar.java
- icu4j/main/core/src/main/java/com/ibm/icu/util/Calendar.java
- icu4j/main/core/src/main/java/com/ibm/icu/util/ChineseCalendar.java
- icu4j/main/core/src/main/java/com/ibm/icu/util/HebrewCalendar.java
- icu4j/main/core/src/main/java/com/ibm/icu/util/IslamicCalendar.java
- icu4j/main/core/src/main/java/com/ibm/icu/util/TimeZone.java
> ICU-22723 Frontload ICU4J API promotions (BRS #18)

- icu4j/APIChangeReport.html
- icu4j/main/core/src/main/java/com/ibm/icu/util/ULocale.java
> ICU-22723 Frontload ICU4J change report 75-76

- icu4j/pom.xml
> ICU-22606 Point the Maven Central link to license to a versioned one

- icu4c/source/tools/genrb/wrtxml.cpp
See: https://unicode-org.atlassian.net/browse/ICU-22913
> ICU-22913 Fix coverity warning in wrtxml.cpp

- icu4c/source/tools/makeconv/makeconv.cpp
See: https://unicode-org.atlassian.net/browse/ICU-22909
> ICU-22909 Fix coverity warning in makeconv.cpp

- icu4c/source/i18n/reldtfmt.cpp
> ICU-22904 Svace: Fix potential out-of-bound access

- icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/format/MeasureUnitTest.java
Documented in docs/processes/release/tasks/updating-measure-unit.md, updating the data for measurement units requires one to uncomment some code in a unit test, run it, copy from stdout an paste in some other files.
That code is left enabled, spamming the standard output every time tests run.
> ICU-22721 Comment (back) some code generation method

- icu4c/source/common/unicode/platform.h
Slight reformulation of
- https://github.com/unicode-org/icu/pull/3038 by @jeremyd2019
to avoid a double negative and a super long line.
Hopefully easier to understand.
> ICU-22721 simpler check for platforms that dont have char16_t

- icu4c/source/configure
> ICU-22392 Update configure files from configure.ac using autoreconf

- .github/pull_request_template.md
- update to ICU 77 minor-fixes tickets
- lift the instructions out of a comment to make them more visible
> ICU-22722 update PR template for ICU 77

- icu4c/source/test/intltest/dtptngts.cpp
- icu4c/source/test/intltest/loctest.cpp
- icu4c/source/test/intltest/tzfmttst.cpp
- icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/util/ULocaleTest.java
- icu4j/main/core/src/test/java/com/ibm/icu/dev/test/calendar/IBMCalendarTest.java
- icu4j/main/translit/src/test/java/com/ibm/icu/dev/test/translit/RoundTripTest.java
> ICU-22723 ICU76: Update known issue references to cloned reports. BRS #27

- docs/download/76.md
Describes ICU 76 changes including Unicode 16, CLDR 46, some new APIs.
> ICU-22723 download 76rc

- icu4c/source/test/intltest/loctest.cpp
- icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/util/ULocaleTest.java
> ICU-22938 Remove Known Issue subtags for "und_Hant_CN" 

- tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/IcuConverterConfig.java
- tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/LdmlConverterConfig.java
- tools/cldr/cldr-to-icu/src/test/java/org/unicode/icu/tool/cldrtoicu/SupplementalDataTest.java
ICU BRS 76 line 16.
- For minor changes you can use one of the following per-release tickets:
- ICU 77 code warnings/version updates: ICU-22920 — Fix compiler warnings. Update versions of code-related dependencies (e.g., dependabot).
- ICU 77 docs minor fixes: ICU-22921 — User Guide & API docs typos etc., and version updates (e.g., dependabot for User Guide)
> ICU-22724 Clean up import statements

- icu4j/demos/pom.xml
- icu4j/main/charset/pom.xml
- icu4j/main/collate/pom.xml
- icu4j/main/common_tests/pom.xml
- icu4j/main/core/pom.xml
- icu4j/main/currdata/pom.xml
- icu4j/main/framework/pom.xml
- icu4j/main/icu4j/pom.xml
- icu4j/main/langdata/pom.xml
- icu4j/main/localespi/pom.xml
- icu4j/main/regiondata/pom.xml
- icu4j/main/translit/pom.xml
- icu4j/perf-tests/pom.xml
- icu4j/pom.xml
- icu4j/releases_tools/shared.sh
- icu4j/samples/pom.xml
- icu4j/tools/build/pom.xml
- icu4j/tools/misc/pom.xml
- tools/cldr/cldr-to-icu/pom.xml
Updates ICU version number to 76.1
Ready to merge once approved
> ICU-22724 BRS_76_GA Update version number to 76.1 (No more -SNAPSHOT)

- docs/download/76.md
- docs/download/index.md
> ICU-22922 ICU 76 final release

- .github/pull_request_template.md
... so that hopefully PR authors delete these lines before sending their PRs for review.
> ICU-22921 PR template: move standing issues up to TODO section

- .github/pull_request_template.md
Update PR template to simplify for users
> ICU-22921 Update to PR template

- icu4c/source/i18n/calendar.cpp
- icu4c/source/test/intltest/caltest.cpp
- icu4c/source/test/intltest/caltest.h
Fix fuzzer found bug in https://g-issues.oss-fuzz.com/issues/385176279
> ICU-22962 Fix int overflow in Calendar::handleComputeJulianDay

- icu4c/source/i18n/calendar.cpp
- icu4c/source/i18n/unicode/calendar.h
Move the DOW calculation into computeWeekFields
> ICU-22991 Remove unnecessary computeGregorianAndDOWFields private

- icu4c/source/common/umapfile.cpp
> ICU-22992 madvise memory mapped files  on Android.

- icu4c/source/tools/genrb/parse.cpp
change the stack allocated char array subtag to CharString to avoid buffer overflow
> ICU-22973 Fix buffer overflow by using CharString

- icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/format/MeasureUnitTest.java
> ICU-22781 Add a test case for unit constant behaviour

- icu4c/source/i18n/units_converter.cpp
- icu4c/source/i18n/units_converter.h
- icu4c/source/test/intltest/units_test.cpp
Implement handling of constant denominators in unit conversion:
- Add divide method to Factor class in UnitsConverter
- Update ConversionRates to apply constant denominator during conversion
- Add comprehensive test cases for units with constant denominators
> ICU-22781 Add support for converting units with constant denominators (C++)

- icu4j/main/core/src/test/java/com/ibm/icu/dev/test/rbbi/RBBITestMonkey.java
> ICU-22984 Generate the Java UAX29 monkeys

- icu4c/source/common/charstr.cpp
- icu4c/source/common/charstr.h
> ICU-23032 Change appendNumber method to accept long instead of int

- icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/format/MeasureUnitTest.java
- icu4j/main/core/src/main/java/com/ibm/icu/impl/units/MeasureUnitImpl.java
- Add support for generating more compact identifiers for constant denominators
- Introduce methods to convert large constant denominators to scientific notation
- Update MeasureUnitImpl to use new constant denominator string generation
- Add test cases to verify identifier generation for various constant denominator scenarios
> ICU-22781 Fix &Improve MeasureUnit identifier generation for constant denominators (Java)

- icu4c/source/common/unicode/uchar.h
- icu4c/source/i18n/unicode/measunit.h
- icu4c/source/i18n/unicode/numberformatter.h
- icu4c/source/i18n/unicode/numberrangeformatter.h
- icu4c/source/i18n/unicode/simplenumberformatter.h
- icu4c/source/i18n/unicode/usimplenumberformatter.h
Promoted all @draft ICU 75 APIs to @stable ICU 75.
> ICU-22922 Promoted all @draft ICU 75 APIs to @stable ICU 75.

- icu4c/source/common/loclikely.cpp
- icu4c/source/common/locresdata.cpp
- icu4c/source/common/ucurr.cpp
- icu4c/source/common/uloc.cpp
- icu4c/source/common/uloc_tag.cpp
- icu4c/source/common/ulocimp.h
- icu4c/source/common/uresbund.cpp
- icu4c/source/i18n/ucol_sit.cpp
> ICU-22901 Update ulocimp_canonicalize() &co. to use std::string_view

- icu4c/source/i18n/collationruleparser.cpp
> ICU-22901 Replace fixed size buffer with CharString

- icu4j/main/core/src/main/java/com/ibm/icu/lang/UCharacter.java
- icu4j/main/core/src/main/java/com/ibm/icu/util/MeasureUnit.java
Updating the status  to @stable from @draft in ICU4J. These were items approved for ICU75.
> ICU-22922 Update ICU4J status

- icu4j/APIChangeReport.html
Update ICU4J API Change report for release candidate
> ICU-22922 ICU4J RC APIChangeReport.html

- icu4c/APIChangeReport.html
- icu4c/APIChangeReport.md
Update API change reports for ICU4C 77 release candidate
> ICU-22922 ICU4C RC APIChangeReport updates

- icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/format/MeasureUnitTest.java
- icu4j/main/core/src/main/java/com/ibm/icu/util/PersianCalendar.java
- icu4j/main/core/src/test/java/com/ibm/icu/dev/test/impl/UnitsTest.java
- icu4j/main/core/src/test/java/com/ibm/icu/dev/test/message2/Args.java
- icu4j/main/core/src/test/java/com/ibm/icu/dev/test/rbbi/SegmentationRule.java
> ICU-22922 Organize import statements

- docs/download/77.md
- docs/download/index.md
from [initial draft](https://github.com/unicode-org/icu/pull/3370) to rc
> ICU-22922 ICU 77rc download page

- .github/pull_request_template.md
Update PR template for v78 ticket numbers
> ICU-23055 Update PR template to reflect v78 tickets after ICU 77rc cut

- icu4c/source/common/umapfile.cpp
> ICU-23064 Fix for POSIX_MADV_RANDOM undefined

- docs/processes/release/tasks/versions.md
- icu4j/demos/pom.xml
- icu4j/main/charset/pom.xml
- icu4j/main/collate/pom.xml
- icu4j/main/common_tests/pom.xml
- icu4j/main/core/pom.xml
- icu4j/main/currdata/pom.xml
- icu4j/main/framework/pom.xml
- icu4j/main/icu4j/pom.xml
- icu4j/main/langdata/pom.xml
- icu4j/main/localespi/pom.xml
- icu4j/main/regiondata/pom.xml
- icu4j/main/translit/pom.xml
- icu4j/perf-tests/pom.xml
- icu4j/pom.xml
- icu4j/releases_tools/shared.sh
- icu4j/samples/pom.xml
- icu4j/tools/build/pom.xml
- icu4j/tools/misc/pom.xml
- tools/cldr/cldr-to-icu/pom.xml
> ICU-22923 BRS_77_GA Update version number to 77.1 (No more -SNAPSHOT)

- docs/download/77.md
- docs/download/index.md
- docs/index.md
> ICU-22923 ICU 77 release page updates

- icu4c/source/i18n/messageformat2_data_model.cpp
See https://github.com/LuMingYinDetect/icu_defects/blob/main/icu_2.png
> ICU-22817 Use LocalArray to fix memory leak

- icu4c/source/i18n/tzgnames.cpp
See https://github.com/LuMingYinDetect/icu_defects/blob/main/icu_10.png
> ICU-22817 Fix potential memory leak by using LocalPointer

- icu4c/source/i18n/basictz.cpp
See https://github.com/LuMingYinDetect/icu_defects/blob/main/icu_1.png
> ICU-22817 Fix memory leak in basictz by using LocalPointer

- icu4c/source/i18n/hebrwcal.cpp
- icu4c/source/i18n/hebrwcal.h
- icu4c/source/test/intltest/caltest.cpp
- icu4c/source/test/intltest/caltest.h
- icu4j/main/core/src/main/java/com/ibm/icu/util/HebrewCalendar.java
- icu4j/main/core/src/test/java/com/ibm/icu/dev/test/calendar/HebrewTest.java
> ICU-23069 Fix Hebrew calendar calculation

- icu4c/source/i18n/calendar.cpp
- icu4c/source/i18n/chnsecal.cpp
> ICU-23077 Correct the internalGet call inside Calendar

- icu4c/source/common/uniset.cpp
- icu4c/source/i18n/rbt_pars.cpp
- icu4c/source/i18n/tznames_impl.cpp
> ICU-22817 Use Local(Pointer|Memory) to clarify ownership transfer

- icu4j/main/core/src/main/java/com/ibm/icu/impl/locale/LSR.java
ICU-23083 Optimize LSR loaded from langinfo.res
It uses string pools to reduce the memory impact
> ICU-23083 Optimize LSR loaded from langinfo.res

- .github/workflows/icu_merge_ci.yml
> ICU-23086 Fix CI performance tests

- icu4j/main/core/src/main/java/com/ibm/icu/impl/locale/InternalLocaleBuilder.java
- icu4j/main/core/src/main/java/com/ibm/icu/impl/units/ConversionRates.java
- icu4j/main/core/src/main/java/com/ibm/icu/text/DateFormatSymbols.java
https://unicode-org.atlassian.net/browse/ICU-23081
It improves the performance on some platforms, e.g. Android.
> ICU-23081 Use String.replace on non-regex string queries

- .github/workflows/icu4j.yml
- .github/workflows/icu_common.yml
- .github/workflows/icu_merge_ci.yml
- .github/workflows/release-icu4j-maven.yml
- icu4j/main/localespi/pom.xml
- icu4j/pom.xml
- icu4j/tools/build/pom.xml
- icu4j/tools/taglets/pom.xml
> ICU-23072 Support from JDK 11 up, drop support for JDK 8

- icu4j/main/core/pom.xml
- icu4j/pom.xml
> ICU-23094 Workaround for a known performance bug in plexus-io

- .github/workflows/icu_merge_ci.yml
> ICU-23072 Support from JDK 11 up - fix bad actions

- docs/userguide/icu4j/locale-service-provider.md
> ICU-23055 Add warning about our plan to remove localespi

- .gitattributes
- .github/workflows/cache_retain.yml
- .github/workflows/icu4j.yml
- .github/workflows/icu_common.yml
- .github/workflows/icu_merge_ci.yml
- .github/workflows/maven.yaml
- .github/workflows/release-check-sign.yml
- .github/workflows/release-icu4c-fedora.yml
- .github/workflows/release-icu4c-ubuntu.yml
- .github/workflows/release-icu4j-maven.yml
- docs/devsetup/source/index.md
- docs/userguide/dev/gitdev.md
* Remove usage of LFS in CI that is no longer needed
* Update docs about LFS usage
> ICU-23048 Remove links to LFS in CI

- icu4j/main/translit/src/main/java/com/ibm/icu/text/Transliterator.java
- icu4j/main/translit/src/main/java/com/ibm/icu/text/TransliteratorRegistry.java
ICU-23082 Lazily load ICU transliteration rules
https://unicode-org.atlassian.net/browse/ICU-23082
Use a java lambda to lazily read the rules.
Once the rule is read, the rule string is cached in ResourceEntry
> ICU-23082 Lazily load ICU transliteration rules

- icu4c/source/i18n/calendar.cpp
- icu4c/source/i18n/gregoimp.cpp
- icu4c/source/i18n/gregoimp.h
- icu4j/main/core/src/main/java/com/ibm/icu/util/Calendar.java
Simplified Calendar code to remove redudent code and unused code
> ICU-23102 Remove unused code

- icu4c/source/i18n/ethpccal.cpp
> ICU-23102 Simplify calendar code

- icu4c/source/common/lstmbe.cpp
> ICU-23097 Fix memory leak while fail

- icu4c/source/i18n/numrange_impl.cpp
- icu4c/source/i18n/numrange_impl.h
- icu4c/source/test/intltest/numbertest.h
- icu4c/source/test/intltest/numbertest_range.cpp
- icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/number/NumberRangeFormatterTest.java
- icu4j/main/core/src/main/java/com/ibm/icu/number/NumberFormatterSettings.java
- icu4j/main/core/src/main/java/com/ibm/icu/number/NumberRangeFormatterImpl.java
> ICU-23110 Fix number range formatting with percentages

- .github/pull_request_template.md
- CONTRIBUTING.md
- README.md
- icu4c/source/config/dist-data.sh
- icu4c/source/data/unidata/CaseFolding.txt
- icu4c/source/test/intltest/messageformat2test.cpp
- icu4c/source/test/intltest/messageformat2test_custom.cpp
- icu4c/source/test/intltest/messageformat2test_icu.cpp
- icu4c/source/test/intltest/messageformat2test_read_json.cpp
- icu4j/tools/build/src/main/java/com/ibm/icu/dev/tool/errorprone/ErrorProneEntry.java
- icu4j/tools/build/src/main/java/com/ibm/icu/dev/tool/errorprone/ErrorProneReport.java
- icu4j/tools/build/src/main/java/com/ibm/icu/dev/tool/errorprone/ErrorProneUtils.java
- icu4j/tools/build/src/main/java/com/ibm/icu/dev/tool/errorprone/HtmlUtils.java
- icu4j/tools/build/src/main/java/com/ibm/icu/dev/tool/errorprone/Main.java
- icu4j/tools/build/src/main/java/com/ibm/icu/dev/tool/errorprone/ParseMavenOutForErrorProne.java
- icu4j/tools/build/src/main/resources/com/ibm/icu/dev/tool/errorprone/errorprone.css
- tools/scripts/cpysearch/cpyscan.pl
Leftover from PR #3487, and prevent it from happening in the future.
> ICU-23054 Fix copyright scanner; fix terms of use

- .github/workflows/icu4c.yml
Fixes the CI error observed in https://github.com/unicode-org/icu/actions/runs/15157974661/job/42617245684
Haven't tested it yet.
CC @echeran @mihnita
> ICU-23121 Fix GHA workflow for ICU4X releases

- .github/workflows/icu4c.yml
> ICU-23121 Fix GHA workflow for ICU4X, second try

- .github/workflows/icu4c.yml
> ICU-23121 Fix GHA workflow for ICU4X, third try

- docs/userguide/icu/howtouseicu.md
Fix followup broken links in User Guide docs that were pointed out in this [Jira ticket comment](https://unicode-org.atlassian.net/browse/ICU-21834?focusedCommentId=163316)
> ICU-21834 Fix more docs broken links in "How To Use ICU" page

- icu4c/source/test/intltest/Makefile.in
- icu4c/source/test/intltest/alphaindextst.cpp
- icu4c/source/test/intltest/apicoll.cpp
- icu4c/source/test/intltest/calregts.cpp
- icu4c/source/test/intltest/convtest.cpp
- icu4c/source/test/intltest/dcfmapts.cpp
- icu4c/source/test/intltest/intltest.cpp
- icu4c/source/test/intltest/intltest.h
- icu4c/source/test/intltest/intltest.vcxproj
- icu4c/source/test/intltest/intltest.vcxproj.filters
- icu4c/source/test/intltest/intltesttest.cpp
- icu4c/source/test/intltest/itutil.cpp
- icu4c/source/test/intltest/loctest.cpp
- icu4c/source/test/intltest/normconf.cpp
- icu4c/source/test/intltest/numbertest_decimalquantity.cpp
- icu4c/source/test/intltest/numfmtst.cpp
- icu4c/source/test/intltest/pluralmaptest.cpp
- icu4c/source/test/intltest/quantityformattertest.cpp
- icu4c/source/test/intltest/reldatefmttest.cpp
- icu4c/source/test/intltest/simpleformattertest.cpp
- icu4c/source/test/intltest/strcase.cpp
- icu4c/source/test/intltest/strtest.cpp
- icu4c/source/test/intltest/tztest.cpp
- icu4c/source/test/intltest/ucdtest.cpp
- icu4c/source/test/intltest/ustrtest.cpp
- icu4c/source/test/intltest/utfiteratortest.cpp
- icu4c/source/test/intltest/utxttest.cpp
> ICU-22995 templatize assert[Not]Equals of integral and enum types

- docs/contacts.md
Migrate the contents of https://icu.unicode.org/contacts into the GitHub Pages, with updates.
> ICU-23055 add contacts page from ICU Site

- icu4c/source/samples/coll/coll.vcxproj
- icu4c/source/samples/strsrch/strsrch.vcxproj
- icu4c/source/samples/translit/translit.vcxproj
- icu4c/source/samples/ugrep/ugrep.vcxproj
Missed in #3522, spotted by post-merge CI; see https://github.com/unicode-org/icu/pull/3522#issuecomment-2976913192 sq.
> ICU-23132 Fix AdditionalIncludeDirectories for sample projects

- icu4j/main/core/src/main/java/com/ibm/icu/segmenter/Segments.java
- icu4j/main/core/src/main/java/com/ibm/icu/text/RuleBasedNumberFormat.java
See failure here to see what this fixes:
https://github.com/unicode-org/icu/actions/runs/16006954410/job/45155748427
> ICU-23054 Fix javadoc tags that prevent publishing

- icu4c/source/i18n/dtptngen.cpp
- icu4c/source/i18n/regeximp.h
- icu4c/source/i18n/scriptset.cpp
Add checks for self-assigment for whole project.
> ICU-23153 Fix self-assigment in copy constructors

- tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/PseudoLocales.java
> ICU-23161 Generate pseudo-locale currency names

- icu4j/demos/src/main/java/com/ibm/icu/dev/demo/Launcher.java
ICU report: https://mihai-nita.net/tmp/ep/20250710/errorprone2.html#name_MutablePublicArray
Issue type: https://errorprone.info/bugpattern/MutablePublicArray
> ICU-23054 Fix all 'MutablePublicArray' errorprone issues

- icu4j/main/charset/src/test/java/com/ibm/icu/dev/test/charset/TestSelection.java
- icu4j/main/collate/src/test/java/com/ibm/icu/dev/test/collator/CollationRegressionTest.java
> ICU-23054 Fix all 'ObjectToString' errorprone issues

- icu4j/demos/src/main/java/com/ibm/icu/dev/demo/calendar/CalendarFrame.java
- icu4j/main/charset/src/test/java/com/ibm/icu/dev/test/charset/TestConversion.java
- icu4j/main/collate/src/main/java/com/ibm/icu/text/RuleBasedCollator.java
- icu4j/main/collate/src/test/java/com/ibm/icu/dev/test/collator/CollationAPITest.java
- icu4j/main/collate/src/test/java/com/ibm/icu/dev/test/collator/UCAConformanceTest.java
- icu4j/main/collate/src/test/java/com/ibm/icu/dev/test/search/SearchTest.java
- icu4j/main/core/src/test/java/com/ibm/icu/dev/test/UnicodeMapTest.java
- icu4j/main/translit/src/test/java/com/ibm/icu/dev/test/translit/TransliteratorTest.java
- icu4j/tools/misc/src/main/java/com/ibm/icu/dev/tool/ime/indic/IndicInputMethodImpl.java
> ICU-23054 Fix all 'ReferenceEquality' errorprone issues

- icu4c/source/tools/toolutil/pkg_gencmn.cpp
> ICU-23054 const up struct that gencmn outputs

- icu4j/pom.xml
- icu4j/tools/build/src/main/java/com/ibm/icu/dev/tool/errorprone/ParseMavenOutForErrorProne.java
> ICU-12717 Errorprone stopped after 1000 warnings, fixed

- icu4c/source/common/unicode/utfiterator.h
- icu4c/source/test/intltest/utfiteratortest.cpp
add [Unsafe]UTFStringCodePoints default constructors
> ICU-23004 add ...CodePoints default constructors

- icu4c/source/tools/toolutil/writesrc.cpp
> ICU-23075 Add nullptr check for localtime call at writesrc.cpp

- icu4c/source/i18n/dtptngen.cpp
- icu4c/source/i18n/unicode/dtptngen.h
- icu4c/source/test/intltest/dtptngts.cpp
- icu4c/source/test/intltest/dtptngts.h
- icu4j/main/core/src/main/java/com/ibm/icu/text/DateTimePatternGenerator.java
- icu4j/main/core/src/test/java/com/ibm/icu/dev/test/format/DateTimeGeneratorTest.java
This tweaks the DTPG behavior according to the ticket.
> ICU-23114 Fix DateTimePatternGenerator numeric/alphabetic substitution

- icu4c/source/common/fixedstring.h
- icu4c/source/common/uloc_keytype.cpp
- icu4c/source/test/intltest/strtest.cpp
> ICU-23192 Replace use of CharString with FixedString in MemoryPool

- tools/cldr/cldr-to-icu/config.xml
Add to ICU 48 the 7 new locales that reached Basic status in CLDR 48.
> ICU-23196 Add 7 new CLDR 48 locales to ICU

- icu4c/source/test/intltest/dtptngts.cpp
- icu4j/main/core/src/main/java/com/ibm/icu/text/DateTimePatternGenerator.java
- icu4j/main/core/src/test/java/com/ibm/icu/dev/test/format/DateTimeGeneratorTest.java
> ICU-23199 Using 'C' in skeleton throws for some locales

- icu4c/source/tools/genrb/wrtjava.cpp
> ICU-23176 Removed condition that was always true

- icu4c/source/test/cintltst/cdetst.c
- icu4c/source/test/cintltst/cestst.c
- icu4c/source/test/cintltst/cfintst.c
- icu4c/source/test/cintltst/cfrtst.c
- icu4c/source/test/cintltst/cg7coll.c
- icu4c/source/test/cintltst/cjaptst.c
- icu4c/source/test/cintltst/cloctst.c
- icu4c/source/test/cintltst/cmsccoll.c
- icu4c/source/test/cintltst/cturtst.c
- icu4c/source/test/cintltst/custrtst.c
- icu4c/source/test/cintltst/encoll.c
- icu4c/source/tools/makeconv/gencnvex.c
> ICU-23054 Address trivial GCC compiler warnings

- icu4c/source/common/unicode/platform.h
- icu4c/source/common/unicode/utf_old.h
- icu4c/source/test/cintltst/bocu1tst.c
- icu4c/source/tools/genrb/read.c
- icu4c/source/tools/makeconv/gencnvex.c
> ICU-23201 Define and use U_FALLTHROUGH also for C

- icu4c/source/common/locid.cpp
- icu4c/source/common/unicode/locid.h
There are no size guarantees for `std::variant<>` (the implementation in LLVM's _libc++_ will currently add at least 4 bytes for the discriminator, for example) so replacing it with a customized data structure instead gives the control required to make Locale objects 8 bytes smaller.
The storage required for different kinds of `Locale` objects then will look like this, each of them now 8 bytes smaller than they currently are:
|| legacy | current | new | _ratio_ |
| :--- | ---: | ---: | ---: | ---: |
| simple | 224 | 48 | 40 | 18% |
| complex | 227 | 117 | 109 | 48% |
| pathological | 245 | 237 | 229 | 93% |
| posix | 224 | 48 | 40 | 18% |
| fubar | 408 | 280 | 272 | 67% |
|||
| --- | --- |
| simple | `hi` |
| complex | `hi@t=en-h0-hybrid` |
| pathological | …
> ICU-20392 Replace std::variant<> with a custom union to save 8 bytes

- icu4c/source/test/intltest/tzfmttst.cpp
> ICU-11052 Remove logKnownIssue

- icu4j/main/core/src/main/java/com/ibm/icu/segmenter/LocalizedSegmenter.java
- icu4j/main/core/src/main/java/com/ibm/icu/segmenter/Segment.java
- icu4j/main/core/src/main/java/com/ibm/icu/segmenter/Segments.java
> ICU-23056 Fix ICU4J public API release status tags for Segmenter files

- icu4j/main/core/src/main/java/com/ibm/icu/message2/Directionality.java
- icu4j/main/core/src/main/java/com/ibm/icu/message2/MessageFormatter.java
- icu4j/main/core/src/main/java/com/ibm/icu/message2/PlainStringFormattedValue.java
> ICU-23056 Update ICU4J public API release status tags for MF2

- icu4j/main/core/src/main/java/com/ibm/icu/util/ChineseCalendar.java
- icu4j/main/core/src/main/java/com/ibm/icu/util/IslamicCalendar.java
Found by the tool that Craig ran for finding draft ICU APIs.
These were listed with version N/A.
Unfortunately, there are a lot of unrelated changes here, because my Eclipse
- removed trailing spaces
- added missing `@Override` annotations
which other people's IDEs evidently don't do :-/
> ICU-23056 fix two doc tags

- icu4j/main/core/src/main/java/com/ibm/icu/message2/Directionality.java
- icu4j/main/core/src/main/java/com/ibm/icu/message2/OptUtils.java
Easy to revert in case it is not approved by TC
> ICU-23056 Use Locale in Directionality.of

- docs/processes/cldr-icu.md
- icu4c/source/data/brkitr/root.txt
- icu4c/source/data/xml/brkitr/root.xml
- icu4c/source/test/testdata/BUILDRULES.py
- tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/mapper/BreakIteratorMapper.java
Rather than hand editing brkitr/root.txt _every single time_, this changes the cldr-to-icu tooling to generate the data automatically.
Note the items are now in lexical order.
Also note TODOs in ICU-23215 and see ticket for background.
> ICU-23214 generate brkitr/root.txt lstm from data

- icu4j/APIChangeReport.html
This is the draft API change document.
> ICU-23056 ICU4J API Change Report (frontloading)

- icu4c/source/i18n/unicode/ucol.h
> ICU-23055 doc ucol_openRules(strength=UCOL_DEFAULT) to not override strength in rules

- docs/download/78.md
This is a mostly content-free template, just to get a start.
- copy 77.md to 78.md
- update version numbers, links, some references to fit 78
I would like to get this in so that we have a basis for making content updates.
Best to review only the second commit, but I plan to squash before merging.
> ICU-23056 initial ICU 78 download page

- docs/processes/release/tasks/miscellaneous.md
> ICU-23055 Update docs for BRS commit checker instructions

- tools/commit-checker/README.md
- tools/commit-checker/check.py
> ICU-23056 Update BRS commit checker to recognize done resolution status

- icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/message2/Mf2FeaturesTest.java
- icu4j/main/core/src/main/java/com/ibm/icu/message2/DateTimeFunctionFactory.java
- icu4j/main/core/src/test/java/com/ibm/icu/dev/test/format/JavaTimeFormatTest.java
- icu4j/main/core/src/test/java/com/ibm/icu/dev/test/message2/MessageFormat2Test.java
- icu4j/main/core/src/test/java/com/ibm/icu/dev/test/message2/Mf2IcuTest.java
- icu4j/main/core/src/test/resources/com/ibm/icu/dev/test/message2/icu-test-functions.json
- icu4j/main/core/src/test/resources/com/ibm/icu/dev/test/message2/more-functions.json
> ICU-23202 MF2 to LDML 48: update :datetime family of functions to spec

- icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/format/DateFormatTest.java
- icu4j/main/core/src/main/java/com/ibm/icu/impl/JavaTimeConverters.java
- icu4j/main/core/src/main/java/com/ibm/icu/message2/DateTimeFunctionFactory.java
- icu4j/main/core/src/main/java/com/ibm/icu/text/DateFormat.java
- icu4j/main/core/src/main/java/com/ibm/icu/text/MessageFormat.java
- icu4j/main/core/src/main/java/com/ibm/icu/text/SimpleDateFormat.java
- icu4j/main/core/src/test/java/com/ibm/icu/dev/test/format/JavaTimeFormatTest.java
> ICU-22852 Ability to format java.util.Calendar

- icu4j/main/core/src/main/java/com/ibm/icu/message2/Function.java
> ICU-23054 Convert obsolete TODO to a simple comment

- icu4c/source/test/intltest/numbertest_skeletons.cpp
> ICU-23056 Update known issue log for volume units in Arabic locale

- icu4c/source/common/unicode/urename.h
> ICU-23056 Updated urename.h with one new function signature.

- icu4c/source/common/unicode/docmain.h
C++ code point ranges and iterators are a new module, add to the ICU4C API docs main page.
I am adding the header file rather than listing each of the classes. Seems better at this level.
> ICU-23056 docmain + utfiterator.h

- .github/workflows/icu_exhaustive_tests.yml
> ICU-23056 Disable the maven download progress logging

- docs/processes/release/tasks/miscellaneous.md
This describes the new script for finding issues marked "done" but that that haven't had comments updated in test code.
> ICU-23056 Update "scrub issues" miscellaneous.md

- docs/download/78.md
Incomplete for rc. I don't want to block tagging & publishing any longer.
I will create a new ticket and another PR to finish this page for rc.
> ICU-23056 some ICU 78 download page updates

- tools/scripts/scrub_issues/scrub_issues.py
Moves the closed issues to last in the output.
Make the short path by removing the icu_base string,
> ICU-23231 Update scrub script for robustness and clarity

- .github/workflows/release-icu4c-ubuntu.yml
> ICU-23057 Fix archive version in icu4c Ubuntu release
