unicode-org/icu

docs/userguide/strings/regexp.md
`<name>` should be escaped with backslash to prevent it from being rendered as a HTML tag
Jira issue: https://unicode-org.atlassian.net/browse/ICU-21688
=> ICU-21688 escape angle bracket in non-HTML content

.ci-builds/.azure-pipelines.yml, icu4c/source/common/localebuilder.cpp, icu4c/source/test/intltest/localebuildertest.cpp, icu4c/source/test/intltest/localebuildertest.h
The `LocaleBuilder` class assumes that ICU's default locale will never have any BCP47 extension tags on it.
The issue is that it uses a `Locale` object internally to store/track any extensions/keywords, but it creates this by calling `new Locale()`, assuming that the default locale will never have any pre-existing extensions/keywords on it.
This change modifies the `LocaleBuilder` class so that when creating the internal `Locale` object it will clear any pre-existing keywords by calling `uloc_getBaseName` (which removes any keywords from the name).
It adds a new test case which changes the default locale, then runs the `TestLocaleBuilderBasic` test (which previously would have failed).
This change also adds a new CI build bot that has the `LANG` environment variable set to …
=> ICU-21707 Fix LocaleBuilder if default locale has BCP47 extension tags

icu4c/source/common/unicode/platform.h
Finally got around to making this; should fix weird behavior with these macros under Clang, and possible clashes with some other libraries like C++RESTSDK
=> ICU-21064 Fix declspec macro conflict on clang.

.ci-builds/.azure-pipelines.yml
Thanks to the work in PR https://github.com/unicode-org/icu/pull/1786, ICU4C now compiles with C++20.
This change adds 3 additional build bots to the Azure CI builds, in order to provide C++20 build coverage in the CI builds.
Notes:
- The Ubuntu 20.04 image doesn't have Clang-13 or GCC-11, so I needed to download and install it as part of the steps.
- For VS2019, there is no `/std:c++20` flag yet, so I used `/std:c++latest` as that includes many of the C++20 compiler and library changes.
=> ICU-20973 Add C++20 build bots to Azure CI: Clang-13, GCC-11, MSVC with std:c++latest

icu4c/source/i18n/unicode/tmutfmt.h
ICU-20973
An operator!=() is already defined by a base class so this class doesn't
need to define it again and not doing so avoids a C++20 ambiguity.
This simplifies the code.
=> ICU-20973 Delete unnecessary deprecated TimeUnitFormat::operator!=().

README.md
When we changed to running the Valgrind checks on every PR, we forgot to update the status badge in the top-level Readme.md file.
=> ICU-21244 Fix the Valgrind status badge in the top-level Readme.

docs/userguide/dev/codingguidelines.md, icu4j/main/classes/charset/src/com/ibm/icu/charset/CharsetASCII.java, icu4j/main/classes/charset/src/com/ibm/icu/charset/CharsetBOCU1.java, icu4j/main/classes/charset/src/com/ibm/icu/charset/CharsetCompoundText.java, icu4j/main/classes/charset/src/com/ibm/icu/charset/CharsetHZ.java, icu4j/main/classes/charset/src/com/ibm/icu/charset/CharsetISCII.java, icu4j/main/classes/charset/src/com/ibm/icu/charset/CharsetISO2022.java, icu4j/main/classes/charset/src/com/ibm/icu/charset/CharsetMBCS.java, icu4j/main/classes/charset/src/com/ibm/icu/charset/CharsetSCSU.java, icu4j/main/classes/charset/src/com/ibm/icu/charset/CharsetUTF8.java, icu4j/main/classes/core/src/com/ibm/icu/impl/CharacterIteration.java, icu4j/main/classes/core/src/com/ibm/icu/impl/ReplaceableUCharacterIterator.java, icu4j/main/classes/core/src/com/ibm/icu/impl/Utility.java, icu4j/main/classes/core/src/com/ibm/icu/lang/UCharacter.java, icu4j/main/classes/core/src/com/ibm/icu/text/Normalizer.java, icu4j/main/classes/core/src/com/ibm/icu/text/UCharacterIterator.java, icu4j/main/classes/core/src/com/ibm/icu/text/UTF16.java, icu4j/main/tests/charset/src/com/ibm/icu/dev/test/charset/TestCharset.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/lang/UCharacterSurrogateTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/lang/UCharacterTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/lang/UTF16Test.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/TrieTest.java
Widen the following APIs from `char` to `int`:
- class UTF16
- public static boolean isSurrogate(int c) {
- public static boolean isTrailSurrogate(int c) {
- public static boolean isLeadSurrogate(int c) {
- class UCharacter
- public static int getCodePoint(int lead, int trail)
- public static boolean isHighSurrogate(int ch) {
- public static boolean isLowSurrogate(int ch) {
- public static final boolean isSurrogatePair(int high, int low) {
- public static final int toCodePoint(int high, int low) {
I did not comprehensively look for call sites that precede such function calls with
“is BMP” or similar range checks that would now be unnecessary.
In most cases, the behavior should be the same.
In some cases, this change might fix obscure bugs when
such function calls _should have been …
=> ICU-21655 widen Java character APIs from char to int arguments

tools/cldr/cldr-to-icu/pom.xml
dependabot reported ant 1.10.9 has a security problem and suggested to update to 1.10.11.
=> ICU-21708 Update ant version in cldr-to-icu tool

icu4c/source/common/unicode/usetiter.h, icu4j/main/classes/core/src/com/ibm/icu/text/UnicodeSetIterator.java
As proposed:
- mark class UnicodeSetIterator as final in both Java and C++
- remove (make private) the protected `@stable` C++ UnicodeSetIterator members
Note that the class docs already said
> This class is not intended to be subclassed.
> Consider any fields or methods declared as "protected" to be private.
> The use of protected in this class is an artifact of history.
=> ICU-21663 UnicodeSetIterator: make protected members private

.ci-builds/.azure-pipelines.yml
Since Ubuntu 18.04 rolled back to gcc++10 (https://github.com/LandSandBoat/server/pull/272) We can remove the workaround we had of uninstalling gcc+11 to avoid build failures
=> ICU-21617 Remove work around of uninstalling GCC11 in CI build

icu4c/source/i18n/usearch.cpp, icu4c/source/i18n/usrchimp.h, icu4c/source/test/cintltst/usrchtst.c
This PR is a follow-up to PR #1800 (which removed BOYER_MOORE dead code from usearch.cpp).
This PR contains additional clean-up. 
Thanks to Andy for pointing out on the other PR that `initialize` and `setShiftTable` were still setting up Boyer-Moore related data. It turns out that we can we can completely remove the shift tables and related fields from the data structs, as well as remove the `setShiftTable` method.
The creation of `UStringSearch` objects should be slightly faster now, as we no longer waste time computing the unused shift tables (which hashed the pattern collation elements).
The `sizeof(UStringSearch)` is decreased from 5240 bytes to 3192 bytes (on x64), so this should help to reduce memory for applications that create many string search objects.
Also added a test case for …
=> ICU-21710 Additional clean up after removing BOYER_MOORE code from usearch.cpp

icu4c/source/allinone/Build.Windows.PlatformToolset.props
I have often wished that MSVC would output the line in question (similar to GCC/Clang) when it hits an error when compiling.
It turns out that MSVC (somewhat recently) added a new config option which will do just that.
This PR enables the setting for all projects when building ICU4C with MSVC.
=> ICU-21740 Output source code line when an error occurs when building with MSVC.

icu4c/source/common/uresbund.cpp
getAliasTargetAsResourceBundle() does not need the whole actual locale's UResourceDataEntry, only its ResourceData.
It looks up the alias string (from ResourceData+Resource) and then does not need anything from the alias source bundle at all. It used to also get the "path" (for locating the bundle "tree") from the source bundle dataEntry, but the path is the same for all bundles in the tree, so we can just as well get it from the validLocaleDataEntry which we need anyway for sideways "/LOCALE/keyPath" aliases.
(This should have been part of PR #1826)
=> ICU-20769 getAliasTargetAsResourceBundle() only needs ResourceData

.ci-builds/.azure-pipelines.yml, icu4c/source/test/intltest/rbbitst.cpp, icu4c/source/tools/genrb/wrtxml.cpp
In order to add `-Wsuggest-override` to the WarningsAsErrors build bot (see PR #1842), we'll need to first upgrade to a newer version of the Clang compiler.
However, updating to a newer version of the compiler also means that it is now better at spotting issues in the code -- so this PR also includes some fixes as well in order to build cleaning with WarningsAsErrors on Clang-13.
=> ICU-21747 Upgrade WarningsAsErrors build bot to Clang-13 on Ubuntu 20.04

icu4j/main/tests/core/src/com/ibm/icu/dev/test/rbbi/RBBIMonkeyTest.java
This is a follow-up from PR #1844.
The ICU4C RBBI Monkey test code had a check to ensure that the number of breaks was less than the test string length.
The ICU4J test code didn't have this check at all. -- This PR adds the check to the Java test code as well.
=> ICU-21747 Add check to ICU4J RBBI Monkey test for expectedBreakCount

icu4c/source/common/filteredbrk.cpp, icu4c/source/common/rbbi.cpp, icu4c/source/common/rbbitblb.cpp, icu4c/source/common/serv.cpp, icu4c/source/common/uniset.cpp, icu4c/source/common/uvector.cpp, icu4c/source/common/uvector.h, icu4c/source/i18n/alphaindex.cpp, icu4c/source/i18n/rbt_pars.cpp, icu4c/source/i18n/translit.cpp, icu4c/source/i18n/transreg.cpp, icu4c/source/i18n/tridpars.cpp, icu4c/source/test/intltest/transapi.cpp, icu4c/source/test/intltest/uvectest.cpp
- Add updated versions of UVector::addElement() and ensureCapacity() that respect
incoming errors.
Follow on to c26aebe, which renamed the original versions.
- Add UVector::adoptElement() as a replacement for addElement() when the vector
has a deleter function set, meaning that it adopts ownership of its elements.
The intent is to make the behavior clearer at the call sites when looking
at unfamiliar code.
- Make all functions with an incoming failure, as indicated by a UErrorCode parameter,
leave the vector unchanged.
- Change all functions that store object pointers into the vector such that,
when the store cannot be completed for any reason _and_ the vector has a deleter function,
then the incoming object is deleted.
This change can simplify the error handling code around calls to the …
=> ICU-21662 Improve UVector error handling.

icu4c/source/common/uloc.cpp, icu4c/source/test/cintltst/capitst.c, icu4c/source/test/cintltst/capitst.h, icu4c/source/test/cintltst/cloctst.c, icu4c/source/test/intltest/loctest.cpp, icu4j/main/classes/core/src/com/ibm/icu/util/ULocale.java, icu4j/main/tests/collate/src/com/ibm/icu/dev/test/collator/CollationAPITest.java
…core characters as field delimiters.
This seemed fairly straightforward when I agreed to take on this bug, but was a little less so in practice.  The basic idea is that even though the `_` character is illegal in BCP47 language tags, because we support both the BCP47 syntax and the old-style locale-ID syntax (and a hybrid of the two), we'll still see locale IDs that use BCP47 syntax but with underscores between some of the fields.  So I just changed the BCP47 parser so that it'd accept either `-` or `_` as a field delimiter.
This works fine and solves the original symptom reported in JIRA, but I ended up having to change the expected results in a few existing unit tests.  I **think** the new results are okay, but I'm not absolutely certain I'm not having undesirable side effects.
On the …
=> ICU-21460 Changed the ULocale initializers to allow locale IDs that use BCP47 syntax, but with _ as a field delimiter.

icu4c/source/common/locdispnames.cpp, icu4c/source/common/locdspnm.cpp, icu4c/source/test/cintltst/cloctst.c, icu4j/main/classes/core/src/com/ibm/icu/impl/LocaleDisplayNamesImpl.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/ULocaleTest.java
If display name lookup fails for a language code, or for the language-code portion of a locale ID with other elements, then try canonicalizing the language code and looking it up again. This is per the updated locale display name algorithm in the CLDR spec: https://www.unicode.org/reports/tr35/tr35-general.html#locale_display_name_algorithm (added per https://unicode-org.atlassian.net/browse/CLDR-14490)
I think this fixes at least a couple of other tickets (linked to the CLDR ticket for this)
=> ICU-20870 If locale/lang name lookup fails, canonicalize lang and try again

icu4c/source/common/ustack.cpp, icu4c/source/common/uvector.h, icu4c/source/i18n/regexcmp.cpp
Clean up some oversights from commit 0ec329c. This was triggered by fuzz testing finding
a memory leak with the original commit, see https://oss-fuzz.com/testcase-detail/4656781834452992
I was unable to replicate the fuzzing failure, but reviewing the nearby code showed
some likely problems.
In this commit,
- Fix UStack::pop() to not delete the popped element when a deleter function is present.
This was a bug, but because there were no stacks with deleters, was not causing trouble.
- Change RegexCompile::compileSet() to delete the set if it cannot be added to the internal
vector of sets. I suspect this is the cause of the fuzzing leak - 0ec329c changed the
behavior of UVector in the presence of errors.
- Changed RegexCompile::fSetStack to use an object deleter function. This fixes the …
=> ICU-21662 UVector Error Handling in Regex

icu4c/source/common/uloc.cpp, icu4c/source/test/cintltst/cloctst.c, icu4c/source/test/cintltst/cloctst.h
Change the _ConvertBCP47 function to return the new string
instead of modify the pointer of the first arg to make such behavior
obvious. Add a new pointer arg in the end to get the length instead.
Move the stack allocated memory to the right scope.
The bug is caused by https://github.com/unicode-org/icu/pull/1795 rich landed 10 days ago
=> ICU-21749 Fix stack-use-after-scope bug in uloc

icu4c/source/i18n/numrange_impl.cpp, icu4c/source/test/intltest/numbertest.h, icu4c/source/test/intltest/numbertest_range.cpp, icu4j/main/classes/core/src/com/ibm/icu/number/NumberRangeFormatterImpl.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberRangeFormatterTest.java
=> ICU-21684 Fix performance issue in NumberRangeFormatter

icu4c/source/common/putil.cpp
This pull request fixes some chromium bugs related to [ICU-21429](https://unicode-org.atlassian.net/browse/ICU-21429).
Especially [Issue 1158789](https://bugs.chromium.org/p/chromium/issues/detail?id=1158789).
I also investigated why `TZ=$(readlink -m /etc/localtime) chromium` does't work, but this usage is not documented in page [Specifying the Time Zone with TZ](https://www.gnu.org/software/libc/manual/html_node/TZ-Variable.html) so I think making this work is not in the favor of the ICU project.
=> ICU-21429 Allow timezones with max 2 digits at the end to

icu4c/source/common/unicode/uniset.h, icu4c/source/common/uniset.cpp, icu4c/source/common/util.cpp, icu4c/source/common/util.h, icu4c/source/test/intltest/usettest.cpp, icu4c/source/test/intltest/usettest.h, icu4j/main/classes/core/src/com/ibm/icu/impl/Utility.java, icu4j/main/classes/core/src/com/ibm/icu/text/UnicodeSet.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/lang/UnicodeSetTest.java, icu4j/main/tests/translit/src/com/ibm/icu/dev/test/translit/RegexUtilitiesTest.java
UnicodeSet.toPattern() changes:
- Always escape surrogate code points, so that the pattern string is well-formed UTF-16.
- For good measure (and after checking with the ICU team), toPattern() now also always escapes control codes (gc=Cc) and noncharacter code points, which could otherwise trip up consumers of the pattern string.
- When a range a-b has exactly the two code points a and b, then it is normally written without the dash (just ab). However, when these are the last lead surrogate and the first trail surrogate (U+DBFF and U+DC00), we do need to write the dash (a-b) so that the two do not combine into a surrogate pair.
- When a range a-f is followed by a range q-x, f is a lead surrogate, and q is a trail surrogate, then we have to do *something* so that f and q do not combine into …
=> ICU-11891 make UnicodeSet.toPattern() well-formed & round-trip

icu4c/source/i18n/basictz.cpp, icu4c/source/i18n/unicode/basictz.h, icu4c/source/i18n/vtzone.cpp
Revise uses of UVector in basictz.cpp to better handle memory allocation failures.
This is one of an ongoing series of commits to address similar problems with
UVector usage throughout ICU.
The changes primarily involve switching to the use of LocalPointers for
the tracking of memory ownership, and to simplify cleanup in case of errors.
In the function BasicTimeZone::getTimeZoneRulesAfter(), also switched some additional
allocated memory to use LocalPointer or LocalMemory, for consistency in
memory handling.
=> ICU-21662 UVector cleanup in basictz.cpp

icu4j/main/classes/core/src/com/ibm/icu/impl/UnicodeRegex.java, icu4j/main/tests/translit/src/com/ibm/icu/dev/test/translit/RegexUtilitiesTest.java
Fixes exhaustive-test failures from PR #1867.
ICU UnicodeSet.toPattern() escapes supplementary code points using `\Uhhhhhhhh` syntax.
The impl.UnicodeRegex utility needs to change such escapes to `\x{h..h}` syntax so that Java regex.Pattern can read them.
I decided against trying to minimize the number of hex digits, because I would have to develop code to do it properly, which seems unnecessary because Java regex accepts leading zeros.
=> ICU-11891 UnicodeRegex change supplementary escapes to Java regex syntax

icu4c/source/common/unicode/uniset.h, icu4c/source/common/unicode/uset.h, icu4c/source/common/uniset_props.cpp, icu4c/source/i18n/regexcmp.cpp, icu4c/source/test/intltest/usettest.cpp, icu4c/source/test/intltest/usettest.h, icu4j/main/classes/core/src/com/ibm/icu/text/UnicodeSet.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/lang/UnicodeSetTest.java
Changes pattern `^` and `\P` etc., and equivalent functions, to perform a “code point complement” (all code points minus the original set).
Leaves the `complement()` API function performing a symmetric difference with all code points, which retains all multicharacter strings.
=> ICU-21524 UnicodeSet pattern parser: code point complement

icu4c/source/i18n/dangical.cpp, icu4c/source/i18n/dangical.h, icu4c/source/i18n/rbtz.cpp, icu4c/source/i18n/unicode/rbtz.h, icu4c/source/i18n/vtzone.cpp, icu4c/source/test/intltest/tzrulets.cpp
Revise uses of UVector in rbtz.cpp to better handle memory allocation failures.
This is one of an ongoing series of commits to address similar problems with
UVector usage throughout ICU.
The changes include
- Use LocalPointers and UVector deleter functions to simplify OOM checking and recovery.
- Fix RuleBasedTimeZone::addTransitionRule(rule) to have standard ICU adopt behavior
when errors occur, meaning automatic deletion of the incoming rule. This simplifies
both the implementation of the function and the code at the call sites.
- Update addTransitionRule() call sites. Includes modifying the Dangi calendar initialization
to not silently ignore errors.
- struct Transition is changed to derive from UMemory, which allows the use of LocalPointers.
=> ICU-21662 UVector cleanup in rbtz.cpp

docs/userguide/datetime/calendar/index.md
`Indian` was listed in bullet list twice; list wasn't in any particular order so alphabetized it
=> ICU-21581 Fix calendar list in userguide

docs/userguide/dev/codingguidelines.md
Update the userguide sections on object adoption and UErrorCode,
expanding on how the two interact.
=> ICU-21662 Userguide on Adoption and UErrorCode

icu4c/source/i18n/usearch.cpp, icu4c/source/i18n/usrchimp.h
The `usearch_*` API has an internal character break iterator that it uses for handling combining characters or sequences.
However, the internal break iterator isn't always strictly needed or used though -- for example when matching with pure ASCII text. Creating the break iterator is a somewhat non-trivial operation though...
I did some profiling using ICU 64 on Windows with a test program that called the usearch APIs in a loop (calling `usearch_open`, then `usearch_first`), and on average, anywhere from 7-10% of the time was spent on just creating the break iterator (which wasn't actually ever used).
By lazily creating the break iterator when needed we can improve the performance of the `usearch_*` API for cases where it isn't used.
Additionally, I noticed that there were several places …
=> ICU-21533 Lazily create the internal break iterator used in StringSearch & improve error handling

icu4c/source/i18n/plurrule.cpp, icu4c/source/i18n/plurrule_impl.h, icu4c/source/test/intltest/plurults.cpp, icu4c/source/test/intltest/plurults.h, icu4j/main/classes/core/src/com/ibm/icu/text/PluralRules.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/PluralRulesTest.java
In tests that parse plural rule sample values from strings (strings = the substrings of the plural rule), this PR parses those strings to FixedDecimal instead of to double. This enables carrying the exponent, which is needed when seeing numbers like 1.2c3 and 1.2e3.
(This also required fixing up the behavior `getPluralOperand` for FixedDecimal to work the same as in FormattedNumber, so that `PluralRules.select(FixedDecimal)` behaves like `PluralRules.select(FormattedNumber)`.)
@pedberg-icu I think this should fix the problems, but let me know what you observe. In ICU4J, when I removed the logKnownIssue line, the test failures I got seem to be due to a difference in the plural rule strings between expected (in `LOCALE_SNAPSHOT`) and actual (coming from data / a factory?). I added the …
=> ICU-21714 Use FixedDecimal instead of double for plural samples in tests

icu4c/source/tools/icuexportdata/icuexportdata.cpp, icu4c/source/tools/toolutil/BUILD, icu4c/source/tools/toolutil/writesrc.cpp, icu4c/source/tools/toolutil/writesrc.h
1. Add Bazel dependencies for toolutil:writesrc corresponding to changes in PR #1741
2. Change writesrc to not depend on common:propname because tools early in the Unicode build process need writesrc before propname_data.h has been generated.
3. Instead, make usrc_writeUCPMap() more generic: Pull the fetching of value names into an abstract interface, and move the u_getPropertyValueName() into the icuexportdata tool code.
=> ICU-21545 fix Unicode properties Bazel build

icu4c/source/common/unicode/uloc.h, icu4c/source/i18n/unicode/alphaindex.h, icu4c/source/i18n/unicode/dcfmtsym.h, icu4c/source/i18n/unicode/measunit.h, icu4c/source/i18n/unicode/numberrangeformatter.h, icu4c/source/i18n/unicode/unumberrangeformatter.h
This was for the BRS task to check the non-stable API macros (mostly U_HIDE_INTERNAL_API, since the others are now checked automatically). I only needed to add one actual U_HIDE_INTERNAL_API conditional; the rest of this was adding "private" comments to things marked @internal that are already private, and adding #endif comments indicating what conditional is being ended.
=> ICU-21581 check non-stable API macros (mostly U_HIDE_INTERNAL_API)

icu4c/APIChangeReport.html, icu4c/APIChangeReport.md, icu4j/APIChangeReport.html, tools/release/java/src/main/java/com/ibm/icu/dev/tools/docs/StableAPI.java
=> ICU-21581 ICU Change Reports for 70rc

icu4c/source/common/ucurr.cpp, icu4c/source/i18n/tzfmt.cpp, icu4c/source/i18n/tzgnames.cpp, icu4c/source/i18n/tznames.cpp, icu4c/source/i18n/tznames_impl.cpp, icu4c/source/i18n/zonemeta.cpp, icu4c/source/i18n/zonemeta.h
Revise uses of UVector in time zone related code to better handle memory
allocation failures.  This is one of an ongoing series of commits to address
similar problems with UVector usage throughout ICU.
The changes involve switching uses of UVector::addElementX() to the new
adoptElement() or addElement() functions, as appropriate, and using
=> ICU-21763 UVector cleanup in time zone code

icu4c/source/common/unistr.cpp, icu4c/source/test/intltest/ustrtest.cpp
Change UnicodeString::clone() to return a nullptr if the underlying copy
constructor produces a bogus string. This can happen if the copy constructor
encounters a memory allocation failure in allocating the copy's internal string
buffer, or if the string being copied was already bogus.
The change is consistent with other ICU clone functions, which are generally
defined to return nullptr in case of errors.
=> ICU-21778 UnicodeString::clone error handling fix

icu4c/source/common/ucase.cpp
I decided to basically take Vitaly's suggested fix to always reset the output pointer in each function implementation. This makes them behave like returning a (pointer, length) value pair.
I did look at the alternative of resetting the output pointer at each call site. That might save a smidgen of time if we also move the pointer declarations outside of their string-case-mapping loops but seems more errorprone.
=> ICU-21820 ucase_toFullXyz() reset output pointer

icu4c/source/common/localematcher.cpp, icu4c/source/common/locid.cpp, icu4c/source/i18n/region.cpp, icu4c/source/i18n/region_impl.h
Revise uses of UVector in Locale and Region related code to better handle
memory allocation failures.  This is one of an ongoing series of commits to
address similar problems with UVector usage throughout ICU.
The changes involve switching uses of UVector::addElementX() to the new
adoptElement() or addElement() functions, as appropriate, and using
In Region::loadRegionData(), improved the overall error detection and recovery.
=> ICU-21763 UVector cleanup in Locale & Region Code

.ci-builds/.azure-pipelines.yml
We need to migrate the Azure CI builds off the `vs2017-win2016` and `macOS-10.14` images, as they are being removed due to support ending soon. (Dec. 10th 2021 for macOS)
From: https://github.com/actions/virtual-environments/issues/4312
> *Breaking changes*
> Windows 2016 hosted runners will be removed from GitHub actions and Azure DevOps.
> 
> *The motivation for the changes*
> Windows Server 2016 Active support ends on 11 Jan 2022 and Windows Server 2022 VM image is going out of beta later this year.
> As part of our ongoing efforts to keep GitHub and Azure Devops hosted runners updated and secure, the Windows 2016 virtual environment will be removed from GitHub Actions and Azure DevOps.
From: https://devblogs.microsoft.com/devops/hosted-pipelines-image-deprecation/
> The macOS-10.14 …
=> ICU-21838 Migrate Azure pipelines win2016 images to win2019. Update Mac OSX to 10.15

icu4c/source/common/normalizer2impl.cpp, icu4c/source/common/serv.cpp, icu4c/source/common/servls.cpp, icu4c/source/common/servnotf.cpp, icu4c/source/i18n/alphaindex.cpp, icu4c/source/i18n/collationdatabuilder.cpp, icu4c/source/i18n/rbt_set.cpp, icu4c/source/i18n/uspoof_conf.cpp, icu4c/source/i18n/uspoof_conf.h, icu4c/source/test/intltest/icusvtst.cpp
Revise uses of UVector in the next batch of files to better handle memory
allocation failures.  This is one of an ongoing series of commits to address
similar problems with UVector usage throughout ICU.
The changes primarily involve switching uses of UVector::addElementX() to the
new adoptElement() or addElement() functions, as appropriate, and using
=> ICU-21763 UVector cleanup, continued.

icu4c/source/common/lstmbe.cpp
ctgmath is deprecated in C++17 and removed in C++20.
=> ICU-21865 Remove include ctgmath  

icu4c/source/i18n/units_converter.cpp, icu4c/source/i18n/units_router.h, icu4c/source/test/intltest/numbertest_api.cpp, icu4c/source/test/intltest/units_test.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitsConverter.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/impl/UnitsTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
Fixes an error in https://github.com/unicode-org/icu/pull/1565
Also cleans up some old icu-units TODOs:
- This PR tackles icu-units#38 and icu-units#63 TODOs, fixed issues tracked by ICU-21863, remaining issues tracked under ICU-21862.
- icu-units#21 is obsolete
=> ICU-21863 Fix div-by-zero in ICU4J, test inverse unit conversions

icu4c/source/i18n/dtfmtsym.cpp, icu4c/source/i18n/dtptngen.cpp, icu4c/source/i18n/msgfmt.cpp, icu4c/source/i18n/msgfmt_impl.h, icu4c/source/i18n/number_compact.cpp, icu4c/source/i18n/numsys.cpp, icu4c/source/i18n/plurrule.cpp, icu4c/source/i18n/tmutfmt.cpp
Revise uses of UVector in Formatting related code to better handle memory
allocation failures.  This is one of an ongoing series of commits to address
similar problems with UVector usage throughout ICU.
The changes primarily involve switching uses of UVector::addElementX() to the
new adoptElement() or addElement() functions, as appropriate, and using
=> ICU-21763 UVector cleanup in Formatting Code

icu4c/source/i18n/units_converter.cpp, icu4c/source/test/intltest/intltest.cpp, icu4c/source/test/intltest/numbertest_api.cpp, icu4c/source/test/intltest/units_test.cpp, icu4j/main/tests/core/src/com/ibm/icu/dev/test/impl/UnitsTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
This only fixes ICU4C, since ICU4J unit conversions don't support Inf/NaN yet.
Fixing Java depends on first fixing https://github.com/icu-units/icu/issues/132
=> ICU-21862 icu4c unit conversions: support inverting 0 and Infinity (for vehicle-fuel)

icu4c/source/common/dictbe.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/breakiter/CjkBreakEngine.java
1. vector.contains() uses sequential comparison, O(n).
As the vector size is great, the performance will be impacted.
Remove this unnecessary check, vector.contains(), in C++.
2. At Java's CjkBreakEngine, replace "vector.contains()" with "if(pos > previous)" to deal with duplicate breakpoint position.
This way, C++ and Java implementation will be synchronous.
Test: ant checkTest -Dtestclass='com.ibm.icu.dev.test.rbbi.RBBITest'
(RBBTest#TestBreakAllChars() can generate duplicate position for word break. It could pass with this change)
=> ICU-21699 Fix CjkBreakEngine performance issue

icu4c/source/i18n/dtptngen.cpp, icu4c/source/i18n/udatpg.cpp, icu4c/source/i18n/unicode/dtptngen.h, icu4c/source/i18n/unicode/udatpg.h, icu4c/source/test/cintltst/cdateintervalformattest.c, icu4c/source/test/cintltst/udatpg_test.c, icu4c/source/test/intltest/dtfmttst.cpp, icu4c/source/test/intltest/dtptngts.cpp, icu4c/source/test/intltest/dtptngts.h, icu4c/source/test/intltest/tmsgfmt.cpp, icu4j/main/classes/core/src/com/ibm/icu/text/DateTimePatternGenerator.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/DateFormatTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/DateTimeGeneratorTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/TestMessageFormat.java
Implement support for DateTimePatternGenerator choosing the correct date-time combining pattern when formatting a combination for date and time, per[ CLDR spec](https://www.unicode.org/reports/tr35/tr35-dates.html#Missing_Skeleton_Fields). Java, C++ and C all had API to get and set the single "default" pattern previously used for this purpose, so this adds new API to set and get each of the 4 patterns. These were approved in ICU TC on 2022-01-12 with amendments, and the current version of this PR has been updated to reflect the approved getter/setter API. Removing draft status.
=> ICU-21353 Implement DateTimePatternGenerator use of correct datetime pattern; includes new API

icu4c/source/common/brkiter.cpp, icu4c/source/data/brkitr/ja.txt, icu4c/source/data/brkitr/rules/line_loose_phrase_cj.txt, icu4c/source/data/brkitr/rules/line_normal_phrase_cj.txt, icu4c/source/test/intltest/rbbitst.cpp, icu4c/source/test/intltest/rbbitst.h
To make lb and lw independent, create the rule file, line_loose_phrase_cj.txt and line_normal_phrase_cj.txt
=> ICU-21699 Separate lb and lw

icu4c/source/i18n/plurrule.cpp
gcc 5.5 on Solaris refuses to recognise pow(int, int32_t)
(I would reword the commit message, but I need some hints)
Potentially related to #1875.
=> ICU-21896 Use double base in pow()

icu4c/source/common/uvector.cpp, icu4c/source/common/uvector.h
Remove the functions UVector::addElementX() and UVector::ensureCapacityX() that
were temporarily added to aid in the cleaning up of UVector's out-of-memory
error handling.
=> ICU-21763 UVector cleanup, remove old funcs.

icu4c/source/test/perf/Makefile.in, icu4c/source/test/perf/charperf/charperf.cpp, icu4c/source/test/perf/ustrperf/Makefile.in, icu4c/source/test/perf/ustrperf/stringperf.h, icu4c/source/tools/ctestfw/uperf.cpp
adding performance tests to ICU CI.
test/perf/Makefile.in:
adds strsrchperf to list of subdirs.
changes target 'all' to compile everything in the standard way.
test/perf/ustrperf/Makefile.in: changes target executable from stringperf to
ustrperf (i.e. name of directory) to allow uniform handling with other
perf tests in GHA CI rules.
tools/ctestfw/uperf.cpp: changes output to ndjson format for processing with
GHA Benchmark. Keep the previous output, which gets processed by the Perl
scripts, when executed in 'verbose' mode. Backward compatibility,
in case someone still wants to use the Perl scripts for the time being.
May get cleaned up later.
Also remove a few non-essential output lines that would interfere with
GHA Benchmark.
=> ICU-21843 Modifies performance tests and test framework in preparation of

icu4c/source/common/servnotf.cpp
ICUNotifier::notifyChanged() was using the thread-unsafe double-checked lock
idiom. Replace it with use of the mutex only.
=> ICU-21832 Remove unsafe double-checked lock in ICUNotifier

icu4c/source/test/intltest/tztest.cpp, icu4j/main/tests/core/src/com/ibm/icu/dev/test/timezone/TimeZoneTest.java
=> ICU-21918 Updated expected useDaylightTime() value for MIT (Asia/Apia).

icu4c/source/data/brkitr/rules/line_loose_cj.txt, icu4c/source/data/brkitr/rules/line_loose_phrase_cj.txt, icu4c/source/data/brkitr/rules/line_normal_cj.txt, icu4c/source/data/brkitr/rules/line_normal_phrase_cj.txt, icu4c/source/test/testdata/break_rules/line_loose_cj.txt, icu4c/source/test/testdata/break_rules/line_normal_cj.txt, icu4c/source/test/testdata/rbbitst.txt, icu4j/main/shared/data/icudata.jar, icu4j/main/shared/data/icutzdata.jar, icu4j/main/shared/data/testdata.jar, icu4j/main/tests/core/src/com/ibm/icu/dev/test/rbbi/break_rules/line_loose_cj.txt, icu4j/main/tests/core/src/com/ibm/icu/dev/test/rbbi/break_rules/line_normal_cj.txt, icu4j/main/tests/core/src/com/ibm/icu/dev/test/rbbi/rbbitst.txt
This updates the CJ normal & loose linebreak tailorings per a recent change agreed on for CSS:
- For normal, CSS no longer allows breaks before \u2010 HYPHEN or \u2013 EN DASH, i.e. it makes the behavior for these back to what standard linebreak does. These are normally in linebreak class BA but the cj normal tailoring has split them off into a separate class BAX to allow breaks; this PR retracts that.
- For loose, CSS allows breaks before  \u2010 HYPHEN or \u2013 EN DASH only after characters of class ID; for other characters it no longer does. These characters are still split into a separate class BAX, but the first part of rule LB 21 that formerly allowed a break before BAX now needs to be split into two rules, one for non-ID and one for ID. (BAX also needed to ba added to $CanFollowIS …
=> ICU-21592 Update cj normal/loose linebreak per CSS

icu4c/source/data/brkitr/rules/line_loose_cj.txt, icu4c/source/data/brkitr/rules/line_loose_phrase_cj.txt, icu4c/source/test/testdata/break_rules/line_loose_cj.txt, icu4j/main/shared/data/icudata.jar, icu4j/main/shared/data/icutzdata.jar, icu4j/main/tests/core/src/com/ibm/icu/dev/test/rbbi/break_rules/line_loose_cj.txt
This is a followup to PR #1991, Update cj normal/loose linebreak per CSS
The original change to the line_loose_cj rules involved splitting hyphens out
of the BA (Break After) class, allowing a break when they follow an ID. This
change simplifies the the rules for doing that.
It also fixes a problem with the original change that had altered the behavior
of BAX hyphens that followed Regional Indicators or Unattached Combining Marks.
=> ICU-21592 Linebreak loose cj rules cleanup

.github/workflows/icu_merge_ci.yml
Adds two post-merge CI tasks, with each executing three performance tests, to
the GHA configuration file, plus an auxiliary job (compiling and caching ICU4C
libraries).
The executed perf tests are: charperf, usetperf, utfperf, collperf,ustrperf,
and normperf
(cf. also https://github.com/unicode-org/icu/tree/main/icu4c/source/test/perf).
Visualization is provided by GitHub Pages, e.g.
https://gnrunge.github.io/icu-perf/results/normperf/TestNames_Latin/.
=> ICU-21843 Add ICU4C performance tests to continuous integration

icu4c/source/io/sprintf.cpp, icu4c/source/test/iotest/strtst.c
ICU-21768 Fixed (u_snprintf improperly counts the required buffer size).
Modified TestSnprintf in iotest to test the null buffer case.
=> ICU-21768 u_snprintf improperly counts buffer size

icu4c/source/i18n/uspoof_impl.cpp
=> ICU-21801 Fix array comparison warning in uspoof_impl.cpp

icu4c/source/common/unistr.cpp
This commit adds an ignore of the unused function
uprv_UnicodeStringDummy.
=> ICU-21784 suppress -Wunused-function warning in unistr.cpp

icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/DateTimeGeneratorTest.java
Add ICU4J test to verify that the problem reported in ICU-21839 no longer occurs (probably because of Rich Gillam fixes for sideways inheritance; and the reported problem only occurred in ICU4J).
=> ICU-21839 Add ICU4J test that ISO8601 inherits patterns/symbols from Gregorian

icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/LocaleDataTest.java
Add tests from ICU4C test into related ICU4J test to verify proper inheritance of delimiters, especially in some cases where there are partial overrides.
=> ICU-21332 Add tests from ICU4C TestDelimiters() into related ICU4J test

icu4c/source/i18n/dtptngen.cpp, icu4c/source/i18n/unicode/dtptngen.h
Now that UDATPG_NARROW is `@stable`, can reference it in header (the original attempt to do this did not work because of  U_HIDE_DRAFT_API conditionals)
=> ICU-13619 Now that UDATPG_NARROW is @stable, can reference it in header

icu4c/LICENSE, icu4j/main/shared/licenses/LICENSE, tools/unicodetools/license.html
The ICU copy of the Unicode license was missing some lines that are
considered part of the license text.
See https://github.com/unicode-org/template-repo/blob/main/LICENSE
and https://www.unicode.org/license.txt
=> ICU-21824 make the Unicode license match exactly

icu4c/source/common/uloc.cpp, icu4c/source/test/cintltst/cloctst.c
=> ICU-21942 Fix Kosovo 3-letter code to be XKK for uloc_getISO3Country etc.

icu4c/source/common/uloc.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/LocaleIDs.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/ULocaleTest.java, icu4j/main/tests/localespi/src/com/ibm/icu/dev/test/localespi/LocaleNameTest.java
Sync some recent ICU4C updates (for uloc_getISOLanguages, uloc_getISOCountries) in ICU-21341 and ICU-21942  to ICU4J LocaleIDs (getISOLanguages, getISOCountries, getISO3Language, getISO3Country) which is used by ULocale. Also add missing "mo" → "ro" mapping in C and sync that over too. Finally, sync some of the 2015 updates to the C language code list over to J (language code adds and removes; in this PR only did the 2015 updates for language codes beginning with a through c, the rest will be for another ticket).
=> ICU-21944 Sync recent uloc_getLanguage/Countries updates to ICU4J; add "mo" mapping for C

icu4c/source/i18n/unicode/numberformatter.h
Just one change from checking non-stable API macros: In internal StringProp class (which is not completely within #ifndef U_HIDE_INTERNAL_API), move the #ifndef U_HIDE_INTERNAL_API that is present to not include class boilerplate.
=> ICU-21900 check non-stable API macros, move class boilerplate out of conditionals

icu4j/build.xml, icu4j/tools/build/manifest-utilities.stub
https://unicode-org.atlassian.net/browse/ICU-21965
com.ibm.icu.utilities - otherwise the automatic module name is unusable
this is on maint-71
=> ICU-21965 fix utilities.jar module name

docs/processes/release/tasks/versions.md, icu4c/source/Makefile.in, icu4c/source/allinone/Build.Windows.IcuVersion.props, icu4c/source/allinone/Build.Windows.ProjectConfiguration.props, icu4c/source/allinone/Build.Windows.UWP.ProjectConfiguration.props, icu4c/source/common/common.vcxproj, icu4c/source/common/common_uwp.vcxproj, icu4c/source/common/unicode/uvernum.h, icu4c/source/config/windows-update.sed.in, icu4c/source/i18n/i18n.vcxproj, icu4c/source/i18n/i18n_uwp.vcxproj, icu4c/source/io/io.vcxproj, icu4c/source/layoutex/layoutex.vcxproj, icu4c/source/stubdata/stubdata.vcxproj, icu4c/source/tools/ctestfw/ctestfw.vcxproj, icu4c/source/tools/toolutil/toolutil.vcxproj
By using a shared `.props` file with the ICU Major Version number, we can reduce the number of places that need to be edited in the Windows Visual Studio project files.
This means that there will be less churn when we do an ICU version update. With this change, we'll have 8 fewer files to edit.
=> ICU-21972 Use a shared props file for the ICU Major Version number in VS build projects

icu4c/source/i18n/csrmbcs.cpp, icu4c/source/i18n/nfsubs.cpp, icu4c/source/i18n/transreg.cpp, icu4c/source/i18n/unesctrn.cpp
Cleanup -Wunused-but-set-variable in warnings
=> ICU-21966 Cleanup -Wunused-but-set-variable

icu4c/source/test/testdata/structLocale.txt, icu4c/source/tools/toolutil/pkgitems.cpp
When the icupkg tool checks for dependencies from one resource bundle on other bundles, it also checks for the truncation parent bundle.
However, when the bundle has a top-level %%ALIAS string, then the alias target *replaces* the current bundle; and when there is a top-level %%Parent string, then the explicit parent bundle is used. In either of these cases, the truncation parent bundle is ignored and is thus not a required dependency.
The dependency checking code is in the toolutil library, in pkgitems.cpp.
=> ICU-22006 icupkg: %%ALIAS & %%Parent do not need truncation parent

icu4c/source/test/intltest/usettest.cpp
Workaround for a gcc 4.9 bug.
Nice for users who work on legacy platforms (RHEL5 and RHEL5_64), with gcc version 4.9.
This partially reverts one line of the changes in https://github.com/unicode-org/icu/pull/1522.
While working on that PR, I already had to change the escape of U+0000 back to the cast -- on the same line of test code.
=> ICU-21679 avoid escape of U+FFFF in a character literal

icu4c/source/common/utrie2.h, icu4c/source/i18n/uspoof_impl.h
... and adjust uspoof_impl.h which depended on utrie2.h for the indirect inclusion of umutex.h
=> ICU-22016 utrie2.h need not include mutex.h

.ci-builds/.azure-pipelines.yml, icu4c/source/common/characterproperties.cpp, icu4c/source/common/ruleiter.h, icu4c/source/common/ucptrie_impl.h, icu4c/source/i18n/coll.cpp, icu4c/source/i18n/collationdata.h, icu4c/source/i18n/collationdatareader.cpp, icu4c/source/i18n/formatted_string_builder.h, icu4c/source/i18n/gregoimp.cpp, icu4c/source/i18n/rulebasedcollator.cpp, icu4c/source/i18n/unicode/basictz.h, icu4c/source/i18n/unicode/calendar.h, icu4c/source/test/cintltst/ucptrietest.c, icu4c/source/test/intltest/numrgts.cpp, icu4c/source/test/intltest/tsdate.cpp, icu4c/source/test/intltest/tsdate.h, icu4c/source/test/intltest/tsputil.cpp
See warnings in a recent "C: Linux Clang-13 C++20 (Ubuntu 20.04)" build, such as on PR #2080.
- `-Wdeprecated-anon-enum-enum-conversion`
- `-Wdeprecated-enum-enum-conversion`
- `-Wdeprecated-enum-float-conversion`
- `-Wdeprecated-declarations`
- `-Wdeprecated-volatile`
=> ICU-21960 fix clang 13 C++20 warnings

icu4c/source/i18n/calendar.cpp, icu4c/source/i18n/cecal.cpp, icu4c/source/i18n/chnsecal.cpp, icu4c/source/i18n/gregocal.cpp, icu4c/source/i18n/gregoimp.cpp, icu4c/source/i18n/gregoimp.h, icu4c/source/i18n/indiancal.cpp, icu4c/source/i18n/persncal.cpp, icu4c/source/i18n/simpletz.cpp, icu4c/source/i18n/timezone.cpp, icu4c/source/test/intltest/calregts.cpp, icu4c/source/test/intltest/calregts.h, icu4c/source/test/intltest/dtfmttst.cpp, icu4c/source/test/intltest/dtfmttst.h
This PR fix several issures related to Calendar::get() return value out of bound
defined by Calendar::getMinimum() and Calendar::getMaximum() while
the Date is a tiny negative value ( between 0 and -1e-9) and the TimeZone is
"UTC". It also fix the issue while Calendar::get() return error under the same 
condition.
The issue is caused by a tiny value of x (0 .. -1e-9) and a huge value of y (> 1e8)
in the form of 
int32_t w = (int32_t)(x + y); while both x and y are double.
This produce a 1-off rounding error.
We fix it by change it by wrapping x with uprv_floor. This appeared in several places 
related to timezone code and we fix them all in this PR
We also add U_ASSERT to check the bound for most fields except fields of year which
has not real hard constrain of range.
We add two new test …
=> ICU-22023 Fix Calendar::get() return out of bound value and SimpleDateTime::format assert while TimeZone is "UTC" and value is -1e-9

.ci-builds/.azure-pipelines.yml
This updates the clang-13 build bots to use clang-14, and also adds a new libc++ build bot.
Also consolidate the clang-14 build bots together in the file.
=> ICU-22040 Update clang-13 build bots to clang-14, add new libc++ build bot for C++20

icu4c/source/i18n/calendar.cpp, icu4c/source/test/intltest/calregts.cpp, icu4c/source/test/intltest/calregts.h, icu4j/main/classes/core/src/com/ibm/icu/util/Calendar.java
GMT offset for Asia/Manila before  Mon Dec 30 23:59:59 1844 is  -15.9333333333 hours
See "zdump Asia/Manila"
so we need to change the minimum to -16 hours.
Also add unit tests to ensure the assertion won't happen.
=> ICU-22043 Change minimum ZONE_OFFSET value from -12h to -16h

icu4c/source/i18n/displayoptions.cpp, icu4c/source/i18n/number_output.cpp, icu4c/source/i18n/unicode/displayoptions.h, icu4c/source/i18n/unicode/numberformatter.h, icu4c/source/i18n/unicode/udisplayoptions.h, icu4c/source/test/intltest/displayoptions_test.cpp, icu4c/source/test/intltest/numbertest_api.cpp, icu4j/main/classes/core/src/com/ibm/icu/number/FormattedNumber.java, icu4j/main/classes/core/src/com/ibm/icu/text/DisplayOptions.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/text/DisplayOptionsTest.java
Cleanup after PR #2061 -- sorry for not reviewing that on time.
Indentation, `@param`s, don't qualify C enum constants, other C++ style & helpers, ...
=> ICU-21935 DisplayOptions cleanup

icu4c/source/i18n/olsontz.cpp, icu4c/source/i18n/rbtz.cpp, icu4c/source/test/intltest/tztest.cpp, icu4c/source/test/intltest/tztest.h, icu4j/main/tests/core/src/com/ibm/icu/dev/test/timezone/TimeZoneTest.java
Fix incorrect raw offset and display name of "Africa/Casablanca" caused by 
extra `* U_MILLIS_PER_SECOND` before using return value of 
uprv_getUTCtime() which is already in ms per source/common/putilimp.h
Adding test to show the issue
The code is currently only printout in -v mode
Running (notice the -v parameter)
```
LD_LIBRARY_PATH=lib:stubdata:tools/ctestfw:../../lib:../../stubdata:../../tools/ctestfw:$LD_LIBRARY_PATH  ./intltest format/TimeZoneTest/TestCasablancaNameAndOffset22041 -v
```
get
```
-----------------------------------------------
IntlTest (C++) Test Suite for                 
International Components for Unicode 72.0.1
Bits: 64, Byte order: Little endian, Chars: ASCII
-----------------------------------------------
Options:                                       
all (a) …
```
=> ICU-22041 Fix "Africa/Casablanca" show strange LONG displayName

icu4c/source/test/intltest/formatted_string_builder_test.cpp
The logKnownIssue skip that was added in PR #2103 to address the unrelated exhaustive test crash in FormattedStringBuilderTest::testInsertOverflow() did not quite skip the crash; the additional change in this PR does.
- See the bug about the problem being skipped with logKnownIssue: https://unicode-org.atlassian.net/browse/ICU-22047
- The crash may be related to the following change in FormattedStringBuilder per https://unicode-org.atlassian.net/browse/ICU-22005 (Integer overflow leading to OOB/CHECK in icu_71::FormattedStringBuilder::prepareForInsertHelper): PR #2070
=> ICU-21957 improve logKnownIssue skip for FormattedStringBuilderTest::testInsertOverflow crash

icu4c/source/common/localebuilder.cpp
https://unicode-org.atlassian.net/browse/ICU-21960 minor warning fixes
This variable was flagged by a chromium check that looks for variables named like constants that end up in the `.data` ELF section (rather than in `.rodata`).
=> ICU-21960 Add missing "const" to kAttributeKey

icu4c/source/i18n/number_formatimpl.cpp, icu4c/source/i18n/number_mapper.cpp, icu4j/main/classes/core/src/com/ibm/icu/number/NumberFormatterImpl.java, icu4j/main/classes/core/src/com/ibm/icu/number/NumberPropertyMapper.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/CompactDecimalFormatTest.java
=> ICU-22073 Do not throw away CompactDecimalFormat's affixes

icu4c/source/common/unicode/rbbi.h, icu4c/source/common/unicode/schriter.h, icu4c/source/common/unicode/uniset.h, icu4c/source/i18n/hebrwcal.h, icu4c/source/i18n/regexcmp.h, icu4c/source/i18n/unicode/calendar.h, icu4c/source/i18n/unicode/dtptngen.h, icu4c/source/i18n/unicode/gregocal.h, icu4c/source/i18n/unicode/listformatter.h, icu4c/source/i18n/unicode/msgfmt.h, icu4c/source/i18n/unicode/numberrangeformatter.h, icu4c/source/i18n/unicode/numsys.h, icu4c/source/i18n/unicode/plurrule.h, icu4c/source/i18n/unicode/regex.h, icu4c/source/i18n/unicode/tzrule.h, icu4c/source/i18n/unicode/vtzone.h
This patch also includes marking `=delete` on specific `normal` member functions, as opposed to compiler generated functions, based on the description of such functions' surrounding comments.
=> ICU-22054 Remove declarations for unimplemented APIs

icu4c/source/configure.ac
https://unicode-org.atlassian.net/browse/ICU-22010
This helps to avoid misleading error message:
```
./source/configure: line 7981: syntax error near unexpected token 'newline'
./source/configure: line 7981: 'AX_CHECK_COMPILE_FLAG('
```
This is the original GitHub Issue: 
https://github.com/microsoft/vcpkg/issues/24361
=> ICU-22010 Add early check for AX_CHECK_COMPILE_FLAG

icu4c/source/runConfigureICU
Currently `runConfigureICU` supports the `xlclang` and `xlclang++` compilers from IBM XL C/C++ 16.1.0. The latest major release is IBM Open XL C/C++ 17.1.0 and has renamed the compilers to `ibm-clang_r` and `ibm-clang++_r`, both of which are now effectively pure `clang`/`clang++` variants which no longer support any of the old -q options.
This PR adds support for using these compilers to `runConfigureICU`.
=> ICU-22086 Add ibm-clang_r/ibm-clang++_r to runConfigureICU

icu4c/source/tools/icuexportdata/icuexportdata.cpp
Tests are in https://github.com/unicode-org/icu4x/pull/2099
=> ICU-22087 Export a non-recursive canonical decomposition supplement for ICU4X

icu4c/source/test/intltest/dtifmtts.cpp, icu4c/source/test/intltest/dtifmtts.h, icu4j/main/classes/core/src/com/ibm/icu/text/DateTimePatternGenerator.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/DateIntervalFormatTest.java
=> ICU-21939 Fix bogus "conflicting fields" error in DateIntervalFormat.

icu4j/main/classes/core/src/com/ibm/icu/text/PluralRules.java
=> ICU-22101 Error prone reports "StringSplitter" error in PluralRules.java

icu4c/source/common/rbbi_cache.cpp, icu4c/source/test/intltest/rbbitst.cpp, icu4c/source/test/intltest/rbbitst.h, icu4j/main/classes/core/src/com/ibm/icu/text/RuleBasedBreakIterator.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/rbbi/RBBITest.java
Adjust RuleBasedBreakIterator::BreakCache::populateNear() to retain
the cache contents in additional cases where they are still useful, resulting in
improved performance.
This change is related to PR #2039, which addressed the same problem. This one
retains the cache contents in more situations.
=> ICU-21946 RBBI Break Cache Optimizations

icu4c/source/Makefile.in
https://unicode-org.atlassian.net/browse/ICU-22109
The makefile hardcodes paths to the build directory into icu-config. It doesn’t
need to do this and it unnecessarily breaks build reproducibility. This patch
makes a simple change to avoid this.
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
=> ICU-22109 icu-config hardcodes build paths unnecessarily

icu4c/source/i18n/measunit_extra.cpp, icu4c/source/i18n/number_longnames.cpp, icu4c/source/test/intltest/measfmttest.cpp, icu4c/source/test/intltest/plurults.cpp, icu4j/main/classes/core/src/com/ibm/icu/impl/units/MeasureUnitImpl.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/MeasureUnitTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
Removed logKnownIssue(ICU-21322) in plurults.cpp, ICU-21322 is done and the
entire if-statement was commented out anyway.
Replaced CLDR-13700 with CLDR-13701 in several TODOs. 13700 is a duplicate of
13701.
Likewise for CLDR-14502 --> CLDR-14582.
PR #1999 from ICU 71 release missed some of the cases.
=> ICU-21957 Clean-up of TODO and logKnownIssue entries (BRS 72 FL task):

.github/workflows/icu_ci.yml, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/PluralRulesTest.java
=> ICU-22116 Update CI job for ICU4J to use Java 8 instead of Java 7

icu4c/source/common/unicode/platform.h, icu4c/source/i18n/unicode/dtitvinf.h, icu4c/source/i18n/unicode/dtptngen.h, icu4c/source/i18n/unicode/listformatter.h
* Update `U_PF_IPHONE` to be 0 when building for macOS/macCatalyst.
* add macro definition for `attribute((visibility("hidden")))` for cases
where internal structs exist within exposed classes.
=> ICU-22072 Update Darwin Specific Macros

docs/userguide/format_parse/numbers/skeletons.md
- [] Required: Each commit message must be prefixed with a JIRA Issue number. 
[ICU-21983](https://unicode-org.atlassian.net/browse/ICU-21983) The last two lines had the exact same skeleton. So I think the second skeleton has to be changed into `.00/@@@s`
=> ICU-21983 Fix fraction precision skeleton

icu4c/source/common/uloc_tag.cpp
This fixes a warning on gcc 9.4.0, which is triggered because the third argument to `strncpy()` depends on the length of the second argument (but should actually indicate the buffer size). Replacing by `memcpy()` seems harmless because a null terminator is appended further below, and the buffer is sized to be "large enough" elsewhere.
See https://github.com/duckdb/duckdb/issues/4391 for details.
Fixing the warning is important for us, because the checks in the duckdb repository treat all warnings as errors.
Happy to file JIRA issues and to tick the checklist boxes if needed.
=> ICU-22117 Replace uprv_strncpy() by uprv_memcpy()

docs/userguide/icu_data/buildtool.md
The uemoji.icu data file and the uemoji build tool feature were added in ICU 70 ICU-21652 https://github.com/unicode-org/icu/pull/1848
=> ICU-21959 add the uemoji feature to ICU Data Build Tool chapter

icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/NumberFormatTest.java
In ICU4J, just add a test of parsing with empty currency symbol (corresponds to ICU4C test in #2187), code already behaves as desired per ICU-20512
=> ICU-20512 ICU4J: just add test of parse with empty curr symbol, code already works as desired

icu4j/main/classes/core/src/com/ibm/icu/message2/MessageFormatter.java, icu4j/main/classes/core/src/com/ibm/icu/message2/Mf2DataModel.java, icu4j/main/classes/core/src/com/ibm/icu/message2/package.html, icu4j/main/tests/core/src/com/ibm/icu/dev/test/message2/Mf2FeaturesTest.java
The GitHub links need to change from:
https://github.com/unicode-org/message-format-wg/blob/develop/spec/
to
https://github.com/unicode-org/message-format-wg/blob/main/spec/
It is not a disaster if it does not happen, we will make sure we don’t delete the branch, so the links will stay valid. But it looks a bit more professional.
See https://unicode-org.atlassian.net/browse/ICU-22124
=> ICU-22124 Update the MessageFormat v2 links to the main branch

icu4j/main/classes/core/src/com/ibm/icu/message2/Mf2DataModel.java
ICU-22124 Tag the default constructor of OrderedMap as internal/deprecated
Fix for apireport, see https://github.com/unicode-org/icu/pull/2193
=> ICU-22124 Tag the default constructor of OrderedMap as internal/deprecated

icu4j/main/classes/core/src/com/ibm/icu/text/PersonNameFormatter.java
Turns out Javadoc doesn't support tables in Markdown format (which I should have known), so I'm sacrificing readability in the source file for readability of the actual generated code by using literal HTML.
=> ICU-22081 Fix table in PersonNameFormatter Javadoc.

icu4c/source/common/unicode/ubiditransform.h, icu4c/source/common/unicode/ucnv_cb.h, icu4c/source/common/unicode/ucnv_err.h, icu4c/source/common/unicode/ucnvsel.h, icu4c/source/common/unicode/ucpmap.h, icu4c/source/common/unicode/ucptrie.h, icu4c/source/common/unicode/uloc.h, icu4c/source/common/unicode/umisc.h, icu4c/source/common/unicode/umutablecptrie.h, icu4c/source/i18n/unicode/displayoptions.h, icu4c/source/i18n/unicode/regex.h, icu4c/source/i18n/unicode/udisplayoptions.h, icu4c/source/i18n/unicode/unumberformatter.h, icu4c/source/i18n/unicode/unumberrangeformatter.h, icu4c/source/i18n/unicode/uspoof.h
While looking at the ICU 72rc [API docs](https://unicode-org.github.io/icu-docs/) I noticed that some old and new files did not look right in the file listing, and the files from ICU-21935 (display options) didn't show up at all in some places where they should. Once I added the `\file` tag to the display options headers, I had to fix a minor parameter name mismatch.
=> ICU-21959 fix file-level doxygen issues

tools/commit-checker/Pipfile, tools/commit-checker/TEST_COMMIT_METADATA.md, tools/commit-checker/check.py, tools/commit-checker/commit_metadata.py, tools/commit-checker/test_commit_metadata.py
ICU-21755
- new option, --commit-metadata= with path to metadata file
- new option, --fix-version=41 (used for SKIP sections)
- scaffolding for 'bad commits' list
- new module CommitMetadata with unit tests
- sample file format TEST_COMMIT_METADATA.md
- such commits are skipped
- refactored the commit skipping part (formerly used for cherry pick skips)
- add a report section for skipped commits
- add a cache for JIRA queries (for dev use): --cache-for-dev "/tmp/cldr-commit-cache"
- add an 'excluded commits' section at the bottom
See https://github.com/unicode-org/cldr/pull/1790 for an example of use and output reports.
=> ICU-21755 commit checker: add support for COMMIT_METADATA.md file

icu4c/source/common/brkeng.cpp, icu4c/source/common/brkeng.h, icu4c/source/common/brkiter.cpp, icu4c/source/common/dictbe.cpp, icu4c/source/common/filteredbrk.cpp, icu4c/source/common/rbbi.cpp, icu4c/source/common/rbbi_cache.cpp, icu4c/source/common/rbbidata.cpp, icu4c/source/common/rbbinode.cpp, icu4c/source/common/rbbirb.cpp, icu4c/source/common/rbbiscan.cpp, icu4c/source/common/rbbiscan.h, icu4c/source/common/rbbisetb.cpp, icu4c/source/common/rbbistbl.cpp, icu4c/source/common/rbbitblb.cpp, icu4c/source/common/rbbitblb.h, icu4c/source/common/ubrk.cpp, icu4c/source/test/intltest/rbbiapts.cpp, icu4c/source/test/intltest/rbbitst.cpp
In the C++ break iterator code, change all use of NULL to nullptr. This is in preparation for follow-on PRs to improve out-of-memory error handling in Break Iterators, keeping use of nullptr consistent between old and new or updated code.
=> ICU-21180 BreakIterator, change all NULL to nulptr

icu4c/source/tools/toolutil/writesrc.cpp
Fixes build failure on macOS with GCC.
`<cinttypes>` should be used instead of `<inttypes.h>`: https://en.cppreference.com/w/cpp/header/cinttypes
P. S. Using <inttypes.h> requires defining `__STDC_FORMAT_MACROS`: https://opensource.apple.com/source/gcc/gcc-926.1/inttypes.h.auto.html – but it is not defined, which results in build failure.
Alternative would be adding something like:
```
#if defined __APPLE__
#define __STDC_FORMAT_MACROS
#endif
```
before problematic header.
=> ICU-22191 writesrc.cpp: fix cinttypes header

icu4c/source/i18n/buddhcal.cpp, icu4c/source/i18n/buddhcal.h, icu4c/source/i18n/hebrwcal.cpp, icu4c/source/i18n/indiancal.cpp
Remove unnecessary BuddhistCalendar::handleComputeMonthStart Remove unnecessary include
for ICU 73, not 72
=> ICU-22160 clean up Calendar code

icu4c/source/i18n/calendar.cpp, icu4c/source/i18n/cecal.cpp, icu4c/source/i18n/cecal.h, icu4c/source/i18n/chnsecal.cpp, icu4c/source/i18n/chnsecal.h, icu4c/source/i18n/gregocal.cpp, icu4c/source/i18n/hebrwcal.cpp, icu4c/source/i18n/hebrwcal.h, icu4c/source/i18n/indiancal.cpp, icu4c/source/i18n/indiancal.h, icu4c/source/i18n/islamcal.cpp, icu4c/source/i18n/islamcal.h, icu4c/source/i18n/persncal.cpp, icu4c/source/i18n/persncal.h, icu4c/source/i18n/unicode/calendar.h, icu4c/source/i18n/unicode/gregocal.h
All the subclass implementation of inDaylightTime are the same so just move to a base class implementation.
=> ICU-22159 Merge inDaylightTime to Calendar

icu4c/source/common/rbbi.cpp, icu4c/source/common/unicode/rbbi.h, icu4c/source/test/intltest/rbbitst.cpp
In class RuleBasedBreakIterator, refactor how object initialization is handled by the various constructors, taking advantage of C++11's ability to directly initialize data members in the class declaration.
This will simplify ongoing maintenance of the code by eliminating the need to keep initialization lists synchronized with the class data members. This is being done now in preparation for additional changes to fix problems with the handling of memory allocation failures.
=> ICU-21180 RuleBasedBreakIterator, refactor init.

icu4c/source/common/brkiter.cpp, icu4c/source/data/brkitr/ko.txt, icu4c/source/data/xml/brkitr/ko.xml, icu4c/source/test/testdata/rbbitst.txt, icu4j/main/classes/core/src/com/ibm/icu/text/BreakIteratorFactory.java, icu4j/main/shared/data/icudata.jar, icu4j/main/shared/data/testdata.jar, icu4j/main/tests/core/src/com/ibm/icu/dev/test/rbbi/rbbitst.txt, tools/cldr/cldr-to-icu/build-icu-data.xml
brkitr/ko.txt is created to use line_*_.cj.txt for both
lw=phrase and lw != phrase cases for Korean. This is the simplest
way to fix ICU-22119 taking advantage of the fact that ICU
does not have a Korean dictionary so we don't have to worry about
adding the list of Korean particles to keep them attached to the
preceeding word.
The downside is that it only works when the locale is ko or ja while
it should work in any locale. Another is it makes ICU deviate from
CSS3 by using the same CJ (conditonal Japanese) rules for Korean as
well. However, CSS3 spec is wrong on that point and should be changed.
See https://unicode-org.atlassian.net/browse/CLDR-4931 .
=> ICU-22119 Add lw=phrase for Korean using line_*_phrase_cj

icu4c/source/i18n/calendar.cpp, icu4c/source/i18n/chnsecal.cpp, icu4c/source/i18n/chnsecal.h, icu4c/source/i18n/coptccal.cpp, icu4c/source/i18n/coptccal.h, icu4c/source/i18n/dangical.cpp, icu4c/source/i18n/dangical.h, icu4c/source/i18n/ethpccal.cpp, icu4c/source/i18n/ethpccal.h, icu4c/source/i18n/hebrwcal.cpp, icu4c/source/i18n/hebrwcal.h, icu4c/source/i18n/indiancal.cpp, icu4c/source/i18n/indiancal.h, icu4c/source/i18n/islamcal.cpp, icu4c/source/i18n/islamcal.h, icu4c/source/i18n/persncal.cpp, icu4c/source/i18n/persncal.h
Remove the switch statment implementaiton in
Calendar::(g|s)etRelatedYear
and move the code into each subclass as proper OOP style.
=> ICU-10752 Spread (s|g)etRelativeYear to subclass

icu4c/source/common/uresbund.cpp
Hi! We've been fuzzing https://github.com/nodejs/node and found stack buffer overflow error in `icu` in `icu4c/source/common/uresbund.cpp`.  More detailed description of error and how to reproduce is here: https://github.com/nodejs/node/issues/45297
=> ICU-22198 Fix stack buffer overflow.

icu4c/source/i18n/smpdtfmt.cpp, icu4c/source/i18n/unicode/smpdtfmt.h, icu4c/source/test/intltest/dtfmttst.cpp
Based on https://github.com/unicode-org/icu/pull/2241
@sffc is this roughly what you were thinking of?
I think we may be able to optimize further with a global static Latin one but I'm not quite sure how.
Also I wasn't sure if it should be a separate allocation or be a child field. I made it a separate allocation since it's easier.
=> ICU-20115 Migrate SimpleDateFormat over to using SimpleNumberFormatter in the fast path

icu4c/source/tools/toolutil/pkg_genc.cpp
👋
This is the associated PR to fix bug [ICU-22204](https://unicode-org.atlassian.net/browse/ICU-22204).
=> ICU-22204 toolutil: Fix crash when trying to generate MinGW assembly

icu4c/source/common/unicode/icuplug.h, icu4c/source/common/unicode/uclean.h, icu4c/source/test/depstest/dependencies.txt
Fixing some CI test failures that I noticed on other pending PRs.
- API doc warnings about parameters in function typedefs
- dependency checker: mutex/init-once code calling pthread_* functions
=> ICU-22193 fix some CI test failures

.github/workflows/icu_ci.yml
Github has been rolling out their migration of their Github Actions CI runner VM from Ubuntu 20.04 to 22.04:
https://github.com/actions/runner-images/issues/6399
The announcement issue says that if we encounter problems, pin the failing jobs to the old Ubuntu version and file an issue on the runner VM repository.
Based on a [test in my personal fork](https://github.com/echeran/icu/actions/runs/3690618526/jobs/6247821953), reverting to the old version of Ubuntu does allow the jobs to pass.
This PR is to pin the failing jobs to the old Ubuntu version (20.04).
=> ICU-22193 Use Ubuntu 20.04 for jobs failing in migration to 22.04

.github/workflows/icu_ci.yml, icu4c/source/test/cintltst/cintltst.c, icu4c/source/test/intltest/intltest.cpp
It remains unknown when and why this changed, but nowadays the required data files are to be found in a subdirectory named "build".
=> ICU-22193 Make run-with-stubdata work with ubuntu-latest.

.github/workflows/icu_ci.yml
There are 2 CI jobs that run a Maven command at the root.  The jobs are configured to persist any downloaded Maven artifact dependencies, and cache them (save them at the end of the job, load the cache at the beginning of the next instantiation).
We want the cache to work properly to make the jobs more resilient in case of ephemeral network connections, etc., like what happened in this [recent workflow run](https://github.com/unicode-org/icu/actions/runs/3700019863/jobs/6268025244#logs).
But because these jobs run in parallel, there is probably a race condition.  One job invokes a target (`verify`) that is later phase in the Maven lifecycle than the other job's target phase (`test`). This means the first jobs required set of dependencies is a superset of the other.
We could have a …
=> ICU-12811 Make CI jobs for Maven run serially

.github/workflows/icu_ci.yml, icu4c/source/test/hdrtst/testtagsguards.sh
Contemporary implementations of the C++ standard library also use the `@deprecated` annotation in its header files and these then get included by the preprocessor when preprocessing the ICU header files, like this:
```
/// @deprecated Non-standard. Use `is_null_pointer` instead.
```
In order to work as expected, testtagsguards.sh must therefore be updated to ignore `@deprecated` annotations unless they're for ICU.
=> ICU-22193 Make clang-release-build-and-test work with ubuntu-latest.

.github/workflows/cache_retain.yml
This PR is adding a workflow to ensure that certain CI caches are not evicted when they are flaky/costly to create.
The motivating reason is that [PRs can have spurious build failures](https://github.com/unicode-org/icu/actions/runs/3896922654/jobs/6654020248) because the Maven build job cannot download all of the dependency artifacts due to flakiness. The job needs to be re-run in that case until all of the dependency artifacts can be successfully downloaded. This happens when the cache does not exist, which can happen because the cache  is evicted automatically after 7 days of inactivity.
Note: Although ICU4J only has a few test dependencies, the Maven build uses plugins that are implemented with code that have many transitive dependencies. 
By ensuring that the cache exists on the …
=> ICU-12811 Add CI workflow to retain caches that are flaky/costly to init

.github/workflows/cache_retain.yml
Fixes the cron schedule string, which turned out to be incorrectly formatted.
I've [tested this fix in my personal fork](https://github.com/echeran/icu/actions/runs/3914831364/workflow#L33) repo, and the workflow parser seems happy with it.
=> ICU-12811 Fix CI cache retain workflow's cron schedule string

.github/workflows/icu_ci.yml
After looking at the list of [caches in the upstream repo](https://github.com/unicode-org/icu/actions/caches), I realized that the CI Bazel job's cache key wasn't as specific as intended. 
The cache key should include the version of Ubuntu. It was the version bump of Ubuntu from 20.04 to 22.04 that corresponded to the library version differences that led to the original compilation errors in the ticket.
However, the Github Actions predefined variable `${{ runner.os }}` only returns the value `Linux`, and there is no other predefined variable that provides the [runner VM name that includes the version number](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners).
This PR creates a workaround using info available in Ubuntu 16+ systems to get the version …
=> ICU-22233 Fix CI cache name for Bazel build

.github/workflows/icu_ci.yml, icu4j/maven-build/maven-icu4j-localespi/pom.xml, icu4j/maven-build/pom.xml
This PR addresses the peculiar behavior for the localespi tests that have failed when run under Java 8, but so far ignored because the Maven test process strangely returns a successful return code.
This PR:
- Fixes localespi tests under Java 8 by configuring the SPI extension jars to work with the testing JVM successfully
- Makes the localespi tests execute localespi tests differently according to whether Java 8 or Java 9+ is used (via the Maven profiles feature)
- Makes both of the CI Maven jobs run under Java 8 and 11 (not just Java 8)
This PR is based on top of #2275 , so it needs the latter to be merged first.  For review purposes, currently, look at only the last 4 commits (FYI, you can [select that range in the Github review …
=> ICU-12811 Fix localespi tests when run by Maven on Java 8

icu4c/source/test/intltest/caltest.cpp, icu4c/source/test/intltest/caltest.h
This PR add test cases for some tricky year (M11L and incorrect M12L) in 1890 and 2033.
=> ICU-22242 Test to show incorrect calculation of 1890

icu4c/source/common/uchar.cpp, icu4c/source/common/unicode/uchar.h, icu4c/source/common/uprops.cpp, icu4c/source/test/cintltst/cucdtst.c, icu4c/source/test/depstest/dependencies.txt, icu4j/main/classes/core/src/com/ibm/icu/lang/UCharacter.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/lang/UCharacterTest.java
1. Adjust the API doc in the uchar.h to refer to TR31 
2. Move u_isIDStart and u_isIDPart to uprops.cpp
3. Add tests for both C and Java API
4. Fix the C and Java implementation.
5. Adjust the dependency
=> ICU-12725 Update u_isIDStart and u_isIDPart to TR31

icu4c/source/i18n/calendar.cpp, icu4c/source/test/intltest/calregts.cpp, icu4c/source/test/intltest/calregts.h, icu4j/main/classes/core/src/com/ibm/icu/util/Calendar.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/calendar/CalendarRegressionTest.java
This CL fixes only ICU-22226, not [ ICU-11870](https://unicode-org.atlassian.net/browse/ICU-11870)
Properly fixing ICU-11870 (the `DateFormat.getTimeInstance` honoring `hc`) does require a redesign (and design document)
This is independent, and a simple bug, does not require design docs.
=> ICU-22226 Fix Calendar.getFirstDayOfWeek to honor -u-fw

icu4c/source/common/mlbe.cpp
1. Use UnicodeString directly instead of type casing between char16_t* and UnicodeString
2. Because Hashtable.geti(key) returns 0 when key doesn't exist, it doesn't need to check whether the key exists.
=> ICU-22100 Improve Japanese phrase breaking performance

icu4c/source/common/unicode/chariter.h
In C++, the enum inside a class should be accessed by "::" instead of ".".
=> ICU-22194 Change CharacterIterator.DONE to CharacterIterator::DONE in doc

.ci-builds/.azure-exhaustive-tests.yml, .ci-builds/.azure-pipelines.yml, .ci-builds/.azure-valgrind.yml
Update configuration in main/.ci-builds from the deprecated 18.04 to the newest 22.04. The Valgrind build somehow is not working under 22.04, so I keep it in 20.04 for now.
=> ICU-22266 update OS version to 22.04 from 18.04

docs/userguide/format_parse/messages/index.md, docs/userguide/format_parse/messages/mf2.md, icu4j/main/classes/core/src/com/ibm/icu/message2/MessageFormatter.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/message2/Mf2IcuTest.java
Demos of added & updated User Guide pages are in my person fork at the following links:
- [added page on MessageFormat 2.0](https://echeran.github.io/icu/userguide/format_parse/messages/mf2.html)
- [updated page on Formatting Messages](https://echeran.github.io/icu/userguide/format_parse/messages/) (= parent page of previous link = page on current ICU MessageFormat)
fyi @macchiati @aphillips @stasm @eemeli @gibson042
=> ICU-22194 Add User Guide doc for MessageFormat 2.0 tech preview impl

.github/workflows/icu_envtest.yml, icu4c/source/test/cintltst/cdtrgtst.c, icu4c/source/test/cintltst/cloctst.c, icu4c/source/test/intltest/itercoll.cpp, icu4c/source/test/intltest/loctest.cpp, icu4c/source/test/intltest/tztest.cpp
Configure 17+21 = 38 jobs to run icu tests under
500+ locales with LC_ALL= environment variable, and
600+ timezone with TZ= environment variable.
Fix broken tests discovered:
1. Ignore error in cintltst/cdtrgtst.c if the calendar of the default
locale is not "gregorian" because the expectation is reasonable
for 'gregorian' calendar only.
2. Consider the string are the same if the numerical value of the digit
are the same for tests inside cintltst/cdtrgtst.c.
3. Skip the TestCDefaultLocale() error in cintltst/cloctst.c
if LC_ALL env is set.
4. Fix the test which incorrectly assume the string iteration is not end
(under "wo" locale") and avoid incorrect expectation in TestAssignment()
of intltest/itercoll.cpp (see [ICU-22273](https://unicode-org.atlassian.net/browse/ICU-22273) )
5. Skip …
=> ICU-22262 Automate environment test

.github/workflows/icu_ci.yml, docs/processes/release/tasks/healthy-code.md
1. Shorten job name uconfig_variation-check-unit-tests to  uconfig-unit-tests 
2. Shorten job name uconfig_variation-check-all-header-tests to  uconfig-header-tests 
3. use 11 jobs to run in parallel to reduce the ~1hrs run to about 6-8 mins
=> ICU-22269 Speed up uconfig tests by running multiple jobs 

.github/workflows/icu_ci.yml, docs/processes/release/tasks/healthy-code.md, docs/processes/release/tasks/integration.md
=> ICU-22220 Automate BRS tasks

icu4c/source/tools/icuexportdata/icuexportdata.cpp
Followup from https://github.com/unicode-org/icu/pull/2339
=> ICU-22270 Use hex discriminants for exported toml properties

icu4c/source/common/putil.cpp, icu4c/source/common/uposixdefs.h, icu4c/source/test/depstest/dependencies.txt
=> ICU-21386 uprv_tzname() should find the correct Olson ID when /etc/localtime is a "double" link

icu4c/source/common/characterproperties.cpp, icu4c/source/common/ucase.cpp, icu4c/source/common/ucase.h, icu4c/source/common/unicode/uniset.h, icu4c/source/common/unicode/uset.h, icu4c/source/common/uniset_closure.cpp, icu4c/source/common/uniset_props.cpp, icu4c/source/common/uprops.h, icu4c/source/common/uset_imp.h, icu4c/source/test/intltest/usettest.cpp, icu4c/source/test/intltest/usettest.h, icu4j/main/classes/core/src/com/ibm/icu/impl/UCaseProps.java, icu4j/main/classes/core/src/com/ibm/icu/text/UnicodeSet.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/lang/UnicodeSetTest.java
Adds a new option for UnicodeSet::closeOver(int options) and other functions with this options parameter:
- C (unicode/uset.h) USET_SIMPLE_CASE_INSENSITIVE
- Java UnicodeSet.SIMPLE_CASE_INSENSITIVE
With the new option, the UnicodeSet is expanded so that for each code point the other code points in its Simple_Case_Folding (scf) equivalence class are added, and each multi-character string is replaced with a version where each code point is replaced with its scf mapping.
The implementation uses the same data structure as for the full case folding (UnicodeSet.CASE_INSENSITIVE) but only adds the “simple” (single-code point) mappings, and also omits a hardcoded list of mappings where there is no scf equivalence. (I will propose additional scf mappings in a future version of Unicode to fix …
=> ICU-6065 UnicodeSet::closeOver(simple case folding)

icu4c/source/i18n/unicode/calendar.h, icu4c/source/i18n/unicode/ucal.h, icu4c/source/i18n/unicode/unum.h
BRS task: Check non-stable API macros (U_HIDE_DRAFT_API and others)
- Some virtual methods were conditionalized with U_HIDE_DRAFT_API, that should not be done
- A couple of enum constants whose values are used to determine the size of structures had different values depending on U_HIDE_DRAFT_API; that should not happen, otherwise clients will use structs that do not match the implementation.
=> ICU-22220 BRS 73rc adjust #ifndef U_HIDE_DRAFT_API for virtual methods, fix conditionalized enums

icu4c/source/tools/icuexportdata/icuexportdata.cpp
As far as I can tell these are stable, however there are enough of them that having a way of _testing_ that the values are correct is useful.
(I do plan to use these in ICU4X via a test, one which will also test the property names and such)
=> ICU-22270 expose uproperty values in icuexportdata

icu4c/source/i18n/unicode/measunit.h
measunit.h uses std::pair, std::make_pair, and std::move, all of which are declared in the <utility> header. This still compiles because many implementations of the C++ standard library have <utility> as a transitive dependency of other C++ standard library headers; however, these transitive includes are not guaranteed to exist and will not exist in some contexts (e.g. building against LLVM's libc++ with -fmodules).
=> ICU-22298 Include <utility> in measunit.h

icu4c/source/common/unicode/unistr.h, icu4c/source/common/unistr.cpp
The main goal of this PR is to speed up and simplify the `UnicodeString::startsWith` and `UnicodeString::endsWith` functions implementations. Those functions use `UnicodeString::doCompare` under the hood. `doCompare` compares strings lexicographically, which is unnecessary when we want to know if two substrings are equal. Based on that, we can do two main optimizations:
1. Return `false` if the substrings we want to compare have different lengths. (If we use `UnicodeString::doCompare`, we can't do this because we want to know the order of the strings).
2. We can use `uprv_memcmp` for both little-endian and big-endian systems because we care only about string equality.
=> ICU-22286 Speed up substring equality comparison

.github/workflows/jekyll-gh-pages.yml, docs/Gemfile, docs/_config.yml, docs/_sass/color_schemes/light.scss
Our User Guide is published via the Github Pages feature. I noticed that updates to it have been [failing over the past 2 weeks](https://github.com/unicode-org/icu/actions/workflows/pages/pages-build-deployment).
When we set it up a couple of years ago, it was still a black box how Github would run its internal version of Jekyll to generate the static pages. Since then, the Github Actions CI framework has become popular, and it is now the [default place to generate and/or deploy Github Pages](https://github.blog/2022-08-10-github-pages-now-uses-actions-by-default/). Even the legacy mechanism is now represented as a Github Actions CI workflow, as the links above show and describe.
This PR introduces a new CI workflow that supports the deployment of our Github Pages (User Guide).
If the new …
=> ICU-22194 Add CI job to generate Github Pages using Github Actions

icu4c/source/i18n/tzfmt.cpp
Return while the status fail without checking and cause crash
=> ICU-22307 Fix crash inside TimeZone

icu4c/source/stubdata/stubdata.cpp, icu4c/source/stubdata/stubdata.h
use C++11 `alignas(16)` for desired alignment of the empty stubdata pointerTOC
=> ICU-22308 stubdata empty pointerTOC alignas(16)

icu4c/source/common/utext.cpp, icu4c/source/test/intltest/utxttest.cpp, icu4c/source/test/intltest/utxttest.h
utext_current32 should handle an access callback that changes chunk size, instead of just restoring previous chunkOffset. Per Markus suggestion (in 2021-06-16 agenda), restore chunkOffset to chunkLength-1. See discussion in the ticket comments.
Most of the work here is creating a test that uses such an access callback.
Apple ICU has been using this code for more than a year now.
=> ICU-21653 utext_current32 should handle access callback that changes chunk size

icu4c/source/i18n/dtfmtsym.cpp
Make DateFormatSymbols::assignArray handle a null srcArray without crashing (by setting dstArray = null and dstCount = 0).
See my explanation and rationale in https://unicode-org.atlassian.net/browse/ICU-21940?focusedCommentId=168805
=> ICU-21940 DateFormatSymbols::assignArray should handle null srcArray

icu4c/source/acinclude.m4, icu4c/source/config/mh-darwin-ppc, icu4c/source/tools/toolutil/pkg_genc.cpp
An attempt to build ICU on old macOS with PowerPC leads to an issue:
```
./out/tmp/icudt72b_dat.S:7:Unknown pseudo-op: .balign
./out/tmp/icudt72b_dat.S:7:Rest of line ignored. 1st junk character valued 49 (1).
```
Why? Because `as` is too old.
Anyway, switc to `.p2align 4` fix a build and allows to pass all tests.
See: https://trac.macports.org/ticket/66258
=> ICU-22211 macOS PPC should use `.p2align 4` instead `.balign 16` 

icu4c/source/tools/icuexportdata/icuexportdata.cpp
Just for binary properties exported by icuexportdata, the value for the field `uproperty_discr` is formatted in hex but forgot the `0x` prefix (see https://github.com/unicode-org/icu/commit/6046af063ddd7ed9cbab601a3c6304ad9070545d).
For example, currently, PCM.toml looks like
```
...
icu_version = "72.1"
unicode_version = "15.0"
[[binary_property]]
long_name = "Prepended_Concatenation_Mark"
short_name = "PCM"
uproperty_discr = 3F
ranges = [
[0x600, 0x605],
[0x6dd, 0x6dd],
...
```
The fix should then make it look like
```
...
icu_version = "72.1"
unicode_version = "15.0"
[[binary_property]]
long_name = "Prepended_Concatenation_Mark"
short_name = "PCM"
uproperty_discr = 0x3F
ranges = [
[0x600, 0x605],
[0x6dd, 0x6dd],
...
```
fyi @Manishearth
=> ICU-22270 Fix hex number formatting in icuexportdata

icu4c/source/stubdata/stubdata.cpp, icu4c/source/stubdata/stubdata.h
Judging from https://en.cppreference.com/w/cpp/language/alignas it should suffice to specify the alignment requirement on the struct type *declaration* (as in PR #2380), but apparently some compilers ignore it unless it is (also?) on the variable *definition*.
I also set the unused padding bytes to something useful for debugging, and cleaned up indentation a little.
=> ICU-22308 add alignas(16) to the data entry point definition

icu4c/source/i18n/unum.cpp, icu4c/source/test/cintltst/cnumtst.c
This fixes a regression from https://github.com/unicode-org/icu/pull/2139
=> ICU-22340 Fix it so that UNUM_NUMBERING_SYSTEM again always returns a RuleBasedNumberFormat.

icu4c/source/i18n/smpdtfmt.cpp, icu4c/source/test/cintltst/cdattst.c, icu4c/source/test/intltest/dtfmttst.cpp, icu4c/source/test/intltest/dtfmttst.h, icu4j/main/classes/core/src/com/ibm/icu/text/SimpleDateFormat.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/format/DateFormatTest.java
ICU-21802 was filed about a valid issue with strict parsing for a formatter set to yyyyMMdd (i.e. with numeric fields that abut). The fix in [PR-2006](https://github.com/unicode-org/icu/pull/2006) did fix the problem in the ticket, but also affected strict parsing of non-abutting numeric date fields, causing them to require exact length match, though they have traditional allowed different lengths  even for strict parsing. This causes compatibility problems for clients
The fix here preserves the intended fix for ICU-21802, while restoring the traditional (pre-ICU-71) behavior for parsing non-abutting numeric date fields. In addition to fixing https://unicode-org.atlassian.net/browse/ICU-22337, this also fixes https://unicode-org.atlassian.net/browse/ICU-22259 and likely other tickets as …
=> ICU-22337 restore strict parsing length tolerance for non-abutting numeric date fields

icu4c/source/common/propname.cpp, icu4c/source/test/intltest/ucdtest.cpp, icu4c/source/test/intltest/ucdtest.h, icu4j/main/tests/core/src/com/ibm/icu/dev/test/lang/UCharacterTest.java
The getProperty(Value)Name functions accept nameChoice values other than SHORT=0 and LONG=1, despite the C functions using enum UPropertyNameChoice for their nameChoice arguments.
Add test code, and fix a recent (unreleased) regression from ICU-22224 pull request #2324.
=> ICU-22338 getProperty(Value)Name accepts nameChoice above 1

icu4j/build.properties
Updates the version number of icu4j/build.properties from 73rc to 73_1.
Jar file changes are not needed ([previous PR 72.1](https://github.com/unicode-org/icu/pull/2227))
=> ICU-22221 BRS73GA: Update version number to 73.1

icu4c/source/data/cldr-icu-readme.txt, tools/cldr/cldr-to-icu/pom.xml
After updating the ICU4J libraries in CLDR to ICU as of 2023-04-10, I re-ran the CLDR-ICU integration to verify that there would be no data changes. There were none; but I did also update the tagged version of ICU used for CLDR-ICU integration to that same 2023-04-10 version. I also enhanced the CLDR-ICU integration instructions a bit, including info on how to run the CLDR tests on production data.
=> ICU-22221 update cldr-icu instructions, and ICU tag for integration

.github/workflows/icu_ci.yml, .github/workflows/icu_envtest.yml, .github/workflows/icu_merge_ci.yml, .github/workflows/icu_valgrind.yml
This should speed up our build process by specify a better -j value in make.
According to https://askubuntu.com/questions/1295713/make-use-of-j-option it is recommended to use twice as much as cores in a machine for the number of thread, which specified by the -j option of make during the build to better utilize the machine.
According to https://man7.org/linux/man-pages/man1/lscpu.1.html#:~:text=DESCRIPTION%20top,for%20easy%20readability%20by%20humans.  we can get the number of CPU from 'lscpu -p="CPU"'
MacOS is BSD base so we use "sysctl -a|grep "machdep.cpu.core_count"|cut -d':' -f2" to find out the number of CPU.
=> ICU-22349 Change to use just -j value in make to "not limit the number of jobs that can run simultaneously"

.ci-builds/.azure-pipelines.yml
Trying -j in the make check to see would it speed up the build process in cygwin. See https://github.com/unicode-org/icu/pull/2422 for other changes.
=> ICU-22349 Build cygwin with -j  to run multiple cores

.ci-builds/.azure-pipelines.yml
Split the 'C: MSVC x64 ARM32 ARM64 Release (VS 2019) + Distrelease ARM64' CI into two to run in parallel.
The x64 and ARM32 CI just build as how it was added in https://github.com/unicode-org/icu/pull/706
Split the  ARM64 CI build and also perform the Distrelease as how it was added in https://github.com/unicode-org/icu/pull/831
The x64 build seems required by the other two build so I have to include the x64 part in both.
This should reduce the CI to about 2/3 of the current run time with three machines building them in paralle.
=> ICU-22349 Speed up pre-merge CI

tools/cldr/lib/install-cldr-jars.sh
Without this flag, any ANSI color escape sequences in the Maven error log will be displayed in their escaped form, which isn't very readable.
=> ICU-22221 Add the -R flag to less to display ANSI colors.

CONTRIBUTING.md
#2402 was the prior update to CONTRIBUTING.md
#2415 also see
CLA section from https://github.com/unicode-org/.github/blob/main/.github/CONTRIBUTING.md
fyi @annebright
=> ICU-22309 update CONTRIBUTING.md for new process

icu4c/source/common/unicode/ures.h, icu4c/source/test/intltest/Makefile.in, icu4c/source/test/intltest/intltest.vcxproj, icu4c/source/test/intltest/intltest.vcxproj.filters, icu4c/source/test/intltest/uchar_type_build_test.cpp
This is necessary for this header file to be usable by clients that define UCHAR_TYPE as a type not compatible with char16_t, eg. uint16_t.
=> ICU-22356 Use ConstChar16Ptr to safely cast from UChar* to char16_t*

.ci-builds/.azure-exhaustive-tests.yml, .ci-builds/.azure-pipelines.yml, .github/workflows/icu_ci.yml, .github/workflows/icu_envtest.yml, .github/workflows/icu_merge_ci.yml, .github/workflows/icu_valgrind.yml, docs/processes/release/tasks/healthy-code.md, docs/processes/release/tasks/integration.md, docs/processes/rules_update.md, icu4c/source/data/cldr-icu-readme.txt, icu4c/source/test/intltest/numbertest_permutation.cpp, tools/scripts/uconfig_vars_test.py
It has been proposed that make running too many parallel jobs recently has led to resource exhaustion in our CI, so that some kind of limit would be helpful to set.
The load average 2.5 limit choosen here is simply the limit used as an example in the make documentation, as we don't really have any way of picking an initial value that's certain to be better.
https://www.gnu.org/software/make/manual/html_node/Parallel.html
See #2421
See #2422
=> ICU-22349 Use -l with make -j to limit jobs based on load average.

.github/workflows/icu_merge_ci.yml
Run the tests only on the main branch of the unicode-org/icu repository. This avoids diluting the performance charts with performance results from the maintenance branches. Also, the performance tests won't execute on forked directories anymore, on which they fail after execution anyway, thus using GitHub resources without purpose.
=> ICU-22384 Limit execution of performance tests

icu4c/source/tools/ctestfw/ctest.c
Found using gcc -fanalyze.
Code built using the following configure command:
```
../configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --datarootdir=/usr/share --docdir=/usr/share/doc/icu-73.1-r1 --htmldir=/usr/share/doc/icu-73.1-r1/html --libdir=/usr/lib64 --disable-renaming --disable-layoutex --disable-debug --disable-static --disable-tests --disable-samples build_alias=x86_64-pc-linux-gnu host_alias=x86_64-pc-linux-gnu CC=x86_64-pc-linux-gnu-gcc CFLAGS="-march=native -O2 -pipe -fanalyzer -Werror=analyzer-va-arg-type-mismatch -Werror=analyzer-va-list-exhausted -Werror=analyzer-va-list-leak -Werror=analyzer-va-list-use-after-va-end" …
```
=> ICU-22377 Fix errors found by gcc -fanalyzer

icu4c/source/tools/icuexportdata/icuexportdata.cpp
Don't read past the storageXX.size(). Refactor find-or-append into a function. Stop double-uset_close() (delete) of a set.
=> ICU-22403 Fix out-of-bounds in icuexportdata

.ci-builds/.azure-pipelines.yml
This reverts the change in e1e1c5feaf67652d9f124b23749a430d3278fe7b for only the data-filter test, which has become flaky since that change landed.
=> ICU-22322 Revert extra parallelism for data-filter test in .azure-pipelines.yml

.github/workflows/cache_retain.yml, .github/workflows/icu_ci.yml, .github/workflows/icu_envtest.yml, .github/workflows/icu_merge_ci.yml, .github/workflows/icu_valgrind.yml, .github/workflows/jekyll-gh-pages.yml, .github/workflows/maven.yaml
As described in the issue, this PR sets read-only tokens for all workflows. Only the deployment job in `jekyll-gh-pages.yml` workflow receives a few additional permissions it needs.
This protects the project from supply-chain attacks.
=> ICU-22350 Set minimal workflow token permissions

.github/workflows/icu_merge_ci.yml
This PR fixes an error in #2487 (sorry!) which caused the performance CI to fail.
I hadn't realized that the `gregtatum/github-action-benchmark` required additional permissions. Following its [documentation](https://github.com/benchmark-action/github-action-benchmark#charts-on-github-pages-1), all jobs that call this Action now have `contents` and `deployments: write` permissions.
I'm currently reusing the ICU-22350 bug ID used in #2487. Let me know if you'd rather I use a new ID and I'll edit the commits as needed.
=> ICU-22350 Fix broken performance CI

.github/workflows/icu_ci.yml, icu4c/source/python/icutools/databuilder/__main__.py, icu4c/source/test/testdata/BUILDRULES.py, icu4c/source/test/testdata/Makefile.in
1. Added github action to test against build with 
a. --enable-static, AND
b. --enable-static --disable-shared
2. Fix the issue which the test/testdata *.res build w/o ucadata.icu by using -i with the build directory..
=> ICU-22406 Fix test breakage w/ --disabled-shared

icu4c/source/Doxyfile.in
Without this flag, the full path to the source directory will be included in the output generated by Doxygen.
=> ICU-22389 Set STRIP_FROM_PATH to enable Doxygen out-of-source builds

SECURITY.md
As described in the JIRA issue, this PR adds a security policy to the unicode-org/icu repo, simply explaining how to submit a sensitive issue via JIRA.
A similar policy could be created in the unicode-org/.github repo. If created, the policy would be available in all unicode-org repos (unless "overwritten" by a policy in the repo itself). So, for example, creating one in /.github won't modify the one shown here if this PR is merged.
=> ICU-22410 Add a security policy

icu4c/source/i18n/gregocal.cpp, icu4c/source/i18n/unicode/gregocal.h
Remove pinDayOfMonth() and yearLength(int32_t year) from GregorianCalendar.
These two methods are
1. Unused by any code inside ICU, not in source/{common,i18n,test}.
2. Marked as @internal in the header.
3. Wrap inside #ifndef U_HIDE_INTERNAL_API block in the header
4. In "protected:" section.
5. No ICU4J counterpart.
The yearLength(int32_t year) dup the functionality as handleGetYearLength of the same class and that one is the correct one to be keep and used..
There is another yearLength() w/o the year as parameter should NOT be removed and still needed internally.
=> ICU-22421 Remove two unused internal methods in gregorian cal

icu4c/source/i18n/ucal.cpp, icu4c/source/test/cintltst/ccaltst.c
This is fixing a 73-1 regression. The test work in 72-maint
The fix came from https://phabricator.services.mozilla.com/D180796
and mentioned in https://unicode-org.atlassian.net/browse/ICU-22412 by @anba
=> ICU-22412 Fix C API ucal_(g|s)etGregorianChange for iso8601 calendar

icu4c/source/i18n/transreg.cpp, icu4c/source/i18n/transreg.h, icu4j/main/classes/translit/src/com/ibm/icu/text/AnyTransliterator.java
WIDTH_FIX instance could be lazily initialized, because it's used only if transliterate() is called on the AnyTransliterator instance, but apparently not used by other Transliterator instance.
=> ICU-22390 Transliterator.<clinit> can be optimized - part 2

.github/workflows/cache_retain.yml, .github/workflows/icu_ci.yml, .github/workflows/icu_envtest.yml, .github/workflows/icu_merge_ci.yml, .github/workflows/icu_valgrind.yml, .github/workflows/jekyll-gh-pages.yml, .github/workflows/maven.yaml
=> ICU-22354 Update actions and platforms in GitHub Actions workflows

.github/workflows/icu_merge_ci.yml
Revert the change of benchmark-action in
https://github.com/unicode-org/icu/pull/2428 which cause post merge test brekage.
See https://github.com/unicode-org/icu/actions/runs/5393383252/jobs/9793048045 for the problem
=> ICU-22354 Revert benchmark-action changes

icu4c/source/i18n/calendar.cpp, icu4c/source/i18n/unicode/calendar.h, icu4c/source/test/intltest/caltest.cpp, icu4c/source/test/intltest/caltest.h
Make the calling of clear(UCAL_MONTH or UCAL_ORDINAL_MONTH) clear both fields.
=> ICU-22424 Fix Calendar::clear(UCAL_MONTH)

icu4c/source/i18n/calendar.cpp, icu4c/source/i18n/iso8601cal.cpp, icu4c/source/test/cintltst/ccaltst.c, icu4c/source/test/intltest/caltest.cpp, icu4c/source/test/intltest/caltest.h, icu4j/main/classes/core/src/com/ibm/icu/util/Calendar.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/calendar/CalendarRegressionTest.java
The Calendar constructor already take care of the fw override. We should not set the first day of week for iso8601 to Monday if we have a fw keyword/type in the locale.
Also fix a bug which caused by an incorrect calendar= keyword extraction code which cannot handle more than one keyword/type, by replacing the correct one from Locale class.
=> ICU-22434 Not calling setFirstDayOfWeek(MONDAY) if the locale has fw

.github/workflows/maven.yaml
This PR fixes an issue observed by @srl295 in https://github.com/unicode-org/icu/pull/2487#discussion_r1268432171 (which fixed ICU-22350) by giving the job `packages:write` permissions.
My apologies, I hadn't noticed the workflow deployed to GitHub Packages, I thought it deployed to Maven Central.
=> ICU-22350 Give maven.yml packages:write

icu4c/source/i18n/ethpccal.h, icu4c/source/test/intltest/caltest.cpp
ICU4J has that as part of public API but ++ is private so we should sync to the ICU4J one.
=> ICU-22442 Sync the spelling of NEHASSA to ICU4J NEHASSE

icu4j/main/classes/core/src/com/ibm/icu/impl/CalType.java, icu4j/main/classes/core/src/com/ibm/icu/util/Calendar.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/calendar/CalendarRegressionTest.java
Remove CalType enum value UNKNOWN and use null for unknown CalType This value is an internal enum and the only place use it is inside Calendar.java Use null for that instead (same as C++)
=> ICU-22444 Remove "unknown" from Calendar.getKeywordValuesForLocale

icu4j/main/classes/core/src/com/ibm/icu/util/CECalendar.java, icu4j/main/classes/core/src/com/ibm/icu/util/Calendar.java, icu4j/main/classes/core/src/com/ibm/icu/util/ChineseCalendar.java, icu4j/main/classes/core/src/com/ibm/icu/util/CopticCalendar.java, icu4j/main/classes/core/src/com/ibm/icu/util/EthiopicCalendar.java, icu4j/main/classes/core/src/com/ibm/icu/util/GregorianCalendar.java, icu4j/main/classes/core/src/com/ibm/icu/util/HebrewCalendar.java, icu4j/main/classes/core/src/com/ibm/icu/util/IndianCalendar.java, icu4j/main/classes/core/src/com/ibm/icu/util/IslamicCalendar.java, icu4j/main/classes/core/src/com/ibm/icu/util/PersianCalendar.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/calendar/CalendarRegressionTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/calendar/InTemporalLeapYearTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/calendar/OrdinalMonthTest.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/calendar/TemporalMonthCodeTest.java
=> ICU-22407 Implement Java Temporal Calendar API

icu4c/source/common/BUILD.bazel, icu4c/source/common/common.vcxproj, icu4c/source/common/common.vcxproj.filters, icu4c/source/common/common_uwp.vcxproj, icu4c/source/common/sources.txt, icu4c/source/common/ulocbuilder.cpp, icu4c/source/common/unicode/ulocbuilder.h, icu4c/source/test/cintltst/Makefile.in, icu4c/source/test/cintltst/cintltst.vcxproj, icu4c/source/test/cintltst/cintltst.vcxproj.filters, icu4c/source/test/cintltst/cutiltst.c, icu4c/source/test/cintltst/ulocbuildertst.c, icu4c/source/test/depstest/dependencies.txt
=> ICU-22365 C API for ULocaleBuilder

icu4c/source/common/locid.cpp, icu4c/source/common/loclikelysubtags.cpp, icu4c/source/common/uniquecharstr.h
UniqueCharStrings was designed to ref to strings return by resource bundle which the strings will not be freed and is used in two places- inside locid.cpp and loclikelysubtags.cpp
But two months ago I misuse that in https://github.com/unicode-org/icu/pull/2458 to also store stack allocated UnicodeString that 1) may not be null terminated and 2) will be freed from the stack before the destruction of UniqueCharStrings. We discover the issue while work on https://github.com/unicode-org/icu/pull/2538
This PR has been changed several time because I found the fix is not safe nor efficient due to the fact that 
a. While the data came from the ResourceBundle, we should use the internal data without allocate unecessary memory.
b. While the data is generated from some computation, we need to keep …
=> ICU-22453 Fix non null terminated buffer issue.

docs/userguide/boundaryanalysis/break-rules.md, docs/userguide/dev/rules_update.md, icu4c/source/tools/genbrk/genbrk.cpp
See comments on #2492 and email thread with Andy titled `genbrk`.
=> ICU-22404 Improve documentation of segmentation rules

icu4c/source/i18n/uspoof.cpp, icu4c/source/test/intltest/itspoof.cpp, icu4j/main/classes/core/src/com/ibm/icu/text/SpoofChecker.java, icu4j/main/tests/core/src/com/ibm/icu/dev/test/text/SpoofCheckerTest.java
The _skeleton_ operation changes in Unicode Version 15.1, see https://www.unicode.org/reports/tr39/tr39-27.html#Confusable_Detection.
=> ICU-22404 Strip default ignorable code points in the skeleton for confusable detection

icu4c/source/common/BUILD.bazel, icu4c/source/common/common.vcxproj, icu4c/source/common/common.vcxproj.filters, icu4c/source/common/common_uwp.vcxproj, icu4c/source/common/sources.txt, icu4c/source/common/ulocale.cpp, icu4c/source/common/ulocbuilder.cpp, icu4c/source/common/unicode/ulocale.h, icu4c/source/test/cintltst/Makefile.in, icu4c/source/test/cintltst/cintltst.vcxproj, icu4c/source/test/cintltst/cintltst.vcxproj.filters, icu4c/source/test/cintltst/cutiltst.c, icu4c/source/test/cintltst/ulocaletst.c, icu4c/source/test/depstest/dependencies.txt
=> ICU-22435 Add C API for Locale 

CONTRIBUTING.md, LICENSE, README.md
* See:  https://github.com/unicode-org/.github/issues/6
=> ICU-22309 update to license v3, readme

icu4c/source/common/locid.cpp, icu4c/source/test/intltest/loctest.cpp
override the count() returned by Locale::createUnicodeKeyword by considering  extension other than -u- such as  -x-, -t-.
=> ICU-22457 Fix the count() of StringEnumeration returned by createUnicodeKeywords 

icu4c/source/common/brkeng.cpp, icu4c/source/common/brkeng.h, icu4c/source/common/brkiter.cpp, icu4c/source/common/dictbe.cpp, icu4c/source/common/dictbe.h, icu4c/source/common/rbbi.cpp, icu4c/source/common/rbbi_cache.cpp, icu4c/source/common/unicode/brkiter.h, icu4c/source/common/unicode/rbbi.h, icu4c/source/test/intltest/lstmbetst.cpp, icu4c/source/test/intltest/lstmbetst.h, icu4c/source/test/intltest/rbbitst.cpp, icu4c/source/test/intltest/rbbitst.h
Implement the ExternalBreakEngineAPI and change the RBBI to use it internally. Add test cases to show how to do that in two fake break engines.
=> ICU-22342 Implement ExternalBreakEngineAPI

icu4c/source/common/uloc_tag.cpp, icu4c/source/test/cintltst/cloctst.c
=> ICU-22475 Fix double free in Locale under OOM

.github/workflows/scorecard.yml, README.md
As mentioned in the JIRA issue, the Scorecard Action will monitor the project's security posture and populate its Security Dashboard with actionable suggestions.
There is also a badge that can be added to the project's README showing the project's current score: [![OpenSSF Scorecard](https://api.securityscorecards.dev/projects/github.com/unicode-org/icu/badge)](https://securityscorecards.dev/viewer/?uri=github.com/unicode-org/icu). I haven't added it yet because the README currently only has build status badges and I didn't want to impose. However, if you'd like me to add the badge, just say the word (including where you'd like it to be) and I'll add it to the PR.
=> ICU-22423 Add OpenSSF Scorecard Action

icu4c/source/test/fuzzer/collator_compare_fuzzer.cpp
Test only first 4K bytes of data, which means compare two UnicodeString each with 1024 Unicodes at most.
Avoid finding timeout issue due to large amount of data.
=> ICU-22479 Limit the collator_compare_fuzzer

icu4c/source/common/ulocbuilder.cpp, icu4c/source/common/unicode/ulocbuilder.h, icu4c/source/test/cintltst/ulocbuildertst.c
Add two methods related to ULocale to ULocaleBuilder API
void ulocbld_adoptULocale(ULocaleBuilder* builder, ULocale* locale);
ULocale* ulocbld_buildULocale(ULocaleBuilder* builder, UErrorCode* err);
ICU TC approved this in 2023-08-31
=> ICU-22365 Add two ULocale methods to ULocaleBuilder

icu4c/source/i18n/unicode/ucol.h, icu4j/main/collate/src/main/java/com/ibm/icu/text/RuleBasedCollator.java
Make the document clear that for a Collator object normally created the default setting is not a specific constant value but depends on the locale, and therefore the value store in the resource as the data for that locale.
See the background information about the historical misunderstanding in 
* **ECMA402** (since 2012 see https://402.ecma-international.org/1.0/#sec-10.1.1.1 the ignorePuncation therefore was design to default to "false" always, instead of undefined or locale dependent . Issues in https://github.com/tc39/ecma402/issues/832 fix in https://github.com/tc39/ecma402/pull/833 )
* **V8** (since 2018-08-08 by gsathya@ - see line 508-511 in https://source.chromium.org/chromium/_/chromium/v8/v8.git/+/363fe1eb66371e55971cbde815369182189cf19f:src/objects/js-collator.cc;dlc=18a0a9746f3 …
=> ICU-22489 Clarify the default setting of Collator

.github/workflows/icu_ci.yml, icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/calendar/DataDrivenCalendarTest.java, icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/format/DataDrivenFormatTest.java, icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/format/DateFormatTest.java, icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/format/TestMessageFormat.java, icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/message2/Mf2FeaturesTest.java, icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/serializable/CompatibilityTest.java
I hope this workaround unblocks PRs from failing Java tests. 
The issue for the underlying problem is https://unicode-org.atlassian.net/browse/ICU-22505
=> ICU-22325 Disable tests as workaround for failures following CI changes

icu4c/source/i18n/nfsubs.cpp, icu4c/source/i18n/unicode/rbnf.h, icu4c/source/i18n/unum.cpp, icu4c/source/test/cintltst/cnumtst.c, icu4c/source/test/intltest/itrbnf.cpp, icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/format/RbnfTest.java, icu4j/main/core/src/main/java/com/ibm/icu/text/NFSubstitution.java, icu4j/main/core/src/main/java/com/ibm/icu/text/RuleBasedNumberFormat.java
- Changed the C interface so that calling unum_open(UNUM_DURATION) produces a formatter that uses a MeaureFormat under the covers instead of a RuleBasedNumberFornmat.
- Changed the C++ and Java interfaces to that the URBNF_DURATION ruleset is marked deprecated.
- Fixed a bug in RuleBasedNumberFormat in both Java and C++ that caused the existing duration-formatting rules to produce bogus results when used on a non-integral value.
=> ICU-22313 Various fixes for duration formatting:

icu4c/source/test/intltest/caltest.cpp
Fix broken test mistakenly landed in
https://github.com/unicode-org/icu/pull/2274
Some important steps were accidentally removed in the last landing.
The corresponding Java tests at
https://github.com/unicode-org/icu/blob/d8659b476d4703b18bb9ea040798c1e62ff3329e/icu4j/main/core/src/test/java/com/ibm/icu/dev/test/calendar/InTemporalLeapYearTest.java#L91
=> ICU-22512 Fix broken TestHebrewCalendarInTemporalLeapYear

icu4c/source/i18n/calendar.cpp
Fix DateFormat::format issue, format internally call Calendar:: setTime and setTimeInMillis  and if the date is NaN it will cause problem. The two if check will be false because nan is not a number and compare with a constant will always be false.
=> ICU-22508 Reject NaN as input to Calendar::setTimeInMillis

icu4c/source/i18n/reldtfmt.cpp, icu4c/source/test/fuzzer/date_format_fuzzer.cpp
This is a follow up PR of https://github.com/unicode-org/icu/pull/2608 to reject the unsupported dateStyle and avoid infinty loop.
Revert back the fuzzer code back to pre PR 2608 then add the new call to ensure that both valid and invalid enum will be tested suggested by Rich
=> ICU-22509 Fix the RelativeDateFormat to reject unsupported dateStyle

icu4c/source/i18n/chnsecal.cpp, icu4c/source/i18n/chnsecal.h, icu4c/source/test/intltest/caltest.cpp, icu4c/source/test/intltest/caltest.h
Rewrite the recursive call to while loop to avoid stack overflow when the two values have big gap.
Include tests to verify the problem in unit test.
=> ICU-22507 Fix stack overflow in ChineseCalendar::isLeapMonthBetween

.github/workflows/cache_retain.yml, .github/workflows/icu_ci.yml, .github/workflows/icu_merge_ci.yml
We still have instances of CI jobs needing to be rerun because the build process dependencies are not being cached. That gives us errors like "...dependencies could not be resolved: Failed to read artifact descriptor..." or "Could not transfer artifact... Connection timed out (Read failed)", as seen today: https://github.com/unicode-org/icu/pull/2601#issuecomment-1721499440
This PR:
* chooses the job with the most build dependencies to create the artifact cache, and the other jobs have a read-only view of that cache.
* changes the Maven target for building from `install` to `verify` so that no artifacts built from the current snapshot of the ICU codebase are stored in the cache, while still ensuring `integration-tests` is run
* gets rid of redundant CI jobs for ICU4J as a partial cleanup
=> ICU-22324 Allow single Maven cache creation and multiple read-only usage

icu4c/source/i18n/units_converter.cpp, icu4c/source/test/intltest/units_test.cpp
Correcting the conversion from gasoline-equivalent units to kilograms-per-meter-squared-per-second is essential. The issue doesn't lie with the Java segment, as Java code employs a more appropriate method for handling unit constants.
=> ICU-22463 Fix the conversion from gasoline-equivalent units to kilograms-per-meter-squared-per-second

icu4j/build.properties, icu4j/demos/pom.xml, icu4j/main/charset/pom.xml, icu4j/main/collate/pom.xml, icu4j/main/common_tests/pom.xml, icu4j/main/core/pom.xml, icu4j/main/currdata/pom.xml, icu4j/main/framework/pom.xml, icu4j/main/icu4j/pom.xml, icu4j/main/langdata/pom.xml, icu4j/main/localespi/pom.xml, icu4j/main/pom.xml, icu4j/main/regiondata/pom.xml, icu4j/main/translit/pom.xml, icu4j/perf-tests/pom.xml, icu4j/pom.xml, icu4j/releases_tools/api_reports.sh, icu4j/samples/pom.xml, icu4j/tools/build/pom.xml, icu4j/tools/misc/pom.xml
Removing `-SNAPSHOT` means we can't publish the cldr utilities more than once per ICU version.
We will only remove `-SNAPSHOT` in the `main-<ver>` branch, closer to the release time.
=> ICU-22324 Mavenization, add -SNAPSHOT back to the maven version

icu4c/source/i18n/collationbuilder.cpp, icu4c/source/test/intltest/regcoll.cpp, icu4c/source/test/intltest/regcoll.h, icu4j/main/collate/src/main/java/com/ibm/icu/impl/coll/CollationBuilder.java, icu4j/main/collate/src/test/java/com/ibm/icu/dev/test/collator/CollationRegressionTest.java
To avoid very slow return from the constructor, we return an error while the Collation rule expand too big.
Add a limit constant to limit to the number of loop needed for 8 Hanguls.
Necessary number of loops: H(0)=0; H(i)=3H(i-1)+2.
Where i is the length of Hangul in the rule.
H(1) = 2, H(2) = 8, H(3)=26, H(4)=80, H(5) = 242 ...
=> ICU-22517 Limit the closure expansion loop and return error

icu4c/source/i18n/calendar.cpp, icu4c/source/test/intltest/tztest.cpp, icu4c/source/test/intltest/tztest.h, icu4j/main/core/src/main/java/com/ibm/icu/util/Calendar.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/timezone/TimeZoneTest.java
ECMA402 now allow offset timezone from -23:59 to 23:59. We need to lower the minimum ZONE_OFFSET value to -23:59
=> ICU-22526 Allow GMT-23:59 time zone

docs/devsetup/java/eclipse-setup-for-java-developers/index.md, docs/devsetup/java/maven.md, docs/userguide/icu4j/index.md
I did a manual run of the ["Deploy User Guide" workflow in my personal fork](https://github.com/echeran/icu/actions/workflows/jekyll-gh-pages.yml) so that you can preview the effects of the changes.
- [Root of deployed site](https://echeran.github.io/icu/)
- ICU4J Readme: https://echeran.github.io/icu/userguide/icu4j/
- Maven Setup for Java: https://echeran.github.io/icu/devsetup/java/maven.html
=> ICU-22324 Add docs for Maven usage

docs/userguide/icu/services.md
https://unicode-org.atlassian.net/browse/ICU-22529
All external links were incorrectly pointing to the current directory, and with .md as the file extension.
Changed all links to be "../" without any extension
=> ICU-22529 Update services.md

icu4c/source/common/putil.cpp, icu4c/source/test/depstest/dependencies.txt
=> ICU-22541 Fix MacOS 14 default timezone issue

icu4c/source/i18n/collationbuilder.cpp, icu4c/source/test/fuzzer/locale_util.h
Reduce the error return from about 100s to 30s to avoid fuzzer 60s timeout error.
Also add a include file to fix uint8_t build breakage.
=> ICU-22548 Reduce the loop limit to fail faster

icu4c/source/common/unistr.cpp, icu4c/source/i18n/calendar.cpp, icu4c/source/i18n/datefmt.cpp, icu4c/source/i18n/dtfmtsym.cpp, icu4c/source/i18n/formatted_string_builder.cpp, icu4c/source/i18n/gregoimp.cpp, icu4c/source/i18n/gregoimp.h, icu4c/source/i18n/smpdtfmt.cpp, icu4c/source/i18n/unicode/calendar.h, icu4c/source/i18n/unicode/formattednumber.h, icu4c/source/i18n/unicode/simplenumberformatter.h
This improves date formatting performance to be 1.5-2x as fast.
<details>
<summary>Script to generate pattern char lookup table</summary>
```js
const chars = [
0x47, 0x79, 0x4D, 0x64, 0x6B, 0x48, 0x6D, 0x73, 0x53, 0x45,
0x44, 0x46, 0x77, 0x57, 0x61, 0x68, 0x4B, 0x7A, 0x59, 0x65,
0x75, 0x67, 0x41, 0x5A, 0x76, 0x63, 0x4c, 0x51, 0x71, 0x56,
0x55, 0x4F, 0x58, 0x78, 0x72, 0x62, 0x42,
0x3a,
];
process.stdout.write(' '.repeat(7));
for (let c = 0; c < 128; c++) {
if (c % 16 == 0) process.stdout.write('\n'+' '.repeat(7));
process.stdout.write(String(chars.indexOf(c)).padStart(3)+',');
}
process.stdout.write('\n');
```
</details>
<details>
<summary>Benchmarking program</summary>
```cpp
#include <chrono>
#include <iostream>
#define U_SHOW_CPLUSPLUS_API 1
#include "unicode/smpdtfmt.h"
#include …
```
=> ICU-22528 Improve date formatting performance

docs/userguide/datetime/timezone/index.md
**Note**: I am not sure if doc PRs also require the creation of a JIRA issue. If yes, let me know and I can do that as well and adjust the commit message.
**Update**: Looks like the CLI is requiring that. Is there a generic JIRA document fix ticket that can be referenced?
**Final Update:** I found another PR was the author was advised to reference ICU-22323 so I did the same now.
=> ICU-22323 Typo fixes in docs for ICU TimeZone Classes

icu4c/source/test/depstest/dependencies.txt, icu4c/source/test/fuzzer/locale_util.h, icu4j/demos/pom.xml, icu4j/main/charset/pom.xml, icu4j/main/collate/pom.xml, icu4j/main/common_tests/pom.xml, icu4j/main/core/pom.xml, icu4j/main/currdata/pom.xml, icu4j/main/framework/pom.xml, icu4j/main/icu4j/pom.xml, icu4j/main/langdata/pom.xml, icu4j/main/localespi/pom.xml, icu4j/main/regiondata/pom.xml, icu4j/main/translit/pom.xml, icu4j/perf-tests/pom.xml, icu4j/pom.xml, icu4j/samples/pom.xml, icu4j/tools/build/pom.xml, icu4j/tools/misc/pom.xml, icu4j/tools/utilities-for-cldr/pom.xml
=> ICU-22326 BRS: Version number update for GA

icu4c/source/i18n/calendar.cpp, icu4c/source/i18n/gregocal.cpp, icu4c/source/i18n/unicode/calendar.h, icu4c/source/i18n/unicode/gregocal.h, icu4c/source/test/intltest/incaltst.cpp, icu4c/source/test/intltest/incaltst.h, icu4j/main/core/src/main/java/com/ibm/icu/util/Calendar.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/calendar/CalendarRegressionTest.java
The computation in IslamicUmalquraCalendar is slower than others, if the days is more than 10,000 years from the epoch, we just return error to avoid hang.
=> ICU-22513 Return error if days is too large in IslamicUmalquraCalendar

icu4c/source/common/loclikelysubtags.cpp
This is the first working prototype. Possible future work (unclear if we should block this PR):
1. Make sure that there is a test that fails when macroregions aren't being loaded (removing them does not seem to cause any test failures in intltest, which is concerning)
2. Convert the data-consistency assertion to a unit test
3. Port this change to Java
=> ICU-22559 Hardcode the macroregions and add a debug assertion

icu4c/source/test/cintltst/cldrtest.c
=> ICU-22326 logKnownIssue skip for exhaustive test failures with kxv(_Deva)? day/month names

icu4c/source/common/loclikely.cpp, icu4c/source/common/unicode/locid.h, icu4c/source/common/unicode/uloc.h, icu4c/source/test/cintltst/cloctst.c, icu4c/source/test/intltest/loctest.cpp, icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/util/ULocaleTest.java, icu4j/main/core/src/main/java/com/ibm/icu/util/ULocale.java
Also fix ICU-22546 to correct the comments in the API doc and add additional unit tests
=> ICU-22547 fix addLikelySubtags for 4 chars script code

docs/processes/release/tasks/versions.md
=> ICU-22533 Don't mention 'Release Candidate' in javadoc

icu4c/source/test/fuzzer/calendar_fuzzer.cpp
Limit to 1000 bytes of valid test data so the fuzzer will not timeout because of running many operations.
=> ICU-22563 Limit the size for calendar fuzzer

icu4c/source/test/fuzzer/Makefile.in, icu4c/source/test/fuzzer/rule_based_break_iterator_fuzzer.cpp
=> ICU-22549 Add RuleBasedBreakIterator fuzzer

icu4c/source/test/fuzzer/Makefile.in, icu4c/source/test/fuzzer/date_time_pattern_generator_fuzzer.cpp
=> ICU-22549 Add DateTimePatternGenerator fuzzer

.github/workflows/icu4c.yml, .github/workflows/icu4j.yml, .github/workflows/icu_common.yml, .github/workflows/icu_docs.yml, .github/workflows/icu_valgrind.yml, .github/workflows/jekyll-gh-pages.yml
Testing PRs in personal fork:
- [docs only change](https://github.com/echeran/icu/pull/55)
- [ICU4C only change](https://github.com/echeran/icu/pull/56)
- [ICU4J only change](https://github.com/echeran/icu/pull/57)
=> ICU-22314 Refactor GH CI jobs into workflows triggered by modified paths

icu4c/source/test/fuzzer/Makefile.in, icu4c/source/test/fuzzer/uprop_fuzzer.cpp
=> ICU-22549 Add Fuzzer for Unicode property API

icu4c/source/test/fuzzer/Makefile.in, icu4c/source/test/fuzzer/number_formatter_fuzzer.cpp
=> ICU-22549 Add fuzzer for NumberFormatter

icu4c/source/test/fuzzer/timezone_create_fuzzer.cpp
The bug was filed because the fuzzer test data is very large and take a long time to run. Not an infinity loop. This PR limit the data to at most 2000 bytes so it will complete in reasonable amount of time.
=> ICU-22589 Avoid timeout in TimeZone test

icu4c/source/common/rbbinode.cpp, icu4c/source/common/rbbinode.h, icu4c/source/test/intltest/rbbitst.cpp, icu4c/source/test/intltest/rbbitst.h
The problem was found by fuzz testing.
A rule consisting of a long literal string produces a large, unbalanced parse tree, one node per string element. Deleting the tree was recursive, once per node, resulting in deep recursion.
This PR changes node deletion to use an iterative (non-recursive) approach.
This change only affects rule building. There is no change to the RBBI run time using pre-built rules.
=> ICU-22584 Fix RBBI rule builder stack overflow.

icu4c/source/common/rbbiscan.cpp, icu4c/source/test/intltest/rbbitst.cpp, icu4c/source/test/intltest/rbbitst.h
=> ICU-22581 Fix RBBI Leakage

icu4c/source/common/rbbiscan.cpp, icu4c/source/test/intltest/rbbiapts.cpp, icu4c/source/test/intltest/rbbiapts.h, icu4j/main/core/src/main/java/com/ibm/icu/text/RBBIRuleScanner.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/rbbi/RBBIAPITest.java
=> ICU-22580 Address infinity loop in RBBI

icu4c/source/common/rbbinode.cpp, icu4c/source/test/intltest/rbbitst.cpp
=> ICU-22584 Fix derefence of nullptr

icu4c/source/common/rbbiscan.cpp, icu4c/source/test/intltest/rbbitst.cpp, icu4c/source/test/intltest/rbbitst.h, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/rbbi/RBBITest.java
=> ICU-22585 Fix infinity loop while unicode set contains single surrogate

icu4c/source/common/rbbiscan.cpp, icu4c/source/test/intltest/rbbitst.cpp, icu4c/source/test/intltest/rbbitst.h, icu4j/main/core/src/main/java/com/ibm/icu/text/RBBIRuleScanner.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/rbbi/RBBITest.java
=> ICU-22579 Fix Null deref while Unicode Set only has string

.github/workflows/icu4c.yml, docs/userguide/icu4c/build.md, icu4c/build_qnx/build-hooks, icu4c/source/Doxyfile.in, icu4c/source/common/unicode/platform.h, icu4c/source/config/mh-solaris, icu4c/source/configure, icu4c/source/configure.ac, icu4c/source/test/depstest/dependencies.txt, icu4c/source/test/hdrtst/testinternalheaders.sh, tools/unicode/c/CMakeLists.txt, tools/unicode/c/genregexcasing/Makefile
=> ICU-21107 Update ICU4C minimum standard version from C++11 to C++17

icu4c/source/common/rbbinode.cpp, icu4c/source/common/rbbinode.h, icu4c/source/common/rbbitblb.cpp, icu4c/source/test/intltest/rbbitst.cpp, icu4c/source/test/intltest/rbbitst.h, icu4j/main/core/src/main/java/com/ibm/icu/text/RBBINode.java, icu4j/main/core/src/main/java/com/ibm/icu/text/RBBITableBuilder.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/rbbi/RBBITest.java
Limit the recursive call of flattenVariables to maximum depth 4000 since Java on my machine throw stack overflow exception around 4300.
=> ICU-22602 Fix stack overflow inside flattenVariables

icu4c/source/i18n/tznames_impl.cpp, icu4c/source/test/fuzzer/Makefile.in, icu4c/source/test/fuzzer/time_zone_names_fuzzer.cpp
=> ICU-22549 Add TimeZoneNames fuzzer

icu4c/source/i18n/smpdtfmt.cpp, icu4c/source/test/cintltst/cdattst.c, icu4c/source/test/intltest/dtfmttst.cpp, icu4c/source/test/intltest/dtfmttst.h
Copy the test from https://github.com/unicode-org/icu/pull/2747
This is my counter proposal for #2747 because the crash could still happen via C++ interface.
=> ICU-22609 Fix nulldef w/ bogus locale in DateFormat::create*

icu4c/source/test/fuzzer/Makefile.in, icu4c/source/test/fuzzer/dtfmtsym_fuzzer.cpp
=> ICU-22549 Add DateFormatSymbols fuzzer

icu4c/source/test/fuzzer/break_iterator_fuzzer.cpp, icu4c/source/test/fuzzer/collator_compare_fuzzer.cpp, icu4c/source/test/fuzzer/date_format_fuzzer.cpp, icu4c/source/test/fuzzer/date_time_pattern_generator_fuzzer.cpp
We found bogus locale cause crash in DateFormat so here we enhance the fuzzer to also test locale name which are not return by the available locale list.
=> ICU-22549 Improve fuzzer to test more locale

icu4c/source/config/dist.mk
ICU-22601
- 'git archive' works on a subtree so did not include LICENSE
- we copy the LICENSE file from the build dir
broken by ICU-22309
=> ICU-22601 v74.2 fix dangling LICENSE file

icu4c/source/i18n/calendar.cpp
The definition of `kOneDay` is `1.0 * U_MILLIS_PER_DAY` so there's no reason whatsoever to not just use `U_MILLIS_PER_DAY` directly here.
=> ICU-22532 Compiler warning: conversion from 'double' to 'int32_t'

icu4c/source/test/fuzzer/break_iterator_fuzzer.cpp, icu4c/source/test/fuzzer/collator_compare_fuzzer.cpp, icu4c/source/test/fuzzer/date_format_fuzzer.cpp, icu4c/source/test/fuzzer/date_time_pattern_generator_fuzzer.cpp
Reland PR2770 w/ the fix that null termination the input to Locale constuctor.
=> ICU-22549 Reland PR2770 w/ fix

icu4c/source/test/fuzzer/collator_compare_fuzzer.cpp
Remove the adjustment of data pointer to avoid buffer-overflow 
Fix bug https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=65632
=> ICU-22549 Fix incorrect pointer in fuzzer

icu4c/source/i18n/plurrule.cpp, icu4c/source/test/intltest/plurults.cpp, icu4c/source/test/intltest/plurults.h
=> ICU-22626 Fix leakage when 2 '=' in PluralRules

.bazelrc
This is copied (with C11 added) from:
https://github.com/tensorflow/tensorflow/blob/v2.15.0/.bazelrc
There were until now no versions specified at all, relying on the default (or commandline overrides) to be sufficiently recent.
=> ICU-21107 Specify language standard versions C11 & C++17 also for Bazel

icu4c/source/common/util_props.cpp, icu4c/source/i18n/plurrule.cpp, icu4c/source/test/depstest/dependencies.txt, icu4c/source/test/intltest/plurults.cpp, icu4c/source/test/intltest/plurults.h, icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/format/PluralRulesTest.java
Fix the crash when the PluralRuleParser::parse hit a long number value in the rule.
Also fix parseNumber so it will not trigger undefined sanitizer
=> ICU-22638 Use parseNumber to fix buffer-overflow

icu4c/source/i18n/timezone.cpp, icu4c/source/test/intltest/tztest.cpp, icu4j/main/core/src/main/java/com/ibm/icu/impl/ZoneMeta.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/timezone/TimeZoneTest.java
The old code use NumberFormat to parse and have the following problem
1. It accept non ASCII digits when the default locale is in a locale which use native non ASCII digits
2. It accept timezone offset in Scientific notation such as GMT-4E23 or GMT-2E03 which should be rejected
3. It may cause integer overflow in case 3 such as GMT-4E58
This PR remove the NumberFormat::parse dependency
=> ICU-22637 Rewrite custom timezone parser

icu4c/source/common/rbbiscan.cpp, icu4c/source/test/intltest/rbbitst.cpp, icu4c/source/test/intltest/rbbitst.h, icu4j/main/core/src/main/java/com/ibm/icu/text/RBBIRuleScanner.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/rbbi/RBBITest.java
To avoid overflow the parsing, we now return U_BRK_RULE_SYNTAX if the status value is in the rule is too large and overflow the int32_t
=> ICU-22636 Return U_BRK_RULE_SYNTAX when status number is too large

icu4c/source/common/uloc.cpp
This was added by commit a998c7cac4d53415e8e699717fc641d6617c14b3 and must surely be a mistake. The old code that was replaced used the macro parameter name `id` but the new code replacing it instead (without any explanation) used the variable name `localeID` which at that point in time was the variable name that all invocations of the macro used as the argument (so the two names happened to be interchangeable in this context).
=> ICU-22520 Bugfix: Use macro parameter name instead of variable name

icu4c/source/tools/tzcode/Makefile.in, icu4c/source/tools/tzcode/zic.c
This is already set in `Makefile.in` and therefore results in a macro redefined warning if also defined in the source file. It seems that setting this in the Makefile was how it was originally intended do be done (but then it was just never updated there).
=> ICU-22532 Move the definition of _POSIX_C_SOURCE to the Makefile

icu4c/source/i18n/plurrule.cpp, icu4c/source/test/intltest/plurults.cpp
Not calling (int64_t)source if source is out of the range of int64_t
=> ICU-22638 Fix cast overflow issue

icu4c/source/test/intltest/rbbitst.cpp, icu4c/source/test/intltest/rbbitst.h
Usage: `.\icu4c\source\test\intltest\x64\Release\intltest.exe
"rbbi/RBBITest/TestMonkey@type=sent seed=1729 loop=20 scalars_only export=meow"`
produces a file meow_sent.txt with
```
÷ 1D5FE × 3001 × 11C53 × A949 × 3167 × 202F × 0455 × 04A4 × 12F1B × 1094 × 1113C × E7E7 × FE52 × FE52 ÷ 14A92 × 1D794 × FE18 × 2029 ÷ 1944 ÷ 10EBF × 19D2 × 2024 × 1680 × 0085 ÷ 0330 × A902 × FF0E × 0437 × 206B × 041B × 111D4 × 07F9 × FE11 × 765F × 2E1C × 111CD ÷ 3DF0 × 2068 × 202D × 1E2F6 × 112F7 × 1144B ÷ 125F6 × 3000 × 2E22 × 1343A × 002E × 2062 × 116C7 × 13434 × 208E × 01B6 × FF0E × 1122F × 0031 × FF24 × 11A92 × 1134C × FE48 × 11A02 × 14E1E × FF64 × 1D471 × 1D8B × 000D ÷ 814B × 1680 × 003A × 2008 × 2C64 × FE52 ÷ 6E15 × FE47 × 0DD8 × 1E945 × 10400 × 1C3C ÷ 2C6F × 0E38 × 002E × 1E66 × 060C × 1CF0C × FF0D × …
```
=> ICU-22518 Export monkeys

icu4c/source/i18n/tznames_impl.cpp, icu4c/source/test/intltest/tzfmttst.cpp, icu4c/source/test/intltest/tzfmttst.h
Add tests and avoid assertion when the ID has non-ASCII
=> ICU-22615 Test TimeZoneNames API will not assert with non ASCII.

icu4c/source/common/loclikely.cpp
This is to facilitate further refactoring of the locale code, goto doesn't play all too well with C++ memory handling.
=> ICU-22520 Refactor code to remove the use of goto for error handling

docs/design/normalization/custom.md
Move https://icu.unicode.org/design/normalization/custom
to GitHub Pages markdown at docs/design/normalization/custom.md
Started with https://codebeautify.org/html-to-markdown
followed by fixing lists, headings, links, some code style.
Copied the two tables from the HTML source view of the Sites page, unescaped their HTML, and fiddled a little with the style. Could probably use more work to minimize cell padding/spacing, and we might not need explicit heights and widths -- but I think it's ok for now.
=> ICU-22533 move custom normalization page from Sites to GitHub

docs/design/normalization/custom.md
=> ICU-22533 compact norm16 tables

.ci-builds/.azure-pipelines-icu4c.yml, .ci-builds/.azure-pipelines-icu4j.yml
I am guessing that this would need some special configuration on the Azure side in order to recognize these new workflow files and give them an official display name.
=> ICU-22314 Refactor Azure CI into workflows conditional on modified paths

icu4j/main/core/src/main/java/com/ibm/icu/text/RuleBasedBreakIterator.java, icu4j/main/core/src/main/java/com/ibm/icu/util/ULocale.java
https://unicode-org.atlassian.net/browse/ICU-22582
Optimize synchronized code which is causing contention which leads to latency degradation.
RuleBasedBreakIterator: Remove fBreakEngines and instead read from the static gAllBreakEngines, this of course has issues, which we fix by using a ConcurrentLinkedQueue and read as normal, but write within a synchronized context, we will only iterate over the LanguageBreakEngines we haven't iterated over and then add a new one if needed.
ULocale: If the Locale hasn't changed then use the cached value, else go through the code path that modifies it. (Similar solution to what Locale is doing), now both defaultLocale and defaultULocale are volatile to prevent CPU caching from leading to wrong results.
Tests: I performed some manual tests and the code …
=> ICU-22582 Avoid synchronizing in RuleBasedBreakIterator and ULocale unless strictly necessary

icu4c/source/test/intltest/transtst.cpp
A reference can't be bound to dereferenced nullptr in well-defined C++ code.
=> ICU-22532 Don't dereference nullptr (-Wtautological-undefined-compare)

.ci-builds/.azure-exhaustive-tests.yml
ICU4J tests have started to fail often in the post-merge CI (~50% of the time?), and it is always due to the timeout being exceeded.
=> ICU-22532 Increase timeout for exhaustive ICU4J tests

icu4c/source/i18n/unicode/numberformatter.h, icu4c/source/i18n/unicode/numberrangeformatter.h
This corrects the ICU version number of these APIs to ICU 75. PR #2483 was merged after 74 but accidentally with `@draft ICU 74`.
Note that the JIRA issue is still marked as "accepted".
=> ICU-21952 fix draft version of withoutLocale to ICU 75

.ci-builds/.azure-exhaustive-tests.yml, .ci-builds/.azure-pipelines-icu4c.yml, .ci-builds/.azure-pipelines-icu4j.yml, .github/workflows/icu4c.yml, .github/workflows/icu4j.yml, .github/workflows/icu_docs.yml, .github/workflows/icu_valgrind.yml
In addition to running C++ tests when C++ code changes, we should also run C++ tests when the configs for the tests change, too.
Also, as a side task, I'm removing the `batch: true` from the Azure pipelines in the triggers for when merging to `main` so that Github will show the Azure CI checks alongside the Github Actions CI checks for each merge commit on `main`.
=> ICU-22532 Trigger CI workflows when workflow definitions change

icu4c/source/i18n/islamcal.cpp, icu4c/source/i18n/islamcal.h
Optimize the calendar code to avoid very slow edge case found by fuzzer
1. Use local variable to remember result to avoid call the same function twice with the same value.
2. Remove function of private usage from header and make them file private and inline.
3. Merge utility function which only called once into the calling function.
This is to address https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=67009
=> ICU-22679 Optimize calendar code for edge cases

.github/workflows/icu4c.yml, docs/devsetup/cpp/index.md, docs/devsetup/cpp/linux.md, docs/processes/release/tasks/healthy-code.md, docs/processes/release/tasks/integration.md, icu4c/source/configure, icu4c/source/configure.ac, icu4c/source/runConfigureICU
When building icu4c, it defaults to clang instead of gcc when the default compiler, cc / c++, is a symlink to gcc / g++. This is not the expected behavior when building C and C++ code. It appears that this behavior was put in place originally for supporting C++11, which hopefully is no longer such a concern. This PR adjusts the configure.ac for icu4c to prefer the cc and c++ compilers first.
=> ICU-22556 Prefer cc and c++ compilers

icu4c/source/common/localebuilder.cpp, icu4c/source/common/localematcher.cpp, icu4c/source/common/locavailable.cpp, icu4c/source/common/locdispnames.cpp, icu4c/source/common/locid.cpp, icu4c/source/common/loclikely.cpp, icu4c/source/common/loclikelysubtags.cpp, icu4c/source/common/locmap.cpp, icu4c/source/common/locresdata.cpp, icu4c/source/common/uloc.cpp, icu4c/source/common/uloc_tag.cpp, icu4c/source/common/ulocale.cpp, icu4c/source/common/ulocbuilder.cpp, icu4c/source/common/unicode/localematcher.h, icu4c/source/common/unicode/locid.h, icu4c/source/i18n/ulocdata.cpp, icu4c/source/test/cintltst/cloctst.c
- No function should do anything if an error has already occurred.
- On error, a value of `0`, `nullptr`, `{}`, etc., should be returned.
- Values shouldn't have overloaded meanings (eg. _index_ or _found_).
- Values that are never used should not be returned at all.
This will make it easier to refactor out shared code.
=> ICU-22520 Standardize return on error for all locale functions

icu4c/source/i18n/number_modifiers.cpp, icu4c/source/i18n/number_modifiers.h, icu4c/source/i18n/number_patternmodifier.cpp, icu4c/source/i18n/number_patternmodifier.h, icu4c/source/i18n/number_scientific.cpp, icu4c/source/i18n/number_scientific.h, icu4c/source/i18n/number_types.h, icu4c/source/test/intltest/numbertest.h, icu4c/source/test/intltest/numbertest_range.cpp, icu4j/main/core/src/main/java/com/ibm/icu/impl/number/ConstantAffixModifier.java, icu4j/main/core/src/main/java/com/ibm/icu/impl/number/ConstantMultiFieldModifier.java, icu4j/main/core/src/main/java/com/ibm/icu/impl/number/Modifier.java, icu4j/main/core/src/main/java/com/ibm/icu/impl/number/MutablePatternModifier.java, icu4j/main/core/src/main/java/com/ibm/icu/impl/number/SimpleModifier.java, icu4j/main/core/src/main/java/com/ibm/icu/number/NumberRangeFormatterImpl.java, icu4j/main/core/src/main/java/com/ibm/icu/number/ScientificNotation.java
There was a bug that was sometimes causing semantically equivalent modifiers to not be recognized as semantically equivalent. It was checking for pointer equality instead of semantic equality.
=> ICU-22319 Fix number range semanticallyEquivalent

icu4c/source/test/intltest/tztest.cpp
1. Mark  "Asia/Qostanay" "Asia/Almaty", and "America/Scoresbysund" TimeZone as known issue for ICU-22274: 
a. tz2024a change "Asia/Qostanay" "Asia/Almaty" but test machines has not yet update their zoneinfo to 2024a so we mark them as known issues
b. extern long timezone; in <time.h> (set man tzset on Linux shell) returns wrong value when TZ=America/Scoresbysund
2. Also print out more infomation on test error for easier debuggin in the future.
=> ICU-22274 Mark known issue for 3 timezones for EnvTest

icu4c/source/common/localematcher.cpp, icu4c/source/common/uloc.cpp, icu4c/source/test/depstest/dependencies.txt
There's a subtle difference between these two ways of accessing the value of an optional and that is that the `value()` method can throw an exception if there isn't any value, but `operator*` won't do that (it's just undefined behavior if there isn't any value).
ICU4C code never tries to access any optional value without first checking that it exists, but the ability of the `value()` method to throw an exception in case there wasn't any such check first is the reason why `std::exception` symbols previously could show up in debug builds.
This reverts the changes that were made to `dependencies.txt` by commit dc70b5a056b618c014c71e8bfd45f3dd9145e9fe.
=> ICU-22520 Use operator* instead of calling std::optional::value()

icu4c/source/common/bytesinkutil.h, icu4c/source/common/loclikely.cpp, icu4c/source/common/ucasemap.cpp, icu4c/source/common/uloc.cpp, icu4c/source/common/uloc_tag.cpp, icu4c/source/common/ulocale.cpp, icu4c/source/common/ulocbuilder.cpp, icu4c/source/common/uts46.cpp
The repeated sequence of allocating a `CheckedArrayByteSink`, calling some function that writes into this, then checking for overflow and returning through `u_terminateChars()` can all be moved into a single shared helper function.
=> ICU-22520 Refactor CheckedArrayByteSink & u_terminateChars into helper

icu4c/source/common/bytesinkutil.h, icu4c/source/common/locdispnames.cpp, icu4c/source/common/locid.cpp, icu4c/source/common/loclikely.cpp, icu4c/source/common/locmap.cpp, icu4c/source/common/locresdata.cpp, icu4c/source/common/ucurr.cpp, icu4c/source/common/uloc.cpp, icu4c/source/common/uloc_tag.cpp, icu4c/source/common/ulocimp.h, icu4c/source/common/uresbund.cpp, icu4c/source/common/uscript.cpp, icu4c/source/i18n/calendar.cpp, icu4c/source/i18n/collationruleparser.cpp, icu4c/source/i18n/dayperiodrules.cpp, icu4c/source/i18n/dtitvinf.cpp, icu4c/source/i18n/dtptngen.cpp, icu4c/source/i18n/gender.cpp, icu4c/source/i18n/plurrule.cpp, icu4c/source/i18n/rulebasedcollator.cpp, icu4c/source/i18n/tmutfmt.cpp, icu4c/source/i18n/tzfmt.cpp, icu4c/source/i18n/tzgnames.cpp, icu4c/source/i18n/tznames_impl.cpp, icu4c/source/i18n/ucol_sit.cpp, icu4c/source/i18n/windtfmt.cpp, icu4c/source/i18n/winnmfmt.cpp
The repeated sequence of allocating a `CharString` and `CharStringByteSink`, before calling some function that writes into this, can be moved into a single shared helper function which then is used to give all `ulocimp.h` functions that write to `ByteSink` an overload that instead returns a `CharString`, to make call sites look like perfectly normal C++ code.
=> ICU-22520 Refactor CharString & CharStringByteSink into helper

icu4c/source/common/brkiter.cpp, icu4c/source/common/bytesinkutil.h, icu4c/source/common/localebuilder.cpp, icu4c/source/common/locdspnm.cpp, icu4c/source/common/locid.cpp, icu4c/source/i18n/units_data.cpp
This makes it possible to call public functions that take a string class as a template parameter and return an object of that class (implemented through the `StringByteSink` helper class) also with the `CharString` class, even though this class doesn't actually provide the public API required by `StringByteSink`.
This makes it possible to use such more modern APIs also internally.
=> ICU-22520 Add a StringByteSink<CharString> template specialization

icu4c/source/i18n/chnsecal.cpp, icu4c/source/test/intltest/caltest.cpp
Fix issue found by https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=67256
=> ICU-22633 Fix overflow in Chinese calendar

icu4c/source/i18n/units_converter.cpp, icu4c/source/i18n/units_converter.h, icu4c/source/i18n/units_data.cpp, icu4c/source/i18n/units_data.h, icu4c/source/test/intltest/units_data_test.cpp, icu4c/source/test/intltest/units_test.cpp, icu4j/main/core/src/main/java/com/ibm/icu/impl/units/UnitsConverter.java
This is the ICU4C counterpart to[ #2847](https://github.com/unicode-org/icu/pull/2847), the ICU4J implementation.
Both implement unit conversion for speed-beaufort using the new CLDR `special` attribute for the `convertUnit` element; this attribute specifies special conversions (such as table-based) between a base unit (e.g. meters/sec in this case) and a scale in which a given scale value represents a range of base unit values (instead of the mapping being represented by a factor and optional offset). Conversions from base to scale map any unit on the range to the specific scale value; conversions from the scale value to base use a value in the middle of the range. The only special scale currently supported is "beaufort".
Both the J and C implementations in these PRs are preliminary, …
=> ICU-22655 Implement "special" conversion for speed-beaufort, part 2 icu4c

icu4c/source/i18n/buddhcal.cpp, icu4c/source/i18n/calendar.cpp, icu4c/source/i18n/cecal.cpp, icu4c/source/i18n/cecal.h, icu4c/source/i18n/chnsecal.cpp, icu4c/source/i18n/chnsecal.h, icu4c/source/i18n/dangical.cpp, icu4c/source/i18n/dangical.h, icu4c/source/i18n/ethpccal.cpp, icu4c/source/i18n/gregocal.cpp, icu4c/source/i18n/hebrwcal.cpp, icu4c/source/i18n/hebrwcal.h, icu4c/source/i18n/indiancal.cpp, icu4c/source/i18n/indiancal.h, icu4c/source/i18n/islamcal.cpp, icu4c/source/i18n/islamcal.h, icu4c/source/i18n/japancal.cpp, icu4c/source/i18n/japancal.h, icu4c/source/i18n/persncal.cpp, icu4c/source/i18n/persncal.h, icu4c/source/i18n/simpletz.cpp, icu4c/source/i18n/taiwncal.cpp, icu4c/source/i18n/unicode/calendar.h, icu4c/source/i18n/unicode/gregocal.h, icu4c/source/test/intltest/caltest.cpp, icu4c/source/test/intltest/caltest.h
Add test to set with INT32_MAX and INT32_MIN then call getTime() and fix all the undefined errors.
There are a lot of fuzzer found int32_t overflow in the area of calendar. I write a test trying to trigger all possible condition and fix allt he found issues here.
=> ICU-22633 Test and fix int32_t overflow for Calendar set

icu4c/source/i18n/calendar.cpp, icu4c/source/i18n/chnsecal.cpp, icu4c/source/i18n/chnsecal.h, icu4c/source/i18n/dangical.cpp, icu4c/source/i18n/gregocal.cpp, icu4c/source/i18n/hebrwcal.cpp, icu4c/source/i18n/indiancal.cpp, icu4c/source/i18n/persncal.cpp, icu4c/source/test/intltest/caltest.cpp, icu4c/source/test/intltest/caltest.h, icu4j/main/core/src/main/java/com/ibm/icu/util/HebrewCalendar.java
Test set+set, set+add, set+roll, add+add, roll+roll
Optimize both Java and C++ Hebrew Calendar month/year advancement by first consider
every 235 months is 19 years before iteration.
=> ICU-22633 Add more Calendar overflow tests

.github/workflows/icu4c.yml
Workaround for an ephemeral issue of `./runConfigureICU` failing for a few CI jobs in Github Actions for ICU4C, seemingly caused by the underlying GHA runner VM's software changing someone in the latest version. (Runner VM version `20240304.1.0` seemed fine, but `20240310.1.0` seems to be a problem. Explains almost all of our observed behavior, modulo a few exceptions.)
=> ICU-22532 Use previous Ubuntu version for ICU4C in GH Actions CI

icu4c/source/common/uloc.cpp, icu4c/source/common/unicode/locid.h, icu4c/source/i18n/dtptngen.cpp, icu4c/source/test/cintltst/cloctst.c, icu4c/source/test/cintltst/cloctst.h, icu4c/source/test/cintltst/creststn.c, icu4c/source/test/intltest/loctest.cpp, icu4c/source/test/intltest/loctest.h, icu4j/main/collate/src/test/java/com/ibm/icu/dev/test/util/ICUResourceBundleCollationTest.java, icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/util/ULocaleTest.java, icu4j/main/core/src/main/java/com/ibm/icu/impl/LocaleIDParser.java
Limit the size of acceptable variants in Locale to avoid long running time of 
resource fallback look up when trying all different combinations of many variants.
I first try to limit to the max size of 10 variants but some test break, so I change it to 20 now.
Also ensure the Locale::getVariant will not return invalid address while the locale is bogus.
=> ICU-22661 Limit the size of variants in Locale

icu4c/source/common/unicode/ptypes.h
We do “just unconditionally include stdint.h here and not need any of the stuff after including platform.h.”
=> ICU-22612 remove obsolete comment

icu4c/source/i18n/chnsecal.cpp, icu4c/source/i18n/chnsecal.h, icu4c/source/i18n/dangical.cpp
Rename and shortern variables. Move private function into file private and avoid unncessary virtual private
Refactor calculation code to not depends on the state of Calendar to avoid creating additional Calendar object during calculation.
=> ICU-22679 Refactor ChineseCalendar

icu4c/source/i18n/calendar.cpp, icu4c/source/i18n/hebrwcal.cpp, icu4c/source/test/intltest/caltest.cpp, icu4c/source/test/intltest/caltest.h
Check error status and return error in the loop
Left over bug fix for ICU-22633 bug fix for Hebrew Calendar. 
Found by fuzzer in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=67463
It is not really a infinity loop but a very slow loop because we should return the error inside the loop right after it happen.
=> ICU-22633 Fix hang on large negative day in hebrew calendar

icu4c/source/i18n/buddhcal.h, icu4c/source/i18n/calendar.cpp, icu4c/source/i18n/coptccal.h, icu4c/source/i18n/iso8601cal.h, icu4c/source/i18n/japancal.h, icu4c/source/i18n/unicode/calendar.h, icu4c/source/i18n/unicode/gregocal.h, icu4j/main/core/src/main/java/com/ibm/icu/util/BuddhistCalendar.java, icu4j/main/core/src/main/java/com/ibm/icu/util/Calendar.java, icu4j/main/core/src/main/java/com/ibm/icu/util/CopticCalendar.java, icu4j/main/core/src/main/java/com/ibm/icu/util/GregorianCalendar.java, icu4j/main/core/src/main/java/com/ibm/icu/util/JapaneseCalendar.java
Change the logic of handling year in era 0 counting backwards to depend on a boolean virtual function instead of adding string comparsion code in the base class to have specific knowledge of behavior of subclass.
=> ICU-22679 Remove getType and string comparsion

icu4c/source/i18n/astro.cpp, icu4c/source/i18n/astro.h, icu4c/source/i18n/chnsecal.cpp, icu4c/source/i18n/islamcal.cpp, icu4c/source/i18n/islamcal.h, icu4c/source/test/intltest/astrotst.cpp, icu4c/source/test/intltest/astrotst.h, icu4j/main/core/src/main/java/com/ibm/icu/impl/CalendarAstronomer.java, icu4j/main/core/src/main/java/com/ibm/icu/util/ChineseCalendar.java, icu4j/main/core/src/main/java/com/ibm/icu/util/IslamicCalendar.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/calendar/AstroTest.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/calendar/IBMCalendarTest.java
1. Remove dead code inside CalendarAstronomer that was not used.
The following methhods are not used and unneeded for the Chinese and Islamic calendar usage and therefore removed:
getJulianCentury(), getGreenwichSidereal(), getLocalSidereal(), lstToUT(), eclipticToHorizon(), getSunPosition(), getSunRiseSet(), getMoonPhase(), getMoonRiseSet(), 
We also removed 6 double member data from CalendarAstronomer since they were only used by removed functions and/or never with complete implementation (for example, lat/long in this class). This save us 48 bytes per CalendarAstronomer object.
3. Since all the current usage call setTime then get a value, the cache inside CalendarAstronomer is not used across different call. Change to allocate the object on stack instead of using mutex to share a …
=> ICU-22698 Clean up CalendarAstronomer

.github/dependabot.yml, .github/workflows/cache_retain.yml, .github/workflows/icu4c.yml, .github/workflows/icu_envtest.yml, .github/workflows/icu_merge_ci.yml, .github/workflows/icu_valgrind.yml, .github/workflows/jekyll-gh-pages.yml, .github/workflows/maven.yaml, .github/workflows/scorecard.yml
This PR hash-pins all GitHub Actions in workflows to protect them from broken or malicious releases.
It also sets up dependabot to sent a single monthly PR to update all Actions with new versions. The PR will update both the hashes and version comments.
Sorry for not sending this PR sooner, I hadn't noticed that the issue had been accepted in JIRA soon after I'd sent it 🤦.
=> ICU-22482 Hash-pin GitHub Actions, keep them updated with Dependabot

icu4c/source/common/unicode/platform.h, icu4c/source/common/unicode/ptypes.h, icu4c/source/common/unicode/umachine.h, icu4c/source/icudefs.mk.in, icu4c/source/test/intltest/Makefile.in, icu4c/source/test/intltest/uchar_type_build_test.cpp
Since ICU4C requires C++11 and C11 the `char16_t` data type can be used everywhere, as long as the `uchar.h` header file gets included when building as C (where it isn't a keyword as in C++), but this doesn't work on macOS which for unknown reasons lacks the `uchar.h` header file and therefore needs a workaround to define `char16_t`.
For any ICU4C internal code the `char16_t` data type should always be used and `UCHAR_TYPE` ignored, which this PR solves by setting `U_ALL_IMPLEMENTATION` in its own build system.
There shouldn't really be any reason to ever use the `UCHAR_TYPE` feature on any platform that doesn't use the autoconf build system so I think it'd be fine to leave this without adding the `U_ALL_IMPLEMENTATION` define to any other build systems (which would be something that I …
=> ICU-22643 Make UCHAR_TYPE work as intended with C++11, C11 & macOS.

icu4c/source/test/cintltst/creststn.c
The original intention behind this test case was to use the root locale, but ures`_getFunctionalEquivalent()` is implemented by calling `ures_open()` which sets `URES_OPEN_LOCALE_DEFAULT_ROOT` which will cause the default locale to be loaded before the root locale.
To avoid that, pick a locale other than the root locale for the test.
=> ICU-22701 Bugfix: Make test independent of the default locale

icu4c/source/i18n/buddhcal.cpp, icu4c/source/i18n/buddhcal.h, icu4c/source/i18n/cecal.cpp, icu4c/source/i18n/cecal.h, icu4c/source/i18n/chnsecal.cpp, icu4c/source/i18n/chnsecal.h, icu4c/source/i18n/coptccal.cpp, icu4c/source/i18n/coptccal.h, icu4c/source/i18n/ethpccal.cpp, icu4c/source/i18n/ethpccal.h, icu4c/source/i18n/gregocal.cpp, icu4c/source/i18n/gregoimp.h, icu4c/source/i18n/hebrwcal.cpp, icu4c/source/i18n/hebrwcal.h, icu4c/source/i18n/indiancal.cpp, icu4c/source/i18n/indiancal.h, icu4c/source/i18n/islamcal.cpp, icu4c/source/i18n/islamcal.h, icu4c/source/i18n/japancal.cpp, icu4c/source/i18n/japancal.h, icu4c/source/i18n/persncal.cpp, icu4c/source/i18n/persncal.h, icu4c/source/i18n/taiwncal.cpp, icu4c/source/i18n/taiwncal.h, icu4c/source/i18n/unicode/calendar.h, icu4c/source/i18n/unicode/gregocal.h
1. Remove redudant implementation of default system century by using macro
2. Fold long if / else block if one block return.
=> ICU-22679 Clean up Calendar code.

icu4c/source/common/uloc.cpp, icu4c/source/test/intltest/loctest.cpp
Fix fuzzer found issue of hang that caused by long POSIX charset name. Limit the POSIX charset name to at most 64 chars.
=> ICU-22700 Fix large POSIX charset name cause hang

icu4c/source/i18n/unicode/calendar.h
This fix the breakage of U_HIDE_INTERNAL_API test on source/i18n/unicode/gregocal.h
caused by the landing of PR 2915
=> ICU-22679 Fix broken header test

README.md, docs/userguide/dev/ci.md
=> ICU-22533 Update badges for CI pipelines, user guide docs about CI

icu4j/main/core/src/main/java/com/ibm/icu/impl/ICUService.java
Sometimes getVisibleIDs() method returns a null reference which might happend because of inaccurate concurrent access. This change attempts to fix this ICUServiceThreadTest flakiness.
=> ICU-22536 Fix ICUServiceThreadTest flakiness

icu4c/source/i18n/chnsecal.cpp, icu4c/source/i18n/chnsecal.h, icu4c/source/i18n/dangical.cpp, icu4c/source/i18n/dangical.h, icu4c/source/test/intltest/callimts.cpp, icu4c/source/test/intltest/incaltst.cpp, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/calendar/IBMCalendarTest.java
Also fix ICU-12620, which is mark duplicate of ICU-9972 just now, and ICU-22258.
Separate the new year and winter solstice cache since the calculated value for these two calendar are mostly but not always the same due to slightly different observation timeZone.
Remove the epochYear and zoneAstroCalc from the member data and instead return them from a getStting() method with the two caches since all four of them are constant per subclass of ChineseCalendar and do not need to be different per object.
The known issues in the TestLimit is caused by both Calendar get/put the value from the same cache while the calculated result depends on the timeZone zoneAstroCalc.
We do not have this issue in Java because both the new year and winter solstice cache in ICU4J 's ChineseCalendar are not global …
=> ICU-9972 Fix Chinese/Dangi Calendar getActualMaximum(UCAL_DAY_OF_YEAR)

icu4c/source/common/unicode/utypes.h, icu4c/source/i18n/unicode/messageformat2_data_model.h, icu4c/source/i18n/unicode/messageformat2_formattable.h, icu4c/source/i18n/unicode/messageformat2_function_registry.h
This PR adds `@internal` and `@deprecated` tags to some methods and enum constants that weren't tagged.
=> ICU-22261 Add missing API tags for MessageFormat 2 methods/constants

icu4c/source/test/intltest/tzfmttst.cpp, icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/format/TimeZoneFormatTest.java
CLDR-17024 is fixed in CLDR45 and the test now passed. Remove the logKnownIssue so it will test and report future breakage.
=> ICU-22534 BRS75 Remove fixed logKnownIssue for CLDR-17024

icu4c/source/test/intltest/loctest.cpp
CLDR-17099 is fixed in CLDR44 and the test now passed. Remove the logKnownIssue so it will test and report future breakage.
=> ICU-22534 BRS75 Remove fixed CLDR17099  logKnownIssue

icu4c/source/i18n/messageformat2_data_model.cpp, icu4c/source/i18n/messageformat2_parser.cpp, icu4c/source/i18n/messageformat2_parser.h, icu4c/source/i18n/unicode/messageformat2_data_model.h
Previously, there were separate overrides for the options and attributes parsing methods in the parser that were used in different context. (Options can appear in Operator and Markup, while attributes can appear in Expression and Markup.)
This is a refactoring that eliminates this duplicated code. To enable it, a builder is added for the internal OptionMap type.
This doesn't change any public APIs, but is also not an urgent change.
=> ICU-22261 Refactor MF2 attributes and options parsing code

icu4c/source/i18n/japancal.cpp, icu4c/source/test/intltest/caltest.cpp, icu4c/source/test/intltest/caltest.h
=> ICU-22730 Fix Japanese extended year int32 overflow

icu4c/source/common/loclikely.cpp, icu4c/source/test/cintltst/cloctst.c, icu4c/source/test/intltest/loctest.cpp, icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/util/ULocaleTest.java
=> ICU-22727 Fix uloc_addLikelySubtags for alpha{5,8} unicode_language_subtag

docs/userguide/format_parse/messages/mf2.md
=> ICU-22722 Fix missing starter character for MF2 keyword in User Guide

icu4c/source/common/unicode/localpointer.h, icu4c/source/common/unicode/platform.h, icu4c/source/i18n/unicode/messageformat2_arguments.h, icu4c/source/i18n/unicode/messageformat2_data_model.h, icu4c/source/i18n/unicode/messageformat2_formattable.h
It's not uncommon for code for Windows to use the `_MSC_VER` preprocessor macro to identify that it's being compiled for Windows so it's also not uncommon for compilers other than the real MSVC compiler to also set this to be able to compile such code.
It's also not possible to use `_MSC_VER` to determine whether the C++ standard library implementation used is the Microsoft STL.
Clang will however refuse to instantiate a template with a forward declared type, so the code that currently does this needs to be moved to after the type has been properly defined, which in turn makes MSVC warn that those templates aren't instantiated, so those warnings need to be disabled, but then the disabling of warning C4661 doesn't work any longer (for some unknown reason) but this can be resolved by …
=> ICU-22261 Improved identification of the MSVC compiler and library

icu4c/source/common/unicode/uloc.h
for example with a U_ILLEGAL_ARGUMENT_ERROR since PR #2813 in some cases where the implementation may have
returned with a misleading U_BUFFER_OVERFLOW_ERROR
API docs wording from 20240411 ICU-TC meeting.
=> ICU-22520 doc: uloc_getName() & others may fail

docs/processes/release/tasks/docs.md
Add how to use release_tools/github_release.sh.
Also detailed how to update the files in icu-docs/apidoc
=> ICU-22722 Revised ICU4J API doc process to modern tools

icu4c/source/i18n/erarules.h, icu4c/source/i18n/measunit_impl.h, icu4c/source/i18n/number_decimfmtprops.h, icu4c/source/i18n/number_patternmodifier.h, icu4c/source/i18n/number_usageprefs.h
The missing operators that used to be warned about were all deleted by commit 75eab42060d6a73b62db2bc639216eae1f8ec47e.
=> ICU-22721 Remove now obsolete disabled warnings for LocalPointerBase

.github/workflows/maven.yaml
Update the CI workflow that deploys Maven artifacts to Github for ICU4J so that:
* We don't publish the `icu4j` artifact to Github for release (non-snapshot) versions. This preserves Maven Central as the single source of truth for `icu4j` artifacts for release versions
- Note: we keep the current behavior for snapshot versions, which is to publish to Github
*  We automatically prevent any manual attempts to publish a release version artifact
Trial runs in my personal fork:
- succeeding workflow run of the PR branch, triggered manually: https://github.com/echeran/icu/actions/runs/8730613164/job/23954716091
* the condition execution of steps within the job shows that the workflow output variables are being captured as expected
- a previous iteration that failed when the version number …
=> ICU-22721 Prevent inconsistent ICU4J Maven deploys via CI

icu4c/source/i18n/calendar.cpp, icu4c/source/test/intltest/caltest.cpp, icu4c/source/test/intltest/caltest.h
In some calendar, the gap could be 0 and cause FPE when we % gap
=> ICU-22750 Fix Floating-point-exception in icu::Calendar::roll

icu4c/source/tools/pkgdata/pkgdata.cpp
1. double size one stack buffer
2. add pragma to ignore some theorical case because the array are in same length but some fields are shorter than the other.
=> ICU-21589 Remove format-overflow warning

.ci-builds/.azure-pipelines-icu4c.yml, icu4c/source/tools/icuexportdata/icuexportdata.cpp
=> ICU-22758 Make icuexportdata compatible with Unicode 16 normalization

icu4j/tools/misc/pom.xml, icu4j/tools/misc/src/main/java/com/ibm/icu/dev/tool/localeconverter/XLIFF2ICUConverter.java
Same changes as in the previous CL.
But even lowers risk :-) this was unused for a long time.
I added code to dump the parameters before refactoring.
Invoked with all kind of options (from a script), and saved the result in a text file.
Refactored, run the previous script and compared results.
Then I removed the code doing the dump.
I didn't attempt to make the whole thing work.
Thank you,
M
=> ICU-21757 Replace UOption with commons-cli in XLIFF2ICUConverter

icu4c/source/common/putil.cpp
This was originally added in the year 2004 for ICU-3854 but is no longer needed with contemporary versions of MinGW where it instead as of GCC 14 causes this problem:
`__STRICT_ANSI__` seems to have been undefined; this is not supported.
=> ICU-22721 Delete obsolete __STRICT_ANSI__ workaround for MinGW

icu4c/source/tools/icuexportdata/icuexportdata.cpp
=> ICU-22723 Add line number info to icuexportdata handleError

.ci-builds/.azure-pipelines-icu4c.yml, icu4c/source/i18n/messageformat2_parser.cpp
This fixes a clang-17 `-Wctad-maybe-unsupported` warning.
=> ICU-22740 Add missing template arguments in MF2 parser

icu4c/source/i18n/messageformat2_errors.cpp
In StaticErrors::addError() and DynamicErrors::addError(), don't read from `e` after moving out of it.
It's surprising to me that this error wasn't caught by asan or ubsan.
=> ICU-22753 Fix read-after-move in MF2

icu4c/source/tools/icuexportdata/icuexportdata.cpp
=> ICU-22718 backport Export disallowed/ignored UTS 46 data for ICU4X

docs/userguide/icu/index.md
- [v] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22722
- [v] Required: The PR title must be prefixed with a JIRA Issue number. 
- [v] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [v] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [v] Issue accepted (done by Technical Committee after discussion)
- [v] Tests included, if applicable
- [v] API docs and/or User Guide docs changed or added, if applicable
=> ICU-22722 Fix broken link to faq in docs/userguide/icu/index.md

icu4c/source/data/Makefile.in, icu4c/source/data/makedata.mak
=> ICU-22769 Fix the jar generation to not use versioned folder

icu4c/source/common/ubidiwrt.cpp, icu4c/source/test/cintltst/cbiditst.c, icu4c/source/test/fuzzer/ubidi_fuzzer.cpp
Consider doWriteForward may return 0 if src only contains bidi control chars.
=> ICU-22768 Fix bidi buffer overflow

icu4c/source/test/intltest/compactdecimalformattest.cpp, icu4c/source/test/intltest/measfmttest.cpp, icu4c/source/test/intltest/ustrtest.cpp, icu4c/source/test/intltest/uts46test.cpp
Any symbol that isn't intended to have external linkage should either be declared static (legacy code) or put in an unnamed namespace.
=> ICU-22001 Put translation unit local definitions in unnamed namespaces

icu4c/source/common/uprops.cpp, icu4c/source/test/cintltst/cucdtst.c, icu4j/main/core/src/main/java/com/ibm/icu/impl/UCharacterProperty.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/lang/UCharacterTest.java
ICU does not store separate data for the Hangul_Syllable_Type property. This property has been a fully redundant subset of the Grapheme_Cluster_Break, and is therefore trivially derived at runtime.
However, starting with Unicode 16, there are a few characters (initially: some Kirat Rai vowel signs) that have nothing to do with Hangul but have GCB=V in order to make grapheme clusters work for their script.
This PR adds some spot checks and a simple derivation fix.
See the "Segmentation Issues" in https://www.unicode.org/versions/beta-16.0.0.html, and https://www.unicode.org/reports/tr29/tr29-44.html#Modifications
FYI: I thought about testing the ICU implementation against ppucd.txt, but that file does not contain hst data either: We don't currently parse HangulSyllableType.txt at all.
=> ICU-22707 bug fix hst=V: hst=NA for Kirat Rai

icu4c/source/common/caniter.cpp, icu4j/main/core/src/main/java/com/ibm/icu/text/CanonicalIterator.java
Fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=65247
=> ICU-22642 Avoid spending too much time inside CanonicalIterator

icu4c/source/i18n/collationbuilder.cpp
Fix an infinity loop issue inside collation builder
=> ICU-22797 Move the loop limit before ignore continue

icu4c/source/common/ucurr.cpp
Change code inside ucurr.cpp to use LocalPointer  to prepare the later changes for correct memory change
=> ICU-21810 Fix error checking of ucurr.cpp part 1

icu4c/source/common/messagepattern.cpp, icu4c/source/common/unicode/messagepattern.h, icu4c/source/test/intltest/msfmrgts.cpp, icu4c/source/test/intltest/msfmrgts.h
Change the nested level limit from 0x7fff to 0x0fff since the fuzzer found in some machine 6400 level deep already cause stack overflow.
=> ICU-22798 Avoid stack overflow by return error.

icu4c/source/test/fuzzer/Makefile.in, icu4c/source/test/fuzzer/uregex_match_fuzzer.cpp
Based on https://chromium-review.googlesource.com/c/chromium/deps/icu/+/5465572
=> ICU-22716 Add uregex_match_fuzzer

icu4c/source/common/uresdata.cpp
=> ICU-21809 Possible memory leak of tempTable.resFlags

icu4c/source/common/locid.cpp
There are some memory leak in Locale which is hard to figure out why. Use different variable to track memory allocation to avoid inconsistent state while malloc fail
=> ICU-22800 Avoid inconsistent state inside Locale

icu4c/source/test/fuzzer/uregex_match_fuzzer.cpp
To avoid unnecessary timeout.
Needed to fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=69750
=> ICU-22716 Set timeout limit for uregex_match_fuzzer

icu4c/source/test/fuzzer/uregex_match_fuzzer.cpp
3000 is still too large and cause https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=69869 set to 300 per andy's earlier suggestion
=> ICU-22716 Set smaller timeout limit for uregex_match_fuzzer

.github/workflows/wait-for-checks.yml, docs/userguide/dev/ci.md
This PR gives instructions and a workflow so that ICU can reestablish all of the CI checks as being required while still retaining the new workflow structure that optimizes time by conditionally executing workflows based on affected file paths.
Examples: I tested this in my fork and saw the new GHA workflow work as advertised. Workflow [instance 1 log](https://github.com/echeran/icu/actions/runs/9720753145/job/26832555994?pr=66), [instance 2 log](https://github.com/echeran/icu/actions/runs/9720943698/job/26833014842?pr=66).
=> ICU-22721 Add workflow that enforces required checks

.github/workflows/wait-for-checks.yml, docs/userguide/dev/ci.md
Applying reviewer changes from #3055 
Also, if CI for the [merge commit](https://github.com/unicode-org/icu/commit/f668bc5218c9eda9ba6df453ccba3642f0f2c21c) for #3055 all looks good (in particular, the [wait for checks job](https://github.com/unicode-org/icu/actions/runs/9738129393/job/26871225814)), then we might be ready to configure the repo settings' branch protection rules and add `enforce-all-checks` as a required check.
=> ICU-22721 Simplify wait-for-checks match logic

docs/processes/cldr-icu.md
=> ICU-22741 Update CLDR-ICU instructions to mention some hardcoded lists that may need updating

icu4c/source/common/locid.cpp, icu4c/source/common/uloc.cpp, icu4c/source/common/uloc_keytype.cpp, icu4c/source/common/ulocimp.h
These optional output parameters weren't used when these function were originally added so they were most likely included just in case someone would want to use them in the future, but that was 10 years ago now and they still haven't been used yet, so it's unlikely that they'll be used in the foreseeable future and call sites as well as the implementation can instead be simplified by removing them.
=> ICU-22696 Delete unused code

icu4c/source/common/unicode/stringpiece.h, icu4c/source/test/intltest/strtest.cpp
This will allow ICU4C to seamlessly use `std::string_view` internally while continuing to use `StringPiece` in the public API.
=> ICU-22696 Add implicit conversion from StringPiece to std::string_view

icu4c/source/common/mlbe.cpp
=> ICU-22819 Fix memory leak during error in mlbe.cpp

icu4c/source/i18n/number_longnames.cpp
=> ICU-22831 Fix memLeak in number_longnames.cpp by using LocalPointer

icu4c/source/i18n/numrange_fluent.cpp
Maybe related to the leak in ICU-22800
=> ICU-22830 Fix memLeak in numrange_fluent.cpp

icu4c/source/i18n/tznames_impl.cpp
=> ICU-22825 Fix memLeak during error in tznames_impl.cpp

icu4c/source/i18n/messageformat2_data_model.cpp
=> ICU-22818 Fix memory leak during error in messageformat2_data_model.cpp

icu4c/source/common/localebuilder.cpp, icu4c/source/common/locid.cpp, icu4c/source/common/uloc.cpp, icu4c/source/common/uloc_keytype.cpp, icu4c/source/common/uloc_tag.cpp, icu4c/source/common/ulocimp.h
=> ICU-22696 Update ulocimp_to*{Key,Type}() to use std::string_view

icu4j/pom.xml
=> ICU-22722 Update the ICU Vice-Chair for Maven publishing

icu4c/source/common/unicode/platform.h, icu4c/source/tools/genccode/genccode.c, icu4c/source/tools/pkgdata/pkgdata.cpp, icu4c/source/tools/toolutil/pkg_genc.cpp, icu4c/source/tools/toolutil/pkg_genc.h
I'm working on supporting Node.js on Windows. There is an ongoing effort to enable it to be compiled with ClangCL. While working on it I noticed an issue when creating `.obj` file in ICU because of the `*pCPU = IMAGE_FILE_MACHINE_UNKNOWN;` line, and the code I made fixes that by adding a new option. Although this is a broader problem that should be fixed for multiple compilers and platforms, my change is aimed toward ClangCL and Windows, but can be used as a good foundation to work on fixes for other platforms and compilers and make corrections in future iterations.
This issue is currently our main blocker for enabling ClangCL compilation for Node.js and it'd be greatly appreciated if it could be reviewed soon.
Refs: https://github.com/nodejs/node/pull/53003
=> ICU-22787 Fix ClangCL compilation on Windows

icu4c/source/common/unicode/char16ptr.h, icu4c/source/common/unicode/platform.h, icu4c/source/common/unicode/unistr.h, icu4c/source/common/uniset_props.cpp, icu4c/source/common/unistr.cpp, icu4c/source/i18n/number_decimalquantity.cpp, icu4c/source/test/intltest/ustrtest.cpp, icu4c/source/test/intltest/ustrtest.h
=> ICU-22843 UnicodeString <-> std::u16string_view / wstring_view

icu4c/source/test/intltest/rbbitst.cpp
This will make the code ever so slightly simpler but more importantly make it possible to compile also when using `-D_GLIBCXX_DEBUG`.
=> ICU-22721 Use correct initializer list syntax

icu4c/source/common/unifiedcache.cpp
Declare the type 'int32_t' for std::max to fix error: no matching function for call to 'max(int, int32_t)'
=> ICU-22861 std::max deduced conflicting types in unifiedcache.cpp

icu4j/main/core/pom.xml, icu4j/pom.xml
=> ICU-21205 Fix Eclipse failing to import the icu4j maven project

icu4c/source/common/ustrcase.cpp
Detail: https://s3.amazonaws.com/clickhouse-test-reports/65761/a273def46e478e465af2078a72dd49ae3a685fb5/ast_fuzzer__msan_.html
It was found in https://github.com/ClickHouse/ClickHouse/pull/65761  
```
==27703==WARNING: MemorySanitizer: use-of-uninitialized-value
#0 0x55d4727bd32e in icu_70::(anonymous namespace)::toLower(int, unsigned int, char16_t*, int, char16_t const*, UCaseContext*, int, int, icu_70::Edits*, UErrorCode&) build_gcc/./contrib/icu/icu4c/source/common/ustrcase.cpp:281:29
#1 0x55d4727be315 in ustrcase_internalToLower_70 build_gcc/./contrib/icu/icu4c/source/common/ustrcase.cpp:1179:25
#2 0x55d4727bf77d in icu_70::UnicodeString::caseMap(int, unsigned int, icu_70::BreakIterator*, int (*)(int, unsigned int, icu_70::BreakIterator*, char16_t*, int, char16_t const*, int, …
```
=> ICU-22832 Fix msan complain about use-of-uninitialized-value

icu4c/source/i18n/unicode/ucol.h
It should obviously be ucol_open here. This typo was introduced in the https://github.com/unicode-org/icu/commit/0335b3b9c3aaa5d6826b33cb3f45e56b917618e9
=> ICU-22850 ucol_openRules: fix ucol_open reference in the description

icu4c/source/i18n/messageformat2_function_registry.cpp
This is a trivial fix for the issue which we have already addressed earlier. But now another instance of the same has to be fixed. See:
https://unicode-org.atlassian.net/browse/ICU-22807
=> ICU-22807 Fix for missing __STDC_FORMAT_MACROS before inttypes.h

.github/workflows/maven-publish.yml, .gitignore, icu4j/demos/pom.xml, icu4j/main/charset/pom.xml, icu4j/main/collate/pom.xml, icu4j/main/common_tests/pom.xml, icu4j/main/core/pom.xml, icu4j/main/currdata/pom.xml, icu4j/main/framework/pom.xml, icu4j/main/icu4j/pom.xml, icu4j/main/langdata/pom.xml, icu4j/main/localespi/pom.xml, icu4j/main/regiondata/pom.xml, icu4j/main/translit/pom.xml, icu4j/perf-tests/pom.xml, icu4j/pom.xml, icu4j/samples/pom.xml, icu4j/tools/build/pom.xml, icu4j/tools/misc/pom.xml
---
This creates a GitHub workflow that builds the ICU4J artifacts using JDK 8 and publishes them to Maven Central.
It does everything that's needed: sources, javadoc, digitally signed.
The next step is to improve it and generate the javadoc ready to publish on the web, and to collect the artifacts, with md5sum for the GitHub Release.
That way the files we publish in GitHub Release / Maven Central + Javadoc site will be binary identical, and generated automatically by this GitHub action.
This will generate all ICU4J files in a GitHub Release.
=> ICU-22606 Make the ICU4J release easier & more predictable

icu4j/main/charset/pom.xml, icu4j/main/icu4j/pom.xml, icu4j/main/localespi/pom.xml, icu4j/pom.xml
1. The flatten plugin appended the relative module paths to the URLs in `<scm>`. The same kind of problem solved earlier with ${proj.url}, and fixed the same way. I was unable to find any way to tell the plugin to not do that append, even after reading some of the plugin code.
2. The stylesheet containing the JCite styles was not copied in the generated javadoc. The first part of our custom stylesheet is 100% the same as the oficial one. So the only part that was visually affected was the code produced by JCite. The code still used `<pre>` and `<code>`, so it was monospaced and well indented / wrapped, but no syntax colors.
=> ICU-22606 Correct urls in the scm entry; fix JCite styles in javadoc

icu4c/source/test/fuzzer/calendar_fuzzer.cpp
The Calendar fuzzer tests too many operations and causes timeouts which do not surface the real issues. Limit the test data size to 100 instead of 1000 instead.
To avoid unnecessary test failure of timeout in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=71058
=> ICU-22716 Reduce the data size to test calendar fuzzer

icu4c/source/common/uts46.cpp, icu4c/source/test/intltest/uts46test.cpp, icu4j/main/core/src/main/java/com/ibm/icu/impl/UTS46.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/normalizer/UTS46Test.java
- I compared the ICU implementation with the UTS46 changes in Unicode [15.1](https://www.unicode.org/reports/tr46/tr46-31.html#Modifications) & [16.0](https://www.unicode.org/reports/tr46/tr46-33.html#Modifications).
- Code & spec are not totally parallel because (a) ICU makes some optimizations and (b) where the spec has options for performing certain checks ICU always performs those but records errors in an output where callers can ignore them.
- I checked some cases via temporary test code to make sure that the outcome was as desired.
- Added a specific check for "starts with xn--" to the code path after Punycode-decoding a label, so that we can set an invalid-ACE-label error rather than a vanilla has-hyphens-at-offsets-3-and-4 error.
- In IDNA2008, this is checked via round-trip …
=> ICU-22707 adjust UTS46 for Unicode 16

icu4c/source/common/unicode/char16ptr.h, icu4c/source/common/unicode/unistr.h, icu4c/source/common/unistr.cpp
When passing a string literal to any of the legacy constructors that take just a plain pointer to a UTF-16 string it becomes necessary to iterate through the string to find its length, even though this length was known to the compiler (which just has no way of passing it on to the constructor).
But when calling the new templated string view constructor instead it becomes possible for the compiler to use the known length of a string literal to directly create a string view of the correct size and pass this on to the constructor.
By replacing the legacy constructors with the new constructor this is made the default behaviour.
Because non-templated functions take priority it's necessary to replace the legacy constructors or else the new constructor would never be called for any data type …
=> ICU-22843 Enable constructing UnicodeString from literal in fixed time

icu4c/source/common/unicode/char16ptr.h, icu4c/source/common/unicode/unistr.h
As was pointed out in PR #3106, the standard doesn't mandate the existence of `std::char_traits<uint16_t>` and libc++ did actually deprecate it in release 18 and delete it in release 19.
As ICU4C uses this for backward compatibility for old code that still depends on setting `-DUCHAR_TYPE=uint16_t` it'd be nice to keep using it as long as possible but once it's gone from the standard library there isn't really much useful that ICU4C could do about that so conditionally compiling the code when the standard library version is old enough should suffice for keeping backward compatibility for yet some time.
https://github.com/llvm/llvm-project/commit/cce062d
=> ICU-22843 Check libc++ version for std::basic_string_view<uint16_t>

icu4c/source/common/uniset_props.cpp, icu4c/source/i18n/number_decimalquantity.cpp
This is a follow-up to PR #3076. There isn't really any advantage in wrapping these in string views, is there? Using plain string literals for UTF-16 strings just like already done for UTF-8 & ASCII strings makes the code simpler.
=> ICU-22843 Simplify UTF-16 string literals

icu4c/source/common/locdispnames.cpp
ICU-22721
Enhance `#if` for locdispnames.cpp from `#if ! UCONFIG_NO_BREAK_ITERATION` to `#if !UCONFIG_NO_BREAK_ITERATION` (remove spacing).
=> ICU-22721 Enhance #if for locdispnames.cpp

icu4c/source/common/unicode/uniset.h, icu4c/source/common/unicode/uset.h, icu4c/source/common/unicode/uversion.h, icu4c/source/common/uniset.cpp, icu4c/source/common/uniset_closure.cpp, icu4c/source/common/uset.cpp, icu4c/source/common/usetiter.cpp, icu4c/source/test/intltest/usettest.cpp, icu4c/source/test/intltest/usettest.h
Modern C++ iteration over the code points, ranges, or strings, or all of the elements, in a C++ UnicodeSet or C USet.
API approved by ICU-TC on 2024sep05.
Minor change sep09 during implementation testing:
Changed CodePointRange::iterator::operator++() from void to returning iterator & (usual signature)
- UnicodeSet.ranges() returns a USetRanges which has begin() & end() which return USetRangeIterator which works like an idiomatic C++ iterator.
- Parallel for UnicodeSet.codePoints() & UnicodeSet.strings().
- For iterating over all elements (code points & strings) in C++, by popular demand, I added begin() & end() directly to class UnicodeSet, similar to Java UnicodeSet which *is an* Iterable. The header-only wrapper still has separate range and iterator classes.
- For strings, adding new C …
=> ICU-22876 C++ UnicodeSet/USet easy item iteration

icu4c/source/test/fuzzer/collator_rulebased_fuzzer.cpp
Easy way to increase the fuzzer test coverage.
=> ICU-22716 Extend Collator fuzzing

icu4c/source/test/fuzzer/timezone_create_fuzzer.cpp
Easy way to increase the fuzzer test coverage.
=> ICU-22716 Test VTimeZone in fuzzer

icu4c/source/i18n/islamcal.cpp
Fix a regression caused by d43d216febe18d37ad840cbac3f953b989b65965
The line "        if (uprv_add32_overflow(eyear, (month / 12), &eyear)) {" was added to replace " eyear += (month / 12);" in the previous check in but I forgot to remove the line "eyear += (month / 12)" last time.
=> ICU-22863 Remove extra line in Islamic calendar

icu4c/source/test/fuzzer/Makefile.in
The running of message_formatter_fuzzer cause out of memory problem. We will address that in later PR.
=> ICU-22716 Temp turn off message_formatter_fuzzer

.github/workflows/wait-for-checks.yml
Post-merge CI workflows run on every commit after it merges to `main`. However, we also use the setting that interrupts a workflow run when a new commit gets added to the branch. 
In order to make commits on `main` in the Github UI not look like failures, we should not run the enforce-all-checks job after merging to `main`. This is the right change to make because the sole purpose of the enforce-all-checks job is to have intelligent automated enforcement of CI jobs _before merging_ (that is: as a requirement before a PR is allowed to merge).
=> ICU-22722 Prevent running PR check enforcement after merging PRs

icu4c/source/common/unicode/unistr.h, icu4c/source/common/unistr.cpp, icu4c/source/test/intltest/ustrtest.cpp
Both `std::u16string_view` and `std::wstring_view` are possible matches for `UnicodeString` as a template parameter, but adding an explicit overload avoids both having to make that choice and taking the detour through creating any string view at all.
=> ICU-22843 Disambiguate UnicodeString::readOnlyAlias() for MSVC

docs/processes/cldr-icu.md
The CLDR-ICU integration instructions should mention that for CLDR-ICU integrations that are part of the BRS steps for CLDR and ICU, there are some prerequisites on the CLDR side:
1. The CLDR task to update test data should be run)
2. THE CLDRModify passes no-options and -fP should be run
=> ICU-22883 Update CLDR-ICU instructions with CLDR prereqs for BRS integrations

icu4c/source/i18n/messageformat2_data_model.cpp, icu4c/source/i18n/messageformat2_formatter.cpp
Issue in icu_76::message2::MessageFormatter::~MessageFormatter
=> ICU-22884 Fix assertion and Heap-use-after-free

.github/workflows/wait-for-checks.yml
CIFuzz jobs take a while to start. Until they do, within a workflow run, their neutral status and warning about "can't find configs" was causing the enforce-all-checks jobs to falsely fail.
=> ICU-22721 Set delay for CI enforce checks job to allow other jobs to init

icu4c/source/common/unicode/uset.h, icu4c/source/common/unicode/utypes.h
This lets users who define U_SHOW_CPLUSPLUS_API=0 to not rely on unstable C++ DLL exports use C++ header-only APIs on top of stable C exports.
As discussed in the 2024-sep-12 ICU-TC meeting.
(FYI All of these visibility controls are marked `@internal`.)
=> ICU-22876 add U_SHOW_CPLUSPLUS_HEADER_API for C++ header-only APIs

icu4c/source/common/unicode/ucasemap.h, icu4c/source/common/unicode/unistr.h, icu4c/source/common/unicode/ustring.h
Fix API docs that claim that titlecasing functions use Unicode Technical Report #&zwnj;21 for the titlecase break iterator.
That was the case only for Unicode 3.2.
Use the wording from the Java API docs instead, which generically refers to the Unicode case mapping algorithms so that we need not adjust the docs every time this changes.
(Titlecasing has been using the word break iterator since Unicode 4.)
=> ICU-22722 toTitle does not use UTR 21

icu4c/source/configure, icu4c/source/configure.ac
Having commented-out checks for things that don't even need to be checked serves no purpose.
MSVC floating point optimizations don't need to be set, `/fp:precise` is the default and has been so for a very long time now:
https://learn.microsoft.com/en-us/cpp/build/reference/fp-specify-floating-point-behavior?view=msvc-140
ICU4C requires C++17 and there aren't any compilers capable of that without namespace support so there's no need to check that.
=> ICU-22310 Delete long since obsolete configure.ac sections

icu4c/source/configure, icu4c/source/configure.ac
This should make log files easier to read by removing uncertainity about what version of the compiler that actually is used.
=> ICU-22873 Make configure log versions of the compilers used

docs/userguide/collation/api.md, icu4c/source/i18n/unicode/coll.h, icu4c/source/i18n/unicode/ucol.h, icu4c/source/test/intltest/collationtest.cpp
=> ICU-22879 Provide collator based predicates for use with STL algorithms

LICENSE
Sync the one-character change in the config.guess license from https://github.com/unicode-org/icu/pull/3169/files#diff-37c409a2bcc2b9fb4ab8a4738e28dd19a2767fedc83196ce426d67b8a56906f0 into the ICU LICENSE file.
FYI: The aclocal.m4 license text did not change.
=> ICU-22874 sync config.guess license

icu4j/main/core/src/main/java/com/ibm/icu/message2/MFDataModel.java, icu4j/main/core/src/main/java/com/ibm/icu/message2/MFDataModelFormatter.java, icu4j/main/core/src/main/java/com/ibm/icu/message2/MFParser.java, icu4j/main/core/src/main/java/com/ibm/icu/message2/MFSerializer.java, icu4j/main/core/src/main/java/com/ibm/icu/message2/StringUtils.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/message2/CoreTest.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/message2/DefaultTestProperties.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/message2/MF2Test.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/message2/Param.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/message2/ParserSmokeTest.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/message2/SerializationTest.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/message2/Sources.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/message2/StringToListAdapter.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/message2/Unit.java, testdata/message2/icu-parser-tests.json
- Corresponds to https://github.com/unicode-org/message-format-wg/pull/883
- Also removes some unused imports
=> ICU-22893 Remove support for Unsupported, Private & Reserved constructs

.github/workflows/icu4c.yml
=> ICU-22873 Update CI to clang18 and enable -Werror

icu4c/source/test/intltest/utxttest.cpp
Fix bad spacing/formatting in utxttest.cpp resulting from PR [#2382](https://github.com/unicode-org/icu/pull/2382) (was supposed to fix typos but did not notice any, maybe they already got fixed under the minor docs fix ticket. This is a separate ticket because Markus originally asked me to make it one...)
=> ICU-22318 Fix bad spacing/formatting in utxttest.cpp

docs/userguide/format_parse/datetime/index.md
Better UserGuide explanation of date pattern char Y. The UserGuide already refers people to the more detailed Date Field Symbol table in the CLDR docs, but people seem to not go there for some pattern chars, including this one.
=> ICU-22397 Better UserGuide explanation of date pattern char Y

icu4j/main/core/src/main/java/com/ibm/icu/util/TimeZone.java
The equality comparison `id.equals(TimeZone.UNKNOWN_ZONE)` causes compiler warning:
> Unlikely argument type for `equals()`: `TimeZone` seems to be unrelated to `String`
I believe `String TimeZone.UNKNOWN_ZONE_ID` was intended instead of `TimeZone TimeZone.UNKNOWN_ZONE`.
The mistake is otherwise inconsequential, the check appears to be just an optimization/reliability matter.
There already is a test for this in [`TimeZoneTest.TestGetIanaID`](https://github.com/rqu/icu/blob/lr/ICU-22721-id-equals-timezone/icu4j/main/core/src/test/java/com/ibm/icu/dev/test/timezone/TimeZoneTest.java#L2421) and it is already passing.
---
=> ICU-22721 Fix trivial slip-up in ICU4J TimeZone.java

icu4c/source/i18n/messageformat2.cpp, icu4c/source/i18n/messageformat2_data_model.cpp, icu4c/source/i18n/messageformat2_errors.cpp, icu4c/source/i18n/messageformat2_errors.h, icu4c/source/i18n/messageformat2_formatter.cpp, icu4c/source/i18n/messageformat2_serializer.cpp, icu4c/source/i18n/unicode/messageformat2.h, icu4c/source/test/intltest/messageformat2test.cpp, icu4c/source/test/intltest/messageformat2test.h, icu4c/source/test/intltest/messageformat2test_utils.h
=> ICU-22762 MF2: Add methods to control error handling behavior

icu4c/source/test/intltest/messageformat2test.cpp, icu4c/source/test/intltest/messageformat2test.h
=> ICU-22890 MF2: Add lone surrogate test to parser

icu4j/main/core/src/main/java/com/ibm/icu/message2/DateTimeFormatterFactory.java, icu4j/main/core/src/main/java/com/ibm/icu/message2/MFDataModelFormatter.java, icu4j/main/core/src/main/java/com/ibm/icu/message2/MessageFormatter.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/message2/MessageFormat2Test.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/message2/TestUtils.java
Implements the decision at https://github.com/unicode-org/message-format-wg/pull/879
=> ICU-22894 MF2, ICU4J: implements configuring the error handling behavior

icu4c/source/i18n/persncal.cpp
Fix issue found by https://g-issues.oss-fuzz.com/issues/42538607
=> ICU-22730 Fix int32_t overflow in persian calendar

icu4c/source/i18n/number_capi.cpp, icu4c/source/i18n/number_simple.cpp, icu4c/source/i18n/unicode/simplenumberformatter.h, icu4c/source/i18n/unicode/usimplenumberformatter.h
=> ICU-22900 Remove deprecated SimpleNumber truncateStart

icu4c/source/i18n/messageformat2_parser.cpp, icu4c/source/i18n/messageformat2_parser.h, icu4c/source/i18n/messageformat2_serializer.cpp, icu4c/source/test/intltest/messageformat2test_read_json.cpp, icu4j/main/core/src/main/java/com/ibm/icu/message2/MFParser.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/message2/CoreTest.java, testdata/message2/syntax-errors-diagnostics.json, testdata/message2/syntax-errors-reserved.json, testdata/message2/valid-tests.json
=> ICU-22898 MF2: fix various parser bugs and add more tests

icu4c/source/Makefile.in
To prevent overlinking when publishing shared libraries, specify internal dependencies using Requires.private and Libs.private.
Use Libs.private in icu-uc.pc for libicudata.so, and Requires.private in icu-i18n.pc, icu-io.pc, and icu-lx.pc, so that ICU internal dependencies will not be bound into clients.
The resulting *.pc files will produce the following output for icu-i18n and icu-lx, provided pkgconf has commit 78d53ea0 (2.2.0 or later) which de-duplicates multiple -L options:
commit 78d53ea012dfbaf397bf8e6907efac5b51abac56
Author: Kai Pastor <dg0yt@darc.de>
Date:   Fri Feb 23 15:18:08 2024 +0100
Revise serials, traversal, flattening
`./configure --enable-shared ...`
#
#
% pkgconf --libs  icu-i18n
-L/opt/local/lib -licui18n
% pkgconf --libs --static icu-i18n
-L/opt/local/lib -licui18n …
=> ICU-22610 Use Requires.private and Libs.private

icu4c/source/common/uprops.cpp, icu4j/main/core/src/main/java/com/ibm/icu/impl/UCharacterProperty.java
Address Rich's comment in https://github.com/unicode-org/icu/pull/3026#pullrequestreview-2100162160
=> ICU-22707 better doc HST=V != GCB=V

icu4j/main/core/src/main/java/com/ibm/icu/impl/locale/LocaleObjectCache.java
When invoking get(K key) method of LocaleObjectCache, it may be blocked for a long time, looping in lines 45 and 53, because after the referent of SoftReference is set to NULL, it may take a long time to add SoftReference to its ReferenceQueue if GC is slowly.
For example, in the Concurrent Copying GC in Android Art virtual machine, the referent in SoftReference is set to null during the copying phase, while the SoftReference is added to its ReferenceQueue in the ReferenceQueueDaemon thread after GC, which experiences a long time in between
In fact, we have found many examples of blocking for more than 10s on some Android devices
=> ICU-22761 Optimize get value of LocaleObjectCache

icu4c/source/python/icutools/databuilder/test/filtration_test.py
`unittest.makeSuite()` was deprecated in Python 3.11 and removed in 3.13: https://docs.python.org/3.13/whatsnew/3.13.html#unittest
=> ICU-22721 Update filtration_test for Python 3.13

icu4c/source/Makefile.in
The generic recursive target calls target-local so also adding it to the dependency list results in races due to install-local being executed twice in parallel.  For example, install-manx can fail if the two install processes race and one process tries to chown a file that the other process has just deleted.
Also install-manx should be a phony target, and for clarity use `$^` instead of `$?` in the install command.
=> ICU-21172 fix install race

icu4c/source/common/unicode/platform.h
uchar.h was added in Cygwin version 3.5.0.  Unfortunately, the last version of Cygwin that supported i686 was 3.3.6, and I think 3.4 was the last version that supported Windows 7, so it is still somewhat relevant to a subset of users.
=> ICU-22721 extend char16_t workaround to cygwin less than 3.5

.github/workflows/cifuzz.yml, .github/workflows/icu4c.yml, .github/workflows/icu4j.yml, .github/workflows/icu_exhaustive_tests.yml, .github/workflows/icu_valgrind.yml
=> ICU-22721 Have the testdata folder trigger CI actions for both icu4c & icu4j

icu4c/source/common/putilimp.h, icu4c/source/common/unicode/platform.h, icu4c/source/config/mh-haiku, icu4c/source/configure.ac
=> ICU-22392 Add, primary support for Haiku

.github/workflows/icu4j.yml, testdata/message2/more-functions.json
At the code of the problem is a change in how Java parses strings to `Double`:
```
System.out.println(Double.valueOf("1234567890123456789"));
```
The results are:
jdk 17 : `1.23456789012345677E18`
jdk 21 : `1.2345678901234568E18`
The json parser was seeing a number and parsed it to a `Double`.
With the change the json parser sees a string and passes that on to our test suite, and the string is parsed / interpreted by our code.
So we just took control from the json parser.
Java supports a `long value = 1234567890123456789L`, there is no rounding, and the result from `MessageFormatter` is `"1,234,567,890,123,456,789"`, as one would expect.
So the current fix does not need to change any code in `MessageFormatter`.
It only bypasses the json parsing of numbers and informs the test code on how …
=> ICU-22919 Enable CI with JDK 21 and fix the json parsing

icu4c/source/tools/gencnval/gencnval.c
See: https://unicode-org.atlassian.net/browse/ICU-22912
=> ICU-22912 fix coverity warning in gencnval.c

icu4j/pom.xml
This is the same bug, and with the same root cause as [ICU-22605: The -sources.jar files in the 74.1 and 74.2 releases are (a lot) bigger than before](https://unicode-org.atlassian.net/browse/ICU-22605)
 
That was fixed in PR https://github.com/unicode-org/icu/pull/2743 by excluding the `/icudt*/` folder.
At the time that matched the name of the data folder, which included the version and endianness (for example `icudt74b`)
But we renamed that folder to be version independent.
It is now `icudata`.
And in the process we inadvertently started bypassing the filtering.
=> ICU-22930 The -sources.jar files in icu4j version 76.1 are AGAIN a lot bigger than before

docs/download/76.md, docs/download/index.md, docs/index.md
Migrate https://icu.unicode.org/download to GitHub Pages, second in the nav_order.
Small updates to download/76.
The merge target is main, not maint/maint-76, because we want the changes to go live right away in GitHub Pages. This is why I am using the ICU 77rc BRS ticket.
=> ICU-22922 migrate download index

icu4c/source/common/rbbinode.cpp, icu4c/source/common/rbbinode.h, icu4c/source/common/rbbitblb.cpp
To avoid stack overflow while building RBBI
=> ICU-22934 Limit the number of resursive call

icu4c/source/common/ucurr.cpp, icu4c/source/test/cintltst/currtest.c, icu4c/source/test/testdata/structLocale.txt
Adding ZWG to few static lists. 
Followed instructions in https://unicode-org.github.io/icu/processes/cldr-icu.html#5-generate-cldr-production-data-and-convert-for-icu (step 5f).
Also, based on discussion in https://github.com/unicode-org/icu/pull/2961, there is no lists to update in Java, so only done in C++.
=> ICU-22935 Add ZWG to static currency lists

icu4c/source/common/unicode/utf8.h, icu4c/source/common/usprep.cpp, icu4c/source/common/utf_impl.cpp, icu4c/source/i18n/scriptset.cpp, icu4c/source/i18n/scriptset.h, icu4c/source/test/cintltst/cloctst.c, icu4c/source/test/cintltst/creststn.c, icu4c/source/test/cintltst/cucdtst.c, icu4c/source/test/cintltst/udatatst.c, icu4c/source/test/intltest/caltest.cpp, icu4c/source/test/intltest/collationtest.cpp, icu4c/source/test/intltest/uvectest.cpp, icu4c/source/tools/makeconv/makeconv.cpp, icu4c/source/tools/toolutil/ucm.cpp, icu4c/source/tools/toolutil/ucm.h
=> ICU-22936 Replace all ICU4C code that uses UBool as an integer

icu4c/source/test/intltest/rbbitst.cpp
UAX #&zwnj;14 and ICU have reconverged in Unicode 16.0 and ICU 76.
=> ICU-21097 Remove LineBreakTest.txt workarounds

icu4c/source/common/loclikelysubtags.cpp, icu4c/source/test/cintltst/cloctst.c, icu4c/source/test/intltest/loctest.cpp, icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/util/ULocaleTest.java
Fix Locale addLikelySubtags when input is "und@x=private"
Since the code are shared by matcher and addLikelySubtags the behavior for this special case need to check an additional condition. 
For Java, just add the test case.
=> ICU-22765 fix uloc_addLikelySubtags on "und@x=private"

icu4c/source/common/putil.cpp
Fixes typo in URL in error message
- For minor changes you can use one of the following per-release tickets:
- ICU 77 code warnings/version updates: ICU-22920 — Fix compiler warnings. Update versions of code-related dependencies (e.g., dependabot).
- ICU 77 docs minor fixes: ICU-22921 — User Guide & API docs typos etc., and version updates (e.g., dependabot for User Guide)
=> ICU-22774 Fix URL typo in error message

icu4c/source/common/unicode/urename.h
Regenerated urename.h one last time (I hope) before the final ICU 76.1 release.  There was one change from the rc.
=> ICU-22724 Update urename.h for ICU 76.1 final.

.github/workflows/cache_retain.yml, .github/workflows/cifuzz.yml, .github/workflows/icu4c.yml, .github/workflows/icu4j.yml, .github/workflows/icu_common.yml, .github/workflows/icu_docs.yml, .github/workflows/icu_envtest.yml, .github/workflows/icu_exhaustive_tests.yml, .github/workflows/icu_merge_ci.yml, .github/workflows/icu_valgrind.yml, .github/workflows/jekyll-gh-pages.yml, .github/workflows/maven.yaml, .github/workflows/release-check-sign.yml, .github/workflows/release-icu4c-fedora.yml, .github/workflows/release-icu4c-ubuntu.yml, .github/workflows/release-icu4j-maven.yml, .github/workflows/scorecard.yml, .github/workflows/wait-for-checks.yml, docs/processes/release/tasks/build.md, vendor/double-conversion/upstream/.github/workflows/ci.yml, vendor/double-conversion/upstream/.github/workflows/cifuzz.yml, vendor/double-conversion/upstream/.github/workflows/scons.yml, vendor/double-conversion/upstream/.github/workflows/scorecard.yml
Pin ubuntu-latest, windows-latest, and macos-latest to their current values, with a note that those are updated in the BRS (I have added a post-release task to the BRS for that).
It does not seem trivial to have that configuration in a single place ([configuration variables](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#defining-configuration-variables-for-multiple-workflows) would work, but those are not part of the repository itself, so they are not source-controlled and they are only accessible to repository owners; I am also not sure how they would behave with PRs from forks). It might be possible to reduce this to one occurrence per file, but 22 files is enough that I would want to three global substitutes anyway, …
=> ICU-22946 Pin all -latest runners per ICU-TC 2024-10-17 🗡️

tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/IcuConverterConfig.java, tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/LdmlConverterConfig.java, tools/cldr/cldr-to-icu/src/test/java/org/unicode/icu/tool/cldrtoicu/SupplementalDataTest.java
I mistakenly did the original cleanup in `main` (PR https://github.com/unicode-org/icu/pull/3245)
This is a cherry-pick from `main` to `maint/maint-76`
=> ICU-22724 Clean up import statements

icu4c/source/acinclude.m4, icu4c/source/configure, icu4c/source/configure.ac
It should print just how to toggle the default. Following this shema, it is not necessary to include default=yes/no in the output.
- For minor changes you can use one of the following per-release tickets:
- ICU 77 code warnings/version updates: ICU-22920 — Fix compiler warnings. Update versions of code-related dependencies (e.g., dependabot).
- ICU 77 docs minor fixes: ICU-22921 — User Guide & API docs typos etc., and version updates (e.g., dependabot for User Guide)
=> ICU-22952 Make configure --help show --enable-* / --disable-* consistently

docs/userguide/icu_data/index.md
=> ICU-22951 Add documentation for --with-data-packaging=auto to the userguide

docs/userguide/format_parse/messages/mf2.md
This PR updates the user guide for MF2, moving statements into the present tense instead of future tense. It also adds a section on ICU4C that, for now, links out to https://messageformat.dev .
=> ICU-22947 Update user guide for MF2

.github/workflows/cache_retain.yml
=> ICU-22920 Only run Maven cache workflow on the upstream repo

icu4c/source/i18n/messageformat2_parser.cpp, icu4c/source/test/intltest/messageformat2test.cpp, icu4c/source/test/intltest/messageformat2test.h
In a previous version of the spec, unpaired surrogates in text or quoted literals were an error. 
A recent PR, https://github.com/unicode-org/message-format-wg/pull/906/ , made them allowable. This PR changes ICU4C to be consistent with the spec.
=> ICU-22953 MF2: Allow unpaired surrogates in text and quoted literals

icu4c/source/i18n/calendar.cpp, icu4c/source/test/intltest/caltest.cpp, icu4c/source/test/intltest/caltest.h
=> ICU-22962 fix int32_t overflow inside handleComputeJulianDay

icu4j/main/charset/pom.xml, icu4j/main/icu4j/pom.xml, icu4j/main/localespi/pom.xml, icu4j/pom.xml
The blocker was the missing `<name>` element, which is mandatory.
See https://central.sonatype.org/publish/requirements/#project-name-description-and-url
The second problem was that all modules were staged, not just the three we normally publish.
=> ICU-22965 Fix the problems we had with the maven deploy for ICU 76.1

icu4j/tools/build/src/main/java/com/ibm/icu/dev/tool/coverage/JacocoReportCheck.java, icu4j/tools/misc/src/main/java/com/ibm/icu/dev/tool/localeconverter/XLIFF2ICUConverter.java
Enhance XML Processor Configuration for Tools Directory in ICU4J Package
=> ICU-22888 Enhance XML Processor Configuration for Tools Directory in ICU4J Package

icu4j/main/core/src/main/java/com/ibm/icu/text/BreakIteratorFactory.java
Propagate the `MissingResourceException` when the data files for BreakIterator are not found
=> ICU-22960 Use `ICUBinary.getRequiredData()` to load BreakIterator data

docs/userguide/transforms/general/rules.md
To check I did a `RuleBasedTransliterator.createFromRules` with the rules in the userguide.
The result is indeed `"acks"`.
=> ICU-21396 Fix incorrect result shown in the userguide example

.github/workflows/icu4c.yml, .github/workflows/icu_merge_ci.yml
=> ICU-22977 Temp fix for MSVC builds: SkipUWP

docs/userguide/datetime/calendar/index.md, docs/userguide/locale/index.md, icu4c/source/test/intltest/dtptngts.cpp, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/format/DateTimeGeneratorTest.java
Support for obsolete locale ID variants was removed 5 years ago, see ICU-20187.
=> ICU-22870 Remove ja_JP_TRADITIONAL pattern generator tests

icu4c/source/test/intltest/loctest.cpp
Restore known issue check for 'und-Latn-RS', addressing issue https://unicode-org.atlassian.net/browse/ICU-22976
=> ICU-22920 fix exhaustive tests for likely subtags failure ICU-22976

icu4c/source/test/intltest/rbbitst.cpp
=> ICU-22127 Remove obsolete WordBreakTest.txt known issues

icu4c/source/common/locdispnames.cpp, icu4c/source/common/loclikely.cpp, icu4c/source/common/uloc.cpp, icu4c/source/common/uloc_tag.cpp, icu4c/source/common/ulocimp.h, icu4c/source/common/uresbund.cpp, icu4c/source/common/uscript.cpp, icu4c/source/i18n/tzgnames.cpp, icu4c/source/i18n/tznames_impl.cpp
=> ICU-22901 Update ulocimp_getSubtags() &co. to use std::string_view

icu4c/source/i18n/number_decimalquantity.cpp, icu4c/source/test/intltest/numfmtst.cpp, icu4c/source/test/intltest/numfmtst.h, icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/format/NumberRegressionTests.java, icu4j/main/core/src/main/java/com/ibm/icu/impl/number/DecimalQuantity_DualStorageBCD.java
Fix undefined behavior of shifting 64 bits in uint64 type
=> ICU-22983 Fix DecimalQuantity::shiftLeft ubsan issue

docs/userguide/dev/gitdev.md
https://unicode-org.github.io/icu/userguide/dev/gitdev.html#requesting-an-exhaustive-test-run-on-a-pull-request-pr points to Continuous Integration / Exhaustive Tests but has a bad indirection. It should just go sideways to its sibling page.
=> ICU-22921 fix link from gitdev to ci exhaustive tests

tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/Cldr2Icu.java, tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/Cldr2IcuCliOptions.java, tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/IcuConverterConfig.java, tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/LdmlConverter.java, tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/LdmlConverterConfig.java, tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/ant/ConvertIcuDataTask.java
About 4 times faster. Tested on Windows, MacOS, and Linux.
Right now it is opt-in.
Do you think it should be opt-out?
---
All on reasonably modern machines (Win & Linux: Intel CPU, 16 cores (8 Performance + 8 Economy), MacOS on a MacBook M3 Pro, 12 cores).
Why not 10 times faster (or more)? I guess the bottleneck moves somewhere else (disk?)
Good enough for now.
=> ICU-22773 Faster generation (4x) with multithreading

icu4c/source/tools/icuexportdata/icuexportdata.cpp
This changes the format of the normalization data export for ICU4X in the way expected by https://github.com/unicode-org/icu4x/pull/5813 , which makes the ICU4X normalizer significantly faster.
=> ICU-22968 Rearrange bits in trie values in normalization data export for ICU4X

docs/processes/release/tasks/healthy-code.md
=> ICU-22921 Document a way to remove unused includes from command line

icu4c/source/i18n/chnsecal.cpp, icu4c/source/i18n/gregocal.cpp
This PR prepare for future simplification of Calendar API. It replace the direct access to protected fStamp member data and replaced with protected method.
=> ICU-22991 Remove protected direct access to fStamp

icu4c/source/i18n/chnsecal.cpp, icu4c/source/test/intltest/caltest.cpp, icu4c/source/test/intltest/caltest.h
Fix int32 overflow found in https://g-issues.oss-fuzz.com/issues/383884624
=> ICU-22962 Fix int32 overflow in Chinese Calendar

icu4c/source/i18n/buddhcal.cpp, icu4c/source/i18n/buddhcal.h, icu4c/source/i18n/cecal.cpp, icu4c/source/i18n/cecal.h, icu4c/source/i18n/chnsecal.cpp, icu4c/source/i18n/gregocal.cpp, icu4c/source/i18n/hebrwcal.cpp, icu4c/source/i18n/indiancal.cpp, icu4c/source/i18n/islamcal.cpp, icu4c/source/i18n/japancal.cpp, icu4c/source/i18n/japancal.h, icu4c/source/i18n/persncal.cpp, icu4c/source/i18n/taiwncal.cpp, icu4c/source/i18n/taiwncal.h
1. Remove unnecessary call to setTimeInMillis(getNow(), success);  in constructor except in GregorianCalendar because allother calendar are not public class and are created through the Calendar::createInstance() method and code in that  method already call setTimeInMillis(getNow(), success);
Notice the Calendar API documentation states
"Like other locale-sensitive classes, Calendar provides a static method, createInstance, for getting a generally useful object of this type. Calendar's createInstance method returns the appropriate Calendar subclass whose time fields have been initialized with the current date and time:
Calendar *rightNow = Calendar::createInstance(errCode);
"
and this is guaranteed in the code
```
Calendar* U_EXPORT2
Calendar::createInstance(TimeZone* zone, const Locale& …
```
=> ICU-22991 Remove unnecessary overload in Calendar

icu4c/source/i18n/calendar.cpp, icu4c/source/i18n/unicode/calendar.h
Remove unused private fIsSet from Calendar to save 24 bytes per Calendar object.
Java removed the isSet field at least 24 years ago.
=> ICU-22991 Remove unused private fIsSet

icu4c/source/i18n/nfrule.cpp, icu4c/source/test/intltest/itrbnf.cpp, icu4c/source/test/intltest/itrbnf.h, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/format/RBNFParseTest.java
NFRule::parseRuleDescriptor need to check not overflowing the int64_t range before performing * 10  + digit.
Add unit test based on test data on https://g-issues.oss-fuzz.com/issues/385224936
=> ICU-23002 Fix int64_t overflow in NFRule::parseRuleDescriptor

icu4c/source/common/brkiter.cpp, icu4c/source/common/charstr.cpp, icu4c/source/common/charstr.h, icu4c/source/common/locbased.cpp, icu4c/source/common/locbased.h, icu4c/source/common/unicode/brkiter.h, icu4c/source/i18n/calendar.cpp, icu4c/source/i18n/dcfmtsym.cpp, icu4c/source/i18n/dtfmtsym.cpp, icu4c/source/i18n/format.cpp, icu4c/source/i18n/unicode/calendar.h, icu4c/source/i18n/unicode/dcfmtsym.h, icu4c/source/i18n/unicode/dtfmtsym.h, icu4c/source/i18n/unicode/format.h
These changes improve the overall peak memory usage and slightly improve
performance
```
main avg	main stdev	branch avg	branch stdev	diff avg	diff avg %
User time (seconds):	81.19	0.37	81.36	0.09	0.17	0.21%
System time (seconds):	5.03	0.08	4.86	0.05	-0.17	-3.38%
Percent of CPU this job got:	237.33%	0.01	235.33%	0.01	-2.00%	-0.84%
Maximum resident set size (kbytes):	227,141	99.14	226,667	366.48	-475	-0.21%
Minor (reclaiming a frame) page faults:	46,009	510.78	43,775	294.47	-2,234	-4.86%
Voluntary context switches:	333,442	4513.76	316,506	8850.48	-16,936	-5.08%
Involuntary context switches:	467	30.60	515	22.65	48	10.36%
```
Raw data in
https://docs.google.com/spreadsheets/d/10LQ3kO83EwvsFfoiySTzsTbIzfUV00Te4jQnX0b_FM4/edit?usp=sharing
=> ICU-23000 Replace CharString for LocaleBased

icu4c/source/i18n/calendar.cpp, icu4c/source/i18n/unicode/calendar.h, icu4j/main/core/src/main/java/com/ibm/icu/util/Calendar.java
Reduce 24x3=72 bytes per Calendar object by changing from 32 bits integer to 8 bits integer for the stamp array.
Reset the fNextStamp whenever we clear the fStamp. There are at most 24 different stamp values stored inside fStamp so using 7 bits to store up to 127 different one should be enough.
Also change to use bit fields for:
fIsTimeSet, fAreFieldsSet, fAreAllFieldsSet, fAreFieldsVirtuallySet, fLenient, fRepeatedWallTime, fSkippedWallTime, fFirstDayOfWeek, fWeekendOnset, fWeekendCease to save more space
=> ICU-22991 Reduce fStamp to 8 bits

icu4c/source/test/intltest/listformattertest.cpp, icu4c/source/test/intltest/listformattertest.h, icu4c/source/tools/ctestfw/tstdtmod.cpp, icu4c/source/tools/ctestfw/unicode/testlog.h
For some unknown reason the use of `std::u16string` in `class IcuTestErrorCode` since commit 5dff777fe045acfafba79ec1e9cb953dac6c068f causes the icu4c-windows-cygwin-gcc CI job to fail.
=> ICU-22954 Workaround to make the icu4c-windows-cygwin-gcc CI job work

icu4c/source/tools/ctestfw/tstdtmod.cpp, icu4c/source/tools/ctestfw/unicode/testlog.h
It seems as if `icu4c-windows-cygwin-gcc` only crashes if the constructor is defined inline, so with the exception of the constructor this commit reverts the code to commit 320220ef694123393a5c5d6eb6a1c7536fc57aba.
=> ICU-22954 Revert to using std::u16string instead of UnicodeString

icu4c/source/i18n/basictz.cpp, icu4c/source/i18n/calendar.cpp, icu4c/source/i18n/chnsecal.cpp, icu4c/source/i18n/erarules.cpp, icu4c/source/i18n/gregoimp.cpp, icu4c/source/i18n/gregoimp.h, icu4c/source/i18n/indiancal.cpp, icu4c/source/i18n/olsontz.cpp, icu4c/source/i18n/simpletz.cpp, icu4c/source/i18n/timezone.cpp, icu4c/source/i18n/tzrule.cpp, icu4c/source/i18n/unicode/calendar.h, icu4c/source/i18n/vtzone.cpp
Gregorian monthOfYear, dayOfMonth only need one byte dayOfYear only need two bytes to store.
These fields are used to store calculated value of day of year, day of month and month of year according to Gregorian calendar, and therefore will max to 365, 31 and 12 so it is a waste to store them with 4 bytes. We only need 9 bits, 5 bits, 4 bits for them. We can use bit fields to store but still need 18 bits which is more than 2 bytes. In this PR, I change to use 2 + 1 + 1 = 4 bytes to store them. Save 8 bytes per Calendar object
=> ICU-22991 Reduce Calendar object size

icu4c/source/data/icu4j-readme.txt, icu4j/extract-data-files.bat
The longer term fix would be to do it in Python, which would be cross-platform.
But that would need some "foundations":
- where to put all the scripts
- support modules (logging, exec, file system manipulation)
=> ICU-22921 Add windows script doing jar extraction

icu4j/main/core/src/main/java/com/ibm/icu/impl/Grego.java, icu4j/main/core/src/main/java/com/ibm/icu/impl/OlsonTimeZone.java, icu4j/main/core/src/main/java/com/ibm/icu/util/AnnualTimeZoneRule.java, icu4j/main/core/src/main/java/com/ibm/icu/util/BasicTimeZone.java, icu4j/main/core/src/main/java/com/ibm/icu/util/VTimeZone.java
Backport C++ code similification in PR 3327 to Java. Add timeToYear and dayToYear functions to skip unnecessary calculation.
=> ICU-22991 Reduce unnecessary Grego calculation

icu4c/source/i18n/messageformat2_parser.cpp, icu4c/source/i18n/messageformat2_parser.h
Improve checking for OOM errors when allocating UnicodeSets, per post-merge comments on https://github.com/unicode-org/icu/pull/3236
=> ICU-22940 MF2 ICU4C: Error checking improvements in parser

icu4c/source/test/fuzzer/date_format_fuzzer.cpp
Try to find out what cause ICU-23008. Use ICU-22929 as bug number to improve fuzzer to find the problem.
According to ICU-23008 bug report, the leak of DecimalFormatSymbols can be reach by udat_open when the style is UDAT_PATTERN
=> ICU-22929 Improve fuzzer to find leak from udat_open

icu4c/source/i18n/nfrs.cpp, icu4c/source/i18n/nfrule.cpp, icu4c/source/i18n/rbnf.cpp, icu4c/source/i18n/unicode/rbnf.h, icu4c/source/test/intltest/itrbnf.cpp, icu4c/source/test/intltest/itrbnf.h, icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/format/RbnfTest.java, icu4j/main/core/src/main/java/com/ibm/icu/text/NFRule.java, icu4j/main/core/src/main/java/com/ibm/icu/text/NFRuleSet.java, icu4j/main/core/src/main/java/com/ibm/icu/text/RuleBasedNumberFormat.java, icu4j/main/core/src/main/resources/com/ibm/icu/text/package.html
This feature enhancement only affects the documentation and RBNF syntax. Some changes were made to keep both the ICU4J and ICU4C implementations in sync.  Some compiler warnings were also fixed.
I’d like to extend the RBNF syntax to support more complex grammar.  I’d like to change the omission rule with square brackets.  By default, everything between the square brackets are omitted when the remainder is 0.  My proposal will not change this behavior by default, unless a “|” (pipe symbol) is present between the square brackets.  You can think of it performing like an else statement.  Everything between the beginning square bracket and the pipe acts as it currently does.  Everything between the pipe symbol and the end square bracket will be used instead of omitting the text.
This behavior …
=> ICU-22979 Support inverse rule for [] span in RBNF

icu4c/source/common/unicode/uset.h
Fix -Wshadow warnings displayed when compiling ICU4C 76.1 or later.
=> ICU-22966 Fix -Wshadow warnings in unicode/uset.h

icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/format/MeasureUnitTest.java, icu4j/main/core/src/main/java/com/ibm/icu/impl/units/MeasureUnitImpl.java, icu4j/main/core/src/main/java/com/ibm/icu/util/MeasureUnit.java
- Introduced a new field for constant denominators in MeasureUnitImpl.
- Added methods to set and retrieve constant denominators in MeasureUnit.
- Updated parsing logic to handle unit constants correctly.
- Enhanced unit tests to cover new functionality, including constant denominator scenarios.
- Improved code readability and consistency across MeasureUnit and SingleUnitImpl classes.
1. Add support to unit constant during units conversion.
2. Add support to unit constant during units formatting.
=> ICU-22781 Adding support for constant denominators (JAVA)

icu4j/main/core/src/main/java/com/ibm/icu/util/MeasureUnit.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/impl/UnitsTest.java
- Fix a small issue `withConstantDenominator` in Java
- Add test cases to test the behaviour of `withConstantDenominator`.
=> ICU-22781 Fix and Add unit tests for withConstantDenominator in MeasureUnit

icu4c/source/i18n/measunit.cpp, icu4c/source/i18n/measunit_extra.cpp, icu4c/source/i18n/measunit_impl.h, icu4c/source/i18n/unicode/measunit.h, icu4c/source/test/depstest/dependencies.txt, icu4c/source/test/intltest/measfmttest.cpp, icu4c/source/test/intltest/units_test.cpp
- Introduced a new field for constant denominators in MeasureUnitImpl.
- Added methods to set and retrieve constant denominators in MeasureUnit.
- Updated parsing logic to handle unit constants correctly.
- Enhanced unit tests to cover new functionality, including constant denominator scenarios.
- Improved code readability and consistency across MeasureUnit and SingleUnitImpl classes.
1. Add support to unit constant during units conversion.
2. Add support to unit constant during units formatting.
=> ICU-22781 Adding support for constant denominators (C++)

docs/userguide/dev/ci.md, docs/userguide/dev/gitdev.md
* Fix link from gitdev to ci/exhaustive-tests.
* Fix link from ci to gitdev.
=> ICU-22921 Fix broken link in userguide

icu4j/main/core/src/main/java/com/ibm/icu/impl/units/ConversionRates.java, icu4j/main/core/src/main/java/com/ibm/icu/impl/units/UnitsConverter.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/impl/UnitsTest.java
Implement handling of constant denominators in unit conversion:
- Add divide method to Factor class in UnitsConverter
- Update ConversionRates to apply constant denominator during conversion
- Add comprehensive test cases for units with constant denominators
=> ICU-22781 Add support for converting units with constant denominators (Java)

icu4c/source/i18n/chnsecal.cpp, icu4c/source/i18n/gregoimp.cpp, icu4c/source/i18n/olsontz.cpp, icu4c/source/i18n/simpletz.cpp, icu4c/source/i18n/timezone.cpp
Use timeToFields instead of dayToFields if possible.
=> ICU-22991 Simplified Grego code

icu4c/source/i18n/chnsecal.cpp, icu4c/source/i18n/chnsecal.h, icu4c/source/test/intltest/calregts.cpp, icu4c/source/test/intltest/caltest.cpp, icu4c/source/test/intltest/caltest.h, icu4j/main/core/src/main/java/com/ibm/icu/util/Calendar.java, icu4j/main/core/src/main/java/com/ibm/icu/util/ChineseCalendar.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/calendar/CalendarRegressionTest.java
Read the IS_LEAP_MONTH field correctly while calling getActualMaximize.
Chinese Calendar need to read additional IS_LEAP_MONTH field while calculate the start and length of month, make the value read from the out most calls and passed into function parameter.
=> ICU-23006 Fix Chinese Calendar getActualMaximize

icu4c/source/test/intltest/rbbitst.cpp
=> ICU-22984 Generate the C++ UAX29 monkeys

icu4c/source/i18n/messageformat2_function_registry.cpp
Based on ICU-23011 I offer to add else branch to avoid nullptr dereference
=> ICU-23011 Add else branch for remove possible CWE-476

icu4c/source/common/resbund.cpp, icu4c/source/common/unicode/resbund.h, icu4c/source/i18n/timezone.cpp, icu4c/source/i18n/unicode/messageformat2_data_model.h, icu4c/source/i18n/unicode/timezone.h, icu4c/source/tools/ctestfw/datamap.cpp, icu4c/source/tools/ctestfw/unicode/datamap.h
Returning a const-qualified prvalue doesn't do anything useful, but it does turn an assignment such as `v = rb.getLocale();` from a move-assignment into a copy-assignment (because it's forbidden to move-from a const value, even if it's a const prvalue). Each affected site was diagnosed mechanically by my fork of Clang. E.g.:
warning: 'const' type qualifier on return type is a bad idea [-Wqual-class-return-type]
391 | const Locale ResourceBundle::getLocale(ULocDataLocaleType type, UErrorCode &status) const
| ^~~~~
=> ICU-22920 Avoid "return by const value" antipattern

icu4c/source/test/cintltst/cmsgtst.c
https://unicode-org.atlassian.net/browse/ICU-23026: This change disable part of `cmsgtst/MessageFormatTest` for QNX 8.0 since it will crash the test.
Test instructions will be provided in the near future.
[ICU-23026]: https://unicode-org.atlassian.net/browse/ICU-23026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ICU-23026 Add support to QNX 8.0 and fix test

icu4c/source/i18n/calendar.cpp, icu4c/source/test/intltest/caltest.cpp, icu4c/source/test/intltest/caltest.h
Fix bug found by fuzzer in https://g-issues.oss-fuzz.com/issues/386415618
=> ICU-22962 Fix int32_t overflow issue when month is large

icu4c/source/common/unicode/uniset.h, icu4c/source/common/unicode/uset.h, icu4c/source/test/intltest/usetheaderonlytest.cpp, icu4c/source/test/intltest/usettest.cpp
... to make the sample code work without U_SHOW_CPLUSPLUS_API as discussed in https://github.com/unicode-org/icu/pull/3295#discussion_r1892174805
I am also moving the non-sample code above the commented-out sample code, for clarity.
=> ICU-22954 USet C++ iter samples no UnicodeString

icu4c/source/common/charstr.cpp, icu4c/source/common/charstr.h, icu4c/source/i18n/measunit_extra.cpp, icu4c/source/test/intltest/units_test.cpp
- Add support for generating more compact identifiers for constant denominators
- Introduce methods to convert large constant denominators to scientific notation
- Update MeasureUnitImpl to use new constant denominator string generation
- Add test cases to verify identifier generation for various constant denominator scenarios
=> ICU-22781 Fix &Improve MeasureUnit identifier generation for constant denominators (C++)

icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/format/NumberFormatTest.java, icu4j/main/core/src/main/java/com/ibm/icu/impl/number/LongNameHandler.java, icu4j/main/core/src/main/java/com/ibm/icu/impl/units/MeasureUnitImpl.java, icu4j/main/core/src/main/java/com/ibm/icu/util/MeasureUnit.java
- Added support for constant denominators in MeasureUnit and LongNameHandler
- Updated MeasureUnit serialization and product methods to handle constant denominators
- Added test cases for formatting units with arbitrary constant denominators
- Added comprehensive test coverage for complex unit formatting scenarios
Related ticket that needs to be addressed: https://unicode-org.atlassian.net/browse/ICU-23039
=> ICU-22781 Support Arbitrary Constant Unit Formatting (Java)

docs/download/76.md, docs/download/77.md, docs/processes/release/tasks/publish/index.md
First cut of the download page. To be refined.
Not yet linked from other pages.
Also add known issues to the ICU 76 download page.
=> ICU-22922 initial ICU 77 download page; incomplete

.github/workflows/icu_merge_ci.yml
The workflow was trying to repair old-xmls.tar.bz2
Which was broken (the first commit in my pull request https://github.com/unicode-org/icu/pull/3375)
Although the right fix would have been to restore the file for good.
But this "fix" does not work now, on a removed file :-) (the second commit in the mentioned PR)
Anyway... the whole folder 'tools/multi' is not needed, so it should be good now.
=> ICU-22967 Remove explicit manipultaion of old-xmls.tar.bz2 in workflows

icu4c/source/common/unicode/char16ptr.h, icu4c/source/i18n/unicode/ucol.h, icu4c/source/test/intltest/Makefile.in, icu4c/source/test/intltest/cplusplus_header_api_build_test.cpp, icu4c/source/test/intltest/intltest.vcxproj, icu4c/source/test/intltest/intltest.vcxproj.filters, icu4c/source/test/intltest/itutil.cpp, icu4c/source/test/intltest/ucolheaderonlytest.cpp
Until now, the implementation of the `UCollator` predicates has been using `UnicodeString` and `StringPiece` as convenient wrappers for converting from standard C++ data types to ICU4C data types.
But as that doesn't work when the client uses ICU4C built without `U_SHOW_CPLUSPLUS_API` this is now changed to instead perform these conversions directly.
(It's a bit more code, but does just the same thing in the end.)
Then add a build test for all header files that use `U_SHOW_CPLUSPLUS_HEADER_API` to verify that they now all can be built without `U_SHOW_CPLUSPLUS_API`.
With this all done, ICU-22954 should be resolved.
=> ICU-22954 Make UCollator predicates usable without U_SHOW_CPLUSPLUS_API

icu4c/source/common/punycode.cpp
I checked a lot source code, and think we should use this type of check to avoid possible CWE-476 or CWE-190/CWE-369
=> ICU-23035 Fix bound check at `u_strToPunycode`

icu4c/source/i18n/number_mapper.cpp
resolveCurrency() slows down simple number formatting requests like:
```
for (int i = 0; i < 9999; i++)
u_snprintf_u(buff, 100, u"%d", i);
```
Since icu4c doesn't use currency there, we can skip its initialization.
=> ICU-22950 Do not initialize currency for NumberPropertyMapper when useCurrency is false

icu4c/source/test/intltest/numbertest.h, icu4c/source/test/intltest/numbertest_api.cpp
- Added a new test method `TestPortionFormat()` in `numbertest_api.cpp`
- Updated `numbertest.h` to declare the new test method
- Test covers formatting of "portion-per-1e9" unit in different locales
- Includes test cases for singular and plural forms
- Handles known issue for other portion units with a log message
java code : https://github.com/unicode-org/icu/pull/3390
=> ICU-22781 Add test for portion format with parts per billion (C++)

icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/format/NumberFormatTest.java
- Expanded test cases for portion unit formatting
- Added support for different locales (en-US, de-DE)
- Improved test coverage for portion unit formatting
- Added handling for known CLDR data limitations
Cpp code: https://github.com/unicode-org/icu/pull/3389
=> ICU-22781 Add test for portion format with parts per billion (Java)

icu4c/source/i18n/calendar.cpp, icu4c/source/i18n/chnsecal.cpp, icu4c/source/i18n/gregocal.cpp, icu4c/source/i18n/hebrwcal.cpp, icu4c/source/i18n/hebrwcal.h, icu4c/source/i18n/indiancal.cpp, icu4c/source/i18n/indiancal.h, icu4c/source/i18n/islamcal.cpp, icu4c/source/i18n/islamcal.h, icu4c/source/i18n/persncal.cpp, icu4c/source/i18n/persncal.h, icu4c/source/i18n/unicode/calendar.h, icu4c/source/i18n/unicode/gregocal.h, icu4c/source/test/intltest/caltest.cpp, icu4c/source/test/intltest/dtfmttst.cpp, icu4c/source/test/intltest/dtfmttst.h
Avoid crash inside calendar while the value is out of service range and cause inconsistent values, propogate error out.
=> ICU-23043 Return error for Chinese Calendar.

icu4c/source/i18n/measunit_extra.cpp, icu4c/source/i18n/number_longnames.cpp, icu4c/source/test/intltest/numbertest.h, icu4c/source/test/intltest/numbertest_api.cpp, icu4j/main/core/src/main/java/com/ibm/icu/util/MeasureUnit.java
- Added support for constant denominators in MeasureUnit and LongNameHandler
- Updated MeasureUnit serialization and product methods to handle constant denominators
- Added test cases for formatting units with arbitrary constant denominators
- Added comprehensive test coverage for complex unit formatting scenarios
Related ticket that needs to be addressed: https://unicode-org.atlassian.net/browse/ICU-23039
=> ICU-22781 Support Arbitrary Constant Unit Formatting

icu4c/source/test/intltest/numbertest_api.cpp, icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/format/NumberFormatTest.java
- Added comments indicating CLDR-18274 for failing portion unit formatting tests
- Updated test cases in both C++ and Java test files
=> ICU-22781 Add CLDR-18274 failing comments to portion unit formatting tests

icu4c/source/io/unicode/ustdio.h
Update doc comment so that the actual behaviour of u_fgetcx is correctly described.
https://unicode-org.atlassian.net/browse/ICU-22808
- [ x ] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-NNNNN
- For minor changes you can use one of the following per-release tickets:
- ICU 77 code warnings/version updates: ICU-22920 — Fix compiler warnings. Update versions of code-related dependencies (e.g., dependabot).
- ICU 77 docs minor fixes: ICU-22921 — User Guide & API docs typos etc., and version updates (e.g., dependabot for User Guide)
- [ x ] Required: The PR title must be prefixed with a JIRA Issue number. Example: "ICU-1234 Fix xyz"
- [ x ] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item …
=> ICU-22808 Correct a factually incorrect doc comment.

icu4c/source/common/rbbinode.cpp, icu4c/source/common/rbbinode.h, icu4c/source/common/rbbiscan.cpp, icu4c/source/common/rbbisetb.cpp, icu4c/source/common/rbbitblb.cpp
=> ICU-22934 clean up error handling in PR#3230

icu4c/source/common/uloc.cpp, icu4c/source/test/cintltst/cloctst.c, icu4c/source/test/cintltst/cloctst.h
Inside of `locimp_forLanguageTag()` in `_appendKeywords()` in `uloc_tag.cpp` there's a hardcoded special case for `-u-va-posix` which appends the `_POSIX` variant but this was missed during the refactoring made for ICU-22520 (there isn't any test case that covers this).
So the call to `locimp_forLanguageTag()` did more than previously understood, but we still don't want to have to call that for every language tag that has BCP-47 extensions just in order to get to this special case. Instead, add a special case also to `ulocimp_getSubtags().`
For this to work nicely, the loop in `_getVariant()` that copies variants needs to be refactored so that it easily can break when encountering the start of any BCP-47 extension (which also has the welcome side-effect of making it more efficient, being …
=> ICU-23031 Reinstate special case for "-u-va-posix" lost by ICU-22520

icu4c/source/test/intltest/measfmttest.cpp, icu4c/source/test/intltest/units_test.cpp, icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/format/MeasureUnitTest.java
Re-enable previously commented out tests for constant denominators in units tests for both ICU4C and ICU4J. This includes tests for:
- Large power of 10 denominators
- Scientific notation denominators
- Specific unit denominators
Added notes about potential CLDR-related edge cases for certain unit representations.
=> ICU-22781 Uncomment and enable constant denominator tests

icu4c/source/common/locid.cpp, icu4c/source/common/ulocale.cpp, icu4c/source/common/unicode/locid.h
=> ICU-22901 Update Locale::init() to use StringPiece

icu4c/source/test/intltest/tzfmttst.cpp, icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/format/TimeZoneFormatTest.java, icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/util/ULocaleTest.java
Updating code for 3 Closed JIRA ids: ['CLDR-18002', 'ICU-22857', 'ICU-22984']
Changed logKnownIssue for 'CLDR-18002' to logKnownIssue for 'ICU-23052' in main/common_tests/src/test/java/com/ibm/icu/dev/test/util/ULocaleTest.java
This now triggers only on locale "und-Latn-RS".
Resolved ICU-22857: ['ICU-22857', 'logKnownIssue', 'main/common_tests/src/test/java/com/ibm/icu/dev/test/format/TimeZoneFormatTest.java', 279]
Resolved ICU-22857: ['ICU-22857', 'logKnownIssue', 'test/intltest/tzfmttst.cpp', 342]
=> ICU-22922 Scrubbing closed issues

.github/workflows/release-icu4c-ubuntu.yml
=> ICU-22922 BRS77 Fix version in release-icu4c-ubuntu.yml

icu4c/source/common/unistr.cpp, icu4c/source/test/intltest/ustrtest.cpp, icu4c/source/test/intltest/ustrtest.h
=> ICU-23060 Fix heap-buffer-overflow when UnicodeString size too large

icu4c/source/common/unistr.cpp, icu4c/source/test/intltest/ustrtest.cpp
Correct the test based on the kMaxCapacity
setToBogus on error
Follow up the incomplete work in https://github.com/unicode-org/icu/pull/3416
=> ICU-23060 Fix largeAppend

icu4c/source/i18n/messageformat2.cpp, icu4c/source/i18n/messageformat2_evaluation.cpp, icu4c/source/i18n/messageformat2_formatter.cpp, icu4c/source/i18n/messageformat2_function_registry.cpp, icu4c/source/i18n/messageformat2_function_registry_internal.h, icu4c/source/i18n/unicode/messageformat2_formattable.h
This PR implements most of the suggested changes from https://github.com/unicode-org/icu/pull/3216 that weren't handled before merging.
[ICU-22907]: https://unicode-org.atlassian.net/browse/ICU-22907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ICU-23073 Use string_view constants for option names and formatter names

icu4c/source/i18n/numparse_validators.cpp, icu4c/source/test/intltest/numfmtst.cpp, icu4c/source/test/intltest/numfmtst.h, icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/format/NumberFormatTest.java, icu4j/main/core/src/main/java/com/ibm/icu/impl/number/parse/RequireDecimalSeparatorValidator.java
If a DecimalFormat pattern contains a decimal point and setDecimalPatternMatchRequired is true, then DecimalFormat parse() fails to parse infinity/NaN representations. This is because infinfity/NAn parsing does not set the HAS_DECIMAL_SEPARATOR_FLAG and so the RequireDecimalSeparatorValidator fails.
This modifies the RequireDecimalSeparatorValidator so that it does not fail if the INFINITY or NAN flags are set, making it so decimal separators are not required if the infinity/NaN representations are parsed.
=> ICU-22303 Support parsing infinity/NaN when decimal pattern match is required

docs/userguide/icu_data/buildtool.md
The pre-existing link to https://hjson.org goes to some sort of gambling/gaming site. It looks like the new authoritative link is https://hjson.github.io/
=> ICU-23055 Update buildtool.md to point to hjson.github.io

icu4j/main/localespi/pom.xml, icu4j/perf-tests/pom.xml, icu4j/pom.xml
- perf-tests: the copy was a convenience (as the comment said)
- icu4j-localespi: the copy was only needed for JDK 8. Moving it into a self-activating profile (based on jdk version) means that the copy still happens when building with maven under jdk 8, but will not get activated in Eclipse (so no error)
- The use of ../testdata (the warning) is an incorrect way to share resources they should have their own (resource only) Maven artifact. And nothing in the folder is not used by icu4j right now. \
ICU-23050 (_"Deduplicate C & Java testdata to a common directory"_) is still open.
=> ICU-23086 Fix Eclipse errors on imported projects

icu4j/main/core/src/main/java/com/ibm/icu/text/UnicodeSet.java
This only affects users of the internal perpetually-`@draft` XSymbolTable (in particular, unicode-org/unicodetools). It makes it possible to distinguish \p{X} (the characters that have binary property X, or that have gc X or script X) from \p{X=} (the characters for which property X is the empty string).
Note that ICU allows \p{Whitespace=} for \p{Whitespace}, or \p{L=} for \p{L}. This remains the case with this change, so the public API is unaffected.
=> ICU-23087 Pass null to applyPropertyAlias for a unary property query

icu4c/source/test/fuzzer/Makefile.in, icu4c/source/test/fuzzer/decimal_format_symbols_fuzzer.cpp, icu4c/source/test/fuzzer/fuzzer_utils.h
Add a fuzzer for DecimalFormatSymbols to explore possible cause of https://g-issues.chromium.org/issues/407149905
=> ICU-23095 Add fuzzer for DecimalFormatSymbols

icu4c/source/i18n/unicode/measunit.h, icu4j/main/core/src/main/java/com/ibm/icu/util/MeasureUnit.java
Deprecate ICU4C createMetricTon/getMetricTon, ICU4J METRIC_TON per [API proposal approved 2025-03-27](https://docs.google.com/document/d/19vv8vxCJiaWZEsR56Ospyr_UbJvl0AW86IZCoMM4bxs/edit?tab=t.0#heading=h.js0nkbazwftv).
=> ICU-22142 Deprecate ICU4C createMetricTon/getMetricTon, ICU4J METRIC_TON

icu4c/source/Makefile.in
ICU-23098
This change allows `make -j 2 check` to pass. This allows faster testing of ICU, and I like fast builds. It was failing because `config/Makefile.inc` is using `ifeq (selfcheck,$(MAKECMDGOALS)) #M#` to check if a self check is run, and the variable can include the other arguments, like the parallels building option. These self check lines are removed when the file is installed.
I confirmed that this change allows testing to fully succeed. It's run right after running intltest, iotest, and cintltst. The rest of the ICU build seems to work when specifying `-j32`.
=> ICU-23098 Allow tests to pass with parallel building

icu4c/source/i18n/nfrule.cpp
Fix fuzzer found Floating-point-exception in icu_78::NFRule::makeRules. The bug is found by fuzzer at https://g-issues.oss-fuzz.com/issues/410114671?pli=1&authuser=0
=> ICU-23109 Fix float point exception cased by "% 0"

icu4c/source/i18n/nfrule.cpp
Andy pointed out in https://github.com/unicode-org/icu/pull/3473 that some of the operation did not check error code while it should. This PR return the error earlier to avoid unnecessary work upon error and exception
=> ICU-23109 Early return on error

icu4c/source/common/uposixdefs.h
Fixes: https://unicode-org.atlassian.net/browse/ICU-23099
```
/opt/local/bin/g++-mp-14 -DU_ALL_IMPLEMENTATION -DU_ATTRIBUTE_DEPRECATED= -DU_COMMON_IMPLEMENTATION -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -DU_HAVE_STRTOD_L=1 -DU_HAVE_XLOCALE_H=1 -I. "-DDEFAULT_ICU_PLUGINS=\"/opt/local/lib/icu\" " -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -arch x86_64 -W -Wall -pedantic -Wpointer-arith -Wwrite-strings -Wno-long-long -std=c++17 -fvisibility=hidden -fno-common -c -MMD -MT "putil.d putil.o putil.ao" -o putil.ao putil.cpp
In file included from /opt/local/include/gcc14/c++/stdlib.h:36,
from uassert.h:23,
from putil.cpp:62:
/opt/local/include/gcc14/c++/cstdlib:136:11: error: 'aligned_alloc' has not been declared in '::'
136 |   using …
```
=> ICU-23099 uposixdefs.h: define _DARWIN_C_SOURCE on macOS

icu4c/source/i18n/gregocal.cpp, icu4c/source/i18n/unicode/gregocal.h
Remove unnecessary fNormalizedGregorianCutover which is not read for any decision making nor in ICU4J.
=> ICU-23102 Simplify GregorianCalendar

icu4c/source/i18n/calendar.cpp, icu4c/source/i18n/chnsecal.cpp, icu4c/source/i18n/chnsecal.h, icu4c/source/i18n/coptccal.cpp, icu4c/source/i18n/coptccal.h, icu4c/source/i18n/dangical.cpp, icu4c/source/i18n/dangical.h, icu4c/source/i18n/ethpccal.cpp, icu4c/source/i18n/ethpccal.h, icu4c/source/i18n/hebrwcal.cpp, icu4c/source/i18n/hebrwcal.h, icu4c/source/i18n/indiancal.cpp, icu4c/source/i18n/indiancal.h, icu4c/source/i18n/persncal.cpp, icu4c/source/i18n/persncal.h, icu4c/source/i18n/unicode/calendar.h, icu4j/main/core/src/main/java/com/ibm/icu/util/Calendar.java, icu4j/main/core/src/main/java/com/ibm/icu/util/ChineseCalendar.java, icu4j/main/core/src/main/java/com/ibm/icu/util/CopticCalendar.java, icu4j/main/core/src/main/java/com/ibm/icu/util/EthiopicCalendar.java, icu4j/main/core/src/main/java/com/ibm/icu/util/HebrewCalendar.java, icu4j/main/core/src/main/java/com/ibm/icu/util/IndianCalendar.java, icu4j/main/core/src/main/java/com/ibm/icu/util/IslamicCalendar.java, icu4j/main/core/src/main/java/com/ibm/icu/util/PersianCalendar.java
Merge int32 overflow handling code in C++
Use real OOP style programming to implement (g|s)etRelatedYear in Java
Move Islamic calendar only logic into IslamicCalendar.java
=> ICU-23102 Refactor and simplify Calendar code

icu4c/source/i18n/cecal.cpp, icu4c/source/i18n/cecal.h, icu4c/source/i18n/coptccal.cpp, icu4c/source/i18n/coptccal.h, icu4c/source/i18n/ethpccal.cpp, icu4c/source/i18n/ethpccal.h, icu4c/source/i18n/indiancal.cpp, icu4j/main/core/src/main/java/com/ibm/icu/util/CECalendar.java, icu4j/main/core/src/main/java/com/ibm/icu/util/CopticCalendar.java, icu4j/main/core/src/main/java/com/ibm/icu/util/EthiopicCalendar.java, icu4j/main/core/src/main/java/com/ibm/icu/util/IndianCalendar.java
Avoid calling unnecessary computeGregorianFields() Refactor and reduced handleComputeFields in CECalendar
=> ICU-23102 Simplify Calendar code

icu4c/source/common/unicode/uniset.h, icu4c/source/i18n/unicode/dtitvinf.h, icu4c/source/i18n/unicode/regex.h, icu4c/source/i18n/unicode/tblcoll.h
Clang has recently added a warning for code with the `virtual` keyword on methods of `final` classes that don't override anything. Such classes can never be subclassed, so the keyword is meaningless. This fixes instances of that warning in ICU.
=> ICU-23107 Remove unnecessary virtual specifiers

icu4j/main/core/pom.xml
Left over from PR ##3450.
This only a warning, not an error, but still "unclean".
=> ICU-23054 Fix Eclipse warning, leftover from un-sharing test data

icu4c/source/tools/genrb/genrb.cpp
The error was found by clang's recently improved -Wtautological-overlap-compare diagnostic.
=> ICU-23122 Fix a comparison error

icu4j/main/core/src/main/java/com/ibm/icu/impl/JavaTimeConverters.java, icu4j/main/core/src/main/java/com/ibm/icu/impl/RBBIDataWrapper.java, icu4j/main/core/src/main/java/com/ibm/icu/impl/number/DecimalQuantity_AbstractBCD.java, icu4j/main/core/src/main/java/com/ibm/icu/impl/personname/PersonNameFormatterImpl.java, icu4j/main/core/src/main/java/com/ibm/icu/text/NFSubstitution.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/number/NumberSkeletonTest.java, icu4j/perf-tests/src/main/java/com/ibm/icu/dev/test/perf/CollationPerformanceTest.java, icu4j/perf-tests/src/main/java/com/ibm/icu/dev/test/perf/RBBIPerf.java
Fixed: `CheckReturnValue`, `EqualsHashCode`, `JavaTimeDefaultTimeZone`
And a couple of resource leaks (streams opened and not closed)
=> ICU-23054 Fix several types of errorprone warnings

icu4c/source/test/intltest/rbbitst.cpp, icu4c/source/test/intltest/rbbitst.h, icu4j/main/core/src/main/java/com/ibm/icu/text/BreakIterator.java, icu4j/main/core/src/main/java/com/ibm/icu/text/RuleBasedBreakIterator.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/rbbi/BreakIteratorTest.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/rbbi/RBBITest.java
Make `BreakIterator.preceding()` return `DONE` when given a negative index for the input string. A negative index is already out of bounds and comes before the start of the string. The current behavior is to return 0, which doesn't make sense and is misleading. By contrast, the current behavior also returns 0 for an index of 1, which does make sense.
=> ICU-22987 Return DONE for BreakIterator.preceding on negative index

icu4c/source/common/locid.cpp, icu4c/source/common/rbbisetb.cpp, icu4c/source/common/ucasemap.cpp, icu4c/source/common/ucnv.cpp, icu4c/source/common/uidna.cpp, icu4c/source/common/unistr_cnv.cpp, icu4c/source/common/usprep.cpp, icu4c/source/common/ustr_wcs.cpp, icu4c/source/common/uts46.cpp, icu4c/source/extra/uconv/uwmsg.c, icu4c/source/i18n/collationdatawriter.cpp, icu4c/source/i18n/rematch.cpp, icu4c/source/i18n/uspoof_conf.cpp, icu4c/source/tools/ctestfw/uperf.cpp
When it's expected that a function call might result in setting `U_BUFFER_OVERFLOW_ERROR` upon which a new buffer is allocated and the function call is retried, this should upon success not overwrite any already set value of `UErrorCode`, as this could accidentally overwrite some valid and meaningful value when this was other than `U_ZERO_ERROR`.
=> ICU-23128 Don't clobber UErrorCode on expected U_BUFFER_OVERFLOW_ERROR

icu4j/main/core/src/main/java/com/ibm/icu/text/RuleBasedBreakIterator.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/rbbi/BreakIteratorTest.java
In `BreakIterator`, change `IllegalArgumentException` to `IndexOutOfBoundsException` when the index is out of bounds.
=> ICU-23124 Fix exception type in BreakIterator for OOB index values

icu4j/main/collate/src/test/java/com/ibm/icu/dev/test/collator/CollationMiscTest.java, icu4j/pom.xml, icu4j/tools/build/pom.xml, icu4j/tools/build/src/main/java/com/ibm/icu/dev/tool/errorprone/ErrorProneReport.java, icu4j/tools/build/src/main/java/com/ibm/icu/dev/tool/errorprone/ErrorProneUtils.java, icu4j/tools/build/src/main/java/com/ibm/icu/dev/tool/errorprone/ParseMavenOutForErrorProne.java, icu4j/tools/build/src/main/resources/com/ibm/icu/dev/tool/errorprone/errorprone.css
1. Turn off the `UnicodeEscape` reporting (in the `pom.xml` file).
2. Filter out `InvalidBlockTag` on ICU custom tags (for example `draft`, `internal`, `icu`).
Errorprone does not allow us to exclude them, so we will filter them out in our code.
3. Also reporting the tags for each error.
For example `FragileCode`, `LikelyError`, `Performance`, `Style`, etc.
4. Assigned `SEVERITY_ICU_PRI?` to the errors voted to be fixed first.
`PRI1` for score in the [2, 3] range, `PRI2` for score in the [1, 2) range.
5. Fixed an issuse with severity Error that was recently introduced (in `CollationMiscTest.java`).
=> ICU-12717 Improve errorprone reporting

docs/userguide/icu/design.md, docs/userguide/icu/howtouseicu.md, docs/userguide/icu/i18n.md, docs/userguide/icu/posix.md, docs/userguide/icu/services.md
Fixed broken links in the docs. Also fixed links like `https://unicode-org.github.io/icu/userguide/strings/index` because it makes sidebar closed and erase current position.
=> ICU-23055 Fix broken links in docs

icu4c/source/common/uloc.cpp, icu4c/source/test/intltest/loctest.cpp, icu4c/source/test/intltest/loctest.h
=> ICU-23131 Bugfix: Set proper end of ByteSink upon early exit

icu4c/source/i18n/messageformat2_formattable.cpp, icu4c/source/i18n/messageformat2_function_registry.cpp, icu4c/source/i18n/messageformat2_function_registry_internal.h, icu4c/source/i18n/tznames.cpp, icu4c/source/i18n/ucln_in.h, icu4c/source/i18n/unicode/messageformat2_formattable.h, icu4c/source/test/intltest/messageformat2test.cpp, icu4c/source/test/intltest/messageformat2test_utils.h, icu4c/source/test/testdata/message2/icu4j/icu-test-functions.json, icu4j/main/core/src/test/resources/com/ibm/icu/dev/test/message2/more-functions.json
Previously, the time zone components of date/time literals were ignored. In order to store the time zone properly for re-formatting, this change also changes the representation of `Formattable` date values to use a `GregorianCalendar` rather than a `UDate`. 
This is a public API change and a design doc can be found in the "ICU 76 API proposal status" document (and was also emailed to the icu-design list on April 29.)
In the TC discussion on May 9, there was some uncertainty about whether to use `GregorianCalendar` or `Calendar` as the return type of `message2::Formattable::getDate()`. I'm leaving it as `GregorianCalendar` for now but can change it if necessary.
=> ICU-22763 MF2: Handle time zones correctly in :datetime

.github/workflows/icu4c.yml, icu4c/source/allinone/Build.Windows.ProjectConfiguration.props, icu4c/source/allinone/Build.Windows.UWP.ProjectConfiguration.props
LanguageStandard is not a property, so setting a property by that name via /p doesn’t actually do anything: the stdcpplatest build is currently C++17.
Note that we want an stdcpplatest build, as that is currently C++23 (preview), and we are using some C++23 features (if available) in #3499.
See also discussion in ICU-TC [2025-06-05](https://docs.google.com/document/d/11yJUWedBIpmq-YNSqqDfgUxcREmlvV0NskYganXkQHA/edit?tab=t.0#heading=h.hqdumez95ye3).
=> ICU-23054 Make the MSVC stdcpplatest build work as intended

icu4j/main/core/src/main/java/com/ibm/icu/segmenter/BoundaryIteratorOfInts.java, icu4j/main/core/src/main/java/com/ibm/icu/segmenter/BoundarySpliterator.java, icu4j/main/core/src/main/java/com/ibm/icu/segmenter/LocalizedSegmenter.java, icu4j/main/core/src/main/java/com/ibm/icu/segmenter/RuleBasedSegmenter.java, icu4j/main/core/src/main/java/com/ibm/icu/segmenter/Segment.java, icu4j/main/core/src/main/java/com/ibm/icu/segmenter/SegmentIterable.java, icu4j/main/core/src/main/java/com/ibm/icu/segmenter/SegmentIterator.java, icu4j/main/core/src/main/java/com/ibm/icu/segmenter/Segmenter.java, icu4j/main/core/src/main/java/com/ibm/icu/segmenter/Segments.java, icu4j/main/core/src/main/java/com/ibm/icu/segmenter/SegmentsImpl.java, icu4j/main/core/src/main/java/com/ibm/icu/text/RuleBasedBreakIterator.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/rbbi/BreakIteratorRules_en_US_TEST.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/segmenter/LocalizedSegmenterTest.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/segmenter/RuleBasedSegmenterTest.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/segmenter/SegmentsTest.java
In order to "modernize" the `BreakIterator` API, this PR introduces a new  wrapper using a more convenient, modern API design around a `Segmenter` interface.
A few of the goals that motivate the new `Segmenter` API:
* Use newer Java features from Java 8 that support the `Stream` API which underlies a functional programming style
* Create instances that are immutable (reduces complexity borne of statefulness; allows user code to be more referentially transparent)
* Create a wrapper class around the iteration. This allows the decoupling of the iteration of a source string from the construction of the BreakIterator such that we can perform iteration over one string in isolation from other strings
* Use interfaces to properly decouple and abstract. APIs built on top of interfaces can allow …
=> ICU-22789 Add Segmenter API to conveniently wrap BreakIterator in ICU4J

icu4j/main/translit/src/main/java/com/ibm/icu/text/BreakTransliterator.java, icu4j/main/translit/src/main/java/com/ibm/icu/text/CaseFoldTransliterator.java, icu4j/main/translit/src/main/java/com/ibm/icu/text/LowercaseTransliterator.java, icu4j/main/translit/src/main/java/com/ibm/icu/text/TitlecaseTransliterator.java, icu4j/main/translit/src/main/java/com/ibm/icu/text/UppercaseTransliterator.java, icu4j/perf-tests/README.txt, icu4j/perf-tests/pom.xml, icu4j/perf-tests/src/main/java/com/ibm/icu/dev/test/perf/BreakTransliteratorPerfTest.java, icu4j/perf-tests/src/main/java/com/ibm/icu/dev/test/perf/CaseFoldTransliteratorPerfTest.java, icu4j/perf-tests/src/main/java/com/ibm/icu/dev/test/perf/LowercaseTransliteratorPerfTest.java, icu4j/perf-tests/src/main/java/com/ibm/icu/dev/test/perf/TitlecaseTransliteratorPerfTest.java, icu4j/perf-tests/src/main/java/com/ibm/icu/dev/test/perf/UppercaseTransliteratorPerfTest.java, icu4j/perf-tests/src/main/java/com/ibm/icu/text/BreakTransliteratorAccess.java, icu4j/pom.xml
LowercaseTransliterator tries to reuse buffers to avoid allocation. Historically, this may have been an important optimization.
However on modern machines you are much more likely to use multiple CPUs, and modern JVMs are very efficient at GC, especially for local temporary data. Contending on a monitor is a big deal nowadays, especially for something so low level and hidden.
I've prepared a benchmark using [JMH](https://github.com/openjdk/jmh) to show the change in scalability:
```
Linux 6.12.13-200.fc41.x86_64 AMD Ryzen 7 3700X 8-Core Processor
JMH version: 1.37
JDK 23.0.2, OpenJDK 64-Bit Server VM, 23.0.2+7
Original `synchronized`:
1 Thread Benchmark                         Mode  Cnt     Score    Error   Units
LowercaseTransliteratorPerf.testSentence  thrpt    5   789.169 ±  2.779 …
```
=> ICU-23061 LowercaseTransliterator has poor scalability due to synchronized state

icu4c/source/common/unicode/utfiterator.h
When the compiler supports C++20 ranges, we use them, so utfiterator.h needs to include the `<range>` standard header file. Follow-up to PR #3499.
I am using the same condition here as in utfiteratortest.cpp.
Found by @AnonymousPC, see https://github.com/unicode-org/icu/pull/3499#issuecomment-3021847302
=> ICU-23004 utfiterator.h include <range>

icu4j/tools/build/src/main/java/com/ibm/icu/dev/tool/errorprone/ErrorProneReport.java, icu4j/tools/build/src/main/java/com/ibm/icu/dev/tool/errorprone/HtmlUtils.java, icu4j/tools/build/src/main/java/com/ibm/icu/dev/tool/errorprone/ParseMavenOutForErrorProne.java
Generating tab-separate-values for easy import in a spreadsheet, and markup to use as reporting from GitHub actions.
=> ICU-12717 Generate errorprone reports as markup and tab-separated-values

icu4c/source/test/testdata/break_rules/line.txt, icu4c/source/test/testdata/break_rules/line_cj.txt, icu4c/source/test/testdata/break_rules/line_loose.txt, icu4c/source/test/testdata/break_rules/line_loose_cj.txt, icu4c/source/test/testdata/break_rules/line_normal.txt, icu4c/source/test/testdata/break_rules/line_normal_cj.txt, icu4j/main/core/src/test/resources/com/ibm/icu/dev/test/rbbi/break_rules/line.txt, icu4j/main/core/src/test/resources/com/ibm/icu/dev/test/rbbi/break_rules/line_cj.txt, icu4j/main/core/src/test/resources/com/ibm/icu/dev/test/rbbi/break_rules/line_loose.txt, icu4j/main/core/src/test/resources/com/ibm/icu/dev/test/rbbi/break_rules/line_loose_cj.txt, icu4j/main/core/src/test/resources/com/ibm/icu/dev/test/rbbi/break_rules/line_normal.txt, icu4j/main/core/src/test/resources/com/ibm/icu/dev/test/rbbi/break_rules/line_normal_cj.txt
Fix exhaustive test failures brought to my attention by @echeran, _e.g._, https://github.com/unicode-org/icu/actions/runs/16234181353/attempts/1. These were broken by https://github.com/unicode-org/icu/pull/3505.
The production implementation is fine (as expected, since it has been eggstensively tested by the old monkeys), but I had an error in the new monkey rules.
=> ICU-23038 Missed a BA to BA HH in the new monkeys

icu4c/source/i18n/unicode/measunit.h, icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/format/MeasureUnitGeneratorTest.java, icu4j/main/core/src/main/java/com/ibm/icu/util/MeasureUnit.java
1. Deprecate ICU4C createMilligramPerDeciliter/getMilligramPerDeciliter, ICU4J MILLIGRAM_PER_DECILITER
2. Remove the @internal from ICU4J METRIC_TON (which was deprecated earlier in ICU 78)
3. Update the MeasureUnit generator handling of replaced APIs to match
Note that items 1,2 are per API [discussion and approval at ICU TC meeting 2025-07-1](https://docs.google.com/document/d/19vv8vxCJiaWZEsR56Ospyr_UbJvl0AW86IZCoMM4bxs/edit?tab=t.0#heading=h.mkq7gt1xbpqj)0
=> ICU-23150 Deprecate C create/getMilligramPerDeciliter, J MILLIGRAM_PER_DECILITER

icu4c/source/common/ucnv_io.cpp, icu4c/source/common/udata.cpp, icu4c/source/common/umapfile.cpp, icu4c/source/data/BUILDRULES.py, icu4c/source/python/icutools/databuilder/request_types.py, icu4c/source/tools/gencfu/gencfu.cpp
These changes fix a condition where a partial cnvalias.icu will cause a segmentation fault. Here are the issues.
1. You have to build the data fast enough in a parallel build where cnvalias.icu is partially written. For the maximum chance at a failure, write just the header. This is a race condition. The changes to BUILDRULES.py should resolve this issue.
2. The code now does a length check of the internal sizes with the actual size. If at any point the calculated data structure size is larger than the actual size, we return a U_INVALID_FORMAT_ERROR. This avoids the segfault in order to fail a little more gracefully and consistently.
3. The udata functionality didn't actually return the size of the file under certain circumstances. This missing functionality was added. This data can be …
=> ICU-23164 Avoid segfault due to incomplete cnvalias.icu

icu4c/source/i18n/messageformat2_data_model.cpp, icu4c/source/i18n/unicode/messageformat2_arguments.h, icu4c/source/i18n/unicode/messageformat2_data_model.h, icu4c/source/i18n/unicode/messageformat2_formattable.h
Make individual members public rather than entire classes, so that private members with templated types don't need to be exported.
=> ICU-23136 Remove template instantiations from MessageFormat-related classes

tools/commit-checker/Pipfile
- workaround for Jira API issue by pinning the API library version.
- This is a temporary fix as surely the API will be turned off someday, so I'm keeping the issue open.
=> ICU-23170 commit-checker: workaround for jira api issue

icu4c/source/i18n/unicode/datefmt.h, icu4c/source/i18n/unicode/numberrangeformatter.h
By removing the use of `__declspec(dllexport)` for private members the need for explicit template instantiations to be able to export these members disappears.
=> ICU-23136 Remove explicit template instantiations for public classes

.github/workflows/release-icu4j-maven.yml, icu4j/main/charset/pom.xml, icu4j/main/icu4j/pom.xml
The central-publishing-maven-plugin disables the regular maven-deploy-plugin, and that prevents publishing snapshots to GitHub.
=> ICU-23148 Separate deploy to Sonatype in a profile

icu4c/source/common/charstr.h, icu4c/source/common/cstr.h, icu4c/source/common/normalizer2impl.h, icu4c/source/common/sharedobject.h, icu4c/source/common/umutex.h, icu4c/source/i18n/measunit_impl.h, icu4c/source/i18n/number_currencysymbols.h, icu4c/source/i18n/number_patternmodifier.h, icu4c/source/i18n/number_usageprefs.h, icu4c/source/i18n/numparse_affixes.h, icu4c/source/i18n/numparse_currency.h, icu4c/source/i18n/olsontz.h, icu4c/source/i18n/units_complexconverter.h, icu4c/source/i18n/units_converter.cpp, icu4c/source/i18n/units_converter.h, icu4c/source/i18n/units_data.cpp, icu4c/source/i18n/units_data.h, icu4c/source/i18n/units_router.h
By removing the use of `__declspec(dllexport)` for private members the need for explicit template instantiations to be able to export these members disappears.
This PR removes such template instantiations from the `icu4c/source/common` internal header files, and then updates everything that's affected by those changes.
=> ICU-23136 Remove explicit template instantiations for common classes

icu4c/source/test/intltest/usettest.cpp, icu4c/source/test/intltest/usettest.h
UnicodeSet has two ways to use variables, both terrible.
1. $variable (with `parseReference` for lexing and `lookup` to get the value) in `SymbolTable`. This is mostly pure textual replacement, so it can produce an operator or a substring that is not a construct of the UnicodeSet grammar (although a property-query has to be entirely within a variable, and the variable has to start _before_ the property-query).
2. Any single code point, with `lookupMatcher`. This happens in the grammar, and must be in a place where the grammar excepts a set, but it happens after de-escaping; in addition, syntax characters can be handled, to varying effect.
Test this mess. Eventually we should fix it, but at least let’s test it in its entire messiness in the meantime.
ALLOW_MANY_COMMITS=meow
=> ICU-23179 Test the behaviour of UnicodeSet parsing with a SymbolTable that uses lookupMatcher

icu4c/source/common/cmemory.h, icu4c/source/common/unicode/localpointer.h, icu4c/source/common/unicode/platform.h, icu4c/source/common/unicode/uobject.h, icu4c/source/common/uresimp.h, icu4c/source/configure, icu4c/source/configure.ac, icu4c/source/i18n/fphdlimp.h, icu4c/source/test/intltest/uobjtest.cpp
This was originally added by commit bb0daf402d17b352f710d8e867ad7bcbcc0dd9d3 as a workaround for HP/UX then not having a standards compliant C++ compiler. But ICU4C made having a standards compliant C++ compiler a hard requirement many years ago, so this no longer serves any purpose and ought to be deleted to simplify the code base.
=> ICU-23190 Delete obsolete U_HAVE_PLACEMENT_NEW

icu4c/source/common/brkiter.cpp, icu4c/source/common/locbased.cpp, icu4c/source/common/locbased.h, icu4c/source/common/unicode/brkiter.h, icu4c/source/i18n/calendar.cpp, icu4c/source/i18n/dcfmtsym.cpp, icu4c/source/i18n/dtfmtsym.cpp, icu4c/source/i18n/format.cpp, icu4c/source/i18n/unicode/calendar.h, icu4c/source/i18n/unicode/dcfmtsym.h, icu4c/source/i18n/unicode/dtfmtsym.h, icu4c/source/i18n/unicode/format.h
This brings a lot of the code that uses `LocaleBased` back to how it was before the refactoring of ICU-23000, accessing the `validLocale` and `actualLocale` fields directly instead of through `LocaleBased` helper functions that now no longer are necessary.
This also makes it possible to remove the `U_LOCALE_BASED()` macro and `LocaleBased` then ends up becoming a trivial class that now contains nothing more than two static helper functions.
The purpose of this PR is to simplify the code, but it should also not have any negative performance impact so with the `/usr/bin/time` test from ICU-23000 averaged over 10 runs it looks like this, with a dramatic change in the user / system time division but no noticeable change in wall time and a tiny reduction in memory consumption:
|| before | …
=> ICU-23005 Replace use of CharString with Locale to simplify the code

icu4c/source/i18n/nfrs.cpp, icu4c/source/i18n/rbnf.cpp, icu4c/source/test/intltest/itrbnf.cpp, icu4c/source/test/intltest/itrbnf.h, icu4j/main/core/src/main/java/com/ibm/icu/text/NFRuleSet.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/format/RBNFParseTest.java
The fuzzer generated test data is very large (4300 lenght unicode string) . Not sure how to minimize it. Depends on the fuzzer to  test.
=> ICU-23184 fix NFRuleSet constructor to return error to avoid null deref later

.github/workflows/icu4c.yml, icu4c/source/common/unicode/unistr.h, icu4c/source/common/unicode/utfiterator.h, icu4c/source/test/intltest/rbbitst.cpp, icu4c/source/test/intltest/utfiteratortest.cpp
Note that the default GCC build is using GCC 11 already, as it is the default on ubuntu 22.04, so we don’t need a separate GCC 11 build. Bump that to 14, which is the most recent we can get on the latest GitHub runner (24.04), and make it build for C++20 and C++23.
Also make clang build for C++23. Try both Clang 18 and 19, as their libc++s have different sets of features (before this change, utfiterator did not compile with Clang 18 in C++23 mode, but compiled with Clang 19).
Fix UB in utfiteratortest.cpp which resulted in a segfault with GCC.
ALLOW_MANY_COMMITS=meow
=> ICU-23189 Test on modern GCC and modern Clang for modern C++

icu4c/source/common/BUILD.bazel, icu4c/source/common/common.vcxproj, icu4c/source/common/common.vcxproj.filters, icu4c/source/common/common_uwp.vcxproj, icu4c/source/common/fixedstring.cpp, icu4c/source/common/fixedstring.h, icu4c/source/common/localebuilder.cpp, icu4c/source/common/locid.cpp, icu4c/source/common/sources.txt, icu4c/source/common/uloc_keytype.cpp, icu4c/source/common/unicode/localebuilder.h, icu4c/source/i18n/fmtable.cpp, icu4c/source/i18n/measunit.cpp, icu4c/source/i18n/measunit_extra.cpp, icu4c/source/i18n/measunit_impl.h, icu4c/source/i18n/number_longnames.cpp, icu4c/source/i18n/tzgnames.cpp, icu4c/source/i18n/tznames_impl.cpp, icu4c/source/i18n/tznames_impl.h, icu4c/source/i18n/unicode/fmtable.h, icu4c/source/i18n/units_converter.cpp, icu4c/source/i18n/units_converter.h, icu4c/source/i18n/units_data.cpp, icu4c/source/i18n/units_data.h, icu4c/source/test/depstest/dependencies.txt, icu4c/source/test/intltest/rbbimonkeytest.h, icu4c/source/test/intltest/strtest.cpp, icu4c/source/test/intltest/strtest.h, icu4c/source/test/intltest/units_data_test.cpp
When `CharString` is used as a data member that never is modified (apart from initialization), it can be replaced with `FixedString` in order to save a little memory (which, in case anyone creates a lot of any of these objects, could add up).
=> ICU-23192 Replace use of CharString with FixedString for data members

.github/workflows/icu_exhaustive_tests.yml
In order to better prevent issues stemming from exhaustive tests that assert the consistency / conformance of locale data ([example](https://github.com/unicode-org/icu/actions/runs/17339113272)), this CI will automatically run exhaustive tests on the PRs that update locale data via resource files.
Currently, the ICU4J / ICU4C tests that run on every push to a PR or merge to `main` don't test the full set of features that are covered by exhaustive tests. Meanwhile, exhaustive tests do not run on all PRs or merges to `main`, but instead on a periodic basis on `main` and on every push to a maintenance branch.
So in total, this PR carves out and enables a narrowly defined middle ground such that we get the full set of test coverage on PRs before we merge, with the knowledge that locale data …
=> ICU-23056 Run CI for exhaustive tests on PRs that update resource files

icu4j/main/core/src/main/java/com/ibm/icu/impl/EraRules.java, icu4j/main/core/src/main/java/com/ibm/icu/text/DateFormatSymbols.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/calendar/JapaneseTest.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/format/DateIntervalFormatTest.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/format/DateTimeGeneratorTest.java
- Rework ICU4J DateFormatSymbols eraNames loading code to match ICU4C rework in [PR #3600 commit 4](https://github.com/unicode-org/icu/pull/3600/commits/a95018f03db53308c0416f01e8d857688cecfee1)
- Now that eraNames data are in map form and EraRules has been updated, rework the eraNames loading code originally added in PR [#3588](https://github.com/unicode-org/icu/pull/3588) so the CalendarSink treats the eraNames data as a table (more natural, and needed in C to remove leaks), then a new initEras function handles the conversion to array and also fills in missing values from parent(s). The latter solves the problem with not loading the narrow modern era names in Japanese, for example.
- Then update tests:
- Remove the logKnownIssue test skips for ICU-23182/ICU-23186
- Update for fixed …
=> ICU-23197 rework J DateFormatSymbols eraNames loading as in C, update tests

docs/processes/cldr-icu.md
Add to the CLDR-ICU integration instructions a note about running the CLDR CompareResolved tool (and analyzing its results) after generating the CLDR production data. This is really a CLDR task but it should be done periodically as part of the CLDR-ICU integration process (when that process is run by someone on the CLDR team) and so is documented here.
=> ICU-23220 Add CLDR-ICU integration note about running CompareResolved

icu4c/source/test/intltest/numbertest_api.cpp, icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
The issue occurred because unit parsing failures were not checked or the status reset. As a result, if one unit failed to parse, the status carried an error and caused all subsequent test cases to fail.  
Changes made:
- Updated expected formats tests for unit aliases in both C++ and Java test files.  
- Refactored test cases to use `unique_ptr` for `MeasureUnit` in C++ and adjusted the constructor in Java.  
- Introduced logging for known issues related to unit aliases.  
Note: This issue still exists — [ICU-23222](https://unicode-org.atlassian.net/browse/ICU-23222).  
[ICU-23222]: https://unicode-org.atlassian.net/browse/ICU-23222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ICU-23105 Update NumberFormatterApiTest/formatUnitsAliases to fail when the units are not parsable

icu4c/source/i18n/measunit_extra.cpp, icu4c/source/i18n/number_longnames.cpp, icu4c/source/test/intltest/numbertest_api.cpp, icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java, icu4j/main/core/src/main/java/com/ibm/icu/impl/number/LongNameHandler.java, icu4j/main/core/src/main/java/com/ibm/icu/impl/units/MeasureUnitImpl.java, icu4j/main/core/src/main/java/com/ibm/icu/impl/units/UnitAliases.java, icu4j/main/core/src/main/java/com/ibm/icu/impl/units/UnitsData.java
In this PR, we **introduced unit aliases** into the **unit parser Trie**.  When the parser **encounters a unit alias** (e.g., **"permillion" → "part-per-1e6"**),  it **ignores the alias**, **replaces it with the canonical unit identifier**,  and then **continues parsing** as if the alias had never appeared.  
This guarantees that **all units with aliases are normalized** to their replacements,  ensuring **consistent parsing results** across both aliases and canonical forms.
```
Input: "meter-permillion-second"
│
▼
[1] Parser reads "meter"
✔ Parsed: [meter]
Remaining: "permillion-second"
[2] Parser reads "permillion"
🔎 Alias detected → replace with "part-per-1e6"
✔ Parsed so far: [meter]
Remaining becomes: "part-per-1e6-second"
[3] Continue parsing...
- "part"   → Parsed: [meter, part]
- …
```
=> ICU-23222 Enhance unit alias handling

icu4c/source/common/static_unicode_sets.cpp, icu4c/source/common/static_unicode_sets.h, icu4c/source/i18n/numparse_affixes.cpp, icu4c/source/i18n/numparse_affixes.h, icu4c/source/i18n/numparse_impl.cpp, icu4c/source/i18n/numparse_impl.h, icu4c/source/i18n/numparse_symbols.cpp, icu4c/source/i18n/numparse_symbols.h, icu4c/source/test/intltest/numbertest_parse.cpp, icu4c/source/test/intltest/numfmtst.cpp, icu4c/source/test/intltest/numfmtst.h, icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/format/NumberFormatTest.java, icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/number/NumberParserTest.java, icu4j/main/core/src/main/java/com/ibm/icu/impl/StaticUnicodeSets.java, icu4j/main/core/src/main/java/com/ibm/icu/impl/number/parse/AffixPatternMatcher.java, icu4j/main/core/src/main/java/com/ibm/icu/impl/number/parse/AffixTokenMatcherFactory.java, icu4j/main/core/src/main/java/com/ibm/icu/impl/number/parse/ApproximatelySignMatcher.java, icu4j/main/core/src/main/java/com/ibm/icu/impl/number/parse/NumberParserImpl.java
This adds support for parsing the approximately sign and fixes the bug observed in ICU-22885.
=> ICU-22885 Add parsing of approximately sign

icu4c/source/test/intltest/dtfmtrtts.cpp, icu4c/source/test/intltest/dtifmtts.cpp, icu4c/source/test/intltest/numbertest_api.cpp, icu4c/source/test/intltest/tsdate.cpp, icu4c/source/test/intltest/tzfmttst.cpp, icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/format/MeasureUnitTest.java, icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/format/NumberFormatTest.java, icu4j/main/common_tests/src/test/java/com/ibm/icu/dev/test/format/TimeZoneFormatTest.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/format/DateIntervalFormatTest.java, icu4j/main/core/src/test/java/com/ibm/icu/dev/test/format/IntlTestDateFormat.java
Removing known issues and TODOs that have been marked as complete in Jira.
- CLDR-18274
- CLDR-18923
- CLDR-18924
- ICU-11052
The following known issues and TODOs are closed, but removing logKnownIssue() (completely) yields test failures:
- CLDR-18901 Disallow [❰❱] in XML element values.
- --> CLDR team fixing remaining cases
- CLDR-18905 How long can narrow be for hour duration (units)?
- --> **change ICU tests**
- ICU-23104 With integration of CLDR 48 m1 data, strange handling of 'part-per-1e9' in number skeletons
- **ICU TODO**
- ICU-23185 became CLDR-18934 Revisit Date time formatting with hz and hv patterns for German
- --> **change ICU tests**
- ICU-23202
- TODO removed in https://github.com/unicode-org/icu/pull/3699
=> ICU-23056 ICU 78 scrub issues
